
addBook('bk/climatic_c2', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/climatic_c2', 'ch_modelVar', "Sampling and Variability");
addSection('bk/climatic_c2', 'sec_modelIntro', "Intro - generalising from data");
addPage_2('bk/african_c2', 'modelIntro1', "Data as representatives", 'interact');
addPage_2('bk/african_c2', 'modelIntro2', "Randomness of data", 'interact');
addPage_2('bk/african_c2', 'modelIntro3', "Modelling randomness", 'interact');
addPage_2('bk/african_c2', 'modelIntro4', "Introduction to the idea of inference", 'static');
addSection('bk/climatic_c2', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp_a1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp2');
addPage_2('en/popSamp', 'popSamp_a3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp3');
addPage_2('en/popSamp', 'popSamp_b4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4', 'en/popSamp', 'v_popSamp_b4');
addPage_2('en/popSamp', 'popSamp_b5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5', 'en/popSamp', 'v_popSamp_b5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addSection('bk/biometric', 'sec_infPopn', "Samples from distributions");
addPage_2('en/infPopn', 'infPopn_b1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn_b1', 'en/infPopn', 'v_infPopn_b1');
addPage_2('en/infPopn', 'infPopn_b2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2', 'en/infPopn', 'v_infPopn_b2');
addPage_2('en/infPopn', 'infPopn_b3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3', 'en/infPopn', 'v_infPopn_b3');
addPage_2('en/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact', 'en/infPopn', 's_infPopn4', 'en/infPopn', 'v_infPopn4');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5', 'en/infPopn', 'v_infPopn5');
addSection('bk/biometric', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity_b1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1', 'en/probDensity', 'v_probDensity_b1');
addPage_2('en/probDensity', 'probDensity_b2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2', 'en/probDensity', 'v_probDensity_b2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3', 'en/probDensity', 'v_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4', 'en/probDensity', 'v_probDensity4');
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5', 'en/probDensity', 'v_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6', 'en/probDensity', 'v_probDensity6');
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7', 'en/probDensity', 'v_probDensity7');
addSection('bk/biometric', 'sec_probSim', "Simulation (optional)");
addPage_2('en/probSim', 'probSim1', "Probability models and simulation", 'interact', 'en/probSim', 's_probSim1', 'en/probSim', 'v_probSim1');
addPage_2('en/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact', 'en/probSim', 's_probSim2', 'en/probSim', 'v_probSim2');
addPage_2('en/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact', 'en/probSim', 's_probSim3', 'en/probSim', 'v_probSim3');
addPage_2('en/probSim', 'probSim_b4', "Assessing unusual features in data", 'interact', 'en/probSim', 's_probSim4', 'en/probSim', 'v_probSim_b4');
addPage_2('en/probSim', 'probSim5', "Random numbers", 'interact', 'en/probSim', 's_probSim5', 'en/probSim', 'v_probSim5');
addPage_2('en/probSim', 'probSim6', "Generating categorical values", 'interact', 'en/probSim', 's_probSim6', 'en/probSim', 'v_probSim6');
addPage_2('en/probSim', 'probSim7', "Generating numerical values", 'interact', 'en/probSim', 's_probSim7', 'en/probSim', 'v_probSim7');

addChapter('bk/climatic_c2', 'ch_sampDistn', "Distributions");
addSection('bk/biometric', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_b1', "Variability of sample statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean_b1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/randomMean', 'randomMean_b6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean_b6', 'en/randomMean', 'v_randomMean_b6');
addPage_2('en/randomMean', 'randomMean_b7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7', 'en/randomMean', 'v_randomMean_b7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite populations", 'interact', 'en/randomMean', 's_randomMean8', 'en/randomMean', 'v_randomMean8');
addSection('bk/biometric', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1', 'en/normalDistn', 'v_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn_b3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn_b3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5', 'en/normalDistn', 'v_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn_b6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6', 'en/normalDistn', 'v_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn_b7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7', 'en/normalDistn', 'v_normalDistn_b7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8', 'en/normalDistn', 'v_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9', 'en/normalDistn', 'v_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10', 'en/normalDistn', 'v_normalDistn10');
addSection('bk/biometric', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1', 'en/randomPropn', 'v_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn_b3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn_b3');
addPage_2('en/randomPropn', 'randomPropn_b4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn_b4', 'en/randomPropn', 'v_randomPropn_b4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'en/randomPropn', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn_b6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn_b6', 'en/randomPropn', 'v_randomPropn_b6');

addChapter('bk/climatic_c2', 'ch_estimation', "Estimating Parameters");
addSection('bk/biometric', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro_b1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro_b1', 'en/estIntro', 'v_estIntro_b1');
addPage_2('en/estIntro', 'estIntro_b2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2', 'en/estIntro', 'v_estIntro_b2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3', 'en/estIntro', 'v_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4', 'en/estIntro', 'v_estIntro4');
addPage_2('en/estIntro', 'estIntro_b5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5', 'en/estIntro', 'v_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6', 'en/estIntro', 'v_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7', 'en/estIntro', 'v_estIntro7');
addSection('bk/general', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1', 'en/seMean', 'v_seMean1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2', 'en/seMean', 'v_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3', 'en/seMean', 'v_seMean3');
addPage_2('en/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean4', 'en/seMean', 'v_seMean4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addPage_2('en/seMean', 'seMean6', "Using SEs to compare estimators", 'interact', 'en/seMean', 's_seMean6', 'en/seMean', 'v_seMean6');
addPage_2('en/seMean', 'seMean7', "More about bias", 'interact', 'en/seMean', 's_seMean7', 'en/seMean', 'v_seMean7');
addSection('bk/climatic_c2', 'sec_sePropn', "Standard error of proportion");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('en/estPropn', 'estPropn_b3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn_b3');
addPage_2('en/estPropn', 'estPropn_b4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4', 'en/estPropn', 'v_estPropn_b4');

addChapter('bk/climatic_c2', 'ch_cis', "Confidence Intervals");
addSection('bk/climatic_c2', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean_m1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean1');
addPage_2('en/ciMean', 'ciMean_b2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2', 'en/ciMean', 'v_ciMean_b2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3', 'en/ciMean', 'v_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4', 'en/ciMean', 'v_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5', 'en/ciMean', 'v_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6', 'en/ciMean', 'v_ciMean6');
addPage_2('en/ciMean', 'ciMean_b7', "Examples", 'static', 'en/ciMean', 's_ciMean_b7', 'en/ciMean', 'v_ciMean_b7');
addSection('bk/climatic_c2', 'sec_ciPropn', "Confidence interval for proportion");
addPage_2('en/estPropn', 'estPropn_b5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5', 'en/estPropn', 'v_estPropn_b5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('en/estPropn', 'estPropn_b7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7', 'en/estPropn', 'v_estPropn_b7');

addChapter('bk/climatic_c2', 'ch_sampSurv', "Sample Surveys");
addSection('bk/climatic_c2', 'sec_sampSchemes', "Sampling schemes");
addPage_2('en/sampPractice', 'sampPractice_b1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1', 'en/sampPractice', 'v_sampPractice_b1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2', 'en/sampPractice', 'v_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3', 'en/sampPractice', 'v_sampPractice3');
addSection('bk/climatic_c2', 'sec_sampErr', "Sampling & non-sampling errors");
addPage_2('en/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4', 'en/sampPractice', 'v_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice_b5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5', 'en/sampPractice', 'v_sampPractice_b5');
addPage_2('en/sampPractice', 'sampPractice_b6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6', 'en/sampPractice', 'v_sampPractice_b6');
addSection('bk/climatic_c2', 'sec_survey', "Conducting a sample survey");
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7', 'en/sampPractice', 'v_sampPractice7');
addSection('bk/climatic_c2', 'sec_sampSize', "Sample size");
addPage_2('en/ciExtra', 'ciExtra_b1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1', 'en/ciExtra', 'v_ciExtra_b1');
addPage_2('en/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2', 'en/ciExtra', 'v_ciExtra2');
addPage_2('en/ciExtra', 'ciExtra_b3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3', 'en/ciExtra', 'v_ciExtra_b3');

addChapter('bk/climatic_c2', 'ch_testProp', "Testing a Proportion");
addSection('bk/biometric', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro_b1', "Inference", 'static', 'en/testIntro', 's_testIntro1', 'en/testIntro', 'v_testIntro_b1');
addPage_2('en/testIntro', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2', 'en/testIntro', 'v_testIntro2');
addPage_2('en/testIntro', 'testIntro_b3', "Simulation to test a proportion", 'interact', 'en/testIntro', 's_testIntro3', 'en/testIntro', 'v_testIntro_b3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4', 'en/testIntro', 'v_testIntro4');
addPage_2('en/testIntro', 'testIntro_b5', "Randomisation tests", 'interact', 'en/testIntro', 's_testIntro5', 'en/testIntro', 'v_testIntro_b5');
addPage_2('en/testIntro', 'testIntro6', "Randomisation test for correlation", 'interact', 'en/testIntro', 's_testIntro6', 'en/testIntro', 'v_testIntro6');
addPage_2('en/testIntro', 'testIntro_b7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7', 'en/testIntro', 'v_testIntro_b7');
addSection('bk/biometric', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'testPropn_b1', "Inference about parameters", 'static', 'en/testPropn', 's_testPropn1', 'en/testPropn', 'v_testPropn_b1');
addPage_2('en/testPropn', 'testPropn_b2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2', 'en/testPropn', 'v_testPropn_b2');
addPage_2('en/testPropn', 'testPropn_b3', "Another example", 'interact', 'en/testPropn', 's_testPropn_b3', 'en/testPropn', 'v_testPropn_b3');
addPage_2('en/testPropn', 'testPropn_b4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn4', 'en/testPropn', 'v_testPropn4');
addPage_2('en/testPropn', 'testPropn_b5', "Normal approximation", 'interact', 'en/testPropn', 's_testPropn_b5', 'en/testPropn', 'v_testPropn_b5');
addPage_2('en/testPropn', 'testPropn6', "Statistical distance", 'static', 'en/testPropn', 's_testPropn6', 'en/testPropn', 'v_testPropn6');
addPage_2('en/testPropn', 'testPropn_b7', "Tests based on statistical distance", 'interact', 'en/testPropn', 's_testPropn_b7', 'en/testPropn', 'v_testPropn_b7');

addChapter('bk/climatic_c2', 'ch_testMean', "Testing a Mean");
addSection('bk/biometric', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean1', "Introduction", 'static', 'en/testMean', 's_testMean1', 'en/testMean', 'v_testMean1');
addPage_2('en/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2', 'en/testMean', 'v_testMean2');
addPage_2('en/testMean', 'testMean_b3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3', 'en/testMean', 'v_testMean_b3');
addPage_2('en/testMean', 'testMean4', "The t distribution", 'interact', 'en/testMean', 's_testMean4', 'en/testMean', 'v_testMean4');
addPage_2('en/testMean', 'testMean5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5', 'en/testMean', 'v_testMean5');
addSection('bk/biometric', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact', 'en/testPValue', 's_testPValue1', 'en/testPValue', 'v_testPValue1');
addPage_2('en/testPValue', 'testPValue_b2', "Consistency with null hypothesis", 'interact', 'en/testPValue', 's_testPValue2', 'en/testPValue', 'v_testPValue_b2');
addPage_2('en/testPValue', 'testPValue3', "Distribution of p-values", 'interact', 'en/testPValue', 's_testPValue3', 'en/testPValue', 'v_testPValue3');
addPage_2('en/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact', 'en/testPValue', 's_testPValue4', 'en/testPValue', 'v_testPValue4');
addPage_2('en/testPValue', 'testPValue_b5', "P-values for other tests", 'interact', 'en/testPValue', 's_testPValue5', 'en/testPValue', 'v_testPValue_b5');

var language = "en";
var logoGif = null;
var homeDir = "bk/climatic_c2";
var versionGif = "images/castClimatic_c2";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "8";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_a': 'African', '_g': 'General', '_b': 'Biometric', '_c': 'Business', '_z': 'Other', '_m': 'Climatic'};
var versions = {};
versions['popSamp1'] = new Array('_a', '_g', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_a', '_g', '_b', '_c');
versions['popSamp4'] = new Array('_b', '_g');
versions['popSamp5'] = new Array('_b', '_g', '_c');
versions['infPopn1'] = new Array('_b', '_g', '_c');
versions['infPopn2'] = new Array('_b', '_g', '_c', '_z');
versions['infPopn3'] = new Array('_b', '_g', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_b', '_g');
versions['probDensity2'] = new Array('_b', '_g', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_b', '_g', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_b', '_g', '_c');
versions['randomMean6'] = new Array('_b', '_g', '_c');
versions['randomMean7'] = new Array('_b', '_g');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_b', '_g', '_c');
versions['normalDistn6'] = new Array('_b', '_g', '_c');
versions['normalDistn7'] = new Array('_b', '_g', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_b', '_g', '_c');
versions['randomPropn4'] = new Array('_b', '_g', '_c');
versions['randomPropn6'] = new Array('_b', '_g', '_c');
versions['estIntro1'] = new Array('_b', '_g', '_c');
versions['estIntro2'] = new Array('_b', '_g', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_b', '_g', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_b', '_g', '_c');
versions['estPropn4'] = new Array('_b', '_g', '_c');
versions['ciMean1'] = new Array('_m', '_g', '_c');
versions['ciMean2'] = new Array('_b', '_g');
versions['ciMean7'] = new Array('_b', '_g', '_c');
versions['estPropn5'] = new Array('_b', '_g', '_c');
versions['estPropn7'] = new Array('_b', '_g', '_c');
versions['sampPractice1'] = new Array('_b', '_g');
versions['sampPractice5'] = new Array('_b', '_g', '_c');
versions['sampPractice6'] = new Array('_b', '_g');
versions['ciExtra1'] = new Array('_b', '_g', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_b', '_g');
versions['testIntro1'] = new Array('_b', '_g');
versions['testIntro3'] = new Array('_b', '_g', '_c');
versions['testIntro5'] = new Array('_b', '_g');
versions['testIntro7'] = new Array('_b', '_g', '_c');
versions['testPropn1'] = new Array('_b', '_g', '_c');
versions['testPropn2'] = new Array('_b', '_g', '_c');
versions['testPropn3'] = new Array('_b', '_g', '_c');
versions['testPropn4'] = new Array('_b', '_g', '_c');
versions['testPropn5'] = new Array('_b', '_g');
versions['testPropn7'] = new Array('_b', '_g');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean2'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_b', '_g');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_b', '_g', '_c');
versions['testPValue5'] = new Array('_b', '_g', '_c');

bookLoaded = true;
