
addBook('bk/businessx', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/generalx', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/generalx', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/generalx', 'ch_intro', "Introduction: About Data");
addSection('bk/businessx', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'l_structures_c1', "Data structures", 'static');
addPage_2('en/structures', 'l_structures_c2', "Variables and individuals", 'interact');
addPage_2('en/structures', 'l_structures_c3', "Types of variable", 'interact');
addPage_2('en/structures', 'l_structures_c4', "Categorical variables and groups", 'interact');
addPage_2('en/structures', 'l_structures_c5', "Meaningful variables", 'interact');
addPage_2('en/structures', 'l_structures_c6', "Time-ordered data", 'static');
addPage_2('en/structures', 'l_structures7', "Multi-level data (advanced)", 'interact');
addPage_2('en/structures', 'l_structures8', "Analysing data at different levels", 'interact');
addSection('bk/businessx', 'sec_variation', "Variation");
addPage_2('en/variation', 'l_variation1', "Signal and noise", 'interact');
addPage_2('en/variation', 'l_variation2', "Natural variability", 'interact');
addPage_2('en/variation', 'l_variation3', "Signal and noise in experiments", 'interact');
addPage_2('en/variation', 'l_variation4', "Variability in survey data", 'interact');
addPage_2('en/variation', 'l_variation_c5', "Explained and unexplained variation", 'static');
addPage_2('en/variation', 'l_variation6', "Predicting future values", 'static');

addChapter('bk/generalx', 'ch_univar', "One Numerical Variable");
addSection('bk/businessx', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'l_valueDisplay_c1', "The basic dot plot", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay_c2', "Jittered and stacked dot plots", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay3', "Crosses or digits", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay_c4', "Basic stem and leaf plot", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay_c5', "Splitting the stems", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay6', "Examples with split stems", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay7', "More about stems and leaves", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay_c8', "Drawing a stem and leaf plot", 'interact');
addSection('bk/generalx', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'l_displayInterp1', "Outliers", 'static');
addPage_2('en/displayInterp', 'l_displayInterp2', "Clusters", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp3', "Names of individuals", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp4', "Distinguishing known groups", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp5', "Back-to-back stem and leaf plots", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp6', "Danger of overinterpretation", 'interact');
addSection('bk/businessx', 'sec_density', "Histograms and density");
addPage_2('en/density', 'l_density1', "Density of values", 'interact');
addPage_2('en/density', 'l_density2', "Histogram with equal class widths", 'interact');
addPage_2('en/density', 'l_density_c3', "Choice of classes", 'interact');
addPage_2('en/density', 'l_density_c4', "Histograms of small data sets", 'interact');
addPage_2('en/density', 'l_density5', "Relative frequency and area", 'interact');
addPage_2('en/density', 'l_density_c6', "Comparing groups", 'interact');
addPage_2('en/density', 'l_density_c7', "Histograms with varying class widths", 'interact');
addPage_2('en/density', 'l_density8', "Mixed class widths (cont)", 'interact');
addPage_2('en/density', 'l_density_c9', "Frequency polygons", 'interact');
addPage_2('en/density', 'l_density_c10', "Kernel density estimates", 'interact');
addSection('bk/generalx', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('en/boxPlot', 'l_boxPlot1', "The need to summarise", 'static');
addPage_2('en/boxPlot', 'l_boxPlot2', "Basic box plot", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot3', "More about box plot shape", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot4', "Displaying outliers", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot5', "Clusters", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot6', "Comparison of groups", 'interact');
addSection('bk/businessx', 'sec_centerSpread', "Describing centre &amp; spread");
addPage_2('en/centerSpread', 'l_centerSpread1', "Ideas of centre and spread", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread2', "Simple measures of centre and spread", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread_c3', "Sample mean", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread4', "Properties of median and mean", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread5', "Standard deviation", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread6', "Rules of thumb for standard deviation", 'static');
addPage_2('en/centerSpread', 'l_centerSpread_c7', "Understanding means and st devns", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread8', "Warnings about mean and standard devn", 'static');
addSection('bk/generalx', 'sec_moreVariation', "More about variation (optional)");
addPage_2('en/moreVariation', 'l_moreVariation1', "Effect of outliers", 'interact');
addPage_2('en/moreVariation', 'l_moreVariation2', "Standard deviation of grouped data", 'interact');
addPage_2('en/moreVariation', 'l_moreVariation3', "Explained variation and predictions", 'interact');
addPage_2('en/moreVariation', 'l_moreVariation4', "Root mean squared error", 'interact');
addPage_2('en/moreVariation', 'l_moreVariation5', "Graphical interpretation of st devn", 'interact');
addSection('bk/generalx', 'sec_percentile', "Proportions and percentiles");
addPage_2('en/percentile', 'l_percentile1', "Cumulative proportions", 'interact');
addPage_2('en/percentile', 'l_percentile2', "Graph of cumulative proportions", 'interact');
addPage_2('en/percentile', 'l_percentile3', "Percentiles", 'interact');
addPage_2('en/percentile', 'l_percentile4', "Displaying percentiles", 'interact');
addPage_2('en/percentile', 'l_percentile5', "Comparing groups", 'interact');
addPage_2('en/percentile', 'l_percentile6', "Better definition of percentiles", 'interact');
addSection('bk/businessx', 'sec_transform', "Transformations");
addPage_2('en/transform', 'l_transform1', "Linear transformations", 'interact');
addPage_2('en/transform', 'l_transform_c2', "Log transformations", 'interact');
addPage_2('en/transform', 'l_transform_c3', "When to use log transform?", 'interact');
addPage_2('en/transform', 'l_transform4', "Power transformations", 'interact');
addPage_2('en/transform', 'l_transform5', "Effect of transformations on displays", 'interact');
addSection('bk/businessx', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'l_counts_c1', "Dot plots for counts", 'interact');
addPage_2('en/counts', 'l_counts_c2', "Histograms for counts", 'interact');
addPage_2('en/counts', 'l_counts3', "Bar charts", 'interact');

addChapter('bk/generalx', 'ch_bivar', "Two Numerical Variables");
addSection('bk/businessx', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'l_scatterplot1', "More than one variable", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot_c2', "Scatterplots", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot3', "Limitations of univariate displays", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot_c4', "Marginal distributions", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot_c5', "Time series", 'interact');
addSection('bk/businessx', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'l_relationship_c1', "Strength of a relationship", 'interact');
addPage_2('en/relationship', 'l_relationship_c2', "Outliers", 'interact');
addPage_2('en/relationship', 'l_relationship3', "Clusters", 'interact');
addPage_2('en/relationship', 'l_relationship_c4', "Dangers of over-interpretation", 'interact');
addSection('bk/businessx', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'l_correlation_c1', "Relationship strength and units of X and Y", 'interact');
addPage_2('en/correlation', 'l_correlation2', "Units-free variables (z-scores)", 'interact');
addPage_2('en/correlation', 'l_correlation3', "Correlation coefficient and its properties", 'interact');
addPage_2('en/correlation', 'l_correlation4', "Scatterplots and the value of r", 'interact');
addPage_2('en/correlation', 'l_correlation5', "Nonlinear relationships", 'interact');
addPage_2('en/correlation', 'l_correlation6', "R does not tell the whole story", 'interact');
addSection('bk/businessx', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'l_leastSqrs_c1', "Predicting Y from X", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs2', "Slope and intercept of straight line", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs3', "Predicting Y from linear model", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs_c4', "Fitted values and residuals", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs5', "Target of small residuals", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs6', "Least squares", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs7', "Outliers", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs_c8', "Residual plots", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs_c9', "Predicting Y and predicting X", 'interact');
addSection('bk/businessx', 'sec_curvature', "Nonlinear relationships");
addPage_2('en/curvature', 'l_curvature_c1', "Transformations and correlation", 'interact');
addPage_2('en/curvature', 'l_curvature_c2', "Transformations and models", 'interact');
addPage_2('en/curvature', 'l_curvature3', "Quadratic models", 'interact');
addPage_2('en/curvature', 'l_curvature_c4', "Quadratic models (cont)", 'interact');
addPage_2('en/curvature', 'l_curvature_c5', "Dangers of extrapolation", 'interact');

addChapter('bk/generalx', 'ch_timeSeries', "Time Series");
addSection('bk/businessx', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'l_timePlot_c1', "Time series plots", 'interact');
addPage_2('en/timePlot', 'l_timePlot_c2', "Time series: trend", 'interact');
addPage_2('en/timePlot', 'l_timePlot3', "Time series: seasonal pattern", 'interact');
addPage_2('en/timePlot', 'l_timePlot_c4', "Time series: autocorrelation", 'interact');
addPage_2('en/timePlot', 'l_timePlot5', "Time series: random fluctuations", 'interact');
addPage_2('en/timePlot', 'l_timePlot6', "Multiple time series", 'interact');
addSection('bk/generalx', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'l_smoothing1', "Moving averages", 'interact');
addPage_2('en/smoothing', 'l_smoothing2', "Robust smoothing with medians", 'interact');
addPage_2('en/smoothing', 'l_smoothing3', "Running medians then means", 'interact');
addPage_2('en/smoothing', 'l_smoothing4', "Exponential smoothing", 'interact');
addPage_2('en/smoothing', 'l_smoothing5', "Lowess smoothing of time series", 'interact');
addPage_2('en/smoothing', 'l_smoothing6', "Lowess smoothing of scatterplots", 'interact');
addSection('bk/generalx', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'l_trend1', "Linear trend", 'interact');
addPage_2('en/trend', 'l_trend2', "Quadratic trend", 'interact');
addPage_2('en/trend', 'l_trend3', "Forecasting", 'interact');
addPage_2('en/trend', 'l_trend4', "Polynomial trend", 'interact');
addPage_2('en/trend', 'l_trend5', "Detrending a time series", 'interact');
addSection('bk/generalx', 'sec_cyclic', "Short-term fluctuations");
addPage_2('en/cyclic', 'l_cyclic1', "Autocorrelation", 'interact');
addPage_2('en/cyclic', 'l_cyclic2', "AR(1) model for autocorrelation", 'interact');
addPage_2('en/cyclic', 'l_cyclic3', "AR(1) model and trend", 'interact');
addPage_2('en/cyclic', 'l_cyclic4', "Trend or autocorrelation?", 'interact');
addPage_2('en/cyclic', 'l_cyclic5', "Cyclical patterns", 'interact');
addSection('bk/generalx', 'sec_seasonal', "Seasonal data");
addPage_2('en/seasonal', 'l_seasonal1', "Seasonal patterns", 'interact');
addPage_2('en/seasonal', 'l_seasonal2', "Smoothing out seasonal variation", 'interact');
addPage_2('en/seasonal', 'l_seasonal3', "Estimating the seasonal effect", 'interact');
addPage_2('en/seasonal', 'l_seasonal4', "Deseasonalised data", 'interact');
addPage_2('en/seasonal', 'l_seasonal5', "Putting it all together", 'interact');
addPage_2('en/seasonal', 'l_seasonal6', "Forecasting with seasonal data", 'interact');
addSection('bk/generalx', 'sec_multiplicative', "Multiplicative models");
addPage_2('en/multiplicative', 'l_multiplicative1', "Multiplicative examples", 'interact');
addPage_2('en/multiplicative', 'l_multiplicative2', "Properties of multiplicative models", 'interact');
addPage_2('en/multiplicative', 'l_multiplicative3', "Forecasting with multiplicative models", 'interact');

addChapter('bk/generalx', 'ch_cat', "Categorical Variables");
addSection('bk/businessx', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'l_freqTable_c1', "Frequency tables", 'interact');
addPage_2('en/freqTable', 'l_freqTable2', "Proportions and percentages", 'interact');
addPage_2('en/freqTable', 'l_freqTable3', "Changes to the categories", 'interact');
addSection('bk/businessx', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'l_univarCat1', "Bar charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat2', "Sorting categories", 'interact');
addPage_2('en/univarCat', 'l_univarCat3', "Pareto diagrams", 'interact');
addPage_2('en/univarCat', 'l_univarCat_c4', "Stacked bar charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat_c5', "Pie charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat_c6', "Comparison of bar and pie charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat7', "Bar charts for quantities", 'interact');
addPage_2('en/univarCat', 'l_univarCat8', "Pie charts for quantities", 'interact');
addPage_2('en/univarCat', 'l_univarCat_c9', "Chartjunk and misleading diagrams", 'static');
addSection('bk/businessx', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'l_groupedCat_c1', "Contingency tables", 'interact');
addPage_2('en/groupedCat', 'l_groupedCat_c2', "Contingency table examples", 'static');
addPage_2('en/groupedCat', 'l_groupedCat_c3', "Proportions within groups", 'interact');
addPage_2('en/groupedCat', 'l_groupedCat_c4', "Bar charts using proportions", 'interact');
addPage_2('en/groupedCat', 'l_groupedCat_c5', "Stacked bar charts", 'interact');
addPage_2('en/groupedCat', 'l_groupedCat_c6', "Time series of categorical distns", 'interact');
addPage_2('en/groupedCat', 'l_groupedCat_c7', "Binary variables", 'interact');
addSection('bk/generalx', 'sec_bivarCat', "Bivariate categorical distributions");
addPage_2('en/bivarCat', 'l_bivarCat1', "3-dimensional bar charts", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat2', "Chartjunk", 'static');
addPage_2('en/bivarCat', 'l_bivarCat3', "3-dimensional bar charts", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat4', "Marginal distributions", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat5', "Conditional distributions", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat6', "More about conditional distributions", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat7', "Conditional vs marginal distns", 'interact');
addSection('bk/businessx', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'l_tableDisplay1', "Gridlines and white space", 'static');
addPage_2('en/tableDisplay', 'l_tableDisplay2', "Layout and annotation", 'static');
addPage_2('en/tableDisplay', 'l_tableDisplay3', "Significant digits and data noise", 'interact');
addPage_2('en/tableDisplay', 'l_tableDisplay_c4', "Meaningful variables", 'interact');
addPage_2('en/tableDisplay', 'l_tableDisplay5', "Reordering rows", 'interact');
addSection('bk/businessx', 'sec_logistic', "Logistic regression");
addPage_2('en/logistic', 'l_logistic1', "Categorical responses", 'interact');
addPage_2('en/logistic', 'l_logistic_c2', "Fitted values and predictions", 'interact');
addPage_2('en/logistic', 'l_logistic3', "Logistic curve", 'interact');
addPage_2('en/logistic', 'l_logistic_c4', "Obtaining a good fit", 'interact');

addChapter('bk/generalx', 'ch_multivar', "Multivariate Data");
addSection('bk/businessx', 'sec_multivariate', "Displaying multivariate data");
addPage_2('en/multivariate', 'l_multivariate_c1', "Representing a third variable", 'interact');
addPage_2('en/multivariate', 'l_multivariate_c2', "Rotating 3D scatterplots", 'interact');
addPage_2('en/multivariate', 'l_multivariate_c3', "Scatterplot matrix and brushing", 'interact');
addPage_2('en/multivariate', 'l_multivariate4', "Brushing example", 'interact');
addPage_2('en/multivariate', 'l_multivariate_c5', "Slicing", 'interact');
addSection('bk/businessx', 'sec_regnGroups', "Groups and regression");
addPage_2('en/regnGroups', 'l_regnGroups1', "Additional variables in regression", 'interact');
addPage_2('en/regnGroups', 'l_regnGroups2', "Displaying groups", 'interact');
addPage_2('en/regnGroups', 'l_regnGroups3', "Regression with grouped data", 'interact');
addPage_2('en/regnGroups', 'l_regnGroups4', "Parallel regression lines", 'interact');
addPage_2('en/regnGroups', 'l_regnGroups5', "Transformed variables and groups", 'interact');
addPage_2('en/regnGroups', 'l_regnGroups6', "Grouping with a numerical variable", 'interact');
addPage_2('en/regnGroups', 'l_regnGroups_c7', "Scatterplot matrix with groups", 'interact');
addSection('bk/generalx', 'sec_multiRegn', "Multiple regression");
addPage_2('en/multiRegn', 'l_multiRegn1', "More than one explanatory variable", 'interact');
addPage_2('en/multiRegn', 'l_multiRegn2', "Multiple regression equation", 'interact');
addPage_2('en/multiRegn', 'l_multiRegn3', "Interpreting coefficients", 'interact');
addPage_2('en/multiRegn', 'l_multiRegn4', "Scatterplot of three variables", 'interact');
addPage_2('en/multiRegn', 'l_multiRegn5', "Displayng the linear equation for Y vs X and Z", 'interact');
addPage_2('en/multiRegn', 'l_multiRegn6', "Fitted values and residuals", 'interact');
addPage_2('en/multiRegn', 'l_multiRegn7', "Least squares estimation", 'interact');
addSection('bk/businessx', 'sec_lurking', "Marginal relationships");
addPage_2('en/lurking', 'l_lurking_c1', "Misleading marginal correlation", 'interact');
addPage_2('en/lurking', 'l_lurking2', "Misleading marginal difference in means", 'interact');
addPage_2('en/lurking', 'l_lurking_c3', "Simpsons paradox", 'interact');
addPage_2('en/lurking', 'l_lurking_c4', "Explanation of Simpsons paradox", 'interact');

addChapter('bk/generalx', 'ch_sample', "Sampling and Variability");
addSection('bk/businessx', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'l_popSamp_c1', "Sampling from a population", 'interact');
addPage_2('en/popSamp', 'l_popSamp_c2', "Variability in a sample", 'interact');
addPage_2('en/popSamp', 'l_popSamp_c3', "Sampling error", 'interact');
addPage_2('en/popSamp', 'l_popSamp4', "Sampling error and sample size", 'interact');
addPage_2('en/popSamp', 'l_popSamp_c5', "Sampling with and without replacement", 'interact');
addPage_2('en/popSamp', 'l_popSamp6', "Generating random numbers", 'interact');
addPage_2('en/popSamp', 'l_popSamp7', "Selecting a random sample", 'interact');
addSection('bk/businessx', 'sec_infPopn', "Abstract infinite populations");
addPage_2('en/infPopn', 'l_infPopn_c1', "Data as representatives", 'static');
addPage_2('en/infPopn', 'l_infPopn_c2', "Randomness of data", 'interact');
addPage_2('en/infPopn', 'l_infPopn3', "Infinite populations", 'interact');
addPage_2('en/infPopn', 'l_infPopn_c4', "Information from a single sample", 'interact');
addSection('bk/businessx', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'l_probDensity1', "Finite populations", 'interact');
addPage_2('en/probDensity', 'l_probDensity_c2', "Probabilities and population proportions", 'interact');
addPage_2('en/probDensity', 'l_probDensity_c3', "Law of large numbers", 'interact');
addPage_2('en/probDensity', 'l_probDensity4', "Bar charts of discrete probabilities &mdash; discrete", 'interact');
addPage_2('en/probDensity', 'l_probDensity5', "Probability density functions", 'interact');
addPage_2('en/probDensity', 'l_probDensity6', "Normal distributions", 'interact');
addPage_2('en/probDensity', 'l_probDensity_c7', "Fitting a normal distribution to data", 'interact');
addPage_2('en/probDensity', 'l_probDensity8', "Probability and area under the pdf", 'interact');
addSection('bk/businessx', 'sec_probSim', "Simulation (optional)");
addPage_2('en/probSim', 'l_probSim1', "Probability models and simulation", 'interact');
addPage_2('en/probSim', 'l_probSim2', "Simulation: Will the best team win?", 'interact');
addPage_2('en/probSim', 'l_probSim3', "Simulation: Will the best team win?", 'interact');
addPage_2('en/probSim', 'l_probSim_c4', "Assessing unusual features in data", 'interact');
addPage_2('en/probSim', 'l_probSim5', "Random numbers", 'interact');
addPage_2('en/probSim', 'l_probSim_c6', "Generating categorical values", 'interact');
addPage_2('en/probSim', 'l_probSim7', "Generating numerical values", 'interact');
addSection('bk/businessx', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'l_randomMean_c1', "Parameters and statistics", 'interact');
addPage_2('en/randomMean', 'l_randomMean2', "Distribution of sample mean", 'interact');
addPage_2('en/randomMean', 'l_randomMean3', "Means from normal populations", 'interact');
addPage_2('en/randomMean', 'l_randomMean4', "Large-sample normality of means", 'interact');
addPage_2('en/randomMean', 'l_randomMean_c5', "Distribution of mean from a sample", 'static');
addPage_2('en/randomMean', 'l_randomMean6', "Requirement of independence", 'interact');
addPage_2('en/randomMean', 'l_randomMean7', "Sampling from finite populations", 'interact');
addSection('bk/businessx', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'l_normalDistn_c1', "Importance of normal distributions", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn2', "Shape of normal distributions", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn3', "Sketching a normal distribution", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn4', "Some normal probabilities", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn5', "Z-scores", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn6', "Probabilities from z-scores", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn_c7', "Finding other normal probabilities", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn8', "Finding normal quantiles", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn9', "Normal probability plots", 'interact');
addSection('bk/businessx', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'l_randomPropn_c1', "Distributions of counts and proportions", 'interact');
addPage_2('en/randomPropn', 'l_randomPropn2', "Family of binomial distributions", 'interact');
addPage_2('en/randomPropn', 'l_randomPropn_c3', "Binomial probability examples", 'static');
addPage_2('en/randomPropn', 'l_randomPropn4', "Normal approximation to binomial", 'interact');
addPage_2('en/randomPropn', 'l_randomPropn_c5', "Normal approximation examples", 'static');
addSection('bk/generalx', 'sec_sampPractice', "Sampling in practice");
addPage_2('en/sampPractice', 'l_sampPractice1', "Stratified sampling", 'interact');
addPage_2('en/sampPractice', 'l_sampPractice2', "Strata with different variability", 'interact');
addPage_2('en/sampPractice', 'l_sampPractice3', "Cluster sampling", 'interact');
addPage_2('en/sampPractice', 'l_sampPractice4', "Loss of accuracy with cluster sampling", 'interact');
addPage_2('en/sampPractice', 'l_sampPractice5', "Two-stage sampling", 'interact');
addPage_2('en/sampPractice', 'l_sampPractice6', "Cost and accuracy of two-stage sampling", 'interact');
addSection('bk/generalx', 'sec_controlChart', "Control charts");
addPage_2('en/controlChart', 'l_controlChart1', "Run charts", 'interact');
addPage_2('en/controlChart', 'l_controlChart2', "Control limits", 'interact');
addPage_2('en/controlChart', 'l_controlChart3', "Other signals of being out-of-control", 'interact');
addPage_2('en/controlChart', 'l_controlChart4', "False alarms", 'interact');
addPage_2('en/controlChart', 'l_controlChart5', "Examples of run charts", 'interact');
addPage_2('en/controlChart', 'l_controlChart6', "Control charts for means", 'interact');
addPage_2('en/controlChart', 'l_controlChart7', "Control charts for ranges", 'interact');
addPage_2('en/controlChart', 'l_controlChart8', "Cause-and-effect (fishbone) diagram", 'interact');

addChapter('bk/businessx', 'ch_expDesign', "Designed Experiments");
addSection('bk/businessx', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'l_causal1', "Causal and non-causal relationships", 'static');
addPage_2('en/causal', 'l_causal_c2', "Observational and experimental data", 'interact');
addPage_2('en/causal', 'l_causal3', "Data collection and causality", 'interact');
addSection('bk/businessx', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'l_designIntro_c1', "Variable experimental units", 'interact');
addPage_2('en/designIntro', 'l_designIntro_c2', "A badly designed experiment", 'interact');
addPage_2('en/designIntro', 'l_designIntro_c3', "Randomisation", 'interact');
addPage_2('en/designIntro', 'l_designIntro_c4', "Mechanics of randomisation", 'interact');
addPage_2('en/designIntro', 'l_designIntro5', "Replication", 'static');
addPage_2('en/designIntro', 'l_designIntro6', "Blocking", 'interact');
addPage_2('en/designIntro', 'l_designIntro_c7', "Benifits of blocking", 'interact');

addChapter('bk/generalx', 'ch_estimation', "Estimating Parameters");
addSection('bk/businessx', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'l_estIntro_c1', "Interest in populations", 'static');
addPage_2('en/estIntro', 'l_estIntro_c2', "Interest in parameters", 'static');
addPage_2('en/estIntro', 'l_estIntro_c3', "Estimation error", 'interact');
addSection('bk/businessx', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'l_seMean_c1', "Error distribution for mean", 'interact');
addPage_2('en/seMean', 'l_seMean2', "Standard error when population SD is known", 'interact');
addPage_2('en/seMean', 'l_seMean_c3', "Standard error when population SD is unknown", 'static');
addPage_2('en/seMean', 'l_seMean4', "Standard error vs standard deviation", 'interact');
addPage_2('en/seMean', 'l_seMean_c5', "Using SEs to compare estimators", 'interact');
addPage_2('en/seMean', 'l_seMean6', "More about bias", 'interact');
addSection('bk/businessx', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'l_ciMean1', "Confidence interval for a mean, known SD", 'interact');
addPage_2('en/ciMean', 'l_ciMean2', "Confidence level", 'interact');
addPage_2('en/ciMean', 'l_ciMean3', "Confidence level if sigma is replaced by s", 'interact');
addPage_2('en/ciMean', 'l_ciMean4', "Adjusting CI width for unknown popn SD", 'interact');
addPage_2('en/ciMean', 'l_ciMean5', "Confidence interval for mean, unknown popn SD", 'interact');
addPage_2('en/ciMean', 'l_ciMean6', "Properties of 95% confidence interval", 'interact');
addPage_2('en/ciMean', 'l_ciMean_c7', "Examples", 'static');
addSection('bk/businessx', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'l_estPropn1', "Estimating a proportion", 'interact');
addPage_2('en/estPropn', 'l_estPropn_c2', "Error distribution", 'interact');
addPage_2('en/estPropn', 'l_estPropn3', "Normal approximation to error distribution", 'interact');
addPage_2('en/estPropn', 'l_estPropn_c4', "Standard error examples", 'static');
addPage_2('en/estPropn', 'l_estPropn_c5', "Confidence interval for proportion", 'static');
addPage_2('en/estPropn', 'l_estPropn6', "Properties of 95% CI for proportion", 'interact');
addPage_2('en/estPropn', 'l_estPropn_c7', "Confidence interval examples", 'static');
addSection('bk/businessx', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'l_ciExtra1', "Maximum standard error for proportion", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra2', "Margin of error", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra_c3', "Sample size for estimating mean", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra4', "Sample size for estimating proportion", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra5', "Other confidence levels", 'interact');
addSection('bk/businessx', 'sec_estOther', "Simulation and bootstrap");
addPage_2('en/estOther', 'l_estOther1', "Error distribution by simulation", 'interact');
addPage_2('en/estOther', 'l_estOther_c2', "Simulation from normal approximation", 'interact');
addPage_2('en/estOther', 'l_estOther3', "Bootstrap error distribution", 'interact');
addPage_2('en/estOther', 'l_estOther4', "Standard error of correlation from bootstrap", 'interact');
addPage_2('en/estOther', 'l_estOther_c5', "Confidence interval from error distribution", 'interact');

addChapter('bk/generalx', 'ch_testing', "Testing Hypotheses");
addSection('bk/businessx', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'l_testIntro1', "Soccer league simulation", 'interact');
addPage_2('en/testIntro', 'l_testIntro_c2', "Simulation to test a proportion", 'interact');
addPage_2('en/testIntro', 'l_testIntro3', "Simulation to test a mean", 'interact');
addPage_2('en/testIntro', 'l_testIntro4', "Randomisation tests", 'interact');
addPage_2('en/testIntro', 'l_testIntro5', "Soccer league randomisation", 'interact');
addSection('bk/businessx', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'l_testPropn_c1', "P-value for testing proportion", 'interact');
addPage_2('en/testPropn', 'l_testPropn_c2', "Another example of testing a proportion", 'interact');
addPage_2('en/testPropn', 'l_testPropn_c3', "Two-tailed tests", 'interact');
addPage_2('en/testPropn', 'l_testPropn4', "Tests based on normal approximation", 'interact');
addSection('bk/businessx', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'l_testMean1', "Tests based on statistical distance", 'interact');
addPage_2('en/testMean', 'l_testMean2', "Example (known sigma)", 'interact');
addPage_2('en/testMean', 'l_testMean3', "Test statistic (unknown sigma)", 'interact');
addPage_2('en/testMean', 'l_testMean4', "The t distribution", 'interact');
addPage_2('en/testMean', 'l_testMean_c5', "The t test for a mean", 'interact');
addSection('bk/generalx', 'sec_decision', "Decisions and significance");
addPage_2('en/decision', 'l_decision1', "Decisions and significance level", 'interact');
addPage_2('en/decision', 'l_decision2', "P-values and decision rules", 'interact');
addPage_2('en/decision', 'l_decision3', "Sample size and power", 'interact');
addSection('bk/businessx', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'l_testPValue_c1', "Null and alternative hypotheses", 'interact');
addPage_2('en/testPValue', 'l_testPValue_c2', "P-value and consistency with null hypothesis", 'interact');
addPage_2('en/testPValue', 'l_testPValue3', "Distribution of p-values", 'interact');
addPage_2('en/testPValue', 'l_testPValue_c4', "P-values for other tests", 'interact');

addChapter('bk/generalx', 'ch_twoGroups', "Comparing Groups");
addSection('bk/businessx', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'l_twoGroupModel_c1', "Interest in underlying population", 'static');
addPage_2('en/twoGroupModel', 'l_twoGroupModel_c2', "Model for two groups", 'interact');
addPage_2('en/twoGroupModel', 'l_twoGroupModel3', "Parameters of the normal model", 'interact');
addPage_2('en/twoGroupModel', 'l_twoGroupModel_c4', "Parameter estimates", 'interact');
addPage_2('en/twoGroupModel', 'l_twoGroupModel_c5', "Difference between means", 'interact');
addSection('bk/generalx', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'l_sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff2', "Sums and differences", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff4', "Probabilities for sums and differences", 'static');
addSection('bk/businessx', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'l_twoGroupInf_c1', "Distn of difference between means", 'interact');
addPage_2('en/twoGroupInf', 'l_twoGroupInf_c2', "Distribution of estimation error", 'static');
addPage_2('en/twoGroupInf', 'l_twoGroupInf_c3', "CI for difference between means", 'static');
addPage_2('en/twoGroupInf', 'l_twoGroupInf4', "Properties of confidence interval", 'interact');
addPage_2('en/twoGroupInf', 'l_twoGroupInf_c5', "Testing a hypothesis", 'static');
addPage_2('en/twoGroupInf', 'l_twoGroupInf6', "Properties of hypothesis test", 'interact');
addPage_2('en/twoGroupInf', 'l_twoGroupInf_c7', "One-tailed tests", 'static');
addPage_2('en/twoGroupInf', 'l_twoGroupInf8', "Properties of one-tailed tests", 'interact');
addSection('bk/businessx', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'l_twoGroupPropn_c1', "Estimating difference between proportions", 'static');
addPage_2('en/twoGroupPropn', 'l_twoGroupPropn2', "Distribution of difference in proportions", 'interact');
addPage_2('en/twoGroupPropn', 'l_twoGroupPropn_c3', "CI for difference in proportions", 'static');
addPage_2('en/twoGroupPropn', 'l_twoGroupPropn_c4', "Testing for difference in probabilities", 'static');
addSection('bk/businessx', 'sec_testPaired', "Paired t test");
addPage_2('en/testPaired', 'l_testPaired_c1', "Analysis of differences", 'static');
addPage_2('en/testPaired', 'l_testPaired2', "Benefits of pairing", 'interact');
addPage_2('en/testPaired', 'l_testPaired_c3', "Paired t-test", 'interact');
addPage_2('en/testPaired', 'l_testPaired4', "Pairing and experimental design", 'interact');
addSection('bk/businessx', 'sec_multiGroup', "Comparing several means");
addPage_2('en/multiGroup', 'l_multiGroup1', "Model with common standard deviation", 'interact');
addPage_2('en/multiGroup', 'l_multiGroup2', "Estimate of common standard deviation", 'interact');
addPage_2('en/multiGroup', 'l_multiGroup_c3', "Inference about two groups", 'static');
addPage_2('en/multiGroup', 'l_multiGroup4', "Assessing differences between groups", 'interact');
addPage_2('en/multiGroup', 'l_multiGroup5', "Sums of squares", 'interact');
addPage_2('en/multiGroup', 'l_multiGroup_c6', "Coefficient of determination", 'static');
addPage_2('en/multiGroup', 'l_multiGroup7', "Test for differences between groups", 'interact');
addPage_2('en/multiGroup', 'l_multiGroup_c8', "Examples", 'static');

addChapter('bk/generalx', 'ch_regnInference', "Regression Inference");
addSection('bk/businessx', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'l_regnModel_c1', "Histogram of Y for each X", 'interact');
addPage_2('en/regnModel', 'l_regnModel_c2', "Distribution of Y for each X", 'interact');
addPage_2('en/regnModel', 'l_regnModel3', "Normal linear model", 'interact');
addPage_2('en/regnModel', 'l_regnModel4', "Band containing 95% of crosses", 'interact');
addPage_2('en/regnModel', 'l_regnModel_c5', "Model parameters", 'interact');
addSection('bk/businessx', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'l_regnEst_c1', "Point estimates of slope and intercept", 'interact');
addPage_2('en/regnEst', 'l_regnEst_c2', "Estimating the error standard devn", 'interact');
addPage_2('en/regnEst', 'l_regnEst3', "Distribution of least squares estimates", 'interact');
addPage_2('en/regnEst', 'l_regnEst_c4', "Standard error of least squares slope", 'static');
addPage_2('en/regnEst', 'l_regnEst5', "95% confidence interval for slope", 'interact');
addPage_2('en/regnEst', 'l_regnEst6', "Standard error and data collection", 'interact');
addSection('bk/businessx', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'l_regnTest_c1', "Importance of zero slope", 'interact');
addPage_2('en/regnTest', 'l_regnTest_c2', "Importance of zero slope", 'interact');
addPage_2('en/regnTest', 'l_regnTest_c3', "T-test examples", 'static');
addPage_2('en/regnTest', 'l_regnTest4', "Strength of evidence and relationship", 'static');
addPage_2('en/regnTest', 'l_regnTest5', "Properties of p-values", 'interact');
addSection('bk/businessx', 'sec_regnPred', "Predicting the response");
addPage_2('en/regnPred', 'l_regnPred_c1', "Estimated response distn at X", 'interact');
addPage_2('en/regnPred', 'l_regnPred2', "Variability of estimate at X", 'interact');
addPage_2('en/regnPred', 'l_regnPred3', "Variability of estimate at X (cont)", 'interact');
addPage_2('en/regnPred', 'l_regnPred4', "Estimating the mean vs prediction", 'interact');
addPage_2('en/regnPred', 'l_regnPred5', "Confidence and prediction intervals", 'interact');
addSection('bk/businessx', 'sec_regnProblem', "Linear model assumptions");
addPage_2('en/regnProblem', 'l_regnProblem1', "Assumptions in a normal linear model", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem2', "Curvature &mdash; transforming X", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem3', "Curvature and non-constant variance &mdash; transforming Y", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem_c4', "Transformations and prediction", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem_c5', "Prediction intervals and transformations", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem6', "Standardised residuals", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem7', "Outliers and leverage", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem8', "Non-normal errors", 'interact');
addPage_2('en/regnProblem', 'l_regnProblem9', "Correlated errors  (optional)", 'interact');

addChapter('bk/generalx', 'ch_independence', "Independence");
addSection('bk/businessx', 'sec_prob', "Probability and applications");
addPage_2('en/prob', 'l_prob_c1', "Joint probabilities", 'interact');
addPage_2('en/prob', 'l_prob_c2', "Marginal probabilities", 'interact');
addPage_2('en/prob', 'l_prob_c3', "Conditional probabilities", 'interact');
addPage_2('en/prob', 'l_prob4', "Graphical display of probabilities", 'interact');
addPage_2('en/prob', 'l_prob_c5', "Calculations with probabilities", 'interact');
addPage_2('en/prob', 'l_prob_c6', "Calculations with probabilities (cont)", 'interact');
addSection('bk/businessx', 'sec_indep', "Independence");
addPage_2('en/indep', 'l_indep_c1', "Association and independence", 'static');
addPage_2('en/indep', 'l_indep2', "More about independence", 'interact');
addPage_2('en/indep', 'l_indep_c3', "Independence from samples", 'static');
addPage_2('en/indep', 'l_indep4', "Chi-squared statistic", 'interact');
addPage_2('en/indep', 'l_indep5', "Chi-squared distribution", 'interact');
addPage_2('en/indep', 'l_indep6', "P-value for chi-squared test", 'interact');
addPage_2('en/indep', 'l_indep_c7', "Examples of tests for independence", 'static');
addPage_2('en/indep', 'l_indep_c8', "Examples of tests comparing groups", 'static');

var language = "en";
var logoGif = null;
var homeDir = "bk/businessx";
var versionGif = "../business/images/castBusiness";
var isLecturingVersion = true;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_c': 'Business', '_g': 'General', '_a': 'African', '_b': 'Biometric', '_m': 'Climatic', '_z': 'Other'};
var versions = {};
versions['l_structures1'] = new Array('_c', '_g', '_a', '_b');
versions['l_structures2'] = new Array('_c', '_g', '_a');
versions['l_structures3'] = new Array('_c', '_g', '_a', '_b');
versions['l_structures4'] = new Array('_c', '_g');
versions['l_structures5'] = new Array('_c', '_g', '_a');
versions['l_structures6'] = new Array('_c', '_g', '_b');
versions['l_structures7'] = new Array('_g', '_b');
versions['l_structures8'] = new Array('_g', '_b');
versions['l_variation5'] = new Array('_c', '_g');
versions['l_valueDisplay1'] = new Array('_c', '_g', '_b');
versions['l_valueDisplay2'] = new Array('_c', '_g', '_b');
versions['l_valueDisplay4'] = new Array('_c', '_g', '_b');
versions['l_valueDisplay5'] = new Array('_c', '_g');
versions['l_valueDisplay8'] = new Array('_c', '_g');
versions['l_displayInterp3'] = new Array('_g', '_b');
versions['l_density3'] = new Array('_c', '_g');
versions['l_density4'] = new Array('_c', '_g', '_b');
versions['l_density6'] = new Array('_c', '_g', '_b');
versions['l_density7'] = new Array('_c', '_g', '_b');
versions['l_density9'] = new Array('_c', '_g');
versions['l_density10'] = new Array('_c', '_g');
versions['l_centerSpread1'] = new Array('_g', '_b');
versions['l_centerSpread2'] = new Array('_g', '_b');
versions['l_centerSpread3'] = new Array('_c', '_g', '_b');
versions['l_centerSpread7'] = new Array('_c', '_g');
versions['l_transform1'] = new Array('_g', '_b');
versions['l_transform2'] = new Array('_c', '_g');
versions['l_transform3'] = new Array('_c', '_g');
versions['l_counts1'] = new Array('_c', '_g');
versions['l_counts2'] = new Array('_c', '_g');
versions['l_scatterplot2'] = new Array('_c', '_g');
versions['l_scatterplot4'] = new Array('_c', '_g');
versions['l_scatterplot5'] = new Array('_c', '_g');
versions['l_relationship1'] = new Array('_c', '_g');
versions['l_relationship2'] = new Array('_c', '_g');
versions['l_relationship4'] = new Array('_c', '_g');
versions['l_correlation1'] = new Array('_c', '_g', '_b');
versions['l_leastSqrs1'] = new Array('_c', '_g', '_b');
versions['l_leastSqrs4'] = new Array('_c', '_g');
versions['l_leastSqrs8'] = new Array('_c', '_g');
versions['l_leastSqrs9'] = new Array('_c', '_g');
versions['l_curvature1'] = new Array('_c', '_g');
versions['l_curvature2'] = new Array('_c', '_g');
versions['l_curvature4'] = new Array('_c', '_g');
versions['l_curvature5'] = new Array('_c', '_g');
versions['l_timePlot1'] = new Array('_c', '_g', '_b');
versions['l_timePlot2'] = new Array('_c', '_g');
versions['l_timePlot3'] = new Array('_g', '_b');
versions['l_timePlot4'] = new Array('_c', '_g', '_b');
versions['l_timePlot5'] = new Array('_g', '_b');
versions['l_seasonal1'] = new Array('_g', '_m', '_z');
versions['l_seasonal2'] = new Array('_g', '_m', '_z');
versions['l_seasonal3'] = new Array('_g', '_m', '_z');
versions['l_seasonal4'] = new Array('_g', '_m', '_z');
versions['l_seasonal5'] = new Array('_g', '_m', '_z');
versions['l_seasonal6'] = new Array('_g', '_m', '_z');
versions['l_freqTable1'] = new Array('_c', '_g');
versions['l_freqTable2'] = new Array('_g', '_a', '_b');
versions['l_univarCat1'] = new Array('_g', '_a', '_b');
versions['l_univarCat4'] = new Array('_c', '_g', '_b');
versions['l_univarCat5'] = new Array('_c', '_g', '_b');
versions['l_univarCat6'] = new Array('_c', '_g', '_b');
versions['l_univarCat8'] = new Array('_g', '_b');
versions['l_univarCat9'] = new Array('_c', '_g', '_b');
versions['l_groupedCat1'] = new Array('_c', '_g');
versions['l_groupedCat2'] = new Array('_c', '_g', '_b');
versions['l_groupedCat3'] = new Array('_c', '_g');
versions['l_groupedCat4'] = new Array('_c', '_g', '_b');
versions['l_groupedCat5'] = new Array('_c', '_g', '_b');
versions['l_groupedCat6'] = new Array('_c', '_g');
versions['l_groupedCat7'] = new Array('_c', '_g');
versions['l_tableDisplay4'] = new Array('_c', '_g');
versions['l_logistic2'] = new Array('_c', '_g', '_b');
versions['l_logistic4'] = new Array('_c', '_g', '_b');
versions['l_multivariate1'] = new Array('_c', '_g', '_b');
versions['l_multivariate2'] = new Array('_c', '_g');
versions['l_multivariate3'] = new Array('_c', '_g');
versions['l_multivariate5'] = new Array('_c', '_g');
versions['l_regnGroups7'] = new Array('_c', '_g');
versions['l_lurking1'] = new Array('_c', '_g', '_b');
versions['l_lurking2'] = new Array('_g', '_b');
versions['l_lurking3'] = new Array('_c', '_g');
versions['l_lurking4'] = new Array('_c', '_g');
versions['l_popSamp1'] = new Array('_c', '_g', '_a', '_b');
versions['l_popSamp2'] = new Array('_c', '_g');
versions['l_popSamp3'] = new Array('_c', '_g', '_a', '_b');
versions['l_popSamp4'] = new Array('_g', '_b');
versions['l_popSamp5'] = new Array('_c', '_g', '_b');
versions['l_infPopn1'] = new Array('_c', '_g', '_b');
versions['l_infPopn2'] = new Array('_c', '_g', '_b', '_z');
versions['l_infPopn4'] = new Array('_c', '_g');
versions['l_probDensity2'] = new Array('_c', '_g', '_b');
versions['l_probDensity3'] = new Array('_c', '_g', '_b');
versions['l_probDensity7'] = new Array('_c', '_g');
versions['l_probSim4'] = new Array('_c', '_g', '_b');
versions['l_probSim6'] = new Array('_c', '_g');
versions['l_randomMean1'] = new Array('_c', '_g', '_b');
versions['l_randomMean5'] = new Array('_c', '_g', '_b');
versions['l_randomMean6'] = new Array('_g', '_b');
versions['l_normalDistn1'] = new Array('_c', '_g');
versions['l_normalDistn7'] = new Array('_c', '_g', '_b');
versions['l_randomPropn1'] = new Array('_c', '_g');
versions['l_randomPropn3'] = new Array('_c', '_g', '_b');
versions['l_randomPropn5'] = new Array('_c', '_g', '_b');
versions['l_sampPractice1'] = new Array('_g', '_b');
versions['l_sampPractice2'] = new Array('_g', '_b');
versions['l_causal2'] = new Array('_c', '_g', '_b');
versions['l_designIntro1'] = new Array('_c', '_g');
versions['l_designIntro2'] = new Array('_c', '_g');
versions['l_designIntro3'] = new Array('_c', '_g');
versions['l_designIntro4'] = new Array('_c', '_g', '_b');
versions['l_designIntro7'] = new Array('_c', '_g');
versions['l_estIntro1'] = new Array('_c', '_g', '_b');
versions['l_estIntro2'] = new Array('_c', '_g', '_b');
versions['l_estIntro3'] = new Array('_c', '_g', '_b');
versions['l_seMean1'] = new Array('_c', '_g', '_b');
versions['l_seMean2'] = new Array('_g', '_b');
versions['l_seMean3'] = new Array('_c', '_g', '_b');
versions['l_seMean5'] = new Array('_c', '_g', '_b');
versions['l_ciMean1'] = new Array('_g', '_b');
versions['l_ciMean7'] = new Array('_c', '_g', '_b');
versions['l_estPropn2'] = new Array('_c', '_g', '_b');
versions['l_estPropn4'] = new Array('_c', '_g', '_b');
versions['l_estPropn5'] = new Array('_c', '_g', '_b');
versions['l_estPropn7'] = new Array('_c', '_g', '_b');
versions['l_ciExtra3'] = new Array('_c', '_g');
versions['l_ciExtra4'] = new Array('_g', '_b');
versions['l_estOther2'] = new Array('_c', '_g');
versions['l_estOther4'] = new Array('_g', '_b');
versions['l_estOther5'] = new Array('_c', '_g');
versions['l_testIntro2'] = new Array('_c', '_g', '_b');
versions['l_testIntro4'] = new Array('_g', '_b');
versions['l_testPropn1'] = new Array('_c', '_g', '_b');
versions['l_testPropn2'] = new Array('_c', '_g', '_b');
versions['l_testPropn3'] = new Array('_c', '_g');
versions['l_testPropn4'] = new Array('_g', '_b');
versions['l_testMean5'] = new Array('_c', '_g');
versions['l_testPValue1'] = new Array('_c', '_g');
versions['l_testPValue2'] = new Array('_c', '_g', '_b');
versions['l_testPValue4'] = new Array('_c', '_g', '_b');
versions['l_twoGroupModel1'] = new Array('_c', '_g', '_b');
versions['l_twoGroupModel2'] = new Array('_c', '_g', '_b');
versions['l_twoGroupModel4'] = new Array('_c', '_g');
versions['l_twoGroupModel5'] = new Array('_c', '_g');
versions['l_twoGroupInf1'] = new Array('_c', '_g');
versions['l_twoGroupInf2'] = new Array('_c', '_g', '_b');
versions['l_twoGroupInf3'] = new Array('_c', '_g', '_b');
versions['l_twoGroupInf5'] = new Array('_c', '_g', '_b');
versions['l_twoGroupInf7'] = new Array('_c', '_g', '_b');
versions['l_twoGroupPropn1'] = new Array('_c', '_g');
versions['l_twoGroupPropn3'] = new Array('_c', '_g');
versions['l_twoGroupPropn4'] = new Array('_c', '_g');
versions['l_testPaired1'] = new Array('_c', '_g', '_b');
versions['l_testPaired2'] = new Array('_g', '_b');
versions['l_testPaired3'] = new Array('_c', '_g');
versions['l_multiGroup3'] = new Array('_c', '_g', '_b');
versions['l_multiGroup6'] = new Array('_c', '_g', '_b');
versions['l_multiGroup8'] = new Array('_c', '_g', '_b');
versions['l_regnModel1'] = new Array('_c', '_g');
versions['l_regnModel2'] = new Array('_c', '_g');
versions['l_regnModel5'] = new Array('_c', '_g', '_b');
versions['l_regnEst1'] = new Array('_c', '_g');
versions['l_regnEst2'] = new Array('_c', '_g');
versions['l_regnEst4'] = new Array('_c', '_g');
versions['l_regnTest1'] = new Array('_c', '_g');
versions['l_regnTest2'] = new Array('_c', '_g');
versions['l_regnTest3'] = new Array('_c', '_g');
versions['l_regnPred1'] = new Array('_c', '_g', '_b');
versions['l_regnPred5'] = new Array('_g', '_b');
versions['l_regnProblem3'] = new Array('_g', '_b');
versions['l_regnProblem4'] = new Array('_c', '_g');
versions['l_regnProblem5'] = new Array('_c', '_g');
versions['l_prob1'] = new Array('_c', '_g');
versions['l_prob2'] = new Array('_c', '_g', '_b');
versions['l_prob3'] = new Array('_c', '_g', '_b');
versions['l_prob4'] = new Array('_g', '_b');
versions['l_prob5'] = new Array('_c', '_g');
versions['l_prob6'] = new Array('_c', '_g');
versions['l_indep1'] = new Array('_c', '_g');
versions['l_indep3'] = new Array('_c', '_g');
versions['l_indep7'] = new Array('_c', '_g');
versions['l_indep8'] = new Array('_c', '_g');

bookLoaded = true;
