
addBook('bk/ncea', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addPart("Pre-NCEA");

addChapter('bk/ncea', 'ch_categories', "Looking at Categories");
addSection('bk/ncea', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1', 'en/freqTable', 'v_freqTable1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('en/freqTable', 'e_freqTable2', "#r#Exercise: #+#Propns from tables", 'static');
addPage_2('en/freqTable', 'e_freqTable3', "#r#Exercise: #+#Propns from ordered categories", 'static');
addSection('bk/ncea', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('en/univarCat', 'univarCat3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat3', 'en/univarCat', 'v_univarCat3');
addPage_2('en/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat4');
addPage_2('en/univarCat', 'univarCat5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat5');
addPage_2('en/univarCat', 'univarCat6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat6', 'en/univarCat', 'v_univarCat6');
addPage_2('en/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat7');
addPage_2('en/univarCat', 'e_univarCat1', "#r#Exercise: #+#Draw a bar chart", 'static');
addPage_2('en/univarCat', 'e_univarCat2', "#r#Exercise: #+#Find proportion from bar chart", 'static');
addPage_2('en/univarCat', 'e_univarCat4', "#r#Exercise: #+#Draw a pie chart", 'static');
addPage_2('en/univarCat', 'e_univarCat5', "#r#Exercise: #+#Match bar and pie charts", 'static');
addPage_2('en/univarCat', 'e_univarCat6', "#r#Exercise: #+#Proportions from pie chart", 'static');

addChapter('bk/ncea', 'ch_numbers', "Looking at Numbers");
addSection('bk/ncea', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay1');
addPage_2('en/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay2');
addPage_2('en/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay4');
addPage_2('en/valueDisplay', 'valueDisplay5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5', 'en/valueDisplay', 'v_valueDisplay5');
addPage_2('bk/ncea', 'valueDisplay7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7', 'bk/ncea', 'v_valueDisplay7');
addPage_2('bk/ncea', 'e_valueDisplay1', "#r#Exercise: #+#Draw stem and leaf plot", 'static');
addPage_2('en/valueDisplay', 'e_valueDisplay2', "#r#Exercise: #+#Complete stacked dot plot", 'static');
addSection('bk/ncea', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2', 'en/density', 'v_density2');
addPage_2('en/density', 'density3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density3');
addPage_2('en/density', 'density4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density4');
addPage_2('en/density', 'density6', "Comparing groups", 'interact', 'en/density', 's_density6', 'en/density', 'v_density6');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9', 'en/density', 'v_density9');
addPage_2('en/density', 'density11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11', 'en/density', 'v_density11');
addPage_2('en/density', 'e_density1', "#r#Exercise: #+#Draw a histogram", 'static');
addSection('bk/ncea', 'sec_boxPlot', "Median, quartiles & box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('bk/ncea', 'e_boxPlot1', "#r#Exercise: #+#Draw a box plot", 'static');
addPage_2('en/boxPlot', 'e_boxPlot2', "#r#Exercise: #+#Shape of a box plot", 'static');
addSection('bk/ncea', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot1', "More than one variable", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2', 'en/scatterplot', 'v_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5', 'en/scatterplot', 'v_scatterplot5');
addPage_2('en/scatterplot', 'e_scatterplot1', "#r#Exercise: #+#Draw a scatterplot", 'static');

addChapter('bk/ncea', 'ch_centreSpread', "Centre and Spread");
addSection('bk/ncea', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addPage_2('en/centerSpread', 'e_centerSpread1', "#r#Exercise: #+#Ideas of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread2', "#r#Exercise: #+#Mean and median", 'static');

addPart("NCEA Level 1");

addChapter('bk/ncea', 'ch_level_1.10', "Explore Data (1.10)");
addSection('bk/ncea', 'sec_variables', "Variables and individuals");
addPage_2('en/structures', 'structures1', "Variables and individuals", 'interact', 'en/structures', 's_structures1', 'en/structures', 'v_structures1');
addPage_2('en/structures', 'structures2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures2');
addPage_2('en/freqTable', 'e_freqTable1', "#r#Exercise: #+#Types of variables", 'static');
addSection('bk/ncea', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp1');
addPage_2('en/displayInterp', 'displayInterp2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp2');
addPage_2('en/displayInterp', 'displayInterp3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp3');
addPage_2('en/displayInterp', 'displayInterp4', "Names of individuals", 'interact', 'en/displayInterp', 's_displayInterp4', 'en/displayInterp', 'v_displayInterp4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp6');
addPage_2('en/displayInterp', 'e_displayInterp1', "#r#Exercise: #+#Information from distributions", 'static');
addSection('bk/ncea', 'sec_boxPlotMore', "More about box plots");
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7', 'en/boxPlot', 'v_boxPlot7');
addPage_2('bk/ncea', 'e_boxPlotMore1', "#r#Exercise: #+#Draw a box plot", 'static');
addSection('bk/ncea', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp2');
addPage_2('en/popSamp', 'popSamp3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp3');
addPage_2('en/popSamp', 'popSamp4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4', 'en/popSamp', 'v_popSamp4');
addPage_2('en/popSamp', 'popSamp5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5', 'en/popSamp', 'v_popSamp5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addPage_2('en/popSamp', 'e_popSamp1', "#r#Exercise: #+#Distinguish between populations and samples", 'static');

addChapter('bk/ncea', 'ch_level_1.11', "Explore Bivariate Data (1.11)");
addSection('bk/ncea', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'en/relationship', 'v_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4', 'en/relationship', 'v_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship5');
addPage_2('en/scatterplot', 'e_scatterplot2', "#r#Exercise: #+#Interpret a scatterplot", 'static');

addChapter('bk/ncea', 'ch_level_1.12', "Chance and Data (1.12)");
addSection('bk/ncea', 'sec_probability', "Probability");
addPage_2('en/probDensity', 'probDensity1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1', 'en/probDensity', 'v_probDensity1');
addPage_2('en/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2', 'en/probDensity', 'v_probDensity2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3', 'en/probDensity', 'v_probDensity3');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('en/probSim', 'e_probSim2', "#r#Exercise: #+#Probabilities and finite populations", 'static');
addPage_2('en/probSim', 'e_probSim3', "#r#Exercise: #+#Probabilities and numerical population", 'static');
addSection('bk/ncea', 'sec_continTable', "Contingency tables");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1', 'en/groupedCat', 'v_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat2', 'en/groupedCat', 'v_groupedCat2');
addPage_2('bk/ncea', 'continTable3', "Proportions within groups", 'interact', 'en/groupedCat', 's_groupedCat3', 'bk/ncea', 'v_continTable3');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures3');
addPage_2('en/groupedCat', 'e_groupedCat1', "#r#Exercise: #+#Create a contingency table", 'static');
addSection('bk/ncea', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1', 'en/timePlot', 'v_timePlot1');
addPage_2('bk/ncea', 'timePlot2', "Patterns in time series", 'interact', 'bk/ncea', 's_timePlot2', 'en/timePlot', 'v_timePlot2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3', 'en/timePlot', 'v_timePlot3');

addChapter('bk/ncea', 'ch_level_1.13', "Situation With Chance (1.13)");

addPart("NCEA Level 2");

addChapter('bk/ncea', 'ch_level_2.08', "Design Questionnaire (2.8)");
addSection('bk/ncea', 'sec_sampPractice', "Sampling in practice");
addPage_2('bk/ncea', 'sampPractice1', "Other sampling schemes", 'static', 'bk/ncea', 's_sampPractice1');
addPage_2('en/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4', 'en/sampPractice', 'v_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5', 'en/sampPractice', 'v_sampPractice5');
addPage_2('en/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6', 'en/sampPractice', 'v_sampPractice6');
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7', 'en/sampPractice', 'v_sampPractice7');

addChapter('bk/ncea', 'ch_level_2.09', "Make an Inference (2.9)");
addSection('bk/ncea', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');
addSection('bk/ncea', 'sec_infPopn', "Sampling from a distribution");
addPage_2('en/infPopn', 'infPopn1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn1', 'en/infPopn', 'v_infPopn1');
addPage_2('en/infPopn', 'infPopn2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2', 'en/infPopn', 'v_infPopn2');
addPage_2('en/infPopn', 'infPopn3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3', 'en/infPopn', 'v_infPopn3');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5', 'en/infPopn', 'v_infPopn5');
addSection('bk/ncea', 'sec_stdDevn', "Standard deviation");
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread_c7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread7');
addPage_2('bk/ncea', 'centerSpread8', "Warnings about mean and standard devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addPage_2('en/centerSpread', 'e_centerSpread3', "#r#Exercise: #+#Standard deviation from graph", 'static');
addPage_2('en/centerSpread', 'e_centerSpread4', "#r#Exercise: #+#Standard deviation from general knowledge", 'static');
addPage_2('en/centerSpread', 'e_centerSpread5', "#r#Exercise: #+#Rough graph from mean and st devn", 'static');
addSection('bk/ncea', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro1', 'en/estIntro', 'v_estIntro1');
addPage_2('en/estIntro', 'estIntro2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2', 'en/estIntro', 'v_estIntro2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3', 'en/estIntro', 'v_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4', 'en/estIntro', 'v_estIntro4');
addPage_2('en/estIntro', 'estIntro5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5', 'en/estIntro', 'v_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6', 'en/estIntro', 'v_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7', 'en/estIntro', 'v_estIntro7');
addPage_2('en/popSamp', 'e_popSamp2', "#r#Exercise: #+#Distinguish between parameters and estimates", 'static');

addChapter('bk/ncea', 'ch_level_2.10', "Conduct Experiment (2.10)");
addSection('bk/general', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal1', "Interest in relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2', 'en/causal', 'v_causal2');
addPage_2('en/causal', 'causal3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3', 'en/causal', 'v_causal3');
addPage_2('en/causal', 'causal4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4', 'en/causal', 'v_causal4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5', 'en/causal', 'v_causal5');
addSection('bk/general', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1', 'en/designPrelim', 'v_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2', 'en/designPrelim', 'v_designPrelim2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3', 'en/designPrelim', 'v_designPrelim3');

addChapter('bk/ncea', 'ch_level_2.11', "Evaluate a Report (2.11)");

addChapter('bk/ncea', 'ch_level_2.12', "Use Probability (2.12)");
addSection('bk/ncea', 'sec_continProbs', "Proportions from tables");
addPage_2('en/bivarCat', 'bivarCat1', "Relationships between variables", 'static', 'en/bivarCat', 's_bivarCat1', 'en/bivarCat', 'v_bivarCat1');
addPage_2('en/bivarCat', 'bivarCat4', "Marginal distributions", 'interact', 'en/bivarCat', 's_bivarCat4', 'en/bivarCat', 'v_bivarCat4');
addPage_2('bk/ncea', 'bivarCat5', "Conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat5', 'bk/ncea', 'v_bivarCat5');
addPage_2('en/bivarCat', 'bivarCat7', "Conditional vs marginal distns", 'interact', 'en/bivarCat', 's_bivarCat7', 'en/bivarCat', 'v_bivarCat7');
addPage_2('en/groupedCat', 'e_groupedCat2', "#r#Exercise: #+#  Proportions from contingency tables", 'static');
addSection('bk/ncea', 'sec_probTable', "Probabilities from tables");
addPage_2('en/prob', 'prob1', "Joint probabilities", 'interact', 'en/prob', 's_prob1', 'en/prob', 'v_prob1');
addPage_2('en/prob', 'prob2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2', 'en/prob', 'v_prob2');
addPage_2('en/prob', 'prob3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3', 'en/prob', 'v_prob3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4', 'en/prob', 'v_prob4');
addPage_2('en/probSim', 'e_probSim1', "#r#Exercise: #+#Probabilities for cards and dice", 'static');
addPage_2('en/probSim', 'e_probSim5', "#r#Exercise: #+#Sampling with and without replacement", 'static');
addSection('bk/ncea', 'sec_treeDiagram', "Tree diagrams");
addPage_2('bk/ncea', 'tree1', "Tree diagrams", 'static', 'bk/ncea', 's_tree1');
addPage_2('bk/ncea', 'tree2', "More about tree diagrams", 'static', 'bk/ncea', 's_tree2');
addSection('bk/ncea', 'sec_densityMore', "More about histograms");
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('en/density', 'density7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7', 'en/density', 'v_density7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8', 'en/density', 'v_density8');
addPage_2('bk/ncea', 'e_densityMore1', "#r#Exercise: #+#Draw histogram with mixed class widths", 'static');
addPage_2('en/density', 'e_density2', "#r#Exercise: #+#Histogram areas and proportions", 'static');
addSection('bk/ncea', 'sec_probDensity', "Probability density functions");
addPage_2('bk/ncea', 'densityCopy5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('bk/ncea', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4', 'en/probDensity', 'v_probDensity4');
addPage_2('bk/ncea', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5', 'en/probDensity', 'v_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6', 'en/probDensity', 'v_probDensity6');
addPage_2('en/probSim', 'e_probSim4', "#r#Exercise: #+#Estimate probability from pdf", 'static');
addSection('bk/ncea', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1', 'en/normalDistn', 'v_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addPage_2('en/normalDistn', 'e_normalDistn1', "#r#Exercise: #+#Normal distribution parameters", 'static');
addPage_2('en/normalDistn', 'e_normalDistn7', "#r#Exercise: #+#Probabilities without calculations", 'static');
addSection('bk/ncea', 'sec_normalProb', "Normal probabilities");
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2', 'en/correlation', 'v_correlation2');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5', 'en/normalDistn', 'v_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6', 'en/normalDistn', 'v_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7', 'en/normalDistn', 'v_normalDistn7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8', 'en/normalDistn', 'v_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9', 'en/normalDistn', 'v_normalDistn9');
addPage_2('en/normalDistn', 'e_normalDistn2', "#r#Exercise: #+#Probability and area under pdf", 'static');
addPage_2('bk/ncea', 'e_normalDistn3', "#r#Exercise: #+#Probabilities from z-scores", 'static');
addPage_2('en/normalDistn', 'e_normalDistn4', "#r#Exercise: #+#Expected count in sample", 'static');
addPage_2('bk/ncea', 'e_normalDistn5', "#r#Exercise: #+#Find X from probability", 'static');

addChapter('bk/ncea', 'ch_level_2.13', "Use Simulation (2.13)");
addSection('bk/ncea', 'sec_probSim', "Simulation");
addPage_2('en/probSim', 'probSim1', "Probability models and simulation", 'interact', 'en/probSim', 's_probSim1', 'en/probSim', 'v_probSim1');
addPage_2('en/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact', 'en/probSim', 's_probSim2', 'en/probSim', 'v_probSim2');
addPage_2('en/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact', 'en/probSim', 's_probSim3', 'en/probSim', 'v_probSim3');
addPage_2('en/probSim', 'probSim4', "Assessing unusual features in data", 'interact', 'en/probSim', 's_probSim4', 'en/probSim', 'v_probSim4');
addPage_2('en/probSim', 'probSim5', "Random numbers", 'interact', 'en/probSim', 's_probSim5', 'en/probSim', 'v_probSim5');
addPage_2('en/probSim', 'probSim6', "Generating categorical values", 'interact', 'en/probSim', 's_probSim6', 'en/probSim', 'v_probSim6');

addPart("NCEA Level 3");

addChapter('bk/ncea', 'ch_level_3.08', "Time Series (3.8)");
addSection('bk/ncea', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1', 'en/smoothing', 'v_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2', 'en/smoothing', 'v_smoothing2');
addSection('bk/ncea', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'trend1', "Linear trend", 'interact', 'en/trend', 's_trend1', 'en/trend', 'v_trend1');
addPage_2('en/trend', 'trend2', "Quadratic trend", 'interact', 'en/trend', 's_trend2', 'en/trend', 'v_trend2');
addPage_2('en/trend', 'trend3', "Forecasting", 'interact', 'en/trend', 's_trend3', 'en/trend', 'v_trend3');
addSection('bk/ncea', 'sec_seasonal', "Seasonal data");
addPage_2('bk/ncea', 'seasonal1', "Seasonal patterns", 'interact', 'en/seasonal', 's_seasonal1', 'bk/ncea', 'v_seasonal1');
addPage_2('en/seasonal', 'seasonal2', "Smoothing out seasonal variation", 'interact', 'en/seasonal', 's_seasonal2', 'en/seasonal', 'v_seasonal2');
addPage_2('en/seasonal', 'seasonal3', "Estimating the seasonal effect", 'interact', 'en/seasonal', 's_seasonal3', 'en/seasonal', 'v_seasonal3');
addPage_2('en/seasonal', 'seasonal4', "Deseasonalised data", 'interact', 'en/seasonal', 's_seasonal4', 'en/seasonal', 'v_seasonal4');
addPage_2('bk/ncea', 'seasonal5', "Putting it all together", 'interact', 'bk/ncea', 's_seasonal5');
addPage_2('bk/ncea', 'seasonal6', "Forecasting with seasonal data", 'interact', 'bk/ncea', 's_seasonal6');

addChapter('bk/ncea', 'ch_level_3.09', "Bivariate Data (3.9)");
addSection('bk/ncea', 'sec_correlation', "Correlation");
addPage_2('bk/ncea', 'correlation3', "Correlation coefficient and its properties", 'interact', 'bk/ncea', 's_correlation3', 'bk/ncea', 'v_correlation3');
addPage_2('en/correlation', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5', 'en/correlation', 'v_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6', 'en/correlation', 'v_correlation6');
addPage_2('en/correlation', 'e_correlation1', "#r#Exercise: #+#Estimate r by eye", 'static');
addPage_2('en/correlation', 'e_correlation2', "#r#Exercise: #+#r for non-standard data", 'static');
addSection('bk/ncea', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1', 'en/leastSqrs', 'v_leastSqrs1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2', 'en/leastSqrs', 'v_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5', 'en/leastSqrs', 'v_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6', 'en/leastSqrs', 'v_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y and predicting X", 'interact', 'en/leastSqrs', 's_leastSqrs7', 'en/leastSqrs', 'v_leastSqrs7');
addPage_2('en/leastSqrs', 'e_leastSqrs1', "#r#Exercise: #+#Pick the explanatory variable and response", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs2', "#r#Exercise: #+#Draw a straight line", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs3', "#r#Exercise: #+#Find the slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs4', "#r#Exercise: #+#Interpret the slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs5', "#r#Exercise: #+#Find a residual", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs6', "#r#Exercise: #+#Match data and residual plot", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs7', "#r#Exercise: #+#Predictions", 'static');
addSection('bk/ncea', 'sec_rSquared', "Coefficient of determination");
addPage_2('bk/ncea', 'rSquared1', "Sums of squares", 'interact');
addPage_2('bk/ncea', 'rSquared2', "Coefficient of determination", 'interact');
addSection('bk/ncea', 'sec_curvature', "Nonlinear relationships (advanced)");
addPage_2('en/curvature', 'curvature1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1', 'en/curvature', 'v_curvature1');
addPage_2('en/curvature', 'curvature2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2', 'en/curvature', 'v_curvature2');
addPage_2('en/curvature', 'curvature3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3', 'en/curvature', 'v_curvature3');
addPage_2('en/curvature', 'curvature4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4', 'en/curvature', 'v_curvature4');
addPage_2('en/curvature', 'e_curvature1', "#r#Exercise: #+#Regression problems", 'static');
addPage_2('en/curvature', 'e_curvature2', "#r#Exercise: #+#Transformations of X and Y", 'static');
addPage_2('en/curvature', 'e_curvature3', "#r#Exercise: #+#Predictions and nonlinearity", 'static');

addChapter('bk/ncea', 'ch_level_3.10', "Formal Inference (3.10)");
addSection('bk/ncea', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_c1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/sumDiff', 'sumDiff1', "Distributions of sums and means", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('en/randomMean', 'e_randomMean1', "#r#Exercise: #+#Spread of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean2', "#r#Exercise: #+#Shape of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean3', "#r#Exercise: #+#Distribution of mean and sum (cont)", 'static');
addPage_2('en/randomMean', 'e_randomMean4', "#r#Exercise: #+#Probabilities relating to means and sums", 'static');
addSection('bk/ncea', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1', 'en/seMean', 'v_seMean1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2', 'en/seMean', 'v_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3', 'en/seMean', 'v_seMean3');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addPage_2('en/seMean', 'e_seMean1', "#r#Exercise: #+#Find standard error of mean", 'static');
addPage_2('en/seMean', 'e_seMean2', "#r#Exercise: #+#Standard error vs standard deviation", 'static');
addPage_2('en/seMean', 'e_seMean3', "#r#Exercise: #+#What affects the standard devn and standard error?", 'static');
addSection('bk/ncea', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean1');
addPage_2('en/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2', 'en/ciMean', 'v_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3', 'en/ciMean', 'v_ciMean3');
addPage_2('en/ciMean', 'e_ciMean1', "#r#Exercise: #+#Find approx 95% CI from standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean2', "#r#Exercise: #+#Find confidence intervals, known &sigma;", 'static');
addPage_2('en/ciMean', 'e_ciMean7', "#r#Exercise: #+#Interpret a 95% confidence interval", 'static');
addSection('bk/ncea', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('en/estPropn', 'estPropn3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn3');
addPage_2('en/estPropn', 'estPropn4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4', 'en/estPropn', 'v_estPropn4');
addPage_2('en/estPropn', 'estPropn5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5', 'en/estPropn', 'v_estPropn5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('en/estPropn', 'estPropn7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7', 'en/estPropn', 'v_estPropn7');
addPage_2('en/estPropn', 'e_estPropn1', "#r#Exercise: #+#Find standard error of proportion", 'static');
addPage_2('en/estPropn', 'e_estPropn2', "#r#Exercise: #+#Find 95% confidence interval", 'static');
addPage_2('en/estPropn', 'e_estPropn5', "#r#Exercise: #+#Interpret a 95% confidence interval", 'static');
addSection('bk/ncea', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'ciExtra1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1', 'en/ciExtra', 'v_ciExtra1');
addPage_2('en/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2', 'en/ciExtra', 'v_ciExtra2');
addPage_2('en/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3', 'en/ciExtra', 'v_ciExtra3');
addPage_2('en/ciExtra', 'ciExtra4', "Other confidence levels", 'interact', 'en/ciExtra', 's_ciExtra4', 'en/ciExtra', 'v_ciExtra4');
addPage_2('en/ciMean', 'e_ciMean4', "#r#Exercise: #+#CIs for &micro; with other confidence levels", 'static');
addPage_2('en/estPropn', 'e_estPropn3', "#r#Exercise: #+#CIs for &pi; with other confidence levels", 'static');
addPage_2('en/ciMean', 'e_ciMean6', "#r#Exercise: #+#Factors affecting CI width of CI for &micro;", 'static');
addPage_2('en/estPropn', 'e_estPropn4', "#r#Exercise: #+#Factors affecting width of CI for &pi;", 'static');
addSection('bk/ncea', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1', 'en/twoGroupInf', 'v_twoGroupInf1');
addPage_2('en/twoGroupInf', 'twoGroupInf2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf2', 'en/twoGroupInf', 'v_twoGroupInf2');

addChapter('bk/ncea', 'ch_level_3.11', "Conduct Experiment (3.11)");
addSection('bk/general', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'designIntro1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1', 'en/designIntro', 'v_designIntro1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2', 'en/designIntro', 'v_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3', 'en/designIntro', 'v_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4', 'en/designIntro', 'v_designIntro4');
addPage_2('en/designIntro', 'designIntro5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5', 'en/designIntro', 'v_designIntro5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6', 'en/designIntro', 'v_designIntro6');
addPage_2('en/designIntro', 'designIntro7', "Blocking", 'interact', 'en/designIntro', 's_designIntro7', 'en/designIntro', 'v_designIntro7');

addChapter('bk/ncea', 'ch_level_3.12', "Evaluate Reports (3.12)");

addChapter('bk/ncea', 'ch_level_3.13', "Use Probability (3.13)");

addChapter('bk/ncea', 'ch_level_3.14', "Use Distributions (3.14)");
addSection('bk/ncea', 'sec_randomPropn', "Binomial distributions");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1', 'en/randomPropn', 'v_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn3');
addPage_2('en/randomPropn', 'randomPropn4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn4', 'en/randomPropn', 'v_randomPropn4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'en/randomPropn', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn6', 'en/randomPropn', 'v_randomPropn6');
addPage_2('en/randomPropn', 'e_randomPropn1', "#r#Exercise: #+#Are variables binomial?", 'static');
addPage_2('en/randomPropn', 'e_randomPropn2', "#r#Exercise: #+#Match bar charts to parameters", 'static');
addPage_2('en/randomPropn', 'e_randomPropn3', "#r#Exercise: #+#Find binomial probabilities", 'static');
addPage_2('en/randomPropn', 'e_randomPropn4', "#r#Exercise: #+#Find a normal approximation", 'static');
addPage_2('en/randomPropn', 'e_randomPropn5', "#r#Exercise: #+#Probabilities from normal approx", 'static');
addSection('bk/ncea', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'sumDiff1', "Means and sums of samples", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('en/sumDiff', 'sumDiff2', "Sum and difference", 'interact', 'en/sumDiff', 's_sumDiff2', 'en/sumDiff', 'v_sumDiff2');
addPage_2('en/sumDiff', 'sumDiff3', "Sum and difference (cont)", 'interact', 'en/sumDiff', 's_sumDiff3', 'en/sumDiff', 'v_sumDiff3');
addPage_2('en/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static', 'en/sumDiff', 's_sumDiff4', 'en/sumDiff', 'v_sumDiff4');

var language = "en";
var logoGif = "logo_massey.gif";
var homeDir = "bk/ncea";
var versionGif = "images/castNcea";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "21";

var localVideos = false;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_c': 'Business', '_a': 'African', '_b': 'Biometric', '_m': 'Climatic', '++': 'Custom', '_o': 'Official stats', '_z': 'Other'};
var versions = {};
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat6'] = new Array('_g', '_b', '_c');
versions['univarCat7'] = new Array('_g', '_b');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('_g', '_a', '_b', '_c', '_m');
versions['valueDisplay7'] = new Array('+g', '_g', '_c', '_m');
versions['e_valueDisplay1'] = new Array('+g', '_g');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density9'] = new Array('_g', '_c');
versions['density11'] = new Array('_g', '_b', '_c', '_m');
versions['e_boxPlot1'] = new Array('+g', '_g');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['displayInterp1'] = new Array('_g', '_b', '_c');
versions['displayInterp2'] = new Array('_g', '_b', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['displayInterp6'] = new Array('_g', '_b', '_c');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('+g', '_g', '_b', '_c');
versions['sampPractice1'] = new Array('+g', '_g', '_b');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['variation4'] = new Array('_g', '_a');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['centerSpread7'] = new Array('_c', '_g');
versions['centerSpread8'] = new Array('+g', '_g');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designPrelim2'] = new Array('_g', '_c');
versions['bivarCat1'] = new Array('_g', '_b', '_c');
versions['bivarCat5'] = new Array('+g', '_g');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['density7'] = new Array('_g', '_b', '_c', '_m');
versions['probDensity4'] = new Array('+g', '_g');
versions['probDensity5'] = new Array('+g', '_g', '_c');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['e_normalDistn3'] = new Array('+g', '_g');
versions['e_normalDistn5'] = new Array('+g', '_g');
versions['probSim4'] = new Array('_g', '_b', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['seasonal1'] = new Array('+g', '_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['seasonal5'] = new Array('+g', '_g', '_m', '_z');
versions['seasonal6'] = new Array('+g', '_g', '_m', '_z');
versions['correlation3'] = new Array('+g', '_g');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_c', '_g', '_b');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');

bookLoaded = true;
