
addBook('bk/german', 'book_splash', "&Uuml;ber CAST e-Books");

addChapter('bk/german', 'ch_preface', "Vorwort");
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/german', 'ch_intro', "Einf&uuml;hrung: Daten");
addSection('bk/german', 'sec_context', "Kontext");
addPage_2('de/context', 'context1', "Importance of context", 'static');
addPage_2('de/context', 'context2', "Statistik", 'static');
addPage_2('de/context', 'context3', "Der statistische Prozess", 'static');
addSection('bk/german', 'sec_structures', "Standard Datenstrukturen");
addPage_2('de/structures', 'structures1', "Variables and individuals", 'interact');
addPage_2('de/structures', 'structures2', "Types of variable", 'interact');
addPage_2('de/structures', 'structures3', "Kategoriale Variablen und Gruppen", 'interact');
addPage_2('de/structures', 'structures4', "Neue Variablen definieren", 'interact');
addPage_2('de/structures', 'structures5', "Time-ordered data", 'static');
addPage_2('de/structures', 'structures6', "Multi-level data", 'interact');
addPage_2('de/structures', 'structures7', "Von der Datenstruktur zur statistischen Methode", 'static');
addSection('bk/german', 'sec_variation', "Variation");
addPage_2('de/variation', 'variation1', "Signal und Rauschen", 'interact');
addPage_2('de/variation', 'variation2', "Nat&uuml;rliche Variabilit&auml;t", 'interact');
addPage_2('de/variation', 'variation3', "Durch Experimente verursachte Variabilit&auml;t", 'interact');
addPage_2('de/variation', 'variation4', "Variabilit&auml;t in Daten aus Frageb&ouml;gen", 'interact');
addPage_2('de/variation', 'variation5', "Explained and unexplained variation", 'static');
addPage_2('de/variation', 'variation6', "Vorhersage zuk&uuml;nftiger Werte", 'static');

addChapter('bk/german', 'ch_univar', "Eine metrische Variable");
addSection('bk/german', 'sec_valueDisplay', "Grafische Darstellung der Werte");
addPage_2('de/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay5', "Stem and leaf plots", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay6', "Die St&auml;mme aufteilen", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay7', "Zeichnen von Ast-Blatt-Diagrammen", 'interact');
addSection('bk/german', 'sec_displayInterp', "Verteilungen verstehen");
addPage_2('de/displayInterp', 'displayInterp1', "Outliers", 'static');
addPage_2('de/displayInterp', 'displayInterp2', "Clusters", 'interact');
addPage_2('de/displayInterp', 'displayInterp3', "Verteilung der Werte", 'static');
addPage_2('de/displayInterp', 'displayInterp4', "Names of individuals", 'interact');
addPage_2('de/displayInterp', 'displayInterp5', "Bekannte Gruppen unterscheiden", 'interact');
addPage_2('de/displayInterp', 'displayInterp6', "Gefahr der Überinterpretation", 'interact');
addSection('bk/german', 'sec_density', "Histogramme und Dichte");
addPage_2('de/density', 'density1', "Dichte der Werte", 'static');
addPage_2('de/density', 'density2', "Histogrammemit einheitlichen Klassenbreiten", 'interact');
addPage_2('de/density', 'density3', "Wahl der Klassenbreite", 'interact');
addPage_2('de/density', 'density4', "Histograms of small data sets", 'interact');
addPage_2('de/density', 'density5', "Relative Häufigkeit und Fläche", 'interact');
addPage_2('de/density', 'density6', "Comparing groups", 'interact');
addPage_2('de/density', 'density7', "Histograms with varying class widths", 'interact');
addPage_2('de/density', 'density8', "Histogramme verstehen", 'interact');
addPage_2('de/density', 'density9', "Summenpolygone", 'interact');
addPage_2('de/density', 'density10', "Kerndichteschätzungen", 'interact');
addPage_2('de/density', 'density11', "Histogramme von Hand zeichnen", 'interact');
addSection('bk/german', 'sec_boxPlot', "Median, Quartile &amp; Boxplots");
addPage_2('de/boxPlot', 'boxPlot1', "Warum ist das Zusammenfassen von Daten wichtig?", 'static');
addPage_2('de/boxPlot', 'boxPlot2', "Median, Quartile und Boxplot", 'interact');
addPage_2('de/boxPlot', 'boxPlot3', "Interpretieren der Form eines Boxplots", 'interact');
addPage_2('de/boxPlot', 'boxPlot4', "Ausreisser darstellen", 'interact');
addPage_2('de/boxPlot', 'boxPlot5', "Cluster", 'interact');
addPage_2('de/boxPlot', 'boxPlot6', "Vergleich von Gruppen", 'interact');
addPage_2('de/boxPlot', 'boxPlot7', "Die Gefahr der Überinterpretation", 'interact');
addSection('bk/german', 'sec_centerSpread', "Lage und Streuung beschreiben");
addPage_2('de/centerSpread', 'centerSpread1', "Centre and spread", 'static');
addPage_2('de/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact');
addPage_2('de/centerSpread', 'centerSpread3', "Summaries of centre", 'interact');
addPage_2('de/centerSpread', 'centerSpread4', "Eigenschaften von Mittelwert und Median", 'interact');
addPage_2('de/centerSpread', 'centerSpread5', "Standardabweichung", 'interact');
addPage_2('de/centerSpread', 'centerSpread6', "Faustregel für die Standardabweichung", 'static');
addPage_2('de/centerSpread', 'centerSpread7', "Standardabweichungen und Mittelwerte verstehen", 'interact');
addPage_2('de/centerSpread', 'centerSpread8', "Warnung für den Gebrauch der Standardabweichung und des Mittelwerts", 'static');
addSection('bk/german', 'sec_moreVariation', "Mehr über Variation (optional)");
addPage_2('de/moreVariation', 'moreVariation1', "Effekte von Ausreissern", 'interact');
addPage_2('de/moreVariation', 'moreVariation2', "Standardabweichung gruppierter Daten", 'interact');
addPage_2('de/moreVariation', 'moreVariation3', "Erklärte Variation und Vorhersagen", 'interact');
addPage_2('de/moreVariation', 'moreVariation4', "Varianz und Freiheitsgrad", 'static');
addPage_2('de/moreVariation', 'moreVariation5', "Mittlerer quadratischer Fehler", 'interact');
addPage_2('de/moreVariation', 'moreVariation6', "Graphische Interpretation der Standardabweichung", 'interact');
addSection('bk/german', 'sec_percentile', "Proportionen und Perzentile");
addPage_2('de/percentile', 'percentile1', "Illustrative data set", 'interact');
addPage_2('de/percentile', 'percentile2', "Cumulative proportions", 'interact');
addPage_2('de/percentile', 'percentile3', "Graph of cumulative proportions", 'interact');
addPage_2('de/percentile', 'percentile4', "Percentiles", 'interact');
addPage_2('de/percentile', 'percentile5', "Displaying percentiles", 'interact');
addPage_2('de/percentile', 'percentile6', "Comparing groups", 'interact');
addPage_2('de/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact');
addPage_2('de/percentile', 'percentile8', "Better definition of percentiles", 'interact');
addSection('bk/german', 'sec_transform', "Transformationen");
addPage_2('de/transform', 'transform1', "Linear transformations", 'interact');
addPage_2('de/transform', 'transform2', "Log transformations", 'interact');
addPage_2('de/transform', 'transform3', "Wann benutzt man die log-Transformation?", 'interact');
addPage_2('de/transform', 'transform4', "Potenz-Transformationen", 'interact');
addPage_2('de/transform', 'transform5', "Effekt von Transformationen auf die Darstellung", 'interact');
addSection('bk/german', 'sec_counts', "Diskrete Daten (Zähldaten)");
addPage_2('de/counts', 'counts1', "Discrete and continuous data", 'interact');
addPage_2('de/counts', 'counts2', "Histograms for counts", 'interact');
addPage_2('de/counts', 'counts3', "Balkendiagramme", 'interact');
addPage_2('de/counts', 'counts4', "Mean and st devn", 'static');

addChapter('bk/german', 'ch_bivar', "Zwei metrische Variablen");
addSection('bk/german', 'sec_scatterplot', "Steudiagramme");
addPage_2('de/scatterplot', 'scatterplot1', "More than one variable", 'interact');
addPage_2('de/scatterplot', 'scatterplot2', "Streudiagramme", 'interact');
addPage_2('de/scatterplot', 'scatterplot3', "Grenzen univariater Darstellungsformen", 'interact');
addPage_2('de/scatterplot', 'scatterplot4', "Randverteilungen", 'interact');
addPage_2('de/scatterplot', 'scatterplot5', "Zeitreihen", 'interact');
addSection('bk/german', 'sec_relationship', "Zusammenhänge verstehen");
addPage_2('de/relationship', 'relationship1', "St&auml;rke des Zusammenhangs", 'interact');
addPage_2('de/relationship', 'relationship2', "Ausreisser", 'interact');
addPage_2('de/relationship', 'relationship3', "Cluster", 'interact');
addPage_2('de/relationship', 'relationship4', "Gefahr der &Uuml;berinterpretation", 'interact');
addPage_2('de/relationship', 'relationship5', "Einflussvariable und Zielvariable", 'static');
addSection('bk/german', 'sec_correlation', "Korrelation");
addPage_2('de/correlation', 'correlation1', "Relationship strength and units of X and Y", 'interact');
addPage_2('de/correlation', 'correlation2', "Variablen ohne Einheiten (z-Werte)", 'interact');
addPage_2('de/correlation', 'correlation3', "Der Korrelationskoeffizient und seine Eigenschaften", 'interact');
addPage_2('de/correlation', 'correlation4', "Streudiagramme und die Maßzahl r", 'interact');
addPage_2('de/correlation', 'correlation5', "Nichtlineare Zusammenhänge", 'interact');
addPage_2('de/correlation', 'correlation6', "R beschreibt nicht das ganze Bild", 'interact');
addSection('bk/german', 'sec_leastSqrs', "Die kleinsten Quadrate");
addPage_2('de/leastSqrs', 'leastSqrs1', "Die Vorhersage von Y durch X", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs2', "Lineare modelle", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs3', "Berechnete Werte und Residuen", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs4', "Methode der kleinsten Quadrate", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs5', "Nichtlinearität und Ausreißer", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs6', "Residuendiagramm", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs7', "Vorhersage von Y und X", 'interact');
addSection('bk/german', 'sec_curvature', "Nichtlineare Zusammenhänge");
addPage_2('de/curvature', 'curvature1', "Transformationen und Korrelation", 'interact');
addPage_2('de/curvature', 'curvature2', "Transformationen und Modelle", 'interact');
addPage_2('de/curvature', 'curvature3', "Quadratische Modelle", 'interact');
addPage_2('de/curvature', 'curvature4', "Gefahren bei der Extrapolation", 'interact');

addChapter('bk/german', 'ch_timeSeries', "Zeitreihen");
addSection('bk/german', 'sec_timePlot', "Grafische Darstellung von Zeitreihen");
addPage_2('de/timePlot', 'timePlot1', "Time series plots", 'interact');
addPage_2('de/timePlot', 'timePlot2', "Patterns in time series", 'interact');
addPage_2('de/timePlot', 'timePlot3', "Multiple Zeitreihen", 'interact');
addSection('bk/german', 'sec_smoothing', "Glätten");
addPage_2('de/smoothing', 'smoothing1', "Gleitender Durchschnitt", 'interact');
addPage_2('de/smoothing', 'smoothing2', "Gleitender Durchschnitt (Fortsetzung)", 'interact');
addPage_2('de/smoothing', 'smoothing3', "Robuste Gl&auml;ttung", 'interact');
addPage_2('de/smoothing', 'smoothing4', "Exponentiale Gl&auml;ttung", 'interact');
addPage_2('de/smoothing', 'smoothing5', "Lowess Gl&auml;ttung von Zeitreihen", 'interact');
addPage_2('de/smoothing', 'smoothing6', "Lowess Gl&auml;ttung von Streudiagrammen", 'interact');
addSection('bk/german', 'sec_trend', "Langzeit-Trends");
addPage_2('de/trend', 'trend1', "Lineare Trends", 'interact');
addPage_2('de/trend', 'trend2', "Quadratische Trends", 'interact');
addPage_2('de/trend', 'trend3', "Vorhersagen", 'interact');
addPage_2('de/trend', 'trend4', "Polynomiale Trends", 'interact');
addPage_2('de/trend', 'trend5', "Trends aus Zeitreihen herausrechnen", 'interact');
addSection('bk/german', 'sec_cyclic', "Short-term fluctuations");
addPage_2('de/cyclic', 'cyclic1', "Autocorrelation", 'interact');
addPage_2('de/cyclic', 'cyclic2', "AR(1) model for autocorrelation", 'interact');
addPage_2('de/cyclic', 'cyclic3', "AR(1) model and trend", 'interact');
addPage_2('de/cyclic', 'cyclic4', "Dangers of over-interpretation", 'interact');
addPage_2('de/cyclic', 'cyclic5', "Cyclical patterns", 'interact');
addSection('bk/german', 'sec_seasonal', "Seasonal data");
addPage_2('de/seasonal', 'seasonal1', "Seasonal patterns", 'interact');
addPage_2('de/seasonal', 'seasonal2', "Smoothing out seasonal variation", 'interact');
addPage_2('de/seasonal', 'seasonal3', "Estimating the seasonal effect", 'interact');
addPage_2('de/seasonal', 'seasonal4', "Deseasonalised data", 'interact');
addPage_2('de/seasonal', 'seasonal5', "Putting it all together", 'interact');
addPage_2('de/seasonal', 'seasonal6', "Forecasting with seasonal data", 'interact');
addSection('bk/german', 'sec_multiplicative', "Multiplicative models");
addPage_2('de/multiplicative', 'multiplicative1', "Additive and multiplicative models", 'interact');
addPage_2('de/multiplicative', 'multiplicative2', "Properties of multiplicative models", 'interact');
addPage_2('de/multiplicative', 'multiplicative3', "Forecasting with multiplicative models", 'interact');
addPage_2('de/multiplicative', 'multiplicative4', "Analysing the right data", 'static');
addPage_2('de/multiplicative', 'multiplicative5', "Types of time series data", 'static');
addSection('bk/german', 'sec_indexNos', "Index numbers");
addPage_2('de/indexNos', 'indexNos1', "Introduction", 'static');
addPage_2('de/indexNos', 'indexNos2', "Simple price index", 'static');
addPage_2('de/indexNos', 'indexNos3', "Aggregate price index", 'static');
addPage_2('de/indexNos', 'indexNos4', "Laspeyres and Paasche indices", 'static');
addPage_2('de/indexNos', 'indexNos5', "Deflating a time series", 'static');

addChapter('bk/german', 'ch_cat', "Kategorielle Variablen");
addSection('bk/german', 'sec_freqTable', "Häufigkeitstabellen");
addPage_2('de/freqTable', 'freqTable1', "Häufigkeitstabellen", 'interact');
addPage_2('de/freqTable', 'freqTable2', "Proportions and percentages", 'interact');
addPage_2('de/freqTable', 'freqTable3', "Häufigkeitstabellen erkennen", 'static');
addPage_2('de/freqTable', 'freqTable4', "Veränderung der Kategorien", 'interact');
addSection('bk/german', 'sec_univarCat', "Balken- und Kreisdiagramme");
addPage_2('de/univarCat', 'univarCat1', "Bar charts", 'interact');
addPage_2('de/univarCat', 'univarCat2', "Paretodiagramme", 'interact');
addPage_2('de/univarCat', 'univarCat3', "Chartjunk and misleading bar charts", 'static');
addPage_2('de/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact');
addPage_2('de/univarCat', 'univarCat5', "Comparison of bar and pie charts", 'interact');
addPage_2('de/univarCat', 'univarCat6', "Chartjunk for pie charts", 'static');
addPage_2('de/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact');
addSection('bk/german', 'sec_groupedCat', "Gruppen vergleichen");
addPage_2('de/groupedCat', 'groupedCat1', "Kontingenztabellen", 'interact');
addPage_2('de/groupedCat', 'groupedCat2', "Contingency table examples", 'static');
addPage_2('de/groupedCat', 'groupedCat3', "Bar charts using proportions", 'interact');
addPage_2('de/groupedCat', 'groupedCat4', "Stacked bar charts", 'interact');
addPage_2('de/groupedCat', 'groupedCat5', "Two special cases", 'interact');
addSection('bk/german', 'sec_bivarCat', "Bivariate kategorielle Verteilungen");
addPage_2('de/bivarCat', 'bivarCat1', "Zusammenhang zwischen Variablen", 'static');
addPage_2('de/bivarCat', 'bivarCat2', "3-dimensionale Balkendiagramme", 'interact');
addPage_2('de/bivarCat', 'bivarCat3', "Gruppierte Balkendiagramme", 'interact');
addPage_2('de/bivarCat', 'bivarCat4', "Randverteilungen", 'interact');
addPage_2('de/bivarCat', 'bivarCat5', "Bedingte Verteilungen", 'interact');
addPage_2('de/bivarCat', 'bivarCat6', "Mehr über bedingte Verteilungen", 'interact');
addPage_2('de/bivarCat', 'bivarCat7', "Bedingte Verteilungen und Randverteilungen im Vergleich", 'interact');
addSection('bk/german', 'sec_tableDisplay', "Daten in Tabellen präsentieren");
addPage_2('de/tableDisplay', 'tableDisplay1', "Rasterlinien und Leerzeichen", 'static');
addPage_2('de/tableDisplay', 'tableDisplay2', "Layout und Erl&auml;uterungen", 'static');
addPage_2('de/tableDisplay', 'tableDisplay3', "Datenrauschen und Dezimalstellen", 'interact');
addPage_2('de/tableDisplay', 'tableDisplay4', "Bedeutsame Variablen", 'interact');
addPage_2('de/tableDisplay', 'tableDisplay5', "Spalten und Zeilen vertauschen", 'static');
addPage_2('de/tableDisplay', 'tableDisplay6', "Zeilen neu ordnen", 'interact');
addPage_2('de/tableDisplay', 'tableDisplay7', "Beispiel", 'static');
addSection('bk/german', 'sec_logistic', "Logistische Regression");
addPage_2('de/logistic', 'logistic1', "Categorical responses", 'interact');
addPage_2('de/logistic', 'logistic2', "Fitted values and predictions", 'interact');
addPage_2('de/logistic', 'logistic3', "Logistische Kurve", 'interact');
addPage_2('de/logistic', 'logistic4', "Eine gute Anpassung ereichen", 'interact');

addChapter('bk/german', 'ch_multivar', "Multivariate Daten");
addSection('bk/german', 'sec_multivariate', "Darstellung multivariater Daten");
addPage_2('de/multivariate', 'multivariate1', "Representing a third variable", 'interact');
addPage_2('de/multivariate', 'multivariate2', "Drehbare 3D-Streudiagramme", 'interact');
addPage_2('de/multivariate', 'multivariate3', "Streudiagrammmatrix und Einf&auml;rben", 'interact');
addPage_2('de/multivariate', 'multivariate4', "Einf&auml;rben", 'interact');
addPage_2('de/multivariate', 'multivariate5', "Aufteilen", 'interact');
addSection('bk/german', 'sec_regnGroups', "Gruppen und Regression");
addPage_2('de/regnGroups', 'regnGroups1', "Zus&auml;tzliche Variablen in der Regression", 'interact');
addPage_2('de/regnGroups', 'regnGroups2', "Gruppen darstellen", 'interact');
addPage_2('de/regnGroups', 'regnGroups3', "Regression mit gruppierten Daten", 'interact');
addPage_2('de/regnGroups', 'regnGroups4', "Parallele Regressionsgeraden", 'interact');
addPage_2('de/regnGroups', 'regnGroups5', "Transformierte Variablen und Gruppen", 'interact');
addPage_2('de/regnGroups', 'regnGroups6', "Gruppierung mit numerischen Variablen", 'interact');
addPage_2('de/regnGroups', 'regnGroups7', "Streudiagrammmatrix mit Gruppen", 'interact');
addSection('bk/german', 'sec_multiRegn', "Multiple Regression");
addPage_2('de/multiRegn', 'multiRegn1', "Mehr als eine Einflussvariable", 'interact');
addPage_2('de/multiRegn', 'multiRegn2', "Multiple Regressionsgleichung", 'interact');
addPage_2('de/multiRegn', 'multiRegn3', "Koeffizienten interpretieren", 'interact');
addPage_2('de/multiRegn', 'multiRegn4', "Streudiagramm zweier Variablen", 'interact');
addPage_2('de/multiRegn', 'multiRegn5', "Die lineare Gleichung für Y mit den Einflussvariablen X und Z", 'interact');
addPage_2('de/multiRegn', 'multiRegn6', "Modelwerte und Residuen", 'interact');
addPage_2('de/multiRegn', 'multiRegn7', "Schätzung der kleinsten Quadrate", 'interact');
addSection('bk/german', 'sec_lurking', "Zusammenhang der Randsummen");
addPage_2('de/lurking', 'lurking1', "Misleading marginal correlation", 'interact');
addPage_2('de/lurking', 'lurking2', "Misleading marginal difference in means", 'interact');
addPage_2('de/lurking', 'lurking3', "Simpsons Paradox", 'interact');
addPage_2('de/lurking', 'lurking4', "Weitere Beispiele f&uuml;r versteckte Variablen", 'static');

addChapter('bk/german', 'ch_sample', "Stichproben und Variabilit&auml;t");
addSection('bk/german', 'sec_popSamp', "Endliche Grundgesamtheiten");
addPage_2('de/popSamp', 'popSamp1', "Census or sample?", 'interact');
addPage_2('de/popSamp', 'popSamp2', "Variabilit&auml;t einer Stichprobe", 'interact');
addPage_2('de/popSamp', 'popSamp3', "Sampling error", 'interact');
addPage_2('de/popSamp', 'popSamp4', "Sampling error and sample size", 'interact');
addPage_2('de/popSamp', 'popSamp5', "Sampling from finite populations", 'interact');
addPage_2('de/popSamp', 'popSamp6', "Eine Zufallsstichprobe ziehen", 'interact');
addSection('bk/german', 'sec_infPopn', "Stichproben von Verteilungen");
addPage_2('de/infPopn', 'infPopn1', "Data as representatives", 'static');
addPage_2('de/infPopn', 'infPopn2', "Randomness of data", 'interact');
addPage_2('de/infPopn', 'infPopn3', "Model to explain randomness", 'static');
addPage_2('de/infPopn', 'infPopn4', "Unendliche Populationen", 'interact');
addPage_2('de/infPopn', 'infPopn5', "Information aus einer einzelnen Stichprobe", 'interact');
addSection('bk/german', 'sec_probDensity', "Wahrscheinlichkeit und Dichte");
addPage_2('de/probDensity', 'probDensity1', "Finite populations", 'interact');
addPage_2('de/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact');
addPage_2('de/probDensity', 'probDensity3', "Balkendiagramm diskreter Wahrscheinlichkeiten", 'interact');
addPage_2('de/probDensity', 'probDensity4', "Dichtefunktionen", 'interact');
addPage_2('de/probDensity', 'probDensity5', "Normalverteilungen", 'interact');
addPage_2('de/probDensity', 'probDensity6', "Die Fl&auml;che unter der Dichtefunktion", 'interact');
addPage_2('de/probDensity', 'probDensity7', "Eigenschaften von Wahrscheinlichkeiten", 'static');
addSection('bk/german', 'sec_probSim', "Simulation (optional)");
addPage_2('de/probSim', 'probSim1', "Wahrscheinlichkeitsmodelle und Simulationen", 'interact');
addPage_2('de/probSim', 'probSim2', "Gewinnt das beste Team?", 'interact');
addPage_2('de/probSim', 'probSim3', "Spielqualit&auml;t in der Fussballliga", 'interact');
addPage_2('de/probSim', 'probSim4', "Assessing unusual features in data", 'interact');
addPage_2('de/probSim', 'probSim5', "Zufallswerte", 'interact');
addPage_2('de/probSim', 'probSim6', "Kategorielle Werte erzeugen", 'interact');
addPage_2('de/probSim', 'probSim7', "Numerische Werte erzeugen", 'interact');
addSection('bk/german', 'sec_randomMean', "Verteilung von Stichprobenmittelwerten");
addPage_2('de/randomMean', 'randomMean1', "Parameters and statistics", 'interact');
addPage_2('de/randomMean', 'randomMean2', "Variabilit&auml;t des Stichprbenmittelwerts", 'interact');
addPage_2('de/randomMean', 'randomMean3', "Standardabweichung der Stichprobe", 'interact');
addPage_2('de/randomMean', 'randomMean4', "Mittelwerte von normalverteilten Grundgesamtheiten", 'interact');
addPage_2('de/randomMean', 'randomMean5', "Zentraler Grenzwertsatz", 'interact');
addPage_2('de/randomMean', 'randomMean6', "Verteilung des Stichprobenmittelwerts", 'static');
addPage_2('de/randomMean', 'randomMean7', "Unabh&auml;ngigkeit", 'interact');
addPage_2('de/randomMean', 'randomMean8', "Stichproben aus endlichen Grundgesamtheiten", 'interact');
addSection('bk/german', 'sec_normalDistn', "Normalverteilungen");
addPage_2('de/normalDistn', 'normalDistn1', "Bedeutung der Normalverteilung", 'interact');
addPage_2('de/normalDistn', 'normalDistn2', "Die Form von Normalverteilungen", 'interact');
addPage_2('de/normalDistn', 'normalDistn3', "Skizzieren einer Normalverteilung", 'interact');
addPage_2('de/normalDistn', 'normalDistn4', "Einige wichtige Wahrscheinlichkeiten", 'interact');
addPage_2('de/normalDistn', 'normalDistn5', "Z-Werte", 'interact');
addPage_2('de/normalDistn', 'normalDistn6', "Wahrscheinlichkeiten in der Normalverteilung", 'interact');
addPage_2('de/normalDistn', 'normalDistn7', "Andere Wahrscheinlichkeiten", 'interact');
addPage_2('de/normalDistn', 'normalDistn8', "z-Tabellen", 'static');
addPage_2('de/normalDistn', 'normalDistn9', "Quantile der Normalverteilung", 'interact');
addPage_2('de/normalDistn', 'normalDistn10', "QQ-plots", 'interact');
addSection('bk/german', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('de/randomPropn', 'randomPropn1', "Proportionen und Wahrscheinlichkeiten", 'interact');
addPage_2('de/randomPropn', 'randomPropn2', "Eigenschaften von Z&auml;hlwerten und Proportionen", 'interact');
addPage_2('de/randomPropn', 'randomPropn3', "Binomial distribution", 'interact');
addPage_2('de/randomPropn', 'randomPropn4', "Binomial probability examples", 'static');
addPage_2('de/randomPropn', 'randomPropn5', "Anpassung der Normalverteilung an die Binomialverteilung", 'interact');
addPage_2('de/randomPropn', 'randomPropn6', "Normal approximation examples", 'static');
addSection('bk/german', 'sec_sampPractice', "Sampling in practice");
addPage_2('de/sampPractice', 'sampPractice1', "Stratified sampling", 'interact');
addPage_2('de/sampPractice', 'sampPractice2', "Clusterstichprobe", 'interact');
addPage_2('de/sampPractice', 'sampPractice3', "Zweistufige Stichprobe", 'interact');
addPage_2('de/sampPractice', 'sampPractice4', "Stichprobenfehler und systematische Fehler", 'static');
addPage_2('de/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static');
addPage_2('de/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact');
addPage_2('de/sampPractice', 'sampPractice7', "Survey design issues", 'static');
addSection('bk/german', 'sec_controlChart', "Control charts");
addPage_2('de/controlChart', 'controlChart1', "Introduction", 'static');
addPage_2('de/controlChart', 'controlChart2', "Run charts", 'interact');
addPage_2('de/controlChart', 'controlChart3', "Control limits", 'interact');
addPage_2('de/controlChart', 'controlChart4', "Other signals of being out-of-control", 'interact');
addPage_2('de/controlChart', 'controlChart5', "False alarms", 'interact');
addPage_2('de/controlChart', 'controlChart6', "Examples of run charts", 'interact');
addPage_2('de/controlChart', 'controlChart7', "Control charts for means", 'interact');
addPage_2('de/controlChart', 'controlChart8', "Control charts for ranges", 'interact');
addPage_2('de/controlChart', 'controlChart9', "Finding the cause of problems", 'interact');

addChapter('bk/german', 'ch_expDesign', "Planung von Experimenten");
addSection('bk/german', 'sec_causal', "Association &amp; causal relationships");
addPage_2('de/causal', 'causal1', "Interest in relationships", 'static');
addPage_2('de/causal', 'causal2', "Kausale und nonkausale Zusammenhänge", 'static');
addPage_2('de/causal', 'causal3', "Detecting causal relationships", 'static');
addPage_2('de/causal', 'causal4', "Observational and experimental data", 'interact');
addPage_2('de/causal', 'causal5', "Daten sammeln und Kausalität", 'interact');
addSection('bk/german', 'sec_designIntro', "Principles of experimental design");
addPage_2('de/designIntro', 'designIntro1', "Experiments and treatments", 'static');
addPage_2('de/designIntro', 'designIntro2', "Variable experimentelle Einheiten", 'interact');
addPage_2('de/designIntro', 'designIntro3', "Schlecht designte Experimente", 'interact');
addPage_2('de/designIntro', 'designIntro4', "Störungen", 'static');
addPage_2('de/designIntro', 'designIntro5', "Randomisation", 'interact');
addPage_2('de/designIntro', 'designIntro6', "Replikation", 'static');
addPage_2('de/designIntro', 'designIntro7', "Blockbildung", 'interact');
addSection('bk/german', 'sec_pairBlock', "Pairing and blocks");
addPage_2('de/pairBlock', 'pairBlock1', "&Auml;hnliche Versuchseinheiten", 'interact');
addPage_2('de/pairBlock', 'pairBlock2', "Experimente mit Paarbildung", 'interact');
addPage_2('de/pairBlock', 'pairBlock3', "Randomisation in Experimenten mit Paarbildung", 'interact');
addPage_2('de/pairBlock', 'pairBlock4', "Einheitliche Gruppen mit 3 oder mehr Versuchseinheiten", 'interact');
addPage_2('de/pairBlock', 'pairBlock5', "Randomised block experiments", 'static');
addSection('bk/german', 'sec_designTwo', "Two or more factors");
addPage_2('de/designTwo', 'designTwo1', "Experiments with 2 factors", 'interact');
addPage_2('de/designTwo', 'designTwo2', "Factorial design", 'static');
addPage_2('de/designTwo', 'designTwo3', "Einfaches Model mit zwei Faktoren", 'interact');
addPage_2('de/designTwo', 'designTwo4', "Interaction zwischen Faktoren", 'interact');
addPage_2('de/designTwo', 'designTwo5', "Beispiel für Interaktionen", 'interact');
addPage_2('de/designTwo', 'designTwo6', "No-interaction model for three factors", 'interact');
addPage_2('de/designTwo', 'designTwo7', "Interaktion in 3-faktoriellen Designs", 'interact');
addSection('bk/german', 'sec_designPrelim', "Practical issues in design");
addPage_2('de/designPrelim', 'designPrelim1', "Zweck", 'static');
addPage_2('de/designPrelim', 'designPrelim2', "Experimentelle Einheiten und Messungen", 'static');
addPage_2('de/designPrelim', 'designPrelim3', "Experimente mit Menschen als Versuchsobjekten", 'static');

addChapter('bk/german', 'ch_estimation', "Parameter sch&auml;tzen");
addSection('bk/german', 'sec_estIntro', "Introduction to estimation");
addPage_2('de/estIntro', 'estIntro1', "Interest in populations", 'static');
addPage_2('de/estIntro', 'estIntro2', "Interest in parameters", 'static');
addPage_2('de/estIntro', 'estIntro3', "Anwendung von Schätzungen", 'static');
addPage_2('de/estIntro', 'estIntro4', "Schätzfehler", 'static');
addPage_2('de/estIntro', 'estIntro5', "Distribution of errors", 'interact');
addPage_2('de/estIntro', 'estIntro6', "Standardfehler und Bias", 'static');
addPage_2('de/estIntro', 'estIntro7', "Intervallschätzungen", 'static');
addSection('bk/german', 'sec_seMean', "Standard error of mean");
addPage_2('de/seMean', 'seMean1', "Error distribution for mean", 'interact');
addPage_2('de/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact');
addPage_2('de/seMean', 'seMean3', "Interpreting the standard error", 'static');
addPage_2('de/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static');
addPage_2('de/seMean', 'seMean5', "Standardfehler vs Standardabweichung", 'interact');
addPage_2('de/seMean', 'seMean6', "Using SEs to compare estimators", 'interact');
addPage_2('de/seMean', 'seMean7', "Weitere Informationen zum Bias", 'interact');
addSection('bk/german', 'sec_ciMean', "Confidence interval for mean");
addPage_2('de/ciMean', 'ciMean1', "Konfidenzintervalle und der Standardfehler", 'static');
addPage_2('de/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact');
addPage_2('de/ciMean', 'ciMean3', "Konfidenzstufen", 'interact');
addPage_2('de/ciMean', 'ciMean4', "Konfidenzstufen, wenn \u03c3 durch s ersetzt wird", 'interact');
addPage_2('de/ciMean', 'ciMean5', "Konfidenzintervall für µ, bei unbekanntem \u03c3", 'interact');
addPage_2('de/ciMean', 'ciMean6', "Eigenschaften des 95% Konfidenzintervalls", 'interact');
addPage_2('de/ciMean', 'ciMean7', "Examples", 'static');
addSection('bk/german', 'sec_estPropn', "Estimating proportions");
addPage_2('de/estPropn', 'estPropn1', "Methoden zur Schätzung", 'static');
addPage_2('de/estPropn', 'estPropn2', "Schätzung einer Proportion", 'interact');
addPage_2('de/estPropn', 'estPropn3', "Fehlerverteilung", 'interact');
addPage_2('de/estPropn', 'estPropn4', "Annäherung der Fehlerverteilung", 'interact');
addPage_2('de/estPropn', 'estPropn5', "Confidence interval for proportion", 'static');
addPage_2('de/estPropn', 'estPropn6', "Eigenschaften des 95%-Konfidenzintervalls von Proportionen", 'interact');
addPage_2('de/estPropn', 'estPropn7', "Confidence interval examples", 'static');
addSection('bk/german', 'sec_ciExtra', "More about estimation");
addPage_2('de/ciExtra', 'ciExtra1', "Margin of error", 'interact');
addPage_2('de/ciExtra', 'ciExtra2', "Stichprobengröße zur Schätzung von Mittelwerten", 'interact');
addPage_2('de/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact');
addPage_2('de/ciExtra', 'ciExtra4', "Andere Vertrauensintervalle", 'interact');
addSection('bk/german', 'sec_estOther', "Simulation and bootstrap");
addPage_2('de/estOther', 'estOther1', "Simulationen", 'static');
addPage_2('de/estOther', 'estOther2', "Fehlerverteilung durch Simulation", 'interact');
addPage_2('de/estOther', 'estOther3', "Simulation mit Normalverteilung", 'interact');
addPage_2('de/estOther', 'estOther4', "Bootstrap der Fehlerverteilung", 'interact');
addPage_2('de/estOther', 'estOther5', "Standard error of correlation from bootstrap", 'interact');
addPage_2('de/estOther', 'estOther6', "KIs durch Simulation", 'interact');

addChapter('bk/german', 'ch_testing', "Hypothesen testen");
addSection('bk/german', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('de/testIntro', 'testIntro1', "Inference", 'static');
addPage_2('de/testIntro', 'testIntro2', "Soccer league simulation", 'interact');
addPage_2('de/testIntro', 'testIntro3', "Simulation to test a proportion", 'interact');
addPage_2('de/testIntro', 'testIntro4', "Test for a mean", 'interact');
addPage_2('de/testIntro', 'testIntro5', "Randomisation tests", 'interact');
addPage_2('de/testIntro', 'testIntro6', "Soccer league randomisation", 'interact');
addPage_2('de/testIntro', 'testIntro7', "Common patterns in hypothesis testing", 'static');
addSection('bk/german', 'sec_testPropn', "Tests about proportions");
addPage_2('de/testPropn', 'testPropn1', "Inference about parameters", 'static');
addPage_2('de/testPropn', 'testPropn2', "P-value for testing proportion", 'interact');
addPage_2('de/testPropn', 'testPropn3', "Another example of testing a proportion", 'interact');
addPage_2('de/testPropn', 'testPropn4', "One- and two-tailed tests", 'interact');
addPage_2('de/testPropn', 'testPropn5', "Tests based on normal approximation", 'interact');
addSection('bk/german', 'sec_testMean', "Tests about means");
addPage_2('de/testMean', 'testMean1', "Introduction", 'static');
addPage_2('de/testMean', 'testMean2', "Tests based on statistical distance", 'interact');
addPage_2('de/testMean', 'testMean3', "P-value for testing mean (known sigma)", 'interact');
addPage_2('de/testMean', 'testMean4', "The t distribution", 'interact');
addPage_2('de/testMean', 'testMean5', "The t test for a mean", 'interact');
addSection('bk/german', 'sec_decision', "Decisions and significance");
addPage_2('de/decision', 'decision1', "Hypothesentests und Entscheidungen", 'static');
addPage_2('de/decision', 'decision2', "Entscheidungsregeln", 'interact');
addPage_2('de/decision', 'decision3', "Significanzlevel und p-Werte", 'interact');
addPage_2('de/decision', 'decision4', "Stichprobenumfang und Power", 'interact');
addSection('bk/german', 'sec_testPValue', "Properties of p-values");
addPage_2('de/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact');
addPage_2('de/testPValue', 'testPValue2', "P-value and consistency with null hypothesis", 'interact');
addPage_2('de/testPValue', 'testPValue3', "Distribution of p-values", 'interact');
addPage_2('de/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact');
addPage_2('de/testPValue', 'testPValue5', "P-values for other tests", 'interact');

addChapter('bk/german', 'ch_twoGroups', "Gruppen vergleichen");
addSection('bk/german', 'sec_twoGroupModel', "Models for two groups");
addPage_2('de/twoGroupModel', 'twoGroupModel1', "Interest in underlying population", 'static');
addPage_2('de/twoGroupModel', 'twoGroupModel2', "Model for two groups", 'interact');
addPage_2('de/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact');
addPage_2('de/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact');
addPage_2('de/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact');
addSection('bk/german', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('de/sumDiff', 'sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('de/sumDiff', 'sumDiff2', "Sum and differences", 'interact');
addPage_2('de/sumDiff', 'sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('de/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static');
addSection('bk/german', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('de/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact');
addPage_2('de/twoGroupInf', 'twoGroupInf2', "Distribution of estimation error", 'static');
addPage_2('de/twoGroupInf', 'twoGroupInf3', "CI for difference between means", 'interact');
addPage_2('de/twoGroupInf', 'twoGroupInf4', "Testing a hypothesis", 'interact');
addPage_2('de/twoGroupInf', 'twoGroupInf5', "One-tailed tests for differences", 'interact');
addSection('bk/german', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('de/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact');
addPage_2('de/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact');
addPage_2('de/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static');
addPage_2('de/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static');
addSection('bk/german', 'sec_testPaired', "Paired t test");
addPage_2('de/testPaired', 'testPaired1', "Paired data examples", 'static');
addPage_2('de/testPaired', 'testPaired2', "Analysis of differences", 'interact');
addPage_2('de/testPaired', 'testPaired3', "Paired t-test", 'interact');
addPage_2('de/testPaired', 'testPaired4', "Pairing and experimental design", 'interact');
addSection('bk/german', 'sec_multiGroup', "Comparing several means");
addPage_2('de/multiGroup', 'multiGroup1', "Model with common standard deviation", 'interact');
addPage_2('de/multiGroup', 'multiGroup2', "Schätzung der gemeinsamen Standardabweichung", 'interact');
addPage_2('de/multiGroup', 'multiGroup3', "Inference about two groups", 'static');
addPage_2('de/multiGroup', 'multiGroup4', "Differenzen zwischen Gruppen schätzen", 'interact');
addPage_2('de/multiGroup', 'multiGroup5', "Quadratsummen", 'interact');
addPage_2('de/multiGroup', 'multiGroup6', "Coefficient of determination", 'static');
addPage_2('de/multiGroup', 'multiGroup7', "Test für Gruppendifferenzen", 'interact');
addPage_2('de/multiGroup', 'multiGroup8', "Examples", 'static');
addSection('bk/german', 'sec_randBlock', "Randomised blocks");
addPage_2('de/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static');
addPage_2('de/randBlock', 'randBlock2', "Importance of using block information", 'interact');
addPage_2('de/randBlock', 'randBlock3', "Data with no baseline treatment", 'interact');
addPage_2('de/randBlock', 'randBlock4', "Randomised block designs", 'interact');
addPage_2('de/randBlock', 'randBlock5', "Model for randomised blocks", 'interact');
addPage_2('de/randBlock', 'randBlock6', "Removing block effects", 'interact');
addPage_2('de/randBlock', 'randBlock7', "Sums of squares", 'interact');
addPage_2('de/randBlock', 'randBlock8', "Anova table and examples", 'static');

addChapter('bk/german', 'ch_regnInference', "Regressionsmodelle");
addSection('bk/german', 'sec_regnModel', "Linear regression models");
addPage_2('de/regnModel', 'regnModel1', "Interest in generalising from data", 'interact');
addPage_2('de/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact');
addPage_2('de/regnModel', 'regnModel3', "Normal linear model", 'interact');
addPage_2('de/regnModel', 'regnModel4', "Errors and 95% band on scatterplot", 'interact');
addPage_2('de/regnModel', 'regnModel5', "Model parameters", 'interact');
addSection('bk/german', 'sec_regnEst', "Estimating parameters");
addPage_2('de/regnEst', 'regnEst1', "Point estimates of slope and intercept", 'interact');
addPage_2('de/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact');
addPage_2('de/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact');
addPage_2('de/regnEst', 'regnEst4', "Standard error of least squares slope", 'static');
addPage_2('de/regnEst', 'regnEst5', "95% confidence interval for slope", 'static');
addPage_2('de/regnEst', 'regnEst6', "Properties of confidence interval", 'interact');
addPage_2('de/regnEst', 'regnEst7', "Influences on accuracy", 'interact');
addSection('bk/german', 'sec_regnTest', "Testing regression parameters");
addPage_2('de/regnTest', 'regnTest1', "Importance of zero slope", 'interact');
addPage_2('de/regnTest', 'regnTest2', "Testing whether slope is zero", 'static');
addPage_2('de/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static');
addPage_2('de/regnTest', 'regnTest4', "Properties of p-values", 'interact');
addSection('bk/german', 'sec_regnPred', "Predicting the response");
addPage_2('de/regnPred', 'regnPred1', "Estimated response distn at X", 'interact');
addPage_2('de/regnPred', 'regnPred2', "Variability of estimate at X", 'interact');
addPage_2('de/regnPred', 'regnPred3', "Estimating the mean vs prediction", 'interact');
addPage_2('de/regnPred', 'regnPred4', "Confidence and prediction intervals", 'interact');
addSection('bk/german', 'sec_regnProblem', "Linear model assumptions");
addPage_2('de/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact');
addPage_2('de/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact');
addPage_2('de/regnProblem', 'regnProblem3', "Curvature and non-constant variance &mdash; transforming Y", 'interact');
addPage_2('de/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact');
addPage_2('de/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact');
addPage_2('de/regnProblem', 'regnProblem6', "Non-normal errors", 'interact');
addPage_2('de/regnProblem', 'regnProblem7', "Correlated errors", 'interact');

addChapter('bk/german', 'ch_independence', "Unabh&auml;ngigkeit");
addSection('bk/german', 'sec_prob', "Probability and applications");
addPage_2('de/prob', 'prob1', "Joint probabilities", 'interact');
addPage_2('de/prob', 'prob2', "Marginal probabilities", 'interact');
addPage_2('de/prob', 'prob3', "Conditional probabilities", 'interact');
addPage_2('de/prob', 'prob4', "Graphical display of probabilities", 'interact');
addPage_2('de/prob', 'prob5', "Calculations with probabilities", 'interact');
addSection('bk/german', 'sec_indep', "Independence");
addPage_2('de/indep', 'indep1', "Association between categorical variables", 'static');
addPage_2('de/indep', 'indep2', "Unabhängigkeit zwischen kategorialen Variablen", 'interact');
addPage_2('de/indep', 'indep3', "Unabhängigkeit von Stichproben", 'static');
addPage_2('de/indep', 'indep4', "Testen auf Unabhängigkeit", 'interact');
addPage_2('de/indep', 'indep5', "Chi-Quadrat Teststatistik", 'interact');
addPage_2('de/indep', 'indep6', "P-Wert des Chi-Quadrat-Test", 'interact');
addPage_2('de/indep', 'indep7', "Beispiele", 'static');
addPage_2('de/indep', 'indep8', "Vergleich von Gruppen", 'static');

var language = "de";
var logoGif = null;
var homeDir = "bk/german";
var versionGif = "images/castGerman";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Volltextsuche';
var summaryTextString = 'Übersicht';
var videoTextString = 'Video';
var appletTextString = 'Interact';
fullTabTooltip = 'Full version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Interactive version of page';
var chapterString = 'Kapitel';

var versionName = {'_g': 'Allgemeine', '_b': 'Biometrische', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Andere'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_g', '_b', '_c');
versions['structures6'] = new Array('_g', '_b');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_g', '_b', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('_g', '_a', '_b', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_g', '_b', '_c');
versions['displayInterp2'] = new Array('_g', '_b', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density7'] = new Array('_g', '_b', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_g', '_b', '_c', '_m');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_g', '_b');
versions['transform2'] = new Array('_g', '_b', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['counts4'] = new Array('_g', '_b', '_c');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship2'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_g', '_b', '_c');
versions['seasonal1'] = new Array('_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['seasonal5'] = new Array('_g', '_m', '_z');
versions['seasonal6'] = new Array('_g', '_m', '_z');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat6'] = new Array('_g', '_b', '_c');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['groupedCat3'] = new Array('_g', '_b', '_c');
versions['groupedCat4'] = new Array('_g', '_b', '_c');
versions['groupedCat5'] = new Array('_g', '_b', '_c');
versions['bivarCat1'] = new Array('_g', '_b', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['logistic1'] = new Array('_g', '_b', '_c');
versions['logistic2'] = new Array('_g', '_b', '_c');
versions['logistic4'] = new Array('_g', '_b', '_c');
versions['multivariate1'] = new Array('_g', '_b', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_g', '_b', '_c');
versions['lurking2'] = new Array('_g', '_b');
versions['lurking3'] = new Array('_g', '_c');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b', '_c');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_g', '_b', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_g', '_b', '_c');
versions['randomMean6'] = new Array('_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');
versions['sampPractice1'] = new Array('_g', '_b');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_g', '_b');
versions['designTwo1'] = new Array('_g', '_b');
versions['designTwo2'] = new Array('_g', '_b');
versions['designTwo6'] = new Array('_g', '_b');
versions['designPrelim2'] = new Array('_g', '_c');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');
versions['estOther3'] = new Array('_g', '_c', '_m');
versions['estOther5'] = new Array('_g', '_b');
versions['estOther6'] = new Array('_g', '_c', '_m');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro3'] = new Array('_g', '_b', '_c');
versions['testIntro5'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_g', '_b', '_c');
versions['testPropn1'] = new Array('_g', '_b', '_c');
versions['testPropn2'] = new Array('_g', '_b', '_c');
versions['testPropn3'] = new Array('_g', '_b', '_c');
versions['testPropn4'] = new Array('_g', '_b', '_c');
versions['testPropn5'] = new Array('_g', '_b');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_g', '_b', '_c');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_g', '_b', '_c');
versions['testPValue5'] = new Array('_g', '_b', '_c');
versions['twoGroupModel1'] = new Array('_g', '_b', '_c');
versions['twoGroupModel2'] = new Array('_g', '_b', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['twoGroupInf3'] = new Array('_g', '_b', '_c');
versions['twoGroupInf4'] = new Array('_g', '_b', '_c');
versions['twoGroupInf5'] = new Array('_g', '_b', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_g', '_b', '_c');
versions['testPaired2'] = new Array('_g', '_b', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_g', '_b', '_c');
versions['multiGroup3'] = new Array('_g', '_b', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_g', '_a', '_b', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_g', '_b', '_c');
versions['regnModel1'] = new Array('_g', '_b', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_g', '_b', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_g', '_b', '_c');
versions['regnPred3'] = new Array('_g', '_b', '_c');
versions['regnPred4'] = new Array('_g', '_b');
versions['regnProblem3'] = new Array('_g', '_b');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_g', '_b', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
