
addBook('bk/idems_data', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/general', 'ch_intro', "Introduction: About Data", null, 'v_ch_intro');
addSection('bk/general', 'sec_context', "Context");
addPage_2('en/context', 'context1', "Importance of context", 'static', 'en/context', 's_context1', 'en/context', 'v_context1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3', 'en/context', 'v_context3');
addSection('bk/general', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures1', "Variables and individuals", 'interact', 'en/structures', 's_structures1', 'en/structures', 'v_structures1');
addPage_2('en/structures', 'structures2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures3');
addPage_2('en/structures', 'structures4', "Meaningful variables", 'interact', 'en/structures', 's_structures4', 'en/structures', 'v_structures4');
addPage_2('en/structures', 'structures5', "Time-ordered data", 'static', 'en/structures', 's_structures5', 'en/structures', 'v_structures5');
addPage_2('en/structures', 'structures6', "Multi-level data", 'interact', 'en/structures', 's_structures6', 'en/structures', 'v_structures6');
addPage_2('en/structures', 'structures7', "Structure of the e-book", 'static', 'en/structures', 's_structures7', 'en/structures', 'v_structures7');
addSection('bk/general', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');
addPage_2('en/variation', 'variation5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5', 'en/variation', 'v_variation5');
addPage_2('en/variation', 'variation6', "Predicting future variation", 'static', 'en/variation', 's_variation6', 'en/variation', 'v_variation6');

addChapter('bk/general', 'ch_univar', "One Numerical Variable", null, 'v_ch_univar');
addSection('bk/general', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay1');
addPage_2('en/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay2');
addPage_2('en/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay4');
addPage_2('en/valueDisplay', 'valueDisplay5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5', 'en/valueDisplay', 'v_valueDisplay5');
addPage_2('en/valueDisplay', 'valueDisplay6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6', 'en/valueDisplay', 'v_valueDisplay6');
addPage_2('en/valueDisplay', 'valueDisplay7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7', 'en/valueDisplay', 'v_valueDisplay7');
addSection('bk/general', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp1');
addPage_2('en/displayInterp', 'displayInterp2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp2');
addPage_2('en/displayInterp', 'displayInterp3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp3');
addPage_2('en/displayInterp', 'displayInterp4', "Names of individuals", 'interact', 'en/displayInterp', 's_displayInterp4', 'en/displayInterp', 'v_displayInterp4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp6');
addSection('bk/general', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2', 'en/density', 'v_density2');
addPage_2('en/density', 'density3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density3');
addPage_2('en/density', 'density4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('en/density', 'density6', "Comparing groups", 'interact', 'en/density', 's_density6', 'en/density', 'v_density6');
addPage_2('en/density', 'density7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7', 'en/density', 'v_density7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8', 'en/density', 'v_density8');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9', 'en/density', 'v_density9');
addPage_2('en/density', 'density10', "Kernel density estimates", 'interact', 'en/density', 's_density10', 'en/density', 'v_density10');
addPage_2('en/density', 'density11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11', 'en/density', 'v_density11');
addSection('bk/general', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7', 'en/boxPlot', 'v_boxPlot7');
addSection('bk/general', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addSection('bk/general', 'sec_moreVariation', "More about variation (optional)");
addPage_2('en/moreVariation', 'moreVariation1', "Effect of outliers", 'interact', 'en/moreVariation', 's_moreVariation1', 'en/moreVariation', 'v_moreVariation1');
addPage_2('en/moreVariation', 'moreVariation2', "Standard deviation of grouped data", 'interact', 'en/moreVariation', 's_moreVariation2', 'en/moreVariation', 'v_moreVariation2');
addPage_2('en/moreVariation', 'moreVariation3', "Explained and unexplained variation", 'interact', 'en/moreVariation', 's_moreVariation3', 'en/moreVariation', 'v_moreVariation3');
addPage_2('en/moreVariation', 'moreVariation4', "Variance and degrees of freedom", 'static', 'en/moreVariation', 's_moreVariation4', 'en/moreVariation', 'v_moreVariation4');
addPage_2('en/moreVariation', 'moreVariation5', "Root mean squared error", 'interact', 'en/moreVariation', 's_moreVariation5', 'en/moreVariation', 'v_moreVariation5');
addPage_2('en/moreVariation', 'moreVariation6', "Distances from the mean", 'interact', 'en/moreVariation', 's_moreVariation6', 'en/moreVariation', 'v_moreVariation6');
addSection('bk/general', 'sec_percentile', "Proportions and percentiles");
addPage_2('en/percentile', 'percentile1', "Illustrative data set", 'interact', 'en/percentile', 's_percentile1', 'en/percentile', 'v_percentile1');
addPage_2('en/percentile', 'percentile2', "Cumulative proportions", 'interact', 'en/percentile', 's_percentile2', 'en/percentile', 'v_percentile2');
addPage_2('en/percentile', 'percentile3', "Graph of cumulative proportions", 'interact', 'en/percentile', 's_percentile3', 'en/percentile', 'v_percentile3');
addPage_2('en/percentile', 'percentile4', "Percentiles", 'interact', 'en/percentile', 's_percentile4', 'en/percentile', 'v_percentile4');
addPage_2('en/percentile', 'percentile5', "Displaying percentiles", 'interact', 'en/percentile', 's_percentile5', 'en/percentile', 'v_percentile5');
addPage_2('en/percentile', 'percentile6', "Comparing groups", 'interact', 'en/percentile', 's_percentile6', 'en/percentile', 'v_percentile6');
addPage_2('en/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact', 'en/percentile', 's_percentile7', 'en/percentile', 'v_percentile7');
addPage_2('en/percentile', 'percentile8', "Better definition of percentiles", 'interact', 'en/percentile', 's_percentile8', 'en/percentile', 'v_percentile8');
addSection('bk/general', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1', 'en/counts', 'v_counts1');
addPage_2('en/counts', 'counts2', "Histograms for counts", 'interact', 'en/counts', 's_counts2', 'en/counts', 'v_counts2');
addPage_2('en/counts', 'counts3', "Bar charts", 'interact', 'en/counts', 's_counts3', 'en/counts', 'v_counts3');
addPage_2('en/counts', 'counts4', "Mean and st devn", 'static', 'en/counts', 's_counts4', 'en/counts', 'v_counts4');

addChapter('bk/general', 'ch_cat', "Categorical Variables", null, 'v_ch_cat');
addSection('bk/general', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1', 'en/freqTable', 'v_freqTable1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addSection('bk/general', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2', 'en/univarCat', 'v_univarCat2');
addPage_2('en/univarCat', 'univarCat3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat3', 'en/univarCat', 'v_univarCat3');
addPage_2('en/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat4');
addPage_2('en/univarCat', 'univarCat5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat5');
addPage_2('en/univarCat', 'univarCat6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat6', 'en/univarCat', 'v_univarCat6');
addPage_2('en/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat7');
addSection('bk/general', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1', 'en/groupedCat', 'v_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat2', 'en/groupedCat', 'v_groupedCat2');
addPage_2('en/groupedCat', 'groupedCat3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat3', 'en/groupedCat', 'v_groupedCat3');
addPage_2('en/groupedCat', 'groupedCat4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4', 'en/groupedCat', 'v_groupedCat4');
addPage_2('en/groupedCat', 'groupedCat5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5', 'en/groupedCat', 'v_groupedCat5');
addSection('bk/general', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2', 'en/tableDisplay', 'v_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4', 'en/tableDisplay', 'v_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5', 'en/tableDisplay', 'v_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6', 'en/tableDisplay', 'v_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7', 'en/tableDisplay', 'v_tableDisplay7');

addChapter('bk/general', 'ch_bivar', "Two Numerical Variables", null, 'v_ch_bivar');
addSection('bk/general', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot1', "More than one variable", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2', 'en/scatterplot', 'v_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5', 'en/scatterplot', 'v_scatterplot5');
addSection('bk/general', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal1', "Interest in relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2', 'en/causal', 'v_causal2');
addPage_2('en/causal', 'causal3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3', 'en/causal', 'v_causal3');
addPage_2('en/causal', 'causal4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4', 'en/causal', 'v_causal4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5', 'en/causal', 'v_causal5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'en/relationship', 'v_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4', 'en/relationship', 'v_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship5');
addSection('bk/general', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation1', 'en/correlation', 'v_correlation1');
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2', 'en/correlation', 'v_correlation2');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3', 'en/correlation', 'v_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4', 'en/correlation', 'v_correlation4');
addPage_2('en/correlation', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5', 'en/correlation', 'v_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6', 'en/correlation', 'v_correlation6');
addSection('bk/general', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1', 'en/leastSqrs', 'v_leastSqrs1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2', 'en/leastSqrs', 'v_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5', 'en/leastSqrs', 'v_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6', 'en/leastSqrs', 'v_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y and predicting X", 'interact', 'en/leastSqrs', 's_leastSqrs7', 'en/leastSqrs', 'v_leastSqrs7');

var language = "en";
var logoGif = null;
var homeDir = "bk/idems_data";
var versionGif = "images/castGeneral";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "5";

var localVideos = false;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_m': 'Climatic', '_o': 'Official stats', '_b': 'Biometric', '_c': 'Business', '_a': 'African'};
var versions = {};
versions['context1'] = new Array('_g', '_m', '_o', '_b', '_c');
versions['context2'] = new Array('_g', '_o', '_m');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_c', '_b');
versions['structures2'] = new Array('_g', '_b', '_c', '_a');
versions['structures3'] = new Array('_g', '_o', '_c');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_g', '_c', '_b');
versions['structures6'] = new Array('_g', '_b');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_g', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_m', '_c', '_b');
versions['valueDisplay3'] = new Array('_g', '_m', '_c', '_b');
versions['valueDisplay4'] = new Array('_g', '_m', '_b', '_c');
versions['valueDisplay5'] = new Array('_g', '_m', '_b', '_c', '_a');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_g', '_c', '_b');
versions['displayInterp2'] = new Array('_g', '_m', '_b', '_c');
versions['displayInterp3'] = new Array('_g', '_m', '_c');
versions['displayInterp4'] = new Array('_g', '_b');
versions['displayInterp6'] = new Array('_g', '_b', '_c');
versions['density3'] = new Array('_g', '_m', '_c');
versions['density4'] = new Array('_g', '_m', '_c', '_b');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density7'] = new Array('_g', '_b', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_g', '_b', '_m', '_c');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_m', '_b', '_c');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_c', '_b');
versions['counts3'] = new Array('_g', '_c');
versions['counts4'] = new Array('_g', '_b', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_b', '_a');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat6'] = new Array('_g', '_c', '_b');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['groupedCat3'] = new Array('_g', '_b', '_c');
versions['groupedCat4'] = new Array('_g', '_c', '_b');
versions['groupedCat5'] = new Array('_g', '_c', '_b');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['scatterplot1'] = new Array('_g', '_c', '_b');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['causal1'] = new Array('_g', '_c', '_b');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_c', '_b');
versions['causal5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_c', '_b');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');

bookLoaded = true;
