
addBook('bk/sadc_c2', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/african_c1', 'ch_intro', "Introduction: About Data");
addSection('bk/general', 'sec_context', "Context");
addPage_2('en/context', 'context1', "Importance of context", 'static', 'en/context', 's_context1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3');
addSection('bk/african_c1', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures_a1', "Variables and individuals", 'interact', 'en/structures', 's_structures1');
addPage_2('en/structures', 'structures_a2', "Types of variable", 'interact', 'en/structures', 's_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3');
addPage_2('en/structures', 'structures_a4', "Meaningful variables", 'interact', 'en/structures', 's_structures4');
addPage_2('en/structures', 'structures_b5', "Time-ordered data", 'static', 'en/structures', 's_structures5');
addPage_2('en/structures', 'structures_b6', "Multi-level data", 'interact', 'en/structures', 's_structures6');
addSection('bk/african_c1', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3');
addPage_2('en/variation', 'variation_a4', "Variability in survey data", 'interact', 'en/variation', 's_variation4');
addPage_2('en/variation', 'variation5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5');
addPage_2('en/variation', 'variation_a6', "Information from variation", 'static', 'en/variation', 's_variation6');

addChapter('bk/african_c1', 'ch_graphSumm', "Graphical Summaries");
addSection('bk/sadc_c2', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2');
addPage_2('en/density', 'density_m3', "Choice of classes", 'interact', 'en/density', 's_density3');
addPage_2('en/density', 'density_m4', "Histograms of small data sets", 'interact', 'en/density', 's_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5');
addPage_2('en/density', 'density_b6', "Comparing groups", 'interact', 'en/density', 's_density6');
addPage_2('en/density', 'density_m7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9');
addPage_2('en/density', 'density10', "Kernel density estimates", 'interact', 'en/density', 's_density10');
addPage_2('en/density', 'density_m11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11');
addSection('bk/african_c1', 'sec_boxPlot', "Median, quartiles & box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6');
addSection('bk/sadc_c2', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1');
addPage_2('en/counts', 'counts2', "Histograms for counts", 'interact', 'en/counts', 's_counts2');
addPage_2('en/counts', 'counts3', "Bar charts", 'interact', 'en/counts', 's_counts3');

addChapter('bk/african_c1', 'ch_numSumm', "Numerical Summaries");
addSection('bk/african_c1', 'sec_center', "Describing centre");
addPage_2('en/centerSpread', 'centerSpread_b1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread_b2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread_m3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4');
addSection('bk/african_c1', 'sec_spread', "Describing spread");
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8');
addPage_2('en/moreVariation', 'moreVariation1', "Effect of outliers", 'interact', 'en/moreVariation', 's_moreVariation1');
addPage_2('en/counts', 'counts_b4', "Mean & sd for discrete data#?# (opt)", 'static', 'en/counts', 's_counts4');
addSection('bk/african_c1', 'sec_varAndGroups', "Variation and groups");
addPage_2('en/moreVariation', 'moreVariation2', "Standard deviation of grouped data", 'interact', 'en/moreVariation', 's_moreVariation2');
addPage_2('en/moreVariation', 'moreVariation3', "Explained and unexplained variation", 'interact', 'en/moreVariation', 's_moreVariation3');
addPage_2('en/multiGroup', 'multiGroup_a4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup_a6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup6');
addPage_2('en/multiGroup', 'multiGroup_a7', "Analysis of variance", 'interact', 'en/multiGroup', 's_multiGroup7');
addSection('bk/african_c1', 'sec_moreVariation', "More about variation (optional)");
addPage_2('en/moreVariation', 'moreVariation4', "Variance and degrees of freedom", 'static', 'en/moreVariation', 's_moreVariation4');
addPage_2('en/moreVariation', 'moreVariation5', "Root mean squared error", 'interact', 'en/moreVariation', 's_moreVariation5');
addPage_2('en/moreVariation', 'moreVariation6', "Distances from the mean", 'interact', 'en/moreVariation', 's_moreVariation6');

addChapter('bk/african_c1', 'ch_percentiles', "Proportions and Percentiles");
addSection('bk/sadc_c2', 'sec_propn', "Proportions");
addPage_2('en/percentile', 'percentile1', "Illustrative data set", 'interact', 'en/percentile', 's_percentile1');
addPage_2('en/percentile', 'percentile2', "Cumulative proportions", 'interact', 'en/percentile', 's_percentile2');
addPage_2('en/percentile', 'percentile3', "Graph of cumulative proportions", 'interact', 'en/percentile', 's_percentile3');
addPage_2('en/percentile', 'percentile_m9', "Other ways to express proportions", 'interact');
addPage_2('en/percentile', 'percentile_m10', "Other data sets", 'interact');
addPage_2('en/percentile', 'e_percentile_m4', "Exercises based on real data", 'static');
addSection('bk/sadc_c2', 'sec_percentile', "Percentiles");
addPage_2('en/percentile', 'percentile4', "Percentiles", 'interact', 'en/percentile', 's_percentile4');
addPage_2('en/percentile', 'percentile5', "Displaying percentiles", 'interact', 'en/percentile', 's_percentile5');
addPage_2('en/percentile', 'e_percentile6', "Percentiles", 'static');
addPage_2('en/percentile', 'percentile6', "Comparing groups", 'interact', 'en/percentile', 's_percentile6');
addPage_2('en/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact', 'en/percentile', 's_percentile7');
addPage_2('en/percentile', 'percentile8', "Better definition of percentiles", 'interact', 'en/percentile', 's_percentile8');

addChapter('bk/general', 'ch_cat', "Categorical Variables", null, 'v_ch_cat');
addSection('bk/biometric', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat_b2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat_b2');
addPage_2('en/groupedCat', 'groupedCat_b3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat3');
addPage_2('en/groupedCat', 'groupedCat_b4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4');
addPage_2('en/groupedCat', 'groupedCat_b5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5');
addSection('bk/general', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7');

addChapter('bk/african_c1', 'ch_relns', "Relationships between Variables");
addSection('bk/biometric', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot_b1', "Bivariate data sets", 'interact', 'en/scatterplot', 's_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5');

addChapter('bk/african_c1', 'ch_transform', "Transformations");
addSection('bk/biometric', 'sec_transform', "Transformations");
addPage_2('en/transform', 'transform_b1', "Linear transformations", 'interact', 'en/transform', 's_transform1');
addPage_2('en/transform', 'transform_b2', "Log transformations", 'interact', 'en/transform', 's_transform2');
addPage_2('en/transform', 'transform3', "When to use log transform?", 'interact', 'en/transform', 's_transform3');
addPage_2('en/transform', 'transform4', "Power transformations", 'interact', 'en/transform', 's_transform4');
addPage_2('en/transform', 'transform5', "Power transforms &amp; skewness", 'interact', 'en/transform', 's_transform5');

addChapter('bk/african_c1', 'ch_multivar', "Exploring Multivariate Data");
addSection('bk/african_c1', 'sec_thirdVar', "Representing a third variable");
addPage_2('en/multivariate', 'multivariate_b1', "Representing a third variable", 'interact', 'en/multivariate', 's_multivariate1');
addPage_2('en/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact', 'en/multivariate', 's_multivariate2');
addSection('bk/sadc_c2', 'sec_brushing', "Scatterplot matrices & brushing");
addPage_2('en/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact', 'en/multivariate', 's_multivariate3');
addPage_2('en/multivariate', 'multivariate5', "Slicing", 'interact', 'en/multivariate', 's_multivariate5');
addPage_2('en/regnGroups', 'regnGroups7', "Scatterplot matrix with groups", 'interact', 'en/regnGroups', 's_regnGroups7');

addChapter('bk/general', 'ch_timeSeries', "Time Series", null, 'v_ch_timeSeries');
addSection('bk/general', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1');
addPage_2('en/timePlot', 'timePlot2', "Patterns in time series", 'interact', 'en/timePlot', 's_timePlot2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3');
addSection('bk/sadc_c2', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2');
addPage_2('en/smoothing', 'smoothing3', "Robust smoothing", 'interact', 'en/smoothing', 's_smoothing3');
addPage_2('en/smoothing', 'smoothing4', "Exponential smoothing", 'interact', 'en/smoothing', 's_smoothing4');

addChapter('bk/african_c2', 'ch_modelVar', "Sampling and Variability");
addSection('bk/african_c2', 'sec_modelIntro', "Intro - generalising from data");
addPage_2('bk/african_c2', 'modelIntro1', "Data as representatives", 'interact');
addPage_2('bk/african_c2', 'modelIntro2', "Randomness of data", 'interact');
addPage_2('bk/african_c2', 'modelIntro3', "Modelling randomness", 'interact');
addPage_2('bk/african_c2', 'modelIntro4', "Introduction to the idea of inference", 'static');
addSection('bk/african_c2', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp_a1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2');
addPage_2('en/popSamp', 'popSamp_a3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3');
addPage_2('en/popSamp', 'popSamp_b4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4');
addPage_2('en/popSamp', 'popSamp_b5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6');

addChapter('bk/african_c2', 'ch_sampSurv', "Sample Surveys");
addSection('bk/african_c2', 'sec_sampSchemes', "Sampling schemes");
addPage_2('en/sampPractice', 'sampPractice_b1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3');
addSection('bk/african_c2', 'sec_sampErr', "Sampling & non-sampling errors");
addPage_2('en/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice_b5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5');
addPage_2('en/sampPractice', 'sampPractice_b6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6');
addSection('bk/african_c2', 'sec_survey', "Conducting a sample survey");
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7');

var language = "en";
var logoGif = "logo_sadc.gif";
var homeDir = "bk/sadc_c2";
var versionGif = "images/castSadc_c2";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "12";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_b': 'Biometric', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_a', '_g', '_b', '_c');
versions['structures2'] = new Array('_a', '_g', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_a', '_g', '_c');
versions['structures5'] = new Array('_b', '_g', '_c');
versions['structures6'] = new Array('_b', '_g');
versions['variation4'] = new Array('_a', '_g');
versions['variation5'] = new Array('_g', '_c');
versions['variation6'] = new Array('_a', '_g');
versions['density3'] = new Array('_m', '_g', '_c');
versions['density4'] = new Array('_m', '_g', '_b', '_c');
versions['density6'] = new Array('_b', '_g', '_c');
versions['density7'] = new Array('_m', '_g', '_b', '_c');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_m', '_g', '_b', '_c');
versions['boxPlot6'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['centerSpread1'] = new Array('_b', '_g');
versions['centerSpread2'] = new Array('_b', '_g');
versions['centerSpread3'] = new Array('_m', '_g', '_b', '_c');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts4'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_a', '_g');
versions['multiGroup6'] = new Array('_a', '_g', '_b', '_c');
versions['multiGroup7'] = new Array('_a', '_g');
versions['e_percentile4'] = new Array('_m', '_g');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_b', '_g', '_c');
versions['groupedCat3'] = new Array('_b', '_g', '_c');
versions['groupedCat4'] = new Array('_b', '_g', '_c');
versions['groupedCat5'] = new Array('_b', '_g', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['scatterplot1'] = new Array('_b', '_g', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['transform1'] = new Array('_b', '_g');
versions['transform2'] = new Array('_b', '_g', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['multivariate1'] = new Array('_b', '_g', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_g', '_b', '_c');
versions['popSamp1'] = new Array('_a', '_g', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_a', '_g', '_b', '_c');
versions['popSamp4'] = new Array('_b', '_g');
versions['popSamp5'] = new Array('_b', '_g', '_c');
versions['sampPractice1'] = new Array('_b', '_g');
versions['sampPractice5'] = new Array('_b', '_g', '_c');
versions['sampPractice6'] = new Array('_b', '_g');

bookLoaded = true;
