
addBook('bk/climatic_c1', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/climatic_c1', 'ch_intro', "Introduction: About Data");
addSection('bk/climatic_c1', 'sec_context', "Context & the statistical process");
addPage_2('en/context', 'context_m1', "Importance of context", 'static', 'en/context', 's_context1', 'en/context', 'v_context1');
addPage_2('en/context', 'context_m2', "Statistics", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('en/context', 'context_b3', "The statistical process", 'static', 'en/context', 's_context3', 'en/context', 'v_context_b3');
addSection('bk/climatic_c1', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures_a1', "Variables and individuals", 'interact', 'en/structures', 's_structures1', 'en/structures', 'v_structures1');
addPage_2('en/structures', 'structures_a2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures3');
addPage_2('en/structures', 'structures_a4', "Meaningful variables", 'interact', 'en/structures', 's_structures4', 'en/structures', 'v_structures4');
addPage_2('en/structures', 'structures_b5', "Time-ordered data", 'static', 'en/structures', 's_structures5', 'en/structures', 'v_structures_b5');
addPage_2('en/structures', 'structures_b6', "Multi-level data", 'interact', 'en/structures', 's_structures6', 'en/structures', 'v_structures_b6');
addSection('bk/climatic_c1', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('en/variation', 'variation_a4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');
addPage_2('en/variation', 'variation5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5', 'en/variation', 'v_variation5');
addPage_2('en/variation', 'variation_a6', "Information from variation", 'static', 'en/variation', 's_variation6', 'en/variation', 'v_variation6');

addChapter('bk/climatic_c1', 'ch_displayData', "Displaying Data");
addSection('bk/climatic_c1', 'sec_dotPlot', "Dot plots");
addPage_2('en/valueDisplay', 'valueDisplay_b1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay_b1');
addPage_2('en/valueDisplay', 'valueDisplay_b2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay_b2');
addPage_2('en/valueDisplay', 'valueDisplay_m3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay_m4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay4');
addSection('bk/climatic_c1', 'sec_stemLeaf', "Stem and leaf plots");
addPage_2('en/valueDisplay', 'valueDisplay_m5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5', 'en/valueDisplay', 'v_valueDisplay5');
addPage_2('en/valueDisplay', 'valueDisplay_m6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6', 'en/valueDisplay', 'v_valueDisplay6');
addPage_2('en/valueDisplay', 'valueDisplay_m7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7', 'en/valueDisplay', 'v_valueDisplay7');
addSection('bk/climatic_c1', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp_b1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp_b1');
addPage_2('en/displayInterp', 'displayInterp_b2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp_b2');
addPage_2('en/displayInterp', 'displayInterp3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp3');
addPage_2('en/displayInterp', 'displayInterp_b4', "Extra information about individuals", 'interact', 'en/displayInterp', 's_displayInterp4', 'en/displayInterp', 'v_displayInterp_b4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp6');

addChapter('bk/climatic_c1', 'ch_graphSumm', "Graphical Summaries");
addSection('bk/climatic_c1', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2', 'en/density', 'v_density2');
addPage_2('en/density', 'density_m3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density3');
addPage_2('en/density', 'density_m4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('en/density', 'density_b6', "Comparing groups", 'interact', 'en/density', 's_density6', 'en/density', 'v_density_b6');
addPage_2('en/density', 'density_m7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7', 'en/density', 'v_density7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8', 'en/density', 'v_density8');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9', 'en/density', 'v_density9');
addPage_2('en/density', 'density10', "Kernel density estimates", 'interact', 'en/density', 's_density10', 'en/density', 'v_density10');
addPage_2('en/density', 'density_m11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11', 'en/density', 'v_density11');
addSection('bk/climatic_c1', 'sec_boxPlot', "Median, quartiles & box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot6');
addSection('bk/climatic_c1', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts_b1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1', 'en/counts', 'v_counts_b1');
addPage_2('en/counts', 'counts_b2', "Histograms for counts", 'interact', 'en/counts', 's_counts2', 'en/counts', 'v_counts_b2');
addPage_2('en/counts', 'counts3', "Bar charts", 'interact', 'en/counts', 's_counts3', 'en/counts', 'v_counts3');

addChapter('bk/climatic_c1', 'ch_numSumm', "Numerical Summaries");
addSection('bk/climatic_c1', 'sec_center', "Describing centre");
addPage_2('en/centerSpread', 'centerSpread_b1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread_b1');
addPage_2('en/centerSpread', 'centerSpread_b2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread_b2');
addPage_2('en/centerSpread', 'centerSpread_m3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addSection('bk/climatic_c1', 'sec_spread', "Describing spread");
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addPage_2('en/moreVariation', 'moreVariation1', "Effect of outliers", 'interact', 'en/moreVariation', 's_moreVariation1', 'en/moreVariation', 'v_moreVariation1');
addPage_2('en/counts', 'counts_b4', "Mean & sd for discrete data#?# (opt)", 'static', 'en/counts', 's_counts4', 'en/counts', 'v_counts_b4');
addSection('bk/climatic_c1', 'sec_varAndGroups', "Variation and groups");
addPage_2('en/moreVariation', 'moreVariation2', "Standard deviation of grouped data", 'interact', 'en/moreVariation', 's_moreVariation2', 'en/moreVariation', 'v_moreVariation2');
addPage_2('en/moreVariation', 'moreVariation3', "Explained and unexplained variation", 'interact', 'en/moreVariation', 's_moreVariation3', 'en/moreVariation', 'v_moreVariation3');
addPage_2('en/multiGroup', 'multiGroup_a4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup_a6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup6', 'en/multiGroup', 'v_multiGroup6');
addPage_2('en/multiGroup', 'multiGroup_a7', "Analysis of variance", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addSection('bk/climatic_c1', 'sec_moreVariation', "More about variation (optional)");
addPage_2('en/moreVariation', 'moreVariation4', "Variance and degrees of freedom", 'static', 'en/moreVariation', 's_moreVariation4', 'en/moreVariation', 'v_moreVariation4');
addPage_2('en/moreVariation', 'moreVariation5', "Root mean squared error", 'interact', 'en/moreVariation', 's_moreVariation5', 'en/moreVariation', 'v_moreVariation5');
addPage_2('en/moreVariation', 'moreVariation6', "Distances from the mean", 'interact', 'en/moreVariation', 's_moreVariation6', 'en/moreVariation', 'v_moreVariation6');

addChapter('bk/climatic_c1', 'ch_percentiles', "Proportions and Percentiles");
addSection('bk/climatic_c1', 'sec_propn', "Proportions");
addPage_2('en/percentile', 'percentile1', "Illustrative data set", 'interact', 'en/percentile', 's_percentile1', 'en/percentile', 'v_percentile1');
addPage_2('en/percentile', 'percentile2', "Cumulative proportions", 'interact', 'en/percentile', 's_percentile2', 'en/percentile', 'v_percentile2');
addPage_2('en/percentile', 'percentile3', "Graph of cumulative proportions", 'interact', 'en/percentile', 's_percentile3', 'en/percentile', 'v_percentile3');
addPage_2('en/percentile', 'percentile_m9', "Other ways to express proportions", 'interact');
addPage_2('en/percentile', 'percentile_m10', "Other data sets", 'interact');
addPage_2('en/percentile', 'e_percentile_m4', "Exercises based on real data", 'static');
addSection('bk/climatic_c1', 'sec_percentile', "Percentiles");
addPage_2('en/percentile', 'percentile4', "Percentiles", 'interact', 'en/percentile', 's_percentile4', 'en/percentile', 'v_percentile4');
addPage_2('en/percentile', 'percentile5', "Displaying percentiles", 'interact', 'en/percentile', 's_percentile5', 'en/percentile', 'v_percentile5');
addPage_2('en/percentile', 'e_percentile6', "Percentiles", 'static');
addPage_2('en/percentile', 'percentile6', "Comparing groups", 'interact', 'en/percentile', 's_percentile6', 'en/percentile', 'v_percentile6');
addPage_2('en/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact', 'en/percentile', 's_percentile7', 'en/percentile', 'v_percentile7');
addPage_2('en/percentile', 'percentile8', "Better definition of percentiles", 'interact', 'en/percentile', 's_percentile8', 'en/percentile', 'v_percentile8');

addChapter('bk/general', 'ch_cat', "Categorical Variables", null, 'v_ch_cat');
addSection('bk/climatic_c1', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1', 'en/freqTable', 'v_freqTable1');
addPage_2('en/freqTable', 'freqTable_a2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable_a2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/tableDisplay', 'tableDisplay_a1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addSection('bk/climatic_c1', 'sec_bar', "Bar charts");
addPage_2('en/univarCat', 'univarCat_a1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2', 'en/univarCat', 'v_univarCat2');
addPage_2('en/univarCat', 'univarCat_a3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat_a3', 'en/univarCat', 'v_univarCat3');
addSection('bk/climatic_c1', 'sec_pie', "Pie charts");
addPage_2('en/univarCat', 'univarCat_b4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat_b4');
addPage_2('en/univarCat', 'univarCat_b5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat_b5');
addPage_2('en/univarCat', 'univarCat_b6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat_b6', 'en/univarCat', 'v_univarCat_b6');
addPage_2('en/univarCat', 'univarCat_b7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat_b7');
addSection('bk/biometric', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1', 'en/groupedCat', 'v_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat_b2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat_b2', 'en/groupedCat', 'v_groupedCat_b2');
addPage_2('en/groupedCat', 'groupedCat_b3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat3', 'en/groupedCat', 'v_groupedCat_b3');
addPage_2('en/groupedCat', 'groupedCat_b4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4', 'en/groupedCat', 'v_groupedCat_b4');
addPage_2('en/groupedCat', 'groupedCat_b5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5', 'en/groupedCat', 'v_groupedCat_b5');

var language = "en";
var logoGif = null;
var homeDir = "bk/climatic_c1";
var versionGif = "images/castClimatic_c1";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "7";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_m': 'Climatic', '_g': 'General', '_b': 'Biometric', '_c': 'Business', '_o': 'Official stats', '_a': 'African'};
var versions = {};
versions['context1'] = new Array('_m', '_g', '_b', '_c', '_o');
versions['context2'] = new Array('_m', '_g', '_o');
versions['context3'] = new Array('_b', '_g');
versions['structures1'] = new Array('_a', '_g', '_b', '_c');
versions['structures2'] = new Array('_a', '_g', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_a', '_g', '_c');
versions['structures5'] = new Array('_b', '_g', '_c');
versions['structures6'] = new Array('_b', '_g');
versions['variation4'] = new Array('_a', '_g');
versions['variation5'] = new Array('_g', '_c');
versions['variation6'] = new Array('_a', '_g');
versions['valueDisplay1'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay2'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay3'] = new Array('_m', '_g', '_b', '_c');
versions['valueDisplay4'] = new Array('_m', '_g', '_b', '_c');
versions['valueDisplay5'] = new Array('_m', '_g', '_a', '_b', '_c');
versions['valueDisplay6'] = new Array('_m', '_g', '_c');
versions['valueDisplay7'] = new Array('_m', '_g', '_c');
versions['displayInterp1'] = new Array('_b', '_g', '_c');
versions['displayInterp2'] = new Array('_b', '_g', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_b', '_g');
versions['displayInterp6'] = new Array('_g', '_b', '_c');
versions['density3'] = new Array('_m', '_g', '_c');
versions['density4'] = new Array('_m', '_g', '_b', '_c');
versions['density6'] = new Array('_b', '_g', '_c');
versions['density7'] = new Array('_m', '_g', '_b', '_c');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_m', '_g', '_b', '_c');
versions['boxPlot6'] = new Array('_g', '_c');
versions['counts1'] = new Array('_b', '_g', '_c');
versions['counts2'] = new Array('_b', '_g', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['centerSpread1'] = new Array('_b', '_g');
versions['centerSpread2'] = new Array('_b', '_g');
versions['centerSpread3'] = new Array('_m', '_g', '_b', '_c');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts4'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_a', '_g');
versions['multiGroup6'] = new Array('_a', '_g', '_b', '_c');
versions['multiGroup7'] = new Array('_a', '_g');
versions['e_percentile4'] = new Array('_m', '_g');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_a', '_g', '_b');
versions['tableDisplay1'] = new Array('_a', '_g');
versions['univarCat1'] = new Array('_a', '_g', '_b');
versions['univarCat3'] = new Array('_a', '_g', '_b');
versions['univarCat4'] = new Array('_b', '_g', '_c');
versions['univarCat5'] = new Array('_b', '_g', '_c');
versions['univarCat6'] = new Array('_b', '_g', '_c');
versions['univarCat7'] = new Array('_b', '_g');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_b', '_g', '_c');
versions['groupedCat3'] = new Array('_b', '_g', '_c');
versions['groupedCat4'] = new Array('_b', '_g', '_c');
versions['groupedCat5'] = new Array('_b', '_g', '_c');

bookLoaded = true;
