
addBook('bk/gaelic', 'book_splash', "About this CAST e-book");

addChapter('bk/gaelic', 'ch_preface', "Preface");
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/gaelic', 'ch_intro', "Introduction: About Data");
addSection('bk/gaelic', 'sec_context', "Context");
addPage_2('gd/context', 'context1', "Importance of context", 'static');
addPage_2('gd/context', 'context2', "Statistics", 'static');
addPage_2('gd/context', 'context3', "The statistical process", 'static');
addSection('bk/gaelic', 'sec_structures', "Standard data structures");
addPage_2('gd/structures', 'structures1', "Variables and individuals", 'interact');
addPage_2('gd/structures', 'structures2', "Types of variable", 'interact');
addPage_2('gd/structures', 'structures3', "Categorical variables and groups", 'interact');
addPage_2('gd/structures', 'structures4', "Defining new variables", 'interact');
addPage_2('gd/structures', 'structures5', "Time-ordered data", 'static');
addPage_2('gd/structures', 'structures6', "Multi-level data", 'interact');
addPage_2('gd/structures', 'structures7', "Data structure to statistical method", 'static');
addSection('bk/gaelic', 'sec_variation', "Variation");
addPage_2('gd/variation', 'variation1', "Signal and noise", 'interact');
addPage_2('gd/variation', 'variation2', "Natural variability", 'interact');
addPage_2('gd/variation', 'variation3', "Variability caused by experiments", 'interact');
addPage_2('gd/variation', 'variation4', "Variability in survey data", 'interact');
addPage_2('gd/variation', 'variation5', "Explained and unexplained variation", 'static');
addPage_2('gd/variation', 'variation6', "Predicting future values", 'static');

addChapter('bk/gaelic', 'ch_univar', "One Numerical Variable");
addSection('bk/gaelic', 'sec_valueDisplay', "Graphical display of values");
addPage_2('gd/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact');
addPage_2('gd/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact');
addPage_2('gd/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact');
addPage_2('gd/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact');
addPage_2('gd/valueDisplay', 'valueDisplay5', "Stem and leaf plots", 'interact');
addPage_2('gd/valueDisplay', 'valueDisplay6', "Splitting the stems", 'interact');
addPage_2('gd/valueDisplay', 'valueDisplay7', "Drawing stem and leaf plots", 'interact');
addSection('bk/gaelic', 'sec_displayInterp', "Understanding distributions");
addPage_2('gd/displayInterp', 'displayInterp1', "Outliers", 'static');
addPage_2('gd/displayInterp', 'displayInterp2', "Clusters", 'interact');
addPage_2('gd/displayInterp', 'displayInterp3', "Distribution of values", 'static');
addPage_2('gd/displayInterp', 'displayInterp4', "Names of individuals", 'interact');
addPage_2('gd/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact');
addPage_2('gd/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact');
addSection('bk/gaelic', 'sec_density', "Histograms and density");
addPage_2('gd/density', 'density1', "Density of values", 'static');
addPage_2('gd/density', 'density2', "Histogram with equal class widths", 'interact');
addPage_2('gd/density', 'density3', "Choice of classes", 'interact');
addPage_2('gd/density', 'density4', "Histograms of small data sets", 'interact');
addPage_2('gd/density', 'density5', "Relative frequency and area", 'interact');
addPage_2('gd/density', 'density6', "Comparing groups", 'interact');
addPage_2('gd/density', 'density7', "Histograms with varying class widths", 'interact');
addPage_2('gd/density', 'density8', "Understanding histograms", 'interact');
addPage_2('gd/density', 'density9', "Frequency polygons", 'interact');
addPage_2('gd/density', 'density10', "Kernel density estimates", 'interact');
addPage_2('gd/density', 'density11', "Drawing histograms by hand", 'interact');
addSection('bk/gaelic', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('gd/boxPlot', 'boxPlot1', "The need to summarise", 'static');
addPage_2('gd/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact');
addPage_2('gd/boxPlot', 'boxPlot3', "Interpreting a box plots shape", 'interact');
addPage_2('gd/boxPlot', 'boxPlot4', "Displaying outliers", 'interact');
addPage_2('gd/boxPlot', 'boxPlot5', "Clusters", 'interact');
addPage_2('gd/boxPlot', 'boxPlot6', "Comparison of groups", 'interact');
addPage_2('gd/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact');
addSection('bk/gaelic', 'sec_centerSpread', "Describing centre and spread");
addPage_2('gd/centerSpread', 'centerSpread1', "Centre and spread", 'static');
addPage_2('gd/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact');
addPage_2('gd/centerSpread', 'centerSpread3', "Summaries of centre", 'interact');
addPage_2('gd/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact');
addPage_2('gd/centerSpread', 'centerSpread5', "Standard deviation", 'interact');
addPage_2('gd/centerSpread', 'centerSpread6', "Rules of thumb for standard deviation", 'static');
addPage_2('gd/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact');
addPage_2('gd/centerSpread', 'centerSpread8', "Warnings about mean and standard devn", 'static');
addSection('bk/gaelic', 'sec_moreVariation', "More about variation (optional)");
addPage_2('gd/moreVariation', 'moreVariation1', "Effect of outliers", 'interact');
addPage_2('gd/moreVariation', 'moreVariation2', "Standard deviation of grouped data", 'interact');
addPage_2('gd/moreVariation', 'moreVariation3', "Explained variation and predictions", 'interact');
addPage_2('gd/moreVariation', 'moreVariation4', "Variance and degrees of freedom", 'static');
addPage_2('gd/moreVariation', 'moreVariation5', "Root mean squared error", 'interact');
addPage_2('gd/moreVariation', 'moreVariation6', "Graphical interpretation of sd", 'interact');
addSection('bk/gaelic', 'sec_percentile', "Proportions and percentiles");
addPage_2('gd/percentile', 'percentile1', "Illustrative data set", 'interact');
addPage_2('gd/percentile', 'percentile2', "Cumulative proportions", 'interact');
addPage_2('gd/percentile', 'percentile3', "Graph of cumulative proportions", 'interact');
addPage_2('gd/percentile', 'percentile4', "Percentiles", 'interact');
addPage_2('gd/percentile', 'percentile5', "Displaying percentiles", 'interact');
addPage_2('gd/percentile', 'percentile6', "Comparing groups", 'interact');
addPage_2('gd/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact');
addPage_2('gd/percentile', 'percentile8', "Better definition of percentiles", 'interact');
addSection('bk/gaelic', 'sec_transform', "Transformations");
addPage_2('gd/transform', 'transform1', "Linear transformations", 'interact');
addPage_2('gd/transform', 'transform2', "Log transformations", 'interact');
addPage_2('gd/transform', 'transform3', "When to use log transform?", 'interact');
addPage_2('gd/transform', 'transform4', "Power transformations", 'interact');
addPage_2('gd/transform', 'transform5', "Effect of transformations on displays", 'interact');
addSection('bk/gaelic', 'sec_counts', "Discrete data (counts)");
addPage_2('gd/counts', 'counts1', "Discrete and continuous data", 'interact');
addPage_2('gd/counts', 'counts2', "Histograms for counts", 'interact');
addPage_2('gd/counts', 'counts3', "Bar charts", 'interact');
addPage_2('gd/counts', 'counts4', "Mean and st devn", 'static');

addChapter('bk/gaelic', 'ch_bivar', "Two Numerical Variables");
addSection('bk/gaelic', 'sec_scatterplot', "Scatterplots");
addPage_2('gd/scatterplot', 'scatterplot1', "More than one variable", 'interact');
addPage_2('gd/scatterplot', 'scatterplot2', "Scatterplots", 'interact');
addPage_2('gd/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact');
addPage_2('gd/scatterplot', 'scatterplot4', "Marginal distributions", 'interact');
addPage_2('gd/scatterplot', 'scatterplot5', "Time series", 'interact');
addSection('bk/gaelic', 'sec_relationship', "Understanding relationships");
addPage_2('gd/relationship', 'relationship1', "Strength of a relationship", 'interact');
addPage_2('gd/relationship', 'relationship2', "Outliers", 'interact');
addPage_2('gd/relationship', 'relationship3', "Clusters", 'interact');
addPage_2('gd/relationship', 'relationship4', "Dangers of over-interpretation", 'interact');
addPage_2('gd/relationship', 'relationship5', "Explanatory and response variables", 'static');
addSection('bk/gaelic', 'sec_correlation', "Correlation");
addPage_2('gd/correlation', 'correlation1', "Units for X and Y", 'interact');
addPage_2('gd/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact');
addPage_2('gd/correlation', 'correlation3', "Correlation coefficient", 'interact');
addPage_2('gd/correlation', 'correlation4', "Scatterplots and the value of r", 'interact');
addPage_2('gd/correlation', 'correlation5', "Nonlinear relationships", 'interact');
addPage_2('gd/correlation', 'correlation6', "R does not tell the whole story", 'interact');
addSection('bk/gaelic', 'sec_leastSqrs', "Least squares");
addPage_2('gd/leastSqrs', 'leastSqrs1', "Predicting Y from X", 'interact');
addPage_2('gd/leastSqrs', 'leastSqrs2', "Linear models", 'interact');
addPage_2('gd/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact');
addPage_2('gd/leastSqrs', 'leastSqrs4', "Least squares", 'interact');
addPage_2('gd/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact');
addPage_2('gd/leastSqrs', 'leastSqrs6', "Residual plots", 'interact');
addPage_2('gd/leastSqrs', 'leastSqrs7', "Predicting Y and predicting X", 'interact');
addSection('bk/gaelic', 'sec_curvature', "Nonlinear relationships");
addPage_2('gd/curvature', 'curvature1', "Transformations and correlation", 'interact');
addPage_2('gd/curvature', 'curvature2', "Transformations and models", 'interact');
addPage_2('gd/curvature', 'curvature3', "Quadratic models", 'interact');
addPage_2('gd/curvature', 'curvature4', "Dangers of extrapolation", 'interact');

addChapter('bk/gaelic', 'ch_timeSeries', "Time Series");
addSection('bk/gaelic', 'sec_timePlot', "Time series plots");
addPage_2('gd/timePlot', 'timePlot1', "Time series plots", 'interact');
addPage_2('gd/timePlot', 'timePlot2', "Patterns in time series", 'interact');
addPage_2('gd/timePlot', 'timePlot3', "Multiple time series", 'interact');
addSection('bk/gaelic', 'sec_smoothing', "Smoothing");
addPage_2('gd/smoothing', 'smoothing1', "Moving averages", 'interact');
addPage_2('gd/smoothing', 'smoothing2', "More about moving averages", 'interact');
addPage_2('gd/smoothing', 'smoothing3', "Robust smoothing", 'interact');
addPage_2('gd/smoothing', 'smoothing4', "Exponential smoothing", 'interact');
addPage_2('gd/smoothing', 'smoothing5', "Lowess smoothing of time series", 'interact');
addPage_2('gd/smoothing', 'smoothing6', "Lowess smoothing of scatterplots", 'interact');
addSection('bk/gaelic', 'sec_trend', "Long-term trend");
addPage_2('gd/trend', 'trend1', "Linear trend", 'interact');
addPage_2('gd/trend', 'trend2', "Quadratic trend", 'interact');
addPage_2('gd/trend', 'trend3', "Forecasting", 'interact');
addPage_2('gd/trend', 'trend4', "Polynomial trend", 'interact');
addPage_2('gd/trend', 'trend5', "Detrending a time series", 'interact');
addSection('bk/gaelic', 'sec_cyclic', "Short-term fluctuations");
addPage_2('gd/cyclic', 'cyclic1', "Autocorrelation", 'interact');
addPage_2('gd/cyclic', 'cyclic2', "AR(1) model for autocorrelation", 'interact');
addPage_2('gd/cyclic', 'cyclic3', "AR(1) model and trend", 'interact');
addPage_2('gd/cyclic', 'cyclic4', "Dangers of over-interpretation", 'interact');
addPage_2('gd/cyclic', 'cyclic5', "Cyclical patterns", 'interact');
addSection('bk/gaelic', 'sec_seasonal', "Seasonal data");
addPage_2('gd/seasonal', 'seasonal1', "Seasonal patterns", 'interact');
addPage_2('gd/seasonal', 'seasonal2', "Smoothing out seasonal variation", 'interact');
addPage_2('gd/seasonal', 'seasonal3', "Estimating the seasonal effect", 'interact');
addPage_2('gd/seasonal', 'seasonal4', "Deseasonalised data", 'interact');
addPage_2('gd/seasonal', 'seasonal5', "Putting it all together", 'interact');
addPage_2('gd/seasonal', 'seasonal6', "Forecasting with seasonal data", 'interact');
addSection('bk/gaelic', 'sec_multiplicative', "Multiplicative models");
addPage_2('gd/multiplicative', 'multiplicative1', "Additive and multiplicative models", 'interact');
addPage_2('gd/multiplicative', 'multiplicative2', "Properties of multiplicative models", 'interact');
addPage_2('gd/multiplicative', 'multiplicative3', "Forecasting with multiplicative models", 'interact');
addPage_2('gd/multiplicative', 'multiplicative4', "Analysing the right data", 'static');
addPage_2('gd/multiplicative', 'multiplicative5', "Types of time series data", 'static');
addSection('bk/gaelic', 'sec_indexNos', "Index numbers");
addPage_2('gd/indexNos', 'indexNos1', "Introduction", 'static');
addPage_2('gd/indexNos', 'indexNos2', "Simple price index", 'static');
addPage_2('gd/indexNos', 'indexNos3', "Aggregate price index", 'static');
addPage_2('gd/indexNos', 'indexNos4', "Laspeyres and Paasche indices", 'static');
addPage_2('gd/indexNos', 'indexNos5', "Deflating a time series", 'static');

addChapter('bk/gaelic', 'ch_cat', "Categorical Variables");
addSection('bk/gaelic', 'sec_freqTable', "Frequency tables");
addPage_2('gd/freqTable', 'freqTable1', "Frequency tables", 'interact');
addPage_2('gd/freqTable', 'freqTable2', "Proportions and percentages", 'interact');
addPage_2('gd/freqTable', 'freqTable3', "Recognising frequency tables", 'static');
addPage_2('gd/freqTable', 'freqTable4', "Changes to the categories", 'interact');
addSection('bk/gaelic', 'sec_univarCat', "Bar and pie charts");
addPage_2('gd/univarCat', 'univarCat1', "Bar charts", 'interact');
addPage_2('gd/univarCat', 'univarCat2', "Pareto diagrams", 'interact');
addPage_2('gd/univarCat', 'univarCat3', "Chartjunk and misleading bar charts", 'static');
addPage_2('gd/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact');
addPage_2('gd/univarCat', 'univarCat5', "Comparison of bar and pie charts", 'interact');
addPage_2('gd/univarCat', 'univarCat6', "Chartjunk for pie charts", 'static');
addPage_2('gd/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact');
addSection('bk/gaelic', 'sec_groupedCat', "Comparing groups");
addPage_2('gd/groupedCat', 'groupedCat1', "Contingency tables", 'interact');
addPage_2('gd/groupedCat', 'groupedCat2', "Contingency table examples", 'static');
addPage_2('gd/groupedCat', 'groupedCat3', "Bar charts using proportions", 'interact');
addPage_2('gd/groupedCat', 'groupedCat4', "Stacked bar charts", 'interact');
addPage_2('gd/groupedCat', 'groupedCat5', "Two special cases", 'interact');
addSection('bk/gaelic', 'sec_bivarCat', "Bivariate categorical distributions");
addPage_2('gd/bivarCat', 'bivarCat1', "Relationships between variables", 'static');
addPage_2('gd/bivarCat', 'bivarCat2', "3-dimensional bar charts", 'interact');
addPage_2('gd/bivarCat', 'bivarCat3', "Clustered bar charts", 'interact');
addPage_2('gd/bivarCat', 'bivarCat4', "Marginal distributions", 'interact');
addPage_2('gd/bivarCat', 'bivarCat5', "Conditional distributions", 'interact');
addPage_2('gd/bivarCat', 'bivarCat6', "More about conditional distributions", 'interact');
addPage_2('gd/bivarCat', 'bivarCat7', "Conditional vs marginal distns", 'interact');
addSection('bk/gaelic', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('gd/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static');
addPage_2('gd/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static');
addPage_2('gd/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact');
addPage_2('gd/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact');
addPage_2('gd/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static');
addPage_2('gd/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact');
addPage_2('gd/tableDisplay', 'tableDisplay7', "Example", 'static');
addSection('bk/gaelic', 'sec_logistic', "Logistic regression");
addPage_2('gd/logistic', 'logistic1', "Categorical responses", 'interact');
addPage_2('gd/logistic', 'logistic2', "Fitted values and predictions", 'interact');
addPage_2('gd/logistic', 'logistic3', "Logistic curve", 'interact');
addPage_2('gd/logistic', 'logistic4', "Obtaining a good fit", 'interact');

addChapter('bk/gaelic', 'ch_multivar', "Multivariate Data");
addSection('bk/gaelic', 'sec_multivariate', "Displaying multivariate data");
addPage_2('gd/multivariate', 'multivariate1', "Representing a third variable", 'interact');
addPage_2('gd/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact');
addPage_2('gd/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact');
addPage_2('gd/multivariate', 'multivariate4', "Brushing example", 'interact');
addPage_2('gd/multivariate', 'multivariate5', "Slicing", 'interact');
addSection('bk/gaelic', 'sec_regnGroups', "Groups and regression");
addPage_2('gd/regnGroups', 'regnGroups1', "Additional variables in regression", 'interact');
addPage_2('gd/regnGroups', 'regnGroups2', "Displaying groups", 'interact');
addPage_2('gd/regnGroups', 'regnGroups3', "Regression with grouped data", 'interact');
addPage_2('gd/regnGroups', 'regnGroups4', "Parallel regression lines", 'interact');
addPage_2('gd/regnGroups', 'regnGroups5', "Transformed variables and groups", 'interact');
addPage_2('gd/regnGroups', 'regnGroups6', "Grouping with a numerical variable", 'interact');
addPage_2('gd/regnGroups', 'regnGroups7', "Scatterplot matrix with groups", 'interact');
addSection('bk/gaelic', 'sec_multiRegn', "Multiple regression");
addPage_2('gd/multiRegn', 'multiRegn1', "More than one explanatory variable", 'interact');
addPage_2('gd/multiRegn', 'multiRegn2', "Multiple regression equation", 'interact');
addPage_2('gd/multiRegn', 'multiRegn3', "Interpreting coefficients", 'interact');
addPage_2('gd/multiRegn', 'multiRegn4', "Scatterplot of three variables", 'interact');
addPage_2('gd/multiRegn', 'multiRegn5', "Displayng the linear equation for Y vs X and Z", 'interact');
addPage_2('gd/multiRegn', 'multiRegn6', "Fitted values and residuals", 'interact');
addPage_2('gd/multiRegn', 'multiRegn7', "Least squares estimation", 'interact');
addSection('bk/gaelic', 'sec_lurking', "Marginal relationships");
addPage_2('gd/lurking', 'lurking1', "Misleading marginal correlation", 'interact');
addPage_2('gd/lurking', 'lurking2', "Misleading marginal difference in means", 'interact');
addPage_2('gd/lurking', 'lurking3', "Simpsons paradox", 'interact');
addPage_2('gd/lurking', 'lurking4', "Other examples with lurking variables", 'static');

addChapter('bk/gaelic', 'ch_sample', "Sampling and Variability");
addSection('bk/gaelic', 'sec_popSamp', "Finite populations");
addPage_2('gd/popSamp', 'popSamp1', "Census or sample?", 'interact');
addPage_2('gd/popSamp', 'popSamp2', "Variability in a sample", 'interact');
addPage_2('gd/popSamp', 'popSamp3', "Sampling error", 'interact');
addPage_2('gd/popSamp', 'popSamp4', "Sampling error and sample size", 'interact');
addPage_2('gd/popSamp', 'popSamp5', "Sampling from finite populations", 'interact');
addPage_2('gd/popSamp', 'popSamp6', "Selecting a random sample", 'interact');
addSection('bk/gaelic', 'sec_infPopn', "Samples from distributions");
addPage_2('gd/infPopn', 'infPopn1', "Data as representatives", 'static');
addPage_2('gd/infPopn', 'infPopn2', "Randomness of data", 'interact');
addPage_2('gd/infPopn', 'infPopn3', "Model to explain randomness", 'static');
addPage_2('gd/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact');
addPage_2('gd/infPopn', 'infPopn5', "Information from a single sample", 'interact');
addSection('bk/gaelic', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('gd/probDensity', 'probDensity1', "Finite populations", 'interact');
addPage_2('gd/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact');
addPage_2('gd/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact');
addPage_2('gd/probDensity', 'probDensity4', "Probability density functions", 'interact');
addPage_2('gd/probDensity', 'probDensity5', "Normal distributions", 'interact');
addPage_2('gd/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact');
addPage_2('gd/probDensity', 'probDensity7', "Properties of probability", 'static');
addSection('bk/gaelic', 'sec_probSim', "Simulation (optional)");
addPage_2('gd/probSim', 'probSim1', "Probability models and simulation", 'interact');
addPage_2('gd/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact');
addPage_2('gd/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact');
addPage_2('gd/probSim', 'probSim4', "Assessing unusual features in data", 'interact');
addPage_2('gd/probSim', 'probSim5', "Random numbers", 'interact');
addPage_2('gd/probSim', 'probSim6', "Generating categorical values", 'interact');
addPage_2('gd/probSim', 'probSim7', "Generating numerical values", 'interact');
addSection('bk/gaelic', 'sec_randomMean', "Distribution of sample mean");
addPage_2('gd/randomMean', 'randomMean1', "Parameters and statistics", 'interact');
addPage_2('gd/randomMean', 'randomMean2', "Variability of sample mean", 'interact');
addPage_2('gd/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact');
addPage_2('gd/randomMean', 'randomMean4', "Means from normal populations", 'interact');
addPage_2('gd/randomMean', 'randomMean5', "Large-sample normality of means", 'interact');
addPage_2('gd/randomMean', 'randomMean6', "Distribution of mean from a sample", 'static');
addPage_2('gd/randomMean', 'randomMean7', "Requirement of independence", 'interact');
addPage_2('gd/randomMean', 'randomMean8', "Sampling from finite populations", 'interact');
addSection('bk/gaelic', 'sec_normalDistn', "Normal distributions");
addPage_2('gd/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact');
addPage_2('gd/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact');
addPage_2('gd/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact');
addPage_2('gd/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact');
addPage_2('gd/normalDistn', 'normalDistn5', "Z-scores", 'interact');
addPage_2('gd/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact');
addPage_2('gd/normalDistn', 'normalDistn7', "Other probabilities", 'interact');
addPage_2('gd/normalDistn', 'normalDistn8', "Normal tables", 'static');
addPage_2('gd/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact');
addPage_2('gd/normalDistn', 'normalDistn10', "Normal probability plots", 'interact');
addSection('bk/gaelic', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('gd/randomPropn', 'randomPropn1', "Proportion and probability", 'interact');
addPage_2('gd/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact');
addPage_2('gd/randomPropn', 'randomPropn3', "Binomial distribution", 'interact');
addPage_2('gd/randomPropn', 'randomPropn4', "Binomial probability examples", 'static');
addPage_2('gd/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact');
addPage_2('gd/randomPropn', 'randomPropn6', "Normal approximation examples", 'static');
addSection('bk/gaelic', 'sec_sampPractice', "Sampling in practice");
addPage_2('gd/sampPractice', 'sampPractice1', "Stratified sampling", 'interact');
addPage_2('gd/sampPractice', 'sampPractice2', "Cluster sampling", 'interact');
addPage_2('gd/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact');
addPage_2('gd/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static');
addPage_2('gd/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static');
addPage_2('gd/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact');
addPage_2('gd/sampPractice', 'sampPractice7', "Survey design issues", 'static');

addChapter('bk/gaelic', 'ch_expDesign', "Designed Experiments");
addSection('bk/gaelic', 'sec_causal', "Association &amp; causal relationships");
addPage_2('gd/causal', 'causal1', "Interest in relationships", 'static');
addPage_2('gd/causal', 'causal2', "Causal and non-causal relationships", 'static');
addPage_2('gd/causal', 'causal3', "Detecting causal relationships", 'static');
addPage_2('gd/causal', 'causal4', "Observational and experimental data", 'interact');
addPage_2('gd/causal', 'causal5', "Data collection and causality", 'interact');
addSection('bk/gaelic', 'sec_designIntro', "Principles of experimental design");
addPage_2('gd/designIntro', 'designIntro1', "Experiments and treatments", 'static');
addPage_2('gd/designIntro', 'designIntro2', "Variable experimental units", 'interact');
addPage_2('gd/designIntro', 'designIntro3', "A badly designed experiment", 'interact');
addPage_2('gd/designIntro', 'designIntro4', "Confounding", 'static');
addPage_2('gd/designIntro', 'designIntro5', "Randomisation", 'interact');
addPage_2('gd/designIntro', 'designIntro6', "Replication", 'static');
addPage_2('gd/designIntro', 'designIntro7', "Blocking", 'interact');
addSection('bk/gaelic', 'sec_pairBlock', "Pairing and blocks");
addPage_2('gd/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact');
addPage_2('gd/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact');
addPage_2('gd/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact');
addPage_2('gd/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact');
addPage_2('gd/pairBlock', 'pairBlock5', "Randomised block experiments", 'static');
addSection('bk/gaelic', 'sec_designTwo', "Two or more factors");
addPage_2('gd/designTwo', 'designTwo1', "Experiments with 2 factors", 'interact');
addPage_2('gd/designTwo', 'designTwo2', "Factorial design", 'static');
addPage_2('gd/designTwo', 'designTwo3', "Simple model for two factors", 'interact');
addPage_2('gd/designTwo', 'designTwo4', "Interaction between factors", 'interact');
addPage_2('gd/designTwo', 'designTwo5', "Example with interaction", 'interact');
addPage_2('gd/designTwo', 'designTwo6', "No-interaction model for three factors", 'interact');
addPage_2('gd/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact');
addSection('bk/gaelic', 'sec_designPrelim', "Practical issues in design");
addPage_2('gd/designPrelim', 'designPrelim1', "Purpose", 'static');
addPage_2('gd/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static');
addPage_2('gd/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static');

addChapter('bk/gaelic', 'ch_estimation', "Estimating Parameters");
addSection('bk/gaelic', 'sec_estIntro', "Introduction to estimation");
addPage_2('gd/estIntro', 'estIntro1', "Interest in populations", 'static');
addPage_2('gd/estIntro', 'estIntro2', "Interest in parameters", 'static');
addPage_2('gd/estIntro', 'estIntro3', "Applications of estimation", 'static');
addPage_2('gd/estIntro', 'estIntro4', "Estimation error", 'static');
addPage_2('gd/estIntro', 'estIntro5', "Distribution of errors", 'interact');
addPage_2('gd/estIntro', 'estIntro6', "Standard error and bias", 'static');
addPage_2('gd/estIntro', 'estIntro7', "Interval estimates", 'static');
addSection('bk/gaelic', 'sec_seMean', "Standard error of mean");
addPage_2('gd/seMean', 'seMean1', "Error distribution for mean", 'interact');
addPage_2('gd/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact');
addPage_2('gd/seMean', 'seMean3', "Interpreting the standard error", 'static');
addPage_2('gd/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static');
addPage_2('gd/seMean', 'seMean5', "Standard error vs standard deviation", 'interact');
addPage_2('gd/seMean', 'seMean6', "Using SEs to compare estimators", 'interact');
addPage_2('gd/seMean', 'seMean7', "More about bias", 'interact');
addSection('bk/gaelic', 'sec_ciMean', "Confidence interval for mean");
addPage_2('gd/ciMean', 'ciMean1', "Confidence interval from standard error", 'static');
addPage_2('gd/ciMean', 'ciMean2', "Confidence interval for mean, known sigma", 'interact');
addPage_2('gd/ciMean', 'ciMean3', "Confidence level", 'interact');
addPage_2('gd/ciMean', 'ciMean4', "Confidence level if sigma is replaced by s", 'interact');
addPage_2('gd/ciMean', 'ciMean5', "Confidence interval for µ, unknown \u03c3", 'interact');
addPage_2('gd/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact');
addPage_2('gd/ciMean', 'ciMean7', "Examples", 'static');
addSection('bk/gaelic', 'sec_estPropn', "Estimating proportions");
addPage_2('gd/estPropn', 'estPropn1', "General framework for estimation", 'static');
addPage_2('gd/estPropn', 'estPropn2', "Estimating a proportion", 'interact');
addPage_2('gd/estPropn', 'estPropn3', "Error distribution", 'interact');
addPage_2('gd/estPropn', 'estPropn4', "Normal approximation to error distribution", 'interact');
addPage_2('gd/estPropn', 'estPropn5', "Confidence interval for proportion", 'static');
addPage_2('gd/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact');
addPage_2('gd/estPropn', 'estPropn7', "Confidence interval examples", 'static');
addSection('bk/gaelic', 'sec_ciExtra', "More about estimation");
addPage_2('gd/ciExtra', 'ciExtra1', "Margin of error", 'interact');
addPage_2('gd/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact');
addPage_2('gd/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact');
addPage_2('gd/ciExtra', 'ciExtra4', "Other confidence levels", 'interact');
addSection('bk/gaelic', 'sec_estOther', "Simulation and bootstrap");
addPage_2('gd/estOther', 'estOther1', "Need for simulation", 'static');
addPage_2('gd/estOther', 'estOther2', "Error distribution by simulation (advanced)", 'interact');
addPage_2('gd/estOther', 'estOther3', "Simulation from normal approximation (advanced)", 'interact');
addPage_2('gd/estOther', 'estOther4', "Bootstrap error distribution (advanced)", 'interact');
addPage_2('gd/estOther', 'estOther5', "Standard error of correlation from bootstrap", 'interact');
addPage_2('gd/estOther', 'estOther6', "CIs from simulation (advanced)", 'interact');

addChapter('bk/gaelic', 'ch_testing', "Testing Hypotheses");
addSection('bk/gaelic', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('gd/testIntro', 'testIntro1', "Inference", 'static');
addPage_2('gd/testIntro', 'testIntro2', "Soccer league simulation", 'interact');
addPage_2('gd/testIntro', 'testIntro3', "Simulation to test a proportion", 'interact');
addPage_2('gd/testIntro', 'testIntro4', "Test for a mean", 'interact');
addPage_2('gd/testIntro', 'testIntro5', "Randomisation tests", 'interact');
addPage_2('gd/testIntro', 'testIntro6', "Soccer league randomisation", 'interact');
addPage_2('gd/testIntro', 'testIntro7', "Common patterns in hypothesis testing", 'static');
addSection('bk/gaelic', 'sec_testPropn', "Tests about proportions");
addPage_2('gd/testPropn', 'testPropn1', "Inference about parameters", 'static');
addPage_2('gd/testPropn', 'testPropn2', "P-value for testing proportion", 'interact');
addPage_2('gd/testPropn', 'testPropn3', "Another example of testing a proportion", 'interact');
addPage_2('gd/testPropn', 'testPropn4', "One- and two-tailed tests", 'interact');
addPage_2('gd/testPropn', 'testPropn5', "Tests based on normal approximation", 'interact');
addSection('bk/gaelic', 'sec_testMean', "Tests about means");
addPage_2('gd/testMean', 'testMean1', "Introduction", 'static');
addPage_2('gd/testMean', 'testMean2', "Tests based on statistical distance", 'interact');
addPage_2('gd/testMean', 'testMean3', "P-value for testing mean (known sigma)", 'interact');
addPage_2('gd/testMean', 'testMean4', "The t distribution", 'interact');
addPage_2('gd/testMean', 'testMean5', "The t test for a mean", 'interact');
addSection('bk/gaelic', 'sec_decision', "Decisions and significance");
addPage_2('gd/decision', 'decision1', "Hypothesis tests and decisions", 'static');
addPage_2('gd/decision', 'decision2', "Decision rules", 'interact');
addPage_2('gd/decision', 'decision3', "Significance level and p-values", 'interact');
addPage_2('gd/decision', 'decision4', "Sample size and power", 'interact');
addSection('bk/gaelic', 'sec_testPValue', "Properties of p-values");
addPage_2('gd/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact');
addPage_2('gd/testPValue', 'testPValue2', "P-value and consistency with null hypothesis", 'interact');
addPage_2('gd/testPValue', 'testPValue3', "Distribution of p-values", 'interact');
addPage_2('gd/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact');
addPage_2('gd/testPValue', 'testPValue5', "P-values for other tests", 'interact');

addChapter('bk/gaelic', 'ch_twoGroups', "Comparing Groups");
addSection('bk/gaelic', 'sec_twoGroupModel', "Models for two groups");
addPage_2('gd/twoGroupModel', 'twoGroupModel1', "Interest in underlying population", 'static');
addPage_2('gd/twoGroupModel', 'twoGroupModel2', "Model for two groups", 'interact');
addPage_2('gd/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact');
addPage_2('gd/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact');
addPage_2('gd/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact');
addSection('bk/gaelic', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('gd/sumDiff', 'sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('gd/sumDiff', 'sumDiff2', "Sum and differences", 'interact');
addPage_2('gd/sumDiff', 'sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('gd/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static');
addSection('bk/gaelic', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('gd/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact');
addPage_2('gd/twoGroupInf', 'twoGroupInf2', "Distribution of estimation error", 'static');
addPage_2('gd/twoGroupInf', 'twoGroupInf3', "CI for difference between means", 'interact');
addPage_2('gd/twoGroupInf', 'twoGroupInf4', "Testing a hypothesis", 'interact');
addPage_2('gd/twoGroupInf', 'twoGroupInf5', "One-tailed tests for differences", 'interact');
addSection('bk/gaelic', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('gd/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact');
addPage_2('gd/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact');
addPage_2('gd/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static');
addPage_2('gd/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static');
addSection('bk/gaelic', 'sec_testPaired', "Paired t test");
addPage_2('gd/testPaired', 'testPaired1', "Paired data examples", 'static');
addPage_2('gd/testPaired', 'testPaired2', "Analysis of differences", 'interact');
addPage_2('gd/testPaired', 'testPaired3', "Paired t-test", 'interact');
addPage_2('gd/testPaired', 'testPaired4', "Pairing and experimental design", 'interact');
addSection('bk/gaelic', 'sec_multiGroup', "Comparing several means");
addPage_2('gd/multiGroup', 'multiGroup1', "Model with common standard deviation", 'interact');
addPage_2('gd/multiGroup', 'multiGroup2', "Estimate of common standard deviation", 'interact');
addPage_2('gd/multiGroup', 'multiGroup3', "Inference about two groups", 'static');
addPage_2('gd/multiGroup', 'multiGroup4', "Assessing differences between groups", 'interact');
addPage_2('gd/multiGroup', 'multiGroup5', "Sums of squares", 'interact');
addPage_2('gd/multiGroup', 'multiGroup6', "Coefficient of determination", 'static');
addPage_2('gd/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact');
addPage_2('gd/multiGroup', 'multiGroup8', "Examples", 'static');
addSection('bk/gaelic', 'sec_randBlock', "Randomised blocks");
addPage_2('gd/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static');
addPage_2('gd/randBlock', 'randBlock2', "Importance of using block information", 'interact');
addPage_2('gd/randBlock', 'randBlock3', "Data with no baseline treatment", 'interact');
addPage_2('gd/randBlock', 'randBlock4', "Randomised block designs", 'interact');
addPage_2('gd/randBlock', 'randBlock5', "Model for randomised blocks", 'interact');
addPage_2('gd/randBlock', 'randBlock6', "Removing block effects", 'interact');
addPage_2('gd/randBlock', 'randBlock7', "Sums of squares", 'interact');
addPage_2('gd/randBlock', 'randBlock8', "Anova table and examples", 'static');

addChapter('bk/gaelic', 'ch_regnInference', "Regression Inference");
addSection('bk/gaelic', 'sec_regnModel', "Linear regression models");
addPage_2('gd/regnModel', 'regnModel1', "Interest in generalising from data", 'interact');
addPage_2('gd/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact');
addPage_2('gd/regnModel', 'regnModel3', "Normal linear model", 'interact');
addPage_2('gd/regnModel', 'regnModel4', "Errors and 95% band on scatterplot", 'interact');
addPage_2('gd/regnModel', 'regnModel5', "Model parameters", 'interact');
addSection('bk/gaelic', 'sec_regnEst', "Estimating parameters");
addPage_2('gd/regnEst', 'regnEst1', "Point estimates of slope and intercept", 'interact');
addPage_2('gd/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact');
addPage_2('gd/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact');
addPage_2('gd/regnEst', 'regnEst4', "Standard error of least squares slope", 'static');
addPage_2('gd/regnEst', 'regnEst5', "95% confidence interval for slope", 'static');
addPage_2('gd/regnEst', 'regnEst6', "Properties of confidence interval", 'interact');
addPage_2('gd/regnEst', 'regnEst7', "Influences on accuracy", 'interact');
addSection('bk/gaelic', 'sec_regnTest', "Testing regression parameters");
addPage_2('gd/regnTest', 'regnTest1', "Importance of zero slope", 'interact');
addPage_2('gd/regnTest', 'regnTest2', "Testing whether slope is zero", 'static');
addPage_2('gd/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static');
addPage_2('gd/regnTest', 'regnTest4', "Properties of p-values", 'interact');
addSection('bk/gaelic', 'sec_regnPred', "Predicting the response");
addPage_2('gd/regnPred', 'regnPred1', "Estimated response distn at X", 'interact');
addPage_2('gd/regnPred', 'regnPred2', "Variability of estimate at X", 'interact');
addPage_2('gd/regnPred', 'regnPred3', "Estimating the mean vs prediction", 'interact');
addPage_2('gd/regnPred', 'regnPred4', "Confidence and prediction intervals", 'interact');
addSection('bk/gaelic', 'sec_regnProblem', "Linear model assumptions");
addPage_2('gd/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact');
addPage_2('gd/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact');
addPage_2('gd/regnProblem', 'regnProblem3', "Curvature and non-constant variance &mdash; transforming Y", 'interact');
addPage_2('gd/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact');
addPage_2('gd/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact');
addPage_2('gd/regnProblem', 'regnProblem6', "Non-normal errors", 'interact');
addPage_2('gd/regnProblem', 'regnProblem7', "Correlated errors", 'interact');

addChapter('bk/gaelic', 'ch_independence', "Independence");
addSection('bk/gaelic', 'sec_prob', "Probability and applications");
addPage_2('gd/prob', 'prob1', "Joint probabilities", 'interact');
addPage_2('gd/prob', 'prob2', "Marginal probabilities", 'interact');
addPage_2('gd/prob', 'prob3', "Conditional probabilities", 'interact');
addPage_2('gd/prob', 'prob4', "Graphical display of probabilities", 'interact');
addPage_2('gd/prob', 'prob5', "Calculations with probabilities", 'interact');
addSection('bk/gaelic', 'sec_indep', "Independence");
addPage_2('gd/indep', 'indep1', "Association between categorical variables", 'static');
addPage_2('gd/indep', 'indep2', "Independence of categorical variables", 'interact');
addPage_2('gd/indep', 'indep3', "Independence from samples", 'static');
addPage_2('gd/indep', 'indep4', "Testing for independence", 'interact');
addPage_2('gd/indep', 'indep5', "Chi-squared test statistic", 'interact');
addPage_2('gd/indep', 'indep6', "P-value for chi-squared test", 'interact');
addPage_2('gd/indep', 'indep7', "Examples", 'static');
addPage_2('gd/indep', 'indep8', "Comparing groups", 'static');

var language = "gd";
var logoGif = null;
var homeDir = "bk/gaelic";
var versionGif = "images/castInternational";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Full text';
var summaryTextString = 'Summary';
var videoTextString = 'Watch';
var appletTextString = 'Interact';
fullTabTooltip = 'Full version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Interactive version of page';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_b': 'Biometric', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_g', '_b', '_c');
versions['structures6'] = new Array('_g', '_b');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_g', '_b', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('_g', '_a', '_b', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_g', '_b', '_c');
versions['displayInterp2'] = new Array('_g', '_b', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density7'] = new Array('_g', '_b', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_g', '_b', '_c', '_m');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_g', '_b');
versions['transform2'] = new Array('_g', '_b', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['counts4'] = new Array('_g', '_b', '_c');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship2'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_g', '_b', '_c');
versions['seasonal1'] = new Array('_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['seasonal5'] = new Array('_g', '_m', '_z');
versions['seasonal6'] = new Array('_g', '_m', '_z');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat6'] = new Array('_g', '_b', '_c');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['groupedCat3'] = new Array('_g', '_b', '_c');
versions['groupedCat4'] = new Array('_g', '_b', '_c');
versions['groupedCat5'] = new Array('_g', '_b', '_c');
versions['bivarCat1'] = new Array('_g', '_b', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['logistic1'] = new Array('_g', '_b', '_c');
versions['logistic2'] = new Array('_g', '_b', '_c');
versions['logistic4'] = new Array('_g', '_b', '_c');
versions['multivariate1'] = new Array('_g', '_b', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_g', '_b', '_c');
versions['lurking2'] = new Array('_g', '_b');
versions['lurking3'] = new Array('_g', '_c');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b', '_c');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_g', '_b', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_g', '_b', '_c');
versions['randomMean6'] = new Array('_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');
versions['sampPractice1'] = new Array('_g', '_b');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_g', '_b');
versions['designTwo1'] = new Array('_g', '_b');
versions['designTwo2'] = new Array('_g', '_b');
versions['designTwo6'] = new Array('_g', '_b');
versions['designPrelim2'] = new Array('_g', '_c');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');
versions['estOther3'] = new Array('_g', '_c', '_m');
versions['estOther5'] = new Array('_g', '_b');
versions['estOther6'] = new Array('_g', '_c', '_m');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro3'] = new Array('_g', '_b', '_c');
versions['testIntro5'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_g', '_b', '_c');
versions['testPropn1'] = new Array('_g', '_b', '_c');
versions['testPropn2'] = new Array('_g', '_b', '_c');
versions['testPropn3'] = new Array('_g', '_b', '_c');
versions['testPropn4'] = new Array('_g', '_b', '_c');
versions['testPropn5'] = new Array('_g', '_b');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_g', '_b', '_c');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_g', '_b', '_c');
versions['testPValue5'] = new Array('_g', '_b', '_c');
versions['twoGroupModel1'] = new Array('_g', '_b', '_c');
versions['twoGroupModel2'] = new Array('_g', '_b', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['twoGroupInf3'] = new Array('_g', '_b', '_c');
versions['twoGroupInf4'] = new Array('_g', '_b', '_c');
versions['twoGroupInf5'] = new Array('_g', '_b', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_g', '_b', '_c');
versions['testPaired2'] = new Array('_g', '_b', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_g', '_b', '_c');
versions['multiGroup3'] = new Array('_g', '_b', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_g', '_a', '_b', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_g', '_b', '_c');
versions['regnModel1'] = new Array('_g', '_b', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_g', '_b', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_g', '_b', '_c');
versions['regnPred3'] = new Array('_g', '_b', '_c');
versions['regnPred4'] = new Array('_g', '_b');
versions['regnProblem3'] = new Array('_g', '_b');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_g', '_b', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
