
addBook('bk/exercisesR', 'book_splash', "About the CAST exercises");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/exercises', 'ch_univar', "One Numerical Variable");
addSection('bk/exercisesR', 'sec_dataDisplay', "Graphical displays");
addPage_2('en/boxPlot', 'e_boxPlot_e1', "Shape of a distribution", 'static');
addPage_2('en/displayInterp', 'e_displayInterp_e1', "Information from distributions", 'static');
addSection('bk/exercisesR', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'e_centerSpread_e1', "Ideas of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread_e2', "Calculate summary statistics", 'static');
addSection('bk/exercisesR', 'sec_percentile', "Proportions and percentiles");
addPage_2('en/density', 'e_density_e1', "Proportions", 'static');
addSection('bk/exercisesR', 'sec_transform', "Transformations");
addPage_2('en/transform', 'e_transform_e1', "Mean and st devn after linear transformations", 'static');
addPage_2('en/transform', 'e_transform_e2', "Power transformations", 'static');

addChapter('bk/exercises', 'ch_bivar', "Two Numerical Variables");
addSection('bk/exercisesR', 'sec_scatterCorr', "Scatterplots and correlation");
addPage_2('en/scatterplot', 'e_scatterplot_e1', "Information from scatterplots", 'static');
addPage_2('en/correlation', 'e_correlation_e1', "Correlation coefficient, r", 'static');
addSection('bk/exercisesR', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'e_leastSqrs_e1', "Slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs_e2', "Interpreting the slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs_e3', "Predictions", 'static');
addSection('bk/exercisesR', 'sec_lsProblems', "Curvature, outliers and leverage");
addPage_2('en/curvature', 'e_curvature_e1', "Regression problems", 'static');
addPage_2('en/curvature', 'e_curvature_e2', "Log transformations of X and Y", 'static');
addPage_2('en/curvature', 'e_curvature_e3', "Prediction from nonlinear model", 'static');

addChapter('bk/exercises', 'ch_timeSeries', "Time Series");
addSection('bk/exercisesR', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'e_timePlot_e1', "Patterns in time series", 'static');
addSection('bk/exercisesR', 'sec_trend', "Trend");
addPage_2('en/trend', 'e_trend_e1', "Forecasting a future value", 'static');

addChapter('bk/exercises', 'ch_cat', "Categorical Variables");
addSection('bk/exercisesR', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'e_freqTable_e1', "Proportions for categorical data", 'static');
addSection('bk/exercisesR', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'e_univarCat_e1', "Bar charts", 'static');
addPage_2('en/univarCat', 'e_univarCat_e2', "Pie charts", 'static');
addSection('bk/exercisesR', 'sec_continTable', "Contingency tables");
addPage_2('en/groupedCat', 'e_groupedCat_e1', "Proportions from contingency tables", 'static');

addChapter('bk/exercises', 'ch_sampling', "Sampling and Variability");
addSection('bk/exercisesR', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'e_normalDistn_e1', "Probability and area under normal curve", 'static');
addPage_2('en/normalDistn', 'e_normalDistn_e2', "Finding X from probability", 'static');
addSection('bk/exercisesR', 'sec_binomial', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'e_randomPropn_e1', "Finding binomial probabilities", 'static');
addPage_2('en/randomPropn', 'e_randomPropn_e2', "Probabilities from normal approximation", 'static');
addSection('bk/exercisesR', 'sec_meanSum', "Distributions of means &amp; sums");
addPage_2('en/randomMean', 'e_randomMean_e1', "Probabilities relating to means and sums", 'static');

addChapter('bk/exercises', 'ch_estimation', "Estimating Parameters");
addSection('bk/exercises', 'sec_popSamp', "Populations and samples");
addPage_2('en/popSamp', 'e_popSamp1', "Distinction between populations and samples", 'static');
addPage_2('en/popSamp', 'e_popSamp2', "Distinction between parameters and estimates", 'static');
addSection('bk/exercises', 'sec_se', "Standard error");
addPage_2('en/seMean', 'e_seMean1', "Standard error of mean", 'static');
addPage_2('en/seMean', 'e_seMean2', "Standard error vs standard deviation", 'static');
addPage_2('en/seMean', 'e_seMean3', "Factors affecting the standard deviation and standard error", 'static');
addSection('bk/exercises', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'e_ciMean1', "Confidence interval from standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean2', "95% confidence interval, known sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean3', "95% confidence interval, unknown sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean4', "Other confidence levels, known sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean5', "Mixture of levels, known &amp; unknown \u03c3", 'static');
addPage_2('en/ciMean', 'e_ciMean6', "Factors affecting width of CI", 'static');
addPage_2('en/ciMean', 'e_ciMean7', "Interpreting a 95% confidence interval", 'static');
addSection('bk/exercises', 'sec_ciProportion', "Estimating proportions");
addPage_2('en/estPropn', 'e_estPropn1', "Standard error of proportion", 'static');
addPage_2('en/estPropn', 'e_estPropn2', "95% confidence interval for probability", 'static');
addPage_2('en/estPropn', 'e_estPropn3', "Other confidence levels", 'static');
addPage_2('en/estPropn', 'e_estPropn4', "Factors affecting width of confidence interval", 'static');
addPage_2('en/estPropn', 'e_estPropn5', "Interpreting a 95% confidence interval", 'static');

addChapter('bk/exercises', 'ch_test', "Testing Hypotheses");
addSection('bk/exercises', 'sec_testSim', "Testing with simulations");
addPage_2('en/testIntro', 'e_testIntro1', "Test about a proportion", 'static');
addPage_2('en/testIntro', 'e_testIntro2', "Test about a mean, known sigma", 'static');
addSection('bk/exercises', 'sec_testPropn', "Tests about probabilities and proportions");
addPage_2('en/testPropn', 'e_testPropn1', "Perform test using binomial distribution", 'static');
addPage_2('en/testPropn', 'e_testPropn2', "Perform test with a normal approximation", 'static');
addPage_2('en/testPropn', 'e_testPropn3', "Test with continuity correction (advanced)", 'static');
addSection('bk/exercises', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'e_testMean1', "Hypothesis test, assuming known \u03c3", 'static');
addPage_2('en/testMean', 'e_testMean2', "T test (unknown sigma)", 'static');
addSection('bk/exercises', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'e_testPValue1', "Generic interpretation of a p-values", 'static');
addPage_2('en/testPValue', 'e_testPValue2', "Interpretation of p-values (in context)", 'static');
addPage_2('en/testPValue', 'e_testPValue3', "Interpretation of p-values (harder)", 'static');

addChapter('bk/exercises', 'ch_compareGroups', "Comparing Groups");
addSection('bk/exercises', 'sec_twoMeans', "Comparing two means");
addPage_2('en/sumDiff', 'e_sumDiff1', "Probabilities about sums and differences", 'static');
addPage_2('en/twoGroupInf', 'e_twoGroupInf1', "Probabilities about differences", 'static');
addPage_2('en/twoGroupInf', 'e_twoGroupInf2', "CI for difference between two means", 'static');
addPage_2('en/twoGroupInf', 'e_twoGroupInf3', "Testing group means for equality", 'static');
addSection('bk/exercises', 'sec_twoPropns', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'e_twoGroupPropn1', "CI for difference between two proportions", 'static');
addPage_2('en/twoGroupPropn', 'e_twoGroupPropn2', "Test about difference between two proportions", 'static');
addSection('bk/exercises', 'sec_paired', "Paired data");
addPage_2('en/testPaired', 'e_testPaired1', "2-sample or paired t-test", 'static');
addPage_2('en/testPaired', 'e_testPaired2', "Conduct paired t-test", 'static');
addSection('bk/exercises', 'sec_multiGroup', "Comparing many groups");
addPage_2('en/multiGroup', 'e_multiGroup1', "Anova table formulae", 'static');
addPage_2('en/multiGroup', 'e_multiGroup2', "Anova table values", 'static');
addPage_2('en/multiGroup', 'e_multiGroup3', "Conclusion from Anova table", 'static');
addSection('bk/exercises', 'sec_continTest', "Association in contingency tables");
addPage_2('en/indep', 'e_indep1', "Expected cell counts", 'static');
addPage_2('en/indep', 'e_indep2', "Chi-squared test for independence", 'static');

addChapter('bk/exercises', 'ch_regnInference', "Regression Inference");
addSection('bk/exercises', 'sec_regnModel', "Regression models");
addPage_2('en/regnModel', 'e_regnModel1', "Normal distribution of response at fixed X", 'static');
addSection('bk/exercises', 'sec_regnEst', "Estimating slope and intercept");
addPage_2('en/regnEst', 'e_regnEst1', "Standard error of slope", 'static');
addPage_2('en/regnEst', 'e_regnEst2', "Confidence interval for slope", 'static');
addPage_2('en/regnEst', 'e_regnEst3', "Influences on accuracy", 'static');
addSection('bk/exercises', 'sec_regnTest', "Testing the regression slope");
addPage_2('en/regnTest', 'e_regnTest1', "Test for zero slope", 'static');

var language = "en";
var logoGif = null;
var homeDir = "bk/exercisesR";
var versionGif = "images/castExercises";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "10";

var localVideos = false;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_e': 'null', '_g': 'General', '_c': 'Business', '_b': 'Biometric'};
var versions = {};
versions['e_boxPlot1'] = new Array('_e', '_g');
versions['e_displayInterp1'] = new Array('_e', '_g');
versions['e_centerSpread1'] = new Array('_e', '_g');
versions['e_centerSpread2'] = new Array('_e', '_g');
versions['e_density1'] = new Array('_e', '_g');
versions['e_transform1'] = new Array('_e', '_g');
versions['e_transform2'] = new Array('_e', '_g');
versions['e_scatterplot1'] = new Array('_e', '_g');
versions['e_correlation1'] = new Array('_e', '_g');
versions['e_leastSqrs1'] = new Array('_e', '_g');
versions['e_leastSqrs2'] = new Array('_e', '_g');
versions['e_leastSqrs3'] = new Array('_e', '_g');
versions['e_curvature1'] = new Array('_e', '_g');
versions['e_curvature2'] = new Array('_e', '_g');
versions['e_curvature3'] = new Array('_e', '_g');
versions['e_timePlot1'] = new Array('_e', '_g');
versions['e_trend1'] = new Array('_e', '_g');
versions['e_freqTable1'] = new Array('_e', '_g');
versions['e_univarCat1'] = new Array('_e', '_g');
versions['e_univarCat2'] = new Array('_e', '_g');
versions['e_groupedCat1'] = new Array('_e', '_g');
versions['e_normalDistn1'] = new Array('_e', '_g');
versions['e_normalDistn2'] = new Array('_e', '_g');
versions['e_randomPropn1'] = new Array('_e', '_g');
versions['e_randomPropn2'] = new Array('_e', '_g');
versions['e_randomMean1'] = new Array('_e', '_g');
versions['e_twoGroupPropn1'] = new Array('_g', '_c', '_b');
versions['e_twoGroupPropn2'] = new Array('_g', '_b', '_c');

bookLoaded = true;
