
addBook('bk/climatic_c3', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/climatic_c3', 'ch_relns', "Relationships between Variables");
addSection('bk/biometric', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot_b1', "Bivariate data sets", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot_b1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2', 'en/scatterplot', 'v_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5', 'en/scatterplot', 'v_scatterplot5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'en/relationship', 'v_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4', 'en/relationship', 'v_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship5');
addSection('bk/general', 'sec_bivarCat', "Bivariate categorical distributions");
addPage_2('en/bivarCat', 'bivarCat1', "Relationships between variables", 'static', 'en/bivarCat', 's_bivarCat1', 'en/bivarCat', 'v_bivarCat1');
addPage_2('en/bivarCat', 'bivarCat2', "3-dimensional bar charts", 'interact', 'en/bivarCat', 's_bivarCat2', 'en/bivarCat', 'v_bivarCat2');
addPage_2('en/bivarCat', 'bivarCat3', "Clustered bar charts", 'interact', 'en/bivarCat', 's_bivarCat3', 'en/bivarCat', 'v_bivarCat3');
addPage_2('en/bivarCat', 'bivarCat4', "Marginal distributions", 'interact', 'en/bivarCat', 's_bivarCat4', 'en/bivarCat', 'v_bivarCat4');
addPage_2('en/bivarCat', 'bivarCat5', "Conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat5', 'en/bivarCat', 'v_bivarCat5');
addPage_2('en/bivarCat', 'bivarCat6', "More about conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat6', 'en/bivarCat', 'v_bivarCat6');
addPage_2('en/bivarCat', 'bivarCat7', "Conditional vs marginal distns", 'interact', 'en/bivarCat', 's_bivarCat7', 'en/bivarCat', 'v_bivarCat7');

addChapter('bk/climatic_c3', 'ch_sumReln', "Summarising Relationships");
addSection('bk/biometric', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation_b1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation_b1', 'en/correlation', 'v_correlation_b1');
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2', 'en/correlation', 'v_correlation2');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3', 'en/correlation', 'v_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4', 'en/correlation', 'v_correlation4');
addPage_2('en/correlation', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5', 'en/correlation', 'v_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6', 'en/correlation', 'v_correlation6');
addSection('bk/climatic_c3', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs_b1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1', 'en/leastSqrs', 'v_leastSqrs_b1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2', 'en/leastSqrs', 'v_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addSection('bk/climatic_c3', 'sec_simpleDiag', "Simple diagnostics");
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5', 'en/leastSqrs', 'v_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6', 'en/leastSqrs', 'v_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y and predicting X", 'interact', 'en/leastSqrs', 's_leastSqrs7', 'en/leastSqrs', 'v_leastSqrs7');

addChapter('bk/climatic_c3', 'ch_transform', "Transformations");
addSection('bk/biometric', 'sec_transform', "Transformations");
addPage_2('en/transform', 'transform_b1', "Linear transformations", 'interact', 'en/transform', 's_transform1', 'en/transform', 'v_transform_b1');
addPage_2('en/transform', 'transform_b2', "Log transformations", 'interact', 'en/transform', 's_transform2', 'en/transform', 'v_transform_b2');
addPage_2('en/transform', 'transform3', "When to use log transform?", 'interact', 'en/transform', 's_transform3', 'en/transform', 'v_transform3');
addPage_2('en/transform', 'transform4', "Power transformations", 'interact', 'en/transform', 's_transform4', 'en/transform', 'v_transform4');
addPage_2('en/transform', 'transform5', "Power transforms &amp; skewness", 'interact', 'en/transform', 's_transform5', 'en/transform', 'v_transform5');
addSection('bk/general', 'sec_curvature', "Nonlinear relationships");
addPage_2('en/curvature', 'curvature1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1', 'en/curvature', 'v_curvature1');
addPage_2('en/curvature', 'curvature2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2', 'en/curvature', 'v_curvature2');
addPage_2('en/curvature', 'curvature3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3', 'en/curvature', 'v_curvature3');
addPage_2('en/curvature', 'curvature4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4', 'en/curvature', 'v_curvature4');

addChapter('bk/climatic_c3', 'ch_multivar', "Exploring Multivariate Data");
addSection('bk/climatic_c3', 'sec_regnGroups', "Groups and regression");
addPage_2('en/regnGroups', 'regnGroups1', "Additional variables in regression", 'interact', 'en/regnGroups', 's_regnGroups1', 'en/regnGroups', 'v_regnGroups1');
addPage_2('en/regnGroups', 'regnGroups2', "Displaying groups", 'interact', 'en/regnGroups', 's_regnGroups2', 'en/regnGroups', 'v_regnGroups2');
addPage_2('en/regnGroups', 'regnGroups3', "Regression with grouped data", 'interact', 'en/regnGroups', 's_regnGroups3', 'en/regnGroups', 'v_regnGroups3');
addPage_2('en/regnGroups', 'regnGroups4', "Parallel regression lines", 'interact', 'en/regnGroups', 's_regnGroups4', 'en/regnGroups', 'v_regnGroups4');
addPage_2('en/regnGroups', 'regnGroups5', "Transformed variables and groups", 'interact', 'en/regnGroups', 's_regnGroups5', 'en/regnGroups', 'v_regnGroups5');
addPage_2('en/regnGroups', 'regnGroups6', "Grouping with a numerical variable", 'interact', 'en/regnGroups', 's_regnGroups6', 'en/regnGroups', 'v_regnGroups6');
addSection('bk/climatic_c3', 'sec_thirdVar', "Representing a third variable");
addPage_2('en/multivariate', 'multivariate_b1', "Representing a third variable", 'interact', 'en/multivariate', 's_multivariate1', 'en/multivariate', 'v_multivariate_b1');
addPage_2('en/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact', 'en/multivariate', 's_multivariate2', 'en/multivariate', 'v_multivariate2');
addSection('bk/climatic_c3', 'sec_brushing', "Scatterplot matrices & brushing");
addPage_2('en/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact', 'en/multivariate', 's_multivariate3', 'en/multivariate', 'v_multivariate3');
addPage_2('en/multivariate', 'multivariate4', "Brushing example", 'interact', 'en/multivariate', 's_multivariate4', 'en/multivariate', 'v_multivariate4');
addPage_2('en/multivariate', 'multivariate5', "Slicing", 'interact', 'en/multivariate', 's_multivariate5', 'en/multivariate', 'v_multivariate5');
addPage_2('en/regnGroups', 'regnGroups7', "Scatterplot matrix with groups", 'interact', 'en/regnGroups', 's_regnGroups7', 'en/regnGroups', 'v_regnGroups7');

addChapter('bk/business', 'ch_timeSeries', "Time Series");
addSection('bk/business', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot_c1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1', 'en/timePlot', 'v_timePlot_c1');
addPage_2('en/timePlot', 'timePlot_c2', "Patterns in time series", 'interact', 'en/timePlot', 's_timePlot2', 'en/timePlot', 'v_timePlot_c2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3', 'en/timePlot', 'v_timePlot3');
addSection('bk/general', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1', 'en/smoothing', 'v_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2', 'en/smoothing', 'v_smoothing2');
addPage_2('en/smoothing', 'smoothing3', "Robust smoothing", 'interact', 'en/smoothing', 's_smoothing3', 'en/smoothing', 'v_smoothing3');
addPage_2('en/smoothing', 'smoothing4', "Exponential smoothing", 'interact', 'en/smoothing', 's_smoothing4', 'en/smoothing', 'v_smoothing4');
addPage_2('en/smoothing', 'smoothing5', "Lowess smoothing of time series", 'interact', 'en/smoothing', 's_smoothing5', 'en/smoothing', 'v_smoothing5');
addPage_2('en/smoothing', 'smoothing6', "Lowess smoothing of scatterplots", 'interact', 'en/smoothing', 's_smoothing6', 'en/smoothing', 'v_smoothing6');
addSection('bk/general', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'trend1', "Linear trend", 'interact', 'en/trend', 's_trend1', 'en/trend', 'v_trend1');
addPage_2('en/trend', 'trend2', "Quadratic trend", 'interact', 'en/trend', 's_trend2', 'en/trend', 'v_trend2');
addPage_2('en/trend', 'trend3', "Forecasting", 'interact', 'en/trend', 's_trend3', 'en/trend', 'v_trend3');
addPage_2('en/trend', 'trend4', "Polynomial trend", 'interact', 'en/trend', 's_trend4', 'en/trend', 'v_trend4');
addPage_2('en/trend', 'trend5', "Detrending a time series", 'interact', 'en/trend', 's_trend5', 'en/trend', 'v_trend5');
addSection('bk/general', 'sec_cyclic', "Short-term fluctuations");
addPage_2('en/cyclic', 'cyclic1', "Autocorrelation", 'interact', 'en/cyclic', 's_cyclic1', 'en/cyclic', 'v_cyclic1');
addPage_2('en/cyclic', 'cyclic2', "AR(1) model for autocorrelation", 'interact', 'en/cyclic', 's_cyclic2', 'en/cyclic', 'v_cyclic2');
addPage_2('en/cyclic', 'cyclic3', "AR(1) model and trend", 'interact', 'en/cyclic', 's_cyclic3', 'en/cyclic', 'v_cyclic3');
addPage_2('en/cyclic', 'cyclic4', "Trend or autocorrelation?", 'interact', 'en/cyclic', 's_cyclic4', 'en/cyclic', 'v_cyclic4');
addPage_2('en/cyclic', 'cyclic5', "Cyclical patterns", 'interact', 'en/cyclic', 's_cyclic5', 'en/cyclic', 'v_cyclic5');
addSection('bk/general', 'sec_seasonal', "Seasonal data");
addPage_2('en/seasonal', 'seasonal1', "Seasonal patterns", 'interact', 'en/seasonal', 's_seasonal1', 'en/seasonal', 'v_seasonal1');
addPage_2('en/seasonal', 'seasonal2', "Smoothing out seasonal variation", 'interact', 'en/seasonal', 's_seasonal2', 'en/seasonal', 'v_seasonal2');
addPage_2('en/seasonal', 'seasonal3', "Estimating the seasonal effect", 'interact', 'en/seasonal', 's_seasonal3', 'en/seasonal', 'v_seasonal3');
addPage_2('en/seasonal', 'seasonal4', "Deseasonalised data", 'interact', 'en/seasonal', 's_seasonal4', 'en/seasonal', 'v_seasonal4');
addPage_2('en/seasonal', 'seasonal5', "Putting it all together", 'interact', 'en/seasonal', 's_seasonal5', 'en/seasonal', 'v_seasonal5');
addPage_2('en/seasonal', 'seasonal6', "Forecasting with seasonal data", 'interact', 'en/seasonal', 's_seasonal6', 'en/seasonal', 'v_seasonal6');
addSection('bk/general', 'sec_multiplicative', "Multiplicative models");
addPage_2('en/multiplicative', 'multiplicative1', "Additive and multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative1', 'en/multiplicative', 'v_multiplicative1');
addPage_2('en/multiplicative', 'multiplicative2', "Properties of multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative2', 'en/multiplicative', 'v_multiplicative2');
addPage_2('en/multiplicative', 'multiplicative3', "Forecasting with multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative3', 'en/multiplicative', 'v_multiplicative3');
addPage_2('en/multiplicative', 'multiplicative4', "Analysing the right data", 'static', 'en/multiplicative', 's_multiplicative4', 'en/multiplicative', 'v_multiplicative4');
addPage_2('en/multiplicative', 'multiplicative5', "Types of time series data", 'static', 'en/multiplicative', 's_multiplicative5', 'en/multiplicative', 'v_multiplicative5');

var language = "en";
var logoGif = null;
var homeDir = "bk/climatic_c3";
var versionGif = "images/castClimatic_c3";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "6";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_b': 'Biometric', '_g': 'General', '_c': 'Business', '_m': 'Climatic', '_z': 'Other'};
var versions = {};
versions['scatterplot1'] = new Array('_b', '_g', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['bivarCat1'] = new Array('_g', '_b', '_c');
versions['correlation1'] = new Array('_b', '_g', '_c');
versions['leastSqrs1'] = new Array('_b', '_g', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_b', '_g');
versions['transform2'] = new Array('_b', '_g', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['multivariate1'] = new Array('_b', '_g', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_c', '_g', '_b');
versions['timePlot2'] = new Array('_c', '_g', '_b');
versions['seasonal1'] = new Array('_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['seasonal5'] = new Array('_g', '_m', '_z');
versions['seasonal6'] = new Array('_g', '_m', '_z');

bookLoaded = true;
