
addBook('bk/idems_prob', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/mathStats', 'ch_probability', "Probability");
addSection('bk/mathStats', 'sec_probDefinitions', "Ways to define probability");
addPage_2('en/probDefinitions', 'probDefinitions1', "Uncertainty and Probability", 'static', 'en/probDefinitions', 's_probDefinitions1', 'en/probDefinitions', 'v_probDefinitions1');
addPage_2('en/probDefinitions', 'probDefinitions2', "Terminology", 'static', 'en/probDefinitions', 's_probDefinitions2', 'en/probDefinitions', 'v_probDefinitions2');
addPage_2('en/probDefinitions', 'probDefinitions3', "Classical definition of probability", 'interact', 'en/probDefinitions', 's_probDefinitions3', 'en/probDefinitions', 'v_probDefinitions3');
addPage_2('en/probDefinitions', 'probDefinitions4', "Applications of classical definition", 'static', 'en/probDefinitions', 's_probDefinitions4', 'en/probDefinitions', 'v_probDefinitions4');
addPage_2('en/probDefinitions', 'probDefinitions5', "Probability from relative frequency", 'interact', 'en/probDefinitions', 's_probDefinitions5', 'en/probDefinitions', 'v_probDefinitions5');
addPage_2('en/probDefinitions', 'probDefinitions6', "Estimating probabilities", 'static', 'en/probDefinitions', 's_probDefinitions6', 'en/probDefinitions', 'v_probDefinitions6');
addPage_2('en/probDefinitions', 'probDefinitions7', "Subjective probability", 'static', 'en/probDefinitions', 's_probDefinitions7', 'en/probDefinitions', 'v_probDefinitions7');
addSection('bk/mathStats', 'sec_probRules', "Probability calculations");
addPage_2('en/probRules', 'probRules1', "Core rules of probability", 'static', 'en/probRules', 's_probRules1', 'en/probRules', 'v_probRules1');
addPage_2('en/probRules', 'probRules2', "A few properties of probability", 'static', 'en/probRules', 's_probRules2', 'en/probRules', 'v_probRules2');
addPage_2('en/probRules', 'probRules3', "Examples", 'static', 'en/probRules', 's_probRules3', 'en/probRules', 'v_probRules3');
addSection('bk/mathStats', 'sec_probCondit', "Conditional probability");
addPage_2('en/probCondit', 'probCondit1', "Conditional probability", 'static', 'en/probCondit', 's_probCondit1', 'en/probCondit', 'v_probCondit1');
addPage_2('en/probCondit', 'probCondit2', "Graphical display of probabilities", 'interact', 'en/probCondit', 's_probCondit2', 'en/probCondit', 'v_probCondit2');
addPage_2('en/probCondit', 'probCondit3', "Partitions of the sample space", 'interact', 'en/probCondit', 's_probCondit3', 'en/probCondit', 'v_probCondit3');
addPage_2('en/probCondit', 'probCondit4', "Tree diagrams", 'static', 'en/probCondit', 's_probCondit4', 'en/probCondit', 'v_probCondit4');
addPage_2('en/probCondit', 'probCondit5', "More about tree diagrams", 'static', 'en/probCondit', 's_probCondit5', 'en/probCondit', 'v_probCondit5');
addPage_2('en/probCondit', 'probCondit6', "Independence", 'static', 'en/probCondit', 's_probCondit6', 'en/probCondit', 'v_probCondit6');
addPage_2('en/probCondit', 'probCondit7', "Law of total probability", 'static', 'en/probCondit', 's_probCondit7', 'en/probCondit', 'v_probCondit7');
addPage_2('en/probCondit', 'probCondit8', "Bayes theorem", 'interact', 'en/probCondit', 's_probCondit8', 'en/probCondit', 'v_probCondit8');

addChapter('bk/mathStats', 'ch_distributions', "Random Variables");
addSection('bk/mathStats', 'sec_discreteDistns', "Discrete random variables");
addPage_2('en/discreteDistns', 'discreteDistns1', "Discrete distributions", 'static', 'en/discreteDistns', 's_discreteDistns1', 'en/discreteDistns', 'v_discreteDistns1');
addPage_2('en/discreteDistns', 'discreteDistns2', "Cumulative distribution function", 'interact', 'en/discreteDistns', 's_discreteDistns2', 'en/discreteDistns', 'v_discreteDistns2');
addPage_2('en/discreteDistns', 'discreteDistns3', "Mean", 'static', 'en/discreteDistns', 's_discreteDistns3', 'en/discreteDistns', 'v_discreteDistns3');
addPage_2('en/discreteDistns', 'discreteDistns4', "Expected values", 'static', 'en/discreteDistns', 's_discreteDistns4', 'en/discreteDistns', 'v_discreteDistns4');
addPage_2('en/discreteDistns', 'discreteDistns5', "Variance", 'static', 'en/discreteDistns', 's_discreteDistns5', 'en/discreteDistns', 'v_discreteDistns5');
addSection('bk/mathStats', 'sec_continuousDistns', "Continuous random variables");
addPage_2('en/continuousDistns', 'continuousDistns1', "Probability density functions", 'interact', 'en/continuousDistns', 's_continuousDistns1', 'en/continuousDistns', 'v_continuousDistns1');
addPage_2('en/continuousDistns', 'continuousDistns2', "Probability and area", 'interact', 'en/continuousDistns', 's_continuousDistns2', 'en/continuousDistns', 'v_continuousDistns2');
addPage_2('en/continuousDistns', 'continuousDistns3', "Mean and variance", 'static', 'en/continuousDistns', 's_continuousDistns3', 'en/continuousDistns', 'v_continuousDistns3');
addPage_2('en/continuousDistns', 'continuousDistns4', "Normal distributions", 'interact', 'en/continuousDistns', 's_continuousDistns4', 'en/continuousDistns', 'v_continuousDistns4');
addPage_2('en/continuousDistns', 'continuousDistns5', "Important normal quantiles", 'interact', 'en/continuousDistns', 's_continuousDistns5', 'en/continuousDistns', 'v_continuousDistns5');
addSection('bk/mathStats', 'sec_randomSample', "Discrete random samples");
addPage_2('en/randomSample', 'randomSample1', "Independence", 'static', 'en/randomSample', 's_randomSample1', 'en/randomSample', 'v_randomSample1');
addPage_2('en/randomSample', 'randomSample2', "Random samples", 'static', 'en/randomSample', 's_randomSample2', 'en/randomSample', 'v_randomSample2');
addPage_2('en/randomSample', 'randomSample3', "Functions of two variables", 'static', 'en/randomSample', 's_randomSample3', 'en/randomSample', 'v_randomSample3');
addPage_2('en/randomSample', 'randomSample4', "Properties of sums and means", 'static', 'en/randomSample', 's_randomSample4', 'en/randomSample', 'v_randomSample4');
addPage_2('en/randomSample', 'randomSample5', "Central limit theorem", 'static', 'en/randomSample', 's_randomSample5', 'en/randomSample', 'v_randomSample5');
addSection('bk/mathStats', 'sec_uniform', "Uniform distribution");
addPage_2('en/uniform', 'uniform1', "Family of uniform distributions", 'static', 'en/uniform', 's_uniform1', 'en/uniform', 'v_uniform1');
addPage_2('en/uniform', 'uniform2', "Mean and variance", 'static', 'en/uniform', 's_uniform2', 'en/uniform', 'v_uniform2');
addPage_2('en/uniform', 'uniform3', "Sample mean", 'interact', 'en/uniform', 's_uniform3', 'en/uniform', 'v_uniform3');

addChapter('bk/mathStats', 'ch_bernoulliTrials', "Successes and Failures");
addSection('bk/mathStats', 'sec_bernoulli', "Bernoulli distribution");
addPage_2('en/bernoulli', 'bernoulli1', "Bernoulli trials", 'static', 'en/bernoulli', 's_bernoulli1', 'en/bernoulli', 'v_bernoulli1');
addPage_2('en/bernoulli', 'bernoulli2', "Mean and variance", 'static', 'en/bernoulli', 's_bernoulli2', 'en/bernoulli', 'v_bernoulli2');
addSection('bk/mathStats', 'sec_binomial', "Binomial distribution");
addPage_2('en/binomial', 'binomial1', "Binomial random variable", 'static', 'en/binomial', 's_binomial1', 'en/binomial', 'v_binomial1');
addPage_2('en/binomial', 'binomial2', "Binomial probability function", 'static', 'en/binomial', 's_binomial2', 'en/binomial', 'v_binomial2');
addPage_2('en/binomial', 'binomial3', "Mean and variance", 'static', 'en/binomial', 's_binomial3', 'en/binomial', 'v_binomial3');
addPage_2('en/binomial', 'binomial4', "Shape of the binomial distribution", 'interact', 'en/binomial', 's_binomial4', 'en/binomial', 'v_binomial4');
addPage_2('en/binomial', 'binomial5', "Binomial examples", 'static', 'en/binomial', 's_binomial5', 'en/binomial', 'v_binomial5');
addPage_2('en/binomial', 'binomial6', "Cumulative probabilities", 'interact', 'en/binomial', 's_binomial6', 'en/binomial', 'v_binomial6');
addSection('bk/mathStats', 'sec_geometric', "Geometric distribution");
addPage_2('en/geometric', 'geometric1', "Geometric random variable", 'interact', 'en/geometric', 's_geometric1', 'en/geometric', 'v_geometric1');
addPage_2('en/geometric', 'geometric2', "Cumulative distribution function", 'interact', 'en/geometric', 's_geometric2', 'en/geometric', 'v_geometric2');
addPage_2('en/geometric', 'geometric3', "Examples", 'static', 'en/geometric', 's_geometric3', 'en/geometric', 'v_geometric3');
addPage_2('en/geometric', 'geometric4', "Mean and variance", 'static', 'en/geometric', 's_geometric4', 'en/geometric', 'v_geometric4');
addSection('bk/mathStats', 'sec_negBinomial', "Negative binomial distribution");
addPage_2('en/negBinomial', 'negBinomial1', "Probability function", 'interact', 'en/negBinomial', 's_negBinomial1', 'en/negBinomial', 'v_negBinomial1');
addPage_2('en/negBinomial', 'negBinomial2', "Alternative form", 'static', 'en/negBinomial', 's_negBinomial2', 'en/negBinomial', 'v_negBinomial2');
addPage_2('en/negBinomial', 'negBinomial3', "Finding negative binomial probabilities", 'static', 'en/negBinomial', 's_negBinomial3', 'en/negBinomial', 'v_negBinomial3');
addPage_2('en/negBinomial', 'negBinomial4', "Cumulative distribution function", 'static', 'en/negBinomial', 's_negBinomial4', 'en/negBinomial', 'v_negBinomial4');
addPage_2('en/negBinomial', 'negBinomial5', "Mean and variance", 'static', 'en/negBinomial', 's_negBinomial5', 'en/negBinomial', 'v_negBinomial5');

addChapter('bk/mathStats', 'ch_continuous', "Continuous Distributions");
addSection('bk/mathStats', 'sec_continuousProbs', "Finding probabilities");
addPage_2('en/continuousProbs', 'continuousProbs1', "Probabilities by integration", 'interact', 'en/continuousProbs', 's_continuousProbs1', 'en/continuousProbs', 'v_continuousProbs1');
addPage_2('en/continuousProbs', 'continuousProbs2', "Rectangular distribution", 'static', 'en/continuousProbs', 's_continuousProbs2', 'en/continuousProbs', 'v_continuousProbs2');
addPage_2('en/continuousProbs', 'continuousProbs3', "Other examples", 'static', 'en/continuousProbs', 's_continuousProbs3', 'en/continuousProbs', 'v_continuousProbs3');
addPage_2('en/continuousProbs', 'continuousProbs4', "Cumulative distribution function", 'static', 'en/continuousProbs', 's_continuousProbs4', 'en/continuousProbs', 'v_continuousProbs4');
addPage_2('en/continuousProbs', 'continuousProbs5', "Quantiles", 'static', 'en/continuousProbs', 's_continuousProbs5', 'en/continuousProbs', 'v_continuousProbs5');
addSection('bk/mathStats', 'sec_continuousMeanVar', "Mean and variance");
addPage_2('en/continuousMeanVar', 'continuousMeanVar1', "Expected values", 'static', 'en/continuousMeanVar', 's_continuousMeanVar1', 'en/continuousMeanVar', 'v_continuousMeanVar1');
addPage_2('en/continuousMeanVar', 'continuousMeanVar2', "Mean and variance", 'static', 'en/continuousMeanVar', 's_continuousMeanVar2', 'en/continuousMeanVar', 'v_continuousMeanVar2');
addPage_2('en/continuousMeanVar', 'continuousMeanVar3', "Example", 'static', 'en/continuousMeanVar', 's_continuousMeanVar3', 'en/continuousMeanVar', 'v_continuousMeanVar3');
addSection('bk/mathStats', 'sec_continuousSamples', "Random samples");
addPage_2('en/continuousSamples', 'continuousSamples1', "Independence and random samples", 'static', 'en/continuousSamples', 's_continuousSamples1', 'en/continuousSamples', 'v_continuousSamples1');
addPage_2('en/continuousSamples', 'continuousSamples2', "Distribution of sample sum and mean", 'static', 'en/continuousSamples', 's_continuousSamples2', 'en/continuousSamples', 'v_continuousSamples2');
addSection('bk/idems_prob', 'sec_normal', "Normal distribution");
addPage_2('en/normal', 'normal1', "Standard normal distribution", 'interact', 'en/normal', 's_normal1', 'en/normal', 'v_normal1');
addPage_2('en/normal', 'normal2', "Mean and variance", 'static', 'en/normal', 's_normal2', 'en/normal', 'v_normal2');
addPage_2('en/normal', 'normal3', "Z-scores", 'interact', 'en/normal', 's_normal3', 'en/normal', 'v_normal3');
addPage_2('en/normal', 'normal4', "Probabilities for normal distributions", 'interact', 'en/normal', 's_normal4', 'en/normal', 'v_normal4');
addPage_2('en/normal', 'normal5', "Normal quantiles", 'static', 'en/normal', 's_normal5', 'en/normal', 'v_normal5');

addChapter('bk/mathStats', 'ch_eventsInTime', "Events in Time");
addSection('bk/mathStats', 'sec_poisson', "Poisson distribution");
addPage_2('en/poisson', 'poisson1', "Poisson process", 'static', 'en/poisson', 's_poisson1', 'en/poisson', 'v_poisson1');
addPage_2('en/poisson', 'poisson2', "Events in fixed time", 'interact', 'en/poisson', 's_poisson2', 'en/poisson', 'v_poisson2');
addPage_2('en/poisson', 'poisson3', "Poisson probability function", 'interact', 'en/poisson', 's_poisson3', 'en/poisson', 'v_poisson3');
addPage_2('en/poisson', 'poisson4', "Mean and variance", 'static', 'en/poisson', 's_poisson4', 'en/poisson', 'v_poisson4');
addPage_2('en/poisson', 'poisson5', "Example", 'static', 'en/poisson', 's_poisson5', 'en/poisson', 'v_poisson5');
addPage_2('en/poisson', 'poisson6', "Maximum likelihood", 'static', 'en/poisson', 's_poisson6', 'en/poisson', 'v_poisson6');
addPage_2('en/poisson', 'poisson7', "Confidence interval for rate", 'static', 'en/poisson', 's_poisson7', 'en/poisson', 'v_poisson7');
addSection('bk/mathStats', 'sec_exponential', "Exponential distribution");
addPage_2('en/exponential', 'exponential1', "Time until first event", 'interact', 'en/exponential', 's_exponential1', 'en/exponential', 'v_exponential1');
addPage_2('en/exponential', 'exponential2', "Other exponential probabilities", 'static', 'en/exponential', 's_exponential2', 'en/exponential', 'v_exponential2');
addPage_2('en/exponential', 'exponential3', "Gamma functions", 'static', 'en/exponential', 's_exponential3', 'en/exponential', 'v_exponential3');
addPage_2('en/exponential', 'exponential4', "Mean and variance", 'static', 'en/exponential', 's_exponential4', 'en/exponential', 'v_exponential4');
addPage_2('en/exponential', 'exponential5', "Maximum likelihood", 'static', 'en/exponential', 's_exponential5', 'en/exponential', 'v_exponential5');
addPage_2('en/exponential', 'exponential6', "Confidence intervals", 'static', 'en/exponential', 's_exponential6', 'en/exponential', 'v_exponential6');
addSection('bk/idems_prob', 'sec_erlang', "Time until k'th event");
addPage_2('en/erlang', 'erlang1', "Erlang distribution#?# Opt", 'static', 'en/erlang', 's_erlang1', 'en/erlang', 'v_erlang1');
addPage_2('en/erlang', 'erlang2', "Mean and variance#?# Opt", 'static', 'en/erlang', 's_erlang2', 'en/erlang', 'v_erlang2');
addPage_2('en/erlang', 'erlang3', "Probabilities#?# Opt", 'static', 'en/erlang', 's_erlang3', 'en/erlang', 'v_erlang3');

addChapter('bk/idems_prob', 'ch_sampling', "Exercises");
addSection('bk/exercises', 'sec_probDistn', "Probability and distributions");
addPage_2('en/probSim', 'e_probSim1', "Equally likely outcomes", 'static');
addPage_2('en/probSim', 'e_probSim2', "Value from finite categorical population", 'static');
addPage_2('en/probSim', 'e_probSim3', "Value from finite numerical population", 'static');
addPage_2('en/probSim', 'e_probSim4', "Random value from infinite population", 'static');
addPage_2('en/probSim', 'e_probSim5', "Equally likely outcomes", 'static');
addSection('bk/exercises', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'e_normalDistn1', "Shape of normal distribution ", 'static');
addPage_2('en/normalDistn', 'e_normalDistn2', "Probability and area under normal curve", 'static');
addPage_2('en/normalDistn', 'e_normalDistn3', "Normal probabilities from z-scores", 'static');
addPage_2('en/normalDistn', 'e_normalDistn4', "Expected numbers", 'static');
addPage_2('en/normalDistn', 'e_normalDistn5', "Finding X from probability", 'static');
addPage_2('en/normalDistn', 'e_normalDistn6', "Mixture of questions", 'static');
addPage_2('en/normalDistn', 'e_normalDistn7', "Guessing normal probabilities", 'static');
addSection('bk/exercises', 'sec_binomial', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'e_randomPropn1', "Recognising a binomial distribution", 'static');
addPage_2('en/randomPropn', 'e_randomPropn2', "Shape of binomial distribution", 'static');
addPage_2('en/randomPropn', 'e_randomPropn3', "Finding binomial probabilities", 'static');
addPage_2('en/randomPropn', 'e_randomPropn4', "Normal approximation", 'static');
addPage_2('en/randomPropn', 'e_randomPropn5', "Probabilities from normal approximation", 'static');
addSection('bk/exercises', 'sec_meanSum', "Distributions of means &amp; sums");
addPage_2('en/randomMean', 'e_randomMean1', "Spread of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean2', "Shape of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean3', "Distribution of mean and sum (cont)", 'static');
addPage_2('en/randomMean', 'e_randomMean4', "Probabilities relating to means and sums", 'static');

var language = "en";
var logoGif = null;
var homeDir = "bk/idems_prob";
var versionGif = "images/castTheory";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "7";

var localVideos = false;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_e': 'null'};
var versions = {};
versions['e_normalDistn1'] = new Array('_g', '_e');
versions['e_normalDistn2'] = new Array('_g', '_e');
versions['e_randomPropn1'] = new Array('_g', '_e');
versions['e_randomPropn2'] = new Array('_g', '_e');
versions['e_randomMean1'] = new Array('_g', '_e');

bookLoaded = true;
