
addBook('bk/sms', 'book_splash', "About this CAST e-book");

addChapter('bk/sms', 'ch_preface', "Preface");
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/sms', 'ch_intro', "What is Statistics?");
addSection('bk/sms', 'sec_context', "Context");
addPage_2('en/context', 'context_c1', "Importance of context", 'static', 'en/context', 's_context1', 'en/context', 'v_context_c1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3', 'en/context', 'v_context3');
addSection('bk/sms', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures_c1', "Variables and individuals", 'interact', 'en/structures', 's_structures_c1', 'en/structures', 'v_structures_c1');
addPage_2('en/structures', 'structures_c2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures_c2');
addPage_2('en/structures', 'structures_c3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures_c3');
addSection('bk/sms', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');
addPage_2('en/variation', 'variation_c5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5', 'en/variation', 'v_variation_c5');
addPage_2('en/variation', 'variation6', "Predicting future variation", 'static', 'en/variation', 's_variation6', 'en/variation', 'v_variation6');
addSection('bk/sms', 'sec_Exercise1', "Exercises");
addPage_2('en/freqTable', 'e_freqTable1', "Types of variables", 'static');
addPage_2('en/centerSpread', 'e_centerSpread1', "Ideas of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread4', "Standard deviation from general knowledge#?# (Optional)", 'static');

addChapter('bk/sms', 'ch_univar', "Describing Data Well");
addSection('bk/sms', 'sec_Dotplots', "Graphical display - dotplots");
addPage_2('en/valueDisplay', 'valueDisplay_c1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay_c1');
addPage_2('en/valueDisplay', 'valueDisplay_c2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay_c2');
addPage_2('en/valueDisplay', 'valueDisplay_c3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay_c3');
addPage_2('en/valueDisplay', 'valueDisplay_c4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay_c4');
addSection('bk/sms', 'sec_boxPlot', "Graphical display - boxplots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot_c6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot_c6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7', 'en/boxPlot', 'v_boxPlot7');
addSection('bk/sms', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread_c3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread_c3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addPage_2('en/moreVariation', 'moreVariation1', "Effect of outliers", 'interact', 'en/moreVariation', 's_moreVariation1', 'en/moreVariation', 'v_moreVariation1');
addSection('bk/sms', 'sec_Exercise2', "Exercises");
addPage_2('en/valueDisplay', 'e_valueDisplay2', "Stacked dot plots", 'static');
addPage_2('en/boxPlot', 'e_boxPlot1', "Box plots", 'static');
addPage_2('en/boxPlot', 'e_boxPlot2', "Shape of a box plot", 'static');
addPage_2('en/displayInterp', 'e_displayInterp1', "Information from distributions", 'static');
addPage_2('en/centerSpread', 'e_centerSpread1', "Ideas of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread2', "Mean and median", 'static');
addPage_2('en/centerSpread', 'e_centerSpread3', "Standard deviation from graph", 'static');

addChapter('bk/sms', 'ch_sample', "Making Good Generalisations");
addSection('bk/sms', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp_c1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp_c1');
addPage_2('en/popSamp', 'popSamp_c2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp_c2');
addPage_2('en/popSamp', 'popSamp_c3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp_c3');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addSection('bk/sms', 'sec_infPopn', "Infinite populations");
addPage_2('en/infPopn', 'infPopn_c1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn_c1', 'en/infPopn', 'v_infPopn_c1');
addPage_2('en/infPopn', 'infPopn_c2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2', 'en/infPopn', 'v_infPopn_c2');
addPage_2('en/infPopn', 'infPopn_c3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3', 'en/infPopn', 'v_infPopn_c3');
addPage_2('en/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact', 'en/infPopn', 's_infPopn4', 'en/infPopn', 'v_infPopn4');
addPage_2('en/infPopn', 'infPopn_c5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5', 'en/infPopn', 'v_infPopn_c5');
addSection('bk/sms', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn_c1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1', 'en/normalDistn', 'v_normalDistn_c1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn_c3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn_c3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addSection('bk/sms', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_c1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean_c1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addSection('bk/sms', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro_c1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro_c1', 'en/estIntro', 'v_estIntro1');
addPage_2('en/estIntro', 'estIntro_c2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2', 'en/estIntro', 'v_estIntro2');
addPage_2('en/seMean', 'seMean_c4', "Standard error", 'static', 'en/seMean', 's_seMean_c4', 'en/seMean', 'v_seMean_c4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addSection('bk/sms', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean_c1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean_c1');
addPage_2('en/ciMean', 'ciMean4', "Confidence level", 'interact', 'en/ciMean', 's_ciMean4', 'en/ciMean', 'v_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean", 'interact', 'en/ciMean', 's_ciMean5', 'en/ciMean', 'v_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6', 'en/ciMean', 'v_ciMean6');
addPage_2('en/ciMean', 'ciMean_c7', "Examples", 'static', 'en/ciMean', 's_ciMean_c7', 'en/ciMean', 'v_ciMean_c7');
addSection('bk/sms', 'sec_Exercise3', "Exercises");
addPage_2('en/normalDistn', 'e_normalDistn1', "Shape of normal distribution ", 'static');
addPage_2('en/normalDistn', 'e_normalDistn7', "Guessing normal probabilities", 'static');
addPage_2('en/popSamp', 'e_popSamp1', "Distinction between populations and samples", 'static');
addPage_2('en/popSamp', 'e_popSamp2', "Distinction between parameters and estimates", 'static');
addPage_2('en/seMean', 'e_seMean1', "Standard error of mean", 'static');
addPage_2('en/seMean', 'e_seMean2', "Standard error vs standard deviation", 'static');
addPage_2('en/seMean', 'e_seMean3', "Factors affecting the standard deviation and standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean3', "95% confidence interval, unknown sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean6', "Factors affecting width of CI", 'static');
addPage_2('en/ciMean', 'e_ciMean7', "Interpreting a 95% confidence interval", 'static');

addChapter('bk/sms', 'ch_testing', "Testing Hypotheses");
addSection('bk/sms', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro1', "Inference", 'static', 'en/testIntro', 's_testIntro1', 'en/testIntro', 'v_testIntro1');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4', 'en/testIntro', 'v_testIntro4');
addPage_2('en/testIntro', 'testIntro_c7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7', 'en/testIntro', 'v_testIntro_c7');
addSection('bk/sms', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean_c1', "Introduction", 'static', 'en/testMean', 's_testMean1', 'en/testMean', 'v_testMean_c1');
addPage_2('en/testMean', 'testMean_c4', "The t distribution", 'interact', 'en/testMean', 's_testMean4', 'en/testMean', 'v_testMean_c4');
addPage_2('en/testMean', 'testMean_c5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5', 'en/testMean', 'v_testMean_c5');
addSection('bk/sms', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'testPValue_c1', "Null and alternative hypotheses", 'interact', 'en/testPValue', 's_testPValue1', 'en/testPValue', 'v_testPValue_c1');
addPage_2('en/testPValue', 'testPValue_c2', "Consistency with null hypothesis", 'interact', 'en/testPValue', 's_testPValue2', 'en/testPValue', 'v_testPValue_c2');
addPage_2('en/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact', 'en/testPValue', 's_testPValue4', 'en/testPValue', 'v_testPValue4');
addSection('bk/sms', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel_c1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel_c1', 'en/twoGroupModel', 'v_twoGroupModel_c1');
addPage_2('en/twoGroupModel', 'twoGroupModel_c2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2', 'en/twoGroupModel', 'v_twoGroupModel_c2');
addPage_2('en/twoGroupInf', 'twoGroupInf_c4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf_c4', 'en/twoGroupInf', 'v_twoGroupInf_c4');
addPage_2('en/twoGroupInf', 'twoGroupInf_c5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf_c5', 'en/twoGroupInf', 'v_twoGroupInf_c5');
addSection('bk/sms', 'sec_Exercise4', "Exercises");
addPage_2('en/testPValue', 'e_testPValue1', "Generic interpretation of a p-values", 'static');
addPage_2('en/testPValue', 'e_testPValue2', "Interpretation of p-values (in context)", 'static');
addPage_2('en/testPValue', 'e_testPValue3', "Interpretation of p-values (harder)", 'static');

addChapter('bk/sms', 'ch_bivar', "Statistical Models");
addSection('bk/sms', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot_c1', "Bivariate data sets", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot_c4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot_c4');
addPage_2('en/scatterplot', 'scatterplot_c5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5', 'en/scatterplot', 'v_scatterplot_c5');
addSection('bk/sms', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship_c1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship_c1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'en/relationship', 'v_relationship2');
addPage_2('en/relationship', 'relationship_c3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship_c5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship_c5');
addSection('bk/sms', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2', 'en/leastSqrs', 'v_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs_c3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs_c3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addPage_2('en/curvature', 'curvature_c3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3', 'en/curvature', 'v_curvature_c3');
addSection('bk/sms', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel_c1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel_c1', 'en/regnModel', 'v_regnModel_c1');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3', 'en/regnModel', 'v_regnModel3');
addPage_2('en/regnModel', 'regnModel_c5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel_c5', 'en/regnModel', 'v_regnModel_c5');
addSection('bk/sms', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst_c1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1', 'en/regnEst', 'v_regnEst_c1');
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3', 'en/regnEst', 'v_regnEst3');
addPage_2('en/regnEst', 'regnEst_c4', "Standard error of least squares slope", 'static', 'en/regnEst', 's_regnEst_c4', 'en/regnEst', 'v_regnEst_c4');
addPage_2('en/regnEst', 'regnEst_c5', "95% confidence interval for slope", 'static', 'en/regnEst', 's_regnEst_c5', 'en/regnEst', 'v_regnEst_c5');
addPage_2('en/regnEst', 'regnEst6', "Properties of confidence interval", 'interact', 'en/regnEst', 's_regnEst6', 'en/regnEst', 'v_regnEst6');
addSection('bk/sms', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest_c1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1', 'en/regnTest', 'v_regnTest_c1');
addPage_2('en/regnTest', 'regnTest_c2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest_c2', 'en/regnTest', 'v_regnTest_c2');
addSection('bk/sms', 'sec_Exercise5', "Exercises");
addPage_2('en/leastSqrs', 'e_leastSqrs2', "Drawing a straight line", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs3', "Slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs4', "Interpreting the slope and intercept", 'static');
addPage_2('en/regnEst', 'e_regnEst1', "Standard error of slope", 'static');
addPage_2('en/regnTest', 'e_regnTest1', "Test for zero slope", 'static');
addPage_2('en/curvature', 'e_curvature1', "Regression problems", 'static');

addChapter('bk/sms', 'ch_cat', "Categorical Variables");
addSection('bk/sms', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable_c1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable_c1', 'en/freqTable', 'v_freqTable_c1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addSection('bk/sms', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('en/univarCat', 'univarCat3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat3', 'en/univarCat', 'v_univarCat3');
addPage_2('en/univarCat', 'univarCat_c4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat_c4');
addPage_2('en/univarCat', 'univarCat_c5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat_c5');
addPage_2('en/univarCat', 'univarCat_c6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat_c6', 'en/univarCat', 'v_univarCat_c6');
addPage_2('en/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat7');
addSection('bk/sms', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat_c1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat_c1', 'en/groupedCat', 'v_groupedCat_c1');
addPage_2('en/groupedCat', 'groupedCat_c2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat_c2', 'en/groupedCat', 'v_groupedCat_c2');
addPage_2('en/groupedCat', 'groupedCat_c3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat_c3', 'en/groupedCat', 'v_groupedCat_c3');
addPage_2('en/groupedCat', 'groupedCat_c4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat_c4', 'en/groupedCat', 'v_groupedCat_c4');
addPage_2('en/groupedCat', 'groupedCat_c5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5', 'en/groupedCat', 'v_groupedCat_c5');
addSection('bk/sms', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2', 'en/tableDisplay', 'v_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4', 'en/tableDisplay', 'v_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5', 'en/tableDisplay', 'v_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6', 'en/tableDisplay', 'v_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7', 'en/tableDisplay', 'v_tableDisplay7');
addSection('bk/sms', 'sec_Exercise6', "Exercises");
addPage_2('en/freqTable', 'e_freqTable1', "Types of variables#?# (also in Topic 1)", 'static');
addPage_2('en/freqTable', 'e_freqTable2', "Proportions from frequency tables", 'static');
addPage_2('en/freqTable', 'e_freqTable3', "Proportions for ordered categories", 'static');
addPage_2('en/univarCat', 'e_univarCat1', "Drawing a bar chart", 'static');
addPage_2('en/univarCat', 'e_univarCat2', "Proportions and percentages from bar charts", 'static');
addPage_2('en/univarCat', 'e_univarCat4', "Drawing a pie chart", 'static');
addPage_2('en/groupedCat', 'e_groupedCat1', "Creating a 2-way table", 'static');
addPage_2('en/groupedCat', 'e_groupedCat2', "Proportions from a 2-way table", 'static');

addChapter('bk/sms', 'ch_ANOVA', "Explaining Variability");
addSection('bk/sms', 'sec_moreVariation', "More about variation");
addPage_2('en/centerSpread', 'centerSpread_c7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread_c7');
addPage_2('en/moreVariation', 'moreVariation1', "Effect of outliers", 'interact', 'en/moreVariation', 's_moreVariation1', 'en/moreVariation', 'v_moreVariation1');
addPage_2('en/moreVariation', 'moreVariation2', "Standard deviation of grouped data", 'interact', 'en/moreVariation', 's_moreVariation2', 'en/moreVariation', 'v_moreVariation2');
addPage_2('en/moreVariation', 'moreVariation3', "Explained and unexplained variation", 'interact', 'en/moreVariation', 's_moreVariation3', 'en/moreVariation', 'v_moreVariation3');
addPage_2('en/moreVariation', 'moreVariation4', "Variance and degrees of freedom", 'static', 'en/moreVariation', 's_moreVariation4', 'en/moreVariation', 'v_moreVariation4');
addSection('bk/sms', 'sec_multiGroup', "Comparing several means");
addPage_2('en/multiGroup', 'multiGroup_c1', "Model", 'interact', 'en/multiGroup', 's_multiGroup1', 'en/multiGroup', 'v_multiGroup_c1');
addPage_2('en/multiGroup', 'multiGroup2', "Parameter estimates", 'interact', 'en/multiGroup', 's_multiGroup2', 'en/multiGroup', 'v_multiGroup2');
addPage_2('en/multiGroup', 'multiGroup4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup_c6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup_c6', 'en/multiGroup', 'v_multiGroup_c6');
addPage_2('en/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addPage_2('en/multiGroup', 'multiGroup_c8', "Examples", 'static', 'en/multiGroup', 's_multiGroup_c8', 'en/multiGroup', 'v_multiGroup_c8');
addSection('bk/sms', 'sec_regnAnova', "Anova for simple linear model");
addPage_2('en/regnAnova', 'regnAnova1', "Components for regression model", 'interact');
addPage_2('en/regnAnova', 'regnAnova2', "Sums of squares", 'interact');
addPage_2('en/regnAnova', 'regnAnova3', "Coefficient of determination", 'interact');
addPage_2('en/regnAnova', 'regnAnova5', "Analysis of variance test", 'static');
addSection('bk/sms', 'sec_nonlinAnova', "Trying a quadratic curve");
addPage_2('en/nonlinAnova', 'nonlinAnova1', "Linear and quadratic models", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova2', "Understanding the sums of squares", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova3', "Testing for linearity", 'interact');
addSection('bk/sms', 'sec_Exercise7', "Exercises");
addPage_2('en/centerSpread', 'e_centerSpread4', "Standard deviation from general knowledge", 'static');
addPage_2('en/centerSpread', 'e_centerSpread5', "Rough graph from mean and st devn", 'static');
addPage_2('en/centerSpread', 'e_centerSpread6', "Clusters and outliers (advanced)", 'static');

addChapter('bk/sms', 'ch_nonNormal', "Non-Normal Data");
addSection('bk/sms', 'sec_randomMean2', "Distribution of sample mean");
addPage_2('en/probDensity', 'probDensity_c5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5', 'en/probDensity', 'v_probDensity_c5');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/randomMean', 'randomMean_c6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean_c6', 'en/randomMean', 'v_randomMean_c6');
addPage_2('en/randomMean', 'randomMean7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7', 'en/randomMean', 'v_randomMean7');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10', 'en/normalDistn', 'v_normalDistn10');
addSection('bk/sms', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts_c1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1', 'en/counts', 'v_counts_c1');
addPage_2('en/counts', 'counts_c2', "Histograms for counts", 'interact', 'en/counts', 's_counts2', 'en/counts', 'v_counts_c2');
addPage_2('en/counts', 'counts_c3', "Bar charts", 'interact', 'en/counts', 's_counts3', 'en/counts', 'v_counts_c3');
addSection('bk/sms', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/popSamp', 'popSamp_c3', "Estimating means and proportions#?# (also in Chapter/Topic 3)", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp_c3');
addPage_2('en/randomPropn', 'randomPropn_c1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1', 'en/randomPropn', 'v_randomPropn_c1');
addPage_2('en/randomPropn', 'randomPropn_c2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn_c2');
addPage_2('en/randomPropn', 'randomPropn_c3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn_c3');
addPage_2('en/randomPropn', 'randomPropn_c4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn_c4', 'en/randomPropn', 'v_randomPropn_c4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'en/randomPropn', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn_c6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn_c6', 'en/randomPropn', 'v_randomPropn_c6');
addSection('bk/sms', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('en/estPropn', 'estPropn_c3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn_c3');
addPage_2('en/estPropn', 'estPropn_c4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn_c4', 'en/estPropn', 'v_estPropn_c4');
addPage_2('en/estPropn', 'estPropn_c5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5', 'en/estPropn', 'v_estPropn_c5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('en/estPropn', 'estPropn_c7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn_c7', 'en/estPropn', 'v_estPropn_c7');
addSection('bk/sms', 'sec_estOther', "Simulation &amp; bootstrap");
addPage_2('en/estOther', 'estOther1', "Need for simulation", 'static', 'en/estOther', 's_estOther1', 'en/estOther', 'v_estOther1');
addPage_2('en/estOther', 'estOther2', "Error distribution by simulation", 'interact', 'en/estOther', 's_estOther2', 'en/estOther', 'v_estOther2');
addPage_2('en/estOther', 'estOther_c3', "Simulations with normal distns", 'interact', 'en/estOther', 's_estOther_c3', 'en/estOther', 'v_estOther_c3');
addPage_2('en/estOther', 'estOther4', "Bootstrap error distribution", 'interact', 'en/estOther', 's_estOther4', 'en/estOther', 'v_estOther4');
addSection('bk/sms', 'sec_ciProportion', "Exercises");
addPage_2('en/normalDistn', 'e_normalDistn7', "Guessing normal probabilities", 'static');
addPage_2('en/randomMean', 'e_randomMean1', "Spread of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean2', "Shape of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean3', "Distribution of mean and sum (cont)", 'static');
addPage_2('en/estPropn', 'e_estPropn1', "Standard error of proportion", 'static');
addPage_2('en/estPropn', 'e_estPropn2', "95% confidence interval for probability", 'static');
addPage_2('en/estPropn', 'e_estPropn3', "Other confidence levels", 'static');
addPage_2('en/estPropn', 'e_estPropn4', "Factors affecting width of confidence interval", 'static');
addPage_2('en/estPropn', 'e_estPropn5', "Interpreting a 95% confidence interval", 'static');

addChapter('bk/sms', 'ch_multivar', "General Modelling Ideas");
addSection('bk/business', 'sec_regnGroups', "Groups and regression");
addPage_2('en/regnGroups', 'regnGroups1', "Additional variables in regression", 'interact', 'en/regnGroups', 's_regnGroups1', 'en/regnGroups', 'v_regnGroups1');
addPage_2('en/regnGroups', 'regnGroups2', "Displaying groups", 'interact', 'en/regnGroups', 's_regnGroups2', 'en/regnGroups', 'v_regnGroups2');
addPage_2('en/regnGroups', 'regnGroups3', "Regression with grouped data", 'interact', 'en/regnGroups', 's_regnGroups3', 'en/regnGroups', 'v_regnGroups3');
addPage_2('en/regnGroups', 'regnGroups4', "Parallel regression lines", 'interact', 'en/regnGroups', 's_regnGroups4', 'en/regnGroups', 'v_regnGroups4');
addPage_2('en/regnGroups', 'regnGroups5', "Transformed variables and groups", 'interact', 'en/regnGroups', 's_regnGroups5', 'en/regnGroups', 'v_regnGroups5');
addPage_2('en/regnGroups', 'regnGroups6', "Grouping with a numerical variable", 'interact', 'en/regnGroups', 's_regnGroups6', 'en/regnGroups', 'v_regnGroups6');
addPage_2('en/regnGroups', 'regnGroups_c7', "Displaying groups", 'interact', 'en/regnGroups', 's_regnGroups7', 'en/regnGroups', 'v_regnGroups_c7');
addSection('bk/sms', 'sec_multiRegn', "Multiple regression");
addPage_2('en/multiRegn', 'multiRegn1', "More than one explanatory variable", 'interact', 'en/multiRegn', 's_multiRegn1', 'en/multiRegn', 'v_multiRegn1');
addPage_2('en/multiRegn', 'multiRegn2', "Multiple regression equation", 'interact', 'en/multiRegn', 's_multiRegn2', 'en/multiRegn', 'v_multiRegn2');
addPage_2('en/multiRegn', 'multiRegn3', "Interpreting coefficients", 'interact', 'en/multiRegn', 's_multiRegn3', 'en/multiRegn', 'v_multiRegn3');
addPage_2('en/multiRegn', 'multiRegn7', "Least squares estimation", 'interact', 'en/multiRegn', 's_multiRegn7', 'en/multiRegn', 'v_multiRegn7');
addSection('bk/sms', 'sec_multiRegnAnova', "All-or-nothing anova (Optional)");
addPage_2('en/multiRegnAnova', 'multiRegnAnova1', "Components of variation for Y vs X and Z", 'interact');
addPage_2('en/multiRegnAnova', 'multiRegnAnova2', "Sums of squares for Y vs X and Z", 'interact');
addPage_2('en/multiRegnAnova', 'multiRegnAnova3', "F test for regression of Y vs X and Z", 'interact');
addPage_2('en/multiRegnAnova', 'multiRegnAnova4', "All-or-nothing F test for any GLM", 'static');
addPage_2('en/multiRegnAnova', 'multiRegnAnova5', "Different interpretations of R-sqr and F", 'interact');
addSection('bk/sms', 'sec_seqRegnSsq', "Sequential sums of squares (Optional)");
addPage_2('en/seqRegnSsq', 'seqRegnSsq1', "Sequentially adding variables", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq2', "Splitting the explained sum of squares", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq3', "Order of adding X and Z", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq4', "Anova tests for individual variables", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq5', "Orthogonal variables", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq6', "Orthogonal variables and experimental design", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq7', "Other sequences of models", 'static');
addSection('bk/business', 'sec_logistic', "Logistic regression");
addPage_2('en/logistic', 'logistic_c1', "Categorical responses", 'interact', 'en/logistic', 's_logistic1', 'en/logistic', 'v_logistic1');
addPage_2('en/logistic', 'logistic_c2', "Fitted values and predictions", 'interact', 'en/logistic', 's_logistic2', 'en/logistic', 'v_logistic_c2');
addPage_2('en/logistic', 'logistic3', "Logistic curve", 'interact', 'en/logistic', 's_logistic3', 'en/logistic', 'v_logistic3');
addPage_2('en/logistic', 'logistic_c4', "Obtaining a good fit", 'interact', 'en/logistic', 's_logistic4', 'en/logistic', 'v_logistic_c4');

addChapter('bk/sms', 'ch_mountains', "Coming Down from the Mountains");
addSection('bk/sms', 'sec_Exercise10a', "Some review exercises");
addPage_2('en/boxPlot', 'e_boxPlot2', "Shape of a box plot", 'static');
addPage_2('en/displayInterp', 'e_displayInterp1', "Information from distributions", 'static');
addPage_2('en/centerSpread', 'e_centerSpread1', "Ideas of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread3', "Standard deviation from graph", 'static');
addPage_2('en/seMean', 'e_seMean3', "Factors affecting the standard deviation and standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean7', "Interpreting a 95% confidence interval", 'static');
addPage_2('en/testPValue', 'e_testPValue3', "Interpretation of p-values (harder)", 'static');
addSection('bk/sms', 'sec_Exercise10b', "A few more exercises!");
addPage_2('en/leastSqrs', 'e_leastSqrs4', "Interpreting the slope and intercept", 'static');
addPage_2('en/regnEst', 'e_regnEst1', "Standard error of slope", 'static');
addPage_2('en/curvature', 'e_curvature1', "Regression problems", 'static');
addPage_2('en/centerSpread', 'e_centerSpread6', "Clusters and outliers (advanced)", 'static');
addPage_2('en/randomMean', 'e_randomMean2', "Shape of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean3', "Distribution of mean and sum (cont)", 'static');
addPage_2('en/estPropn', 'e_estPropn4', "Factors affecting width of confidence interval", 'static');

var language = "en";
var logoGif = null;
var homeDir = "bk/sms";
var versionGif = "../general/images/castGeneral";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "11";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_c': 'Business', '_g': 'General', '_b': 'Biometric', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_c', '_g', '_b', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_c', '_g', '_a', '_b');
versions['structures2'] = new Array('_c', '_g', '_a', '_b');
versions['structures3'] = new Array('_c', '_g', '_o');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_c', '_g');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay2'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay3'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay4'] = new Array('_c', '_g', '_b', '_m');
versions['boxPlot6'] = new Array('_c', '_g');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_c', '_g', '_b', '_m');
versions['popSamp1'] = new Array('_c', '_g', '_a', '_b');
versions['popSamp2'] = new Array('_c', '_g');
versions['popSamp3'] = new Array('_c', '_g', '_a', '_b');
versions['infPopn1'] = new Array('_c', '_g', '_b');
versions['infPopn2'] = new Array('_c', '_g', '_b', '_z');
versions['infPopn3'] = new Array('_c', '_g', '_b');
versions['infPopn5'] = new Array('_c', '_g');
versions['normalDistn1'] = new Array('_c', '_g');
versions['normalDistn3'] = new Array('_c', '_g', '_b');
versions['randomMean1'] = new Array('_c', '_g', '_b');
versions['estIntro1'] = new Array('_c', '_g', '_b');
versions['estIntro2'] = new Array('_c', '_g', '_b');
versions['seMean4'] = new Array('_c', '_g', '_b');
versions['ciMean1'] = new Array('_c', '_g', '_m');
versions['ciMean7'] = new Array('_c', '_g', '_b');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_c', '_g', '_b');
versions['testMean1'] = new Array('_c', '_g');
versions['testMean4'] = new Array('_c', '_g');
versions['testMean5'] = new Array('_c', '_g');
versions['testPValue1'] = new Array('_c', '_g');
versions['testPValue2'] = new Array('_c', '_g', '_b');
versions['twoGroupModel1'] = new Array('_c', '_g', '_b');
versions['twoGroupModel2'] = new Array('_c', '_g', '_b');
versions['twoGroupInf4'] = new Array('_c', '_g', '_b');
versions['twoGroupInf5'] = new Array('_c', '_g', '_b');
versions['scatterplot1'] = new Array('_c', '_g', '_b');
versions['scatterplot4'] = new Array('_c', '_g');
versions['scatterplot5'] = new Array('_c', '_g');
versions['relationship1'] = new Array('_c', '_g');
versions['relationship3'] = new Array('_c', '_g');
versions['relationship5'] = new Array('_c', '_g');
versions['leastSqrs3'] = new Array('_c', '_g');
versions['curvature3'] = new Array('_c', '_g');
versions['regnModel1'] = new Array('_c', '_g', '_b');
versions['regnModel5'] = new Array('_c', '_g', '_b');
versions['regnEst1'] = new Array('_c', '_g');
versions['regnEst4'] = new Array('_c', '_g');
versions['regnEst5'] = new Array('_c', '_g');
versions['regnTest1'] = new Array('_c', '_g');
versions['regnTest2'] = new Array('_c', '_g');
versions['freqTable1'] = new Array('_c', '_g');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_c', '_g', '_b');
versions['univarCat5'] = new Array('_c', '_g', '_b');
versions['univarCat6'] = new Array('_c', '_g', '_b');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('_c', '_g');
versions['groupedCat2'] = new Array('_c', '_g', '_b');
versions['groupedCat3'] = new Array('_c', '_g', '_b');
versions['groupedCat4'] = new Array('_c', '_g', '_b');
versions['groupedCat5'] = new Array('_c', '_g', '_b');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['centerSpread7'] = new Array('_c', '_g');
versions['multiGroup1'] = new Array('_c', '_g', '_b');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_c', '_g', '_a', '_b');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_c', '_g', '_b');
versions['probDensity5'] = new Array('_c', '_g');
versions['randomMean6'] = new Array('_c', '_g', '_b');
versions['randomMean7'] = new Array('_g', '_b');
versions['counts1'] = new Array('_c', '_g', '_b');
versions['counts2'] = new Array('_c', '_g', '_b');
versions['counts3'] = new Array('_c', '_g');
versions['popSamp3'] = new Array('_c', '_g', '_a', '_b');
versions['randomPropn1'] = new Array('_c', '_g');
versions['randomPropn2'] = new Array('_c', '_g');
versions['randomPropn3'] = new Array('_c', '_g', '_b');
versions['randomPropn4'] = new Array('_c', '_g', '_b');
versions['randomPropn6'] = new Array('_c', '_g', '_b');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_c', '_g', '_b');
versions['estPropn4'] = new Array('_c', '_g', '_b');
versions['estPropn5'] = new Array('_c', '_g', '_b');
versions['estPropn7'] = new Array('_c', '_g', '_b');
versions['estOther3'] = new Array('_c', '_g', '_m');
versions['regnGroups7'] = new Array('_c', '_g');
versions['logistic1'] = new Array('_c', '_g', '_b');
versions['logistic2'] = new Array('_c', '_g', '_b');
versions['logistic4'] = new Array('_c', '_g', '_b');

bookLoaded = true;
