
addBook('bk/massey120', 'book_splash', "About this CAST e-book", null, 'v_book_splash');

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/massey120', 'ch_intro', "Introduction", null, 'v_ch_intro');
addSection('bk/general', 'sec_context', "Context");
addPage_2('en/context', 'context1', "Importance of context", 'static', 'en/context', 's_context1', 'en/context', 'v_context1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3', 'en/context', 'v_context3');
addSection('bk/massey120', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures1', "Variables and individuals", 'interact', 'en/structures', 's_structures1', 'en/structures', 'v_structures1');
addPage_2('en/structures', 'structures2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures3');
addPage_2('en/structures', 'structures4', "Meaningful variables", 'interact', 'en/structures', 's_structures4', 'en/structures', 'v_structures4');
addPage_2('en/structures', 'structures5', "Time-ordered data", 'static', 'en/structures', 's_structures5', 'en/structures', 'v_structures5');
addSection('bk/massey120', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');

addPart("Part A: NCEA Overlap");

addChapter('bk/massey120', 'ch_graphicalSum', "Graphical Summaries", null, 'v_ch_graphicalSum');
addSection('bk/massey120', 'sec_valueDisplay', "Dot plots &amp; stem-and-leaf plots");
addPage_2('en/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay1');
addPage_2('en/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay2');
addPage_2('en/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay4');
addPage_2('bk/massey120', 'valueDisplay5', "Simple stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5', 'en/valueDisplay', 'v_valueDisplay5');
addPage_2('bk/massey120', 'valueDisplay7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7', 'bk/massey120', 'v_valueDisplay7');
addSection('bk/general', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp1');
addPage_2('en/displayInterp', 'displayInterp2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp2');
addPage_2('en/displayInterp', 'displayInterp3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp3');
addPage_2('en/displayInterp', 'displayInterp4', "Names of individuals", 'interact', 'en/displayInterp', 's_displayInterp4', 'en/displayInterp', 'v_displayInterp4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp6');
addSection('bk/massey120', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2', 'en/density', 'v_density2');
addPage_2('en/density', 'density3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density3');
addPage_2('en/density', 'density4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('en/density', 'density6', "Comparing groups", 'interact', 'en/density', 's_density6', 'en/density', 'v_density6');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9', 'en/density', 'v_density9');
addSection('bk/massey120', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1', 'en/counts', 'v_counts1');
addPage_2('en/counts', 'counts2', "Histograms for counts", 'interact', 'en/counts', 's_counts2', 'en/counts', 'v_counts2');
addPage_2('en/counts', 'counts3', "Bar charts", 'interact', 'en/counts', 's_counts3', 'en/counts', 'v_counts3');
addSection('bk/general', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1', 'en/freqTable', 'v_freqTable1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addSection('bk/massey120', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('en/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat4');
addPage_2('en/univarCat', 'univarCat5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat5');
addPage_2('en/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat7');

addChapter('bk/massey120', 'ch_sumStats', "Summary Statistics", null, 'v_ch_sumStats');
addSection('bk/massey120', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7', 'en/boxPlot', 'v_boxPlot7');
addSection('bk/massey120', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addPage_2('bk/massey120', 'counts4', "Mean and st devn for discrete data", 'static', 'en/counts', 's_counts4', 'bk/massey120', 'v_counts4');

addChapter('bk/massey120', 'ch_bivar', "Bivariate Relationships", null, 'v_ch_bivar');
addSection('bk/general', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot1', "More than one variable", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2', 'en/scatterplot', 'v_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5', 'en/scatterplot', 'v_scatterplot5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'en/relationship', 'v_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4', 'en/relationship', 'v_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship5');
addSection('bk/massey120', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation1', 'en/correlation', 'v_correlation1');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3', 'en/correlation', 'v_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4', 'en/correlation', 'v_correlation4');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6', 'en/correlation', 'v_correlation6');
addSection('bk/massey120', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1', 'en/leastSqrs', 'v_leastSqrs1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2', 'en/leastSqrs', 'v_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5', 'en/leastSqrs', 'v_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6', 'en/leastSqrs', 'v_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y & predicting X#?# (opt)", 'interact', 'en/leastSqrs', 's_leastSqrs7', 'en/leastSqrs', 'v_leastSqrs7');
addSection('bk/massey120', 'sec_rSquared', "Coefficient of determination");
addPage_2('bk/massey120', 'rSquared1', "Sums of squares", 'interact', 'bk/massey120', 's_rSquared1', 'bk/massey120', 'v_rSquared1');
addPage_2('bk/massey120', 'rSquared2', "Coefficient of determination", 'interact', 'bk/massey120', 's_rSquared2', 'bk/massey120', 'v_rSquared2');
addSection('bk/massey120', 'sec_continTable', "Contingency tables");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1', 'en/groupedCat', 'v_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat2', 'en/groupedCat', 'v_groupedCat2');
addPage_2('bk/massey120', 'continTable3', "Proportions within groups", 'interact', 'en/groupedCat', 's_groupedCat3', 'bk/massey120', 'v_continTable3');
addPage_2('bk/massey120', 'bivarCat1', "Categorical variables and groups", 'static', 'bk/massey120', 's_bivarCat1', 'bk/massey120', 'v_bivarCat1');
addPage_2('en/bivarCat', 'bivarCat4', "Marginal distributions", 'interact', 'en/bivarCat', 's_bivarCat4', 'en/bivarCat', 'v_bivarCat4');
addPage_2('en/bivarCat', 'bivarCat5', "Conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat5', 'en/bivarCat', 'v_bivarCat5');
addPage_2('en/bivarCat', 'bivarCat7', "Conditional vs marginal distns#?# (opt)", 'interact', 'en/bivarCat', 's_bivarCat7', 'en/bivarCat', 'v_bivarCat7');

addChapter('bk/massey120', 'ch_timeSeries', "Time Series", null, 'v_ch_timeSeries');
addSection('bk/general', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1', 'en/timePlot', 'v_timePlot1');
addPage_2('en/timePlot', 'timePlot2', "Patterns in time series", 'interact', 'en/timePlot', 's_timePlot2', 'en/timePlot', 'v_timePlot2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3', 'en/timePlot', 'v_timePlot3');
addSection('bk/massey120', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1', 'en/smoothing', 'v_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2', 'en/smoothing', 'v_smoothing2');
addPage_2('en/smoothing', 'smoothing3', "Robust smoothing", 'interact', 'en/smoothing', 's_smoothing3', 'en/smoothing', 'v_smoothing3');
addPage_2('en/smoothing', 'smoothing4', "Exponential smoothing", 'interact', 'en/smoothing', 's_smoothing4', 'en/smoothing', 'v_smoothing4');
addSection('bk/general', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'trend1', "Linear trend", 'interact', 'en/trend', 's_trend1', 'en/trend', 'v_trend1');
addPage_2('en/trend', 'trend2', "Quadratic trend", 'interact', 'en/trend', 's_trend2', 'en/trend', 'v_trend2');
addPage_2('en/trend', 'trend3', "Forecasting", 'interact', 'en/trend', 's_trend3', 'en/trend', 'v_trend3');
addPage_2('en/trend', 'trend4', "Polynomial trend", 'interact', 'en/trend', 's_trend4', 'en/trend', 'v_trend4');
addPage_2('en/trend', 'trend5', "Detrending a time series", 'interact', 'en/trend', 's_trend5', 'en/trend', 'v_trend5');

addChapter('bk/massey120', 'ch_sample', "Sampling and Probability", null, 'v_ch_sample');
addSection('bk/massey120', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp2');
addPage_2('en/popSamp', 'popSamp3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp3');
addPage_2('en/popSamp', 'popSamp4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4', 'en/popSamp', 'v_popSamp4');
addPage_2('en/popSamp', 'popSamp5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5', 'en/popSamp', 'v_popSamp5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addSection('bk/massey120', 'sec_infPopn', "Sampling from a distribution");
addPage_2('en/infPopn', 'infPopn1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn1', 'en/infPopn', 'v_infPopn1');
addPage_2('en/infPopn', 'infPopn2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2', 'en/infPopn', 'v_infPopn2');
addPage_2('en/infPopn', 'infPopn3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3', 'en/infPopn', 'v_infPopn3');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5', 'en/infPopn', 'v_infPopn5');
addSection('bk/massey120', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1', 'en/probDensity', 'v_probDensity1');
addPage_2('en/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2', 'en/probDensity', 'v_probDensity2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3', 'en/probDensity', 'v_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4', 'en/probDensity', 'v_probDensity4');
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5', 'en/probDensity', 'v_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6', 'en/probDensity', 'v_probDensity6');
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7', 'en/probDensity', 'v_probDensity7');
addSection('bk/massey120', 'sec_probTable', "Probabilities from tables");
addPage_2('en/prob', 'prob1', "Joint probabilities", 'interact', 'en/prob', 's_prob1', 'en/prob', 'v_prob1');
addPage_2('en/prob', 'prob2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2', 'en/prob', 'v_prob2');
addPage_2('en/prob', 'prob3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3', 'en/prob', 'v_prob3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4', 'en/prob', 'v_prob4');
addPage_2('en/indep', 'indep1', "Association", 'static', 'en/indep', 's_indep1', 'en/indep', 'v_indep1');
addPage_2('en/indep', 'indep2', "Independence", 'static', 'en/indep', 's_indep2', 'en/indep', 'v_indep2');
addSection('bk/massey120', 'sec_probSim', "Simulation (optional)");
addPage_2('en/probSim', 'probSim1', "Probability models and simulation", 'interact', 'en/probSim', 's_probSim1', 'en/probSim', 'v_probSim1');
addPage_2('en/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact', 'en/probSim', 's_probSim2', 'en/probSim', 'v_probSim2');
addPage_2('en/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact', 'en/probSim', 's_probSim3', 'en/probSim', 'v_probSim3');
addPage_2('en/probSim', 'probSim4', "Assessing unusual features in data", 'interact', 'en/probSim', 's_probSim4', 'en/probSim', 'v_probSim4');
addPage_2('en/probSim', 'probSim5', "Random numbers", 'interact', 'en/probSim', 's_probSim5', 'en/probSim', 'v_probSim5');
addPage_2('en/probSim', 'probSim6', "Generating categorical values", 'interact', 'en/probSim', 's_probSim6', 'en/probSim', 'v_probSim6');

addChapter('bk/massey120', 'ch_basicCollection', "Basic Data Collection", null, 'v_ch_basicCollection');
addSection('bk/general', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal1', "Interest in relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2', 'en/causal', 'v_causal2');
addPage_2('en/causal', 'causal3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3', 'en/causal', 'v_causal3');
addPage_2('en/causal', 'causal4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4', 'en/causal', 'v_causal4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5', 'en/causal', 'v_causal5');
addSection('bk/massey120', 'sec_sampPractice', "Sampling in practice");
addPage_2('bk/massey120', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'bk/massey120', 's_sampPractice4', 'en/sampPractice', 'v_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5', 'en/sampPractice', 'v_sampPractice5');
addPage_2('en/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6', 'en/sampPractice', 'v_sampPractice6');
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7', 'en/sampPractice', 'v_sampPractice7');
addSection('bk/massey120', 'sec_designIntro', "Simple experiments");
addPage_2('en/designIntro', 'designIntro1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1', 'en/designIntro', 'v_designIntro1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2', 'en/designIntro', 'v_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3', 'en/designIntro', 'v_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4', 'en/designIntro', 'v_designIntro4');
addPage_2('en/designIntro', 'designIntro5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5', 'en/designIntro', 'v_designIntro5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6', 'en/designIntro', 'v_designIntro6');
addSection('bk/general', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1', 'en/designPrelim', 'v_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2', 'en/designPrelim', 'v_designPrelim2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3', 'en/designPrelim', 'v_designPrelim3');

addChapter('bk/massey120', 'ch_meanPropnDistn', "Sample Means and Propns", null, 'v_ch_meanPropnDistn');
addSection('bk/massey120', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/randomMean', 'randomMean6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean6', 'en/randomMean', 'v_randomMean6');
addPage_2('en/randomMean', 'randomMean7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7', 'en/randomMean', 'v_randomMean7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite popns#?# (opt)", 'interact', 'en/randomMean', 's_randomMean8', 'en/randomMean', 'v_randomMean8');
addSection('bk/massey120', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1', 'en/normalDistn', 'v_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addPage_2('bk/massey120', 'correlation2', "Z-scores for data sets", 'interact', 'en/correlation', 's_correlation2', 'bk/massey120', 'v_correlation2');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5', 'en/normalDistn', 'v_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6', 'en/normalDistn', 'v_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7', 'en/normalDistn', 'v_normalDistn7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8', 'en/normalDistn', 'v_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9', 'en/normalDistn', 'v_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots#?# (opt)", 'interact', 'en/normalDistn', 's_normalDistn10', 'en/normalDistn', 'v_normalDistn10');
addSection('bk/general', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1', 'en/randomPropn', 'v_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn3');
addPage_2('en/randomPropn', 'randomPropn4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn4', 'en/randomPropn', 'v_randomPropn4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'en/randomPropn', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn6', 'en/randomPropn', 'v_randomPropn6');

addChapter('bk/massey120', 'ch_masteryTests', "Mastery Tests");
addSection('bk/massey120', 'sec_masteryOne', "Exercises for test 1");
addPage_2('bk/massey120', 'e_density1', "Draw a histogram", 'static');
addPage_2('bk/massey120', 'e_density2', "Estimate proportion from histogram", 'static');
addPage_2('en/displayInterp', 'e_displayInterp1', "Interpret shape of stacked dot plot", 'static');
addPage_2('en/centerSpread', 'e_centerSpread1', "Concepts of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread2', "Guess mean and median", 'static');
addPage_2('bk/massey120', 'e_centerSpread3', "Guess SD from histogram", 'static');
addPage_2('en/centerSpread', 'e_centerSpread4', "Guess SD from general knowledge", 'static');
addPage_2('en/freqTable', 'e_freqTable1', "Identify numerical and categorical variables", 'static');
addPage_2('en/univarCat', 'e_univarCat6', "Find percentage from a pie chart", 'static');
addPage_2('en/univarCat', 'e_univarCat5', "Match pie charts and bar charts", 'static');
addSection('bk/massey120', 'sec_masteryTwo', "Exercises for test 2");
addPage_2('bk/massey120', 'e_scatterplot2', "Interpret scatterplot", 'static');
addPage_2('en/correlation', 'e_correlation1', "Guess correlation", 'static');
addPage_2('bk/massey120', 'e_leastSqrs3', "Find equation of line", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs5', "Find a residual", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs4', "Interpret slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs7', "Make prediction from LS line", 'static');
addPage_2('bk/massey120', 'e_curvature1', "Identify problems with LS line", 'static');
addPage_2('en/timePlot', 'e_timePlot1', "Identify patterns in a time series", 'static');
addPage_2('en/smoothing', 'e_smoothing1', "Find smoothed time series values", 'static');
addPage_2('en/groupedCat', 'e_groupedCat2', "Find proportion from contingency table", 'static');
addSection('bk/massey120', 'sec_masteryThree', "Exercises for test 3");
addPage_2('en/popSamp', 'e_popSamp2', "Identify parameters and estimates", 'static');
addPage_2('en/probSim', 'e_probSim1', "Find probability about cards or dice", 'static');
addPage_2('en/probSim', 'e_probSim5', "Probability when sampling with/without replacement", 'static');
addPage_2('en/randomPropn', 'e_randomPropn1', "Identify binomial variables", 'static');
addPage_2('en/randomPropn', 'e_randomPropn3', "Find binomial prob from a barchart", 'static');
addPage_2('en/randomPropn', 'e_randomPropn5', "Find binomial prob using normal approx", 'static');
addPage_2('en/probSim', 'e_probSim4', "Find probability for non-normal pdf", 'static');
addPage_2('bk/massey120', 'e_normalDistn1', "Guess SD from normal pdf", 'static');
addPage_2('bk/massey120', 'e_normalDistn3', "Find normal probability using z-score", 'static');
addPage_2('bk/massey120', 'e_normalDistn5', "Find a normal quantile", 'static');

addPart("Part B: New Material");

addChapter('bk/massey120', 'ch_moreGraphics', "More Exploratory Graphics", null, 'v_ch_moreGraphics');
addSection('bk/massey120', 'sec_moreGraphs', "Improved simple graphs");
addPage_2('en/valueDisplay', 'valueDisplay6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6', 'en/valueDisplay', 'v_valueDisplay6');
addPage_2('bk/massey120', 'density7', "Histograms with varying class widths", 'interact', 'bk/massey120', 's_density7', 'bk/massey120', 'v_density7');
addPage_2('bk/massey120', 'density8', "Histogram areas and proportions", 'interact', 'bk/massey120', 's_density8', 'bk/massey120', 'v_density8');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2', 'en/univarCat', 'v_univarCat2');
addSection('bk/massey120', 'sec_transform', "Transformations");
addPage_2('en/transform', 'transform1', "Linear transformations", 'interact', 'en/transform', 's_transform1', 'en/transform', 'v_transform1');
addPage_2('en/transform', 'transform2', "Log transformations", 'interact', 'en/transform', 's_transform2', 'en/transform', 'v_transform2');
addPage_2('en/transform', 'transform3', "When to use log transform?", 'interact', 'en/transform', 's_transform3', 'en/transform', 'v_transform3');
addPage_2('en/transform', 'transform4', "Power transformations", 'interact', 'en/transform', 's_transform4', 'en/transform', 'v_transform4');
addPage_2('en/transform', 'transform5', "Power transforms &amp; skewness#?# (opt)", 'interact', 'en/transform', 's_transform5', 'en/transform', 'v_transform5');
addSection('bk/massey120', 'sec_nonlinear', "Nonlinear relationships");
addPage_2('bk/massey120', 'correlation5', "Correlation and nonlinear relationships", 'interact', 'en/correlation', 's_correlation5', 'bk/massey120', 'v_correlation5');
addPage_2('en/curvature', 'curvature1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1', 'en/curvature', 'v_curvature1');
addPage_2('en/curvature', 'curvature2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2', 'en/curvature', 'v_curvature2');
addPage_2('en/curvature', 'curvature3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3', 'en/curvature', 'v_curvature3');
addPage_2('en/curvature', 'curvature4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4', 'en/curvature', 'v_curvature4');
addPage_2('bk/massey120', 'smoothing6', "Lowess smoothing of scatterplots#?# (opt)", 'interact', 'en/smoothing', 's_smoothing6', 'bk/massey120', 'v_smoothing6');
addSection('bk/general', 'sec_multivariate', "Displaying multivariate data");
addPage_2('en/multivariate', 'multivariate1', "Representing a third variable", 'interact', 'en/multivariate', 's_multivariate1', 'en/multivariate', 'v_multivariate1');
addPage_2('en/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact', 'en/multivariate', 's_multivariate2', 'en/multivariate', 'v_multivariate2');
addPage_2('en/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact', 'en/multivariate', 's_multivariate3', 'en/multivariate', 'v_multivariate3');
addPage_2('en/multivariate', 'multivariate4', "Brushing example", 'interact', 'en/multivariate', 's_multivariate4', 'en/multivariate', 'v_multivariate4');
addPage_2('en/multivariate', 'multivariate5', "Slicing", 'interact', 'en/multivariate', 's_multivariate5', 'en/multivariate', 'v_multivariate5');
addSection('bk/massey120', 'sec_moreGraphicsExercises', "Exercises");
addPage_2('bk/massey120', 'e_valueDisplay1', "Stem and leaf plots with split stems", 'static');
addPage_2('bk/massey120', 'e_boxPlot1', "Box plots with outliers", 'static');
addPage_2('bk/massey120', 'e_density1b', "Histograms with mixed class widths", 'static');
addPage_2('en/univarCat', 'e_univarCat3', "Pareto diagrams", 'static');
addPage_2('en/transform', 'e_transform1', "Linear transformations", 'static');
addPage_2('en/transform', 'e_transform2', "Mean and st devn after linear transformations", 'static');
addPage_2('en/transform', 'e_transform3', "Nonlinear transformations", 'static');
addPage_2('en/curvature', 'e_curvature2', "Transformations for regression", 'static');
addPage_2('en/curvature', 'e_curvature3', "Prediction from nonlinear model", 'static');
addPage_2('en/curvature', 'e_curvature4', "Power transformations (advanced)", 'static');

addChapter('bk/massey120', 'ch_dataPresentation', "Data Presentation", null, 'v_ch_dataPresentation');
addSection('bk/massey120', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay0', "Overview", 'static', 'en/tableDisplay', 's_tableDisplay0');
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2', 'en/tableDisplay', 'v_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4', 'en/tableDisplay', 'v_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5', 'en/tableDisplay', 'v_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6', 'en/tableDisplay', 'v_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7', 'en/tableDisplay', 'v_tableDisplay7');
addSection('bk/massey120', 'sec_barPieDisplay', "Presenting bar and pie charts");
addPage_2('en/simpleBar', 'simpleBar1', "Bar charts", 'interact', 'en/simpleBar', 's_simpleBar1');
addPage_2('bk/massey120', 'simpleBar2', "Ordering of categories", 'interact', 'bk/massey120', 's_simpleBar2');
addPage_2('en/simpleBar', 'simpleBar3', "Importance of zero and -ve values", 'interact', 'en/simpleBar', 's_simpleBar3');
addPage_2('en/simpleBar', 'simpleBar4', "Chartjunk", 'static', 'en/simpleBar', 's_simpleBar4');
addPage_2('en/simpleBar', 'simpleBar5', "Misleading bar charts", 'static', 'en/simpleBar', 's_simpleBar5');
addPage_2('en/simplePie', 'simplePie3', "Chartjunk for pie charts", 'interact', 'en/univarCat', 's_univarCat6');
addPage_2('en/simplePie', 'simplePie4', "Misleading stacked bar charts", 'static', 'en/simplePie', 's_simplePie4');
addSection('bk/massey120', 'sec_groupGraph', "Bar charts to compare groups");
addPage_2('bk/massey120', 'groupGraph1', "Bar charts of frequencies and proportions", 'interact', 'bk/massey120', 's_groupGraph1');
addPage_2('en/groupGraph', 'groupGraph3', "Clustered bar charts", 'interact', 'en/bivarCat', 's_bivarCat3');
addPage_2('en/groupGraph', 'groupGraph4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4');
addPage_2('en/groupGraph', 'groupGraph5', "Two categories", 'interact', 'en/groupGraph', 's_groupGraph5');
addPage_2('en/groupGraph', 'groupGraph6', "Chartjunk", 'interact', 'en/bivarCat', 's_bivarCat2');
addSection('bk/massey120', 'sec_otherGraphs', "Other ways to present data");
addPage_2('en/scatterGraph', 'scatterGraph3', "Distinguishing groups#?# (opt)", 'interact', 'en/scatterGraph', 's_scatterGraph3');
addPage_2('en/scatterGraph', 'scatterGraph4', "Showing size#?# (opt)", 'interact', 'en/scatterGraph', 's_scatterGraph4');
addPage_2('en/timeGraph', 'timeGraph7', "Dynamic scatterplots#?# (opt)", 'interact', 'en/timeGraph', 's_timeGraph7');
addPage_2('en/maps', 'maps4', "Maps with pie and bar charts#?# (opt)", 'interact', 'en/maps', 's_maps4');
addPage_2('en/maps', 'maps5', "Distorted population maps#?# (opt)", 'interact', 'en/maps', 's_maps5');
addPage_2('en/maps', 'maps6', "Other distorted maps#?# (opt)", 'static', 'en/maps', 's_maps6');
addSection('bk/massey120', 'sec_graphs', "Data presentation principles");
addPage_2('en/graphs', 'graphs0', "Overview", 'static', 'en/graphs', 's_graphs0');
addPage_2('en/graphs', 'graphs1', "Types of publication", 'static', 'en/graphs', 's_graphs1');
addPage_2('en/graphs', 'graphs2', "From data to information", 'interact', 'en/graphs', 's_graphs2');
addPage_2('en/graphs', 'graphs3', "Tables, graphs and text", 'static', 'en/graphs', 's_graphs3');
addPage_2('en/graphs', 'graphs4', "Combining simple graphs#?# (opt)", 'static', 'en/graphs', 's_graphs4');
addPage_2('en/graphs', 'graphs5', "Advanced graphs#?# (opt)", 'interact', 'en/graphs', 's_graphs5');
addPage_2('en/graphs', 'graphs6', "Innovative graphics#?# (opt)", 'static', 'en/graphs', 's_graphs6');

addChapter('bk/massey120', 'ch_moreCollection', "More Data Collection", null, 'v_ch_moreCollection');
addSection('bk/massey120', 'sec_lurking', "Lurking variables");
addPage_2('en/lurking', 'lurking1', "Misleading marginal correlation", 'interact', 'en/lurking', 's_lurking1', 'en/lurking', 'v_lurking1');
addPage_2('en/lurking', 'lurking2', "Misleading marginal difference in means", 'interact', 'en/lurking', 's_lurking2', 'en/lurking', 'v_lurking2');
addPage_2('en/lurking', 'lurking3', "Simpsons paradox", 'interact', 'en/lurking', 's_lurking3', 'en/lurking', 'v_lurking3');
addPage_2('en/lurking', 'lurking4', "Other examples with lurking variables", 'static', 'en/lurking', 's_lurking4', 'en/lurking', 'v_lurking4');
addSection('bk/massey120', 'sec_samplingSchemes', "Different sampling schemes");
addPage_2('en/sampPractice', 'sampPractice1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1', 'en/sampPractice', 'v_sampPractice1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2', 'en/sampPractice', 'v_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3', 'en/sampPractice', 'v_sampPractice3');
addSection('bk/massey120', 'sec_blocks', "Experiments with blocks");
addPage_2('en/blockIntro', 'blockIntro1', "Variability of experimental units", 'interact', 'en/blockIntro', 's_blockIntro1', 'en/blockIntro', 'v_blockIntro1');
addPage_2('en/blockIntro', 'blockIntro2', "Blocks of similar experimental units", 'static', 'en/blockIntro', 's_blockIntro2', 'en/blockIntro', 'v_blockIntro2');
addPage_2('bk/massey120', 'oneBlock1', "Randomised block design", 'interact', 'en/oneBlock', 's_oneBlock1', 'en/oneBlock', 'v_oneBlock1');
addPage_2('en/oneBlock', 'oneBlock2', "Randomised block examples", 'static', 'en/oneBlock', 's_oneBlock2', 'en/oneBlock', 'v_oneBlock2');
addPage_2('en/oneBlock', 'oneBlock3', "Comparison of designs", 'interact', 'en/oneBlock', 's_oneBlock3', 'en/oneBlock', 'v_oneBlock3');

addChapter('bk/massey120', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/massey120', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro1', 'en/estIntro', 'v_estIntro1');
addPage_2('en/estIntro', 'estIntro2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2', 'en/estIntro', 'v_estIntro2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation#?# (opt)", 'static', 'en/estIntro', 's_estIntro3', 'en/estIntro', 'v_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4', 'en/estIntro', 'v_estIntro4');
addPage_2('en/estIntro', 'estIntro5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5', 'en/estIntro', 'v_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6', 'en/estIntro', 'v_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7', 'en/estIntro', 'v_estIntro7');
addSection('bk/massey120', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1', 'en/seMean', 'v_seMean1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2', 'en/seMean', 'v_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3', 'en/seMean', 'v_seMean3');
addPage_2('en/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean4', 'en/seMean', 'v_seMean4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addPage_2('en/seMean', 'seMean6', "Usng SEs to compare estimators#?# (opt)", 'interact', 'en/seMean', 's_seMean6', 'en/seMean', 'v_seMean6');
addPage_2('en/seMean', 'seMean7', "More about bias#?# (opt)", 'interact', 'en/seMean', 's_seMean7', 'en/seMean', 'v_seMean7');
addSection('bk/general', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean1');
addPage_2('en/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2', 'en/ciMean', 'v_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3', 'en/ciMean', 'v_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4', 'en/ciMean', 'v_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5', 'en/ciMean', 'v_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6', 'en/ciMean', 'v_ciMean6');
addPage_2('en/ciMean', 'ciMean7', "Examples", 'static', 'en/ciMean', 's_ciMean7', 'en/ciMean', 'v_ciMean7');
addSection('bk/general', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('en/estPropn', 'estPropn3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn3');
addPage_2('en/estPropn', 'estPropn4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4', 'en/estPropn', 'v_estPropn4');
addPage_2('en/estPropn', 'estPropn5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5', 'en/estPropn', 'v_estPropn5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('en/estPropn', 'estPropn7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7', 'en/estPropn', 'v_estPropn7');
addSection('bk/general', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'ciExtra1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1', 'en/ciExtra', 'v_ciExtra1');
addPage_2('en/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2', 'en/ciExtra', 'v_ciExtra2');
addPage_2('en/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3', 'en/ciExtra', 'v_ciExtra3');
addPage_2('en/ciExtra', 'ciExtra4', "Other confidence levels", 'interact', 'en/ciExtra', 's_ciExtra4', 'en/ciExtra', 'v_ciExtra4');
addSection('bk/massey120', 'sec_estimationExercises', "Exercises");
addPage_2('en/seMean', 'e_seMean1', "Standard error of mean", 'static');
addPage_2('en/seMean', 'e_seMean2', "Standard error vs standard deviation", 'static');
addPage_2('en/seMean', 'e_seMean3', "Factors affecting the standard deviation and standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean1', "Confidence interval from standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean2', "Find 95% CI for mean, known sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean3', "Find 95% CI for mean, unknown sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean6', "Factors affecting width of CI", 'static');
addPage_2('en/ciMean', 'e_ciMean7', "Interpreting a 95% confidence interval", 'static');
addPage_2('en/estPropn', 'e_estPropn1', "Standard error of proportion", 'static');
addPage_2('en/estPropn', 'e_estPropn2', "95% confidence interval for probability", 'static');
addPage_2('en/estPropn', 'e_estPropn4', "Factors affecting width of confidence interval", 'static');
addPage_2('en/estPropn', 'e_estPropn5', "Interpreting a 95% confidence interval", 'static');
addPage_2('en/ciMean', 'e_ciMean4', "CIs for mean at other confidence levels, known sigma", 'static');
addPage_2('en/ciMean', 'e_ciMean5', "Mixture of levels, known &amp; unknown \u03c3", 'static');
addPage_2('en/estPropn', 'e_estPropn3', "CIs for proportions, various confidence levels", 'static');

addChapter('bk/massey120', 'ch_testing', "Testing Hypotheses", null, 'v_ch_testing');
addSection('bk/massey120', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro1', "Inference", 'static', 'en/testIntro', 's_testIntro1', 'en/testIntro', 'v_testIntro1');
addPage_2('en/testIntro', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2', 'en/testIntro', 'v_testIntro2');
addPage_2('en/testIntro', 'testIntro3', "Simulation to test a proportion", 'interact', 'en/testIntro', 's_testIntro3', 'en/testIntro', 'v_testIntro3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4', 'en/testIntro', 'v_testIntro4');
addPage_2('en/testIntro', 'testIntro5', "Randomisation tests#?# (opt)", 'interact', 'en/testIntro', 's_testIntro5', 'en/testIntro', 'v_testIntro5');
addPage_2('en/testIntro', 'testIntro6', "Soccer league randomisation#?# (opt)", 'interact', 'en/testIntro', 's_testIntro6', 'en/testIntro', 'v_testIntro6');
addPage_2('en/testIntro', 'testIntro7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7', 'en/testIntro', 'v_testIntro7');
addSection('bk/general', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'testPropn1', "Inference about parameters", 'static', 'en/testPropn', 's_testPropn1', 'en/testPropn', 'v_testPropn1');
addPage_2('en/testPropn', 'testPropn2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2', 'en/testPropn', 'v_testPropn2');
addPage_2('en/testPropn', 'testPropn3', "Another example", 'interact', 'en/testPropn', 's_testPropn3', 'en/testPropn', 'v_testPropn3');
addPage_2('en/testPropn', 'testPropn4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn4', 'en/testPropn', 'v_testPropn4');
addPage_2('en/testPropn', 'testPropn5', "Normal approximation", 'interact', 'en/testPropn', 's_testPropn5', 'en/testPropn', 'v_testPropn5');
addPage_2('en/testPropn', 'testPropn6', "Statistical distance", 'static', 'en/testPropn', 's_testPropn6', 'en/testPropn', 'v_testPropn6');
addPage_2('en/testPropn', 'testPropn7', "Tests based on statistical distance", 'interact', 'en/testPropn', 's_testPropn7', 'en/testPropn', 'v_testPropn7');
addSection('bk/general', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean1', "Introduction", 'static', 'en/testMean', 's_testMean1', 'en/testMean', 'v_testMean1');
addPage_2('en/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2', 'en/testMean', 'v_testMean2');
addPage_2('en/testMean', 'testMean3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3', 'en/testMean', 'v_testMean3');
addPage_2('en/testMean', 'testMean4', "The t distribution", 'interact', 'en/testMean', 's_testMean4', 'en/testMean', 'v_testMean4');
addPage_2('en/testMean', 'testMean5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5', 'en/testMean', 'v_testMean5');
addSection('bk/massey120', 'sec_decision', "Decisions and significance");
addPage_2('en/decision', 'decision1', "Hypothesis tests and decisions", 'static', 'en/decision', 's_decision1', 'en/decision', 'v_decision1');
addPage_2('en/decision', 'decision2', "Decision rules", 'interact', 'en/decision', 's_decision2', 'en/decision', 'v_decision2');
addPage_2('en/decision', 'decision3', "Significance level and p-values", 'interact', 'en/decision', 's_decision3', 'en/decision', 'v_decision3');
addPage_2('en/decision', 'decision4', "Sample size and power", 'interact', 'en/decision', 's_decision4', 'en/decision', 'v_decision4');
addSection('bk/massey120', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact', 'en/testPValue', 's_testPValue1', 'en/testPValue', 'v_testPValue1');
addPage_2('en/testPValue', 'testPValue2', "Consistency with null hypothesis", 'interact', 'en/testPValue', 's_testPValue2', 'en/testPValue', 'v_testPValue2');
addPage_2('en/testPValue', 'testPValue3', "Distribution of p-values", 'interact', 'en/testPValue', 's_testPValue3', 'en/testPValue', 'v_testPValue3');
addPage_2('en/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact', 'en/testPValue', 's_testPValue4', 'en/testPValue', 'v_testPValue4');
addPage_2('en/testPValue', 'testPValue5', "P-values for other tests#?# (opt)", 'interact', 'en/testPValue', 's_testPValue5', 'en/testPValue', 'v_testPValue5');
addSection('bk/massey120', 'sec_testingExercises', "Exercises");
addPage_2('en/testIntro', 'e_testIntro1', "Simulation to test a proportion", 'static');
addPage_2('en/testIntro', 'e_testIntro2', "Simulation to test a mean", 'static');
addPage_2('en/testPropn', 'e_testPropn1', "Test proportion using binomial distribution", 'static');
addPage_2('en/testPropn', 'e_testPropn2', "Test proportion with normal approximation", 'static');
addPage_2('en/testPropn', 'e_testPropn3', "Test with continuity correction (advanced)", 'static');
addPage_2('en/testMean', 'e_testMean1', "Test mean, assuming known sigma", 'static');
addPage_2('en/testMean', 'e_testMean2', "T test (unknown sigma)", 'static');
addPage_2('en/testPValue', 'e_testPValue1', "Generic interpretation of a p-values", 'static');
addPage_2('en/testPValue', 'e_testPValue2', "Interpretation of p-values (in context)", 'static');
addPage_2('en/testPValue', 'e_testPValue3', "Interpretation of p-values (harder)", 'static');

addChapter('bk/massey120', 'ch_compareMeans', "Comparing Means", null, 'v_ch_compareMeans');
addSection('bk/general', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel1', 'en/twoGroupModel', 'v_twoGroupModel1');
addPage_2('en/twoGroupModel', 'twoGroupModel2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2', 'en/twoGroupModel', 'v_twoGroupModel2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3', 'en/twoGroupModel', 'v_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4', 'en/twoGroupModel', 'v_twoGroupModel4');
addPage_2('en/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel5', 'en/twoGroupModel', 'v_twoGroupModel5');
addSection('bk/massey120', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'sumDiff1', "Means and sums of samples#?# (opt)", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('en/sumDiff', 'sumDiff2', "Sum and difference#?# (opt)", 'interact', 'en/sumDiff', 's_sumDiff2', 'en/sumDiff', 'v_sumDiff2');
addPage_2('en/sumDiff', 'sumDiff3', "Sum and difference (cont)#?# (opt)", 'interact', 'en/sumDiff', 's_sumDiff3', 'en/sumDiff', 'v_sumDiff3');
addPage_2('en/sumDiff', 'sumDiff4', "Probabilities for sums and differences#?# (opt)", 'static', 'en/sumDiff', 's_sumDiff4', 'en/sumDiff', 'v_sumDiff4');
addSection('bk/general', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1', 'en/twoGroupInf', 'v_twoGroupInf1');
addPage_2('en/twoGroupInf', 'twoGroupInf2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf2', 'en/twoGroupInf', 'v_twoGroupInf2');
addPage_2('en/twoGroupInf', 'twoGroupInf3', "CI for difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf3', 'en/twoGroupInf', 'v_twoGroupInf3');
addPage_2('en/twoGroupInf', 'twoGroupInf4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf4', 'en/twoGroupInf', 'v_twoGroupInf4');
addPage_2('en/twoGroupInf', 'twoGroupInf5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf5', 'en/twoGroupInf', 'v_twoGroupInf5');
addSection('bk/general', 'sec_testPaired', "Paired t test");
addPage_2('en/testPaired', 'testPaired1', "Paired data", 'static', 'en/testPaired', 's_testPaired1', 'en/testPaired', 'v_testPaired1');
addPage_2('en/testPaired', 'testPaired2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2', 'en/testPaired', 'v_testPaired2');
addPage_2('en/testPaired', 'testPaired3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3', 'en/testPaired', 'v_testPaired3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4', 'en/testPaired', 'v_testPaired4');
addSection('bk/massey120', 'sec_multiGroup', "Comparing several means");
addPage_2('en/multiGroup', 'multiGroup1', "Model", 'interact', 'en/multiGroup', 's_multiGroup1', 'en/multiGroup', 'v_multiGroup1');
addPage_2('en/multiGroup', 'multiGroup2', "Parameter estimates", 'interact', 'en/multiGroup', 's_multiGroup2', 'en/multiGroup', 'v_multiGroup2');
addPage_2('en/multiGroup', 'multiGroup3', "Inference about two groups#?# (opt)", 'static', 'en/multiGroup', 's_multiGroup3', 'en/multiGroup', 'v_multiGroup3');
addPage_2('en/multiGroup', 'multiGroup4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup6', "Coefficient of determination#?# (opt)", 'static', 'en/multiGroup', 's_multiGroup6', 'en/multiGroup', 'v_multiGroup6');
addPage_2('en/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addPage_2('en/multiGroup', 'multiGroup8', "Examples", 'static', 'en/multiGroup', 's_multiGroup8', 'en/multiGroup', 'v_multiGroup8');
addSection('bk/massey120', 'sec_compareMeansExercises', "Exercises");
addPage_2('en/twoGroupInf', 'e_twoGroupInf1', "Probabilities about differences#?#  (Optional)", 'static');
addPage_2('en/twoGroupInf', 'e_twoGroupInf2', "CI for difference between two means", 'static');
addPage_2('en/twoGroupInf', 'e_twoGroupInf3', "Testing two group means for equality", 'static');
addPage_2('en/testPaired', 'e_testPaired1', "2-sample or paired t-test", 'static');
addPage_2('en/testPaired', 'e_testPaired2', "Conduct paired t-test", 'static');
addPage_2('en/multiGroup', 'e_multiGroup1', "Anova table formulae", 'static');
addPage_2('en/multiGroup', 'e_multiGroup2', "Anova table values", 'static');
addPage_2('en/multiGroup', 'e_multiGroup3', "Conclusion from Anova table", 'static');

addChapter('bk/massey120', 'ch_comparePropns', "Comparing Proportions");
addSection('bk/general', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn1', 'en/twoGroupPropn', 'v_twoGroupPropn1');
addPage_2('en/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn2', 'en/twoGroupPropn', 'v_twoGroupPropn2');
addPage_2('en/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static', 'en/twoGroupPropn', 's_twoGroupPropn3', 'en/twoGroupPropn', 'v_twoGroupPropn3');
addPage_2('en/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static', 'en/twoGroupPropn', 's_twoGroupPropn4', 'en/twoGroupPropn', 'v_twoGroupPropn4');
addSection('bk/massey120', 'sec_indep', "Contingency table association");
addPage_2('en/indep', 'indep3', "Independence from samples", 'static', 'en/indep', 's_indep3', 'en/indep', 'v_indep3');
addPage_2('en/indep', 'indep4', "Testing for independence", 'interact', 'en/indep', 's_indep4', 'en/indep', 'v_indep4');
addPage_2('en/indep', 'indep5', "Chi-squared test statistic", 'interact', 'en/indep', 's_indep5', 'en/indep', 'v_indep5');
addPage_2('en/indep', 'indep6', "P-value for chi-squared test", 'interact', 'en/indep', 's_indep6', 'en/indep', 'v_indep6');
addPage_2('en/indep', 'indep7', "Examples", 'static', 'en/indep', 's_indep7', 'en/indep', 'v_indep7');
addPage_2('en/indep', 'indep8', "Comparing groups", 'static', 'en/indep', 's_indep8', 'en/indep', 'v_indep8');
addSection('bk/massey120', 'sec_comparePropnsExercises', "Exercises");
addPage_2('en/twoGroupPropn', 'e_twoGroupPropn1', "CI for difference between two proportions", 'static');
addPage_2('en/twoGroupPropn', 'e_twoGroupPropn2', "Test about difference between two proportions", 'static');
addPage_2('en/indep', 'e_indep1', "Expected cell counts in contingency tables", 'static');
addPage_2('en/indep', 'e_indep2', "Chi-squared test for independence", 'static');

addChapter('bk/massey120', 'ch_regnInference', "Regression Inference", null, 'v_ch_regnInference');
addSection('bk/general', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel1', 'en/regnModel', 'v_regnModel1');
addPage_2('en/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact', 'en/regnModel', 's_regnModel2', 'en/regnModel', 'v_regnModel2');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3', 'en/regnModel', 'v_regnModel3');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4', 'en/regnModel', 'v_regnModel4');
addPage_2('en/regnModel', 'regnModel5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel5', 'en/regnModel', 'v_regnModel5');
addSection('bk/massey120', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1', 'en/regnEst', 'v_regnEst1');
addPage_2('en/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2', 'en/regnEst', 'v_regnEst2');
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3', 'en/regnEst', 'v_regnEst3');
addPage_2('en/regnEst', 'regnEst4', "Standard error of least squares slope", 'static', 'en/regnEst', 's_regnEst4', 'en/regnEst', 'v_regnEst4');
addPage_2('en/regnEst', 'regnEst5', "95% confidence interval for slope", 'static', 'en/regnEst', 's_regnEst5', 'en/regnEst', 'v_regnEst5');
addPage_2('en/regnEst', 'regnEst6', "Properties of confidence interval", 'interact', 'en/regnEst', 's_regnEst6', 'en/regnEst', 'v_regnEst6');
addPage_2('en/regnEst', 'regnEst7', "Influences on accuracy", 'interact', 'en/regnEst', 's_regnEst7', 'en/regnEst', 'v_regnEst7');
addSection('bk/massey120', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1', 'en/regnTest', 'v_regnTest1');
addPage_2('en/regnTest', 'regnTest2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest2', 'en/regnTest', 'v_regnTest2');
addPage_2('en/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3', 'en/regnTest', 'v_regnTest3');
addPage_2('en/regnTest', 'regnTest4', "Properties of p-values", 'interact', 'en/regnTest', 's_regnTest4', 'en/regnTest', 'v_regnTest4');
addSection('bk/general', 'sec_regnPred', "Predicting the response");
addPage_2('en/regnPred', 'regnPred1', "Estimated response distn at X", 'interact', 'en/regnPred', 's_regnPred1', 'en/regnPred', 'v_regnPred1');
addPage_2('en/regnPred', 'regnPred2', "Variability of estimate at X", 'interact', 'en/regnPred', 's_regnPred2', 'en/regnPred', 'v_regnPred2');
addPage_2('en/regnPred', 'regnPred3', "Estimating the mean vs prediction", 'interact', 'en/regnPred', 's_regnPred3', 'en/regnPred', 'v_regnPred3');
addPage_2('en/regnPred', 'regnPred4', "Confidence and prediction intervals", 'interact', 'en/regnPred', 's_regnPred4', 'en/regnPred', 'v_regnPred4');
addSection('bk/massey120', 'sec_regnExercises', "Exercises");
addPage_2('en/regnModel', 'e_regnModel1', "Normal distribution of response at fixed X", 'static');
addPage_2('en/regnEst', 'e_regnEst1', "Standard error of slope", 'static');
addPage_2('en/regnEst', 'e_regnEst2', "Confidence interval for slope", 'static');
addPage_2('en/regnEst', 'e_regnEst3', "Influences on accuracy", 'static');
addPage_2('en/regnTest', 'e_regnTest1', "Test for zero slope", 'static');

var language = "en";
var logoGif = "logo_massey.gif";
var homeDir = "bk/massey120";
var versionGif = "../general/images/castGeneral";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = "http://castAdmin2.massey.ac.nz/pdf/massey120";
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "18";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_b': 'Biometric', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '++': 'Custom', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_g', '_b', '_c');
versions['variation4'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('+g', '_g', '_a', '_b', '_c', '_m');
versions['valueDisplay7'] = new Array('+g', '_g', '_c', '_m');
versions['displayInterp1'] = new Array('_g', '_b', '_c');
versions['displayInterp2'] = new Array('_g', '_b', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['displayInterp6'] = new Array('_g', '_b', '_c');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density9'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat7'] = new Array('_g', '_b');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts4'] = new Array('+g', '_g', '_b', '_c');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['bivarCat1'] = new Array('+g', '_g', '_b', '_c');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_g', '_b', '_c');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['indep1'] = new Array('_g', '_b', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_g', '_b', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['sampPractice4'] = new Array('+g', '_g');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['designPrelim2'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_g', '_b', '_c');
versions['randomMean6'] = new Array('_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['correlation2'] = new Array('+g', '_g');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');
versions['e_density1'] = new Array('+g', '_g');
versions['e_density2'] = new Array('+g', '_g');
versions['e_centerSpread3'] = new Array('+g', '_g');
versions['e_scatterplot2'] = new Array('+g', '_g');
versions['e_leastSqrs3'] = new Array('+g', '_g');
versions['e_curvature1'] = new Array('+g', '_g');
versions['e_normalDistn1'] = new Array('+g', '_g');
versions['e_normalDistn3'] = new Array('+g', '_g');
versions['e_normalDistn5'] = new Array('+g', '_g');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['density7'] = new Array('+g', '_g', '_b', '_c', '_m');
versions['density8'] = new Array('+g', '_g');
versions['transform1'] = new Array('_g', '_b');
versions['transform2'] = new Array('_g', '_b', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['correlation5'] = new Array('+g', '_g');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['smoothing6'] = new Array('+g', '_g');
versions['multivariate1'] = new Array('_g', '_b', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['e_valueDisplay1'] = new Array('+g', '_g');
versions['e_boxPlot1'] = new Array('+g', '_g');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['simpleBar2'] = new Array('+g', '_g');
versions['simpleBar4'] = new Array('_g', '_b');
versions['groupGraph1'] = new Array('+g', '_g');
versions['lurking1'] = new Array('_g', '_b', '_c');
versions['lurking2'] = new Array('_g', '_b');
versions['lurking3'] = new Array('_g', '_c');
versions['sampPractice1'] = new Array('_g', '_b');
versions['oneBlock1'] = new Array('+g', '_g');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro3'] = new Array('_g', '_b', '_c');
versions['testIntro5'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_g', '_b', '_c');
versions['testPropn1'] = new Array('_g', '_b', '_c');
versions['testPropn2'] = new Array('_g', '_b', '_c');
versions['testPropn3'] = new Array('_g', '_b', '_c');
versions['testPropn4'] = new Array('_g', '_b', '_c');
versions['testPropn5'] = new Array('_g', '_b');
versions['testPropn7'] = new Array('_g', '_b');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean2'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_g', '_b');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_g', '_b', '_c');
versions['testPValue5'] = new Array('_g', '_b', '_c');
versions['twoGroupModel1'] = new Array('_g', '_b', '_c');
versions['twoGroupModel2'] = new Array('_g', '_b', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['twoGroupInf3'] = new Array('_g', '_b', '_c');
versions['twoGroupInf4'] = new Array('_g', '_b', '_c');
versions['twoGroupInf5'] = new Array('_g', '_b', '_c');
versions['testPaired1'] = new Array('_g', '_b', '_c');
versions['testPaired2'] = new Array('_g', '_b', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_g', '_b', '_c');
versions['multiGroup3'] = new Array('_g', '_b', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_g', '_a', '_b', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_g', '_b', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');
versions['e_twoGroupPropn1'] = new Array('_g', '_b', '_c');
versions['e_twoGroupPropn2'] = new Array('_g', '_b', '_c');
versions['regnModel1'] = new Array('_g', '_b', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_g', '_b', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_g', '_b', '_c');
versions['regnPred3'] = new Array('_g', '_b', '_c');
versions['regnPred4'] = new Array('_g', '_b');

bookLoaded = true;
