
addBook('bk/official', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/official', 'ch_dataPresent', "Tables, graphs and maps");
addSection('bk/official', 'sec_simpleTable', "Simple tables");
addPage_2('en/simpleTable', 'simpleTable0', "Overview", 'static');
addPage_2('en/simpleTable', 'simpleTable1', "Frequency tables", 'interact');
addPage_2('en/simpleTable', 'simpleTable2', "Tables for other partitions", 'static');
addPage_2('en/simpleTable', 'simpleTable3', "Proportions and percentages", 'interact');
addPage_2('en/simpleTable', 'simpleTable4', "Other simple tables", 'static');
addPage_2('en/simpleTable', 'simpleTable5', "Variations", 'interact');
addPage_2('en/simpleTable', 'simpleTable6', "Tables within tables", 'static');
addSection('bk/official', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay0', "Overview", 'static');
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static');
addSection('bk/official', 'sec_simpleBar', "Bar charts");
addPage_2('en/simpleBar', 'simpleBar0', "Overview", 'static');
addPage_2('en/simpleBar', 'simpleBar1', "Bar charts", 'interact');
addPage_2('en/simpleBar', 'simpleBar2', "Ordering of categories", 'interact');
addPage_2('en/simpleBar', 'simpleBar3', "Importance of zero and -ve values", 'interact');
addPage_2('en/simpleBar', 'simpleBar4', "Chartjunk", 'interact');
addPage_2('en/simpleBar', 'simpleBar5', "Misleading bar charts", 'static');
addPage_2('en/simpleBar', 'simpleBar6', "Histograms", 'interact');
addSection('bk/official', 'sec_simplePie', "Pie charts");
addPage_2('en/simplePie', 'simplePie0', "Overview", 'static');
addPage_2('en/simplePie', 'simplePie1', "Stacked bar charts and pie charts", 'interact');
addPage_2('en/simplePie', 'simplePie2', "Comparison of bar and pie charts", 'interact');
addPage_2('en/simplePie', 'simplePie3', "Chartjunk for pie charts", 'interact');
addPage_2('en/simplePie', 'simplePie4', "Misleading stacked bar charts", 'static');
addPage_2('en/simplePie', 'simplePie5', "Colour", 'interact');
addSection('bk/official', 'sec_groupGraph', "Comparing groups");
addPage_2('en/groupGraph', 'groupGraph0', "Overview", 'static');
addPage_2('en/groupGraph', 'groupGraph1', "Two-way tables", 'interact');
addPage_2('en/groupGraph', 'groupGraph2', "Proportions within groups", 'interact');
addPage_2('en/groupGraph', 'groupGraph3', "Clustered bar charts", 'interact');
addPage_2('en/groupGraph', 'groupGraph4', "Stacked bar charts", 'interact');
addPage_2('en/groupGraph', 'groupGraph5', "Two categories", 'interact');
addPage_2('en/groupGraph', 'groupGraph6', "Chartjunk", 'interact');
addSection('bk/official', 'sec_scatterGraph', "Relationships between measurements");
addPage_2('en/scatterGraph', 'scatterGraph0', "Overview", 'static');
addPage_2('en/scatterGraph', 'scatterGraph1', "Scatterplots", 'interact');
addPage_2('en/scatterGraph', 'scatterGraph2', "Information from scatterplots", 'interact');
addPage_2('en/scatterGraph', 'scatterGraph3', "Distinguishing groups", 'interact');
addPage_2('en/scatterGraph', 'scatterGraph4', "Showing size", 'interact');
addPage_2('en/scatterGraph', 'scatterGraph5', "Nonlinear scales", 'interact');
addSection('bk/official', 'sec_maps', "Maps");
addPage_2('en/maps', 'maps0', "Overview", 'static');
addPage_2('en/maps', 'maps1', "Colouring regions", 'interact');
addPage_2('en/maps', 'maps2', "Choice of colours", 'interact');
addPage_2('en/maps', 'maps3', "Adding information with circles", 'interact');
addPage_2('en/maps', 'maps4', "Maps with pie and bar charts", 'interact');
addPage_2('en/maps', 'maps5', "Distorted population maps", 'interact');
addPage_2('en/maps', 'maps6', "Other distorted maps", 'static');
addSection('bk/official', 'sec_timeGraph', "Changes over time");
addPage_2('en/timeGraph', 'timeGraph0', "Overview", 'static');
addPage_2('en/timeGraph', 'timeGraph1', "Time series charts", 'interact');
addPage_2('en/timeGraph', 'timeGraph2', "Time series for quantities", 'interact');
addPage_2('en/timeGraph', 'timeGraph3', "Time series with categories", 'interact');
addPage_2('en/timeGraph', 'timeGraph4', "Chartjunk", 'interact');
addPage_2('en/timeGraph', 'timeGraph5', "Dynamic pie and bar charts", 'interact');
addPage_2('en/timeGraph', 'timeGraph6', "Dynamic histograms", 'interact');
addPage_2('en/timeGraph', 'timeGraph7', "Dynamic scatterplots", 'interact');
addPage_2('en/timeGraph', 'timeGraph8', "Dynamic maps", 'interact');
addSection('bk/official', 'sec_graphs', "Data presentation principles");
addPage_2('en/graphs', 'graphs0', "Overview", 'static');
addPage_2('en/graphs', 'graphs1', "Types of publication", 'static');
addPage_2('en/graphs', 'graphs2', "From data to information", 'interact');
addPage_2('en/graphs', 'graphs3', "Tables, graphs and text", 'static');
addPage_2('en/graphs', 'graphs4', "Combining simple graphs", 'static');
addPage_2('en/graphs', 'graphs5', "Advanced graphs", 'interact');
addPage_2('en/graphs', 'graphs6', "Innovative graphics", 'static');

var language = "en";
var logoGif = null;
var homeDir = "bk/official";
var versionGif = "images/castOfficial";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "2";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_a': 'African'};
var versions = {};
versions['tableDisplay1'] = new Array('_g', '_a');

bookLoaded = true;
