
addBook('bk/business', 'book_splash', "About this CAST e-book", null, 'v_book_splash');

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/general', 'ch_intro', "Introduction: About Data", null, 'v_ch_intro');
addSection('bk/business', 'sec_context', "Context");
addPage_2('en/context', 'context_c1', "Importance of context", 'static', 'en/context', 's_context1', 'en/context', 'v_context_c1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3', 'en/context', 'v_context3');
addSection('bk/business', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures_c1', "Variables and individuals", 'interact', 'en/structures', 's_structures_c1', 'en/structures', 'v_structures_c1');
addPage_2('en/structures', 'structures_c2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures_c2');
addPage_2('en/structures', 'structures_c3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures_c3');
addPage_2('en/structures', 'structures_c4', "Meaningful variables", 'interact', 'en/structures', 's_structures_c4', 'en/structures', 'v_structures_c4');
addPage_2('en/structures', 'structures_c5', "Time-ordered data", 'static', 'en/structures', 's_structures5', 'en/structures', 'v_structures_c5');
addPage_2('en/structures', 'structures6', "Multi-level data", 'interact', 'en/structures', 's_structures6', 'en/structures', 'v_structures6');
addPage_2('en/structures', 'structures7', "Structure of the e-book", 'static', 'en/structures', 's_structures7', 'en/structures', 'v_structures7');
addSection('bk/business', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');
addPage_2('en/variation', 'variation_c5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5', 'en/variation', 'v_variation_c5');
addPage_2('en/variation', 'variation6', "Predicting future variation", 'static', 'en/variation', 's_variation6', 'en/variation', 'v_variation6');

addChapter('bk/general', 'ch_univar', "One Numerical Variable", null, 'v_ch_univar');
addSection('bk/business', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'valueDisplay_c1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay_c1');
addPage_2('en/valueDisplay', 'valueDisplay_c2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay_c2');
addPage_2('en/valueDisplay', 'valueDisplay_c3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay_c3');
addPage_2('en/valueDisplay', 'valueDisplay_c4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay_c4');
addPage_2('en/valueDisplay', 'valueDisplay_c5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5', 'en/valueDisplay', 'v_valueDisplay_c5');
addPage_2('en/valueDisplay', 'valueDisplay_c6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6', 'en/valueDisplay', 'v_valueDisplay_c6');
addPage_2('en/valueDisplay', 'valueDisplay_c7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7', 'en/valueDisplay', 'v_valueDisplay_c7');
addSection('bk/business', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp_c1', "Outliers", 'interact', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp_c1');
addPage_2('en/displayInterp', 'displayInterp_c2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp_c2');
addPage_2('en/displayInterp', 'displayInterp_c3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp_c3');
addPage_2('en/displayInterp', 'displayInterp4', "Names of individuals", 'interact', 'en/displayInterp', 's_displayInterp4', 'en/displayInterp', 'v_displayInterp4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp_c6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp_c6');
addSection('bk/business', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2', 'en/density', 'v_density2');
addPage_2('en/density', 'density_c3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density_c3');
addPage_2('en/density', 'density_c4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density_c4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('en/density', 'density_c6', "Comparing groups", 'interact', 'en/density', 's_density6', 'en/density', 'v_density_c6');
addPage_2('en/density', 'density_c7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7', 'en/density', 'v_density_c7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8', 'en/density', 'v_density8');
addPage_2('en/density', 'density_c9', "Frequency polygons", 'interact', 'en/density', 's_density9', 'en/density', 'v_density_c9');
addPage_2('en/density', 'density_c10', "Kernel density estimates", 'interact', 'en/density', 's_density10', 'en/density', 'v_density_c10');
addPage_2('en/density', 'density_c11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11', 'en/density', 'v_density_c11');
addSection('bk/business', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot_c6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot_c6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7', 'en/boxPlot', 'v_boxPlot7');
addSection('bk/business', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread_c3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread_c3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread_c7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread_c7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addSection('bk/general', 'sec_moreVariation', "More about variation (optional)");
addPage_2('en/moreVariation', 'moreVariation1', "Effect of outliers", 'interact', 'en/moreVariation', 's_moreVariation1', 'en/moreVariation', 'v_moreVariation1');
addPage_2('en/moreVariation', 'moreVariation2', "Standard deviation of grouped data", 'interact', 'en/moreVariation', 's_moreVariation2', 'en/moreVariation', 'v_moreVariation2');
addPage_2('en/moreVariation', 'moreVariation3', "Explained and unexplained variation", 'interact', 'en/moreVariation', 's_moreVariation3', 'en/moreVariation', 'v_moreVariation3');
addPage_2('en/moreVariation', 'moreVariation4', "Variance and degrees of freedom", 'static', 'en/moreVariation', 's_moreVariation4', 'en/moreVariation', 'v_moreVariation4');
addPage_2('en/moreVariation', 'moreVariation5', "Root mean squared error", 'interact', 'en/moreVariation', 's_moreVariation5', 'en/moreVariation', 'v_moreVariation5');
addPage_2('en/moreVariation', 'moreVariation6', "Distances from the mean", 'interact', 'en/moreVariation', 's_moreVariation6', 'en/moreVariation', 'v_moreVariation6');
addSection('bk/general', 'sec_percentile', "Proportions and percentiles");
addPage_2('en/percentile', 'percentile1', "Illustrative data set", 'interact', 'en/percentile', 's_percentile1', 'en/percentile', 'v_percentile1');
addPage_2('en/percentile', 'percentile2', "Cumulative proportions", 'interact', 'en/percentile', 's_percentile2', 'en/percentile', 'v_percentile2');
addPage_2('en/percentile', 'percentile3', "Graph of cumulative proportions", 'interact', 'en/percentile', 's_percentile3', 'en/percentile', 'v_percentile3');
addPage_2('en/percentile', 'percentile4', "Percentiles", 'interact', 'en/percentile', 's_percentile4', 'en/percentile', 'v_percentile4');
addPage_2('en/percentile', 'percentile5', "Displaying percentiles", 'interact', 'en/percentile', 's_percentile5', 'en/percentile', 'v_percentile5');
addPage_2('en/percentile', 'percentile6', "Comparing groups", 'interact', 'en/percentile', 's_percentile6', 'en/percentile', 'v_percentile6');
addPage_2('en/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact', 'en/percentile', 's_percentile7', 'en/percentile', 'v_percentile7');
addPage_2('en/percentile', 'percentile8', "Better definition of percentiles", 'interact', 'en/percentile', 's_percentile8', 'en/percentile', 'v_percentile8');
addSection('bk/business', 'sec_transform', "Transformations");
addPage_2('en/transform', 'transform1', "Linear transformations", 'interact', 'en/transform', 's_transform1', 'en/transform', 'v_transform1');
addPage_2('en/transform', 'transform_c2', "Log transformations", 'interact', 'en/transform', 's_transform2', 'en/transform', 'v_transform_c2');
addPage_2('en/transform', 'transform_c3', "When to use log transform?", 'interact', 'en/transform', 's_transform3', 'en/transform', 'v_transform_c3');
addPage_2('en/transform', 'transform4', "Power transformations", 'interact', 'en/transform', 's_transform4', 'en/transform', 'v_transform4');
addPage_2('en/transform', 'transform5', "Power transforms &amp; skewness", 'interact', 'en/transform', 's_transform5', 'en/transform', 'v_transform5');
addSection('bk/business', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts_c1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1', 'en/counts', 'v_counts_c1');
addPage_2('en/counts', 'counts_c2', "Histograms for counts", 'interact', 'en/counts', 's_counts2', 'en/counts', 'v_counts_c2');
addPage_2('en/counts', 'counts_c3', "Bar charts", 'interact', 'en/counts', 's_counts3', 'en/counts', 'v_counts_c3');
addPage_2('en/counts', 'counts_c4', "Mean and st devn", 'static', 'en/counts', 's_counts4', 'en/counts', 'v_counts_c4');

addChapter('bk/business', 'ch_bivar', "Two Numerical Variables", null, 'v_ch_bivar');
addSection('bk/business', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot_c1', "Bivariate data sets", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot_c2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2', 'en/scatterplot', 'v_scatterplot_c2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot_c4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot_c4');
addPage_2('en/scatterplot', 'scatterplot_c5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5', 'en/scatterplot', 'v_scatterplot_c5');
addSection('bk/business', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship_c1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship_c1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'en/relationship', 'v_relationship2');
addPage_2('en/relationship', 'relationship_c3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship_c4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4', 'en/relationship', 'v_relationship_c4');
addPage_2('en/relationship', 'relationship_c5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship_c5');
addSection('bk/business', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation_c1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation_c1', 'en/correlation', 'v_correlation_c1');
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2', 'en/correlation', 'v_correlation2');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3', 'en/correlation', 'v_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4', 'en/correlation', 'v_correlation4');
addPage_2('en/correlation', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5', 'en/correlation', 'v_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6', 'en/correlation', 'v_correlation6');
addSection('bk/business', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs_c1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1', 'en/leastSqrs', 'v_leastSqrs_c1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2', 'en/leastSqrs', 'v_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs_c3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs_c3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5', 'en/leastSqrs', 'v_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs_c6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6', 'en/leastSqrs', 'v_leastSqrs_c6');
addPage_2('en/leastSqrs', 'leastSqrs_c7', "Predicting Y and predicting X", 'interact', 'en/leastSqrs', 's_leastSqrs7', 'en/leastSqrs', 'v_leastSqrs_c7');
addSection('bk/business', 'sec_curvature', "Nonlinear relationships");
addPage_2('en/curvature', 'curvature_c1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1', 'en/curvature', 'v_curvature_c1');
addPage_2('en/curvature', 'curvature_c2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2', 'en/curvature', 'v_curvature_c2');
addPage_2('en/curvature', 'curvature_c3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3', 'en/curvature', 'v_curvature_c3');
addPage_2('en/curvature', 'curvature_c4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4', 'en/curvature', 'v_curvature_c4');

addChapter('bk/business', 'ch_timeSeries', "Time Series", null, 'v_ch_timeSeries');
addSection('bk/business', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot_c1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1', 'en/timePlot', 'v_timePlot_c1');
addPage_2('en/timePlot', 'timePlot_c2', "Patterns in time series", 'interact', 'en/timePlot', 's_timePlot2', 'en/timePlot', 'v_timePlot_c2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3', 'en/timePlot', 'v_timePlot3');
addSection('bk/general', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1', 'en/smoothing', 'v_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2', 'en/smoothing', 'v_smoothing2');
addPage_2('en/smoothing', 'smoothing3', "Robust smoothing", 'interact', 'en/smoothing', 's_smoothing3', 'en/smoothing', 'v_smoothing3');
addPage_2('en/smoothing', 'smoothing4', "Exponential smoothing", 'interact', 'en/smoothing', 's_smoothing4', 'en/smoothing', 'v_smoothing4');
addPage_2('en/smoothing', 'smoothing5', "Lowess smoothing of time series", 'interact', 'en/smoothing', 's_smoothing5', 'en/smoothing', 'v_smoothing5');
addPage_2('en/smoothing', 'smoothing6', "Lowess smoothing of scatterplots", 'interact', 'en/smoothing', 's_smoothing6', 'en/smoothing', 'v_smoothing6');
addSection('bk/general', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'trend1', "Linear trend", 'interact', 'en/trend', 's_trend1', 'en/trend', 'v_trend1');
addPage_2('en/trend', 'trend2', "Quadratic trend", 'interact', 'en/trend', 's_trend2', 'en/trend', 'v_trend2');
addPage_2('en/trend', 'trend3', "Forecasting", 'interact', 'en/trend', 's_trend3', 'en/trend', 'v_trend3');
addPage_2('en/trend', 'trend4', "Polynomial trend", 'interact', 'en/trend', 's_trend4', 'en/trend', 'v_trend4');
addPage_2('en/trend', 'trend5', "Detrending a time series", 'interact', 'en/trend', 's_trend5', 'en/trend', 'v_trend5');
addSection('bk/general', 'sec_cyclic', "Short-term fluctuations");
addPage_2('en/cyclic', 'cyclic1', "Autocorrelation", 'interact', 'en/cyclic', 's_cyclic1', 'en/cyclic', 'v_cyclic1');
addPage_2('en/cyclic', 'cyclic2', "AR(1) model for autocorrelation", 'interact', 'en/cyclic', 's_cyclic2', 'en/cyclic', 'v_cyclic2');
addPage_2('en/cyclic', 'cyclic3', "AR(1) model and trend", 'interact', 'en/cyclic', 's_cyclic3', 'en/cyclic', 'v_cyclic3');
addPage_2('en/cyclic', 'cyclic4', "Trend or autocorrelation?", 'interact', 'en/cyclic', 's_cyclic4', 'en/cyclic', 'v_cyclic4');
addPage_2('en/cyclic', 'cyclic5', "Cyclical patterns", 'interact', 'en/cyclic', 's_cyclic5', 'en/cyclic', 'v_cyclic5');
addSection('bk/general', 'sec_seasonal', "Seasonal data");
addPage_2('en/seasonal', 'seasonal1', "Seasonal patterns", 'interact', 'en/seasonal', 's_seasonal1', 'en/seasonal', 'v_seasonal1');
addPage_2('en/seasonal', 'seasonal2', "Smoothing out seasonal variation", 'interact', 'en/seasonal', 's_seasonal2', 'en/seasonal', 'v_seasonal2');
addPage_2('en/seasonal', 'seasonal3', "Estimating the seasonal effect", 'interact', 'en/seasonal', 's_seasonal3', 'en/seasonal', 'v_seasonal3');
addPage_2('en/seasonal', 'seasonal4', "Deseasonalised data", 'interact', 'en/seasonal', 's_seasonal4', 'en/seasonal', 'v_seasonal4');
addPage_2('en/seasonal', 'seasonal5', "Putting it all together", 'interact', 'en/seasonal', 's_seasonal5', 'en/seasonal', 'v_seasonal5');
addPage_2('en/seasonal', 'seasonal6', "Forecasting with seasonal data", 'interact', 'en/seasonal', 's_seasonal6', 'en/seasonal', 'v_seasonal6');
addSection('bk/general', 'sec_multiplicative', "Multiplicative models");
addPage_2('en/multiplicative', 'multiplicative1', "Additive and multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative1', 'en/multiplicative', 'v_multiplicative1');
addPage_2('en/multiplicative', 'multiplicative2', "Properties of multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative2', 'en/multiplicative', 'v_multiplicative2');
addPage_2('en/multiplicative', 'multiplicative3', "Forecasting with multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative3', 'en/multiplicative', 'v_multiplicative3');
addPage_2('en/multiplicative', 'multiplicative4', "Analysing the right data", 'static', 'en/multiplicative', 's_multiplicative4', 'en/multiplicative', 'v_multiplicative4');
addPage_2('en/multiplicative', 'multiplicative5', "Types of time series data", 'static', 'en/multiplicative', 's_multiplicative5', 'en/multiplicative', 'v_multiplicative5');
addSection('bk/general', 'sec_indexNos', "Index numbers");
addPage_2('en/indexNos', 'indexNos1', "Introduction", 'static', 'en/indexNos', 's_indexNos1', 'en/indexNos', 'v_indexNos1');
addPage_2('en/indexNos', 'indexNos2', "Simple price index", 'static', 'en/indexNos', 's_indexNos2', 'en/indexNos', 'v_indexNos2');
addPage_2('en/indexNos', 'indexNos3', "Aggregate price index", 'static', 'en/indexNos', 's_indexNos3', 'en/indexNos', 'v_indexNos3');
addPage_2('en/indexNos', 'indexNos4', "Laspeyres and Paasche indices", 'static', 'en/indexNos', 's_indexNos4', 'en/indexNos', 'v_indexNos4');
addPage_2('en/indexNos', 'indexNos5', "Deflating a time series", 'static', 'en/indexNos', 's_indexNos5', 'en/indexNos', 'v_indexNos5');

addChapter('bk/general', 'ch_cat', "Categorical Variables", null, 'v_ch_cat');
addSection('bk/business', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable_c1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable_c1', 'en/freqTable', 'v_freqTable_c1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addSection('bk/business', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2', 'en/univarCat', 'v_univarCat2');
addPage_2('en/univarCat', 'univarCat3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat3', 'en/univarCat', 'v_univarCat3');
addPage_2('en/univarCat', 'univarCat_c4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat_c4');
addPage_2('en/univarCat', 'univarCat_c5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat_c5');
addPage_2('en/univarCat', 'univarCat_c6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat_c6', 'en/univarCat', 'v_univarCat_c6');
addPage_2('en/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat7');
addSection('bk/business', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat_c1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat_c1', 'en/groupedCat', 'v_groupedCat_c1');
addPage_2('en/groupedCat', 'groupedCat_c2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat_c2', 'en/groupedCat', 'v_groupedCat_c2');
addPage_2('en/groupedCat', 'groupedCat_c3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat_c3', 'en/groupedCat', 'v_groupedCat_c3');
addPage_2('en/groupedCat', 'groupedCat_c4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat_c4', 'en/groupedCat', 'v_groupedCat_c4');
addPage_2('en/groupedCat', 'groupedCat_c5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5', 'en/groupedCat', 'v_groupedCat_c5');
addSection('bk/business', 'sec_bivarCat', "Bivariate categorical distributions");
addPage_2('en/bivarCat', 'bivarCat_c1', "Relationships between variables", 'static', 'en/bivarCat', 's_bivarCat1', 'en/bivarCat', 'v_bivarCat_c1');
addPage_2('en/bivarCat', 'bivarCat2', "3-dimensional bar charts", 'interact', 'en/bivarCat', 's_bivarCat2', 'en/bivarCat', 'v_bivarCat2');
addPage_2('en/bivarCat', 'bivarCat3', "Clustered bar charts", 'interact', 'en/bivarCat', 's_bivarCat3', 'en/bivarCat', 'v_bivarCat3');
addPage_2('en/bivarCat', 'bivarCat4', "Marginal distributions", 'interact', 'en/bivarCat', 's_bivarCat4', 'en/bivarCat', 'v_bivarCat4');
addPage_2('en/bivarCat', 'bivarCat5', "Conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat5', 'en/bivarCat', 'v_bivarCat5');
addPage_2('en/bivarCat', 'bivarCat6', "More about conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat6', 'en/bivarCat', 'v_bivarCat6');
addPage_2('en/bivarCat', 'bivarCat7', "Conditional vs marginal distns", 'interact', 'en/bivarCat', 's_bivarCat7', 'en/bivarCat', 'v_bivarCat7');
addSection('bk/general', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2', 'en/tableDisplay', 'v_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4', 'en/tableDisplay', 'v_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5', 'en/tableDisplay', 'v_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6', 'en/tableDisplay', 'v_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7', 'en/tableDisplay', 'v_tableDisplay7');
addSection('bk/business', 'sec_logistic', "Logistic regression");
addPage_2('en/logistic', 'logistic_c1', "Categorical responses", 'interact', 'en/logistic', 's_logistic1', 'en/logistic', 'v_logistic1');
addPage_2('en/logistic', 'logistic_c2', "Fitted values and predictions", 'interact', 'en/logistic', 's_logistic2', 'en/logistic', 'v_logistic_c2');
addPage_2('en/logistic', 'logistic3', "Logistic curve", 'interact', 'en/logistic', 's_logistic3', 'en/logistic', 'v_logistic3');
addPage_2('en/logistic', 'logistic_c4', "Obtaining a good fit", 'interact', 'en/logistic', 's_logistic4', 'en/logistic', 'v_logistic_c4');

addChapter('bk/general', 'ch_multivar', "Multivariate Data", null, 'v_ch_multivar');
addSection('bk/business', 'sec_multivariate', "Displaying multivariate data");
addPage_2('en/multivariate', 'multivariate_c1', "Representing a third variable", 'interact', 'en/multivariate', 's_multivariate1', 'en/multivariate', 'v_multivariate_c1');
addPage_2('en/multivariate', 'multivariate_c2', "Rotating 3D scatterplots", 'interact', 'en/multivariate', 's_multivariate2', 'en/multivariate', 'v_multivariate_c2');
addPage_2('en/multivariate', 'multivariate_c3', "Scatterplot matrix and brushing", 'interact', 'en/multivariate', 's_multivariate3', 'en/multivariate', 'v_multivariate_c3');
addPage_2('en/multivariate', 'multivariate4', "Brushing example", 'interact', 'en/multivariate', 's_multivariate4', 'en/multivariate', 'v_multivariate4');
addPage_2('en/multivariate', 'multivariate_c5', "Slicing", 'interact', 'en/multivariate', 's_multivariate_c5', 'en/multivariate', 'v_multivariate_c5');
addSection('bk/business', 'sec_regnGroups', "Groups and regression");
addPage_2('en/regnGroups', 'regnGroups1', "Additional variables in regression", 'interact', 'en/regnGroups', 's_regnGroups1', 'en/regnGroups', 'v_regnGroups1');
addPage_2('en/regnGroups', 'regnGroups2', "Displaying groups", 'interact', 'en/regnGroups', 's_regnGroups2', 'en/regnGroups', 'v_regnGroups2');
addPage_2('en/regnGroups', 'regnGroups3', "Regression with grouped data", 'interact', 'en/regnGroups', 's_regnGroups3', 'en/regnGroups', 'v_regnGroups3');
addPage_2('en/regnGroups', 'regnGroups4', "Parallel regression lines", 'interact', 'en/regnGroups', 's_regnGroups4', 'en/regnGroups', 'v_regnGroups4');
addPage_2('en/regnGroups', 'regnGroups5', "Transformed variables and groups", 'interact', 'en/regnGroups', 's_regnGroups5', 'en/regnGroups', 'v_regnGroups5');
addPage_2('en/regnGroups', 'regnGroups6', "Grouping with a numerical variable", 'interact', 'en/regnGroups', 's_regnGroups6', 'en/regnGroups', 'v_regnGroups6');
addPage_2('en/regnGroups', 'regnGroups_c7', "Displaying groups", 'interact', 'en/regnGroups', 's_regnGroups7', 'en/regnGroups', 'v_regnGroups_c7');
addSection('bk/general', 'sec_multiRegn', "Multiple regression");
addPage_2('en/multiRegn', 'multiRegn1', "More than one explanatory variable", 'interact', 'en/multiRegn', 's_multiRegn1', 'en/multiRegn', 'v_multiRegn1');
addPage_2('en/multiRegn', 'multiRegn2', "Multiple regression equation", 'interact', 'en/multiRegn', 's_multiRegn2', 'en/multiRegn', 'v_multiRegn2');
addPage_2('en/multiRegn', 'multiRegn3', "Interpreting coefficients", 'interact', 'en/multiRegn', 's_multiRegn3', 'en/multiRegn', 'v_multiRegn3');
addPage_2('en/multiRegn', 'multiRegn4', "Scatterplot of three variables", 'interact', 'en/multiRegn', 's_multiRegn4', 'en/multiRegn', 'v_multiRegn4');
addPage_2('en/multiRegn', 'multiRegn5', "Regression plane", 'interact', 'en/multiRegn', 's_multiRegn5', 'en/multiRegn', 'v_multiRegn5');
addPage_2('en/multiRegn', 'multiRegn6', "Fitted values and residuals", 'interact', 'en/multiRegn', 's_multiRegn6', 'en/multiRegn', 'v_multiRegn6');
addPage_2('en/multiRegn', 'multiRegn7', "Least squares estimation", 'interact', 'en/multiRegn', 's_multiRegn7', 'en/multiRegn', 'v_multiRegn7');
addSection('bk/business', 'sec_lurking', "Marginal relationships");
addPage_2('en/lurking', 'lurking_c1', "Misleading marginal correlation", 'interact', 'en/lurking', 's_lurking1', 'en/lurking', 'v_lurking_c1');
addPage_2('en/lurking', 'lurking2', "Misleading marginal difference in means", 'interact', 'en/lurking', 's_lurking2', 'en/lurking', 'v_lurking2');
addPage_2('en/lurking', 'lurking_c3', "Simpsons paradox", 'interact', 'en/lurking', 's_lurking_c3', 'en/lurking', 'v_lurking_c3');
addPage_2('en/lurking', 'lurking4', "Other examples with lurking variables", 'static', 'en/lurking', 's_lurking4', 'en/lurking', 'v_lurking4');

addChapter('bk/general', 'ch_sample', "Sampling and Variability", null, 'v_ch_sample');
addSection('bk/business', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp_c1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp_c1');
addPage_2('en/popSamp', 'popSamp_c2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp_c2');
addPage_2('en/popSamp', 'popSamp_c3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp_c3');
addPage_2('en/popSamp', 'popSamp4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4', 'en/popSamp', 'v_popSamp4');
addPage_2('en/popSamp', 'popSamp_c5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5', 'en/popSamp', 'v_popSamp_c5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addSection('bk/business', 'sec_infPopn', "Abstract infinite populations");
addPage_2('en/infPopn', 'infPopn_c1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn_c1', 'en/infPopn', 'v_infPopn_c1');
addPage_2('en/infPopn', 'infPopn_c2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2', 'en/infPopn', 'v_infPopn_c2');
addPage_2('en/infPopn', 'infPopn_c3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3', 'en/infPopn', 'v_infPopn_c3');
addPage_2('en/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact', 'en/infPopn', 's_infPopn4', 'en/infPopn', 'v_infPopn4');
addPage_2('en/infPopn', 'infPopn_c5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5', 'en/infPopn', 'v_infPopn_c5');
addSection('bk/business', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1', 'en/probDensity', 'v_probDensity1');
addPage_2('en/probDensity', 'probDensity_c2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2', 'en/probDensity', 'v_probDensity_c2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3', 'en/probDensity', 'v_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4', 'en/probDensity', 'v_probDensity4');
addPage_2('en/probDensity', 'probDensity_c5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5', 'en/probDensity', 'v_probDensity_c5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6', 'en/probDensity', 'v_probDensity6');
addPage_2('en/probDensity', 'probDensity_c7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7', 'en/probDensity', 'v_probDensity_c7');
addSection('bk/business', 'sec_probSim', "Simulation (optional)");
addPage_2('en/probSim', 'probSim1', "Probability models and simulation", 'interact', 'en/probSim', 's_probSim1', 'en/probSim', 'v_probSim1');
addPage_2('en/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact', 'en/probSim', 's_probSim2', 'en/probSim', 'v_probSim2');
addPage_2('en/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact', 'en/probSim', 's_probSim3', 'en/probSim', 'v_probSim3');
addPage_2('en/probSim', 'probSim_c4', "Assessing unusual features in data", 'interact', 'en/probSim', 's_probSim4', 'en/probSim', 'v_probSim_c4');
addPage_2('en/probSim', 'probSim5', "Random numbers", 'interact', 'en/probSim', 's_probSim5', 'en/probSim', 'v_probSim5');
addPage_2('en/probSim', 'probSim_c6', "Generating categorical values (advanced)", 'interact', 'en/probSim', 's_probSim6', 'en/probSim', 'v_probSim_c6');
addPage_2('en/probSim', 'probSim7', "Generating numerical values", 'interact', 'en/probSim', 's_probSim7', 'en/probSim', 'v_probSim7');
addSection('bk/business', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_c1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean_c1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/randomMean', 'randomMean_c6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean_c6', 'en/randomMean', 'v_randomMean_c6');
addPage_2('en/randomMean', 'randomMean7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7', 'en/randomMean', 'v_randomMean7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite populations", 'interact', 'en/randomMean', 's_randomMean8', 'en/randomMean', 'v_randomMean8');
addSection('bk/business', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn_c1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1', 'en/normalDistn', 'v_normalDistn_c1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn_c3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn_c3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5', 'en/normalDistn', 'v_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn_c6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6', 'en/normalDistn', 'v_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn_c7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7', 'en/normalDistn', 'v_normalDistn_c7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8', 'en/normalDistn', 'v_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9', 'en/normalDistn', 'v_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10', 'en/normalDistn', 'v_normalDistn10');
addSection('bk/business', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn_c1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1', 'en/randomPropn', 'v_randomPropn_c1');
addPage_2('en/randomPropn', 'randomPropn_c2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn_c2');
addPage_2('en/randomPropn', 'randomPropn_c3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn_c3');
addPage_2('en/randomPropn', 'randomPropn_c4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn_c4', 'en/randomPropn', 'v_randomPropn_c4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'en/randomPropn', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn_c6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn_c6', 'en/randomPropn', 'v_randomPropn_c6');
addSection('bk/business', 'sec_sampPractice', "Sampling in practice");
addPage_2('en/sampPractice', 'sampPractice1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1', 'en/sampPractice', 'v_sampPractice1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2', 'en/sampPractice', 'v_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3', 'en/sampPractice', 'v_sampPractice3');
addPage_2('en/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4', 'en/sampPractice', 'v_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice_c5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5', 'en/sampPractice', 'v_sampPractice_c5');
addPage_2('en/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6', 'en/sampPractice', 'v_sampPractice6');
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7', 'en/sampPractice', 'v_sampPractice7');
addSection('bk/general', 'sec_controlChart', "Control charts");
addPage_2('en/controlChart', 'controlChart1', "Introduction", 'static', 'en/controlChart', 's_controlChart1', 'en/controlChart', 'v_controlChart1');
addPage_2('en/controlChart', 'controlChart2', "Run charts", 'interact', 'en/controlChart', 's_controlChart2', 'en/controlChart', 'v_controlChart2');
addPage_2('en/controlChart', 'controlChart3', "Control limits", 'interact', 'en/controlChart', 's_controlChart3', 'en/controlChart', 'v_controlChart3');
addPage_2('en/controlChart', 'controlChart4', "Other signals of being out-of-control", 'interact', 'en/controlChart', 's_controlChart4', 'en/controlChart', 'v_controlChart4');
addPage_2('en/controlChart', 'controlChart5', "False alarms", 'interact', 'en/controlChart', 's_controlChart5', 'en/controlChart', 'v_controlChart5');
addPage_2('en/controlChart', 'controlChart6', "Examples of run charts", 'interact', 'en/controlChart', 's_controlChart6', 'en/controlChart', 'v_controlChart6');
addPage_2('en/controlChart', 'controlChart7', "Control charts for means", 'interact', 'en/controlChart', 's_controlChart7', 'en/controlChart', 'v_controlChart7');
addPage_2('en/controlChart', 'controlChart8', "Control charts for ranges", 'interact', 'en/controlChart', 's_controlChart8', 'en/controlChart', 'v_controlChart8');
addPage_2('en/controlChart', 'controlChart9', "Finding the cause of problems", 'interact', 'en/controlChart', 's_controlChart9', 'en/controlChart', 'v_controlChart9');

addChapter('bk/business', 'ch_expDesign', "Designed Experiments", null, 'v_ch_expDesign');
addSection('bk/business', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal_c1', "Interest in relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal_c1');
addPage_2('en/causal', 'causal_c2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2', 'en/causal', 'v_causal_c2');
addPage_2('en/causal', 'causal_c3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3', 'en/causal', 'v_causal_c3');
addPage_2('en/causal', 'causal_c4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4', 'en/causal', 'v_causal_c4');
addPage_2('en/causal', 'causal_c5', "Data collection and causality", 'interact', 'en/causal', 's_causal5', 'en/causal', 'v_causal_c5');
addSection('bk/business', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'designIntro_c1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1', 'en/designIntro', 'v_designIntro_c1');
addPage_2('en/designIntro', 'designIntro_c2', "Variability in experimental units", 'interact', 'en/designIntro', 's_designIntro2', 'en/designIntro', 'v_designIntro_c2');
addPage_2('en/designIntro', 'designIntro_c3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3', 'en/designIntro', 'v_designIntro_c3');
addPage_2('en/designIntro', 'designIntro_c4', "Confounding", 'static', 'en/designIntro', 's_designIntro4', 'en/designIntro', 'v_designIntro_c4');
addPage_2('en/designIntro', 'designIntro_c5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5', 'en/designIntro', 'v_designIntro_c5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6', 'en/designIntro', 'v_designIntro6');
addPage_2('en/designIntro', 'designIntro_c7', "Blocking", 'interact', 'en/designIntro', 's_designIntro7', 'en/designIntro', 'v_designIntro_c7');
addSection('bk/business', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1', 'en/designPrelim', 'v_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim_c2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2', 'en/designPrelim', 'v_designPrelim_c2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3', 'en/designPrelim', 'v_designPrelim3');

addChapter('bk/general', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/business', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro_c1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro_c1', 'en/estIntro', 'v_estIntro_c1');
addPage_2('en/estIntro', 'estIntro_c2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2', 'en/estIntro', 'v_estIntro_c2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3', 'en/estIntro', 'v_estIntro3');
addPage_2('en/estIntro', 'estIntro_c4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4', 'en/estIntro', 'v_estIntro_c4');
addPage_2('en/estIntro', 'estIntro_c5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5', 'en/estIntro', 'v_estIntro_c5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6', 'en/estIntro', 'v_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7', 'en/estIntro', 'v_estIntro7');
addSection('bk/business', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean_c1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1', 'en/seMean', 'v_seMean_c1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2', 'en/seMean', 'v_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3', 'en/seMean', 'v_seMean3');
addPage_2('en/seMean', 'seMean_c4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean_c4', 'en/seMean', 'v_seMean_c4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addPage_2('en/seMean', 'seMean_c6', "Using SEs to compare estimators", 'interact', 'en/seMean', 's_seMean6', 'en/seMean', 'v_seMean_c6');
addPage_2('en/seMean', 'seMean7', "More about bias", 'interact', 'en/seMean', 's_seMean7', 'en/seMean', 'v_seMean7');
addSection('bk/business', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean_c1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean_c1');
addPage_2('en/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2', 'en/ciMean', 'v_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3', 'en/ciMean', 'v_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4', 'en/ciMean', 'v_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5', 'en/ciMean', 'v_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6', 'en/ciMean', 'v_ciMean6');
addPage_2('en/ciMean', 'ciMean_c7', "Examples", 'static', 'en/ciMean', 's_ciMean_c7', 'en/ciMean', 'v_ciMean_c7');
addSection('bk/business', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('en/estPropn', 'estPropn_c3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn_c3');
addPage_2('en/estPropn', 'estPropn_c4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn_c4', 'en/estPropn', 'v_estPropn_c4');
addPage_2('en/estPropn', 'estPropn_c5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5', 'en/estPropn', 'v_estPropn_c5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('en/estPropn', 'estPropn_c7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn_c7', 'en/estPropn', 'v_estPropn_c7');
addSection('bk/business', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'ciExtra_c1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1', 'en/ciExtra', 'v_ciExtra_c1');
addPage_2('en/ciExtra', 'ciExtra_c2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2', 'en/ciExtra', 'v_ciExtra_c2');
addPage_2('en/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3', 'en/ciExtra', 'v_ciExtra3');
addPage_2('en/ciExtra', 'ciExtra4', "Other confidence levels", 'interact', 'en/ciExtra', 's_ciExtra4', 'en/ciExtra', 'v_ciExtra4');
addSection('bk/business', 'sec_estOther', "Simulation &amp; bootstrap (advanced)");
addPage_2('en/estOther', 'estOther1', "Need for simulation", 'static', 'en/estOther', 's_estOther1', 'en/estOther', 'v_estOther1');
addPage_2('en/estOther', 'estOther2', "Error distribution by simulation", 'interact', 'en/estOther', 's_estOther2', 'en/estOther', 'v_estOther2');
addPage_2('en/estOther', 'estOther_c3', "Simulations with normal distns", 'interact', 'en/estOther', 's_estOther_c3', 'en/estOther', 'v_estOther_c3');
addPage_2('en/estOther', 'estOther4', "Bootstrap error distribution", 'interact', 'en/estOther', 's_estOther4', 'en/estOther', 'v_estOther4');
addPage_2('en/estOther', 'estOther5', "Standard error of correlation", 'interact', 'en/estOther', 's_estOther5', 'en/estOther', 'v_estOther5');

addChapter('bk/general', 'ch_testing', "Testing Hypotheses", null, 'v_ch_testing');
addSection('bk/business', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro1', "Inference", 'static', 'en/testIntro', 's_testIntro1', 'en/testIntro', 'v_testIntro1');
addPage_2('en/testIntro', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2', 'en/testIntro', 'v_testIntro2');
addPage_2('en/testIntro', 'testIntro_c3', "Simulation to test a proportion", 'interact', 'en/testIntro', 's_testIntro3', 'en/testIntro', 'v_testIntro_c3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4', 'en/testIntro', 'v_testIntro4');
addPage_2('en/testIntro', 'testIntro5', "Randomisation tests", 'interact', 'en/testIntro', 's_testIntro5', 'en/testIntro', 'v_testIntro5');
addPage_2('en/testIntro', 'testIntro6', "Randomisation test for correlation", 'interact', 'en/testIntro', 's_testIntro6', 'en/testIntro', 'v_testIntro6');
addPage_2('en/testIntro', 'testIntro_c7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7', 'en/testIntro', 'v_testIntro_c7');
addSection('bk/business', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'testPropn_c1', "Inference about parameters", 'static', 'en/testPropn', 's_testPropn1', 'en/testPropn', 'v_testPropn_c1');
addPage_2('en/testPropn', 'testPropn_c2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2', 'en/testPropn', 'v_testPropn_c2');
addPage_2('en/testPropn', 'testPropn_c3', "Another example", 'interact', 'en/testPropn', 's_testPropn_c3', 'en/testPropn', 'v_testPropn_c3');
addPage_2('en/testPropn', 'testPropn_c4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn_c4', 'en/testPropn', 'v_testPropn_c4');
addPage_2('en/testPropn', 'testPropn5', "Normal approximation", 'interact', 'en/testPropn', 's_testPropn5', 'en/testPropn', 'v_testPropn5');
addPage_2('en/testPropn', 'testPropn6', "Statistical distance", 'static', 'en/testPropn', 's_testPropn6', 'en/testPropn', 'v_testPropn6');
addPage_2('en/testPropn', 'testPropn7', "Tests based on statistical distance", 'interact', 'en/testPropn', 's_testPropn7', 'en/testPropn', 'v_testPropn7');
addSection('bk/business', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean_c1', "Introduction", 'static', 'en/testMean', 's_testMean1', 'en/testMean', 'v_testMean_c1');
addPage_2('en/testMean', 'testMean_c2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2', 'en/testMean', 'v_testMean_c2');
addPage_2('en/testMean', 'testMean3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3', 'en/testMean', 'v_testMean3');
addPage_2('en/testMean', 'testMean_c4', "The t distribution", 'interact', 'en/testMean', 's_testMean4', 'en/testMean', 'v_testMean_c4');
addPage_2('en/testMean', 'testMean_c5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5', 'en/testMean', 'v_testMean_c5');
addSection('bk/general', 'sec_decision', "Decisions and significance");
addPage_2('en/decision', 'decision1', "Hypothesis tests and decisions", 'static', 'en/decision', 's_decision1', 'en/decision', 'v_decision1');
addPage_2('en/decision', 'decision2', "Decision rules", 'interact', 'en/decision', 's_decision2', 'en/decision', 'v_decision2');
addPage_2('en/decision', 'decision3', "Significance level and p-values", 'interact', 'en/decision', 's_decision3', 'en/decision', 'v_decision3');
addPage_2('en/decision', 'decision4', "Sample size and power", 'interact', 'en/decision', 's_decision4', 'en/decision', 'v_decision4');
addSection('bk/business', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'testPValue_c1', "Null and alternative hypotheses", 'interact', 'en/testPValue', 's_testPValue1', 'en/testPValue', 'v_testPValue_c1');
addPage_2('en/testPValue', 'testPValue_c2', "Consistency with null hypothesis", 'interact', 'en/testPValue', 's_testPValue2', 'en/testPValue', 'v_testPValue_c2');
addPage_2('en/testPValue', 'testPValue3', "Distribution of p-values", 'interact', 'en/testPValue', 's_testPValue3', 'en/testPValue', 'v_testPValue3');
addPage_2('en/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact', 'en/testPValue', 's_testPValue4', 'en/testPValue', 'v_testPValue4');
addPage_2('en/testPValue', 'testPValue_c5', "P-values for other tests", 'interact', 'en/testPValue', 's_testPValue5', 'en/testPValue', 'v_testPValue_c5');

addChapter('bk/general', 'ch_twoGroups', "Comparing Groups", null, 'v_ch_twoGroups');
addSection('bk/business', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel_c1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel_c1', 'en/twoGroupModel', 'v_twoGroupModel_c1');
addPage_2('en/twoGroupModel', 'twoGroupModel_c2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2', 'en/twoGroupModel', 'v_twoGroupModel_c2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3', 'en/twoGroupModel', 'v_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel_c4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4', 'en/twoGroupModel', 'v_twoGroupModel_c4');
addPage_2('en/twoGroupModel', 'twoGroupModel_c5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel_c5', 'en/twoGroupModel', 'v_twoGroupModel_c5');
addSection('bk/general', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'sumDiff1', "Means and sums of samples", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('en/sumDiff', 'sumDiff2', "Sum and difference", 'interact', 'en/sumDiff', 's_sumDiff2', 'en/sumDiff', 'v_sumDiff2');
addPage_2('en/sumDiff', 'sumDiff3', "Sum and difference (cont)", 'interact', 'en/sumDiff', 's_sumDiff3', 'en/sumDiff', 'v_sumDiff3');
addPage_2('en/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static', 'en/sumDiff', 's_sumDiff4', 'en/sumDiff', 'v_sumDiff4');
addSection('bk/business', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'twoGroupInf_c1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1', 'en/twoGroupInf', 'v_twoGroupInf_c1');
addPage_2('en/twoGroupInf', 'twoGroupInf_c2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf_c2', 'en/twoGroupInf', 'v_twoGroupInf_c2');
addPage_2('en/twoGroupInf', 'twoGroupInf_c3', "CI for difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf_c3', 'en/twoGroupInf', 'v_twoGroupInf_c3');
addPage_2('en/twoGroupInf', 'twoGroupInf_c4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf_c4', 'en/twoGroupInf', 'v_twoGroupInf_c4');
addPage_2('en/twoGroupInf', 'twoGroupInf_c5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf_c5', 'en/twoGroupInf', 'v_twoGroupInf_c5');
addSection('bk/business', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'twoGroupPropn_c1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn_c1', 'en/twoGroupPropn', 'v_twoGroupPropn_c1');
addPage_2('en/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn2', 'en/twoGroupPropn', 'v_twoGroupPropn2');
addPage_2('en/twoGroupPropn', 'twoGroupPropn_c3', "CI for difference in proportions", 'static', 'en/twoGroupPropn', 's_twoGroupPropn_c3', 'en/twoGroupPropn', 'v_twoGroupPropn_c3');
addPage_2('en/twoGroupPropn', 'twoGroupPropn_c4', "Testing for difference in probabilities", 'static', 'en/twoGroupPropn', 's_twoGroupPropn_c4', 'en/twoGroupPropn', 'v_twoGroupPropn_c4');
addSection('bk/business', 'sec_testPaired', "Paired t test");
addPage_2('en/testPaired', 'testPaired_c1', "Paired data", 'static', 'en/testPaired', 's_testPaired1', 'en/testPaired', 'v_testPaired_c1');
addPage_2('en/testPaired', 'testPaired_c2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2', 'en/testPaired', 'v_testPaired_c2');
addPage_2('en/testPaired', 'testPaired_c3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3', 'en/testPaired', 'v_testPaired_c3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4', 'en/testPaired', 'v_testPaired4');
addSection('bk/business', 'sec_multiGroup', "Comparing several means");
addPage_2('en/multiGroup', 'multiGroup_c1', "Model", 'interact', 'en/multiGroup', 's_multiGroup1', 'en/multiGroup', 'v_multiGroup_c1');
addPage_2('en/multiGroup', 'multiGroup2', "Parameter estimates", 'interact', 'en/multiGroup', 's_multiGroup2', 'en/multiGroup', 'v_multiGroup2');
addPage_2('en/multiGroup', 'multiGroup_c3', "Revisiting two groups", 'static', 'en/multiGroup', 's_multiGroup3', 'en/multiGroup', 'v_multiGroup_c3');
addPage_2('en/multiGroup', 'multiGroup4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup_c6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup_c6', 'en/multiGroup', 'v_multiGroup_c6');
addPage_2('en/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addPage_2('en/multiGroup', 'multiGroup_c8', "Examples", 'static', 'en/multiGroup', 's_multiGroup_c8', 'en/multiGroup', 'v_multiGroup_c8');

addChapter('bk/general', 'ch_regnInference', "Regression Inference", null, 'v_ch_regnInference');
addSection('bk/business', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel_c1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel_c1', 'en/regnModel', 'v_regnModel_c1');
addPage_2('en/regnModel', 'regnModel_c2', "Distribution of Y for each X", 'interact', 'en/regnModel', 's_regnModel2', 'en/regnModel', 'v_regnModel_c2');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3', 'en/regnModel', 'v_regnModel3');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4', 'en/regnModel', 'v_regnModel4');
addPage_2('en/regnModel', 'regnModel_c5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel_c5', 'en/regnModel', 'v_regnModel_c5');
addSection('bk/business', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst_c1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1', 'en/regnEst', 'v_regnEst_c1');
addPage_2('en/regnEst', 'regnEst_c2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2', 'en/regnEst', 'v_regnEst_c2');
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3', 'en/regnEst', 'v_regnEst3');
addPage_2('en/regnEst', 'regnEst_c4', "Standard error of least squares slope", 'static', 'en/regnEst', 's_regnEst_c4', 'en/regnEst', 'v_regnEst_c4');
addPage_2('en/regnEst', 'regnEst_c5', "95% confidence interval for slope", 'static', 'en/regnEst', 's_regnEst_c5', 'en/regnEst', 'v_regnEst_c5');
addPage_2('en/regnEst', 'regnEst6', "Properties of confidence interval", 'interact', 'en/regnEst', 's_regnEst6', 'en/regnEst', 'v_regnEst6');
addPage_2('en/regnEst', 'regnEst7', "Influences on accuracy", 'interact', 'en/regnEst', 's_regnEst7', 'en/regnEst', 'v_regnEst7');
addSection('bk/business', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest_c1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1', 'en/regnTest', 'v_regnTest_c1');
addPage_2('en/regnTest', 'regnTest_c2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest_c2', 'en/regnTest', 'v_regnTest_c2');
addPage_2('en/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3', 'en/regnTest', 'v_regnTest3');
addPage_2('en/regnTest', 'regnTest4', "Properties of p-values", 'interact', 'en/regnTest', 's_regnTest4', 'en/regnTest', 'v_regnTest4');
addSection('bk/business', 'sec_regnPred', "Predicting the response");
addPage_2('en/regnPred', 'regnPred_c1', "Estimated response distn at X", 'interact', 'en/regnPred', 's_regnPred1', 'en/regnPred', 'v_regnPred_c1');
addPage_2('en/regnPred', 'regnPred2', "Variability of estimate at X", 'interact', 'en/regnPred', 's_regnPred2', 'en/regnPred', 'v_regnPred2');
addPage_2('en/regnPred', 'regnPred_c3', "Estimating the mean vs prediction", 'interact', 'en/regnPred', 's_regnPred3', 'en/regnPred', 'v_regnPred_c3');
addPage_2('en/regnPred', 'regnPred4', "Confidence and prediction intervals", 'interact', 'en/regnPred', 's_regnPred4', 'en/regnPred', 'v_regnPred4');
addSection('bk/business', 'sec_regnProblem', "Linear model assumptions");
addPage_2('en/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact', 'en/regnProblem', 's_regnProblem1', 'en/regnProblem', 'v_regnProblem1');
addPage_2('en/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact', 'en/regnProblem', 's_regnProblem2', 'en/regnProblem', 'v_regnProblem2');
addPage_2('en/regnProblem', 'regnProblem3', "Curvature and non-constant variance", 'interact', 'en/regnProblem', 's_regnProblem3', 'en/regnProblem', 'v_regnProblem3');
addPage_2('en/regnProblem', 'regnProblem_c4', "Transformations and prediction", 'interact', 'en/regnProblem', 's_regnProblem4', 'en/regnProblem', 'v_regnProblem_c4');
addPage_2('en/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact', 'en/regnProblem', 's_regnProblem5', 'en/regnProblem', 'v_regnProblem5');
addPage_2('en/regnProblem', 'regnProblem_c6', "Non-normal errors", 'interact', 'en/regnProblem', 's_regnProblem6', 'en/regnProblem', 'v_regnProblem_c6');
addPage_2('en/regnProblem', 'regnProblem7', "Correlated errors", 'interact', 'en/regnProblem', 's_regnProblem7', 'en/regnProblem', 'v_regnProblem7');

addChapter('bk/general', 'ch_independence', "Independence", null, 'v_ch_independence');
addSection('bk/business', 'sec_prob', "Probability and applications");
addPage_2('en/prob', 'prob_c1', "Joint probabilities", 'interact', 'en/prob', 's_prob_c1', 'en/prob', 'v_prob_c1');
addPage_2('en/prob', 'prob_c2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2', 'en/prob', 'v_prob_c2');
addPage_2('en/prob', 'prob3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3', 'en/prob', 'v_prob3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4', 'en/prob', 'v_prob4');
addPage_2('en/prob', 'prob_c5', "Calculations with probabilities", 'interact', 'en/prob', 's_prob_c5', 'en/prob', 'v_prob_c5');
addSection('bk/business', 'sec_indep', "Independence");
addPage_2('en/indep', 'indep_c1', "Association", 'static', 'en/indep', 's_indep_c1', 'en/indep', 'v_indep_c1');
addPage_2('en/indep', 'indep_c2', "Independence", 'static', 'en/indep', 's_indep_c2', 'en/indep', 'v_indep_c2');
addPage_2('en/indep', 'indep_c3', "Independence from samples", 'static', 'en/indep', 's_indep3', 'en/indep', 'v_indep_c3');
addPage_2('en/indep', 'indep_c4', "Testing for independence", 'interact', 'en/indep', 's_indep4', 'en/indep', 'v_indep_c4');
addPage_2('en/indep', 'indep5', "Chi-squared test statistic", 'interact', 'en/indep', 's_indep5', 'en/indep', 'v_indep5');
addPage_2('en/indep', 'indep6', "P-value for chi-squared test", 'interact', 'en/indep', 's_indep6', 'en/indep', 'v_indep6');
addPage_2('en/indep', 'indep_c7', "Examples", 'static', 'en/indep', 's_indep_c7', 'en/indep', 'v_indep_c7');
addPage_2('en/indep', 'indep_c8', "Comparing groups", 'static', 'en/indep', 's_indep_c8', 'en/indep', 'v_indep_c8');

var language = "en";
var logoGif = null;
var homeDir = "bk/business";
var versionGif = "images/castBusiness";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = "http://castAdmin2.massey.ac.nz/pdf/business";
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_c': 'Business', '_g': 'General', '_b': 'Biometric', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_c', '_g', '_b', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_c', '_g', '_a', '_b');
versions['structures2'] = new Array('_c', '_g', '_a', '_b');
versions['structures3'] = new Array('_c', '_g', '_o');
versions['structures4'] = new Array('_c', '_g', '_a');
versions['structures5'] = new Array('_c', '_g', '_b');
versions['structures6'] = new Array('_g', '_b');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_c', '_g');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay2'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay3'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay4'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay5'] = new Array('_c', '_g', '_a', '_b', '_m');
versions['valueDisplay6'] = new Array('_c', '_g', '_m');
versions['valueDisplay7'] = new Array('_c', '_g', '_m');
versions['displayInterp1'] = new Array('_c', '_g', '_b');
versions['displayInterp2'] = new Array('_c', '_g', '_b', '_m');
versions['displayInterp3'] = new Array('_c', '_g', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['displayInterp6'] = new Array('_c', '_g', '_b');
versions['density3'] = new Array('_c', '_g', '_m');
versions['density4'] = new Array('_c', '_g', '_b', '_m');
versions['density6'] = new Array('_c', '_g', '_b');
versions['density7'] = new Array('_c', '_g', '_b', '_m');
versions['density9'] = new Array('_c', '_g');
versions['density10'] = new Array('_c', '_g', '_m');
versions['density11'] = new Array('_c', '_g', '_b', '_m');
versions['boxPlot6'] = new Array('_c', '_g');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_c', '_g', '_b', '_m');
versions['centerSpread7'] = new Array('_c', '_g');
versions['transform1'] = new Array('_g', '_b');
versions['transform2'] = new Array('_c', '_g', '_b');
versions['transform3'] = new Array('_c', '_g');
versions['counts1'] = new Array('_c', '_g', '_b');
versions['counts2'] = new Array('_c', '_g', '_b');
versions['counts3'] = new Array('_c', '_g');
versions['counts4'] = new Array('_c', '_g', '_b');
versions['scatterplot1'] = new Array('_c', '_g', '_b');
versions['scatterplot2'] = new Array('_c', '_g');
versions['scatterplot4'] = new Array('_c', '_g');
versions['scatterplot5'] = new Array('_c', '_g');
versions['relationship1'] = new Array('_c', '_g');
versions['relationship3'] = new Array('_c', '_g');
versions['relationship4'] = new Array('_c', '_g');
versions['relationship5'] = new Array('_c', '_g');
versions['correlation1'] = new Array('_c', '_g', '_b');
versions['leastSqrs1'] = new Array('_c', '_g', '_b');
versions['leastSqrs3'] = new Array('_c', '_g');
versions['leastSqrs6'] = new Array('_c', '_g');
versions['leastSqrs7'] = new Array('_c', '_g');
versions['curvature1'] = new Array('_c', '_g');
versions['curvature2'] = new Array('_c', '_g');
versions['curvature3'] = new Array('_c', '_g');
versions['curvature4'] = new Array('_c', '_g');
versions['timePlot1'] = new Array('_c', '_g', '_b');
versions['timePlot2'] = new Array('_c', '_g', '_b');
versions['seasonal1'] = new Array('_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['seasonal5'] = new Array('_g', '_m', '_z');
versions['seasonal6'] = new Array('_g', '_m', '_z');
versions['freqTable1'] = new Array('_c', '_g');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_c', '_g', '_b');
versions['univarCat5'] = new Array('_c', '_g', '_b');
versions['univarCat6'] = new Array('_c', '_g', '_b');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('_c', '_g');
versions['groupedCat2'] = new Array('_c', '_g', '_b');
versions['groupedCat3'] = new Array('_c', '_g', '_b');
versions['groupedCat4'] = new Array('_c', '_g', '_b');
versions['groupedCat5'] = new Array('_c', '_g', '_b');
versions['bivarCat1'] = new Array('_c', '_g', '_b');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['logistic1'] = new Array('_c', '_g', '_b');
versions['logistic2'] = new Array('_c', '_g', '_b');
versions['logistic4'] = new Array('_c', '_g', '_b');
versions['multivariate1'] = new Array('_c', '_g', '_b');
versions['multivariate2'] = new Array('_c', '_g');
versions['multivariate3'] = new Array('_c', '_g');
versions['multivariate5'] = new Array('_c', '_g');
versions['regnGroups7'] = new Array('_c', '_g');
versions['lurking1'] = new Array('_c', '_g', '_b');
versions['lurking2'] = new Array('_g', '_b');
versions['lurking3'] = new Array('_c', '_g');
versions['popSamp1'] = new Array('_c', '_g', '_a', '_b');
versions['popSamp2'] = new Array('_c', '_g');
versions['popSamp3'] = new Array('_c', '_g', '_a', '_b');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_c', '_g', '_b');
versions['infPopn1'] = new Array('_c', '_g', '_b');
versions['infPopn2'] = new Array('_c', '_g', '_b', '_z');
versions['infPopn3'] = new Array('_c', '_g', '_b');
versions['infPopn5'] = new Array('_c', '_g');
versions['probDensity1'] = new Array('_g', '_b');
versions['probDensity2'] = new Array('_c', '_g', '_b');
versions['probDensity5'] = new Array('_c', '_g');
versions['probDensity7'] = new Array('_c', '_g');
versions['probSim4'] = new Array('_c', '_g', '_b');
versions['probSim6'] = new Array('_c', '_g');
versions['randomMean1'] = new Array('_c', '_g', '_b');
versions['randomMean6'] = new Array('_c', '_g', '_b');
versions['randomMean7'] = new Array('_g', '_b');
versions['normalDistn1'] = new Array('_c', '_g');
versions['normalDistn3'] = new Array('_c', '_g', '_b');
versions['normalDistn6'] = new Array('_c', '_g', '_b');
versions['normalDistn7'] = new Array('_c', '_g', '_b');
versions['randomPropn1'] = new Array('_c', '_g');
versions['randomPropn2'] = new Array('_c', '_g');
versions['randomPropn3'] = new Array('_c', '_g', '_b');
versions['randomPropn4'] = new Array('_c', '_g', '_b');
versions['randomPropn6'] = new Array('_c', '_g', '_b');
versions['sampPractice1'] = new Array('_g', '_b');
versions['sampPractice5'] = new Array('_c', '_g', '_b');
versions['sampPractice6'] = new Array('_g', '_b');
versions['causal1'] = new Array('_c', '_g', '_b');
versions['causal2'] = new Array('_c', '_g');
versions['causal3'] = new Array('_c', '_g', '_b');
versions['causal4'] = new Array('_c', '_g', '_b');
versions['causal5'] = new Array('_c', '_g');
versions['designIntro1'] = new Array('_c', '_g', '_b');
versions['designIntro2'] = new Array('_c', '_g');
versions['designIntro3'] = new Array('_c', '_g');
versions['designIntro4'] = new Array('_c', '_g');
versions['designIntro5'] = new Array('_c', '_g', '_b');
versions['designIntro7'] = new Array('_c', '_g');
versions['designPrelim2'] = new Array('_c', '_g');
versions['estIntro1'] = new Array('_c', '_g', '_b');
versions['estIntro2'] = new Array('_c', '_g', '_b');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_c', '_g', '_m');
versions['estIntro5'] = new Array('_c', '_g', '_b');
versions['seMean1'] = new Array('_c', '_g', '_b');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_c', '_g', '_b');
versions['seMean6'] = new Array('_c', '_g', '_b');
versions['ciMean1'] = new Array('_c', '_g', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_c', '_g', '_b');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_c', '_g', '_b');
versions['estPropn4'] = new Array('_c', '_g', '_b');
versions['estPropn5'] = new Array('_c', '_g', '_b');
versions['estPropn7'] = new Array('_c', '_g', '_b');
versions['ciExtra1'] = new Array('_c', '_g', '_b');
versions['ciExtra2'] = new Array('_c', '_g');
versions['ciExtra3'] = new Array('_g', '_b');
versions['estOther3'] = new Array('_c', '_g', '_m');
versions['estOther5'] = new Array('_g', '_b');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro3'] = new Array('_c', '_g', '_b');
versions['testIntro5'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_c', '_g', '_b');
versions['testPropn1'] = new Array('_c', '_g', '_b');
versions['testPropn2'] = new Array('_c', '_g', '_b');
versions['testPropn3'] = new Array('_c', '_g', '_b');
versions['testPropn4'] = new Array('_c', '_g', '_b');
versions['testPropn5'] = new Array('_g', '_b');
versions['testPropn7'] = new Array('_g', '_b');
versions['testMean1'] = new Array('_c', '_g');
versions['testMean2'] = new Array('_c', '_g');
versions['testMean3'] = new Array('_g', '_b');
versions['testMean4'] = new Array('_c', '_g');
versions['testMean5'] = new Array('_c', '_g');
versions['testPValue1'] = new Array('_c', '_g');
versions['testPValue2'] = new Array('_c', '_g', '_b');
versions['testPValue5'] = new Array('_c', '_g', '_b');
versions['twoGroupModel1'] = new Array('_c', '_g', '_b');
versions['twoGroupModel2'] = new Array('_c', '_g', '_b');
versions['twoGroupModel4'] = new Array('_c', '_g');
versions['twoGroupModel5'] = new Array('_c', '_g');
versions['twoGroupInf1'] = new Array('_c', '_g');
versions['twoGroupInf2'] = new Array('_c', '_g', '_b');
versions['twoGroupInf3'] = new Array('_c', '_g', '_b');
versions['twoGroupInf4'] = new Array('_c', '_g', '_b');
versions['twoGroupInf5'] = new Array('_c', '_g', '_b');
versions['twoGroupPropn1'] = new Array('_c', '_g');
versions['twoGroupPropn3'] = new Array('_c', '_g');
versions['twoGroupPropn4'] = new Array('_c', '_g');
versions['testPaired1'] = new Array('_c', '_g', '_b');
versions['testPaired2'] = new Array('_c', '_g', '_b');
versions['testPaired3'] = new Array('_c', '_g');
versions['multiGroup1'] = new Array('_c', '_g', '_b');
versions['multiGroup3'] = new Array('_c', '_g', '_b');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_c', '_g', '_a', '_b');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_c', '_g', '_b');
versions['regnModel1'] = new Array('_c', '_g', '_b');
versions['regnModel2'] = new Array('_c', '_g');
versions['regnModel5'] = new Array('_c', '_g', '_b');
versions['regnEst1'] = new Array('_c', '_g');
versions['regnEst2'] = new Array('_c', '_g');
versions['regnEst4'] = new Array('_c', '_g');
versions['regnEst5'] = new Array('_c', '_g');
versions['regnTest1'] = new Array('_c', '_g');
versions['regnTest2'] = new Array('_c', '_g');
versions['regnPred1'] = new Array('_c', '_g', '_b');
versions['regnPred3'] = new Array('_c', '_g', '_b');
versions['regnPred4'] = new Array('_g', '_b');
versions['regnProblem3'] = new Array('_g', '_b');
versions['regnProblem4'] = new Array('_c', '_g');
versions['regnProblem6'] = new Array('_c', '_g');
versions['prob1'] = new Array('_c', '_g', '_b');
versions['prob2'] = new Array('_c', '_g', '_b');
versions['prob3'] = new Array('_g', '_b');
versions['prob5'] = new Array('_c', '_g');
versions['indep1'] = new Array('_c', '_g', '_b');
versions['indep2'] = new Array('_c', '_g');
versions['indep3'] = new Array('_c', '_g');
versions['indep4'] = new Array('_c', '_g');
versions['indep7'] = new Array('_c', '_g');
versions['indep8'] = new Array('_c', '_g');

bookLoaded = true;
