
addBook('bk/climatic_c4', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/climatic_c4', 'ch_aboutReln', "About Relationships");
addSection('bk/biometric', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal_b1', "Interest in relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal_b1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2', 'en/causal', 'v_causal2');
addPage_2('en/causal', 'causal_b3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3', 'en/causal', 'v_causal_b3');
addPage_2('en/causal', 'causal_b4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4', 'en/causal', 'v_causal_b4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5', 'en/causal', 'v_causal5');
addSection('bk/biometric', 'sec_lurking', "Marginal relationships");
addPage_2('en/lurking', 'lurking_b1', "Misleading marginal correlation", 'interact', 'en/lurking', 's_lurking1', 'en/lurking', 'v_lurking_b1');
addPage_2('en/lurking', 'lurking_b2', "Misleading marginal difference in means", 'interact', 'en/lurking', 's_lurking2', 'en/lurking', 'v_lurking_b2');
addPage_2('en/lurking', 'lurking3', "Simpsons paradox", 'interact', 'en/lurking', 's_lurking3', 'en/lurking', 'v_lurking3');
addPage_2('en/lurking', 'lurking4', "Other examples with lurking variables", 'static', 'en/lurking', 's_lurking4', 'en/lurking', 'v_lurking4');

addChapter('bk/climatic_c4', 'ch_expDesign', "Designed Experiments");
addSection('bk/biometric', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'designIntro_b1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1', 'en/designIntro', 'v_designIntro_b1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2', 'en/designIntro', 'v_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3', 'en/designIntro', 'v_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4', 'en/designIntro', 'v_designIntro4');
addPage_2('en/designIntro', 'designIntro_b5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5', 'en/designIntro', 'v_designIntro_b5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6', 'en/designIntro', 'v_designIntro6');
addPage_2('en/designIntro', 'designIntro7', "Blocking", 'interact', 'en/designIntro', 's_designIntro7', 'en/designIntro', 'v_designIntro7');
addSection('bk/biometric', 'sec_pairBlock', "Pairing and blocks");
addPage_2('en/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact', 'en/pairBlock', 's_pairBlock1', 'en/pairBlock', 'v_pairBlock1');
addPage_2('en/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact', 'en/pairBlock', 's_pairBlock2', 'en/pairBlock', 'v_pairBlock2');
addPage_2('en/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact', 'en/pairBlock', 's_pairBlock3', 'en/pairBlock', 'v_pairBlock3');
addPage_2('en/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact', 'en/pairBlock', 's_pairBlock4', 'en/pairBlock', 'v_pairBlock4');
addPage_2('en/pairBlock', 'pairBlock_b5', "Randomised block experiments", 'static', 'en/pairBlock', 's_pairBlock5', 'en/pairBlock', 'v_pairBlock_b5');
addSection('bk/biometric', 'sec_designTwo', "Two or more factors");
addPage_2('en/designTwo', 'designTwo_b1', "Experiments with 2 factors", 'interact', 'en/designTwo', 's_designTwo1', 'en/designTwo', 'v_designTwo1');
addPage_2('en/designTwo', 'designTwo_b2', "Factorial design", 'static', 'en/designTwo', 's_designTwo2', 'en/designTwo', 'v_designTwo_b2');
addPage_2('en/designTwo', 'designTwo3', "Simple model for two factors", 'interact', 'en/designTwo', 's_designTwo3', 'en/designTwo', 'v_designTwo3');
addPage_2('en/designTwo', 'designTwo4', "Interaction between factors", 'interact', 'en/designTwo', 's_designTwo4', 'en/designTwo', 'v_designTwo4');
addPage_2('en/designTwo', 'designTwo5', "Example with interaction", 'interact', 'en/designTwo', 's_designTwo5', 'en/designTwo', 'v_designTwo5');
addPage_2('en/designTwo', 'designTwo_b6', "No-interaction model for three factors", 'interact', 'en/designTwo', 's_designTwo6', 'en/designTwo', 'v_designTwo_b6');
addPage_2('en/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact', 'en/designTwo', 's_designTwo7', 'en/designTwo', 'v_designTwo7');
addSection('bk/general', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1', 'en/designPrelim', 'v_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2', 'en/designPrelim', 'v_designPrelim2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3', 'en/designPrelim', 'v_designPrelim3');

addChapter('bk/climatic_c4', 'ch_twoMeans', "Comparing Two Means");
addSection('bk/biometric', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel_b1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel1', 'en/twoGroupModel', 'v_twoGroupModel_b1');
addPage_2('en/twoGroupModel', 'twoGroupModel_b2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2', 'en/twoGroupModel', 'v_twoGroupModel_b2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3', 'en/twoGroupModel', 'v_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4', 'en/twoGroupModel', 'v_twoGroupModel4');
addPage_2('en/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel5', 'en/twoGroupModel', 'v_twoGroupModel5');
addSection('bk/general', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'sumDiff1', "Means and sums of samples", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('en/sumDiff', 'sumDiff2', "Sum and difference", 'interact', 'en/sumDiff', 's_sumDiff2', 'en/sumDiff', 'v_sumDiff2');
addPage_2('en/sumDiff', 'sumDiff3', "Sum and difference (cont)", 'interact', 'en/sumDiff', 's_sumDiff3', 'en/sumDiff', 'v_sumDiff3');
addPage_2('en/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static', 'en/sumDiff', 's_sumDiff4', 'en/sumDiff', 'v_sumDiff4');
addSection('bk/climatic_c4', 'sec_ciDiff', "Confidence interval for difference");
addPage_2('en/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1', 'en/twoGroupInf', 'v_twoGroupInf1');
addPage_2('en/twoGroupInf', 'twoGroupInf_b2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf2', 'en/twoGroupInf', 'v_twoGroupInf_b2');
addPage_2('en/twoGroupInf', 'twoGroupInf_b3', "CI for difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf3', 'en/twoGroupInf', 'v_twoGroupInf_b3');
addSection('bk/climatic_c4', 'sec_testDiff', "Hypothesis test for difference");
addPage_2('en/twoGroupInf', 'twoGroupInf_b4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf4', 'en/twoGroupInf', 'v_twoGroupInf_b4');
addPage_2('en/twoGroupInf', 'twoGroupInf_b5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf5', 'en/twoGroupInf', 'v_twoGroupInf_b5');
addSection('bk/biometric', 'sec_testPaired', "Paired t test");
addPage_2('en/testPaired', 'testPaired_b1', "Paired data", 'static', 'en/testPaired', 's_testPaired1', 'en/testPaired', 'v_testPaired_b1');
addPage_2('en/testPaired', 'testPaired_b2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2', 'en/testPaired', 'v_testPaired_b2');
addPage_2('en/testPaired', 'testPaired3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3', 'en/testPaired', 'v_testPaired3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4', 'en/testPaired', 'v_testPaired4');

addChapter('bk/climatic_c4', 'ch_twoPropns', "Comparing Two Proportions");
addSection('bk/climatic_c4', 'sec_ciPropnDiff', "Confidence interval for difference");
addPage_2('en/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn1', 'en/twoGroupPropn', 'v_twoGroupPropn1');
addPage_2('en/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn2', 'en/twoGroupPropn', 'v_twoGroupPropn2');
addPage_2('en/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static', 'en/twoGroupPropn', 's_twoGroupPropn3', 'en/twoGroupPropn', 'v_twoGroupPropn3');
addSection('bk/climatic_c4', 'sec_testPropnDiff', "Hypothesis test for difference");
addPage_2('en/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static', 'en/twoGroupPropn', 's_twoGroupPropn4', 'en/twoGroupPropn', 'v_twoGroupPropn4');

addChapter('bk/climatic_c4', 'ch_manyMeans', "Comparing Many Means");
addSection('bk/climatic_c4', 'sec_commonSD', "Model with common SD");
addPage_2('en/multiGroup', 'multiGroup_b1', "Model", 'interact', 'en/multiGroup', 's_multiGroup1', 'en/multiGroup', 'v_multiGroup_b1');
addPage_2('en/multiGroup', 'multiGroup2', "Parameter estimates", 'interact', 'en/multiGroup', 's_multiGroup2', 'en/multiGroup', 'v_multiGroup2');
addSection('bk/climatic_c4', 'sec_ssqF', "Sums of squares and F test");
addPage_2('en/multiGroup', 'multiGroup_b3', "Revisiting two groups", 'static', 'en/multiGroup', 's_multiGroup3', 'en/multiGroup', 'v_multiGroup_b3');
addPage_2('en/multiGroup', 'multiGroup4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup_b6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup_b6', 'en/multiGroup', 'v_multiGroup_b6');
addPage_2('en/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addPage_2('en/multiGroup', 'multiGroup_b8', "Examples", 'static', 'en/multiGroup', 's_multiGroup_b8', 'en/multiGroup', 'v_multiGroup_b8');
addSection('bk/general', 'sec_randBlock', "Randomised blocks");
addPage_2('en/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static', 'en/randBlock', 's_randBlock1', 'en/randBlock', 'v_randBlock1');
addPage_2('en/randBlock', 'randBlock2', "Example with baseline treatment", 'interact', 'en/randBlock', 's_randBlock2', 'en/randBlock', 'v_randBlock2');
addPage_2('en/randBlock', 'randBlock3', "Use of blocking information", 'interact', 'en/randBlock', 's_randBlock3', 'en/randBlock', 'v_randBlock3');
addPage_2('en/randBlock', 'randBlock4', "Randomised block designs", 'interact', 'en/randBlock', 's_randBlock4', 'en/randBlock', 'v_randBlock4');
addPage_2('en/randBlock', 'randBlock5', "Model for randomised blocks", 'interact', 'en/randBlock', 's_randBlock5', 'en/randBlock', 'v_randBlock5');
addPage_2('en/randBlock', 'randBlock6', "Removing block effects", 'interact', 'en/randBlock', 's_randBlock6', 'en/randBlock', 'v_randBlock6');
addPage_2('en/randBlock', 'randBlock7', "Sums of squares", 'interact', 'en/randBlock', 's_randBlock7', 'en/randBlock', 'v_randBlock7');
addPage_2('en/randBlock', 'randBlock8', "Anova table and examples", 'static', 'en/randBlock', 's_randBlock8', 'en/randBlock', 'v_randBlock8');

addChapter('bk/climatic_c4', 'ch_regnModel', "Regression Models");
addSection('bk/biometric', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel_b1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel1', 'en/regnModel', 'v_regnModel_b1');
addPage_2('en/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact', 'en/regnModel', 's_regnModel2', 'en/regnModel', 'v_regnModel2');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3', 'en/regnModel', 'v_regnModel3');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4', 'en/regnModel', 'v_regnModel4');
addPage_2('en/regnModel', 'regnModel_b5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel5', 'en/regnModel', 'v_regnModel_b5');
addSection('bk/climatic_c4', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1', 'en/regnEst', 'v_regnEst1');
addPage_2('en/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2', 'en/regnEst', 'v_regnEst2');

addChapter('bk/climatic_c4', 'ch_regnInf', "Inference for Regression");
addSection('bk/general', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1', 'en/regnTest', 'v_regnTest1');
addPage_2('en/regnTest', 'regnTest2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest2', 'en/regnTest', 'v_regnTest2');
addPage_2('en/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3', 'en/regnTest', 'v_regnTest3');
addPage_2('en/regnTest', 'regnTest4', "Properties of p-values", 'interact', 'en/regnTest', 's_regnTest4', 'en/regnTest', 'v_regnTest4');
addSection('bk/biometric', 'sec_regnPred', "Predicting the response");
addPage_2('en/regnPred', 'regnPred_b1', "Estimated response distn at X", 'interact', 'en/regnPred', 's_regnPred1', 'en/regnPred', 'v_regnPred_b1');
addPage_2('en/regnPred', 'regnPred2', "Variability of estimate at X", 'interact', 'en/regnPred', 's_regnPred2', 'en/regnPred', 'v_regnPred2');
addPage_2('en/regnPred', 'regnPred_b3', "Estimating the mean vs prediction", 'interact', 'en/regnPred', 's_regnPred3', 'en/regnPred', 'v_regnPred_b3');
addPage_2('en/regnPred', 'regnPred_b4', "Confidence and prediction intervals", 'interact', 'en/regnPred', 's_regnPred4', 'en/regnPred', 'v_regnPred_b4');

addChapter('bk/climatic_c4', 'ch_advRegn', "Advanced Regression");
addSection('bk/biometric', 'sec_regnProblem', "Linear model assumptions");
addPage_2('en/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact', 'en/regnProblem', 's_regnProblem1', 'en/regnProblem', 'v_regnProblem1');
addPage_2('en/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact', 'en/regnProblem', 's_regnProblem2', 'en/regnProblem', 'v_regnProblem2');
addPage_2('en/regnProblem', 'regnProblem_b3', "Curvature and non-constant variance", 'interact', 'en/regnProblem', 's_regnProblem3', 'en/regnProblem', 'v_regnProblem_b3');
addPage_2('en/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact', 'en/regnProblem', 's_regnProblem4', 'en/regnProblem', 'v_regnProblem4');
addPage_2('en/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact', 'en/regnProblem', 's_regnProblem5', 'en/regnProblem', 'v_regnProblem5');
addPage_2('en/regnProblem', 'regnProblem6', "Non-normal errors", 'interact', 'en/regnProblem', 's_regnProblem6', 'en/regnProblem', 'v_regnProblem6');
addPage_2('en/regnProblem', 'regnProblem7', "Correlated errors", 'interact', 'en/regnProblem', 's_regnProblem7', 'en/regnProblem', 'v_regnProblem7');
addSection('bk/biometric', 'sec_logistic', "Logistic regression");
addPage_2('en/logistic', 'logistic_b1', "Categorical responses", 'interact', 'en/logistic', 's_logistic_b1', 'en/logistic', 'v_logistic_b1');
addPage_2('en/logistic', 'logistic_b2', "Fitted values and predictions", 'interact', 'en/logistic', 's_logistic2', 'en/logistic', 'v_logistic_b2');
addPage_2('en/logistic', 'logistic3', "Logistic curve", 'interact', 'en/logistic', 's_logistic3', 'en/logistic', 'v_logistic3');
addPage_2('en/logistic', 'logistic_b4', "Obtaining a good fit", 'interact', 'en/logistic', 's_logistic4', 'en/logistic', 'v_logistic_b4');

addChapter('bk/general', 'ch_independence', "Independence", null, 'v_ch_independence');
addSection('bk/climatic_c4', 'sec_prob', "Marginal & conditional probability");
addPage_2('en/prob', 'prob_b1', "Joint probabilities", 'interact', 'en/prob', 's_prob1', 'en/prob', 'v_prob_b1');
addPage_2('en/prob', 'prob_b2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2', 'en/prob', 'v_prob_b2');
addPage_2('en/prob', 'prob_b3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3', 'en/prob', 'v_prob_b3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4', 'en/prob', 'v_prob4');
addPage_2('en/prob', 'prob5', "Calculations with probabilities", 'interact', 'en/prob', 's_prob5', 'en/prob', 'v_prob5');
addSection('bk/climatic_c4', 'sec_indep', "Independence");
addPage_2('en/indep', 'indep_b1', "Association", 'static', 'en/indep', 's_indep1', 'en/indep', 'v_indep_b1');
addPage_2('en/indep', 'indep2', "Independence", 'static', 'en/indep', 's_indep2', 'en/indep', 'v_indep2');
addSection('bk/climatic_c4', 'sec_testIndep', "Testing for independence");
addPage_2('en/indep', 'indep3', "Independence from samples", 'static', 'en/indep', 's_indep3', 'en/indep', 'v_indep3');
addPage_2('en/indep', 'indep4', "Testing for independence", 'interact', 'en/indep', 's_indep4', 'en/indep', 'v_indep4');
addPage_2('en/indep', 'indep5', "Chi-squared test statistic", 'interact', 'en/indep', 's_indep5', 'en/indep', 'v_indep5');
addPage_2('en/indep', 'indep6', "P-value for chi-squared test", 'interact', 'en/indep', 's_indep6', 'en/indep', 'v_indep6');
addPage_2('en/indep', 'indep7', "Examples", 'static', 'en/indep', 's_indep7', 'en/indep', 'v_indep7');
addPage_2('en/indep', 'indep8', "Comparing groups", 'static', 'en/indep', 's_indep8', 'en/indep', 'v_indep8');

var language = "en";
var logoGif = null;
var homeDir = "bk/climatic_c4";
var versionGif = "images/castClimatic_c4";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "10";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_b': 'Biometric', '_g': 'General', '_c': 'Business', '_a': 'African'};
var versions = {};
versions['causal1'] = new Array('_b', '_g', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_b', '_g', '_c');
versions['causal4'] = new Array('_b', '_g', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_b', '_g', '_c');
versions['lurking2'] = new Array('_b', '_g');
versions['lurking3'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_b', '_g', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_b', '_g', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_b', '_g');
versions['designTwo1'] = new Array('_b', '_g');
versions['designTwo2'] = new Array('_b', '_g');
versions['designTwo6'] = new Array('_b', '_g');
versions['designPrelim2'] = new Array('_g', '_c');
versions['twoGroupModel1'] = new Array('_b', '_g', '_c');
versions['twoGroupModel2'] = new Array('_b', '_g', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_b', '_g', '_c');
versions['twoGroupInf3'] = new Array('_b', '_g', '_c');
versions['twoGroupInf4'] = new Array('_b', '_g', '_c');
versions['twoGroupInf5'] = new Array('_b', '_g', '_c');
versions['testPaired1'] = new Array('_b', '_g', '_c');
versions['testPaired2'] = new Array('_b', '_g', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_b', '_g', '_c');
versions['multiGroup3'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_b', '_g', '_a', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_b', '_g', '_c');
versions['regnModel1'] = new Array('_b', '_g', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_b', '_g', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_b', '_g', '_c');
versions['regnPred3'] = new Array('_b', '_g', '_c');
versions['regnPred4'] = new Array('_b', '_g');
versions['regnProblem3'] = new Array('_b', '_g');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['logistic1'] = new Array('_b', '_g', '_c');
versions['logistic2'] = new Array('_b', '_g', '_c');
versions['logistic4'] = new Array('_b', '_g', '_c');
versions['prob1'] = new Array('_b', '_g', '_c');
versions['prob2'] = new Array('_b', '_g', '_c');
versions['prob3'] = new Array('_b', '_g');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_b', '_g', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
