
addBook('bk/african_c2', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/african_c2', 'ch_modelVar', "Sampling and Variability");
addSection('bk/african_c2', 'sec_modelIntro', "Intro - generalising from data");
addPage_2('bk/african_c2', 'modelIntro1', "Data as representatives", 'interact');
addPage_2('bk/african_c2', 'modelIntro2', "Randomness of data", 'interact');
addPage_2('bk/african_c2', 'modelIntro3', "Modelling randomness", 'interact');
addPage_2('bk/african_c2', 'modelIntro4', "Introduction to the idea of inference", 'static');
addSection('bk/african_c2', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp_a1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp2');
addPage_2('en/popSamp', 'popSamp_a3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3', 'en/popSamp', 'v_popSamp3');
addPage_2('en/popSamp', 'popSamp_b4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4', 'en/popSamp', 'v_popSamp_b4');
addPage_2('en/popSamp', 'popSamp_b5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5', 'en/popSamp', 'v_popSamp_b5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addSection('bk/biometric', 'sec_infPopn', "Samples from distributions");
addPage_2('en/infPopn', 'infPopn_b1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn_b1', 'en/infPopn', 'v_infPopn_b1');
addPage_2('en/infPopn', 'infPopn_b2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2', 'en/infPopn', 'v_infPopn_b2');
addPage_2('en/infPopn', 'infPopn_b3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3', 'en/infPopn', 'v_infPopn_b3');
addPage_2('en/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact', 'en/infPopn', 's_infPopn4', 'en/infPopn', 'v_infPopn4');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5', 'en/infPopn', 'v_infPopn5');
addSection('bk/biometric', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity_b1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1', 'en/probDensity', 'v_probDensity_b1');
addPage_2('en/probDensity', 'probDensity_b2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2', 'en/probDensity', 'v_probDensity_b2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3', 'en/probDensity', 'v_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4', 'en/probDensity', 'v_probDensity4');
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5', 'en/probDensity', 'v_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6', 'en/probDensity', 'v_probDensity6');
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7', 'en/probDensity', 'v_probDensity7');
addSection('bk/biometric', 'sec_probSim', "Simulation (optional)");
addPage_2('en/probSim', 'probSim1', "Probability models and simulation", 'interact', 'en/probSim', 's_probSim1', 'en/probSim', 'v_probSim1');
addPage_2('en/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact', 'en/probSim', 's_probSim2', 'en/probSim', 'v_probSim2');
addPage_2('en/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact', 'en/probSim', 's_probSim3', 'en/probSim', 'v_probSim3');
addPage_2('en/probSim', 'probSim_b4', "Assessing unusual features in data", 'interact', 'en/probSim', 's_probSim4', 'en/probSim', 'v_probSim_b4');
addPage_2('en/probSim', 'probSim5', "Random numbers", 'interact', 'en/probSim', 's_probSim5', 'en/probSim', 'v_probSim5');
addPage_2('en/probSim', 'probSim6', "Generating categorical values", 'interact', 'en/probSim', 's_probSim6', 'en/probSim', 'v_probSim6');
addPage_2('en/probSim', 'probSim7', "Generating numerical values", 'interact', 'en/probSim', 's_probSim7', 'en/probSim', 'v_probSim7');

addChapter('bk/african_c2', 'ch_sampDistn', "Distributions");
addSection('bk/biometric', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_b1', "Variability of sample statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean_b1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/randomMean', 'randomMean_b6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean_b6', 'en/randomMean', 'v_randomMean_b6');
addPage_2('en/randomMean', 'randomMean_b7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7', 'en/randomMean', 'v_randomMean_b7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite populations", 'interact', 'en/randomMean', 's_randomMean8', 'en/randomMean', 'v_randomMean8');
addSection('bk/biometric', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1', 'en/normalDistn', 'v_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn_b3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn_b3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5', 'en/normalDistn', 'v_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn_b6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6', 'en/normalDistn', 'v_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn_b7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7', 'en/normalDistn', 'v_normalDistn_b7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8', 'en/normalDistn', 'v_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9', 'en/normalDistn', 'v_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10', 'en/normalDistn', 'v_normalDistn10');
addSection('bk/biometric', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1', 'en/randomPropn', 'v_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn_b3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn_b3');
addPage_2('en/randomPropn', 'randomPropn_b4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn_b4', 'en/randomPropn', 'v_randomPropn_b4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'en/randomPropn', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn_b6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn_b6', 'en/randomPropn', 'v_randomPropn_b6');

addChapter('bk/general', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/biometric', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro_b1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro_b1', 'en/estIntro', 'v_estIntro_b1');
addPage_2('en/estIntro', 'estIntro_b2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2', 'en/estIntro', 'v_estIntro_b2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3', 'en/estIntro', 'v_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4', 'en/estIntro', 'v_estIntro4');
addPage_2('en/estIntro', 'estIntro_b5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5', 'en/estIntro', 'v_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6', 'en/estIntro', 'v_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7', 'en/estIntro', 'v_estIntro7');
addSection('bk/general', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1', 'en/seMean', 'v_seMean1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2', 'en/seMean', 'v_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3', 'en/seMean', 'v_seMean3');
addPage_2('en/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean4', 'en/seMean', 'v_seMean4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addPage_2('en/seMean', 'seMean6', "Using SEs to compare estimators", 'interact', 'en/seMean', 's_seMean6', 'en/seMean', 'v_seMean6');
addPage_2('en/seMean', 'seMean7', "More about bias", 'interact', 'en/seMean', 's_seMean7', 'en/seMean', 'v_seMean7');
addSection('bk/african_c2', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean_m1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean1');
addPage_2('en/ciMean', 'ciMean_b2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2', 'en/ciMean', 'v_ciMean_b2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3', 'en/ciMean', 'v_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4', 'en/ciMean', 'v_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5', 'en/ciMean', 'v_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6', 'en/ciMean', 'v_ciMean6');
addPage_2('en/ciMean', 'ciMean_b7', "Examples", 'static', 'en/ciMean', 's_ciMean_b7', 'en/ciMean', 'v_ciMean_b7');
addSection('bk/biometric', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('en/estPropn', 'estPropn_b3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn_b3');
addPage_2('en/estPropn', 'estPropn_b4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4', 'en/estPropn', 'v_estPropn_b4');
addPage_2('en/estPropn', 'estPropn_b5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5', 'en/estPropn', 'v_estPropn_b5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('en/estPropn', 'estPropn_b7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7', 'en/estPropn', 'v_estPropn_b7');
addSection('bk/african_c2', 'sec_estOther', "Simulation and bootstrap");
addPage_2('en/estOther', 'estOther1', "Need for simulation", 'static', 'en/estOther', 's_estOther1', 'en/estOther', 'v_estOther1');
addPage_2('en/estOther', 'estOther2', "Error distribution by simulation", 'interact', 'en/estOther', 's_estOther2', 'en/estOther', 'v_estOther2');
addPage_2('en/estOther', 'estOther_m3', "Simulations with normal distns", 'interact', 'en/estOther', 's_estOther3', 'en/estOther', 'v_estOther3');
addPage_2('en/estOther', 'estOther4', "Bootstrap error distribution", 'interact', 'en/estOther', 's_estOther4', 'en/estOther', 'v_estOther4');
addPage_2('en/estOther', 'estOther5', "Standard error of correlation", 'interact', 'en/estOther', 's_estOther5', 'en/estOther', 'v_estOther5');
addPage_2('en/estOther', 'estOther_m6', "CIs from simulation", 'interact', 'en/estOther', 's_estOther6');

addChapter('bk/african_c2', 'ch_sampSurv', "Sample Surveys");
addSection('bk/african_c2', 'sec_sampSchemes', "Sampling schemes");
addPage_2('en/sampPractice', 'sampPractice_b1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1', 'en/sampPractice', 'v_sampPractice_b1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2', 'en/sampPractice', 'v_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3', 'en/sampPractice', 'v_sampPractice3');
addSection('bk/african_c2', 'sec_sampErr', "Sampling & non-sampling errors");
addPage_2('en/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4', 'en/sampPractice', 'v_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice_b5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5', 'en/sampPractice', 'v_sampPractice_b5');
addPage_2('en/sampPractice', 'sampPractice_b6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6', 'en/sampPractice', 'v_sampPractice_b6');
addSection('bk/african_c2', 'sec_survey', "Conducting a sample survey");
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7', 'en/sampPractice', 'v_sampPractice7');
addSection('bk/african_c2', 'sec_sampSize', "Sample size");
addPage_2('en/ciExtra', 'ciExtra_b1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1', 'en/ciExtra', 'v_ciExtra_b1');
addPage_2('en/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2', 'en/ciExtra', 'v_ciExtra2');
addPage_2('en/ciExtra', 'ciExtra_b3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3', 'en/ciExtra', 'v_ciExtra_b3');

addChapter('bk/african_c2', 'ch_testProp', "Testing a Proportion");
addSection('bk/biometric', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro_b1', "Inference", 'static', 'en/testIntro', 's_testIntro1', 'en/testIntro', 'v_testIntro_b1');
addPage_2('en/testIntro', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2', 'en/testIntro', 'v_testIntro2');
addPage_2('en/testIntro', 'testIntro_b3', "Simulation to test a proportion", 'interact', 'en/testIntro', 's_testIntro3', 'en/testIntro', 'v_testIntro_b3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4', 'en/testIntro', 'v_testIntro4');
addPage_2('en/testIntro', 'testIntro_b5', "Randomisation tests", 'interact', 'en/testIntro', 's_testIntro5', 'en/testIntro', 'v_testIntro_b5');
addPage_2('en/testIntro', 'testIntro6', "Randomisation test for correlation", 'interact', 'en/testIntro', 's_testIntro6', 'en/testIntro', 'v_testIntro6');
addPage_2('en/testIntro', 'testIntro_b7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7', 'en/testIntro', 'v_testIntro_b7');
addSection('bk/biometric', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'testPropn_b1', "Inference about parameters", 'static', 'en/testPropn', 's_testPropn1', 'en/testPropn', 'v_testPropn_b1');
addPage_2('en/testPropn', 'testPropn_b2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2', 'en/testPropn', 'v_testPropn_b2');
addPage_2('en/testPropn', 'testPropn_b3', "Another example", 'interact', 'en/testPropn', 's_testPropn_b3', 'en/testPropn', 'v_testPropn_b3');
addPage_2('en/testPropn', 'testPropn_b4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn4', 'en/testPropn', 'v_testPropn4');
addPage_2('en/testPropn', 'testPropn_b5', "Normal approximation", 'interact', 'en/testPropn', 's_testPropn_b5', 'en/testPropn', 'v_testPropn_b5');
addPage_2('en/testPropn', 'testPropn6', "Statistical distance", 'static', 'en/testPropn', 's_testPropn6', 'en/testPropn', 'v_testPropn6');
addPage_2('en/testPropn', 'testPropn_b7', "Tests based on statistical distance", 'interact', 'en/testPropn', 's_testPropn_b7', 'en/testPropn', 'v_testPropn_b7');

addChapter('bk/african_c2', 'ch_testMean', "Testing a Mean");
addSection('bk/biometric', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean1', "Introduction", 'static', 'en/testMean', 's_testMean1', 'en/testMean', 'v_testMean1');
addPage_2('en/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2', 'en/testMean', 'v_testMean2');
addPage_2('en/testMean', 'testMean_b3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3', 'en/testMean', 'v_testMean_b3');
addPage_2('en/testMean', 'testMean4', "The t distribution", 'interact', 'en/testMean', 's_testMean4', 'en/testMean', 'v_testMean4');
addPage_2('en/testMean', 'testMean5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5', 'en/testMean', 'v_testMean5');
addSection('bk/biometric', 'sec_testPValue', "Properties of p-values");
addPage_2('en/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact', 'en/testPValue', 's_testPValue1', 'en/testPValue', 'v_testPValue1');
addPage_2('en/testPValue', 'testPValue_b2', "Consistency with null hypothesis", 'interact', 'en/testPValue', 's_testPValue2', 'en/testPValue', 'v_testPValue_b2');
addPage_2('en/testPValue', 'testPValue3', "Distribution of p-values", 'interact', 'en/testPValue', 's_testPValue3', 'en/testPValue', 'v_testPValue3');
addPage_2('en/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact', 'en/testPValue', 's_testPValue4', 'en/testPValue', 'v_testPValue4');
addPage_2('en/testPValue', 'testPValue_b5', "P-values for other tests", 'interact', 'en/testPValue', 's_testPValue5', 'en/testPValue', 'v_testPValue_b5');

addChapter('bk/african_c2', 'ch_aboutReln', "About Relationships");
addSection('bk/biometric', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal_b1', "Interest in relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal_b1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2', 'en/causal', 'v_causal2');
addPage_2('en/causal', 'causal_b3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3', 'en/causal', 'v_causal_b3');
addPage_2('en/causal', 'causal_b4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4', 'en/causal', 'v_causal_b4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5', 'en/causal', 'v_causal5');
addSection('bk/biometric', 'sec_lurking', "Marginal relationships");
addPage_2('en/lurking', 'lurking_b1', "Misleading marginal correlation", 'interact', 'en/lurking', 's_lurking1', 'en/lurking', 'v_lurking_b1');
addPage_2('en/lurking', 'lurking_b2', "Misleading marginal difference in means", 'interact', 'en/lurking', 's_lurking2', 'en/lurking', 'v_lurking_b2');
addPage_2('en/lurking', 'lurking3', "Simpsons paradox", 'interact', 'en/lurking', 's_lurking3', 'en/lurking', 'v_lurking3');
addPage_2('en/lurking', 'lurking4', "Other examples with lurking variables", 'static', 'en/lurking', 's_lurking4', 'en/lurking', 'v_lurking4');

addChapter('bk/african_c2', 'ch_expDesign', "Designed Experiments");
addSection('bk/biometric', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'designIntro_b1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1', 'en/designIntro', 'v_designIntro_b1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2', 'en/designIntro', 'v_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3', 'en/designIntro', 'v_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4', 'en/designIntro', 'v_designIntro4');
addPage_2('en/designIntro', 'designIntro_b5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5', 'en/designIntro', 'v_designIntro_b5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6', 'en/designIntro', 'v_designIntro6');
addPage_2('en/designIntro', 'designIntro7', "Blocking", 'interact', 'en/designIntro', 's_designIntro7', 'en/designIntro', 'v_designIntro7');
addSection('bk/biometric', 'sec_pairBlock', "Pairing and blocks");
addPage_2('en/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact', 'en/pairBlock', 's_pairBlock1', 'en/pairBlock', 'v_pairBlock1');
addPage_2('en/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact', 'en/pairBlock', 's_pairBlock2', 'en/pairBlock', 'v_pairBlock2');
addPage_2('en/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact', 'en/pairBlock', 's_pairBlock3', 'en/pairBlock', 'v_pairBlock3');
addPage_2('en/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact', 'en/pairBlock', 's_pairBlock4', 'en/pairBlock', 'v_pairBlock4');
addPage_2('en/pairBlock', 'pairBlock_b5', "Randomised block experiments", 'static', 'en/pairBlock', 's_pairBlock5', 'en/pairBlock', 'v_pairBlock_b5');
addSection('bk/biometric', 'sec_designTwo', "Two or more factors");
addPage_2('en/designTwo', 'designTwo_b1', "Experiments with 2 factors", 'interact', 'en/designTwo', 's_designTwo1', 'en/designTwo', 'v_designTwo1');
addPage_2('en/designTwo', 'designTwo_b2', "Factorial design", 'static', 'en/designTwo', 's_designTwo2', 'en/designTwo', 'v_designTwo_b2');
addPage_2('en/designTwo', 'designTwo3', "Simple model for two factors", 'interact', 'en/designTwo', 's_designTwo3', 'en/designTwo', 'v_designTwo3');
addPage_2('en/designTwo', 'designTwo4', "Interaction between factors", 'interact', 'en/designTwo', 's_designTwo4', 'en/designTwo', 'v_designTwo4');
addPage_2('en/designTwo', 'designTwo5', "Example with interaction", 'interact', 'en/designTwo', 's_designTwo5', 'en/designTwo', 'v_designTwo5');
addPage_2('en/designTwo', 'designTwo_b6', "No-interaction model for three factors", 'interact', 'en/designTwo', 's_designTwo6', 'en/designTwo', 'v_designTwo_b6');
addPage_2('en/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact', 'en/designTwo', 's_designTwo7', 'en/designTwo', 'v_designTwo7');
addSection('bk/general', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1', 'en/designPrelim', 'v_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2', 'en/designPrelim', 'v_designPrelim2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3', 'en/designPrelim', 'v_designPrelim3');

addChapter('bk/african_c2', 'ch_twoMeans', "Comparing Two Means");
addSection('bk/biometric', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel_b1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel1', 'en/twoGroupModel', 'v_twoGroupModel_b1');
addPage_2('en/twoGroupModel', 'twoGroupModel_b2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2', 'en/twoGroupModel', 'v_twoGroupModel_b2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3', 'en/twoGroupModel', 'v_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4', 'en/twoGroupModel', 'v_twoGroupModel4');
addPage_2('en/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel5', 'en/twoGroupModel', 'v_twoGroupModel5');
addSection('bk/general', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'sumDiff1', "Means and sums of samples", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('en/sumDiff', 'sumDiff2', "Sum and difference", 'interact', 'en/sumDiff', 's_sumDiff2', 'en/sumDiff', 'v_sumDiff2');
addPage_2('en/sumDiff', 'sumDiff3', "Sum and difference (cont)", 'interact', 'en/sumDiff', 's_sumDiff3', 'en/sumDiff', 'v_sumDiff3');
addPage_2('en/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static', 'en/sumDiff', 's_sumDiff4', 'en/sumDiff', 'v_sumDiff4');
addSection('bk/african_c2', 'sec_ciDiff', "Confidence interval for difference");
addPage_2('en/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1', 'en/twoGroupInf', 'v_twoGroupInf1');
addPage_2('en/twoGroupInf', 'twoGroupInf_b2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf2', 'en/twoGroupInf', 'v_twoGroupInf_b2');
addPage_2('en/twoGroupInf', 'twoGroupInf_b3', "CI for difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf3', 'en/twoGroupInf', 'v_twoGroupInf_b3');
addSection('bk/african_c2', 'sec_testDiff', "Hypothesis test for difference");
addPage_2('en/twoGroupInf', 'twoGroupInf_b4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf4', 'en/twoGroupInf', 'v_twoGroupInf_b4');
addPage_2('en/twoGroupInf', 'twoGroupInf_b5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf5', 'en/twoGroupInf', 'v_twoGroupInf_b5');
addSection('bk/biometric', 'sec_testPaired', "Paired t test");
addPage_2('en/testPaired', 'testPaired_b1', "Paired data", 'static', 'en/testPaired', 's_testPaired1', 'en/testPaired', 'v_testPaired_b1');
addPage_2('en/testPaired', 'testPaired_b2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2', 'en/testPaired', 'v_testPaired_b2');
addPage_2('en/testPaired', 'testPaired3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3', 'en/testPaired', 'v_testPaired3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4', 'en/testPaired', 'v_testPaired4');

addChapter('bk/african_c2', 'ch_twoPropns', "Comparing Two Proportions");
addSection('bk/african_c2', 'sec_ciPropnDiff', "Confidence interval for difference");
addPage_2('en/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn1', 'en/twoGroupPropn', 'v_twoGroupPropn1');
addPage_2('en/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn2', 'en/twoGroupPropn', 'v_twoGroupPropn2');
addPage_2('en/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static', 'en/twoGroupPropn', 's_twoGroupPropn3', 'en/twoGroupPropn', 'v_twoGroupPropn3');
addSection('bk/african_c2', 'sec_testPropnDiff', "Hypothesis test for difference");
addPage_2('en/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static', 'en/twoGroupPropn', 's_twoGroupPropn4', 'en/twoGroupPropn', 'v_twoGroupPropn4');

addChapter('bk/african_c2', 'ch_manyMeans', "Comparing Many Means");
addSection('bk/african_c2', 'sec_commonSD', "Model with common SD");
addPage_2('en/multiGroup', 'multiGroup_b1', "Model", 'interact', 'en/multiGroup', 's_multiGroup1', 'en/multiGroup', 'v_multiGroup_b1');
addPage_2('en/multiGroup', 'multiGroup2', "Parameter estimates", 'interact', 'en/multiGroup', 's_multiGroup2', 'en/multiGroup', 'v_multiGroup2');
addSection('bk/african_c2', 'sec_ssqF', "Sums of squares and F test");
addPage_2('en/multiGroup', 'multiGroup_b3', "Revisiting two groups", 'static', 'en/multiGroup', 's_multiGroup3', 'en/multiGroup', 'v_multiGroup_b3');
addPage_2('en/multiGroup', 'multiGroup4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup_b6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup_b6', 'en/multiGroup', 'v_multiGroup_b6');
addPage_2('en/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addPage_2('en/multiGroup', 'multiGroup_b8', "Examples", 'static', 'en/multiGroup', 's_multiGroup_b8', 'en/multiGroup', 'v_multiGroup_b8');
addSection('bk/general', 'sec_randBlock', "Randomised blocks");
addPage_2('en/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static', 'en/randBlock', 's_randBlock1', 'en/randBlock', 'v_randBlock1');
addPage_2('en/randBlock', 'randBlock2', "Example with baseline treatment", 'interact', 'en/randBlock', 's_randBlock2', 'en/randBlock', 'v_randBlock2');
addPage_2('en/randBlock', 'randBlock3', "Use of blocking information", 'interact', 'en/randBlock', 's_randBlock3', 'en/randBlock', 'v_randBlock3');
addPage_2('en/randBlock', 'randBlock4', "Randomised block designs", 'interact', 'en/randBlock', 's_randBlock4', 'en/randBlock', 'v_randBlock4');
addPage_2('en/randBlock', 'randBlock5', "Model for randomised blocks", 'interact', 'en/randBlock', 's_randBlock5', 'en/randBlock', 'v_randBlock5');
addPage_2('en/randBlock', 'randBlock6', "Removing block effects", 'interact', 'en/randBlock', 's_randBlock6', 'en/randBlock', 'v_randBlock6');
addPage_2('en/randBlock', 'randBlock7', "Sums of squares", 'interact', 'en/randBlock', 's_randBlock7', 'en/randBlock', 'v_randBlock7');
addPage_2('en/randBlock', 'randBlock8', "Anova table and examples", 'static', 'en/randBlock', 's_randBlock8', 'en/randBlock', 'v_randBlock8');

addChapter('bk/african_c2', 'ch_regnModel', "Regression Models");
addSection('bk/biometric', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel_b1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel1', 'en/regnModel', 'v_regnModel_b1');
addPage_2('en/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact', 'en/regnModel', 's_regnModel2', 'en/regnModel', 'v_regnModel2');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3', 'en/regnModel', 'v_regnModel3');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4', 'en/regnModel', 'v_regnModel4');
addPage_2('en/regnModel', 'regnModel_b5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel5', 'en/regnModel', 'v_regnModel_b5');
addSection('bk/african_c2', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1', 'en/regnEst', 'v_regnEst1');
addPage_2('en/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2', 'en/regnEst', 'v_regnEst2');

addChapter('bk/african_c2', 'ch_regnInf', "Inference for Regression");
addSection('bk/african_c2', 'sec_regnCi', "Confidence intervals");
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3', 'en/regnEst', 'v_regnEst3');
addPage_2('en/regnEst', 'regnEst4', "Standard error of least squares slope", 'static', 'en/regnEst', 's_regnEst4', 'en/regnEst', 'v_regnEst4');
addPage_2('en/regnEst', 'regnEst5', "95% confidence interval for slope", 'static', 'en/regnEst', 's_regnEst5', 'en/regnEst', 'v_regnEst5');
addPage_2('en/regnEst', 'regnEst6', "Properties of confidence interval", 'interact', 'en/regnEst', 's_regnEst6', 'en/regnEst', 'v_regnEst6');
addPage_2('en/regnEst', 'regnEst7', "Influences on accuracy", 'interact', 'en/regnEst', 's_regnEst7', 'en/regnEst', 'v_regnEst7');
addSection('bk/general', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1', 'en/regnTest', 'v_regnTest1');
addPage_2('en/regnTest', 'regnTest2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest2', 'en/regnTest', 'v_regnTest2');
addPage_2('en/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3', 'en/regnTest', 'v_regnTest3');
addPage_2('en/regnTest', 'regnTest4', "Properties of p-values", 'interact', 'en/regnTest', 's_regnTest4', 'en/regnTest', 'v_regnTest4');
addSection('bk/biometric', 'sec_regnPred', "Predicting the response");
addPage_2('en/regnPred', 'regnPred_b1', "Estimated response distn at X", 'interact', 'en/regnPred', 's_regnPred1', 'en/regnPred', 'v_regnPred_b1');
addPage_2('en/regnPred', 'regnPred2', "Variability of estimate at X", 'interact', 'en/regnPred', 's_regnPred2', 'en/regnPred', 'v_regnPred2');
addPage_2('en/regnPred', 'regnPred_b3', "Estimating the mean vs prediction", 'interact', 'en/regnPred', 's_regnPred3', 'en/regnPred', 'v_regnPred_b3');
addPage_2('en/regnPred', 'regnPred_b4', "Confidence and prediction intervals", 'interact', 'en/regnPred', 's_regnPred4', 'en/regnPred', 'v_regnPred_b4');

addChapter('bk/african_c2', 'ch_advRegn', "Advanced Regression");
addSection('bk/biometric', 'sec_regnProblem', "Linear model assumptions");
addPage_2('en/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact', 'en/regnProblem', 's_regnProblem1', 'en/regnProblem', 'v_regnProblem1');
addPage_2('en/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact', 'en/regnProblem', 's_regnProblem2', 'en/regnProblem', 'v_regnProblem2');
addPage_2('en/regnProblem', 'regnProblem_b3', "Curvature and non-constant variance", 'interact', 'en/regnProblem', 's_regnProblem3', 'en/regnProblem', 'v_regnProblem_b3');
addPage_2('en/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact', 'en/regnProblem', 's_regnProblem4', 'en/regnProblem', 'v_regnProblem4');
addPage_2('en/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact', 'en/regnProblem', 's_regnProblem5', 'en/regnProblem', 'v_regnProblem5');
addPage_2('en/regnProblem', 'regnProblem6', "Non-normal errors", 'interact', 'en/regnProblem', 's_regnProblem6', 'en/regnProblem', 'v_regnProblem6');
addPage_2('en/regnProblem', 'regnProblem7', "Correlated errors", 'interact', 'en/regnProblem', 's_regnProblem7', 'en/regnProblem', 'v_regnProblem7');
addSection('bk/biometric', 'sec_logistic', "Logistic regression");
addPage_2('en/logistic', 'logistic_b1', "Categorical responses", 'interact', 'en/logistic', 's_logistic_b1', 'en/logistic', 'v_logistic_b1');
addPage_2('en/logistic', 'logistic_b2', "Fitted values and predictions", 'interact', 'en/logistic', 's_logistic2', 'en/logistic', 'v_logistic_b2');
addPage_2('en/logistic', 'logistic3', "Logistic curve", 'interact', 'en/logistic', 's_logistic3', 'en/logistic', 'v_logistic3');
addPage_2('en/logistic', 'logistic_b4', "Obtaining a good fit", 'interact', 'en/logistic', 's_logistic4', 'en/logistic', 'v_logistic_b4');

addChapter('bk/general', 'ch_independence', "Independence", null, 'v_ch_independence');
addSection('bk/african_c2', 'sec_prob', "Marginal & conditional probability");
addPage_2('en/prob', 'prob_b1', "Joint probabilities", 'interact', 'en/prob', 's_prob1', 'en/prob', 'v_prob_b1');
addPage_2('en/prob', 'prob_b2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2', 'en/prob', 'v_prob_b2');
addPage_2('en/prob', 'prob_b3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3', 'en/prob', 'v_prob_b3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4', 'en/prob', 'v_prob4');
addPage_2('en/prob', 'prob5', "Calculations with probabilities", 'interact', 'en/prob', 's_prob5', 'en/prob', 'v_prob5');
addSection('bk/african_c2', 'sec_indep', "Independence");
addPage_2('en/indep', 'indep_b1', "Association", 'static', 'en/indep', 's_indep1', 'en/indep', 'v_indep_b1');
addPage_2('en/indep', 'indep2', "Independence", 'static', 'en/indep', 's_indep2', 'en/indep', 'v_indep2');
addSection('bk/african_c2', 'sec_testIndep', "Testing for independence");
addPage_2('en/indep', 'indep3', "Independence from samples", 'static', 'en/indep', 's_indep3', 'en/indep', 'v_indep3');
addPage_2('en/indep', 'indep4', "Testing for independence", 'interact', 'en/indep', 's_indep4', 'en/indep', 'v_indep4');
addPage_2('en/indep', 'indep5', "Chi-squared test statistic", 'interact', 'en/indep', 's_indep5', 'en/indep', 'v_indep5');
addPage_2('en/indep', 'indep6', "P-value for chi-squared test", 'interact', 'en/indep', 's_indep6', 'en/indep', 'v_indep6');
addPage_2('en/indep', 'indep7', "Examples", 'static', 'en/indep', 's_indep7', 'en/indep', 'v_indep7');
addPage_2('en/indep', 'indep8', "Comparing groups", 'static', 'en/indep', 's_indep8', 'en/indep', 'v_indep8');

var language = "en";
var logoGif = null;
var homeDir = "bk/african_c2";
var versionGif = "images/castAfrica_c2";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "16";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_a': 'African', '_g': 'General', '_b': 'Biometric', '_c': 'Business', '_z': 'Other', '_m': 'Climatic'};
var versions = {};
versions['popSamp1'] = new Array('_a', '_g', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_a', '_g', '_b', '_c');
versions['popSamp4'] = new Array('_b', '_g');
versions['popSamp5'] = new Array('_b', '_g', '_c');
versions['infPopn1'] = new Array('_b', '_g', '_c');
versions['infPopn2'] = new Array('_b', '_g', '_c', '_z');
versions['infPopn3'] = new Array('_b', '_g', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_b', '_g');
versions['probDensity2'] = new Array('_b', '_g', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_b', '_g', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_b', '_g', '_c');
versions['randomMean6'] = new Array('_b', '_g', '_c');
versions['randomMean7'] = new Array('_b', '_g');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_b', '_g', '_c');
versions['normalDistn6'] = new Array('_b', '_g', '_c');
versions['normalDistn7'] = new Array('_b', '_g', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_b', '_g', '_c');
versions['randomPropn4'] = new Array('_b', '_g', '_c');
versions['randomPropn6'] = new Array('_b', '_g', '_c');
versions['estIntro1'] = new Array('_b', '_g', '_c');
versions['estIntro2'] = new Array('_b', '_g', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_b', '_g', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_m', '_g', '_c');
versions['ciMean2'] = new Array('_b', '_g');
versions['ciMean7'] = new Array('_b', '_g', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_b', '_g', '_c');
versions['estPropn4'] = new Array('_b', '_g', '_c');
versions['estPropn5'] = new Array('_b', '_g', '_c');
versions['estPropn7'] = new Array('_b', '_g', '_c');
versions['estOther3'] = new Array('_m', '_g', '_c');
versions['estOther5'] = new Array('_g', '_b');
versions['estOther6'] = new Array('_m', '_g', '_c');
versions['sampPractice1'] = new Array('_b', '_g');
versions['sampPractice5'] = new Array('_b', '_g', '_c');
versions['sampPractice6'] = new Array('_b', '_g');
versions['ciExtra1'] = new Array('_b', '_g', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_b', '_g');
versions['testIntro1'] = new Array('_b', '_g');
versions['testIntro3'] = new Array('_b', '_g', '_c');
versions['testIntro5'] = new Array('_b', '_g');
versions['testIntro7'] = new Array('_b', '_g', '_c');
versions['testPropn1'] = new Array('_b', '_g', '_c');
versions['testPropn2'] = new Array('_b', '_g', '_c');
versions['testPropn3'] = new Array('_b', '_g', '_c');
versions['testPropn4'] = new Array('_b', '_g', '_c');
versions['testPropn5'] = new Array('_b', '_g');
versions['testPropn7'] = new Array('_b', '_g');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean2'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_b', '_g');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_b', '_g', '_c');
versions['testPValue5'] = new Array('_b', '_g', '_c');
versions['causal1'] = new Array('_b', '_g', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_b', '_g', '_c');
versions['causal4'] = new Array('_b', '_g', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_b', '_g', '_c');
versions['lurking2'] = new Array('_b', '_g');
versions['lurking3'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_b', '_g', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_b', '_g', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_b', '_g');
versions['designTwo1'] = new Array('_b', '_g');
versions['designTwo2'] = new Array('_b', '_g');
versions['designTwo6'] = new Array('_b', '_g');
versions['designPrelim2'] = new Array('_g', '_c');
versions['twoGroupModel1'] = new Array('_b', '_g', '_c');
versions['twoGroupModel2'] = new Array('_b', '_g', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_b', '_g', '_c');
versions['twoGroupInf3'] = new Array('_b', '_g', '_c');
versions['twoGroupInf4'] = new Array('_b', '_g', '_c');
versions['twoGroupInf5'] = new Array('_b', '_g', '_c');
versions['testPaired1'] = new Array('_b', '_g', '_c');
versions['testPaired2'] = new Array('_b', '_g', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_b', '_g', '_c');
versions['multiGroup3'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_b', '_g', '_a', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_b', '_g', '_c');
versions['regnModel1'] = new Array('_b', '_g', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_b', '_g', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_b', '_g', '_c');
versions['regnPred3'] = new Array('_b', '_g', '_c');
versions['regnPred4'] = new Array('_b', '_g');
versions['regnProblem3'] = new Array('_b', '_g');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['logistic1'] = new Array('_b', '_g', '_c');
versions['logistic2'] = new Array('_b', '_g', '_c');
versions['logistic4'] = new Array('_b', '_g', '_c');
versions['prob1'] = new Array('_b', '_g', '_c');
versions['prob2'] = new Array('_b', '_g', '_c');
versions['prob3'] = new Array('_b', '_g');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_b', '_g', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
