
addBook('bk/fr_esiac', 'book_splash', "À propos de ce e-book CAST");

addChapter('bk/french', 'ch_preface', "Pr&eacute;face");
addSection('bk/french', 'sec_aboutCast', "A propos de CAST");
addPage_2('fr/aboutCast', 'aboutCast1', "Qu'est-ce que CAST?", 'static');
addPage_2('fr/aboutCast', 'aboutCast2', "Structure et navigation", 'static');
addPage_2('fr/aboutCast', 'aboutCast3', "Droit d'auteur et de licence", 'static');
addPage_2('fr/aboutCast', 'aboutCast4', "Remerciements", 'static');
addPage_2('fr/aboutCast', 'aboutCast5', "A propos de l'auteur", 'static');
addSection('bk/french', 'sec_otherInfo', " Autre information");
addPage_2('fr/otherInfo', 'otherInfo1', " Navigateurs et Java", 'static');
addPage_2('fr/otherInfo', 'otherInfo2', " Problèmes?", 'static');
addPage_2('fr/otherInfo', 'otherInfo3', " Impression", 'static');
addPage_2('fr/otherInfo', 'otherInfo4', "Modifications récentes aux CAST", 'static');
addPage_2('fr/otherInfo', 'otherInfo5', "Développements futurs possibles", 'static');

addChapter('bk/fr_esiac', 'ch_intro', "Introduction: À propos des données");
addSection('bk/fr_esiac', 'sec_context', "Contexte et processus statistique");
addPage_2('fr/context', 'context_m1', "Importance of context", 'static', 'en/context', 's_context1', 'en/context', 'v_context1');
addPage_2('fr/context', 'context_m2', "Statistics", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('fr/context', 'context_b3', "The statistical process", 'static', 'en/context', 's_context3', 'en/context', 'v_context_b3');
addSection('bk/fr_esiac', 'sec_structures', "Structures de données standard");
addPage_2('fr/structures', 'structures_a1', "Variables and individuals", 'interact', 'en/structures', 's_structures1', 'en/structures', 'v_structures1');
addPage_2('fr/structures', 'structures_a2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures2');
addPage_2('fr/structures', 'structures3', "Les variables catégorielles et les groupes", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures3');
addPage_2('fr/structures', 'structures_a4', "Meaningful variables", 'static', 'en/structures', 's_structures4', 'en/structures', 'v_structures4');
addPage_2('fr/structures', 'structures_b5', "Time-ordered data", 'static', 'en/structures', 's_structures5', 'en/structures', 'v_structures_b5');
addPage_2('fr/structures', 'structures_b6', "Multi-level data", 'interact', 'en/structures', 's_structures6', 'en/structures', 'v_structures_b6');
addSection('bk/fr_esiac', 'sec_variation', "Variation");
addPage_2('fr/variation', 'variation1', "Signal et le bruit", 'interact', 'en/variation', 's_variation1', 'en/variation', 'v_variation1');
addPage_2('fr/variation', 'variation2', "La variabilité naturelle", 'interact', 'en/variation', 's_variation2', 'en/variation', 'v_variation2');
addPage_2('fr/variation', 'variation3', "Variabilité causée par des expériences", 'interact', 'en/variation', 's_variation3', 'en/variation', 'v_variation3');
addPage_2('fr/variation', 'variation_a4', "Variability in survey data", 'interact', 'en/variation', 's_variation4', 'en/variation', 'v_variation4');
addPage_2('fr/variation', 'variation5', "Variation expliquée et inexpliquée", 'static', 'en/variation', 's_variation5', 'en/variation', 'v_variation5');
addPage_2('fr/variation', 'variation_a6', "Information from variation", 'static', 'en/variation', 's_variation6', 'en/variation', 'v_variation6');

addChapter('bk/fr_esiac', 'ch_displayData', "Affichage des Données");
addSection('bk/fr_esiac', 'sec_dotPlot', "Parcelles dot");
addPage_2('fr/valueDisplay', 'valueDisplay_b1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay_b1');
addPage_2('fr/valueDisplay', 'valueDisplay_b2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2', 'en/valueDisplay', 'v_valueDisplay_b2');
addPage_2('fr/valueDisplay', 'valueDisplay_m3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3', 'en/valueDisplay', 'v_valueDisplay3');
addPage_2('fr/valueDisplay', 'valueDisplay_m4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4', 'en/valueDisplay', 'v_valueDisplay4');
addSection('bk/fr_esiac', 'sec_stemLeaf', "Tiges et à feuilles parcelles");
addPage_2('fr/valueDisplay', 'valueDisplay_m5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5', 'en/valueDisplay', 'v_valueDisplay5');
addPage_2('fr/valueDisplay', 'valueDisplay_m6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6', 'en/valueDisplay', 'v_valueDisplay6');
addPage_2('fr/valueDisplay', 'valueDisplay_m7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7', 'en/valueDisplay', 'v_valueDisplay7');
addSection('bk/fr_esiac', 'sec_displayInterp', "Comprendre les distributions");
addPage_2('fr/displayInterp', 'displayInterp_b1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp_b1');
addPage_2('fr/displayInterp', 'displayInterp_b2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp_b2');
addPage_2('fr/displayInterp', 'displayInterp3', "Distribution des valeurs", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp3');
addPage_2('fr/displayInterp', 'displayInterp_b4', "Extra information about individuals", 'interact', 'en/displayInterp', 's_displayInterp4', 'en/displayInterp', 'v_displayInterp_b4');
addPage_2('fr/displayInterp', 'displayInterp5', "Distinguer les groupes connus", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('fr/displayInterp', 'displayInterp6', "Dangers de la surinterprétation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp6');

addChapter('bk/fr_esiac', 'ch_graphSumm', "Résumés Graphiques");
addSection('bk/fr_esiac', 'sec_density', "Histogrammes et de la densité");
addPage_2('fr/density', 'density1', "Densité des valeurs", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('fr/density', 'density2', "Histogramme avec des largeurs de classe égale", 'interact', 'en/density', 's_density2', 'en/density', 'v_density2');
addPage_2('fr/density', 'density_m3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density3');
addPage_2('fr/density', 'density_m4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density4');
addPage_2('fr/density', 'density5', "Fréquence relative et de la zone", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('fr/density', 'density_b6', "Comparing groups", 'interact', 'en/density', 's_density6', 'en/density', 'v_density_b6');
addPage_2('fr/density', 'density_m7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7', 'en/density', 'v_density7');
addPage_2('fr/density', 'density8', "Comprendre les histogrammes", 'interact', 'en/density', 's_density8', 'en/density', 'v_density8');
addPage_2('fr/density', 'density9', "Polygones de fréquence", 'interact', 'en/density', 's_density9', 'en/density', 'v_density9');
addPage_2('fr/density', 'density10', "Estimations de la densité du noyau", 'interact', 'en/density', 's_density10', 'en/density', 'v_density10');
addPage_2('fr/density', 'density_m11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11', 'en/density', 'v_density11');
addSection('bk/fr_esiac', 'sec_boxPlot', "Médiane, quartiles et boîtes à moustaches");
addPage_2('fr/boxPlot', 'boxPlot1', "La nécessité de résumer", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('fr/boxPlot', 'boxPlot2', "Médian, quartiles et boîte à moustaches", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('fr/boxPlot', 'boxPlot3', "Interpréter une forme de boîte parcelles", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('fr/boxPlot', 'boxPlot4', "Afficher les valeurs aberrantes", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('fr/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('fr/boxPlot', 'boxPlot6', "Comparaison des groupes", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot6');
addSection('bk/fr_esiac', 'sec_counts', "Données discrètes (chiffres)");
addPage_2('fr/counts', 'counts_b1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1', 'en/counts', 'v_counts_b1');
addPage_2('fr/counts', 'counts_b2', "Histograms for counts", 'interact', 'en/counts', 's_counts2', 'en/counts', 'v_counts_b2');
addPage_2('fr/counts', 'counts3', "Les diagrammes à barres", 'interact', 'en/counts', 's_counts3', 'en/counts', 'v_counts3');

addChapter('bk/fr_esiac', 'ch_numSumm', "Résumés numériques");
addSection('bk/fr_esiac', 'sec_center', "Centre décrivant");
addPage_2('fr/centerSpread', 'centerSpread_b1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread_b1');
addPage_2('fr/centerSpread', 'centerSpread_b2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2', 'en/centerSpread', 'v_centerSpread_b2');
addPage_2('fr/centerSpread', 'centerSpread_m3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread3');
addPage_2('fr/centerSpread', 'centerSpread4', "Propriétés de la médiane et la moyenne", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addSection('bk/fr_esiac', 'sec_spread', "Décrivant la propagation");
addPage_2('fr/centerSpread', 'centerSpread5', "L'écart-type", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('fr/centerSpread', 'centerSpread6', "Règles d'or pour l'écart-type", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('fr/centerSpread', 'centerSpread7', "Signifie comprendre et devns er", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread7');
addPage_2('fr/centerSpread', 'centerSpread8', "Avertissements sur devn moyenne et standard", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addPage_2('fr/moreVariation', 'moreVariation1', "Effet des valeurs aberrantes", 'interact', 'en/moreVariation', 's_moreVariation1', 'en/moreVariation', 'v_moreVariation1');
addPage_2('fr/counts', 'counts_b4', "Mean & sd for discrete data#?# (opt)", 'static', 'en/counts', 's_counts4', 'en/counts', 'v_counts_b4');
addSection('bk/fr_esiac', 'sec_varAndGroups', "Variation et les groupes");
addPage_2('fr/moreVariation', 'moreVariation2', "L'écart type des données groupées", 'interact', 'en/moreVariation', 's_moreVariation2', 'en/moreVariation', 'v_moreVariation2');
addPage_2('fr/moreVariation', 'moreVariation3', "Variation expliquée et les prédictions", 'interact', 'en/moreVariation', 's_moreVariation3', 'en/moreVariation', 'v_moreVariation3');
addPage_2('fr/multiGroup', 'multiGroup_a4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4', 'en/multiGroup', 'v_multiGroup4');
addPage_2('fr/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5', 'en/multiGroup', 'v_multiGroup5');
addPage_2('fr/multiGroup', 'multiGroup_a6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup6', 'en/multiGroup', 'v_multiGroup6');
addPage_2('fr/multiGroup', 'multiGroup_a7', "Analysis of variance", 'interact', 'en/multiGroup', 's_multiGroup7', 'en/multiGroup', 'v_multiGroup7');
addSection('bk/fr_esiac', 'sec_moreVariation', "Plus à propos de variation (en option)");
addPage_2('fr/moreVariation', 'moreVariation4', "Variance et de degrés de liberté", 'static', 'en/moreVariation', 's_moreVariation4', 'en/moreVariation', 'v_moreVariation4');
addPage_2('fr/moreVariation', 'moreVariation5', "Racine l'erreur quadratique moyenne", 'interact', 'en/moreVariation', 's_moreVariation5', 'en/moreVariation', 'v_moreVariation5');
addPage_2('fr/moreVariation', 'moreVariation6', "Interprétation graphique de SD", 'interact', 'en/moreVariation', 's_moreVariation6', 'en/moreVariation', 'v_moreVariation6');

addChapter('bk/fr_esiac', 'ch_percentiles', "Proportions et Percentiles");
addSection('bk/fr_esiac', 'sec_propn', "Proportions");
addPage_2('fr/percentile', 'percentile1', "Ensemble de données illustratives", 'interact', 'en/percentile', 's_percentile1', 'en/percentile', 'v_percentile1');
addPage_2('fr/percentile', 'percentile2', "Proportions cumulatives", 'interact', 'en/percentile', 's_percentile2', 'en/percentile', 'v_percentile2');
addPage_2('fr/percentile', 'percentile3', "Graphique des proportions cumulatives", 'interact', 'en/percentile', 's_percentile3', 'en/percentile', 'v_percentile3');
addPage_2('fr/percentile', 'percentile_m9', "Other ways to express proportions", 'interact');
addPage_2('fr/percentile', 'percentile_m10', "Other data sets", 'interact');
addPage_2('fr/percentile', 'e_percentile_m4', "Exercises based on real data", 'static');
addSection('bk/fr_esiac', 'sec_percentile', "Percentiles");
addPage_2('fr/percentile', 'percentile4', "Centiles", 'interact', 'en/percentile', 's_percentile4', 'en/percentile', 'v_percentile4');
addPage_2('fr/percentile', 'percentile5', "Afficher les percentiles", 'interact', 'en/percentile', 's_percentile5', 'en/percentile', 'v_percentile5');
addPage_2('fr/percentile', 'e_percentile6', "Percentiles", 'static');
addPage_2('fr/percentile', 'percentile6', "En comparant des groupes", 'interact', 'en/percentile', 's_percentile6', 'en/percentile', 'v_percentile6');
addPage_2('fr/percentile', 'percentile7', "En comparant des groupes d'autres percentiles", 'interact', 'en/percentile', 's_percentile7', 'en/percentile', 'v_percentile7');
addPage_2('fr/percentile', 'percentile8', "Une meilleure définition des centiles", 'interact', 'en/percentile', 's_percentile8', 'en/percentile', 'v_percentile8');

addChapter('bk/french', 'ch_cat', "Variables Catégorielles");
addSection('bk/fr_esiac', 'sec_freqTable', "Les tableaux de fréquence");
addPage_2('fr/freqTable', 'freqTable1', "Tables de fréquences", 'interact', 'en/freqTable', 's_freqTable1', 'en/freqTable', 'v_freqTable1');
addPage_2('fr/freqTable', 'freqTable_a2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable_a2', 'en/freqTable', 'v_freqTable2');
addPage_2('fr/tableDisplay', 'tableDisplay_a1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('fr/tableDisplay', 'tableDisplay3', "Chiffres significatifs et le bruit des données", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('fr/freqTable', 'freqTable3', "Reconnaissant les tableaux de fréquence", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('fr/freqTable', 'freqTable4', "Modifications aux catégories", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addSection('bk/fr_esiac', 'sec_bar', "Diagramme à barres");
addPage_2('fr/univarCat', 'univarCat_a1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('fr/univarCat', 'univarCat2', "Diagrammes de Pareto", 'interact', 'en/univarCat', 's_univarCat2', 'en/univarCat', 'v_univarCat2');
addPage_2('fr/univarCat', 'univarCat_a3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat_a3', 'en/univarCat', 'v_univarCat3');
addSection('bk/fr_esiac', 'sec_pie', "Camemberts");
addPage_2('en/univarCat', 'univarCat_b4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat_b4');
addPage_2('en/univarCat', 'univarCat_b5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat_b5');
addPage_2('en/univarCat', 'univarCat_b6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat_b6', 'en/univarCat', 'v_univarCat_b6');
addPage_2('en/univarCat', 'univarCat_b7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat_b7');
addSection('bk/french_b', 'sec_groupedCat', "En comparant des groupes");
addPage_2('fr/groupedCat', 'groupedCat1', "Tableaux de contingence", 'interact');
addPage_2('fr/groupedCat', 'groupedCat_b2', "Contingency table examples", 'static');
addPage_2('fr/groupedCat', 'groupedCat_b3', "Bar charts using proportions", 'interact');
addPage_2('fr/groupedCat', 'groupedCat_b4', "Stacked bar charts", 'interact');
addPage_2('fr/groupedCat', 'groupedCat_b5', "Two special cases", 'interact');

var language = "fr";
var logoGif = null;
var homeDir = "bk/fr_esiac";
var versionGif = "images/castClimatic_c1";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "7";

var localVideos = false;

var fullTextString = 'Complet';
var summaryTextString = 'Résumé';
var videoTextString = 'Video';
var appletTextString = 'Complet';
fullTabTooltip = 'Full version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Interactive version of page';
var chapterString = 'Chapitre';

var versionName = {'_m': 'Climatiques', '_g': 'Général', '_b': 'Biométrique', '_c': 'Business', '_o': 'Stats officielles', '_a': 'Africaine'};
var versions = {};
versions['context1'] = new Array('_m', '_g', '_b', '_c', '_o');
versions['context2'] = new Array('_m', '_g', '_o');
versions['context3'] = new Array('_b', '_g');
versions['structures1'] = new Array('_a', '_g', '_b', '_c');
versions['structures2'] = new Array('_a', '_g', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_a', '_g', '_c');
versions['structures5'] = new Array('_b', '_g', '_c');
versions['structures6'] = new Array('_b', '_g');
versions['variation4'] = new Array('_a', '_g');
versions['variation5'] = new Array('_g', '_b', '_c');
versions['variation6'] = new Array('_a', '_g');
versions['valueDisplay1'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay2'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay3'] = new Array('_m', '_g', '_b', '_c');
versions['valueDisplay4'] = new Array('_m', '_g', '_b', '_c');
versions['valueDisplay5'] = new Array('_m', '_g', '_a', '_b', '_c');
versions['valueDisplay6'] = new Array('_m', '_g', '_c');
versions['valueDisplay7'] = new Array('_m', '_g', '_c');
versions['displayInterp1'] = new Array('_b', '_g', '_c');
versions['displayInterp2'] = new Array('_b', '_g', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_b', '_g');
versions['density3'] = new Array('_m', '_g', '_c');
versions['density4'] = new Array('_m', '_g', '_b', '_c');
versions['density6'] = new Array('_b', '_g', '_c');
versions['density7'] = new Array('_m', '_g', '_b', '_c');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_m', '_g', '_b', '_c');
versions['boxPlot6'] = new Array('_g', '_c');
versions['counts1'] = new Array('_b', '_g', '_c');
versions['counts2'] = new Array('_b', '_g', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['centerSpread1'] = new Array('_b', '_g');
versions['centerSpread2'] = new Array('_b', '_g');
versions['centerSpread3'] = new Array('_m', '_g', '_b', '_c');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts4'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_a', '_g');
versions['multiGroup6'] = new Array('_a', '_g', '_b', '_c');
versions['multiGroup7'] = new Array('_a', '_g');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_a', '_g', '_b');
versions['tableDisplay1'] = new Array('_a', '_g');
versions['univarCat1'] = new Array('_a', '_g', '_b');
versions['univarCat3'] = new Array('_a', '_g', '_b');
versions['univarCat4'] = new Array('_b', '_g', '_c');
versions['univarCat5'] = new Array('_b', '_g', '_c');
versions['univarCat6'] = new Array('_b', '_g', '_c');
versions['univarCat7'] = new Array('_b', '_g');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_b', '_g', '_c');
versions['groupedCat3'] = new Array('_b', '_g', '_c');
versions['groupedCat4'] = new Array('_b', '_g', '_c');
versions['groupedCat5'] = new Array('_b', '_g', '_c');

bookLoaded = true;
