
addBook('bk/masseyBbs', 'book_splash', "About this CAST e-book", null, 'v_book_splash');

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/masseyBbs', 'ch_intro', "Intro &amp; Data Collection");
addSection('bk/masseyBbs', 'sec_introduction', "Introduction");
addPage_2('bk/masseyBbs', 'context_c1', "Why Statistics for Business?", 'static', 'en/context', 's_context1', 'en/context', 'v_context_c1');
addPage_2('bk/masseyBbs', 'context2', "The statistical process", 'static', 'en/context', 's_context2', 'en/context', 'v_context2');
addPage_2('bk/masseyBbs', 'variation4', "Variation", 'interact', 'bk/masseyBbs', 's_variation4', 'bk/masseyBbs', 'v_variation4');
addSection('bk/masseyBbs', 'sec_structures', "Variables and data");
addPage_2('bk/masseyBbs', 'structures_c1', "Variables and individuals", 'interact', 'bk/masseyBbs', 's_structures1', 'bk/masseyBbs', 'v_structures1');
addPage_2('en/structures', 'structures_c2', "Types of variable", 'interact', 'en/structures', 's_structures2', 'en/structures', 'v_structures_c2');
addPage_2('bk/masseyBbs', 'structures_c3', "Groups", 'interact', 'en/structures', 's_structures3', 'en/structures', 'v_structures_c3');
addPage_2('en/structures', 'structures_c4', "Meaningful variables", 'interact', 'en/structures', 's_structures_c4', 'en/structures', 'v_structures_c4');
addPage_2('bk/masseyBbs', 'causal_c1', "Relationships", 'static', 'en/causal', 's_causal1', 'en/causal', 'v_causal_c1');
addPage_2('bk/masseyBbs', 'causal4', "Sources of data", 'interact', 'bk/masseyBbs', 's_causal4', 'bk/masseyBbs', 'v_causal4');
addPage_2('en/freqTable', 'e_freqTable1', "#r#Exercise: #+#Types of variables", 'static');
addSection('bk/masseyBbs', 'sec_popSamp', "Populations and samples");
addPage_2('en/popSamp', 'popSamp_c1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1', 'en/popSamp', 'v_popSamp_c1');
addPage_2('en/popSamp', 'popSamp_c2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2', 'en/popSamp', 'v_popSamp_c2');
addPage_2('bk/masseyBbs', 'popSamp_c3', "Sampling error", 'interact', 'bk/masseyBbs', 's_popSamp3', 'bk/masseyBbs', 'v_popSamp_c3');
addPage_2('bk/masseyBbs', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6', 'en/popSamp', 'v_popSamp6');
addSection('bk/masseyBbs', 'sec_sampPractice', "Sampling in practice");
addPage_2('bk/masseyBbs', 'sampPractice1', "Stratified sampling", 'static', 'bk/masseyBbs', 's_sampPractice1', 'bk/masseyBbs', 'v_sampPractice1');
addPage_2('bk/masseyBbs', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2', 'bk/masseyBbs', 'v_sampPractice2');
addPage_2('bk/masseyBbs', 'sampPractice3', "Two-stage sampling#?# (opt)", 'interact', 'en/sampPractice', 's_sampPractice3', 'bk/masseyBbs', 'v_sampPractice3');
addPage_2('bk/masseyBbs', 'sampPractice8', "Cost & accuracy of sampling schemes#?# (opt)", 'interact', 'bk/masseyBbs', 's_sampPractice8', 'bk/masseyBbs', 'v_sampPractice8');
addPage_2('bk/masseyBbs', 'sampPractice9', "Systematic sampling", 'static', 'bk/masseyBbs', 's_sampPractice9');
addPage_2('bk/masseyBbs', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4', 'en/sampPractice', 'v_sampPractice4');
addPage_2('bk/masseyBbs', 'sampPractice5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5', 'en/sampPractice', 'v_sampPractice5');
addPage_2('en/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6', 'en/sampPractice', 'v_sampPractice6');
addPage_2('bk/masseyBbs', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7', 'bk/masseyBbs', 'v_sampPractice7');
addSection('bk/masseyBbs', 'overview', "Overview of the rest of the book");

addChapter('bk/masseyBbs', 'ch_categorical', "Categorical Data");
addSection('bk/masseyBbs', 'sec_freqTable', "Frequency tables");
addPage_2('bk/masseyBbs', 'freqTable_c1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable_c1', 'en/freqTable', 'v_freqTable_c1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2', 'en/freqTable', 'v_freqTable2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables#?# (opt)", 'static', 'en/freqTable', 's_freqTable3', 'en/freqTable', 'v_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories#?# (opt)", 'interact', 'en/freqTable', 's_freqTable4', 'en/freqTable', 'v_freqTable4');
addPage_2('en/freqTable', 'e_freqTable2', "#r#Exercise: #+#Proportions from tables", 'static');
addPage_2('en/freqTable', 'e_freqTable3', "#r#Exercise: #+#Propns from ordered categories", 'static');
addSection('bk/masseyBbs', 'sec_univarCat', "Bar and pie charts");
addPage_2('bk/masseyBbs', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1', 'en/univarCat', 'v_univarCat1');
addPage_2('bk/masseyBbs', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2', 'en/univarCat', 'v_univarCat2');
addPage_2('bk/masseyBbs', 'univarCat3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat3', 'en/univarCat', 'v_univarCat3');
addPage_2('bk/masseyBbs', 'univarCat_c4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4', 'en/univarCat', 'v_univarCat_c4');
addPage_2('en/univarCat', 'univarCat_c5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5', 'en/univarCat', 'v_univarCat_c5');
addPage_2('en/univarCat', 'univarCat_c6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat_c6', 'en/univarCat', 'v_univarCat_c6');
addPage_2('en/univarCat', 'univarCat7', "Bar & pie charts for quantities#?# (opt)", 'interact', 'en/univarCat', 's_univarCat7', 'en/univarCat', 'v_univarCat7');
addPage_2('en/univarCat', 'e_univarCat1', "#r#Exercise: #+#Draw a bar chart", 'static');
addPage_2('en/univarCat', 'e_univarCat2', "#r#Exercise: #+#Find proportion from bar chart", 'static');
addPage_2('en/univarCat', 'e_univarCat3', "#r#Exercise: #+#Pareto diagram", 'static');
addPage_2('en/univarCat', 'e_univarCat4', "#r#Exercise: #+#Draw a pie chart", 'static');
addPage_2('en/univarCat', 'e_univarCat5', "#r#Exercise: #+#Match bar and pie charts", 'static');
addPage_2('en/univarCat', 'e_univarCat6', "#r#Exercise: #+#Proportions from pie chart", 'static');
addSection('bk/masseyBbs', 'sec_groupedCat', "Comparing groups");
addPage_2('bk/masseyBbs', 'groupedCat_c1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat_c1', 'en/groupedCat', 'v_groupedCat_c1');
addPage_2('bk/masseyBbs', 'groupedCat_c2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat_c2', 'en/groupedCat', 'v_groupedCat_c2');
addPage_2('bk/masseyBbs', 'groupedCat_c3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat_c3', 'en/groupedCat', 'v_groupedCat_c3');
addPage_2('en/groupedCat', 'groupedCat_c4', "Stacked bar charts#?# (opt)", 'interact', 'en/groupedCat', 's_groupedCat_c4', 'en/groupedCat', 'v_groupedCat_c4');
addPage_2('en/groupedCat', 'groupedCat_c5', "Two special cases#?# (opt)", 'interact', 'en/groupedCat', 's_groupedCat5', 'en/groupedCat', 'v_groupedCat_c5');
addPage_2('bk/masseyBbs', 'groupedCat6', "Bivariate categorical data", 'interact', 'bk/masseyBbs', 's_groupedCat6', 'bk/masseyBbs', 'v_groupedCat6');
addPage_2('en/groupedCat', 'e_groupedCat1', "#r#Exercise: #+#Create a contingency table", 'static');
addSection('bk/masseyBbs', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1', 'en/tableDisplay', 'v_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2', 'en/tableDisplay', 'v_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3', 'en/tableDisplay', 'v_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4', 'en/tableDisplay', 'v_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5', 'en/tableDisplay', 'v_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6', 'en/tableDisplay', 'v_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7', 'en/tableDisplay', 'v_tableDisplay7');

addChapter('bk/masseyBbs', 'ch_numerical', "Numerical Data");
addSection('bk/masseyBbs', 'sec_numDisplay', "Tables and graphs for numbers");
addPage_2('en/valueDisplay', 'valueDisplay_c1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1', 'en/valueDisplay', 'v_valueDisplay_c1');
addPage_2('bk/masseyBbs', 'valueDisplay_c5', "Stem and leaf plots", 'interact', 'bk/masseyBbs', 's_valueDisplay5', 'bk/masseyBbs', 'v_valueDisplay_c5');
addPage_2('bk/masseyBbs', 'valueDisplay_c6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6', 'en/valueDisplay', 'v_valueDisplay_c6');
addPage_2('bk/masseyBbs', 'valueDisplay_c7', "Drawing stem and leaf plots", 'interact', 'bk/masseyBbs', 's_valueDisplay7', 'en/valueDisplay', 'v_valueDisplay_c7');
addPage_2('bk/masseyBbs', 'valueDisplay_c3', "Dot plots", 'interact', 'bk/masseyBbs', 's_valueDisplay3', 'bk/masseyBbs', 'v_valueDisplay_c3');
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1', 'en/density', 'v_density1');
addPage_2('bk/masseyBbs', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2', 'bk/masseyBbs', 'v_density2');
addPage_2('bk/masseyBbs', 'density_c3', "Choice of classes", 'interact', 'en/density', 's_density3', 'en/density', 'v_density_c3');
addPage_2('en/density', 'density_c4', "Histograms of small data sets", 'interact', 'en/density', 's_density4', 'en/density', 'v_density_c4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5', 'en/density', 'v_density5');
addPage_2('bk/masseyBbs', 'density11', "Drawing histograms by hand#?# (opt)", 'interact', 'en/density', 's_density11', 'bk/masseyBbs', 'v_density11');
addPage_2('bk/masseyBbs', 'density7', "Histograms with varying class widths#?# (opt)", 'interact', 'en/density', 's_density7', 'bk/masseyBbs', 'v_density7');
addPage_2('en/valueDisplay', 'e_valueDisplay1', "#r#Exercise: #+#Draw a stem and leaf plot", 'static');
addPage_2('bk/masseyBbs', 'e_density1', "#r#Exercise: #+#Draw a histogram", 'static');
addPage_2('en/density', 'e_density2', "#r#Exercise: #+#Histogram areas and proportions", 'static');
addSection('bk/masseyBbs', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp_c1', "Outliers", 'interact', 'en/displayInterp', 's_displayInterp1', 'en/displayInterp', 'v_displayInterp_c1');
addPage_2('en/displayInterp', 'displayInterp_c2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2', 'en/displayInterp', 'v_displayInterp_c2');
addPage_2('en/displayInterp', 'displayInterp_c3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3', 'en/displayInterp', 'v_displayInterp_c3');
addPage_2('en/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6', 'en/displayInterp', 'v_displayInterp6');
addPage_2('en/displayInterp', 'e_displayInterp1', "#r#Exercise: #+#Information from distributions", 'static');
addSection('bk/masseyBbs', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1', 'en/centerSpread', 'v_centerSpread1');
addPage_2('bk/masseyBbs', 'centerSpread_c3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3', 'en/centerSpread', 'v_centerSpread_c3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4', 'en/centerSpread', 'v_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5', 'en/centerSpread', 'v_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6', 'en/centerSpread', 'v_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread_c7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7', 'en/centerSpread', 'v_centerSpread_c7');
addPage_2('bk/masseyBbs', 'centerSpread8', "Warnings about mean and standard devn", 'static', 'en/centerSpread', 's_centerSpread8', 'en/centerSpread', 'v_centerSpread8');
addPage_2('bk/masseyBbs', 'centerSpread9', "Population parameters", 'static', 'bk/masseyBbs', 's_centerSpread9');
addPage_2('en/centerSpread', 'e_centerSpread1', "#r#Exercise: #+#Ideas of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread2', "#r#Exercise: #+#Mean and median", 'static');
addPage_2('en/centerSpread', 'e_centerSpread3', "#r#Exercise: #+#Standard deviation from graph", 'static');
addPage_2('en/centerSpread', 'e_centerSpread4', "#r#Exercise: #+#Standard deviation from general knowledge", 'static');
addPage_2('en/centerSpread', 'e_centerSpread5', "#r#Exercise: #+#Rough graph from mean and st devn", 'static');
addSection('bk/masseyBbs', 'sec_groups', "Comparing groups");
addPage_2('bk/masseyBbs', 'displayInterp5', "Comparing dot and stem and leaf plots", 'interact', 'en/displayInterp', 's_displayInterp5', 'en/displayInterp', 'v_displayInterp5');
addPage_2('bk/masseyBbs', 'density_c6', "Comparing histograms", 'interact', 'en/density', 's_density6', 'en/density', 'v_density_c6');
addPage_2('bk/masseyBbs', 'density_c9', "Frequency polygons", 'interact', 'en/density', 's_density9', 'en/density', 'v_density_c9');
addPage_2('bk/masseyBbs', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1', 'en/boxPlot', 'v_boxPlot1');
addPage_2('bk/masseyBbs', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2', 'en/boxPlot', 'v_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3', 'en/boxPlot', 'v_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers#?# (opt)", 'interact', 'en/boxPlot', 's_boxPlot4', 'en/boxPlot', 'v_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5', 'en/boxPlot', 'v_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot_c6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6', 'en/boxPlot', 'v_boxPlot_c6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7', 'en/boxPlot', 'v_boxPlot7');
addPage_2('bk/masseyBbs', 'e_boxPlot1', "#r#Exercise: #+#Draw a box plot", 'static');
addPage_2('en/boxPlot', 'e_boxPlot2', "#r#Exercise: #+#Shape of a box plot", 'static');
addSection('bk/masseyBbs', 'sec_bivarNum', "Two numerical variables");
addPage_2('en/scatterplot', 'scatterplot_c1', "Bivariate data sets", 'interact', 'en/scatterplot', 's_scatterplot1', 'en/scatterplot', 'v_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot_c2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2', 'en/scatterplot', 'v_scatterplot_c2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3', 'en/scatterplot', 'v_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot_c4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4', 'en/scatterplot', 'v_scatterplot_c4');
addPage_2('en/relationship', 'relationship_c1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1', 'en/relationship', 'v_relationship_c1');
addPage_2('bk/masseyBbs', 'relationship_c2', "Outliers", 'interact', 'en/relationship', 's_relationship2', 'bk/masseyBbs', 'v_relationship2');
addPage_2('en/relationship', 'relationship_c3', "Clusters", 'interact', 'en/relationship', 's_relationship3', 'en/relationship', 'v_relationship3');
addPage_2('en/relationship', 'relationship_c4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4', 'en/relationship', 'v_relationship_c4');
addPage_2('en/relationship', 'relationship_c5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5', 'en/relationship', 'v_relationship_c5');
addPage_2('en/scatterplot', 'e_scatterplot1', "#r#Exercise: #+#Draw a scatterplot", 'static');
addPage_2('en/scatterplot', 'e_scatterplot2', "#r#Exercise: #+#Interpret a scatterplot", 'static');
addSection('bk/masseyBbs', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation_c1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation_c1', 'en/correlation', 'v_correlation_c1');
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2', 'en/correlation', 'v_correlation2');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3', 'en/correlation', 'v_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4', 'en/correlation', 'v_correlation4');
addPage_2('bk/masseyBbs', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5', 'bk/masseyBbs', 'v_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6', 'en/correlation', 'v_correlation6');
addPage_2('en/correlation', 'e_correlation1', "#r#Exercise: #+#Estimate r by eye", 'static');
addPage_2('en/correlation', 'e_correlation2', "#r#Exercise: #+#r for non-standard data", 'static');

addChapter('bk/masseyBbs', 'ch_prob', "Basic Probability");
addSection('bk/masseyBbs', 'sec_probIntro', "Introduction");
addPage_2('bk/masseyBbs', 'probIntro1', "Introduction", 'static', 'bk/masseyBbs', 's_probIntro1');
addPage_2('bk/masseyBbs', 'probIntro2', "Classical definition of probability", 'interact', 'bk/masseyBbs', 's_probIntro2', 'bk/masseyBbs', 'v_probIntro2');
addPage_2('bk/masseyBbs', 'probIntro3', "Probability and proportion", 'interact', 'bk/masseyBbs', 's_probIntro3', 'bk/masseyBbs', 'v_probIntro3');
addPage_2('bk/masseyBbs', 'probIntro4', "Empirical and subjective probability", 'static', 'bk/masseyBbs', 's_probIntro4');
addPage_2('bk/masseyBbs', 'probIntro5', "Probability and numerical populations", 'interact', 'bk/masseyBbs', 's_probIntro5', 'bk/masseyBbs', 'v_probIntro5');
addPage_2('bk/masseyBbs', 'probIntro6', "Properties and rules of probability", 'static', 'bk/masseyBbs', 's_probIntro6', 'bk/masseyBbs', 'v_probIntro6');
addPage_2('en/probSim', 'e_probSim1', "#r#Exercise: #+#Probabilities for cards and dice", 'static');
addPage_2('en/probSim', 'e_probSim2', "#r#Exercise: #+#Probabilities and finite populations", 'static');
addSection('bk/masseyBbs', 'sec_conditProb', "Conditional probability");
addPage_2('bk/masseyBbs', 'conditProb1', "Contingency tables", 'static', 'bk/masseyBbs', 's_conditProb1', 'bk/masseyBbs', 'v_conditProb1');
addPage_2('bk/masseyBbs', 'conditProb2', "Joint probabilities", 'interact', 'bk/masseyBbs', 's_conditProb2', 'bk/masseyBbs', 'v_conditProb2');
addPage_2('bk/masseyBbs', 'conditProb3', "Marginal probabilities", 'interact', 'bk/masseyBbs', 's_conditProb3', 'bk/masseyBbs', 'v_conditProb3');
addPage_2('bk/masseyBbs', 'conditProb4', "Conditional probability", 'interact', 'bk/masseyBbs', 's_conditProb4', 'bk/masseyBbs', 'v_conditProb4');
addPage_2('bk/masseyBbs', 'conditProb5', "Displaying probabilities", 'interact', 'bk/masseyBbs', 's_conditProb5', 'bk/masseyBbs', 'v_conditProb5');
addPage_2('bk/masseyBbs', 'conditProb6', "Tree diagrams", 'static', 'bk/masseyBbs', 's_conditProb6');
addPage_2('bk/masseyBbs', 'conditProb7', "More about tree diagrams", 'static', 'bk/masseyBbs', 's_conditProb7');
addPage_2('en/groupedCat', 'e_groupedCat2', "#r#Exercise: #+#Find contingency table proportions", 'static');
addSection('bk/masseyBbs', 'sec_indep', "Independence");
addPage_2('bk/masseyBbs', 'indep_c1', "Association and conditional probability", 'static', 'en/indep', 's_indep_c1', 'en/indep', 'v_indep_c1');
addPage_2('bk/masseyBbs', 'indep_c2', "Definition of independence", 'static', 'en/indep', 's_indep_c2', 'en/indep', 'v_indep_c2');

addChapter('bk/masseyBbs', 'ch_distn', "Probability Distributions");
addSection('bk/masseyBbs', 'sec_discreteIntro', "Discrete distributions");
addPage_2('bk/masseyBbs', 'discreteIntro1', "Introduction and examples", 'static', 'bk/masseyBbs', 's_discreteIntro1');
addPage_2('bk/masseyBbs', 'discreteIntro2', "Bar charts and probabilities", 'interact', 'en/probDensity', 's_probDensity3', 'bk/masseyBbs', 'v_discreteIntro2');
addPage_2('bk/masseyBbs', 'discreteIntro3', "Expected value", 'static', 'bk/masseyBbs', 's_discreteIntro3');
addPage_2('bk/masseyBbs', 'discreteIntro4', "Standard deviation", 'static', 'bk/masseyBbs', 's_discreteIntro4');
addSection('bk/masseyBbs', 'sec_binomial', "Binomial distributions");
addPage_2('en/randomPropn', 'randomPropn_c2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2', 'en/randomPropn', 'v_randomPropn_c2');
addPage_2('en/randomPropn', 'randomPropn_c3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3', 'en/randomPropn', 'v_randomPropn_c3');
addPage_2('bk/masseyBbs', 'binomial3', "Binomial probability examples", 'static', 'bk/masseyBbs', 's_binomial3', 'bk/masseyBbs', 'v_binomial3');
addPage_2('bk/masseyBbs', 'binomial4', "Mean and standard deviation", 'static', 'bk/masseyBbs', 's_binomial4');
addPage_2('bk/masseyBbs', 'binomial5', "Binomial assumptions", 'static', 'bk/masseyBbs', 's_binomial5', 'bk/masseyBbs', 'v_binomial5');
addPage_2('en/randomPropn', 'e_randomPropn1', "#r#Exercise: #+#Are variables binomial?", 'static');
addPage_2('en/randomPropn', 'e_randomPropn2', "#r#Exercise: #+#Match bar charts to parameters", 'static');
addPage_2('en/randomPropn', 'e_randomPropn3', "#r#Exercise: #+#Find binomial probabilities", 'static');
addSection('bk/masseyBbs', 'sec_continIntro', "Continuous distributions");
addPage_2('bk/masseyBbs', 'continIntro1', "Introduction and examples", 'static', 'bk/masseyBbs', 's_continIntro1');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4', 'en/probDensity', 'v_probDensity4');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under pdf", 'interact', 'en/probDensity', 's_probDensity6', 'en/probDensity', 'v_probDensity6');
addPage_2('en/probSim', 'e_probSim3', "#r#Exercise: #+#Probabilities and numerical populations", 'static');
addPage_2('en/probSim', 'e_probSim4', "#r#Exercise: #+#Probabilities from continuous distributions", 'static');
addSection('bk/masseyBbs', 'sec_normalDistn', "Normal distributions");
addPage_2('bk/masseyBbs', 'probDensity_c5', "Importance of normal distributions", 'interact', 'bk/masseyBbs', 's_probDensity5', 'en/probDensity', 'v_probDensity_c5');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2', 'en/normalDistn', 'v_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn_c3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3', 'en/normalDistn', 'v_normalDistn_c3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4', 'en/normalDistn', 'v_normalDistn4');
addPage_2('bk/masseyBbs', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10', 'en/normalDistn', 'v_normalDistn10');
addPage_2('en/normalDistn', 'e_normalDistn1', "#r#Exercise: #+#Normal distribution parameters", 'static');
addPage_2('en/normalDistn', 'e_normalDistn7', "#r#Exercise: #+#Probabilities without calculations", 'static');
addSection('bk/masseyBbs', 'sec_normalCalc', "Normal distribution calculations");
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5', 'en/normalDistn', 'v_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn_c6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6', 'en/normalDistn', 'v_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn_c7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7', 'en/normalDistn', 'v_normalDistn_c7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables#?# (opt)", 'static', 'en/normalDistn', 's_normalDistn8', 'en/normalDistn', 'v_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9', 'en/normalDistn', 'v_normalDistn9');
addPage_2('en/normalDistn', 'e_normalDistn2', "#r#Exercise: #+#Probability and area under pdf", 'static');
addPage_2('bk/masseyBbs', 'e_normalDistn3', "#r#Exercise: #+#Probabilities from z-scores", 'static');
addPage_2('en/normalDistn', 'e_normalDistn4', "#r#Exercise: #+#Expected count in sample", 'static');
addPage_2('bk/masseyBbs', 'e_normalDistn5', "#r#Exercise: #+#Find X from probability", 'static');
addSection('bk/masseyBbs', 'sec_normalApprox', "Normal approximation to binomial");
addPage_2('bk/masseyBbs', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5', 'bk/masseyBbs', 'v_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn_c6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn_c6', 'en/randomPropn', 'v_randomPropn_c6');
addPage_2('en/randomPropn', 'e_randomPropn4', "#r#Exercise: #+#Find normal approximation", 'static');
addPage_2('en/randomPropn', 'e_randomPropn5', "#r#Exercise: #+#Probabilities from normal approximation", 'static');

addChapter('bk/general', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/masseyBbs', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_c1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1', 'en/randomMean', 'v_randomMean_c1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2', 'en/randomMean', 'v_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3', 'en/randomMean', 'v_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4', 'en/randomMean', 'v_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5', 'en/randomMean', 'v_randomMean5');
addPage_2('en/sumDiff', 'sumDiff1', "Distributions of sums and means", 'interact', 'en/sumDiff', 's_sumDiff1', 'en/sumDiff', 'v_sumDiff1');
addPage_2('bk/masseyBbs', 'randomMean_c6', "Estimating variability from one sample", 'static', 'en/randomMean', 's_randomMean_c6', 'en/randomMean', 'v_randomMean_c6');
addPage_2('en/randomMean', 'randomMean7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7', 'en/randomMean', 'v_randomMean7');
addPage_2('en/randomMean', 'e_randomMean1', "#r#Exercise: #+#Spread of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean2', "#r#Exercise: #+#Shape of distribution of mean and sum", 'static');
addPage_2('en/randomMean', 'e_randomMean3', "#r#Exercise: #+#Distribution of mean and sum (cont)", 'static');
addPage_2('en/randomMean', 'e_randomMean4', "#r#Exercise: #+#Probabilities relating to means and sums", 'static');
addSection('bk/masseyBbs', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro_c1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro_c1', 'en/estIntro', 'v_estIntro_c1');
addPage_2('en/estIntro', 'estIntro_c2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro_c2', 'en/estIntro', 'v_estIntro_c2');
addPage_2('bk/masseyBbs', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3', 'en/estIntro', 'v_estIntro3');
addPage_2('en/estIntro', 'estIntro_c4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4', 'en/estIntro', 'v_estIntro_c4');
addPage_2('en/estIntro', 'estIntro_c5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5', 'en/estIntro', 'v_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6', 'en/estIntro', 'v_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7', 'en/estIntro', 'v_estIntro7');
addPage_2('en/popSamp', 'e_popSamp1', "#r#Exercise: #+#Distinguish between populations and samples", 'static');
addPage_2('en/popSamp', 'e_popSamp2', "#r#Exercise: #+#Distinguish between parameters and estimates", 'static');
addSection('bk/masseyBbs', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean_c1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1', 'en/seMean', 'v_seMean_c1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2', 'en/seMean', 'v_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3', 'en/seMean', 'v_seMean3');
addPage_2('en/seMean', 'seMean_c4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean_c4', 'en/seMean', 'v_seMean_c4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5', 'en/seMean', 'v_seMean5');
addPage_2('en/seMean', 'seMean_c6', "Using SEs to compare estimators#?# (opt)", 'interact', 'en/seMean', 's_seMean6', 'en/seMean', 'v_seMean_c6');
addPage_2('en/seMean', 'e_seMean1', "#r#Exercise: #+#  Find standard error of mean", 'static');
addPage_2('en/seMean', 'e_seMean2', "#r#Exercise: #+#  Standard error vs standard deviation", 'static');
addPage_2('en/seMean', 'e_seMean3', "#r#Exercise: #+#  What affects the standard devn and standard error?", 'static');
addSection('bk/masseyBbs', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean_c1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1', 'en/ciMean', 'v_ciMean_c1');
addPage_2('en/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2', 'en/ciMean', 'v_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3', 'en/ciMean', 'v_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4', 'en/ciMean', 'v_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5', 'en/ciMean', 'v_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6', 'en/ciMean', 'v_ciMean6');
addPage_2('bk/masseyBbs', 'ciExtra4a', "Other confidence levels", 'interact', 'bk/masseyBbs', 's_ciExtra4a', 'bk/masseyBbs', 'v_ciExtra4a');
addPage_2('en/ciMean', 'ciMean_c7', "Examples", 'static', 'en/ciMean', 's_ciMean_c7', 'en/ciMean', 'v_ciMean_c7');
addPage_2('en/ciMean', 'e_ciMean1', "#r#Exercise: #+#Find approx 95% CI from standard error", 'static');
addPage_2('en/ciMean', 'e_ciMean4', "#r#Exercise: #+#Find confidence intervals, known &sigma;", 'static');
addPage_2('en/ciMean', 'e_ciMean5', "#r#Exercise: #+#Find CIs, known and unknown &sigma;", 'static');
addPage_2('en/ciMean', 'e_ciMean6', "#r#Exercise: #+#What affects width of confidence interval", 'static');
addPage_2('en/ciMean', 'e_ciMean7', "#r#Exercise: #+#Interpret a 95% confidence interval", 'static');
addSection('bk/masseyBbs', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1', 'en/estPropn', 'v_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2', 'en/estPropn', 'v_estPropn2');
addPage_2('bk/masseyBbs', 'estPropn_c3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3', 'en/estPropn', 'v_estPropn_c3');
addPage_2('bk/masseyBbs', 'estPropn_c4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn_c4', 'en/estPropn', 'v_estPropn_c4');
addPage_2('bk/masseyBbs', 'estPropn_c5', "Confidence interval for proportion", 'static', 'bk/masseyBbs', 's_estPropn5', 'bk/masseyBbs', 'v_estPropn_c5');
addPage_2('bk/masseyBbs', 'ciExtra4b', "Other confidence levels", 'static', 'bk/masseyBbs', 's_ciExtra4b');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6', 'en/estPropn', 'v_estPropn6');
addPage_2('bk/masseyBbs', 'estPropn_c7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn_c7', 'bk/masseyBbs', 'v_estPropn_c7');
addPage_2('bk/masseyBbs', 'ciExtra1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1', 'en/ciExtra', 'v_ciExtra1');
addPage_2('en/estPropn', 'e_estPropn1', "#r#Exercise: #+#Find standard error of proportion", 'static');
addPage_2('en/estPropn', 'e_estPropn3', "#r#Exercise: #+#Find CI for probability", 'static');
addPage_2('en/estPropn', 'e_estPropn4', "#r#Exercise: #+#What affects width of CI?", 'static');
addPage_2('en/estPropn', 'e_estPropn5', "#r#Exercise: #+#Interpret a 95% confidence interval", 'static');

addChapter('bk/masseyBbs', 'ch_test', "Testing Hypotheses");
addSection('bk/masseyBbs', 'sec_testIntro', "Introduction to hypothesis testing");
addPage_2('en/testIntro', 'testIntro1', "Inference", 'static', 'en/testIntro', 's_testIntro1', 'en/testIntro', 'v_testIntro1');
addPage_2('bk/masseyBbs', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2', 'en/testIntro', 'v_testIntro2');
addPage_2('bk/masseyBbs', 'testIntro_c3', "Test for a proportion", 'interact', 'en/testIntro', 's_testIntro3', 'en/testIntro', 'v_testIntro_c3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4', 'en/testIntro', 'v_testIntro4');
addPage_2('bk/masseyBbs', 'testIntro_c7', "Common patterns in tests", 'static', 'bk/masseyBbs', 's_testIntro_c7', 'bk/masseyBbs', 'v_testIntro_c7');
addPage_2('bk/masseyBbs', 'testPropn6', "Statistical distance", 'static', 'bk/masseyBbs', 's_testPropn6', 'bk/masseyBbs', 'v_testPropn6');
addPage_2('bk/masseyBbs', 'testPropn7', "Tests based on statistical distance", 'static', 'bk/masseyBbs', 's_testPropn7', 'en/testPropn', 'v_testPropn7');
addPage_2('en/testIntro', 'e_testIntro1', "#r#Exercise: #+#Simulation to test a propn#?# (opt)", 'static');
addPage_2('en/testIntro', 'e_testIntro2', "#r#Exercise: #+#Simulation to test a mean#?# (opt)", 'static');
addSection('bk/masseyBbs', 'sec_testMean', "Tests about means");
addPage_2('bk/masseyBbs', 'testMean_c1', "Introduction", 'static', 'en/testMean', 's_testMean1', 'bk/masseyBbs', 'v_testMean1');
addPage_2('en/testMean', 'testMean_c2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2', 'en/testMean', 'v_testMean_c2');
addPage_2('en/testMean', 'testMean3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3', 'en/testMean', 'v_testMean3');
addPage_2('en/testMean', 'testMean_c4', "The t distribution", 'interact', 'en/testMean', 's_testMean4', 'en/testMean', 'v_testMean_c4');
addPage_2('en/testMean', 'testMean_c5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5', 'en/testMean', 'v_testMean_c5');
addPage_2('bk/masseyBbs', 'testMean6', "Testing with non-normal populations", 'static', 'bk/masseyBbs', 's_testMean6');
addPage_2('en/testMean', 'e_testMean1', "#r#Exercise: #+#  Test mean, with &sigma; known", 'static');
addPage_2('en/testMean', 'e_testMean2', "#r#Exercise: #+#  Test mean, unknown &sigma;", 'static');
addSection('bk/masseyBbs', 'sec_testPropn', "Tests about probabilities &amp; propns");
addPage_2('bk/masseyBbs', 'testPropn_c1', "Inference about categorical populations", 'static', 'bk/masseyBbs', 's_testPropn1', 'bk/masseyBbs', 'v_testPropn1');
addPage_2('en/testPropn', 'testPropn_c2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2', 'en/testPropn', 'v_testPropn_c2');
addPage_2('en/testPropn', 'testPropn_c3', "Another example", 'interact', 'en/testPropn', 's_testPropn_c3', 'en/testPropn', 'v_testPropn_c3');
addPage_2('en/testPropn', 'testPropn_c4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn_c4', 'en/testPropn', 'v_testPropn_c4');
addPage_2('bk/masseyBbs', 'testPropn5', "Tests based on normal approximation", 'interact', 'bk/masseyBbs', 's_testPropn5', 'bk/masseyBbs', 'v_testPropn5');
addPage_2('en/testPropn', 'e_testPropn1', "#r#Exercise: #+#Test using binomial distribution#?# (opt)", 'static');
addPage_2('bk/masseyBbs', 'e_testPropn2', "#r#Exercise: #+#Test with normal approximation", 'static');
addSection('bk/masseyBbs', 'sec_testMore', "More about testing");
addPage_2('en/decision', 'decision1', "Hypothesis tests and decisions", 'static', 'en/decision', 's_decision1', 'en/decision', 'v_decision1');
addPage_2('bk/masseyBbs', 'decision3', "Decisions and p-values", 'static', 'bk/masseyBbs', 's_decision3', 'bk/masseyBbs', 'v_decision3');
addPage_2('bk/masseyBbs', 'testPValue5', "P-values for other tests#?# (opt)", 'interact', 'en/testPValue', 's_testPValue5', 'en/testPValue', 'v_testPValue5');
addPage_2('en/testPValue', 'e_testPValue1', "#r#Exercise: #+#Interpret a p-value#?# (opt)", 'static');
addPage_2('en/testPValue', 'e_testPValue2', "#r#Exercise: #+#Interpret p-value in context#?# (opt)", 'static');
addPage_2('en/testPValue', 'e_testPValue3', "#r#Exercise: #+#Interpret p-value (harder)#?# (opt)", 'static');

addChapter('bk/masseyBbs', 'ch_compare', "Comparisons");
addSection('bk/masseyBbs', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel_c1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel_c1', 'en/twoGroupModel', 'v_twoGroupModel_c1');
addPage_2('en/twoGroupModel', 'twoGroupModel_c2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2', 'en/twoGroupModel', 'v_twoGroupModel_c2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3', 'en/twoGroupModel', 'v_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel_c4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4', 'en/twoGroupModel', 'v_twoGroupModel_c4');
addPage_2('en/twoGroupModel', 'twoGroupModel_c5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel_c5', 'en/twoGroupModel', 'v_twoGroupModel_c5');
addPage_2('bk/masseyBbs', 'twoGroupModel6', "Distribution of a difference", 'static', 'bk/masseyBbs', 's_twoGroupModel6', 'bk/masseyBbs', 'v_twoGroupModel6');
addSection('bk/masseyBbs', 'sec_twoGroupInf', "Are the means equal?");
addPage_2('en/twoGroupInf', 'twoGroupInf_c1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1', 'en/twoGroupInf', 'v_twoGroupInf_c1');
addPage_2('en/twoGroupInf', 'twoGroupInf_c2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf_c2', 'en/twoGroupInf', 'v_twoGroupInf_c2');
addPage_2('bk/masseyBbs', 'twoGroupInf_c4', "Are the means equal?", 'interact', 'en/twoGroupInf', 's_twoGroupInf_c4', 'bk/masseyBbs', 'v_twoGroupInf4');
addPage_2('bk/masseyBbs', 'twoGroupInf_c5', "One-tailed tests for differences", 'static', 'en/twoGroupInf', 's_twoGroupInf_c5', 'bk/masseyBbs', 'v_twoGroupInf5');
addPage_2('en/twoGroupInf', 'e_twoGroupInf3', "#r#Exercise:#+#  Test for two means being equal", 'static');
addSection('bk/masseyBbs', 'sec_testPaired', "Paired data");
addPage_2('en/testPaired', 'testPaired_c1', "Paired data", 'static', 'en/testPaired', 's_testPaired1', 'en/testPaired', 'v_testPaired_c1');
addPage_2('en/testPaired', 'testPaired_c2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2', 'en/testPaired', 'v_testPaired_c2');
addPage_2('en/testPaired', 'testPaired_c3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3', 'en/testPaired', 'v_testPaired_c3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4', 'en/testPaired', 'v_testPaired4');
addPage_2('en/testPaired', 'e_testPaired1', "#r#Exercise:#+#  Paired or two-sample test?", 'static');
addPage_2('en/testPaired', 'e_testPaired2', "#r#Exercise:#+#  Conduct a paired t-test", 'static');
addSection('bk/masseyBbs', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('bk/masseyBbs', 'twoGroupPropn_c1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn_c1', 'en/twoGroupPropn', 'v_twoGroupPropn_c1');
addPage_2('bk/masseyBbs', 'twoGroupPropn2b', "Distribution of difference in proportions", 'interact', 'bk/masseyBbs', 's_twoGroupPropn2b');
addPage_2('bk/masseyBbs', 'twoGroupPropn4', "Testing for difference in probabilities", 'static', 'bk/masseyBbs', 's_twoGroupPropn4', 'bk/masseyBbs', 'v_twoGroupPropn4');
addPage_2('en/twoGroupPropn', 'e_twoGroupPropn2', "#r#Exercise:#+#  Are probabilities in two groups equal?", 'static');
addSection('bk/masseyBbs', 'sec_continTest', "Contingency table tests");
addPage_2('bk/masseyBbs', 'indep_c3', "Independence from samples", 'static', 'en/indep', 's_indep3', 'en/indep', 'v_indep_c3');
addPage_2('bk/masseyBbs', 'indep_c4', "Testing for independence", 'interact', 'bk/masseyBbs', 's_indep4', 'bk/masseyBbs', 'v_indep_c4');
addPage_2('bk/masseyBbs', 'indep5', "Chi-squared distribution", 'interact', 'bk/masseyBbs', 's_indep5', 'bk/masseyBbs', 'v_indep5');
addPage_2('en/indep', 'indep6', "P-value for chi-squared test", 'interact', 'en/indep', 's_indep6', 'en/indep', 'v_indep6');
addPage_2('en/indep', 'indep_c7', "Examples", 'static', 'en/indep', 's_indep_c7', 'en/indep', 'v_indep_c7');
addPage_2('en/indep', 'indep_c8', "Comparing groups", 'static', 'en/indep', 's_indep_c8', 'en/indep', 'v_indep_c8');
addPage_2('en/indep', 'e_indep1', "#r#Exercise:#+#  Expected cell counts", 'static');
addPage_2('en/indep', 'e_indep2', "#r#Exercise:#+#  Chi-squared test", 'static');

addChapter('bk/masseyBbs', 'ch_regn', "Regression");
addSection('bk/masseyBbs', 'sec_simpleRegn', "Simple linear regression");
addPage_2('bk/masseyBbs', 'leastSqrs2', "Linear models", 'interact', 'bk/masseyBbs', 's_leastSqrs2', 'bk/masseyBbs', 'v_leastSqrs2');
addPage_2('bk/masseyBbs', 'leastSqrs3', "Predictions and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3', 'en/leastSqrs', 'v_leastSqrs3');
addPage_2('bk/masseyBbs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4', 'en/leastSqrs', 'v_leastSqrs4');
addPage_2('bk/masseyBbs', 'regnModel_c1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel_c1', 'en/regnModel', 'v_regnModel_c1');
addPage_2('bk/masseyBbs', 'regnModel_c2', "Normal linear model", 'interact', 'bk/masseyBbs', 's_regnModel2', 'en/regnModel', 'v_regnModel_c2');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4', 'en/regnModel', 'v_regnModel4');
addPage_2('bk/masseyBbs', 'regnModel_c5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel_c5', 'en/regnModel', 'v_regnModel_c5');
addPage_2('en/leastSqrs', 'e_leastSqrs1', "#r#Exercise: #+#Pick the explanatory variable and response", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs2', "#r#Exercise: #+#Draw a straight line", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs3', "#r#Exercise: #+#Find the slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs4', "#r#Exercise: #+#Interpret the slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs5', "#r#Exercise: #+#Find a residual", 'static');
addSection('bk/masseyBbs', 'sec_regnAssumptions', "Linear model assumptions");
addPage_2('bk/masseyBbs', 'regnProblem1', "Assumptions in a normal linear model", 'static', 'bk/masseyBbs', 's_regnProblem1', 'bk/masseyBbs', 'v_regnProblem1');
addPage_2('bk/masseyBbs', 'leastSqrs6', "Residual plots", 'interact', 'bk/masseyBbs', 's_leastSqrs6', 'bk/masseyBbs', 'v_leastSqrs6');
addPage_2('bk/masseyBbs', 'regnProblem6', "Probability plot of residuals", 'interact', 'en/regnProblem', 's_regnProblem6', 'en/regnProblem', 'v_regnProblem6');
addPage_2('bk/masseyBbs', 'leastSqrs5', "Outliers", 'interact', 'bk/masseyBbs', 's_leastSqrs5', 'en/leastSqrs', 'v_leastSqrs5');
addPage_2('bk/masseyBbs', 'regnProblem5', "Standardised residuals#?# (opt)", 'interact', 'bk/masseyBbs', 's_regnProblem5', 'bk/masseyBbs', 'v_regnProblem5');
addPage_2('bk/masseyBbs', 'regnLeverage', "Outliers and leverage#?# (opt)", 'interact', 'bk/masseyBbs', 's_regnLeverage', 'bk/masseyBbs', 'v_regnLeverage');
addPage_2('en/leastSqrs', 'e_leastSqrs6', "#r#Exercise: #+#Pick the correct residual plot", 'static');
addPage_2('en/curvature', 'e_curvature1', "#r#Exercise: #+#Identify regression problems#?# (opt)", 'static');
addSection('bk/masseyBbs', 'sec_regnInference', "Inference for regression parameters");
addPage_2('en/regnEst', 'regnEst_c1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1', 'en/regnEst', 'v_regnEst_c1');
addPage_2('bk/masseyBbs', 'regnEst_c2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2', 'en/regnEst', 'v_regnEst_c2');
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3', 'en/regnEst', 'v_regnEst3');
addPage_2('bk/masseyBbs', 'regnEst_c4', "Standard error of least squares slope", 'interact', 'bk/masseyBbs', 's_regnEst4', 'en/regnEst', 'v_regnEst_c4');
addPage_2('bk/masseyBbs', 'regnTest_c2', "Testing whether slope is zero", 'static', 'bk/masseyBbs', 's_regnTest2', 'en/regnTest', 'v_regnTest_c2');
addPage_2('bk/masseyBbs', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3', 'en/regnTest', 'v_regnTest3');
addPage_2('en/regnEst', 'e_regnEst1', "#r#Exercise:#+#  Standard error of slope", 'static');
addPage_2('en/regnEst', 'e_regnEst2', "#r#Exercise:#+#  Confidence interval for slope", 'static');
addPage_2('en/regnTest', 'e_regnTest1', "#r#Exercise:#+#  Test for zero slope", 'static');
addSection('bk/masseyBbs', 'sec_regnPred', "Predicting the response");
addPage_2('bk/masseyBbs', 'regnPred0', "Point estimates of the response", 'interact', 'bk/masseyBbs', 's_regnPred0');
addPage_2('bk/masseyBbs', 'regnPred1', "Estimated response distn at X#?# (opt)", 'interact', 'en/regnPred', 's_regnPred1', 'en/regnPred', 'v_regnPred1');
addPage_2('en/regnPred', 'regnPred2', "Variability of estimate at X#?# (opt)", 'interact', 'en/regnPred', 's_regnPred2', 'en/regnPred', 'v_regnPred2');
addPage_2('en/regnPred', 'regnPred_c3', "Estimating the mean vs prediction#?# (opt)", 'interact', 'en/regnPred', 's_regnPred3', 'en/regnPred', 'v_regnPred_c3');
addPage_2('en/regnPred', 'regnPred4', "Confidence & prediction intervals#?# (opt)", 'interact', 'en/regnPred', 's_regnPred4', 'en/regnPred', 'v_regnPred4');
addPage_2('en/leastSqrs', 'e_leastSqrs7', "#r#Exercise: #+#Predict the response", 'static');
addSection('bk/masseyBbs', 'sec_regnAnova', "Coefficient of determination");
addPage_2('bk/masseyBbs', 'regnAnova1', "Sums of squares", 'interact', 'bk/masseyBbs', 's_regnAnova1');
addPage_2('en/regnAnova', 'regnAnova3', "Coefficient of determination", 'interact', 'bk/masseyBbs', 's_regnAnova2');
addSection('bk/masseyBbs', 'sec_multiRegn', "Multiple regression");
addPage_2('en/multiRegn', 'multiRegn1', "More than one explanatory variable", 'interact', 'en/multiRegn', 's_multiRegn1', 'en/multiRegn', 'v_multiRegn1');
addPage_2('bk/masseyBbs', 'multiRegn2', "Multiple regression equation", 'interact', 'en/multiRegn', 's_multiRegn2', 'en/multiRegn', 'v_multiRegn2');
addPage_2('en/glm', 'glm5', "Interpreting coefficients", 'interact', 'en/multiRegn', 's_multiRegn3');
addPage_2('bk/masseyBbs', 'glm6', "Standard errors", 'interact', 'bk/masseyBbs', 's_glm6');
addPage_2('bk/masseyBbs', 'glm7', "Inference for general linear models", 'interact', 'bk/masseyBbs', 's_glm7');
addSection('bk/masseyBbs', 'important_regn', "What will be assessed?");

addChapter('bk/masseyBbs', 'ch_timeSeries', "Time Series Analysis");
addSection('bk/masseyBbs', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1', 'en/timePlot', 'v_timePlot1');
addPage_2('en/timePlot', 'timePlot_c2', "Patterns in time series", 'interact', 'en/timePlot', 's_timePlot2', 'en/timePlot', 'v_timePlot_c2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3', 'en/timePlot', 'v_timePlot3');
addPage_2('en/timePlot', 'e_timePlot1', "#r#Exercise: #+#Identify time series patterns", 'static');
addSection('bk/masseyBbs', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1', 'en/smoothing', 'v_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2', 'en/smoothing', 'v_smoothing2');
addPage_2('en/smoothing', 'smoothing3', "Robust smoothing#?# (opt)", 'interact', 'en/smoothing', 's_smoothing3', 'en/smoothing', 'v_smoothing3');
addPage_2('en/smoothing', 'smoothing4', "Exponential smoothing", 'interact', 'en/smoothing', 's_smoothing4', 'en/smoothing', 'v_smoothing4');
addPage_2('en/smoothing', 'e_smoothing1', "#r#Exercise: #+#Find smoothed values", 'static');
addSection('bk/masseyBbs', 'sec_trend', "Long-term trend");
addPage_2('bk/masseyBbs', 'trend1', "Linear trend", 'interact', 'en/trend', 's_trend1', 'bk/masseyBbs', 'v_trend1');
addPage_2('en/trend', 'trend2', "Quadratic trend#?# (opt)", 'interact', 'en/trend', 's_trend2', 'en/trend', 'v_trend2');
addPage_2('en/trend', 'trend3', "Forecasting", 'interact', 'en/trend', 's_trend3', 'en/trend', 'v_trend3');
addPage_2('en/trend', 'trend5', "Detrending a time series", 'interact', 'en/trend', 's_trend5', 'en/trend', 'v_trend5');
addPage_2('en/trend', 'e_trend1', "#r#Exercise: #+#Forecast a future value", 'static');
addSection('bk/masseyBbs', 'sec_seasonal', "Seasonal data");
addPage_2('en/seasonal', 'seasonal1', "Seasonal patterns", 'interact', 'en/seasonal', 's_seasonal1', 'en/seasonal', 'v_seasonal1');
addPage_2('en/seasonal', 'seasonal2', "Smoothing out seasonal variation", 'interact', 'en/seasonal', 's_seasonal2', 'en/seasonal', 'v_seasonal2');
addPage_2('en/seasonal', 'seasonal3', "Estimating the seasonal effect", 'interact', 'en/seasonal', 's_seasonal3', 'en/seasonal', 'v_seasonal3');
addPage_2('en/seasonal', 'seasonal4', "Deseasonalised data", 'interact', 'en/seasonal', 's_seasonal4', 'en/seasonal', 'v_seasonal4');
addSection('bk/general', 'sec_indexNos', "Index numbers");
addPage_2('en/indexNos', 'indexNos1', "Introduction", 'static', 'en/indexNos', 's_indexNos1', 'en/indexNos', 'v_indexNos1');
addPage_2('en/indexNos', 'indexNos2', "Simple price index", 'static', 'en/indexNos', 's_indexNos2', 'en/indexNos', 'v_indexNos2');
addPage_2('en/indexNos', 'indexNos3', "Aggregate price index", 'static', 'en/indexNos', 's_indexNos3', 'en/indexNos', 'v_indexNos3');
addPage_2('en/indexNos', 'indexNos4', "Laspeyres and Paasche indices", 'static', 'en/indexNos', 's_indexNos4', 'en/indexNos', 'v_indexNos4');
addPage_2('en/indexNos', 'indexNos5', "Deflating a time series", 'static', 'en/indexNos', 's_indexNos5', 'en/indexNos', 'v_indexNos5');
addSection('bk/masseyBbs', 'sec_multiplicative', "Multiplicative models and more");
addPage_2('en/multiplicative', 'multiplicative1', "Additive and multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative1', 'en/multiplicative', 'v_multiplicative1');
addPage_2('en/multiplicative', 'multiplicative2', "Properties of multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative2', 'en/multiplicative', 'v_multiplicative2');
addPage_2('en/multiplicative', 'multiplicative3', "Forecasting with multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative3', 'en/multiplicative', 'v_multiplicative3');
addPage_2('en/multiplicative', 'multiplicative4', "Analysing the right data#?# (opt)", 'static', 'en/multiplicative', 's_multiplicative4', 'en/multiplicative', 'v_multiplicative4');
addPage_2('en/multiplicative', 'multiplicative5', "Types of time series data#?# (opt)", 'static', 'en/multiplicative', 's_multiplicative5', 'en/multiplicative', 'v_multiplicative5');
addSection('bk/masseyBbs', 'important_timeSeries', "What will be assessed?");

addChapter('bk/masseyBbs', 'ch_tqm', "Control Charts");
addSection('bk/masseyBbs', 'sec_tqm', "Total quality management");
addPage_2('bk/masseyBbs', 'tqm1', "Introduction", 'static', 'bk/masseyBbs', 's_tqm1');
addPage_2('bk/masseyBbs', 'context3', "The statistical process", 'static', 'en/context', 's_context3', 'bk/masseyBbs', 'v_context3');
addPage_2('bk/masseyBbs', 'controlChart9', "Finding the cause of problems", 'interact', 'en/controlChart', 's_controlChart9', 'en/controlChart', 'v_controlChart9');
addSection('bk/masseyBbs', 'sec_controlBasics', "Control chart basics");
addPage_2('bk/masseyBbs', 'controlChart1', "Introduction", 'static', 'bk/masseyBbs', 's_controlChart1', 'en/controlChart', 'v_controlChart1');
addPage_2('bk/masseyBbs', 'controlChart2', "Run charts", 'interact', 'en/controlChart', 's_controlChart2', 'en/controlChart', 'v_controlChart2');
addPage_2('en/controlChart', 'controlChart3', "Control limits", 'interact', 'en/controlChart', 's_controlChart3', 'en/controlChart', 'v_controlChart3');
addPage_2('bk/masseyBbs', 'controlChart4', "Other signals of being out-of-control", 'interact', 'bk/masseyBbs', 's_controlChart4', 'bk/masseyBbs', 'v_controlChart4');
addPage_2('en/controlChart', 'controlChart5', "False alarms", 'interact', 'en/controlChart', 's_controlChart5', 'en/controlChart', 'v_controlChart5');
addPage_2('en/controlChart', 'controlChart6', "Examples of run charts", 'interact', 'en/controlChart', 's_controlChart6', 'en/controlChart', 'v_controlChart6');
addSection('bk/masseyBbs', 'sec_controlPractice', "Control charts in practice");
addPage_2('bk/masseyBbs', 'controlPractice1', "Control charts based on samples", 'static', 'bk/masseyBbs', 's_controlPractice1');
addPage_2('bk/masseyBbs', 'controlPractice2', "Control charts for means", 'interact', 'bk/masseyBbs', 's_controlPractice2');
addPage_2('bk/masseyBbs', 'controlPractice3', "Control charts for ranges", 'interact', 'bk/masseyBbs', 's_controlPractice3');
addPage_2('bk/masseyBbs', 'controlPractice4', "Control charts for proportions", 'static', 'bk/masseyBbs', 's_controlPractice4');
addPage_2('bk/masseyBbs', 'controlPractice5', "Final comments", 'static', 'bk/masseyBbs', 's_controlPractice5');
addSection('bk/masseyBbs', 'important_controlCharts', "What will be assessed?");

var language = "en";
var logoGif = "logo_massey.gif";
var homeDir = "bk/masseyBbs";
var versionGif = "../business/images/castBusiness";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = "http://castAdmin2.massey.ac.nz/pdf/masseyBbs";
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "12";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'++': 'Custom', '_g': 'General', '_b': 'Biometric', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('+c', '_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('+g', '_g', '_m', '_o');
versions['variation4'] = new Array('+g', '_g', '_a');
versions['structures1'] = new Array('+c', '_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_c', '_g', '_a', '_b');
versions['structures3'] = new Array('+c', '_g', '_c', '_o');
versions['structures4'] = new Array('_c', '_g', '_a');
versions['causal1'] = new Array('+c', '_g', '_b', '_c');
versions['causal4'] = new Array('+g', '_g', '_b', '_c');
versions['popSamp1'] = new Array('_c', '_g', '_a', '_b');
versions['popSamp2'] = new Array('_c', '_g');
versions['popSamp3'] = new Array('+c', '_g', '_a', '_b', '_c');
versions['popSamp6'] = new Array('+g', '_g');
versions['sampPractice1'] = new Array('+g', '_g', '_b');
versions['sampPractice2'] = new Array('+g', '_g');
versions['sampPractice3'] = new Array('+g', '_g');
versions['sampPractice4'] = new Array('+g', '_g');
versions['sampPractice5'] = new Array('+g', '_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['sampPractice7'] = new Array('+g', '_g');
versions['freqTable1'] = new Array('+c', '_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('+g', '_g', '_a', '_b');
versions['univarCat2'] = new Array('+g', '_g');
versions['univarCat3'] = new Array('+g', '_g', '_a', '_b');
versions['univarCat4'] = new Array('+c', '_g', '_b', '_c');
versions['univarCat5'] = new Array('_c', '_g', '_b');
versions['univarCat6'] = new Array('_c', '_g', '_b');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('+c', '_g', '_c');
versions['groupedCat2'] = new Array('+c', '_g', '_b', '_c');
versions['groupedCat3'] = new Array('+c', '_g', '_b', '_c');
versions['groupedCat4'] = new Array('_c', '_g', '_b');
versions['groupedCat5'] = new Array('_c', '_g', '_b');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_c', '_g', '_b', '_m');
versions['valueDisplay5'] = new Array('+c', '_g', '_a', '_b', '_c', '_m');
versions['valueDisplay6'] = new Array('+c', '_g', '_c', '_m');
versions['valueDisplay7'] = new Array('+c', '_g', '_c', '_m');
versions['valueDisplay3'] = new Array('+c', '_g', '_b', '_c', '_m');
versions['density2'] = new Array('+g', '_g');
versions['density3'] = new Array('+c', '_g', '_c', '_m');
versions['density4'] = new Array('_c', '_g', '_b', '_m');
versions['density11'] = new Array('+g', '_g', '_b', '_c', '_m');
versions['density7'] = new Array('+g', '_g', '_b', '_c', '_m');
versions['e_density1'] = new Array('+g', '_g');
versions['displayInterp1'] = new Array('_c', '_g', '_b');
versions['displayInterp2'] = new Array('_c', '_g', '_b', '_m');
versions['displayInterp3'] = new Array('_c', '_g', '_m');
versions['displayInterp6'] = new Array('_g', '_b', '_c');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('+c', '_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_c', '_g');
versions['centerSpread8'] = new Array('+g', '_g');
versions['displayInterp5'] = new Array('+g', '_g');
versions['density6'] = new Array('+c', '_g', '_b', '_c');
versions['density9'] = new Array('+c', '_g', '_c');
versions['boxPlot1'] = new Array('+g', '_g');
versions['boxPlot2'] = new Array('+g', '_g');
versions['boxPlot6'] = new Array('_c', '_g');
versions['boxPlot7'] = new Array('_g', '_b');
versions['e_boxPlot1'] = new Array('+g', '_g');
versions['scatterplot1'] = new Array('_c', '_g', '_b');
versions['scatterplot2'] = new Array('_c', '_g');
versions['scatterplot4'] = new Array('_c', '_g');
versions['relationship1'] = new Array('_c', '_g');
versions['relationship2'] = new Array('+c', '_g');
versions['relationship3'] = new Array('_c', '_g');
versions['relationship4'] = new Array('_c', '_g');
versions['relationship5'] = new Array('_c', '_g');
versions['correlation1'] = new Array('_c', '_g', '_b');
versions['correlation5'] = new Array('+g', '_g');
versions['indep1'] = new Array('+c', '_g', '_b', '_c');
versions['indep2'] = new Array('+c', '_g', '_c');
versions['randomPropn2'] = new Array('_c', '_g');
versions['randomPropn3'] = new Array('_c', '_g', '_b');
versions['binomial3'] = new Array('+g', '_g');
versions['binomial4'] = new Array('+g', '_g');
versions['binomial5'] = new Array('+g', '_g');
versions['probDensity5'] = new Array('+c', '_g', '_c');
versions['normalDistn3'] = new Array('_c', '_g', '_b');
versions['normalDistn10'] = new Array('+g', '_g');
versions['normalDistn6'] = new Array('_c', '_g', '_b');
versions['normalDistn7'] = new Array('_c', '_g', '_b');
versions['e_normalDistn3'] = new Array('+g', '_g');
versions['e_normalDistn5'] = new Array('+g', '_g');
versions['randomPropn5'] = new Array('+g', '_g');
versions['randomPropn6'] = new Array('_c', '_g', '_b');
versions['randomMean1'] = new Array('_c', '_g', '_b');
versions['randomMean6'] = new Array('+c', '_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['estIntro1'] = new Array('_c', '_g', '_b');
versions['estIntro2'] = new Array('_c', '_g', '_b');
versions['estIntro3'] = new Array('+g', '_g', '_m');
versions['estIntro4'] = new Array('_c', '_g', '_m');
versions['estIntro5'] = new Array('_c', '_g', '_b');
versions['seMean1'] = new Array('_c', '_g', '_b');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_c', '_g', '_b');
versions['seMean6'] = new Array('_c', '_g', '_b');
versions['ciMean1'] = new Array('_c', '_g', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_c', '_g', '_b');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('+c', '_g', '_b', '_c');
versions['estPropn4'] = new Array('+c', '_g', '_b', '_c');
versions['estPropn5'] = new Array('+c', '_g', '_b', '_c');
versions['estPropn7'] = new Array('+c', '_g', '_b', '_c');
versions['ciExtra1'] = new Array('+g', '_g', '_b', '_c');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro2'] = new Array('+g', '_g');
versions['testIntro3'] = new Array('+c', '_g', '_b', '_c');
versions['testIntro7'] = new Array('+c', '_g', '_b', '_c');
versions['testPropn6'] = new Array('+g', '_g');
versions['testPropn7'] = new Array('+g', '_g', '_b');
versions['testMean1'] = new Array('+c', '_g', '_c');
versions['testMean2'] = new Array('_c', '_g');
versions['testMean3'] = new Array('_g', '_b');
versions['testMean4'] = new Array('_c', '_g');
versions['testMean5'] = new Array('_c', '_g');
versions['testPropn1'] = new Array('+c', '_g', '_b', '_c');
versions['testPropn2'] = new Array('_c', '_g', '_b');
versions['testPropn3'] = new Array('_c', '_g', '_b');
versions['testPropn4'] = new Array('_c', '_g', '_b');
versions['testPropn5'] = new Array('+g', '_g', '_b');
versions['e_testPropn2'] = new Array('+g', '_g');
versions['decision3'] = new Array('+g', '_g');
versions['testPValue5'] = new Array('+g', '_g', '_b', '_c');
versions['twoGroupModel1'] = new Array('_c', '_g', '_b');
versions['twoGroupModel2'] = new Array('_c', '_g', '_b');
versions['twoGroupModel4'] = new Array('_c', '_g');
versions['twoGroupModel5'] = new Array('_c', '_g');
versions['twoGroupInf1'] = new Array('_c', '_g');
versions['twoGroupInf2'] = new Array('_c', '_g', '_b');
versions['twoGroupInf4'] = new Array('+c', '_g', '_b', '_c');
versions['twoGroupInf5'] = new Array('+c', '_g', '_b', '_c');
versions['testPaired1'] = new Array('_c', '_g', '_b');
versions['testPaired2'] = new Array('_c', '_g', '_b');
versions['testPaired3'] = new Array('_c', '_g');
versions['twoGroupPropn1'] = new Array('+c', '_g', '_c');
versions['twoGroupPropn4'] = new Array('+g', '_g', '_c');
versions['e_twoGroupPropn2'] = new Array('_g', '_b', '_c');
versions['indep3'] = new Array('+c', '_g', '_c');
versions['indep4'] = new Array('+c', '_g', '_c');
versions['indep5'] = new Array('+g', '_g');
versions['indep7'] = new Array('_c', '_g');
versions['indep8'] = new Array('_c', '_g');
versions['leastSqrs2'] = new Array('+g', '_g');
versions['leastSqrs3'] = new Array('+g', '_g', '_c');
versions['leastSqrs4'] = new Array('+g', '_g');
versions['regnModel1'] = new Array('+c', '_g', '_b', '_c');
versions['regnModel2'] = new Array('+c', '_g', '_c');
versions['regnModel5'] = new Array('+c', '_g', '_b', '_c');
versions['regnProblem1'] = new Array('+g', '_g');
versions['leastSqrs6'] = new Array('+g', '_g', '_c');
versions['regnProblem6'] = new Array('+g', '_g', '_c');
versions['leastSqrs5'] = new Array('+g', '_g');
versions['regnProblem5'] = new Array('+g', '_g');
versions['regnEst1'] = new Array('_c', '_g');
versions['regnEst2'] = new Array('+c', '_g', '_c');
versions['regnEst4'] = new Array('+c', '_g', '_c');
versions['regnTest2'] = new Array('+c', '_g', '_c');
versions['regnTest3'] = new Array('+g', '_g');
versions['regnPred1'] = new Array('+g', '_g', '_b', '_c');
versions['regnPred3'] = new Array('_c', '_g', '_b');
versions['regnPred4'] = new Array('_g', '_b');
versions['regnAnova1'] = new Array('+g', '_g');
versions['multiRegn2'] = new Array('+g', '_g');
versions['glm6'] = new Array('+g', '_g');
versions['glm7'] = new Array('+g', '_g');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_c', '_g', '_b');
versions['trend1'] = new Array('+g', '_g');
versions['seasonal1'] = new Array('_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['context3'] = new Array('+g', '_g', '_b');
versions['controlChart9'] = new Array('+g', '_g');
versions['controlChart1'] = new Array('+g', '_g');
versions['controlChart2'] = new Array('+g', '_g');
versions['controlChart4'] = new Array('+g', '_g');

bookLoaded = true;
