
addBook('bk/german_b', 'book_splash', "&Uuml;ber CAST e-Books");

addChapter('bk/german', 'ch_preface', "Vorwort");
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/german', 'ch_intro', "Einf&uuml;hrung: Daten");
addSection('bk/german_b', 'sec_context', "Kontext");
addPage_2('de/context', 'context_b1', "Die Bedeutung des Kontexts", 'static');
addPage_2('de/context', 'context2', "Statistik", 'static');
addPage_2('de/context', 'context3', "Der statistische Prozess", 'static');
addSection('bk/german_b', 'sec_structures', "Standard Datenstrukturen");
addPage_2('de/structures', 'structures_b1', "Variablen und Individuen", 'interact');
addPage_2('de/structures', 'structures_b2', " Arten von Variablen", 'interact');
addPage_2('de/structures', 'structures3', "Kategoriale Variablen und Gruppen", 'interact');
addPage_2('de/structures', 'structures4', "Neue Variablen definieren", 'interact');
addPage_2('de/structures', 'structures_b5', "Zeitlich geordnete Daten", 'static');
addPage_2('de/structures', 'structures_b6', "Multi-level Daten", 'interact');
addPage_2('de/structures', 'structures7', "Von der Datenstruktur zur statistischen Methode", 'static');
addSection('bk/german_b', 'sec_variation', "Variation");
addPage_2('de/variation', 'variation1', "Signal und Rauschen", 'interact');
addPage_2('de/variation', 'variation2', "Nat&uuml;rliche Variabilit&auml;t", 'interact');
addPage_2('de/variation', 'variation3', "Durch Experimente verursachte Variabilit&auml;t", 'interact');
addPage_2('de/variation', 'variation4', "Variabilit&auml;t in Daten aus Frageb&ouml;gen", 'interact');
addPage_2('de/variation', 'variation_b5', "Erkl&auml;rte und unerkl&auml;rte Variation", 'static');
addPage_2('de/variation', 'variation6', "Vorhersage zuk&uuml;nftiger Werte", 'static');

addChapter('bk/german', 'ch_univar', "Eine metrische Variable");
addSection('bk/german_b', 'sec_valueDisplay', "Grafische Darstellung der Werte");
addPage_2('de/valueDisplay', 'valueDisplay_b1', "Analyse der Variation", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay_b2', "Einfache Dotplots", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay_b3', "Jittered Dotplots", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay_b4', "Gestapelte Dotplots", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay_b5', "Ast-Blatt-Diagramm", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay6', "Die St&auml;mme aufteilen", 'interact');
addPage_2('de/valueDisplay', 'valueDisplay7', "Zeichnen von Ast-Blatt-Diagrammen", 'interact');
addSection('bk/german_b', 'sec_displayInterp', "Verteilungen verstehen");
addPage_2('de/displayInterp', 'displayInterp_b1', "Ausreisser", 'static');
addPage_2('de/displayInterp', 'displayInterp_b2', "Cluster", 'interact');
addPage_2('de/displayInterp', 'displayInterp3', "Verteilung der Werte", 'static');
addPage_2('de/displayInterp', 'displayInterp_b4', "Zusätzliche Information zu den Individuen", 'interact');
addPage_2('de/displayInterp', 'displayInterp5', "Bekannte Gruppen unterscheiden", 'interact');
addPage_2('de/displayInterp', 'displayInterp6', "Gefahr der Überinterpretation", 'interact');
addSection('bk/german_b', 'sec_density', "Histogramme und Dichte");
addPage_2('de/density', 'density1', "Dichte der Werte", 'static');
addPage_2('de/density', 'density2', "Histogrammemit einheitlichen Klassenbreiten", 'interact');
addPage_2('de/density', 'density3', "Wahl der Klassenbreite", 'interact');
addPage_2('de/density', 'density_b4', "Histogramme kleiner Datensätze", 'interact');
addPage_2('de/density', 'density5', "Relative Häufigkeit und Fläche", 'interact');
addPage_2('de/density', 'density_b6', "Gruppen vergleichen", 'interact');
addPage_2('de/density', 'density_b7', "Histogramme mit variierenden Klassenbreiten", 'interact');
addPage_2('de/density', 'density8', "Histogramme verstehen", 'interact');
addPage_2('de/density', 'density9', "Summenpolygone", 'interact');
addPage_2('de/density', 'density10', "Kerndichteschätzungen", 'interact');
addPage_2('de/density', 'density_b11', "Drawing histograms by hand", 'interact');
addSection('bk/german_b', 'sec_boxPlot', "Median, Quartile &amp; Boxplots");
addPage_2('de/boxPlot', 'boxPlot1', "Warum ist das Zusammenfassen von Daten wichtig?", 'static');
addPage_2('de/boxPlot', 'boxPlot2', "Median, Quartile und Boxplot", 'interact');
addPage_2('de/boxPlot', 'boxPlot3', "Interpretieren der Form eines Boxplots", 'interact');
addPage_2('de/boxPlot', 'boxPlot4', "Ausreisser darstellen", 'interact');
addPage_2('de/boxPlot', 'boxPlot5', "Cluster", 'interact');
addPage_2('de/boxPlot', 'boxPlot6', "Vergleich von Gruppen", 'interact');
addPage_2('de/boxPlot', 'boxPlot_b7', "Die Gefahr der Überinterpretation", 'interact');
addSection('bk/german_b', 'sec_centerSpread', "Lage und Streuung beschreiben");
addPage_2('de/centerSpread', 'centerSpread_b1', "Lage und Streuung", 'static');
addPage_2('de/centerSpread', 'centerSpread_b2', "Median, Spannbreite und Interquartilsbreite", 'interact');
addPage_2('de/centerSpread', 'centerSpread_b3', "Lagemaße", 'interact');
addPage_2('de/centerSpread', 'centerSpread4', "Eigenschaften von Mittelwert und Median", 'interact');
addPage_2('de/centerSpread', 'centerSpread5', "Standardabweichung", 'interact');
addPage_2('de/centerSpread', 'centerSpread6', "Faustregel für die Standardabweichung", 'static');
addPage_2('de/centerSpread', 'centerSpread7', "Standardabweichungen und Mittelwerte verstehen", 'interact');
addPage_2('de/centerSpread', 'centerSpread8', "Warnung für den Gebrauch der Standardabweichung und des Mittelwerts", 'static');
addSection('bk/german', 'sec_moreVariation', "Mehr über Variation (optional)");
addPage_2('de/moreVariation', 'moreVariation1', "Effekte von Ausreissern", 'interact');
addPage_2('de/moreVariation', 'moreVariation2', "Standardabweichung gruppierter Daten", 'interact');
addPage_2('de/moreVariation', 'moreVariation3', "Erklärte Variation und Vorhersagen", 'interact');
addPage_2('de/moreVariation', 'moreVariation4', "Varianz und Freiheitsgrad", 'static');
addPage_2('de/moreVariation', 'moreVariation5', "Mittlerer quadratischer Fehler", 'interact');
addPage_2('de/moreVariation', 'moreVariation6', "Graphische Interpretation der Standardabweichung", 'interact');
addSection('bk/german', 'sec_percentile', "Proportionen und Perzentile");
addPage_2('de/percentile', 'percentile1', "Illustrative data set", 'interact');
addPage_2('de/percentile', 'percentile2', "Cumulative proportions", 'interact');
addPage_2('de/percentile', 'percentile3', "Graph of cumulative proportions", 'interact');
addPage_2('de/percentile', 'percentile4', "Percentiles", 'interact');
addPage_2('de/percentile', 'percentile5', "Displaying percentiles", 'interact');
addPage_2('de/percentile', 'percentile6', "Comparing groups", 'interact');
addPage_2('de/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact');
addPage_2('de/percentile', 'percentile8', "Better definition of percentiles", 'interact');
addSection('bk/german_b', 'sec_transform', "Transformationen");
addPage_2('de/transform', 'transform_b1', "Lineare Transformationen", 'interact');
addPage_2('de/transform', 'transform_b2', "Log-Transformationen", 'interact');
addPage_2('de/transform', 'transform3', "Wann benutzt man die log-Transformation?", 'interact');
addPage_2('de/transform', 'transform4', "Potenz-Transformationen", 'interact');
addPage_2('de/transform', 'transform5', "Effekt von Transformationen auf die Darstellung", 'interact');
addSection('bk/german_b', 'sec_counts', "Diskrete Daten (Zähldaten)");
addPage_2('de/counts', 'counts_b1', "Diskrete und stetige Daten", 'interact');
addPage_2('de/counts', 'counts_b2', "Histogramme von Zähldaten", 'interact');
addPage_2('de/counts', 'counts3', "Balkendiagramme", 'interact');
addPage_2('de/counts', 'counts_b4', "Mittelwert und Standardabweichung", 'static');

addChapter('bk/german_b', 'ch_bivar', "Zwei metrische Variablen");
addSection('bk/german_b', 'sec_scatterplot', "Steudiagramme");
addPage_2('de/scatterplot', 'scatterplot_b1', "Bivariate Datens&auml;tze", 'interact');
addPage_2('de/scatterplot', 'scatterplot2', "Streudiagramme", 'interact');
addPage_2('de/scatterplot', 'scatterplot3', "Grenzen univariater Darstellungsformen", 'interact');
addPage_2('de/scatterplot', 'scatterplot4', "Randverteilungen", 'interact');
addPage_2('de/scatterplot', 'scatterplot5', "Zeitreihen", 'interact');
addSection('bk/german', 'sec_relationship', "Zusammenhänge verstehen");
addPage_2('de/relationship', 'relationship1', "St&auml;rke des Zusammenhangs", 'interact');
addPage_2('de/relationship', 'relationship2', "Ausreisser", 'interact');
addPage_2('de/relationship', 'relationship3', "Cluster", 'interact');
addPage_2('de/relationship', 'relationship4', "Gefahr der &Uuml;berinterpretation", 'interact');
addPage_2('de/relationship', 'relationship5', "Einflussvariable und Zielvariable", 'static');
addSection('bk/german_b', 'sec_correlation', "Korrelation");
addPage_2('de/correlation', 'correlation_b1', "Stärke des Zusammenhangs zwischen X und Y", 'interact');
addPage_2('de/correlation', 'correlation2', "Variablen ohne Einheiten (z-Werte)", 'interact');
addPage_2('de/correlation', 'correlation3', "Der Korrelationskoeffizient und seine Eigenschaften", 'interact');
addPage_2('de/correlation', 'correlation4', "Streudiagramme und die Maßzahl r", 'interact');
addPage_2('de/correlation', 'correlation5', "Nichtlineare Zusammenhänge", 'interact');
addPage_2('de/correlation', 'correlation6', "R beschreibt nicht das ganze Bild", 'interact');
addSection('bk/german_b', 'sec_leastSqrs', "Die kleinsten Quadrate");
addPage_2('de/leastSqrs', 'leastSqrs1', "Die Vorhersage von Y durch X", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs2', "Lineare modelle", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs3', "Berechnete Werte und Residuen", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs4', "Methode der kleinsten Quadrate", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs5', "Nichtlinearität und Ausreißer", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs6', "Residuendiagramm", 'interact');
addPage_2('de/leastSqrs', 'leastSqrs7', "Vorhersage von Y und X", 'interact');
addSection('bk/german', 'sec_curvature', "Nichtlineare Zusammenhänge");
addPage_2('de/curvature', 'curvature1', "Transformationen und Korrelation", 'interact');
addPage_2('de/curvature', 'curvature2', "Transformationen und Modelle", 'interact');
addPage_2('de/curvature', 'curvature3', "Quadratische Modelle", 'interact');
addPage_2('de/curvature', 'curvature4', "Gefahren bei der Extrapolation", 'interact');

addChapter('bk/german_b', 'ch_timeSeries', "Zeitreihen");
addSection('bk/german_b', 'sec_timePlot', "Grafische Darstellung von Zeitreihen");
addPage_2('de/timePlot', 'timePlot_b1', "Grafische Darstellung von Zeitreihen", 'interact');
addPage_2('de/timePlot', 'timePlot_b2', "Muster in Zeitreihen", 'interact');
addPage_2('de/timePlot', 'timePlot3', "Multiple Zeitreihen", 'interact');
addSection('bk/german', 'sec_smoothing', "Glätten");
addPage_2('de/smoothing', 'smoothing1', "Gleitender Durchschnitt", 'interact');
addPage_2('de/smoothing', 'smoothing2', "Gleitender Durchschnitt (Fortsetzung)", 'interact');
addPage_2('de/smoothing', 'smoothing3', "Robuste Gl&auml;ttung", 'interact');
addPage_2('de/smoothing', 'smoothing4', "Exponentiale Gl&auml;ttung", 'interact');
addPage_2('de/smoothing', 'smoothing5', "Lowess Gl&auml;ttung von Zeitreihen", 'interact');
addPage_2('de/smoothing', 'smoothing6', "Lowess Gl&auml;ttung von Streudiagrammen", 'interact');
addSection('bk/german', 'sec_trend', "Langzeit-Trends");
addPage_2('de/trend', 'trend1', "Lineare Trends", 'interact');
addPage_2('de/trend', 'trend2', "Quadratische Trends", 'interact');
addPage_2('de/trend', 'trend3', "Vorhersagen", 'interact');
addPage_2('de/trend', 'trend4', "Polynomiale Trends", 'interact');
addPage_2('de/trend', 'trend5', "Trends aus Zeitreihen herausrechnen", 'interact');

addChapter('bk/german', 'ch_cat', "Kategorielle Variablen");
addSection('bk/german_b', 'sec_freqTable', "Häufigkeitstabellen");
addPage_2('de/freqTable', 'freqTable1', "Häufigkeitstabellen", 'interact');
addPage_2('de/freqTable', 'freqTable_b2', "Proportionen und Prozentwerte", 'interact');
addPage_2('de/freqTable', 'freqTable3', "Häufigkeitstabellen erkennen", 'static');
addPage_2('de/freqTable', 'freqTable4', "Veränderung der Kategorien", 'interact');
addSection('bk/german_b', 'sec_univarCat', "Balken- und Kreisdiagramme");
addPage_2('de/univarCat', 'univarCat_b1', "Balkendiagramme", 'interact');
addPage_2('de/univarCat', 'univarCat2', "Paretodiagramme", 'interact');
addPage_2('de/univarCat', 'univarCat_b3', "Chartjunk und irref&uuml;hrende Balkendiagramme", 'static');
addPage_2('de/univarCat', 'univarCat_b4', "Gestapelte Balkendiagramme und Kreisdiagramme", 'interact');
addPage_2('de/univarCat', 'univarCat_b5', "Vergleich von Balken- und Kreisdiagrammen", 'interact');
addPage_2('de/univarCat', 'univarCat_b6', "Chartjunk in Kreisdiagrammen", 'static');
addPage_2('de/univarCat', 'univarCat_b7', "Balken- und Kreisdiagramme", 'interact');
addSection('bk/german_b', 'sec_groupedCat', "Gruppen vergleichen");
addPage_2('de/groupedCat', 'groupedCat1', "Kontingenztabellen", 'interact');
addPage_2('de/groupedCat', 'groupedCat_b2', "Beispiele f&uuml;r Kontingenztabellen", 'static');
addPage_2('de/groupedCat', 'groupedCat_b3', "Balkendiagramme mit relativen H&auml;ufigkeiten", 'interact');
addPage_2('de/groupedCat', 'groupedCat_b4', "Gestapelte Balkendiagramme", 'interact');
addPage_2('de/groupedCat', 'groupedCat_b5', "Sonderf&auml;lle", 'interact');
addSection('bk/german_b', 'sec_bivarCat', "Bivariate kategorielle Verteilungen");
addPage_2('de/bivarCat', 'bivarCat_b1', "Zusammenhang zwischen Variablen", 'static');
addPage_2('de/bivarCat', 'bivarCat2', "3-dimensionale Balkendiagramme", 'interact');
addPage_2('de/bivarCat', 'bivarCat3', "Gruppierte Balkendiagramme", 'interact');
addPage_2('de/bivarCat', 'bivarCat4', "Randverteilungen", 'interact');
addPage_2('de/bivarCat', 'bivarCat5', "Bedingte Verteilungen", 'interact');
addPage_2('de/bivarCat', 'bivarCat6', "Mehr über bedingte Verteilungen", 'interact');
addPage_2('de/bivarCat', 'bivarCat7', "Bedingte Verteilungen und Randverteilungen im Vergleich", 'interact');
addSection('bk/german', 'sec_tableDisplay', "Daten in Tabellen präsentieren");
addPage_2('de/tableDisplay', 'tableDisplay1', "Rasterlinien und Leerzeichen", 'static');
addPage_2('de/tableDisplay', 'tableDisplay2', "Layout und Erl&auml;uterungen", 'static');
addPage_2('de/tableDisplay', 'tableDisplay3', "Datenrauschen und Dezimalstellen", 'interact');
addPage_2('de/tableDisplay', 'tableDisplay4', "Bedeutsame Variablen", 'interact');
addPage_2('de/tableDisplay', 'tableDisplay5', "Spalten und Zeilen vertauschen", 'static');
addPage_2('de/tableDisplay', 'tableDisplay6', "Zeilen neu ordnen", 'interact');
addPage_2('de/tableDisplay', 'tableDisplay7', "Beispiel", 'static');
addSection('bk/german_b', 'sec_logistic', "Logistische Regression");
addPage_2('de/logistic', 'logistic_b1', "Kategoriale Zielgrößen", 'interact');
addPage_2('de/logistic', 'logistic_b2', "Vorhersagen", 'interact');
addPage_2('de/logistic', 'logistic3', "Logistische Kurve", 'interact');
addPage_2('de/logistic', 'logistic_b4', "Obtaining a good fit", 'interact');

addChapter('bk/german', 'ch_multivar', "Multivariate Daten");
addSection('bk/german_b', 'sec_multivariate', "Darstellung multivariater Daten");
addPage_2('de/multivariate', 'multivariate_b1', "Darstellung einer dritten Variablen", 'interact');
addPage_2('de/multivariate', 'multivariate2', "Drehbare 3D-Streudiagramme", 'interact');
addPage_2('de/multivariate', 'multivariate3', "Streudiagrammmatrix und Einf&auml;rben", 'interact');
addPage_2('de/multivariate', 'multivariate4', "Einf&auml;rben", 'interact');
addPage_2('de/multivariate', 'multivariate5', "Aufteilen", 'interact');
addSection('bk/german', 'sec_regnGroups', "Gruppen und Regression");
addPage_2('de/regnGroups', 'regnGroups1', "Zus&auml;tzliche Variablen in der Regression", 'interact');
addPage_2('de/regnGroups', 'regnGroups2', "Gruppen darstellen", 'interact');
addPage_2('de/regnGroups', 'regnGroups3', "Regression mit gruppierten Daten", 'interact');
addPage_2('de/regnGroups', 'regnGroups4', "Parallele Regressionsgeraden", 'interact');
addPage_2('de/regnGroups', 'regnGroups5', "Transformierte Variablen und Gruppen", 'interact');
addPage_2('de/regnGroups', 'regnGroups6', "Gruppierung mit numerischen Variablen", 'interact');
addPage_2('de/regnGroups', 'regnGroups7', "Streudiagrammmatrix mit Gruppen", 'interact');
addSection('bk/german', 'sec_multiRegn', "Multiple Regression");
addPage_2('de/multiRegn', 'multiRegn1', "Mehr als eine Einflussvariable", 'interact');
addPage_2('de/multiRegn', 'multiRegn2', "Multiple Regressionsgleichung", 'interact');
addPage_2('de/multiRegn', 'multiRegn3', "Koeffizienten interpretieren", 'interact');
addPage_2('de/multiRegn', 'multiRegn4', "Streudiagramm zweier Variablen", 'interact');
addPage_2('de/multiRegn', 'multiRegn5', "Die lineare Gleichung für Y mit den Einflussvariablen X und Z", 'interact');
addPage_2('de/multiRegn', 'multiRegn6', "Modelwerte und Residuen", 'interact');
addPage_2('de/multiRegn', 'multiRegn7', "Schätzung der kleinsten Quadrate", 'interact');
addSection('bk/german_b', 'sec_lurking', "Zusammenhang der Randsummen");
addPage_2('de/lurking', 'lurking_b1', "Irref&uuml;hrende Randkorrelation", 'interact');
addPage_2('de/lurking', 'lurking_b2', "Irref&uuml;hrende Differenz von Mittelwerten", 'interact');
addPage_2('de/lurking', 'lurking3', "Simpsons Paradox", 'interact');
addPage_2('de/lurking', 'lurking4', "Weitere Beispiele f&uuml;r versteckte Variablen", 'static');

addChapter('bk/german', 'ch_sample', "Stichproben und Variabilit&auml;t");
addSection('bk/german_b', 'sec_popSamp', "Endliche Grundgesamtheiten");
addPage_2('de/popSamp', 'popSamp_b1', "Zensus oder Stichprobe?", 'interact');
addPage_2('de/popSamp', 'popSamp2', "Variabilit&auml;t einer Stichprobe", 'interact');
addPage_2('de/popSamp', 'popSamp_b3', "Stichprobenfehler", 'interact');
addPage_2('de/popSamp', 'popSamp_b4', "Stichprobenumfang und Stichprobenfehler", 'interact');
addPage_2('de/popSamp', 'popSamp_b5', "Stichproben aus endlichen Grundgesamtheiten", 'interact');
addPage_2('de/popSamp', 'popSamp6', "Eine Zufallsstichprobe ziehen", 'interact');
addSection('bk/german_b', 'sec_infPopn', "Stichproben von Verteilungen");
addPage_2('de/infPopn', 'infPopn_b1', "Was Daten darstellen", 'static');
addPage_2('de/infPopn', 'infPopn_b2', "Zufälligkeit von Daten", 'interact');
addPage_2('de/infPopn', 'infPopn_b3', "Model zur Erklärung der Zufälligkeit", 'static');
addPage_2('de/infPopn', 'infPopn4', "Unendliche Populationen", 'interact');
addPage_2('de/infPopn', 'infPopn5', "Information aus einer einzelnen Stichprobe", 'interact');
addSection('bk/german_b', 'sec_probDensity', "Wahrscheinlichkeit und Dichte");
addPage_2('de/probDensity', 'probDensity_b1', "Endliche Grundgesamtheiten", 'interact');
addPage_2('de/probDensity', 'probDensity_b2', "Wahrscheinlichkeiten innerhalb von Grundgesamtheiten", 'interact');
addPage_2('de/probDensity', 'probDensity3', "Balkendiagramm diskreter Wahrscheinlichkeiten", 'interact');
addPage_2('de/probDensity', 'probDensity4', "Dichtefunktionen", 'interact');
addPage_2('de/probDensity', 'probDensity5', "Normalverteilungen", 'interact');
addPage_2('de/probDensity', 'probDensity6', "Die Fl&auml;che unter der Dichtefunktion", 'interact');
addPage_2('de/probDensity', 'probDensity7', "Eigenschaften von Wahrscheinlichkeiten", 'static');
addSection('bk/german_b', 'sec_probSim', "Simulation (optional)");
addPage_2('de/probSim', 'probSim1', "Wahrscheinlichkeitsmodelle und Simulationen", 'interact');
addPage_2('de/probSim', 'probSim2', "Gewinnt das beste Team?", 'interact');
addPage_2('de/probSim', 'probSim3', "Spielqualit&auml;t in der Fussballliga", 'interact');
addPage_2('de/probSim', 'probSim_b4', "Bewertung von Besonderheiten", 'interact');
addPage_2('de/probSim', 'probSim5', "Zufallswerte", 'interact');
addPage_2('de/probSim', 'probSim6', "Kategorielle Werte erzeugen", 'interact');
addPage_2('de/probSim', 'probSim7', "Numerische Werte erzeugen", 'interact');
addSection('bk/german_b', 'sec_randomMean', "Verteilung von Stichprobenmittelwerten");
addPage_2('de/randomMean', 'randomMean_b1', "Variabilit&auml;t von Stichprobenstatistiken", 'interact');
addPage_2('de/randomMean', 'randomMean2', "Variabilit&auml;t des Stichprbenmittelwerts", 'interact');
addPage_2('de/randomMean', 'randomMean3', "Standardabweichung der Stichprobe", 'interact');
addPage_2('de/randomMean', 'randomMean4', "Mittelwerte von normalverteilten Grundgesamtheiten", 'interact');
addPage_2('de/randomMean', 'randomMean5', "Zentraler Grenzwertsatz", 'interact');
addPage_2('de/randomMean', 'randomMean_b6', "Distribution of mean from a sample", 'static');
addPage_2('de/randomMean', 'randomMean_b7', "Requirement of independence", 'interact');
addPage_2('de/randomMean', 'randomMean8', "Stichproben aus endlichen Grundgesamtheiten", 'interact');
addSection('bk/german_b', 'sec_normalDistn', "Normalverteilungen");
addPage_2('de/normalDistn', 'normalDistn1', "Bedeutung der Normalverteilung", 'interact');
addPage_2('de/normalDistn', 'normalDistn2', "Die Form von Normalverteilungen", 'interact');
addPage_2('de/normalDistn', 'normalDistn_b3', "Sketching a normal distribution", 'interact');
addPage_2('de/normalDistn', 'normalDistn4', "Einige wichtige Wahrscheinlichkeiten", 'interact');
addPage_2('de/normalDistn', 'normalDistn5', "Z-Werte", 'interact');
addPage_2('de/normalDistn', 'normalDistn_b6', "Finding normal probabilities", 'interact');
addPage_2('de/normalDistn', 'normalDistn_b7', "Other probabilities", 'interact');
addPage_2('de/normalDistn', 'normalDistn8', "z-Tabellen", 'static');
addPage_2('de/normalDistn', 'normalDistn9', "Quantile der Normalverteilung", 'interact');
addPage_2('de/normalDistn', 'normalDistn10', "QQ-plots", 'interact');
addSection('bk/german_b', 'sec_randomPropn', "Stichprobenverteilung von Häufigkeiten");
addPage_2('de/randomPropn', 'randomPropn1', "Proportionen und Wahrscheinlichkeiten", 'interact');
addPage_2('de/randomPropn', 'randomPropn2', "Eigenschaften von Z&auml;hlwerten und Proportionen", 'interact');
addPage_2('de/randomPropn', 'randomPropn_b3', "Binomialverteilung", 'interact');
addPage_2('de/randomPropn', 'randomPropn_b4', "Binomiale Wahrscheinlichkeiten", 'static');
addPage_2('de/randomPropn', 'randomPropn5', "Anpassung der Normalverteilung an die Binomialverteilung", 'interact');
addPage_2('de/randomPropn', 'randomPropn_b6', "Beispiele f&uuml;r die Ann&auml;herung an die Normalverteilung", 'static');
addSection('bk/german_b', 'sec_sampPractice', "Stichproben in der Praxis");
addPage_2('de/sampPractice', 'sampPractice_b1', "Geschichtete Stichprobe", 'interact');
addPage_2('de/sampPractice', 'sampPractice2', "Clusterstichprobe", 'interact');
addPage_2('de/sampPractice', 'sampPractice3', "Zweistufige Stichprobe", 'interact');
addPage_2('de/sampPractice', 'sampPractice4', "Stichprobenfehler und systematische Fehler", 'static');
addPage_2('de/sampPractice', 'sampPractice_b5', "Erfassungsfehler und Antwortausfall", 'static');
addPage_2('de/sampPractice', 'sampPractice_b6', "Interviewer- und Ger&auml;tefehler", 'interact');
addPage_2('de/sampPractice', 'sampPractice7', "Survey design issues", 'static');

addChapter('bk/german', 'ch_expDesign', "Planung von Experimenten");
addSection('bk/german_b', 'sec_causal', "Zusammenhang &amp; kausale Beziehungen");
addPage_2('de/causal', 'causal_b1', "Das Interesse an Zusammenhängen", 'static');
addPage_2('de/causal', 'causal2', "Kausale und nonkausale Zusammenhänge", 'static');
addPage_2('de/causal', 'causal_b3', "Kausale Zusammenhänge feststellen", 'static');
addPage_2('de/causal', 'causal_b4', "Beobachtungen und experimentelle Daten", 'interact');
addPage_2('de/causal', 'causal5', "Daten sammeln und Kausalität", 'interact');
addSection('bk/german_b', 'sec_designIntro', "Prinzipien der Versuchsplanung");
addPage_2('de/designIntro', 'designIntro_b1', "Experimente und Behandlungen", 'static');
addPage_2('de/designIntro', 'designIntro2', "Variable experimentelle Einheiten", 'interact');
addPage_2('de/designIntro', 'designIntro3', "Schlecht designte Experimente", 'interact');
addPage_2('de/designIntro', 'designIntro4', "Störungen", 'static');
addPage_2('de/designIntro', 'designIntro_b5', "Randomisation", 'interact');
addPage_2('de/designIntro', 'designIntro6', "Replikation", 'static');
addPage_2('de/designIntro', 'designIntro7', "Blockbildung", 'interact');
addSection('bk/german_b', 'sec_pairBlock', "Paarbildung und Blöcke");
addPage_2('de/pairBlock', 'pairBlock1', "&Auml;hnliche Versuchseinheiten", 'interact');
addPage_2('de/pairBlock', 'pairBlock2', "Experimente mit Paarbildung", 'interact');
addPage_2('de/pairBlock', 'pairBlock3', "Randomisation in Experimenten mit Paarbildung", 'interact');
addPage_2('de/pairBlock', 'pairBlock4', "Einheitliche Gruppen mit 3 oder mehr Versuchseinheiten", 'interact');
addPage_2('de/pairBlock', 'pairBlock_b5', "Randomisierte Blockexperimente", 'static');
addSection('bk/german_b', 'sec_designTwo', "Zwei oder mehr Faktoren");
addPage_2('de/designTwo', 'designTwo_b1', "Experimente mit 2 Faktoren", 'interact');
addPage_2('de/designTwo', 'designTwo_b2', "Faktorielles Design", 'static');
addPage_2('de/designTwo', 'designTwo3', "Einfaches Model mit zwei Faktoren", 'interact');
addPage_2('de/designTwo', 'designTwo4', "Interaction zwischen Faktoren", 'interact');
addPage_2('de/designTwo', 'designTwo5', "Beispiel für Interaktionen", 'interact');
addPage_2('de/designTwo', 'designTwo_b6', "Model für drei Faktoren ohne Interaktion", 'interact');
addPage_2('de/designTwo', 'designTwo7', "Interaktion in 3-faktoriellen Designs", 'interact');
addSection('bk/german', 'sec_designPrelim', "Practical issues in design");
addPage_2('de/designPrelim', 'designPrelim1', "Zweck", 'static');
addPage_2('de/designPrelim', 'designPrelim2', "Experimentelle Einheiten und Messungen", 'static');
addPage_2('de/designPrelim', 'designPrelim3', "Experimente mit Menschen als Versuchsobjekten", 'static');

addChapter('bk/german', 'ch_estimation', "Parameter sch&auml;tzen");
addSection('bk/german_b', 'sec_estIntro', "Einführung in statistische Schätzverfahren");
addPage_2('de/estIntro', 'estIntro_b1', "Das Interesse an Grundgesamtheiten", 'static');
addPage_2('de/estIntro', 'estIntro_b2', "Das Interesse an Parametern", 'static');
addPage_2('de/estIntro', 'estIntro3', "Anwendung von Schätzungen", 'static');
addPage_2('de/estIntro', 'estIntro4', "Schätzfehler", 'static');
addPage_2('de/estIntro', 'estIntro_b5', "Fehlerverteilung", 'interact');
addPage_2('de/estIntro', 'estIntro6', "Standardfehler und Bias", 'static');
addPage_2('de/estIntro', 'estIntro7', "Intervallschätzungen", 'static');
addSection('bk/german_b', 'sec_seMean', "Standardfehler des Mittelwertes");
addPage_2('de/seMean', 'seMean_b1', "Fehlerverteilung des Mittelwerts", 'interact');
addPage_2('de/seMean', 'seMean_b2', "Standardfehler bei bekanntem &sigma;", 'interact');
addPage_2('de/seMean', 'seMean_b3', "Interpretation des Standardfehlers", 'static');
addPage_2('de/seMean', 'seMean_b4', "Standardfehler bei unbekanntem &sigma;", 'static');
addPage_2('de/seMean', 'seMean5', "Standardfehler vs Standardabweichung", 'interact');
addPage_2('de/seMean', 'seMean_b6', "Vergleich von Sch&auml;tzern", 'interact');
addPage_2('de/seMean', 'seMean7', "Weitere Informationen zum Bias", 'interact');
addSection('bk/german_b', 'sec_ciMean', "Konfidenzintervall des Mittelwertes");
addPage_2('de/ciMean', 'ciMean1', "Konfidenzintervalle und der Standardfehler", 'static');
addPage_2('de/ciMean', 'ciMean_b2', "Konfidenzintervalle bei bekanntem \u03c3", 'interact');
addPage_2('de/ciMean', 'ciMean3', "Konfidenzstufen", 'interact');
addPage_2('de/ciMean', 'ciMean4', "Konfidenzstufen, wenn \u03c3 durch s ersetzt wird", 'interact');
addPage_2('de/ciMean', 'ciMean5', "Konfidenzintervall für µ, bei unbekanntem \u03c3", 'interact');
addPage_2('de/ciMean', 'ciMean6', "Eigenschaften des 95% Konfidenzintervalls", 'interact');
addPage_2('de/ciMean', 'ciMean_b7', "Beispiele", 'static');
addSection('bk/german_b', 'sec_estPropn', "Estimating proportions");
addPage_2('de/estPropn', 'estPropn1', "Methoden zur Schätzung", 'static');
addPage_2('de/estPropn', 'estPropn2', "Schätzung einer Proportion", 'interact');
addPage_2('de/estPropn', 'estPropn_b3', "Fehlerverteilung", 'interact');
addPage_2('de/estPropn', 'estPropn_b4', "Annäherung der Fehlerverteilung", 'static');
addPage_2('de/estPropn', 'estPropn_b5', "Konfidenzintervall von Proportionen", 'static');
addPage_2('de/estPropn', 'estPropn6', "Eigenschaften des 95%-Konfidenzintervalls von Proportionen", 'interact');
addPage_2('de/estPropn', 'estPropn_b7', "Beispiele", 'static');
addSection('bk/german_b', 'sec_ciExtra', "More about estimation");
addPage_2('de/ciExtra', 'ciExtra_b1', "Begrenzung des Fehlers", 'interact');
addPage_2('de/ciExtra', 'ciExtra2', "Stichprobengröße zur Schätzung von Mittelwerten", 'interact');
addPage_2('de/ciExtra', 'ciExtra_b3', "Stichprobengröße zur Schätzung von Proportionen", 'interact');
addPage_2('de/ciExtra', 'ciExtra4', "Andere Vertrauensintervalle", 'interact');
addSection('bk/german_b', 'sec_estOther', "Simulation and bootstrap");
addPage_2('de/estOther', 'estOther1', "Simulationen", 'static');
addPage_2('de/estOther', 'estOther2', "Fehlerverteilung durch Simulation", 'interact');
addPage_2('de/estOther', 'estOther3', "Simulation mit Normalverteilung", 'interact');
addPage_2('de/estOther', 'estOther4', "Bootstrap der Fehlerverteilung", 'interact');
addPage_2('de/estOther', 'estOther_b5', "Standardfehler der Korrelation mit Bootstrap", 'interact');
addPage_2('de/estOther', 'estOther6', "KIs durch Simulation", 'interact');

addChapter('bk/german', 'ch_testing', "Hypothesen testen");
addSection('bk/german_b', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('de/testIntro', 'testIntro_b1', "Inference", 'static');
addPage_2('de/testIntro', 'testIntro2', "Soccer league simulation", 'interact');
addPage_2('de/testIntro', 'testIntro_b3', "Simulation to test a proportion", 'interact');
addPage_2('de/testIntro', 'testIntro4', "Test for a mean", 'interact');
addPage_2('de/testIntro', 'testIntro_b5', "Randomisation tests", 'interact');
addPage_2('de/testIntro', 'testIntro6', "Soccer league randomisation", 'interact');
addPage_2('de/testIntro', 'testIntro_b7', "Common patterns in hypothesis testing", 'static');
addSection('bk/german_b', 'sec_testPropn', "Tests about proportions");
addPage_2('de/testPropn', 'testPropn_b1', "Inference about parameters", 'static');
addPage_2('de/testPropn', 'testPropn_b2', "P-value for testing proportion", 'interact');
addPage_2('de/testPropn', 'testPropn_b3', "Another example of testing a proportion", 'interact');
addPage_2('de/testPropn', 'testPropn_b4', "One- and two-tailed tests", 'interact');
addPage_2('de/testPropn', 'testPropn_b5', "Tests based on normal approximation", 'interact');
addSection('bk/german_b', 'sec_testMean', "Tests about means");
addPage_2('de/testMean', 'testMean1', "Introduction", 'static');
addPage_2('de/testMean', 'testMean2', "Tests based on statistical distance", 'interact');
addPage_2('de/testMean', 'testMean_b3', "P-value for test (known sigma)", 'interact');
addPage_2('de/testMean', 'testMean4', "The t distribution", 'interact');
addPage_2('de/testMean', 'testMean5', "The t test for a mean", 'interact');
addSection('bk/german', 'sec_decision', "Decisions and significance");
addPage_2('de/decision', 'decision1', "Hypothesentests und Entscheidungen", 'static');
addPage_2('de/decision', 'decision2', "Entscheidungsregeln", 'interact');
addPage_2('de/decision', 'decision3', "Significanzlevel und p-Werte", 'interact');
addPage_2('de/decision', 'decision4', "Stichprobenumfang und Power", 'interact');
addSection('bk/german_b', 'sec_testPValue', "Properties of p-values");
addPage_2('de/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact');
addPage_2('de/testPValue', 'testPValue_b2', "P-value and consistency with null hypothesis", 'interact');
addPage_2('de/testPValue', 'testPValue3', "Distribution of p-values", 'interact');
addPage_2('de/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact');
addPage_2('de/testPValue', 'testPValue_b5', "P-values for other tests", 'interact');

addChapter('bk/german', 'ch_twoGroups', "Gruppen vergleichen");
addSection('bk/german_b', 'sec_twoGroupModel', "Models for two groups");
addPage_2('de/twoGroupModel', 'twoGroupModel_b1', "Interest in underlying population", 'static');
addPage_2('de/twoGroupModel', 'twoGroupModel_b2', "Model for two groups", 'interact');
addPage_2('de/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact');
addPage_2('de/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact');
addPage_2('de/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact');
addSection('bk/german', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('de/sumDiff', 'sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('de/sumDiff', 'sumDiff2', "Sum and differences", 'interact');
addPage_2('de/sumDiff', 'sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('de/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static');
addSection('bk/german_b', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('de/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact');
addPage_2('de/twoGroupInf', 'twoGroupInf_b2', "Distribution of estimation error", 'static');
addPage_2('de/twoGroupInf', 'twoGroupInf_b3', "CI for difference between means", 'interact');
addPage_2('de/twoGroupInf', 'twoGroupInf_b4', "Testing a hypothesis", 'interact');
addPage_2('de/twoGroupInf', 'twoGroupInf_b5', "One-tailed tests for differences", 'interact');
addSection('bk/german', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('de/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact');
addPage_2('de/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact');
addPage_2('de/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static');
addPage_2('de/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static');
addSection('bk/german_b', 'sec_testPaired', "Paired t test");
addPage_2('de/testPaired', 'testPaired_b1', "Paired data examples", 'static');
addPage_2('de/testPaired', 'testPaired_b2', "Analysis of differences", 'interact');
addPage_2('de/testPaired', 'testPaired3', "Paired t-test", 'interact');
addPage_2('de/testPaired', 'testPaired4', "Pairing and experimental design", 'interact');
addSection('bk/german_b', 'sec_multiGroup', "Comparing several means");
addPage_2('de/multiGroup', 'multiGroup_b1', "Model mit gemeinsamer Standardabweichung", 'interact');
addPage_2('de/multiGroup', 'multiGroup2', "Schätzung der gemeinsamen Standardabweichung", 'interact');
addPage_2('de/multiGroup', 'multiGroup_b3', "Inferenz über zwei Gruppen", 'static');
addPage_2('de/multiGroup', 'multiGroup4', "Differenzen zwischen Gruppen schätzen", 'interact');
addPage_2('de/multiGroup', 'multiGroup5', "Quadratsummen", 'interact');
addPage_2('de/multiGroup', 'multiGroup_b6', "Coefficient of determination", 'static');
addPage_2('de/multiGroup', 'multiGroup7', "Test für Gruppendifferenzen", 'interact');
addPage_2('de/multiGroup', 'multiGroup_b8', "Beispiele", 'static');
addSection('bk/german', 'sec_randBlock', "Randomised blocks");
addPage_2('de/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static');
addPage_2('de/randBlock', 'randBlock2', "Importance of using block information", 'interact');
addPage_2('de/randBlock', 'randBlock3', "Data with no baseline treatment", 'interact');
addPage_2('de/randBlock', 'randBlock4', "Randomised block designs", 'interact');
addPage_2('de/randBlock', 'randBlock5', "Model for randomised blocks", 'interact');
addPage_2('de/randBlock', 'randBlock6', "Removing block effects", 'interact');
addPage_2('de/randBlock', 'randBlock7', "Sums of squares", 'interact');
addPage_2('de/randBlock', 'randBlock8', "Anova table and examples", 'static');

addChapter('bk/german', 'ch_regnInference', "Regressionsmodelle");
addSection('bk/german_b', 'sec_regnModel', "Linear regression models");
addPage_2('de/regnModel', 'regnModel_b1', "Interest in generalising from data", 'interact');
addPage_2('de/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact');
addPage_2('de/regnModel', 'regnModel3', "Normal linear model", 'interact');
addPage_2('de/regnModel', 'regnModel4', "Errors and 95% band on scatterplot", 'interact');
addPage_2('de/regnModel', 'regnModel_b5', "Model parameters", 'interact');
addSection('bk/german', 'sec_regnEst', "Estimating parameters");
addPage_2('de/regnEst', 'regnEst1', "Point estimates of slope and intercept", 'interact');
addPage_2('de/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact');
addPage_2('de/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact');
addPage_2('de/regnEst', 'regnEst4', "Standard error of least squares slope", 'static');
addPage_2('de/regnEst', 'regnEst5', "95% confidence interval for slope", 'static');
addPage_2('de/regnEst', 'regnEst6', "Properties of confidence interval", 'interact');
addPage_2('de/regnEst', 'regnEst7', "Influences on accuracy", 'interact');
addSection('bk/german', 'sec_regnTest', "Testing regression parameters");
addPage_2('de/regnTest', 'regnTest1', "Importance of zero slope", 'interact');
addPage_2('de/regnTest', 'regnTest2', "Testing whether slope is zero", 'static');
addPage_2('de/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static');
addPage_2('de/regnTest', 'regnTest4', "Properties of p-values", 'interact');
addSection('bk/german_b', 'sec_regnPred', "Predicting the response");
addPage_2('de/regnPred', 'regnPred_b1', "Estimated response distn at X", 'interact');
addPage_2('de/regnPred', 'regnPred2', "Variability of estimate at X", 'interact');
addPage_2('de/regnPred', 'regnPred_b3', "Estimating the mean vs prediction", 'interact');
addPage_2('de/regnPred', 'regnPred_b4', "Confidence and prediction intervals", 'interact');
addSection('bk/german_b', 'sec_regnProblem', "Linear model assumptions");
addPage_2('de/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact');
addPage_2('de/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact');
addPage_2('de/regnProblem', 'regnProblem_b3', "Curvature and non-constant variance &mdash; transforming Y", 'interact');
addPage_2('de/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact');
addPage_2('de/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact');
addPage_2('de/regnProblem', 'regnProblem6', "Non-normal errors", 'interact');
addPage_2('de/regnProblem', 'regnProblem7', "Correlated errors", 'interact');

addChapter('bk/german', 'ch_independence', "Unabh&auml;ngigkeit");
addSection('bk/german_b', 'sec_prob', "Probability and applications");
addPage_2('de/prob', 'prob_b1', "Joint probabilities", 'interact');
addPage_2('de/prob', 'prob_b2', "Marginal probabilities", 'interact');
addPage_2('de/prob', 'prob_b3', "Conditional probabilities", 'interact');
addPage_2('de/prob', 'prob4', "Graphical display of probabilities", 'interact');
addPage_2('de/prob', 'prob5', "Calculations with probabilities", 'interact');
addSection('bk/german_b', 'sec_indep', "Independence");
addPage_2('de/indep', 'indep_b1', "Zusammenhang zwischen kategorialen Variables", 'static');
addPage_2('de/indep', 'indep2', "Unabhängigkeit zwischen kategorialen Variablen", 'interact');
addPage_2('de/indep', 'indep3', "Unabhängigkeit von Stichproben", 'static');
addPage_2('de/indep', 'indep4', "Testen auf Unabhängigkeit", 'interact');
addPage_2('de/indep', 'indep5', "Chi-Quadrat Teststatistik", 'interact');
addPage_2('de/indep', 'indep6', "P-Wert des Chi-Quadrat-Test", 'interact');
addPage_2('de/indep', 'indep7', "Beispiele", 'static');
addPage_2('de/indep', 'indep8', "Vergleich von Gruppen", 'static');

var language = "de";
var logoGif = null;
var homeDir = "bk/german_b";
var versionGif = "images/castGerman";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Volltextsuche';
var summaryTextString = 'Übersicht';
var videoTextString = 'Video';
var appletTextString = 'Interact';
fullTabTooltip = 'Full version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Interactive version of page';
var chapterString = 'Kapitel';

var versionName = {'_b': 'Biometrische', '_g': 'Allgemeine', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Andere'};
var versions = {};
versions['context1'] = new Array('_b', '_g', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_b', '_g', '_a', '_c');
versions['structures2'] = new Array('_b', '_g', '_a', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_b', '_g', '_c');
versions['structures6'] = new Array('_b', '_g');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_b', '_g', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay2'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay3'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay4'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay5'] = new Array('_b', '_g', '_a', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_b', '_g', '_c');
versions['displayInterp2'] = new Array('_b', '_g', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_b', '_g');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_b', '_g', '_c', '_m');
versions['density6'] = new Array('_b', '_g', '_c');
versions['density7'] = new Array('_b', '_g', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_b', '_g', '_c', '_m');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_b', '_g');
versions['centerSpread1'] = new Array('_b', '_g');
versions['centerSpread2'] = new Array('_b', '_g');
versions['centerSpread3'] = new Array('_b', '_g', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_b', '_g');
versions['transform2'] = new Array('_b', '_g', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['counts1'] = new Array('_b', '_g', '_c');
versions['counts2'] = new Array('_b', '_g', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['counts4'] = new Array('_b', '_g', '_c');
versions['scatterplot1'] = new Array('_b', '_g', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship2'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_b', '_g', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_b', '_g', '_c');
versions['timePlot2'] = new Array('_b', '_g', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_b', '_g', '_a');
versions['univarCat1'] = new Array('_b', '_g', '_a');
versions['univarCat3'] = new Array('_b', '_g', '_a');
versions['univarCat4'] = new Array('_b', '_g', '_c');
versions['univarCat5'] = new Array('_b', '_g', '_c');
versions['univarCat6'] = new Array('_b', '_g', '_c');
versions['univarCat7'] = new Array('_b', '_g');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_b', '_g', '_c');
versions['groupedCat3'] = new Array('_b', '_g', '_c');
versions['groupedCat4'] = new Array('_b', '_g', '_c');
versions['groupedCat5'] = new Array('_b', '_g', '_c');
versions['bivarCat1'] = new Array('_b', '_g', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['logistic1'] = new Array('_b', '_g', '_c');
versions['logistic2'] = new Array('_b', '_g', '_c');
versions['logistic4'] = new Array('_b', '_g', '_c');
versions['multivariate1'] = new Array('_b', '_g', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_b', '_g', '_c');
versions['lurking2'] = new Array('_b', '_g');
versions['lurking3'] = new Array('_g', '_c');
versions['popSamp1'] = new Array('_b', '_g', '_a', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_b', '_g', '_a', '_c');
versions['popSamp4'] = new Array('_b', '_g');
versions['popSamp5'] = new Array('_b', '_g', '_c');
versions['infPopn1'] = new Array('_b', '_g', '_c');
versions['infPopn2'] = new Array('_b', '_g', '_c', '_z');
versions['infPopn3'] = new Array('_b', '_g', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_b', '_g', '_c');
versions['probDensity2'] = new Array('_b', '_g', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_b', '_g', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_b', '_g', '_c');
versions['randomMean6'] = new Array('_b', '_g', '_c');
versions['randomMean7'] = new Array('_b', '_g');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_b', '_g', '_c');
versions['normalDistn6'] = new Array('_b', '_g', '_c');
versions['normalDistn7'] = new Array('_b', '_g', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_b', '_g', '_c');
versions['randomPropn4'] = new Array('_b', '_g', '_c');
versions['randomPropn6'] = new Array('_b', '_g', '_c');
versions['sampPractice1'] = new Array('_b', '_g');
versions['sampPractice5'] = new Array('_b', '_g', '_c');
versions['sampPractice6'] = new Array('_b', '_g');
versions['causal1'] = new Array('_b', '_g', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_b', '_g', '_c');
versions['causal4'] = new Array('_b', '_g', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_b', '_g', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_b', '_g', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_b', '_g');
versions['designTwo1'] = new Array('_b', '_g');
versions['designTwo2'] = new Array('_b', '_g');
versions['designTwo6'] = new Array('_b', '_g');
versions['designPrelim2'] = new Array('_g', '_c');
versions['estIntro1'] = new Array('_b', '_g', '_c');
versions['estIntro2'] = new Array('_b', '_g', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_b', '_g', '_c');
versions['seMean1'] = new Array('_b', '_g', '_c');
versions['seMean2'] = new Array('_b', '_g');
versions['seMean3'] = new Array('_b', '_g');
versions['seMean4'] = new Array('_b', '_g', '_c');
versions['seMean6'] = new Array('_b', '_g', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_b', '_g');
versions['ciMean7'] = new Array('_b', '_g', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_b', '_g', '_c');
versions['estPropn4'] = new Array('_b', '_g', '_c');
versions['estPropn5'] = new Array('_b', '_g', '_c');
versions['estPropn7'] = new Array('_b', '_g', '_c');
versions['ciExtra1'] = new Array('_b', '_g', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_b', '_g');
versions['estOther3'] = new Array('_g', '_c', '_m');
versions['estOther5'] = new Array('_b', '_g');
versions['estOther6'] = new Array('_g', '_c', '_m');
versions['testIntro1'] = new Array('_b', '_g');
versions['testIntro3'] = new Array('_b', '_g', '_c');
versions['testIntro5'] = new Array('_b', '_g');
versions['testIntro7'] = new Array('_b', '_g', '_c');
versions['testPropn1'] = new Array('_b', '_g', '_c');
versions['testPropn2'] = new Array('_b', '_g', '_c');
versions['testPropn3'] = new Array('_b', '_g', '_c');
versions['testPropn4'] = new Array('_b', '_g', '_c');
versions['testPropn5'] = new Array('_b', '_g');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_b', '_g', '_c');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_b', '_g', '_c');
versions['testPValue5'] = new Array('_b', '_g', '_c');
versions['twoGroupModel1'] = new Array('_b', '_g', '_c');
versions['twoGroupModel2'] = new Array('_b', '_g', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_b', '_g', '_c');
versions['twoGroupInf3'] = new Array('_b', '_g', '_c');
versions['twoGroupInf4'] = new Array('_b', '_g', '_c');
versions['twoGroupInf5'] = new Array('_b', '_g', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_b', '_g', '_c');
versions['testPaired2'] = new Array('_b', '_g', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_b', '_g', '_c');
versions['multiGroup3'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_b', '_g', '_a', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_b', '_g', '_c');
versions['regnModel1'] = new Array('_b', '_g', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_b', '_g', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_b', '_g', '_c');
versions['regnPred3'] = new Array('_b', '_g', '_c');
versions['regnPred4'] = new Array('_b', '_g');
versions['regnProblem3'] = new Array('_b', '_g');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['prob1'] = new Array('_b', '_g', '_c');
versions['prob2'] = new Array('_b', '_g', '_c');
versions['prob3'] = new Array('_b', '_g');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_b', '_g', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
