
addBook('bk/french_b', 'book_splash', "A propos de ce e-livre CAST");

addChapter('bk/french', 'ch_preface', "Pr&eacute;face");
addSection('bk/french', 'sec_aboutCast', "A propos de CAST");
addPage_2('fr/aboutCast', 'aboutCast1', "Qu'est-ce que CAST?", 'static');
addPage_2('fr/aboutCast', 'aboutCast2', "Structure et navigation", 'static');
addPage_2('fr/aboutCast', 'aboutCast3', "Droit d'auteur et de licence", 'static');
addPage_2('fr/aboutCast', 'aboutCast4', "Remerciements", 'static');
addPage_2('fr/aboutCast', 'aboutCast5', "A propos de l'auteur", 'static');
addSection('bk/french', 'sec_otherInfo', " Autre information");
addPage_2('fr/otherInfo', 'otherInfo1', " Navigateurs et Java", 'static');
addPage_2('fr/otherInfo', 'otherInfo2', " Problèmes?", 'static');
addPage_2('fr/otherInfo', 'otherInfo3', " Impression", 'static');
addPage_2('fr/otherInfo', 'otherInfo4', "Modifications récentes aux CAST", 'static');
addPage_2('fr/otherInfo', 'otherInfo5', "Développements futurs possibles", 'static');

addChapter('bk/french', 'ch_intro', "Introduction: Des Donn&eacute;es");
addSection('bk/french_b', 'sec_context', "Contexte");
addPage_2('fr/context', 'context_b1', "Importance of context", 'static');
addPage_2('fr/context', 'context2', "Statistiques", 'static');
addPage_2('fr/context', 'context_b3', "The statistical process", 'static');
addSection('bk/french_b', 'sec_structures', "Structures de donn&eacute;es standard");
addPage_2('fr/structures', 'structures_b1', "Variables and individuals", 'interact');
addPage_2('fr/structures', 'structures_b2', "Types of variable", 'interact');
addPage_2('fr/structures', 'structures3', "Les variables catégorielles et les groupes", 'interact');
addPage_2('fr/structures', 'structures4', "Définir de nouvelles variables", 'interact');
addPage_2('fr/structures', 'structures_b5', "Time-ordered data", 'static');
addPage_2('fr/structures', 'structures_b6', "Multi-level data", 'interact');
addPage_2('fr/structures', 'structures7', "Structure de données et la méthode statistique", 'static');
addSection('bk/french_b', 'sec_variation', "Variation");
addPage_2('fr/variation', 'variation1', "Signal et le bruit", 'interact');
addPage_2('fr/variation', 'variation2', "La variabilité naturelle", 'interact');
addPage_2('fr/variation', 'variation3', "Variabilité causée par des expériences", 'interact');
addPage_2('fr/variation', 'variation4', "La variabilité des données d'enquête", 'interact');
addPage_2('fr/variation', 'variation_b5', "Explained and unexplained variation", 'static');
addPage_2('fr/variation', 'variation6', "Prédire les valeurs futures", 'static');

addChapter('bk/french', 'ch_univar', "Une Variable Numérique");
addSection('bk/french_b', 'sec_valueDisplay', "Affichage graphique des valeurs");
addPage_2('fr/valueDisplay', 'valueDisplay_b1', "Analysing variation", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay_b2', "Basic dot plot", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay_b3', "Jittered dot plot", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay_b4', "Stacked dot plots", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay_b5', "Stem and leaf plots", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay6', "Division des tiges", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay7', "Tiges et feuilles de dessin", 'interact');
addSection('bk/french_b', 'sec_displayInterp', "Comprendre distributions");
addPage_2('fr/displayInterp', 'displayInterp_b1', "Outliers", 'static');
addPage_2('fr/displayInterp', 'displayInterp_b2', "Clusters", 'interact');
addPage_2('fr/displayInterp', 'displayInterp3', "Distribution des valeurs", 'static');
addPage_2('fr/displayInterp', 'displayInterp_b4', "Extra information about individuals", 'interact');
addPage_2('fr/displayInterp', 'displayInterp5', "Distinguer les groupes connus", 'interact');
addPage_2('fr/displayInterp', 'displayInterp6', "Dangers de la surinterprétation", 'interact');
addSection('bk/french_b', 'sec_density', "Histogrammes et la densit&eacute;");
addPage_2('fr/density', 'density1', "Densité des valeurs", 'static');
addPage_2('fr/density', 'density2', "Histogramme avec des largeurs de classe égale", 'interact');
addPage_2('fr/density', 'density3', "Choix des classes", 'interact');
addPage_2('fr/density', 'density_b4', "Histograms of small data sets", 'interact');
addPage_2('fr/density', 'density5', "Fréquence relative et de la zone", 'interact');
addPage_2('fr/density', 'density_b6', "Comparing groups", 'interact');
addPage_2('fr/density', 'density_b7', "Histograms with varying class widths", 'interact');
addPage_2('fr/density', 'density8', "Comprendre les histogrammes", 'interact');
addPage_2('fr/density', 'density9', "Polygones de fréquence", 'interact');
addPage_2('fr/density', 'density10', "Estimations de la densité du noyau", 'interact');
addPage_2('fr/density', 'density_b11', "Drawing histograms by hand", 'interact');
addSection('bk/french_b', 'sec_boxPlot', "M&eacute;diane, quartiles et trac&eacute;s en bo&icirc;te");
addPage_2('fr/boxPlot', 'boxPlot1', "La nécessité de résumer", 'static');
addPage_2('fr/boxPlot', 'boxPlot2', "Médian, quartiles et boîte à moustaches", 'interact');
addPage_2('fr/boxPlot', 'boxPlot3', "Interpréter une forme de boîte parcelles", 'interact');
addPage_2('fr/boxPlot', 'boxPlot4', "Afficher les valeurs aberrantes", 'interact');
addPage_2('fr/boxPlot', 'boxPlot5', "Clusters", 'interact');
addPage_2('fr/boxPlot', 'boxPlot6', "Comparaison des groupes", 'interact');
addPage_2('fr/boxPlot', 'boxPlot_b7', "Dangers of over-interpretation", 'interact');
addSection('bk/french_b', 'sec_centerSpread', "D&eacute;crivant le centre et la propagation");
addPage_2('fr/centerSpread', 'centerSpread_b1', "Centre and spread", 'static');
addPage_2('fr/centerSpread', 'centerSpread_b2', "Median, range and IQR", 'interact');
addPage_2('fr/centerSpread', 'centerSpread_b3', "Summaries of centre", 'interact');
addPage_2('fr/centerSpread', 'centerSpread4', "Propriétés de la médiane et la moyenne", 'interact');
addPage_2('fr/centerSpread', 'centerSpread5', "L'écart-type", 'interact');
addPage_2('fr/centerSpread', 'centerSpread6', "Règles d'or pour l'écart-type", 'static');
addPage_2('fr/centerSpread', 'centerSpread7', "Signifie comprendre et devns er", 'interact');
addPage_2('fr/centerSpread', 'centerSpread8', "Avertissements sur devn moyenne et standard", 'static');
addSection('bk/french', 'sec_moreVariation', "En savoir plus sur la variation (en option)");
addPage_2('fr/moreVariation', 'moreVariation1', "Effet des valeurs aberrantes", 'interact');
addPage_2('fr/moreVariation', 'moreVariation2', "L'écart type des données groupées", 'interact');
addPage_2('fr/moreVariation', 'moreVariation3', "Variation expliquée et les prédictions", 'interact');
addPage_2('fr/moreVariation', 'moreVariation4', "Variance et de degrés de liberté", 'static');
addPage_2('fr/moreVariation', 'moreVariation5', "Racine l'erreur quadratique moyenne", 'interact');
addPage_2('fr/moreVariation', 'moreVariation6', "Interprétation graphique de SD", 'interact');
addSection('bk/french', 'sec_percentile', "Les proportions et les centiles");
addPage_2('fr/percentile', 'percentile1', "Ensemble de données illustratives", 'interact');
addPage_2('fr/percentile', 'percentile2', "Proportions cumulatives", 'interact');
addPage_2('fr/percentile', 'percentile3', "Graphique des proportions cumulatives", 'interact');
addPage_2('fr/percentile', 'percentile4', "Centiles", 'interact');
addPage_2('fr/percentile', 'percentile5', "Afficher les percentiles", 'interact');
addPage_2('fr/percentile', 'percentile6', "En comparant des groupes", 'interact');
addPage_2('fr/percentile', 'percentile7', "En comparant des groupes d'autres percentiles", 'interact');
addPage_2('fr/percentile', 'percentile8', "Une meilleure définition des centiles", 'interact');
addSection('bk/french_b', 'sec_transform', "Transformations");
addPage_2('fr/transform', 'transform_b1', "Linear transformations", 'interact');
addPage_2('fr/transform', 'transform_b2', "Log transformations", 'interact');
addPage_2('fr/transform', 'transform3', "Quand utiliser une transformation logarithmique?", 'interact');
addPage_2('fr/transform', 'transform4', "Puissance transformations", 'interact');
addPage_2('fr/transform', 'transform5', "Effet de transformations sur les écrans", 'interact');
addSection('bk/french_b', 'sec_counts', "Les donn&eacute;es discr&egrave;tes (chiffres)");
addPage_2('fr/counts', 'counts_b1', "Discrete and continuous data", 'interact');
addPage_2('fr/counts', 'counts_b2', "Histograms for counts", 'interact');
addPage_2('fr/counts', 'counts3', "Les diagrammes à barres", 'interact');
addPage_2('fr/counts', 'counts_b4', "Mean and st devn", 'static');

addChapter('bk/french_b', 'ch_bivar', "Deux Variables Num&eacute;riques");
addSection('bk/french_b', 'sec_scatterplot', "Nuage de points");
addPage_2('fr/scatterplot', 'scatterplot_b1', "Bivariate data sets", 'interact');
addPage_2('fr/scatterplot', 'scatterplot2', "Nuage de points", 'interact');
addPage_2('fr/scatterplot', 'scatterplot3', "Limitations des écrans univariée", 'interact');
addPage_2('fr/scatterplot', 'scatterplot4', "Distributions marginales", 'interact');
addPage_2('fr/scatterplot', 'scatterplot5', "Des séries chronologiques", 'interact');
addSection('bk/french', 'sec_relationship', "Comprendre les relations");
addPage_2('fr/relationship', 'relationship1', "Force d'une relation", 'interact');
addPage_2('fr/relationship', 'relationship2', "Les valeurs aberrantes", 'interact');
addPage_2('fr/relationship', 'relationship3', "Clusters", 'interact');
addPage_2('fr/relationship', 'relationship4', "Dangers de sur-interprétation", 'interact');
addPage_2('fr/relationship', 'relationship5', "Les variables explicatives et la réponse", 'static');
addSection('bk/french_b', 'sec_correlation', "Corr&eacute;lation");
addPage_2('fr/correlation', 'correlation_b1', "Units for X and Y", 'interact');
addPage_2('fr/correlation', 'correlation2', "Variables sans unités (z-scores)", 'interact');
addPage_2('fr/correlation', 'correlation3', "Le coefficient de corrélation", 'interact');
addPage_2('fr/correlation', 'correlation4', "Les diagrammes de dispersion et de la valeur de r", 'interact');
addPage_2('fr/correlation', 'correlation5', "Relations non linéaires", 'interact');
addPage_2('fr/correlation', 'correlation6', "R n'a pas raconter toute l'histoire", 'interact');
addSection('bk/french_b', 'sec_leastSqrs', "Moindres carr&eacute;s");
addPage_2('fr/leastSqrs', 'leastSqrs_b1', "Predicting Y from X", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs2', "Les modèles linéaires", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs3', "Valeurs ajustées et des résidus", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs4', "Moindres carrés", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs5', "La courbure et les valeurs aberrantes", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs6', "Parcelles résiduelles", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs7', "Prédire X Y et la prédiction", 'interact');
addSection('bk/french', 'sec_curvature', "Relations non linéaires");
addPage_2('fr/curvature', 'curvature1', "Transformations et la corrélation", 'interact');
addPage_2('fr/curvature', 'curvature2', "Transformations et modèles", 'interact');
addPage_2('fr/curvature', 'curvature3', "Modèles quadratiques", 'interact');
addPage_2('fr/curvature', 'curvature4', "Les dangers de l'extrapolation", 'interact');

addChapter('bk/french_b', 'ch_timeSeries', "S&eacute;ries Chronologiques");
addSection('bk/french_b', 'sec_timePlot', "Graphiques chronologiques");
addPage_2('fr/timePlot', 'timePlot_b1', "Graphiques chronologiques", 'interact');
addPage_2('fr/timePlot', 'timePlot_b2', "Patterns in time series", 'interact');
addPage_2('fr/timePlot', 'timePlot3', "Plusieurs séries chronologiques", 'interact');
addSection('bk/french', 'sec_smoothing', "Lissage");
addPage_2('fr/smoothing', 'smoothing1', "Moyennes mobiles", 'interact');
addPage_2('fr/smoothing', 'smoothing2', "En savoir plus sur les moyennes mobiles", 'interact');
addPage_2('fr/smoothing', 'smoothing3', "Lissage robuste", 'interact');
addPage_2('fr/smoothing', 'smoothing4', "Lissage exponentiel", 'interact');
addPage_2('fr/smoothing', 'smoothing5', "Lissage Lowess des séries chronologiques", 'interact');
addPage_2('fr/smoothing', 'smoothing6', "Lissage Lowess de diagrammes de dispersion", 'interact');
addSection('bk/french', 'sec_trend', "Tendance à long terme");
addPage_2('fr/trend', 'trend1', "Tendance linéaire", 'interact');
addPage_2('fr/trend', 'trend2', "Tendance quadratique", 'interact');
addPage_2('fr/trend', 'trend3', "Prévision", 'interact');
addPage_2('fr/trend', 'trend4', "Tendance polynomiale", 'interact');
addPage_2('fr/trend', 'trend5', "Élimination de la tendance d'une série chronologique", 'interact');

addChapter('bk/french', 'ch_cat', "Variables Catégorielles");
addSection('bk/french_b', 'sec_freqTable', "Tables de fr&eacute;quences");
addPage_2('fr/freqTable', 'freqTable1', "Tables de fréquences", 'interact');
addPage_2('fr/freqTable', 'freqTable_b2', "Proportions and percentages", 'interact');
addPage_2('fr/freqTable', 'freqTable3', "Reconnaissant les tableaux de fréquence", 'static');
addPage_2('fr/freqTable', 'freqTable4', "Modifications aux catégories", 'interact');
addSection('bk/french_b', 'sec_univarCat', "Diagrammes &agrave; barres et camemberts");
addPage_2('fr/univarCat', 'univarCat_b1', "Bar charts", 'interact');
addPage_2('fr/univarCat', 'univarCat2', "Diagrammes de Pareto", 'interact');
addPage_2('fr/univarCat', 'univarCat_b3', "Chartjunk and misleading bar charts", 'static');
addPage_2('fr/univarCat', 'univarCat_b4', "Stacked bar charts and pie charts", 'interact');
addPage_2('fr/univarCat', 'univarCat_b5', "Comparison of bar and pie charts", 'interact');
addPage_2('fr/univarCat', 'univarCat_b6', "Chartjunk for pie charts", 'static');
addPage_2('fr/univarCat', 'univarCat_b7', "Bar and pie charts for quantities", 'interact');
addSection('bk/french_b', 'sec_groupedCat', "En comparant des groupes");
addPage_2('fr/groupedCat', 'groupedCat1', "Tableaux de contingence", 'interact');
addPage_2('fr/groupedCat', 'groupedCat_b2', "Contingency table examples", 'static');
addPage_2('fr/groupedCat', 'groupedCat_b3', "Bar charts using proportions", 'interact');
addPage_2('fr/groupedCat', 'groupedCat_b4', "Stacked bar charts", 'interact');
addPage_2('fr/groupedCat', 'groupedCat_b5', "Two special cases", 'interact');
addSection('bk/french_b', 'sec_bivarCat', "Bivari&eacute;es distributions cat&eacute;gorielles");
addPage_2('fr/bivarCat', 'bivarCat_b1', "Relationships between variables", 'static');
addPage_2('fr/bivarCat', 'bivarCat2', "Histogrammes en 3 dimensions", 'interact');
addPage_2('fr/bivarCat', 'bivarCat3', "Graphiques à barres en cluster", 'interact');
addPage_2('fr/bivarCat', 'bivarCat4', "Distributions marginales", 'interact');
addPage_2('fr/bivarCat', 'bivarCat5', "Distributions conditionnelles", 'interact');
addPage_2('fr/bivarCat', 'bivarCat6', "En savoir plus sur les distributions conditionnelles", 'interact');
addPage_2('fr/bivarCat', 'bivarCat7', "Distns conditionnelle vs marginale", 'interact');
addSection('bk/french', 'sec_tableDisplay', "Présentation des données dans tableaux");
addPage_2('fr/tableDisplay', 'tableDisplay1', "Quadrillage et l'espace blanc", 'static');
addPage_2('fr/tableDisplay', 'tableDisplay2', "Mise en page et d'annotation", 'static');
addPage_2('fr/tableDisplay', 'tableDisplay3', "Chiffres significatifs et le bruit des données", 'interact');
addPage_2('fr/tableDisplay', 'tableDisplay4', "Variables significatives", 'interact');
addPage_2('fr/tableDisplay', 'tableDisplay5', "Permutation des lignes et des colonnes", 'static');
addPage_2('fr/tableDisplay', 'tableDisplay6', "Réorganisation des lignes", 'interact');
addPage_2('fr/tableDisplay', 'tableDisplay7', "Exemple", 'static');
addSection('bk/french_b', 'sec_logistic', "R&eacute;gression logistique");
addPage_2('fr/logistic', 'logistic_b1', "Categorical responses", 'interact');
addPage_2('fr/logistic', 'logistic_b2', "Fitted values and predictions", 'interact');
addPage_2('fr/logistic', 'logistic3', "Courbe logistique", 'interact');
addPage_2('fr/logistic', 'logistic_b4', "Obtaining a good fit", 'interact');

addChapter('bk/french', 'ch_multivar', "Multivariée des données");
addSection('bk/french_b', 'sec_multivariate', "Displaying multivariate data");
addPage_2('fr/multivariate', 'multivariate_b1', "Representing a third variable", 'interact');
addPage_2('fr/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact');
addPage_2('fr/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact');
addPage_2('fr/multivariate', 'multivariate4', "Brushing example", 'interact');
addPage_2('fr/multivariate', 'multivariate5', "Slicing", 'interact');
addSection('bk/french', 'sec_regnGroups', "Groupes et régression");
addPage_2('fr/regnGroups', 'regnGroups1', "Additional variables in regression", 'interact');
addPage_2('fr/regnGroups', 'regnGroups2', "Displaying groups", 'interact');
addPage_2('fr/regnGroups', 'regnGroups3', "Regression with grouped data", 'interact');
addPage_2('fr/regnGroups', 'regnGroups4', "Parallel regression lines", 'interact');
addPage_2('fr/regnGroups', 'regnGroups5', "Transformed variables and groups", 'interact');
addPage_2('fr/regnGroups', 'regnGroups6', "Grouping with a numerical variable", 'interact');
addPage_2('fr/regnGroups', 'regnGroups7', "Scatterplot matrix with groups", 'interact');
addSection('bk/french', 'sec_multiRegn', "Régression multiple");
addPage_2('fr/multiRegn', 'multiRegn1', "More than one explanatory variable", 'interact');
addPage_2('fr/multiRegn', 'multiRegn2', "Multiple regression equation", 'interact');
addPage_2('fr/multiRegn', 'multiRegn3', "Interpreting coefficients", 'interact');
addPage_2('fr/multiRegn', 'multiRegn4', "Scatterplot of three variables", 'interact');
addPage_2('fr/multiRegn', 'multiRegn5', "Displayng the linear equation for Y vs X and Z", 'interact');
addPage_2('fr/multiRegn', 'multiRegn6', "Fitted values and residuals", 'interact');
addPage_2('fr/multiRegn', 'multiRegn7', "Least squares estimation", 'interact');
addSection('bk/french_b', 'sec_lurking', "Marginal relationships");
addPage_2('fr/lurking', 'lurking_b1', "Misleading marginal correlation", 'interact');
addPage_2('fr/lurking', 'lurking_b2', "Misleading marginal difference in means", 'interact');
addPage_2('fr/lurking', 'lurking3', "Simpsons paradox", 'interact');
addPage_2('fr/lurking', 'lurking4', "Other examples with lurking variables", 'static');

addChapter('bk/french', 'ch_sample', "Échantillonnage et de la variabilité");
addSection('bk/french_b', 'sec_popSamp', "Finite populations");
addPage_2('fr/popSamp', 'popSamp_b1', "Census or sample?", 'interact');
addPage_2('fr/popSamp', 'popSamp2', "Variability in a sample", 'interact');
addPage_2('fr/popSamp', 'popSamp_b3', "Sampling error", 'interact');
addPage_2('fr/popSamp', 'popSamp_b4', "Sampling error and sample size", 'interact');
addPage_2('fr/popSamp', 'popSamp_b5', "Sampling from finite populations", 'interact');
addPage_2('fr/popSamp', 'popSamp6', "Selecting a random sample", 'interact');
addSection('bk/french_b', 'sec_infPopn', "Samples from distributions");
addPage_2('fr/infPopn', 'infPopn_b1', "Data as representatives", 'static');
addPage_2('fr/infPopn', 'infPopn_b2', "Randomness of data", 'interact');
addPage_2('fr/infPopn', 'infPopn_b3', "Model to explain randomness", 'static');
addPage_2('fr/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact');
addPage_2('fr/infPopn', 'infPopn5', "Information from a single sample", 'interact');
addSection('bk/french_b', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('fr/probDensity', 'probDensity_b1', "Finite populations", 'interact');
addPage_2('fr/probDensity', 'probDensity_b2', "Probabilities with infinite populations", 'interact');
addPage_2('fr/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact');
addPage_2('fr/probDensity', 'probDensity4', "Probability density functions", 'interact');
addPage_2('fr/probDensity', 'probDensity5', "Normal distributions", 'interact');
addPage_2('fr/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact');
addPage_2('fr/probDensity', 'probDensity7', "Properties of probability", 'static');
addSection('bk/french_b', 'sec_probSim', "Simulation (optional)");
addPage_2('fr/probSim', 'probSim1', "Probability models and simulation", 'interact');
addPage_2('fr/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact');
addPage_2('fr/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact');
addPage_2('fr/probSim', 'probSim_b4', "Assessing unusual features in data", 'interact');
addPage_2('fr/probSim', 'probSim5', "Random numbers", 'interact');
addPage_2('fr/probSim', 'probSim6', "Generating categorical values", 'interact');
addPage_2('fr/probSim', 'probSim7', "Generating numerical values", 'interact');
addSection('bk/french_b', 'sec_randomMean', "Distribution of sample mean");
addPage_2('fr/randomMean', 'randomMean_b1', "Variability of sample statistics", 'interact');
addPage_2('fr/randomMean', 'randomMean2', "Variability of sample mean", 'interact');
addPage_2('fr/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact');
addPage_2('fr/randomMean', 'randomMean4', "Means from normal populations", 'interact');
addPage_2('fr/randomMean', 'randomMean5', "Large-sample normality of means", 'interact');
addPage_2('fr/randomMean', 'randomMean_b6', "Distribution of mean from a sample", 'static');
addPage_2('fr/randomMean', 'randomMean_b7', "Requirement of independence", 'interact');
addPage_2('fr/randomMean', 'randomMean8', "Sampling from finite populations", 'interact');
addSection('bk/french_b', 'sec_normalDistn', "Normal distributions");
addPage_2('fr/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact');
addPage_2('fr/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact');
addPage_2('fr/normalDistn', 'normalDistn_b3', "Sketching a normal distribution", 'interact');
addPage_2('fr/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact');
addPage_2('fr/normalDistn', 'normalDistn5', "Z-scores", 'interact');
addPage_2('fr/normalDistn', 'normalDistn_b6', "Finding normal probabilities", 'interact');
addPage_2('fr/normalDistn', 'normalDistn_b7', "Other probabilities", 'interact');
addPage_2('fr/normalDistn', 'normalDistn8', "Normal tables", 'static');
addPage_2('fr/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact');
addPage_2('fr/normalDistn', 'normalDistn10', "Normal probability plots", 'interact');
addSection('bk/french_b', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('fr/randomPropn', 'randomPropn1', "Proportion and probability", 'interact');
addPage_2('fr/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact');
addPage_2('fr/randomPropn', 'randomPropn_b3', "Binomial distribution", 'interact');
addPage_2('fr/randomPropn', 'randomPropn_b4', "Binomial probability examples", 'static');
addPage_2('fr/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact');
addPage_2('fr/randomPropn', 'randomPropn_b6', "Normal approximation examples", 'static');
addSection('bk/french_b', 'sec_sampPractice', "Sampling in practice");
addPage_2('fr/sampPractice', 'sampPractice_b1', "Stratified sampling", 'interact');
addPage_2('fr/sampPractice', 'sampPractice2', "Cluster sampling", 'interact');
addPage_2('fr/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact');
addPage_2('fr/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static');
addPage_2('fr/sampPractice', 'sampPractice_b5', "Coverage and non-response errors", 'static');
addPage_2('fr/sampPractice', 'sampPractice_b6', "Interviewer and instrument errors", 'interact');
addPage_2('fr/sampPractice', 'sampPractice7', "Survey design issues", 'static');

addChapter('bk/french', 'ch_expDesign', "Expériences conçues");
addSection('bk/french_b', 'sec_causal', "Association &amp; causal relationships");
addPage_2('fr/causal', 'causal_b1', "Interest in relationships", 'static');
addPage_2('fr/causal', 'causal2', "Relations causales et non causales", 'static');
addPage_2('fr/causal', 'causal_b3', "Detecting causal relationships", 'static');
addPage_2('fr/causal', 'causal_b4', "Observational and experimental data", 'interact');
addPage_2('fr/causal', 'causal5', "La collecte des données et de la causalité", 'interact');
addSection('bk/french_b', 'sec_designIntro', "Principles of experimental design");
addPage_2('fr/designIntro', 'designIntro_b1', "Experiments and treatments", 'static');
addPage_2('fr/designIntro', 'designIntro2', "Variable experimental units", 'interact');
addPage_2('fr/designIntro', 'designIntro3', "A badly designed experiment", 'interact');
addPage_2('fr/designIntro', 'designIntro4', "Confounding", 'static');
addPage_2('fr/designIntro', 'designIntro_b5', "Randomisation", 'interact');
addPage_2('fr/designIntro', 'designIntro6', "Replication", 'static');
addPage_2('fr/designIntro', 'designIntro7', "Blocking", 'interact');
addSection('bk/french_b', 'sec_pairBlock', "Pairing and blocks");
addPage_2('fr/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact');
addPage_2('fr/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact');
addPage_2('fr/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact');
addPage_2('fr/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact');
addPage_2('fr/pairBlock', 'pairBlock_b5', "Randomised block experiments", 'static');
addSection('bk/french_b', 'sec_designTwo', "Two or more factors");
addPage_2('fr/designTwo', 'designTwo_b1', "Experiments with 2 factors", 'interact');
addPage_2('fr/designTwo', 'designTwo_b2', "Factorial design", 'static');
addPage_2('fr/designTwo', 'designTwo3', "Simple model for two factors", 'interact');
addPage_2('fr/designTwo', 'designTwo4', "Interaction between factors", 'interact');
addPage_2('fr/designTwo', 'designTwo5', "Example with interaction", 'interact');
addPage_2('fr/designTwo', 'designTwo_b6', "No-interaction model for three factors", 'interact');
addPage_2('fr/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact');
addSection('bk/french', 'sec_designPrelim', "Questions pratiques en matière de conception");
addPage_2('fr/designPrelim', 'designPrelim1', "Purpose", 'static');
addPage_2('fr/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static');
addPage_2('fr/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static');

addChapter('bk/french', 'ch_estimation', "L'estimation des paramètres");
addSection('bk/french_b', 'sec_estIntro', "Introduction to estimation");
addPage_2('fr/estIntro', 'estIntro_b1', "Interest in populations", 'static');
addPage_2('fr/estIntro', 'estIntro_b2', "Interest in parameters", 'static');
addPage_2('fr/estIntro', 'estIntro3', "Applications of estimation", 'static');
addPage_2('fr/estIntro', 'estIntro4', "Estimation error", 'static');
addPage_2('fr/estIntro', 'estIntro_b5', "Distribution of errors", 'interact');
addPage_2('fr/estIntro', 'estIntro6', "Standard error and bias", 'static');
addPage_2('fr/estIntro', 'estIntro7', "Interval estimates", 'static');
addSection('bk/french_b', 'sec_seMean', "Standard error of mean");
addPage_2('fr/seMean', 'seMean_b1', "Error distribution for mean", 'interact');
addPage_2('fr/seMean', 'seMean_b2', "Standard error when \u03c3 is known", 'interact');
addPage_2('fr/seMean', 'seMean_b3', "Interpreting the standard error", 'static');
addPage_2('fr/seMean', 'seMean_b4', "Standard error when \u03c3 is unknown", 'static');
addPage_2('fr/seMean', 'seMean5', "Standard error vs standard deviation", 'interact');
addPage_2('fr/seMean', 'seMean_b6', "Using SEs to compare estimators", 'interact');
addPage_2('fr/seMean', 'seMean7', "More about bias", 'interact');
addSection('bk/french_b', 'sec_ciMean', "Confidence interval for mean");
addPage_2('fr/ciMean', 'ciMean1', "Intervalle de confiance à partir de l'erreur-type", 'static');
addPage_2('fr/ciMean', 'ciMean_b2', "Confidence interval for mean, known sigma", 'interact');
addPage_2('fr/ciMean', 'ciMean3', "Le niveau de confiance", 'interact');
addPage_2('fr/ciMean', 'ciMean4', "Le niveau de confiance, si sigma est remplacé par s", 'interact');
addPage_2('fr/ciMean', 'ciMean5', "Intervalle de confiance pour \u03bc, \u03c3 inconnu", 'interact');
addPage_2('fr/ciMean', 'ciMean6', "Propriétés de l'intervalle de confiance à 95%", 'interact');
addPage_2('fr/ciMean', 'ciMean_b7', "Examples", 'static');
addSection('bk/french_b', 'sec_estPropn', "Estimating proportions");
addPage_2('fr/estPropn', 'estPropn1', "General framework for estimation", 'static');
addPage_2('fr/estPropn', 'estPropn2', "Estimating a proportion", 'interact');
addPage_2('fr/estPropn', 'estPropn_b3', "Error distribution", 'interact');
addPage_2('fr/estPropn', 'estPropn_b4', "Normal approximation to error distribution", 'interact');
addPage_2('fr/estPropn', 'estPropn_b5', "Confidence interval for proportion", 'static');
addPage_2('fr/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact');
addPage_2('fr/estPropn', 'estPropn_b7', "Confidence interval examples", 'static');
addSection('bk/french_b', 'sec_ciExtra', "More about estimation");
addPage_2('fr/ciExtra', 'ciExtra_b1', "Margin of error", 'interact');
addPage_2('fr/ciExtra', 'ciExtra2', "Taille de l'échantillon pour l'estimation signifie", 'interact');
addPage_2('fr/ciExtra', 'ciExtra_b3', "Sample size for estimating proportion", 'interact');
addPage_2('fr/ciExtra', 'ciExtra4', "Autres niveaux de confiance", 'interact');
addSection('bk/french_b', 'sec_estOther', "Simulation &amp; bootstrap (advanced)");
addPage_2('fr/estOther', 'estOther1', "Need for simulation", 'static');
addPage_2('fr/estOther', 'estOther2', "Error distribution by simulation (advanced)", 'interact');
addPage_2('fr/estOther', 'estOther3', "Simulation from normal approximation (advanced)", 'interact');
addPage_2('fr/estOther', 'estOther4', "Bootstrap error distribution", 'interact');
addPage_2('fr/estOther', 'estOther_b5', "Standard error of correlation from bootstrap", 'interact');
addPage_2('fr/estOther', 'estOther6', "CIs from simulation", 'interact');

addChapter('bk/french', 'ch_testing', "Tester des hypothèses");
addSection('bk/french_b', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('fr/testIntro', 'testIntro_b1', "Inference", 'static');
addPage_2('fr/testIntro', 'testIntro2', "Soccer league simulation", 'interact');
addPage_2('fr/testIntro', 'testIntro_b3', "Simulation to test a proportion", 'interact');
addPage_2('fr/testIntro', 'testIntro4', "Test for a mean", 'interact');
addPage_2('fr/testIntro', 'testIntro_b5', "Randomisation tests", 'interact');
addPage_2('fr/testIntro', 'testIntro6', "Soccer league randomisation", 'interact');
addPage_2('fr/testIntro', 'testIntro_b7', "Common patterns in hypothesis testing", 'static');
addSection('bk/french_b', 'sec_testPropn', "Tests about proportions");
addPage_2('fr/testPropn', 'testPropn_b1', "Inference about parameters", 'static');
addPage_2('fr/testPropn', 'testPropn_b2', "P-value for testing proportion", 'interact');
addPage_2('fr/testPropn', 'testPropn_b3', "Another example of testing a proportion", 'interact');
addPage_2('fr/testPropn', 'testPropn_b4', "One- and two-tailed tests", 'interact');
addPage_2('fr/testPropn', 'testPropn_b5', "Tests based on normal approximation", 'interact');
addSection('bk/french_b', 'sec_testMean', "Tests about means");
addPage_2('fr/testMean', 'testMean1', "Introduction", 'static');
addPage_2('fr/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static');
addPage_2('fr/testMean', 'testMean_b3', "P-value for test (known sigma)", 'interact');
addPage_2('fr/testMean', 'testMean4', "The t distribution", 'interact');
addPage_2('fr/testMean', 'testMean5', "The t test for a mean", 'interact');
addSection('bk/french', 'sec_decision', "Décisions et le niveau de signification");
addPage_2('fr/decision', 'decision1', "Hypothesis tests and decisions", 'static');
addPage_2('fr/decision', 'decision2', "Decision rules", 'interact');
addPage_2('fr/decision', 'decision3', "Significance level and p-values", 'interact');
addPage_2('fr/decision', 'decision4', "Sample size and power", 'interact');
addSection('bk/french_b', 'sec_testPValue', "Properties of p-values");
addPage_2('fr/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact');
addPage_2('fr/testPValue', 'testPValue_b2', "P-value and consistency with null hypothesis", 'interact');
addPage_2('fr/testPValue', 'testPValue3', "Distribution of p-values", 'interact');
addPage_2('fr/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact');
addPage_2('fr/testPValue', 'testPValue_b5', "P-values for other tests", 'interact');

addChapter('bk/french', 'ch_twoGroups', "En comparant des groupes");
addSection('bk/french_b', 'sec_twoGroupModel', "Models for two groups");
addPage_2('fr/twoGroupModel', 'twoGroupModel_b1', "Interest in underlying population", 'static');
addPage_2('fr/twoGroupModel', 'twoGroupModel_b2', "Model for two groups", 'interact');
addPage_2('fr/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact');
addPage_2('fr/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact');
addPage_2('fr/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact');
addSection('bk/french', 'sec_sumDiff', "Distribution des sommes et des différences");
addPage_2('fr/sumDiff', 'sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('fr/sumDiff', 'sumDiff2', "Sum and differences", 'interact');
addPage_2('fr/sumDiff', 'sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('fr/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static');
addSection('bk/french_b', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('fr/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact');
addPage_2('fr/twoGroupInf', 'twoGroupInf_b2', "Distribution of estimation error", 'static');
addPage_2('fr/twoGroupInf', 'twoGroupInf_b3', "CI for difference between means", 'interact');
addPage_2('fr/twoGroupInf', 'twoGroupInf_b4', "Testing a hypothesis", 'interact');
addPage_2('fr/twoGroupInf', 'twoGroupInf_b5', "One-tailed tests for differences", 'interact');
addSection('bk/french', 'sec_twoGroupPropn', "Comparaison de deux proportions");
addPage_2('fr/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact');
addPage_2('fr/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact');
addPage_2('fr/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static');
addPage_2('fr/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static');
addSection('bk/french_b', 'sec_testPaired', "Paired t test");
addPage_2('fr/testPaired', 'testPaired_b1', "Paired data examples", 'static');
addPage_2('fr/testPaired', 'testPaired_b2', "Analysis of differences", 'interact');
addPage_2('fr/testPaired', 'testPaired3', "Paired t-test", 'interact');
addPage_2('fr/testPaired', 'testPaired4', "Pairing and experimental design", 'interact');
addSection('bk/french_b', 'sec_multiGroup', "Comparing several means");
addPage_2('fr/multiGroup', 'multiGroup_b1', "Model with common standard deviation", 'interact');
addPage_2('fr/multiGroup', 'multiGroup2', "Estimate of common standard deviation", 'interact');
addPage_2('fr/multiGroup', 'multiGroup_b3', "Inference about two groups", 'static');
addPage_2('fr/multiGroup', 'multiGroup4', "Assessing differences between groups", 'interact');
addPage_2('fr/multiGroup', 'multiGroup5', "Sums of squares", 'interact');
addPage_2('fr/multiGroup', 'multiGroup_b6', "Coefficient of determination", 'static');
addPage_2('fr/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact');
addPage_2('fr/multiGroup', 'multiGroup_b8', "Examples", 'static');
addSection('bk/french', 'sec_randBlock', "Blocs randomisés");
addPage_2('fr/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static');
addPage_2('fr/randBlock', 'randBlock2', "Importance of using block information", 'interact');
addPage_2('fr/randBlock', 'randBlock3', "Data with no baseline treatment", 'interact');
addPage_2('fr/randBlock', 'randBlock4', "Randomised block designs", 'interact');
addPage_2('fr/randBlock', 'randBlock5', "Model for randomised blocks", 'interact');
addPage_2('fr/randBlock', 'randBlock6', "Removing block effects", 'interact');
addPage_2('fr/randBlock', 'randBlock7', "Sums of squares", 'interact');
addPage_2('fr/randBlock', 'randBlock8', "Anova table and examples", 'static');

addChapter('bk/french', 'ch_regnInference', "Régression inférence");
addSection('bk/french_b', 'sec_regnModel', "Linear regression models");
addPage_2('fr/regnModel', 'regnModel_b1', "Interest in generalising from data", 'interact');
addPage_2('fr/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact');
addPage_2('fr/regnModel', 'regnModel3', "Normal linear model", 'interact');
addPage_2('fr/regnModel', 'regnModel4', "Errors and 95% band on scatterplot", 'interact');
addPage_2('fr/regnModel', 'regnModel_b5', "Model parameters", 'interact');
addSection('bk/french', 'sec_regnEst', "Estimation des paramètres");
addPage_2('fr/regnEst', 'regnEst1', "Point estimates of slope and intercept", 'interact');
addPage_2('fr/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact');
addPage_2('fr/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact');
addPage_2('fr/regnEst', 'regnEst4', "Standard error of least squares slope", 'static');
addPage_2('fr/regnEst', 'regnEst5', "95% confidence interval for slope", 'static');
addPage_2('fr/regnEst', 'regnEst6', "Properties of confidence interval", 'interact');
addPage_2('fr/regnEst', 'regnEst7', "Influences on accuracy", 'interact');
addSection('bk/french', 'sec_regnTest', "Paramètres tests de régression");
addPage_2('fr/regnTest', 'regnTest1', "Importance of zero slope", 'interact');
addPage_2('fr/regnTest', 'regnTest2', "Testing whether slope is zero", 'static');
addPage_2('fr/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static');
addPage_2('fr/regnTest', 'regnTest4', "Properties of p-values", 'interact');
addSection('bk/french_b', 'sec_regnPred', "Predicting the response");
addPage_2('fr/regnPred', 'regnPred_b1', "Estimated response distn at X", 'interact');
addPage_2('fr/regnPred', 'regnPred2', "Variability of estimate at X", 'interact');
addPage_2('fr/regnPred', 'regnPred_b3', "Estimating the mean vs prediction", 'interact');
addPage_2('fr/regnPred', 'regnPred_b4', "Confidence and prediction intervals", 'interact');
addSection('bk/french_b', 'sec_regnProblem', "Linear model assumptions");
addPage_2('fr/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact');
addPage_2('fr/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact');
addPage_2('fr/regnProblem', 'regnProblem_b3', "Curvature and non-constant variance &mdash; transforming Y", 'interact');
addPage_2('fr/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact');
addPage_2('fr/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact');
addPage_2('fr/regnProblem', 'regnProblem6', "Non-normal errors", 'interact');
addPage_2('fr/regnProblem', 'regnProblem7', "Correlated errors", 'interact');

addChapter('bk/french', 'ch_independence', "Indépendance");
addSection('bk/french_b', 'sec_prob', "Probability and applications");
addPage_2('fr/prob', 'prob_b1', "Joint probabilities", 'interact');
addPage_2('fr/prob', 'prob_b2', "Marginal probabilities", 'interact');
addPage_2('fr/prob', 'prob_b3', "Conditional probabilities", 'interact');
addPage_2('fr/prob', 'prob4', "Graphical display of probabilities", 'interact');
addPage_2('fr/prob', 'prob5', "Calculations with probabilities", 'interact');
addSection('bk/french_b', 'sec_indep', "Independence");
addPage_2('fr/indep', 'indep_b1', "Association between categorical variables", 'static');
addPage_2('fr/indep', 'indep2', "Independence of categorical variables", 'interact');
addPage_2('fr/indep', 'indep3', "Independence from samples", 'static');
addPage_2('fr/indep', 'indep4', "Testing for independence", 'interact');
addPage_2('fr/indep', 'indep5', "Chi-squared test statistic", 'interact');
addPage_2('fr/indep', 'indep6', "P-value for chi-squared test", 'interact');
addPage_2('fr/indep', 'indep7', "Examples", 'static');
addPage_2('fr/indep', 'indep8', "Comparing groups", 'static');

var language = "fr";
var logoGif = null;
var homeDir = "bk/french_b";
var versionGif = "images/castFrench";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Complet';
var summaryTextString = 'Résumé';
var videoTextString = 'Video';
var appletTextString = 'Complet';
fullTabTooltip = 'Full version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Interactive version of page';
var chapterString = 'Chapitre';

var versionName = {'_b': 'Biométrique', '_g': 'Général', '_c': 'Business', '_m': 'Climatiques', '_o': 'Stats officielles', '_a': 'Africaine', '_z': 'Autres'};
var versions = {};
versions['context1'] = new Array('_b', '_g', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_b', '_g');
versions['structures1'] = new Array('_b', '_g', '_a', '_c');
versions['structures2'] = new Array('_b', '_g', '_a', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_b', '_g', '_c');
versions['structures6'] = new Array('_b', '_g');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_b', '_g', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay2'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay3'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay4'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay5'] = new Array('_b', '_g', '_a', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_b', '_g', '_c');
versions['displayInterp2'] = new Array('_b', '_g', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_b', '_g');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_b', '_g', '_c', '_m');
versions['density6'] = new Array('_b', '_g', '_c');
versions['density7'] = new Array('_b', '_g', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_b', '_g', '_c', '_m');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_b', '_g');
versions['centerSpread1'] = new Array('_b', '_g');
versions['centerSpread2'] = new Array('_b', '_g');
versions['centerSpread3'] = new Array('_b', '_g', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_b', '_g');
versions['transform2'] = new Array('_b', '_g', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['counts1'] = new Array('_b', '_g', '_c');
versions['counts2'] = new Array('_b', '_g', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['counts4'] = new Array('_b', '_g', '_c');
versions['scatterplot1'] = new Array('_b', '_g', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship2'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_b', '_g', '_c');
versions['leastSqrs1'] = new Array('_b', '_g', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_b', '_g', '_c');
versions['timePlot2'] = new Array('_b', '_g', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_b', '_g', '_a');
versions['univarCat1'] = new Array('_b', '_g', '_a');
versions['univarCat3'] = new Array('_b', '_g', '_a');
versions['univarCat4'] = new Array('_b', '_g', '_c');
versions['univarCat5'] = new Array('_b', '_g', '_c');
versions['univarCat6'] = new Array('_b', '_g', '_c');
versions['univarCat7'] = new Array('_b', '_g');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_b', '_g', '_c');
versions['groupedCat3'] = new Array('_b', '_g', '_c');
versions['groupedCat4'] = new Array('_b', '_g', '_c');
versions['groupedCat5'] = new Array('_b', '_g', '_c');
versions['bivarCat1'] = new Array('_b', '_g', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['logistic1'] = new Array('_b', '_g', '_c');
versions['logistic2'] = new Array('_b', '_g', '_c');
versions['logistic4'] = new Array('_b', '_g', '_c');
versions['multivariate1'] = new Array('_b', '_g', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_b', '_g', '_c');
versions['lurking2'] = new Array('_b', '_g');
versions['lurking3'] = new Array('_g', '_c');
versions['popSamp1'] = new Array('_b', '_g', '_a', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_b', '_g', '_a', '_c');
versions['popSamp4'] = new Array('_b', '_g');
versions['popSamp5'] = new Array('_b', '_g', '_c');
versions['infPopn1'] = new Array('_b', '_g', '_c');
versions['infPopn2'] = new Array('_b', '_g', '_c', '_z');
versions['infPopn3'] = new Array('_b', '_g', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_b', '_g', '_c');
versions['probDensity2'] = new Array('_b', '_g', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_b', '_g', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_b', '_g', '_c');
versions['randomMean6'] = new Array('_b', '_g', '_c');
versions['randomMean7'] = new Array('_b', '_g');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_b', '_g', '_c');
versions['normalDistn6'] = new Array('_b', '_g', '_c');
versions['normalDistn7'] = new Array('_b', '_g', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_b', '_g', '_c');
versions['randomPropn4'] = new Array('_b', '_g', '_c');
versions['randomPropn6'] = new Array('_b', '_g', '_c');
versions['sampPractice1'] = new Array('_b', '_g');
versions['sampPractice5'] = new Array('_b', '_g', '_c');
versions['sampPractice6'] = new Array('_b', '_g');
versions['causal1'] = new Array('_b', '_g', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_b', '_g', '_c');
versions['causal4'] = new Array('_b', '_g', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_b', '_g', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_b', '_g', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_b', '_g');
versions['designTwo1'] = new Array('_b', '_g');
versions['designTwo2'] = new Array('_b', '_g');
versions['designTwo6'] = new Array('_b', '_g');
versions['designPrelim2'] = new Array('_g', '_c');
versions['estIntro1'] = new Array('_b', '_g', '_c');
versions['estIntro2'] = new Array('_b', '_g', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_b', '_g', '_c');
versions['seMean1'] = new Array('_b', '_g', '_c');
versions['seMean2'] = new Array('_b', '_g');
versions['seMean3'] = new Array('_b', '_g');
versions['seMean4'] = new Array('_b', '_g', '_c');
versions['seMean6'] = new Array('_b', '_g', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_b', '_g');
versions['ciMean7'] = new Array('_b', '_g', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_b', '_g', '_c');
versions['estPropn4'] = new Array('_b', '_g', '_c');
versions['estPropn5'] = new Array('_b', '_g', '_c');
versions['estPropn7'] = new Array('_b', '_g', '_c');
versions['ciExtra1'] = new Array('_b', '_g', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_b', '_g');
versions['estOther3'] = new Array('_g', '_c', '_m');
versions['estOther5'] = new Array('_b', '_g');
versions['estOther6'] = new Array('_g', '_c', '_m');
versions['testIntro1'] = new Array('_b', '_g');
versions['testIntro3'] = new Array('_b', '_g', '_c');
versions['testIntro5'] = new Array('_b', '_g');
versions['testIntro7'] = new Array('_b', '_g', '_c');
versions['testPropn1'] = new Array('_b', '_g', '_c');
versions['testPropn2'] = new Array('_b', '_g', '_c');
versions['testPropn3'] = new Array('_b', '_g', '_c');
versions['testPropn4'] = new Array('_b', '_g', '_c');
versions['testPropn5'] = new Array('_b', '_g');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_b', '_g', '_c');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_b', '_g', '_c');
versions['testPValue5'] = new Array('_b', '_g', '_c');
versions['twoGroupModel1'] = new Array('_b', '_g', '_c');
versions['twoGroupModel2'] = new Array('_b', '_g', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_b', '_g', '_c');
versions['twoGroupInf3'] = new Array('_b', '_g', '_c');
versions['twoGroupInf4'] = new Array('_b', '_g', '_c');
versions['twoGroupInf5'] = new Array('_b', '_g', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_b', '_g', '_c');
versions['testPaired2'] = new Array('_b', '_g', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_b', '_g', '_c');
versions['multiGroup3'] = new Array('_b', '_g', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_b', '_g', '_a', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_b', '_g', '_c');
versions['regnModel1'] = new Array('_b', '_g', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_b', '_g', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_b', '_g', '_c');
versions['regnPred3'] = new Array('_b', '_g', '_c');
versions['regnPred4'] = new Array('_b', '_g');
versions['regnProblem3'] = new Array('_b', '_g');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['prob1'] = new Array('_b', '_g', '_c');
versions['prob2'] = new Array('_b', '_g', '_c');
versions['prob3'] = new Array('_b', '_g');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_b', '_g', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
