
addBook('bk/nceax', 'book_splash', "About CAST for NCEA teachers");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addPart("Pre-NCEA");

addChapter('bk/nceax', 'ch_categories', "Looking at Categories");
addSection('bk/nceax', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'l_freqTable1', "Frequency tables", 'interact');
addPage_2('en/freqTable', 'l_freqTable2', "Proportions and percentages", 'interact');
addPage_2('en/freqTable', 'l_freqTable3', "Changes to the categories", 'interact');
addSection('bk/nceax', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'l_univarCat1', "Bar charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat4', "Stacked bar charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat5', "Pie charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat6', "Comparison of bar and pie charts", 'interact');
addPage_2('en/univarCat', 'l_univarCat7', "Bar charts for quantities", 'interact');
addPage_2('en/univarCat', 'l_univarCat8', "Pie charts for quantities", 'interact');
addPage_2('en/univarCat', 'l_univarCat9', "Chartjunk and misleading diagrams", 'static');

addChapter('bk/nceax', 'ch_numbers', "Looking at Numbers");
addSection('bk/nceax', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'l_valueDisplay1', "The basic dot plot", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay2', "Jittered and stacked dot plots", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay3', "Crosses or digits", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay4', "Basic stem and leaf plot", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay7', "More about stems and leaves", 'interact');
addPage_2('en/valueDisplay', 'l_valueDisplay8', "Drawing a stem and leaf plot", 'interact');
addSection('bk/nceax', 'sec_density', "Histograms and density");
addPage_2('en/density', 'l_density1', "Density of values", 'interact');
addPage_2('en/density', 'l_density2', "Histogram with equal class widths", 'interact');
addPage_2('en/density', 'l_density3', "Choice of classes", 'interact');
addPage_2('en/density', 'l_density4', "Histograms of small data sets", 'interact');
addPage_2('en/density', 'l_density5', "Relative frequency and area", 'interact');
addPage_2('en/density', 'l_density6', "Comparing groups", 'interact');
addSection('bk/nceax', 'sec_boxPlot', "Box plots");
addPage_2('en/boxPlot', 'l_boxPlot1', "The need to summarise", 'static');
addPage_2('en/boxPlot', 'l_boxPlot2', "Basic box plot", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot3', "More about box plot shape", 'interact');
addSection('bk/generalx', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'l_scatterplot1', "More than one variable", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot2', "Scatterplots", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot3', "Limitations of univariate displays", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot4', "Marginal distributions", 'interact');
addPage_2('en/scatterplot', 'l_scatterplot5', "Time series", 'interact');

addChapter('bk/nceax', 'ch_centreSpread', "Centre and Spread");
addSection('bk/nceax', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'l_centerSpread1', "Ideas of centre and spread", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread2', "Simple measures of centre and spread", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread3', "Sample mean", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread4', "Properties of median and mean", 'interact');

addPart("NCEA Level 1");

addChapter('bk/nceax', 'ch_level_1.10', "Explore Data (1.10)");
addSection('bk/nceax', 'sec_variables', "Variables and individuals");
addPage_2('en/structures', 'l_structures1', "Data structures", 'static');
addPage_2('en/structures', 'l_structures2', "Variables and individuals", 'interact');
addPage_2('en/structures', 'l_structures3', "Types of variable", 'interact');
addSection('bk/generalx', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'l_displayInterp1', "Outliers", 'static');
addPage_2('en/displayInterp', 'l_displayInterp2', "Clusters", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp3', "Names of individuals", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp4', "Distinguishing known groups", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp5', "Back-to-back stem and leaf plots", 'interact');
addPage_2('en/displayInterp', 'l_displayInterp6', "Danger of overinterpretation", 'interact');
addSection('bk/nceax', 'sec_boxPlotMore', "More about box plots");
addPage_2('en/boxPlot', 'l_boxPlot4', "Displaying outliers", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot5', "Clusters", 'interact');
addPage_2('en/boxPlot', 'l_boxPlot6', "Comparison of groups", 'interact');
addSection('bk/generalx', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'l_popSamp1', "Sampling from a population", 'interact');
addPage_2('en/popSamp', 'l_popSamp2', "Variability in a sample", 'interact');
addPage_2('en/popSamp', 'l_popSamp3', "Sampling error", 'interact');
addPage_2('en/popSamp', 'l_popSamp4', "Sampling error and sample size", 'interact');
addPage_2('en/popSamp', 'l_popSamp5', "Sampling with and without replacement", 'interact');
addPage_2('en/popSamp', 'l_popSamp6', "Generating random numbers", 'interact');
addPage_2('en/popSamp', 'l_popSamp7', "Selecting a random sample", 'interact');

addChapter('bk/nceax', 'ch_level_1.11', "Explore Bivariate Data (1.11)");
addSection('bk/generalx', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'l_relationship1', "Strength of a relationship", 'interact');
addPage_2('en/relationship', 'l_relationship2', "Outliers", 'interact');
addPage_2('en/relationship', 'l_relationship3', "Clusters", 'interact');
addPage_2('en/relationship', 'l_relationship4', "Dangers of over-interpretation", 'interact');

addChapter('bk/nceax', 'ch_level_1.12', "Chance and Data (1.12)");
addSection('bk/nceax', 'sec_probability', "Probability");
addPage_2('en/probDensity', 'l_probDensity1', "Finite populations", 'interact');
addPage_2('en/probDensity', 'l_probDensity2', "Probabilities and population proportions", 'interact');
addPage_2('en/probDensity', 'l_probDensity3', "Law of large numbers", 'interact');
addPage_2('en/probDensity', 'l_probDensity4', "Bar charts of discrete probabilities &mdash; discrete", 'interact');
addPage_2('en/density', 'l_density5', "Relative frequency and area", 'interact');
addSection('bk/nceax', 'sec_probTable', "Probabilities from tables");
addPage_2('en/prob', 'l_prob1', "Joint probabilities", 'interact');
addPage_2('en/prob', 'l_prob2', "Marginal probabilities", 'interact');
addPage_2('en/prob', 'l_prob3', "Conditional probabilities", 'interact');
addPage_2('en/prob', 'l_prob4', "Graphical display of probabilities", 'interact');
addSection('bk/nceax', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'l_timePlot1', "Time series plots", 'interact');
addPage_2('en/timePlot', 'l_timePlot2', "Time series: trend", 'interact');
addPage_2('en/timePlot', 'l_timePlot3', "Time series: seasonal pattern", 'interact');
addPage_2('en/timePlot', 'l_timePlot5', "Time series: random fluctuations", 'interact');
addPage_2('en/timePlot', 'l_timePlot6', "Multiple time series", 'interact');

addChapter('bk/nceax', 'ch_level_1.13', "Situation With Chance (1.13)");

addPart("NCEA Level 2");

addChapter('bk/nceax', 'ch_level_2.08', "Design Questionnaire (2.8)");
addSection('bk/nceax', 'sec_sampPractice', "Other sampling schemes");

addChapter('bk/nceax', 'ch_level_2.09', "Make an Inference (2.9)");
addSection('bk/nceax', 'sec_variation', "Variation");
addPage_2('en/variation', 'l_variation1', "Signal and noise", 'interact');
addPage_2('en/variation', 'l_variation2', "Natural variability", 'interact');
addPage_2('en/variation', 'l_variation3', "Signal and noise in experiments", 'interact');
addPage_2('en/variation', 'l_variation4', "Variability in survey data", 'interact');
addSection('bk/nceax', 'sec_infPopn', "Sampling from a distribution");
addPage_2('en/infPopn', 'l_infPopn1', "Data as representatives", 'static');
addPage_2('en/infPopn', 'l_infPopn2', "Randomness of data", 'interact');
addPage_2('en/infPopn', 'l_infPopn4', "Information from a single sample", 'interact');
addSection('bk/nceax', 'sec_stdDevn', "Standard deviation");
addPage_2('en/centerSpread', 'l_centerSpread5', "Standard deviation", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread6', "Rules of thumb for standard deviation", 'static');
addPage_2('en/centerSpread', 'l_centerSpread7', "Understanding means and st devns", 'interact');
addPage_2('en/centerSpread', 'l_centerSpread8', "Warnings about mean and standard devn", 'static');
addSection('bk/generalx', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'l_estIntro1', "Interest in populations", 'static');
addPage_2('en/estIntro', 'l_estIntro2', "Interest in parameters", 'static');
addPage_2('en/estIntro', 'l_estIntro3', "Estimation error", 'interact');

addChapter('bk/nceax', 'ch_level_2.10', "Conduct Experiment (2.10)");
addSection('bk/generalx', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'l_causal1', "Causal and non-causal relationships", 'static');
addPage_2('en/causal', 'l_causal2', "Observational and experimental data", 'interact');
addPage_2('en/causal', 'l_causal3', "Data collection and causality", 'interact');

addChapter('bk/nceax', 'ch_level_2.11', "Evaluate a Report (2.11)");

addChapter('bk/nceax', 'ch_level_2.12', "Use Probability (2.12)");
addSection('bk/nceax', 'sec_densityMore', "More about histograms");
addPage_2('en/density', 'l_density5', "Relative frequency and area", 'interact');
addPage_2('en/density', 'l_density7', "Histograms with varying class widths", 'interact');
addPage_2('en/density', 'l_density8', "Mixed class widths (cont)", 'interact');
addSection('bk/nceax', 'sec_continTable', "Contingency tables");
addPage_2('en/groupedCat', 'l_groupedCat1', "Contingency tables", 'interact');
addPage_2('en/groupedCat', 'l_groupedCat2', "Contingency table examples", 'static');
addPage_2('en/groupedCat', 'l_groupedCat3', "Proportions within groups", 'interact');
addPage_2('en/structures', 'l_structures4', "Categorical variables and groups", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat4', "Marginal distributions", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat5', "Conditional distributions", 'interact');
addPage_2('en/bivarCat', 'l_bivarCat7', "Conditional vs marginal distns", 'interact');
addSection('bk/nceax', 'sec_probDensity', "Probability density functions");
addPage_2('bk/nceax', 'l_densityCopy5', "Relative frequency and area", 'interact');
addPage_2('en/probDensity', 'l_probDensity5', "Probability density functions", 'interact');
addPage_2('en/probDensity', 'l_probDensity6', "Normal distributions", 'interact');
addPage_2('en/probDensity', 'l_probDensity8', "Probability and area under the pdf", 'interact');
addSection('bk/nceax', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'l_normalDistn1', "Importance of normal distributions", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn2', "Shape of normal distributions", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn3', "Sketching a normal distribution", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn4', "Some normal probabilities", 'interact');
addSection('bk/nceax', 'sec_normalProb', "Normal probabilities");
addPage_2('en/correlation', 'l_correlation2', "Units-free variables (z-scores)", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn5', "Z-scores", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn6', "Probabilities from z-scores", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn7', "Finding other normal probabilities", 'interact');
addPage_2('en/normalDistn', 'l_normalDistn8', "Finding normal quantiles", 'interact');

addChapter('bk/nceax', 'ch_level_2.13', "Use Simulation (2.13)");
addSection('bk/nceax', 'sec_probSim', "Simulation");
addPage_2('en/probSim', 'l_probSim1', "Probability models and simulation", 'interact');
addPage_2('en/probSim', 'l_probSim2', "Simulation: Will the best team win?", 'interact');
addPage_2('en/probSim', 'l_probSim3', "Simulation: Will the best team win?", 'interact');
addPage_2('en/probSim', 'l_probSim4', "Assessing unusual features in data", 'interact');
addPage_2('en/probSim', 'l_probSim5', "Random numbers", 'interact');
addPage_2('en/probSim', 'l_probSim6', "Generating categorical values", 'interact');

addPart("NCEA Level 3");

addChapter('bk/nceax', 'ch_level_3.08', "Time Series (3.8)");
addSection('bk/nceax', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'l_smoothing1', "Moving averages", 'interact');
addSection('bk/nceax', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'l_trend1', "Linear trend", 'interact');
addPage_2('en/trend', 'l_trend2', "Quadratic trend", 'interact');
addPage_2('en/trend', 'l_trend3', "Forecasting", 'interact');
addSection('bk/nceax', 'sec_seasonal', "Seasonal data");
addPage_2('en/seasonal', 'l_seasonal1', "Seasonal patterns", 'interact');
addPage_2('en/seasonal', 'l_seasonal2', "Smoothing out seasonal variation", 'interact');
addPage_2('en/seasonal', 'l_seasonal3', "Estimating the seasonal effect", 'interact');
addPage_2('en/seasonal', 'l_seasonal4', "Deseasonalised data", 'interact');
addPage_2('bk/nceax', 'l_seasonal5', "Putting it all together", 'interact');
addPage_2('bk/nceax', 'l_seasonal6', "Forecasting with seasonal data", 'interact');

addChapter('bk/nceax', 'ch_level_3.09', "Bivariate Data (3.9)");
addSection('bk/nceax', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'l_correlation4', "Scatterplots and the value of r", 'interact');
addPage_2('en/correlation', 'l_correlation5', "Nonlinear relationships", 'interact');
addPage_2('en/correlation', 'l_correlation6', "R does not tell the whole story", 'interact');
addSection('bk/generalx', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'l_leastSqrs1', "Predicting Y from X", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs2', "Slope and intercept of straight line", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs3', "Predicting Y from linear model", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs4', "Fitted values and residuals", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs5', "Target of small residuals", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs6', "Least squares", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs7', "Outliers", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs8', "Residual plots", 'interact');
addPage_2('en/leastSqrs', 'l_leastSqrs9', "Predicting Y and predicting X", 'interact');
addSection('bk/nceax', 'sec_rSquared', "Coefficient of determination");
addPage_2('bk/nceax', 'l_rSquared1', "Sums of squares", 'static');
addPage_2('bk/nceax', 'l_rSquared2', "Coefficient of determination", 'interact');
addPage_2('bk/nceax', 'l_rSquared3', "Examples", 'static');
addSection('bk/generalx', 'sec_curvature', "Nonlinear relationships");
addPage_2('en/curvature', 'l_curvature1', "Transformations and correlation", 'interact');
addPage_2('en/curvature', 'l_curvature2', "Transformations and models", 'interact');
addPage_2('en/curvature', 'l_curvature3', "Quadratic models", 'interact');
addPage_2('en/curvature', 'l_curvature4', "Quadratic models (cont)", 'interact');
addPage_2('en/curvature', 'l_curvature5', "Dangers of extrapolation", 'interact');

addChapter('bk/nceax', 'ch_level_3.10', "Formal Inference (3.10)");
addSection('bk/nceax', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'l_randomMean1', "Parameters and statistics", 'interact');
addPage_2('en/randomMean', 'l_randomMean2', "Distribution of sample mean", 'interact');
addPage_2('en/randomMean', 'l_randomMean3', "Means from normal populations", 'interact');
addPage_2('en/randomMean', 'l_randomMean4', "Large-sample normality of means", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff1', "Means and sums of random samples", 'interact');
addSection('bk/nceax', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'l_seMean1', "Error distribution for mean", 'interact');
addPage_2('en/seMean', 'l_seMean2', "Standard error when population SD is known", 'interact');
addPage_2('en/seMean', 'l_seMean4', "Standard error vs standard deviation", 'interact');
addSection('bk/nceax', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'l_ciMean1', "Confidence interval for a mean, known SD", 'interact');
addPage_2('en/ciMean', 'l_ciMean2', "Confidence level", 'interact');
addSection('bk/generalx', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'l_estPropn1', "Estimating a proportion", 'interact');
addPage_2('en/estPropn', 'l_estPropn2', "Error distribution", 'interact');
addPage_2('en/estPropn', 'l_estPropn3', "Normal approximation to error distribution", 'interact');
addPage_2('en/estPropn', 'l_estPropn4', "Standard error examples", 'static');
addPage_2('en/estPropn', 'l_estPropn5', "Confidence interval for proportion", 'static');
addPage_2('en/estPropn', 'l_estPropn6', "Properties of 95% CI for proportion", 'interact');
addPage_2('en/estPropn', 'l_estPropn7', "Confidence interval examples", 'static');
addSection('bk/generalx', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'l_ciExtra1', "Maximum standard error for proportion", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra2', "Margin of error", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra3', "Sample size for estimating mean", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra4', "Sample size for estimating proportion", 'interact');
addPage_2('en/ciExtra', 'l_ciExtra5', "Other confidence levels", 'interact');
addSection('bk/nceax', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'l_twoGroupInf1', "Distn of difference between means", 'interact');
addPage_2('en/twoGroupInf', 'l_twoGroupInf2', "Distribution of estimation error", 'static');

addChapter('bk/nceax', 'ch_level_3.11', "Conduct Experiment (3.11)");
addSection('bk/generalx', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'l_designIntro1', "Variable experimental units", 'interact');
addPage_2('en/designIntro', 'l_designIntro2', "A badly designed experiment", 'interact');
addPage_2('en/designIntro', 'l_designIntro3', "Randomisation", 'interact');
addPage_2('en/designIntro', 'l_designIntro4', "Mechanics of randomisation", 'interact');
addPage_2('en/designIntro', 'l_designIntro5', "Replication", 'static');
addPage_2('en/designIntro', 'l_designIntro6', "Blocking", 'interact');
addPage_2('en/designIntro', 'l_designIntro7', "Benifits of blocking", 'interact');

addChapter('bk/nceax', 'ch_level_3.12', "Evaluate Reports (3.12)");

addChapter('bk/nceax', 'ch_level_3.13', "Use Probability (3.13)");

addChapter('bk/nceax', 'ch_level_3.14', "Use Distributions (3.14)");
addSection('bk/generalx', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'l_randomPropn1', "Distributions of counts and proportions", 'interact');
addPage_2('en/randomPropn', 'l_randomPropn2', "Family of binomial distributions", 'interact');
addPage_2('en/randomPropn', 'l_randomPropn3', "Binomial probability examples", 'static');
addPage_2('en/randomPropn', 'l_randomPropn4', "Normal approximation to binomial", 'interact');
addPage_2('en/randomPropn', 'l_randomPropn5', "Normal approximation examples", 'static');
addSection('bk/generalx', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'l_sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff2', "Sums and differences", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('en/sumDiff', 'l_sumDiff4', "Probabilities for sums and differences", 'static');

var language = "en";
var logoGif = "logo_massey.gif";
var homeDir = "bk/nceax";
var versionGif = "images/castNcea";
var isLecturingVersion = true;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "21";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_c': 'Business', '_a': 'African', '_b': 'Biometric', '_z': 'Other', '_m': 'Climatic', '++': 'Custom'};
var versions = {};
versions['l_freqTable1'] = new Array('_g', '_c');
versions['l_freqTable2'] = new Array('_g', '_a', '_b');
versions['l_univarCat1'] = new Array('_g', '_a', '_b');
versions['l_univarCat4'] = new Array('_g', '_b', '_c');
versions['l_univarCat5'] = new Array('_g', '_b', '_c');
versions['l_univarCat6'] = new Array('_g', '_b', '_c');
versions['l_univarCat8'] = new Array('_g', '_b');
versions['l_univarCat9'] = new Array('_g', '_b', '_c');
versions['l_valueDisplay1'] = new Array('_g', '_b', '_c');
versions['l_valueDisplay2'] = new Array('_g', '_b', '_c');
versions['l_valueDisplay4'] = new Array('_g', '_b', '_c');
versions['l_valueDisplay8'] = new Array('_g', '_c');
versions['l_density3'] = new Array('_g', '_c');
versions['l_density4'] = new Array('_g', '_b', '_c');
versions['l_density6'] = new Array('_g', '_b', '_c');
versions['l_scatterplot2'] = new Array('_g', '_c');
versions['l_scatterplot4'] = new Array('_g', '_c');
versions['l_scatterplot5'] = new Array('_g', '_c');
versions['l_centerSpread1'] = new Array('_g', '_b');
versions['l_centerSpread2'] = new Array('_g', '_b');
versions['l_centerSpread3'] = new Array('_g', '_b', '_c');
versions['l_structures1'] = new Array('_g', '_a', '_b', '_c');
versions['l_structures2'] = new Array('_g', '_a', '_c');
versions['l_structures3'] = new Array('_g', '_a', '_b', '_c');
versions['l_displayInterp3'] = new Array('_g', '_b');
versions['l_popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['l_popSamp2'] = new Array('_g', '_c');
versions['l_popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['l_popSamp4'] = new Array('_g', '_b');
versions['l_popSamp5'] = new Array('_g', '_b', '_c');
versions['l_relationship1'] = new Array('_g', '_c');
versions['l_relationship2'] = new Array('_g', '_c');
versions['l_relationship4'] = new Array('_g', '_c');
versions['l_probDensity2'] = new Array('_g', '_b', '_c');
versions['l_probDensity3'] = new Array('_g', '_b', '_c');
versions['l_prob1'] = new Array('_g', '_c');
versions['l_prob2'] = new Array('_g', '_b', '_c');
versions['l_prob3'] = new Array('_g', '_b', '_c');
versions['l_prob4'] = new Array('_g', '_b');
versions['l_timePlot1'] = new Array('_g', '_b', '_c');
versions['l_timePlot2'] = new Array('_g', '_c');
versions['l_timePlot3'] = new Array('_g', '_b');
versions['l_timePlot5'] = new Array('_g', '_b');
versions['l_infPopn1'] = new Array('_g', '_b', '_c');
versions['l_infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['l_infPopn4'] = new Array('_g', '_c');
versions['l_centerSpread7'] = new Array('_g', '_c');
versions['l_estIntro1'] = new Array('_g', '_b', '_c');
versions['l_estIntro2'] = new Array('_g', '_b', '_c');
versions['l_estIntro3'] = new Array('_g', '_b', '_c');
versions['l_causal2'] = new Array('_g', '_b', '_c');
versions['l_density7'] = new Array('_g', '_b', '_c');
versions['l_groupedCat1'] = new Array('_g', '_c');
versions['l_groupedCat2'] = new Array('_g', '_b', '_c');
versions['l_groupedCat3'] = new Array('_g', '_c');
versions['l_structures4'] = new Array('_g', '_c');
versions['l_normalDistn1'] = new Array('_g', '_c');
versions['l_normalDistn7'] = new Array('_g', '_b', '_c');
versions['l_probSim4'] = new Array('_g', '_b', '_c');
versions['l_probSim6'] = new Array('_g', '_c');
versions['l_seasonal1'] = new Array('_g', '_m', '_z');
versions['l_seasonal2'] = new Array('_g', '_m', '_z');
versions['l_seasonal3'] = new Array('_g', '_m', '_z');
versions['l_seasonal4'] = new Array('_g', '_m', '_z');
versions['l_seasonal5'] = new Array('+g', '_g', '_m', '_z');
versions['l_seasonal6'] = new Array('+g', '_g', '_m', '_z');
versions['l_leastSqrs1'] = new Array('_g', '_b', '_c');
versions['l_leastSqrs4'] = new Array('_g', '_c');
versions['l_leastSqrs8'] = new Array('_g', '_c');
versions['l_leastSqrs9'] = new Array('_g', '_c');
versions['l_curvature1'] = new Array('_g', '_c');
versions['l_curvature2'] = new Array('_g', '_c');
versions['l_curvature4'] = new Array('_g', '_c');
versions['l_curvature5'] = new Array('_g', '_c');
versions['l_randomMean1'] = new Array('_g', '_b', '_c');
versions['l_seMean1'] = new Array('_g', '_b', '_c');
versions['l_seMean2'] = new Array('_g', '_b');
versions['l_ciMean1'] = new Array('_g', '_b');
versions['l_estPropn2'] = new Array('_g', '_b', '_c');
versions['l_estPropn4'] = new Array('_g', '_b', '_c');
versions['l_estPropn5'] = new Array('_g', '_b', '_c');
versions['l_estPropn7'] = new Array('_g', '_b', '_c');
versions['l_ciExtra3'] = new Array('_g', '_c');
versions['l_ciExtra4'] = new Array('_g', '_b');
versions['l_twoGroupInf1'] = new Array('_g', '_c');
versions['l_twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['l_designIntro1'] = new Array('_g', '_c');
versions['l_designIntro2'] = new Array('_g', '_c');
versions['l_designIntro3'] = new Array('_g', '_c');
versions['l_designIntro4'] = new Array('_g', '_b', '_c');
versions['l_designIntro7'] = new Array('_g', '_c');
versions['l_randomPropn1'] = new Array('_g', '_c');
versions['l_randomPropn3'] = new Array('_g', '_b', '_c');
versions['l_randomPropn5'] = new Array('_g', '_b', '_c');

bookLoaded = true;
