
addBook('bk/anu', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/general', 'ch_intro', "Introduction: About Data", null, 'v_ch_intro');
addSection('bk/biometric', 'sec_context', "Context");
addPage_2('en/context', 'context_b1', "Importance of context", 'static', 'en/context', 's_context1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2');
addPage_2('en/context', 'context_b3', "The statistical process", 'static', 'en/context', 's_context3');
addSection('bk/biometric', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures_b1', "Variables and individuals", 'interact', 'en/structures', 's_structures_b1');
addPage_2('en/structures', 'structures_b2', "Types of variable", 'interact', 'en/structures', 's_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3');
addPage_2('en/structures', 'structures4', "Meaningful variables", 'interact', 'en/structures', 's_structures4');
addPage_2('en/structures', 'structures_b5', "Time-ordered data", 'static', 'en/structures', 's_structures5');
addPage_2('en/structures', 'structures_b6', "Multi-level data", 'interact', 'en/structures', 's_structures6');
addPage_2('en/structures', 'structures7', "Structure of the e-book", 'static', 'en/structures', 's_structures7');
addSection('bk/biometric', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4');
addPage_2('en/variation', 'variation5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5');
addPage_2('en/variation', 'variation6', "Predicting future variation", 'static', 'en/variation', 's_variation6');

addChapter('bk/general', 'ch_univar', "One Numerical Variable", null, 'v_ch_univar');
addSection('bk/biometric', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'valueDisplay_b1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1');
addPage_2('en/valueDisplay', 'valueDisplay_b2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2');
addPage_2('en/valueDisplay', 'valueDisplay_b3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay_b4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4');
addPage_2('en/valueDisplay', 'valueDisplay_b5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5');
addPage_2('en/valueDisplay', 'valueDisplay6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6');
addPage_2('en/valueDisplay', 'valueDisplay7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7');
addSection('bk/biometric', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp_b1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1');
addPage_2('en/displayInterp', 'displayInterp_b2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2');
addPage_2('en/displayInterp', 'displayInterp3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3');
addPage_2('en/displayInterp', 'displayInterp_b4', "Extra information about individuals", 'interact', 'en/displayInterp', 's_displayInterp4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp_b6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6');
addSection('bk/biometric', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2');
addPage_2('en/density', 'density3', "Choice of classes", 'interact', 'en/density', 's_density3');
addPage_2('en/density', 'density_b4', "Histograms of small data sets", 'interact', 'en/density', 's_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5');
addPage_2('en/density', 'density_b6', "Comparing groups", 'interact', 'en/density', 's_density6');
addPage_2('en/density', 'density_b7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9');
addPage_2('en/density', 'density10', "Kernel density estimates", 'interact', 'en/density', 's_density10');
addPage_2('en/density', 'density_b11', "Drawing histograms by hand", 'interact', 'en/density', 's_density11');
addSection('bk/biometric', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6');
addPage_2('en/boxPlot', 'boxPlot_b7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7');
addSection('bk/biometric', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread_b1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread_b2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread_b3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8');
addSection('bk/general', 'sec_percentile', "Proportions and percentiles");
addPage_2('en/percentile', 'percentile1', "Illustrative data set", 'interact', 'en/percentile', 's_percentile1');
addPage_2('en/percentile', 'percentile2', "Cumulative proportions", 'interact', 'en/percentile', 's_percentile2');
addPage_2('en/percentile', 'percentile3', "Graph of cumulative proportions", 'interact', 'en/percentile', 's_percentile3');
addPage_2('en/percentile', 'percentile4', "Percentiles", 'interact', 'en/percentile', 's_percentile4');
addPage_2('en/percentile', 'percentile5', "Displaying percentiles", 'interact', 'en/percentile', 's_percentile5');
addPage_2('en/percentile', 'percentile6', "Comparing groups", 'interact', 'en/percentile', 's_percentile6');
addPage_2('en/percentile', 'percentile7', "Comparing groups with other percentiles", 'interact', 'en/percentile', 's_percentile7');
addPage_2('en/percentile', 'percentile8', "Better definition of percentiles", 'interact', 'en/percentile', 's_percentile8');
addSection('bk/biometric', 'sec_transform', "Transformations");
addPage_2('en/transform', 'transform_b1', "Linear transformations", 'interact', 'en/transform', 's_transform1');
addPage_2('en/transform', 'transform_b2', "Log transformations", 'interact', 'en/transform', 's_transform2');
addPage_2('en/transform', 'transform3', "When to use log transform?", 'interact', 'en/transform', 's_transform3');
addPage_2('en/transform', 'transform4', "Power transformations", 'interact', 'en/transform', 's_transform4');
addPage_2('en/transform', 'transform5', "Power transforms &amp; skewness", 'interact', 'en/transform', 's_transform5');

addChapter('bk/general', 'ch_cat', "Categorical Variables", null, 'v_ch_cat');
addSection('bk/biometric', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1');
addPage_2('en/freqTable', 'freqTable_b2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable_b2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4');
addSection('bk/biometric', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat_b1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2');
addPage_2('en/univarCat', 'univarCat_b3', "Chartjunk and misleading bar charts", 'static', 'en/univarCat', 's_univarCat_b3');
addPage_2('en/univarCat', 'univarCat_b4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4');
addPage_2('en/univarCat', 'univarCat_b5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5');
addPage_2('en/univarCat', 'univarCat_b6', "Chartjunk for pie charts", 'static', 'en/univarCat', 's_univarCat_b6');
addPage_2('en/univarCat', 'univarCat_b7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7');
addSection('bk/biometric', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat_b2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat_b2');
addPage_2('en/groupedCat', 'groupedCat_b3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat3');
addPage_2('en/groupedCat', 'groupedCat_b4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4');
addPage_2('en/groupedCat', 'groupedCat_b5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5');

addChapter('bk/general', 'ch_sample', "Sampling and Variability", null, 'v_ch_sample');
addSection('bk/biometric', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp_b1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2');
addPage_2('en/popSamp', 'popSamp_b3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3');
addPage_2('en/popSamp', 'popSamp_b4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4');
addPage_2('en/popSamp', 'popSamp_b5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6');
addSection('bk/biometric', 'sec_infPopn', "Samples from distributions");
addPage_2('en/infPopn', 'infPopn_b1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn_b1');
addPage_2('en/infPopn', 'infPopn_b2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2');
addPage_2('en/infPopn', 'infPopn_b3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3');
addPage_2('en/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact', 'en/infPopn', 's_infPopn4');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5');
addSection('bk/biometric', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity_b1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1');
addPage_2('en/probDensity', 'probDensity_b2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4');
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6');
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7');
addSection('bk/biometric', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean_b1', "Variability of sample statistics", 'interact', 'en/randomMean', 's_randomMean1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5');
addPage_2('en/randomMean', 'randomMean_b6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean_b6');
addPage_2('en/randomMean', 'randomMean_b7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite populations", 'interact', 'en/randomMean', 's_randomMean8');
addSection('bk/biometric', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn_b3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn_b6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn_b7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10');
addSection('bk/biometric', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn_b3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3');
addPage_2('en/randomPropn', 'randomPropn_b4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn_b4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn_b6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn_b6');

addChapter('bk/general', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/biometric', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro_b1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro_b1');
addPage_2('en/estIntro', 'estIntro_b2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4');
addPage_2('en/estIntro', 'estIntro_b5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7');
addSection('bk/biometric', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean_b1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1');
addPage_2('en/seMean', 'seMean_b2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2');
addPage_2('en/seMean', 'seMean_b3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3');
addPage_2('en/seMean', 'seMean_b4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean_b4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5');
addPage_2('en/seMean', 'seMean_b6', "Using SEs to compare estimators", 'interact', 'en/seMean', 's_seMean6');
addPage_2('en/seMean', 'seMean7', "More about bias", 'interact', 'en/seMean', 's_seMean7');
addSection('bk/biometric', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1');
addPage_2('en/ciMean', 'ciMean_b2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6');
addPage_2('en/ciMean', 'ciMean_b7', "Examples", 'static', 'en/ciMean', 's_ciMean_b7');
addSection('bk/biometric', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2');
addPage_2('en/estPropn', 'estPropn_b3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3');
addPage_2('en/estPropn', 'estPropn_b4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4');
addPage_2('en/estPropn', 'estPropn_b5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6');
addPage_2('en/estPropn', 'estPropn_b7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7');

addChapter('bk/general', 'ch_testing', "Testing Hypotheses", null, 'v_ch_testing');
addSection('bk/biometric', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro_b1', "Inference", 'static', 'en/testIntro', 's_testIntro1');
addPage_2('en/testIntro', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2');
addPage_2('en/testIntro', 'testIntro_b3', "Simulation to test a proportion", 'interact', 'en/testIntro', 's_testIntro3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4');
addPage_2('en/testIntro', 'testIntro_b5', "Randomisation tests", 'interact', 'en/testIntro', 's_testIntro5');
addPage_2('en/testIntro', 'testIntro6', "Randomisation test for correlation", 'interact', 'en/testIntro', 's_testIntro6');
addPage_2('en/testIntro', 'testIntro_b7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7');
addSection('bk/biometric', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'testPropn_b1', "Inference about parameters", 'static', 'en/testPropn', 's_testPropn1');
addPage_2('en/testPropn', 'testPropn_b2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2');
addPage_2('en/testPropn', 'testPropn_b3', "Another example", 'interact', 'en/testPropn', 's_testPropn_b3');
addPage_2('en/testPropn', 'testPropn_b4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn4');
addPage_2('en/testPropn', 'testPropn_b5', "Normal approximation", 'interact', 'en/testPropn', 's_testPropn_b5');
addPage_2('en/testPropn', 'testPropn6', "Statistical distance", 'static', 'en/testPropn', 's_testPropn6');
addPage_2('en/testPropn', 'testPropn_b7', "Tests based on statistical distance", 'interact', 'en/testPropn', 's_testPropn_b7');
addSection('bk/biometric', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean1', "Introduction", 'static', 'en/testMean', 's_testMean1');
addPage_2('en/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2');
addPage_2('en/testMean', 'testMean_b3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3');
addPage_2('en/testMean', 'testMean4', "The t distribution", 'interact', 'en/testMean', 's_testMean4');
addPage_2('en/testMean', 'testMean5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5');
addSection('bk/general', 'sec_decision', "Decisions and significance");
addPage_2('en/decision', 'decision1', "Hypothesis tests and decisions", 'static', 'en/decision', 's_decision1');
addPage_2('en/decision', 'decision2', "Decision rules", 'interact', 'en/decision', 's_decision2');
addPage_2('en/decision', 'decision3', "Significance level and p-values", 'interact', 'en/decision', 's_decision3');
addPage_2('en/decision', 'decision4', "Sample size and power", 'interact', 'en/decision', 's_decision4');

addChapter('bk/general', 'ch_twoGroups', "Comparing Groups", null, 'v_ch_twoGroups');
addSection('bk/biometric', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel_b1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel1');
addPage_2('en/twoGroupModel', 'twoGroupModel_b2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4');
addPage_2('en/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel5');
addSection('bk/general', 'sec_sumDiff', "Distn of sums and differences");
addPage_2('en/sumDiff', 'sumDiff1', "Means and sums of samples", 'interact', 'en/sumDiff', 's_sumDiff1');
addPage_2('en/sumDiff', 'sumDiff2', "Sum and difference", 'interact', 'en/sumDiff', 's_sumDiff2');
addPage_2('en/sumDiff', 'sumDiff3', "Sum and difference (cont)", 'interact', 'en/sumDiff', 's_sumDiff3');
addPage_2('en/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static', 'en/sumDiff', 's_sumDiff4');
addSection('bk/biometric', 'sec_twoGroupInf', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1');
addPage_2('en/twoGroupInf', 'twoGroupInf_b2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf2');
addPage_2('en/twoGroupInf', 'twoGroupInf_b3', "CI for difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf3');
addPage_2('en/twoGroupInf', 'twoGroupInf_b4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf4');
addPage_2('en/twoGroupInf', 'twoGroupInf_b5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf5');
addSection('bk/general', 'sec_twoGroupPropn', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn1');
addPage_2('en/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn2');
addPage_2('en/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static', 'en/twoGroupPropn', 's_twoGroupPropn3');
addPage_2('en/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static', 'en/twoGroupPropn', 's_twoGroupPropn4');
addSection('bk/biometric', 'sec_testPaired', "Paired t test");
addPage_2('en/testPaired', 'testPaired_b1', "Paired data", 'static', 'en/testPaired', 's_testPaired1');
addPage_2('en/testPaired', 'testPaired_b2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2');
addPage_2('en/testPaired', 'testPaired3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4');

addChapter('bk/biometric', 'ch_bivar', "Two Numerical Variables");
addSection('bk/biometric', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot_b1', "Bivariate data sets", 'interact', 'en/scatterplot', 's_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5');
addSection('bk/biometric', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation_b1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation_b1');
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4');
addPage_2('en/correlation', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6');
addSection('bk/biometric', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs_b1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y and predicting X", 'interact', 'en/leastSqrs', 's_leastSqrs7');
addSection('bk/general', 'sec_curvature', "Nonlinear relationships");
addPage_2('en/curvature', 'curvature1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1');
addPage_2('en/curvature', 'curvature2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2');
addPage_2('en/curvature', 'curvature3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3');
addPage_2('en/curvature', 'curvature4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4');

addChapter('bk/general', 'ch_regnInference', "Regression Inference", null, 'v_ch_regnInference');
addSection('bk/biometric', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel_b1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel1');
addPage_2('en/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact', 'en/regnModel', 's_regnModel2');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4');
addPage_2('en/regnModel', 'regnModel_b5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel5');
addSection('bk/general', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1');
addPage_2('en/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2');
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3');
addPage_2('en/regnEst', 'regnEst4', "Standard error of least squares slope", 'static', 'en/regnEst', 's_regnEst4');
addPage_2('en/regnEst', 'regnEst5', "95% confidence interval for slope", 'static', 'en/regnEst', 's_regnEst5');
addPage_2('en/regnEst', 'regnEst6', "Properties of confidence interval", 'interact', 'en/regnEst', 's_regnEst6');
addPage_2('en/regnEst', 'regnEst7', "Influences on accuracy", 'interact', 'en/regnEst', 's_regnEst7');
addSection('bk/general', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1');
addPage_2('en/regnTest', 'regnTest2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest2');
addPage_2('en/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3');
addPage_2('en/regnTest', 'regnTest4', "Properties of p-values", 'interact', 'en/regnTest', 's_regnTest4');
addSection('bk/biometric', 'sec_regnProblem', "Linear model assumptions");
addPage_2('en/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact', 'en/regnProblem', 's_regnProblem1');
addPage_2('en/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact', 'en/regnProblem', 's_regnProblem2');
addPage_2('en/regnProblem', 'regnProblem_b3', "Curvature and non-constant variance", 'interact', 'en/regnProblem', 's_regnProblem3');
addPage_2('en/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact', 'en/regnProblem', 's_regnProblem4');
addPage_2('en/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact', 'en/regnProblem', 's_regnProblem5');
addPage_2('en/regnProblem', 'regnProblem6', "Non-normal errors", 'interact', 'en/regnProblem', 's_regnProblem6');
addPage_2('en/regnProblem', 'regnProblem7', "Correlated errors", 'interact', 'en/regnProblem', 's_regnProblem7');

var language = "en";
var logoGif = "anu_logo.gif";
var homeDir = "bk/anu";
var versionGif = "../biometric/images/castBiometric";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "10";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_b': 'Biometric', '_g': 'General', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_b', '_g', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_b', '_g');
versions['structures1'] = new Array('_b', '_g', '_a', '_c');
versions['structures2'] = new Array('_b', '_g', '_a', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_b', '_g', '_c');
versions['structures6'] = new Array('_b', '_g');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_g', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay2'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay3'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay4'] = new Array('_b', '_g', '_c', '_m');
versions['valueDisplay5'] = new Array('_b', '_g', '_a', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_b', '_g', '_c');
versions['displayInterp2'] = new Array('_b', '_g', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_b', '_g');
versions['displayInterp6'] = new Array('_b', '_g', '_c');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_b', '_g', '_c', '_m');
versions['density6'] = new Array('_b', '_g', '_c');
versions['density7'] = new Array('_b', '_g', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_b', '_g', '_c', '_m');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_b', '_g');
versions['centerSpread1'] = new Array('_b', '_g');
versions['centerSpread2'] = new Array('_b', '_g');
versions['centerSpread3'] = new Array('_b', '_g', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_b', '_g');
versions['transform2'] = new Array('_b', '_g', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_b', '_g', '_a');
versions['univarCat1'] = new Array('_b', '_g', '_a');
versions['univarCat3'] = new Array('_b', '_g', '_a');
versions['univarCat4'] = new Array('_b', '_g', '_c');
versions['univarCat5'] = new Array('_b', '_g', '_c');
versions['univarCat6'] = new Array('_b', '_g', '_c');
versions['univarCat7'] = new Array('_b', '_g');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_b', '_g', '_c');
versions['groupedCat3'] = new Array('_b', '_g', '_c');
versions['groupedCat4'] = new Array('_b', '_g', '_c');
versions['groupedCat5'] = new Array('_b', '_g', '_c');
versions['popSamp1'] = new Array('_b', '_g', '_a', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_b', '_g', '_a', '_c');
versions['popSamp4'] = new Array('_b', '_g');
versions['popSamp5'] = new Array('_b', '_g', '_c');
versions['infPopn1'] = new Array('_b', '_g', '_c');
versions['infPopn2'] = new Array('_b', '_g', '_c', '_z');
versions['infPopn3'] = new Array('_b', '_g', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_b', '_g');
versions['probDensity2'] = new Array('_b', '_g', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_b', '_g', '_c');
versions['randomMean6'] = new Array('_b', '_g', '_c');
versions['randomMean7'] = new Array('_b', '_g');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_b', '_g', '_c');
versions['normalDistn6'] = new Array('_b', '_g', '_c');
versions['normalDistn7'] = new Array('_b', '_g', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_b', '_g', '_c');
versions['randomPropn4'] = new Array('_b', '_g', '_c');
versions['randomPropn6'] = new Array('_b', '_g', '_c');
versions['estIntro1'] = new Array('_b', '_g', '_c');
versions['estIntro2'] = new Array('_b', '_g', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_b', '_g', '_c');
versions['seMean1'] = new Array('_b', '_g', '_c');
versions['seMean2'] = new Array('_b', '_g');
versions['seMean3'] = new Array('_b', '_g');
versions['seMean4'] = new Array('_b', '_g', '_c');
versions['seMean6'] = new Array('_b', '_g', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_b', '_g');
versions['ciMean7'] = new Array('_b', '_g', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_b', '_g', '_c');
versions['estPropn4'] = new Array('_b', '_g', '_c');
versions['estPropn5'] = new Array('_b', '_g', '_c');
versions['estPropn7'] = new Array('_b', '_g', '_c');
versions['testIntro1'] = new Array('_b', '_g');
versions['testIntro3'] = new Array('_b', '_g', '_c');
versions['testIntro5'] = new Array('_b', '_g');
versions['testIntro7'] = new Array('_b', '_g', '_c');
versions['testPropn1'] = new Array('_b', '_g', '_c');
versions['testPropn2'] = new Array('_b', '_g', '_c');
versions['testPropn3'] = new Array('_b', '_g', '_c');
versions['testPropn4'] = new Array('_b', '_g', '_c');
versions['testPropn5'] = new Array('_b', '_g');
versions['testPropn7'] = new Array('_b', '_g');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean2'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_b', '_g');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['twoGroupModel1'] = new Array('_b', '_g', '_c');
versions['twoGroupModel2'] = new Array('_b', '_g', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_b', '_g', '_c');
versions['twoGroupInf3'] = new Array('_b', '_g', '_c');
versions['twoGroupInf4'] = new Array('_b', '_g', '_c');
versions['twoGroupInf5'] = new Array('_b', '_g', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_b', '_g', '_c');
versions['testPaired2'] = new Array('_b', '_g', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['scatterplot1'] = new Array('_b', '_g', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_b', '_g', '_c');
versions['leastSqrs1'] = new Array('_b', '_g', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['regnModel1'] = new Array('_b', '_g', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_b', '_g', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnProblem3'] = new Array('_b', '_g');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');

bookLoaded = true;
