
addBook('bk/sadc_c4', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/african_c2', 'ch_sampDistn', "Distributions");
addSection('bk/general', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots", 'interact', 'en/normalDistn', 's_normalDistn10');

addChapter('bk/business', 'ch_timeSeries', "Time Series");
addSection('bk/general', 'sec_multiplicative', "Multiplicative models");
addPage_2('en/multiplicative', 'multiplicative1', "Additive and multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative1');
addPage_2('en/multiplicative', 'multiplicative2', "Properties of multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative2');
addPage_2('en/multiplicative', 'multiplicative3', "Forecasting with multiplicative models", 'interact', 'en/multiplicative', 's_multiplicative3');
addPage_2('en/multiplicative', 'multiplicative4', "Analysing the right data", 'static', 'en/multiplicative', 's_multiplicative4');
addPage_2('en/multiplicative', 'multiplicative5', "Types of time series data", 'static', 'en/multiplicative', 's_multiplicative5');

addChapter('bk/general', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/african_c2', 'sec_estOther', "Simulation and bootstrap");
addPage_2('en/estOther', 'estOther1', "Need for simulation", 'static', 'en/estOther', 's_estOther1');
addPage_2('en/estOther', 'estOther2', "Error distribution by simulation", 'interact', 'en/estOther', 's_estOther2');
addPage_2('en/estOther', 'estOther_m3', "Simulations with normal distns", 'interact', 'en/estOther', 's_estOther3');
addPage_2('en/estOther', 'estOther4', "Bootstrap error distribution", 'interact', 'en/estOther', 's_estOther4');
addPage_2('en/estOther', 'estOther5', "Standard error of correlation", 'interact', 'en/estOther', 's_estOther5');
addPage_2('en/estOther', 'estOther_m6', "CIs from simulation", 'interact', 'en/estOther', 's_estOther6');

addChapter('bk/general', 'ch_independence', "Independence", null, 'v_ch_independence');
addSection('bk/african_c2', 'sec_prob', "Marginal & conditional probability");
addPage_2('en/prob', 'prob_b1', "Joint probabilities", 'interact', 'en/prob', 's_prob1');
addPage_2('en/prob', 'prob_b2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2');
addPage_2('en/prob', 'prob_b3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4');
addPage_2('en/prob', 'prob5', "Calculations with probabilities", 'interact', 'en/prob', 's_prob5');

addChapter('bk/african_c2', 'ch_aboutReln', "About Relationships");
addSection('bk/biometric', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal_b1', "Interest in relationships", 'static', 'en/causal', 's_causal1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2');
addPage_2('en/causal', 'causal_b3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3');
addPage_2('en/causal', 'causal_b4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5');
addSection('bk/biometric', 'sec_lurking', "Marginal relationships");
addPage_2('en/lurking', 'lurking_b1', "Misleading marginal correlation", 'interact', 'en/lurking', 's_lurking1');
addPage_2('en/lurking', 'lurking_b2', "Misleading marginal difference in means", 'interact', 'en/lurking', 's_lurking2');
addPage_2('en/lurking', 'lurking3', "Simpsons paradox", 'interact', 'en/lurking', 's_lurking3');
addPage_2('en/lurking', 'lurking4', "Other examples with lurking variables", 'static', 'en/lurking', 's_lurking4');

addChapter('bk/african_c2', 'ch_expDesign', "Designed Experiments");
addSection('bk/biometric', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'designIntro_b1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4');
addPage_2('en/designIntro', 'designIntro_b5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6');
addPage_2('en/designIntro', 'designIntro7', "Blocking", 'interact', 'en/designIntro', 's_designIntro7');
addSection('bk/general', 'sec_pairBlock', "Pairing and blocks");
addPage_2('en/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact', 'en/pairBlock', 's_pairBlock1');
addPage_2('en/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact', 'en/pairBlock', 's_pairBlock2');
addPage_2('en/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact', 'en/pairBlock', 's_pairBlock3');
addPage_2('en/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact', 'en/pairBlock', 's_pairBlock4');
addPage_2('en/pairBlock', 'pairBlock5', "Randomised block experiments", 'static', 'en/pairBlock', 's_pairBlock5');
addSection('bk/biometric', 'sec_designTwo', "Two or more factors");
addPage_2('en/designTwo', 'designTwo_b1', "Experiments with 2 factors", 'interact', 'en/designTwo', 's_designTwo1');
addPage_2('en/designTwo', 'designTwo_b2', "Factorial design", 'static', 'en/designTwo', 's_designTwo2');
addPage_2('en/designTwo', 'designTwo3', "Simple model for two factors", 'interact', 'en/designTwo', 's_designTwo3');
addPage_2('en/designTwo', 'designTwo4', "Interaction between factors", 'interact', 'en/designTwo', 's_designTwo4');
addPage_2('en/designTwo', 'designTwo5', "Example with interaction", 'interact', 'en/designTwo', 's_designTwo5');
addPage_2('en/designTwo', 'designTwo_b6', "No-interaction model for three factors", 'interact', 'en/designTwo', 's_designTwo6');
addPage_2('en/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact', 'en/designTwo', 's_designTwo7');
addSection('bk/general', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3');

addChapter('bk/african_c2', 'ch_manyMeans', "Comparing Many Means");
addSection('bk/general', 'sec_randBlock', "Randomised blocks");
addPage_2('en/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static', 'en/randBlock', 's_randBlock1');
addPage_2('en/randBlock', 'randBlock2', "Example with baseline treatment", 'interact', 'en/randBlock', 's_randBlock2');
addPage_2('en/randBlock', 'randBlock3', "Use of blocking information", 'interact', 'en/randBlock', 's_randBlock3');
addPage_2('en/randBlock', 'randBlock4', "Randomised block designs", 'interact', 'en/randBlock', 's_randBlock4');
addPage_2('en/randBlock', 'randBlock5', "Model for randomised blocks", 'interact', 'en/randBlock', 's_randBlock5');
addPage_2('en/randBlock', 'randBlock6', "Removing block effects", 'interact', 'en/randBlock', 's_randBlock6');
addPage_2('en/randBlock', 'randBlock7', "Sums of squares", 'interact', 'en/randBlock', 's_randBlock7');
addPage_2('en/randBlock', 'randBlock8', "Anova table and examples", 'static', 'en/randBlock', 's_randBlock8');

addChapter('bk/regn', 'ch_simpleRegn', "Simple Linear Regression");
addSection('bk/regn', 'sec_diagnostics', "Leverage, outliers and influence");
addPage_2('en/diagnostics', 'diagnostics1', "Leverage", 'interact');
addPage_2('en/diagnostics', 'diagnostics2', "Outliers and leverage", 'interact');
addPage_2('en/diagnostics', 'diagnostics3', "Variances of the residuals", 'interact');
addPage_2('en/diagnostics', 'diagnostics4', "Standardised residuals", 'interact');
addPage_2('en/diagnostics', 'diagnostics5', "Deleted residuals", 'interact');
addPage_2('en/diagnostics', 'diagnostics6', "Externally studentised residuals", 'interact');
addPage_2('en/diagnostics', 'diagnostics7', "Influence on fitted values", 'interact');
addPage_2('en/diagnostics', 'diagnostics8', "Influence on regression coefficients", 'interact');
addPage_2('en/diagnostics', 'diagnostics9', "Summary and examples", 'interact');
addSection('bk/general', 'sec_logistic', "Logistic regression");
addPage_2('en/logistic', 'logistic1', "Categorical responses", 'interact', 'en/logistic', 's_logistic1');
addPage_2('en/logistic', 'logistic2', "Fitted values and predictions", 'interact', 'en/logistic', 's_logistic2');
addPage_2('en/logistic', 'logistic3', "Logistic curve", 'interact', 'en/logistic', 's_logistic3');
addPage_2('en/logistic', 'logistic4', "Obtaining a good fit", 'interact', 'en/logistic', 's_logistic4');

addChapter('bk/regn', 'ch_multipleRegn', "Multiple Regression");
addSection('bk/regn', 'sec_glm', "The general linear model");
addPage_2('en/glm', 'glm1', "General linear model", 'static');
addPage_2('en/glm', 'glm2', "Describing the simple linear model with matrices", 'interact');
addPage_2('en/glm', 'glm3', "General linear model with matrices", 'interact');
addPage_2('en/glm', 'glm4', "Least squares with matrices", 'interact');
addPage_2('en/glm', 'glm5', "Interpreting coefficients", 'interact');
addPage_2('en/glm', 'glm6', "Standard errors", 'interact');
addPage_2('en/glm', 'glm7', "Inference for general linear models", 'interact');
addSection('bk/regn', 'sec_nonlinTwo', "Nonlinear relationships");
addPage_2('en/nonlinTwo', 'nonlinTwo1', "Linear models for curvature", 'static');
addPage_2('en/nonlinTwo', 'nonlinTwo2', "Linearity of quadratic models", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo3', "Polynomial models", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo4', "Residual plots to detect nonlinearity", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo5', "Partial residual plots", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo6', "Model with quadratic in X, linear in Z", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo7', "Model with quadratic terms in X and Z", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo8', "Visualising least squares", 'interact');
addPage_2('en/nonlinTwo', 'nonlinTwo9', "Tests for curvature in X and Z", 'interact');
addSection('bk/regn', 'sec_interact', "Interaction");
addPage_2('en/interact', 'interact1', "Additivity of effects of X and Z", 'interact');
addPage_2('en/interact', 'interact2', "Interaction between X and Z", 'interact');
addPage_2('en/interact', 'interact3', "Inference for models with interaction", 'interact');
addPage_2('en/interact', 'interact4', "Tranformations and interaction", 'interact');
addPage_2('en/interact', 'interact5', "Example (nonlinearity and interaction)", 'interact');
addSection('bk/regn', 'sec_diagnosticsTwo', "Diagnostics for models with 2 explanatory variables");
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo1', "Problem points", 'static');
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo2', "Leverage", 'interact');
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo3', "Problems with high leverage", 'interact');
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo4', "Standardised residuals", 'interact');
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo5', "Externally studentised residuals", 'interact');
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo6', "Influence", 'static');
addPage_2('en/diagnosticsTwo', 'diagnosticsTwo7', "Examples", 'interact');

addChapter('bk/regn', 'ch_regnAnova', "Analysis of Variance");
addSection('bk/regn', 'sec_regnAnova', "Anova for simple linear model");
addPage_2('en/regnAnova', 'regnAnova1', "Components for regression model", 'interact');
addPage_2('en/regnAnova', 'regnAnova2', "Sums of squares", 'interact');
addPage_2('en/regnAnova', 'regnAnova3', "Coefficient of determination", 'interact');
addPage_2('en/regnAnova', 'regnAnova4', "Coefficient of determination and experiments", 'interact');
addPage_2('en/regnAnova', 'regnAnova5', "Analysis of variance test", 'static');
addSection('bk/regn', 'sec_multiRegnAnova', "All-or-nothing anova");
addPage_2('en/multiRegnAnova', 'multiRegnAnova1', "Components of variation for Y vs X and Z", 'interact');
addPage_2('en/multiRegnAnova', 'multiRegnAnova2', "Sums of squares for Y vs X and Z", 'interact');
addPage_2('en/multiRegnAnova', 'multiRegnAnova3', "F test for regression of Y vs X and Z", 'interact');
addPage_2('en/multiRegnAnova', 'multiRegnAnova4', "All-or-nothing F test for any GLM", 'static');
addPage_2('en/multiRegnAnova', 'multiRegnAnova5', "Different interpretations of R-sqr and F", 'interact');
addSection('bk/regn', 'sec_multicollin', "Multicollinearity of X and Z");
addPage_2('en/multicollin', 'multicollin1', "Correlated explanatory variables", 'interact');
addPage_2('en/multicollin', 'multicollin2', "Correlated explanatory variables", 'interact');
addPage_2('en/multicollin', 'multicollin3', "Understanding multicollinearity", 'interact');
addPage_2('en/multicollin', 'multicollin4', "Understanding multicollinearity (cont)", 'interact');
addPage_2('en/multicollin', 'multicollin5', "F- and t-tests: a paradox?", 'interact');
addPage_2('en/multicollin', 'multicollin6', "T-tests in full and partial models", 'interact');
addSection('bk/regn', 'sec_seqRegnSsq', "Sequential sums of squares");
addPage_2('en/seqRegnSsq', 'seqRegnSsq1', "Sequentially adding variables", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq2', "Splitting the explained sum of squares", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq3', "Order of adding X and Z", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq4', "Anova tests for individual variables", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq5', "Orthogonal variables", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq6', "Orthogonal variables and experimental design", 'interact');
addPage_2('en/seqRegnSsq', 'seqRegnSsq7', "Other sequences of models", 'static');
addSection('bk/regn', 'sec_nonlinAnova', "Testing linearity in regression");
addPage_2('en/nonlinAnova', 'nonlinAnova1', "Linear and quadratic models", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova2', "Understanding the sums of squares", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova3', "Testing for linearity", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova4', "Polynomial models", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova5', "Testing curvature in complex models", 'interact');
addPage_2('en/nonlinAnova', 'nonlinAnova6', "Inference for models with interaction", 'interact');
addSection('bk/regn', 'sec_glmAnova', "Several explanatory variables");
addPage_2('en/glmAnova', 'glmAnova1', "Marginal sums of squares", 'interact');
addPage_2('en/glmAnova', 'glmAnova2', "Variable selection", 'interact');
addPage_2('en/glmAnova', 'glmAnova3', "Multicollinearity", 'interact');
addPage_2('en/glmAnova', 'glmAnova4', "Sequential sums of squares", 'interact');
addPage_2('en/glmAnova', 'glmAnova5', "Sequential sums of squares and fitted values", 'interact');
addPage_2('en/glmAnova', 'glmAnova6', "Order of variables in ssq table", 'interact');
addPage_2('en/glmAnova', 'glmAnova7', "Sums of squares for groups of variables", 'interact');
addPage_2('en/glmAnova', 'glmAnova8', "Hypothesis tests in anova tables", 'interact');

var language = "en";
var logoGif = "logo_sadc.gif";
var homeDir = "bk/sadc_c4";
var versionGif = "images/castSadc_c4";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "11";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_c': 'Business', '_b': 'Biometric', '_m': 'Climatic'};
var versions = {};
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['estOther3'] = new Array('_m', '_g', '_c');
versions['estOther5'] = new Array('_g', '_b');
versions['estOther6'] = new Array('_m', '_g', '_c');
versions['prob1'] = new Array('_b', '_g', '_c');
versions['prob2'] = new Array('_b', '_g', '_c');
versions['prob3'] = new Array('_b', '_g');
versions['prob5'] = new Array('_g', '_c');
versions['causal1'] = new Array('_b', '_g', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_b', '_g', '_c');
versions['causal4'] = new Array('_b', '_g', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_b', '_g', '_c');
versions['lurking2'] = new Array('_b', '_g');
versions['lurking3'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_b', '_g', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_b', '_g', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_g', '_b');
versions['designTwo1'] = new Array('_b', '_g');
versions['designTwo2'] = new Array('_b', '_g');
versions['designTwo6'] = new Array('_b', '_g');
versions['designPrelim2'] = new Array('_g', '_c');
versions['logistic1'] = new Array('_g', '_b', '_c');
versions['logistic2'] = new Array('_g', '_b', '_c');
versions['logistic4'] = new Array('_g', '_b', '_c');

bookLoaded = true;
