
addBook('bk/masseyBe', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addPart("For 100-level projects");

addChapter('bk/massey120', 'ch_intro', "Introduction", null, 'v_ch_intro');
addSection('bk/general', 'sec_context', "Context");
addPage_2('en/context', 'context1', "Importance of context", 'static', 'en/context', 's_context1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3');
addSection('bk/massey120', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures1', "Variables and individuals", 'interact', 'en/structures', 's_structures1');
addPage_2('en/structures', 'structures2', "Types of variable", 'interact', 'en/structures', 's_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3');
addPage_2('en/structures', 'structures4', "Meaningful variables", 'interact', 'en/structures', 's_structures4');
addPage_2('en/structures', 'structures5', "Time-ordered data", 'static', 'en/structures', 's_structures5');
addSection('bk/massey120', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4');

addChapter('bk/massey120', 'ch_graphicalSum', "Graphical Summaries", null, 'v_ch_graphicalSum');
addSection('bk/massey120', 'sec_valueDisplay', "Dot plots &amp; stem-and-leaf plots");
addPage_2('en/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1');
addPage_2('en/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2');
addPage_2('en/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4');
addPage_2('bk/massey120', 'valueDisplay5', "Simple stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5');
addPage_2('bk/massey120', 'valueDisplay7', "Drawing stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay7');
addSection('bk/general', 'sec_displayInterp', "Understanding distributions");
addPage_2('en/displayInterp', 'displayInterp1', "Outliers", 'static', 'en/displayInterp', 's_displayInterp1');
addPage_2('en/displayInterp', 'displayInterp2', "Clusters", 'interact', 'en/displayInterp', 's_displayInterp2');
addPage_2('en/displayInterp', 'displayInterp3', "Distribution of values", 'static', 'en/displayInterp', 's_displayInterp3');
addPage_2('en/displayInterp', 'displayInterp4', "Names of individuals", 'interact', 'en/displayInterp', 's_displayInterp4');
addPage_2('en/displayInterp', 'displayInterp5', "Distinguishing known groups", 'interact', 'en/displayInterp', 's_displayInterp5');
addPage_2('en/displayInterp', 'displayInterp6', "Dangers of overinterpretation", 'interact', 'en/displayInterp', 's_displayInterp6');
addSection('bk/massey120', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2');
addPage_2('en/density', 'density3', "Choice of classes", 'interact', 'en/density', 's_density3');
addPage_2('en/density', 'density4', "Histograms of small data sets", 'interact', 'en/density', 's_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5');
addPage_2('en/density', 'density6', "Comparing groups", 'interact', 'en/density', 's_density6');
addPage_2('en/density', 'density9', "Frequency polygons", 'interact', 'en/density', 's_density9');
addSection('bk/massey120', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1');
addPage_2('en/counts', 'counts2', "Histograms for counts", 'interact', 'en/counts', 's_counts2');
addPage_2('en/counts', 'counts3', "Bar charts", 'interact', 'en/counts', 's_counts3');
addSection('bk/general', 'sec_freqTable', "Frequency tables");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2');
addPage_2('en/freqTable', 'freqTable3', "Recognising frequency tables", 'static', 'en/freqTable', 's_freqTable3');
addPage_2('en/freqTable', 'freqTable4', "Changes to the categories", 'interact', 'en/freqTable', 's_freqTable4');
addSection('bk/massey120', 'sec_univarCat', "Bar and pie charts");
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1');
addPage_2('en/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4');
addPage_2('en/univarCat', 'univarCat5', "Comparison of bar and pie charts", 'interact', 'en/univarCat', 's_univarCat5');
addPage_2('en/univarCat', 'univarCat7', "Bar and pie charts for quantities", 'interact', 'en/univarCat', 's_univarCat7');

addChapter('bk/massey120', 'ch_sumStats', "Summary Statistics", null, 'v_ch_sumStats');
addSection('bk/massey120', 'sec_boxPlot', "Median, quartiles &amp; box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6');
addPage_2('en/boxPlot', 'boxPlot7', "Dangers of over-interpretation", 'interact', 'en/boxPlot', 's_boxPlot7');
addSection('bk/massey120', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8');
addPage_2('bk/massey120', 'counts4', "Mean and st devn for discrete data", 'static', 'en/counts', 's_counts4');

addChapter('bk/massey120', 'ch_bivar', "Bivariate Relationships", null, 'v_ch_bivar');
addSection('bk/general', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot1', "More than one variable", 'interact', 'en/scatterplot', 's_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5');
addSection('bk/massey120', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation1');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6');
addSection('bk/massey120', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y & predicting X#?# (opt)", 'interact', 'en/leastSqrs', 's_leastSqrs7');
addSection('bk/massey120', 'sec_rSquared', "Coefficient of determination");
addPage_2('bk/massey120', 'rSquared1', "Sums of squares", 'interact', 'bk/massey120', 's_rSquared1');
addPage_2('bk/massey120', 'rSquared2', "Coefficient of determination", 'interact', 'bk/massey120', 's_rSquared2');
addSection('bk/massey120', 'sec_continTable', "Contingency tables");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat2');
addPage_2('bk/massey120', 'continTable3', "Proportions within groups", 'interact', 'en/groupedCat', 's_groupedCat3');
addPage_2('bk/massey120', 'bivarCat1', "Categorical variables and groups", 'static', 'bk/massey120', 's_bivarCat1');
addPage_2('en/bivarCat', 'bivarCat4', "Marginal distributions", 'interact', 'en/bivarCat', 's_bivarCat4');
addPage_2('en/bivarCat', 'bivarCat5', "Conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat5');
addPage_2('en/bivarCat', 'bivarCat7', "Conditional vs marginal distns#?# (opt)", 'interact', 'en/bivarCat', 's_bivarCat7');

addChapter('bk/massey120', 'ch_basicCollection', "Basic Data Collection", null, 'v_ch_basicCollection');
addSection('bk/general', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal1', "Interest in relationships", 'static', 'en/causal', 's_causal1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2');
addPage_2('en/causal', 'causal3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3');
addPage_2('en/causal', 'causal4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5');
addSection('bk/massey120', 'sec_sampPractice', "Sampling in practice");
addPage_2('bk/massey120', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'bk/massey120', 's_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5');
addPage_2('en/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6');
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7');
addSection('bk/massey120', 'sec_designIntro', "Simple experiments");
addPage_2('en/designIntro', 'designIntro1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4');
addPage_2('en/designIntro', 'designIntro5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6');

addPart("For 200-level projects");

addChapter('bk/massey120', 'ch_sample', "Sampling and Probability", null, 'v_ch_sample');
addSection('bk/massey120', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2');
addPage_2('en/popSamp', 'popSamp3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3');
addPage_2('en/popSamp', 'popSamp4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4');
addPage_2('en/popSamp', 'popSamp5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6');
addSection('bk/massey120', 'sec_infPopn', "Sampling from a distribution");
addPage_2('en/infPopn', 'infPopn1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn1');
addPage_2('en/infPopn', 'infPopn2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2');
addPage_2('en/infPopn', 'infPopn3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5');
addSection('bk/massey120', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1');
addPage_2('en/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4');
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6');
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7');
addSection('bk/massey120', 'sec_probTable', "Probabilities from tables");
addPage_2('en/prob', 'prob1', "Joint probabilities", 'interact', 'en/prob', 's_prob1');
addPage_2('en/prob', 'prob2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2');
addPage_2('en/prob', 'prob3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4');
addPage_2('en/indep', 'indep1', "Association", 'static', 'en/indep', 's_indep1');
addPage_2('en/indep', 'indep2', "Independence", 'static', 'en/indep', 's_indep2');
addSection('bk/massey120', 'sec_probSim', "Simulation (optional)");
addPage_2('en/probSim', 'probSim1', "Probability models and simulation", 'interact', 'en/probSim', 's_probSim1');
addPage_2('en/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact', 'en/probSim', 's_probSim2');
addPage_2('en/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact', 'en/probSim', 's_probSim3');
addPage_2('en/probSim', 'probSim4', "Assessing unusual features in data", 'interact', 'en/probSim', 's_probSim4');
addPage_2('en/probSim', 'probSim5', "Random numbers", 'interact', 'en/probSim', 's_probSim5');
addPage_2('en/probSim', 'probSim6', "Generating categorical values", 'interact', 'en/probSim', 's_probSim6');

addChapter('bk/massey120', 'ch_meanPropnDistn', "Sample Means and Propns", null, 'v_ch_meanPropnDistn');
addSection('bk/massey120', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5');
addPage_2('en/randomMean', 'randomMean6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean6');
addPage_2('en/randomMean', 'randomMean7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite popns#?# (opt)", 'interact', 'en/randomMean', 's_randomMean8');
addSection('bk/massey120', 'sec_normalDistn', "Normal distributions");
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4');
addPage_2('bk/massey120', 'correlation2', "Z-scores for data sets", 'interact', 'en/correlation', 's_correlation2');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9');
addPage_2('en/normalDistn', 'normalDistn10', "Normal probability plots#?# (opt)", 'interact', 'en/normalDistn', 's_normalDistn10');
addSection('bk/general', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3');
addPage_2('en/randomPropn', 'randomPropn4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn6');

addChapter('bk/massey120', 'ch_masteryTests', "Mastery Tests");
addSection('bk/massey120', 'sec_masteryOne', "Exercises for test 1");
addPage_2('bk/massey120', 'e_density1', "Draw a histogram", 'static');
addPage_2('bk/massey120', 'e_density2', "Estimate proportion from histogram", 'static');
addPage_2('en/displayInterp', 'e_displayInterp1', "Interpret shape of stacked dot plot", 'static');
addPage_2('en/centerSpread', 'e_centerSpread1', "Concepts of centre and spread", 'static');
addPage_2('en/centerSpread', 'e_centerSpread2', "Guess mean and median", 'static');
addPage_2('bk/massey120', 'e_centerSpread3', "Guess SD from histogram", 'static');
addPage_2('en/centerSpread', 'e_centerSpread4', "Guess SD from general knowledge", 'static');
addPage_2('en/freqTable', 'e_freqTable1', "Identify numerical and categorical variables", 'static');
addPage_2('en/univarCat', 'e_univarCat6', "Find percentage from a pie chart", 'static');
addPage_2('en/univarCat', 'e_univarCat5', "Match pie charts and bar charts", 'static');
addSection('bk/massey120', 'sec_masteryTwo', "Exercises for test 2");
addPage_2('bk/massey120', 'e_scatterplot2', "Interpret scatterplot", 'static');
addPage_2('en/correlation', 'e_correlation1', "Guess correlation", 'static');
addPage_2('bk/massey120', 'e_leastSqrs3', "Find equation of line", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs5', "Find a residual", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs4', "Interpret slope and intercept", 'static');
addPage_2('en/leastSqrs', 'e_leastSqrs7', "Make prediction from LS line", 'static');
addPage_2('bk/massey120', 'e_curvature1', "Identify problems with LS line", 'static');
addPage_2('en/timePlot', 'e_timePlot1', "Identify patterns in a time series", 'static');
addPage_2('en/smoothing', 'e_smoothing1', "Find smoothed time series values", 'static');
addPage_2('en/groupedCat', 'e_groupedCat2', "Find proportion from contingency table", 'static');
addSection('bk/massey120', 'sec_masteryThree', "Exercises for test 3");
addPage_2('en/popSamp', 'e_popSamp2', "Identify parameters and estimates", 'static');
addPage_2('en/probSim', 'e_probSim1', "Find probability about cards or dice", 'static');
addPage_2('en/probSim', 'e_probSim5', "Probability when sampling with/without replacement", 'static');
addPage_2('en/randomPropn', 'e_randomPropn1', "Identify binomial variables", 'static');
addPage_2('en/randomPropn', 'e_randomPropn3', "Find binomial prob from a barchart", 'static');
addPage_2('en/randomPropn', 'e_randomPropn5', "Find binomial prob using normal approx", 'static');
addPage_2('en/probSim', 'e_probSim4', "Find probability for non-normal pdf", 'static');
addPage_2('bk/massey120', 'e_normalDistn1', "Guess SD from normal pdf", 'static');
addPage_2('bk/massey120', 'e_normalDistn3', "Find normal probability using z-score", 'static');
addPage_2('bk/massey120', 'e_normalDistn5', "Find a normal quantile", 'static');

addPart("Slightly more advanced");

addChapter('bk/massey120', 'ch_timeSeries', "Time Series", null, 'v_ch_timeSeries');
addSection('bk/general', 'sec_timePlot', "Time series plots");
addPage_2('en/timePlot', 'timePlot1', "Time series plots", 'interact', 'en/timePlot', 's_timePlot1');
addPage_2('en/timePlot', 'timePlot2', "Patterns in time series", 'interact', 'en/timePlot', 's_timePlot2');
addPage_2('en/timePlot', 'timePlot3', "Multiple time series", 'interact', 'en/timePlot', 's_timePlot3');
addSection('bk/massey120', 'sec_smoothing', "Smoothing");
addPage_2('en/smoothing', 'smoothing1', "Moving averages", 'interact', 'en/smoothing', 's_smoothing1');
addPage_2('en/smoothing', 'smoothing2', "More about moving averages", 'interact', 'en/smoothing', 's_smoothing2');
addPage_2('en/smoothing', 'smoothing3', "Robust smoothing", 'interact', 'en/smoothing', 's_smoothing3');
addPage_2('en/smoothing', 'smoothing4', "Exponential smoothing", 'interact', 'en/smoothing', 's_smoothing4');
addSection('bk/general', 'sec_trend', "Long-term trend");
addPage_2('en/trend', 'trend1', "Linear trend", 'interact', 'en/trend', 's_trend1');
addPage_2('en/trend', 'trend2', "Quadratic trend", 'interact', 'en/trend', 's_trend2');
addPage_2('en/trend', 'trend3', "Forecasting", 'interact', 'en/trend', 's_trend3');
addPage_2('en/trend', 'trend4', "Polynomial trend", 'interact', 'en/trend', 's_trend4');
addPage_2('en/trend', 'trend5', "Detrending a time series", 'interact', 'en/trend', 's_trend5');

addChapter('bk/massey120', 'ch_moreGraphics', "More Exploratory Graphics", null, 'v_ch_moreGraphics');
addSection('bk/massey120', 'sec_moreGraphs', "Improved simple graphs");
addPage_2('en/valueDisplay', 'valueDisplay6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6');
addPage_2('bk/massey120', 'density7', "Histograms with varying class widths", 'interact', 'bk/massey120', 's_density7');
addPage_2('bk/massey120', 'density8', "Histogram areas and proportions", 'interact', 'bk/massey120', 's_density8');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot5', "Clusters", 'interact', 'en/boxPlot', 's_boxPlot5');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2');
addSection('bk/massey120', 'sec_transform', "Transformations");
addPage_2('en/transform', 'transform1', "Linear transformations", 'interact', 'en/transform', 's_transform1');
addPage_2('en/transform', 'transform2', "Log transformations", 'interact', 'en/transform', 's_transform2');
addPage_2('en/transform', 'transform3', "When to use log transform?", 'interact', 'en/transform', 's_transform3');
addPage_2('en/transform', 'transform4', "Power transformations", 'interact', 'en/transform', 's_transform4');
addPage_2('en/transform', 'transform5', "Power transforms &amp; skewness#?# (opt)", 'interact', 'en/transform', 's_transform5');
addSection('bk/massey120', 'sec_nonlinear', "Nonlinear relationships");
addPage_2('bk/massey120', 'correlation5', "Correlation and nonlinear relationships", 'interact', 'en/correlation', 's_correlation5');
addPage_2('en/curvature', 'curvature1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1');
addPage_2('en/curvature', 'curvature2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2');
addPage_2('en/curvature', 'curvature3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3');
addPage_2('en/curvature', 'curvature4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4');
addPage_2('bk/massey120', 'smoothing6', "Lowess smoothing of scatterplots#?# (opt)", 'interact', 'en/smoothing', 's_smoothing6');
addSection('bk/general', 'sec_multivariate', "Displaying multivariate data");
addPage_2('en/multivariate', 'multivariate1', "Representing a third variable", 'interact', 'en/multivariate', 's_multivariate1');
addPage_2('en/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact', 'en/multivariate', 's_multivariate2');
addPage_2('en/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact', 'en/multivariate', 's_multivariate3');
addPage_2('en/multivariate', 'multivariate4', "Brushing example", 'interact', 'en/multivariate', 's_multivariate4');
addPage_2('en/multivariate', 'multivariate5', "Slicing", 'interact', 'en/multivariate', 's_multivariate5');

addChapter('bk/massey120', 'ch_dataPresentation', "Data Presentation", null, 'v_ch_dataPresentation');
addSection('bk/official', 'sec_tableDisplay', "Presenting data in tables");
addPage_2('en/tableDisplay', 'tableDisplay0', "Overview", 'static');
addPage_2('en/tableDisplay', 'tableDisplay1', "Gridlines and white space", 'static', 'en/tableDisplay', 's_tableDisplay1');
addPage_2('en/tableDisplay', 'tableDisplay2', "Layout and annotation", 'static', 'en/tableDisplay', 's_tableDisplay2');
addPage_2('en/tableDisplay', 'tableDisplay3', "Significant digits and data noise", 'interact', 'en/tableDisplay', 's_tableDisplay3');
addPage_2('en/tableDisplay', 'tableDisplay4', "Meaningful variables", 'interact', 'en/tableDisplay', 's_tableDisplay4');
addPage_2('en/tableDisplay', 'tableDisplay5', "Swapping rows and columns", 'static', 'en/tableDisplay', 's_tableDisplay5');
addPage_2('en/tableDisplay', 'tableDisplay6', "Reordering rows", 'interact', 'en/tableDisplay', 's_tableDisplay6');
addPage_2('en/tableDisplay', 'tableDisplay7', "Example", 'static', 'en/tableDisplay', 's_tableDisplay7');
addSection('bk/massey120', 'sec_barPieDisplay', "Presenting bar and pie charts");
addPage_2('en/simpleBar', 'simpleBar1', "Bar charts", 'interact', 'en/simpleBar', 's_simpleBar1');
addPage_2('bk/massey120', 'simpleBar2', "Ordering of categories", 'interact', 'bk/massey120', 's_simpleBar2');
addPage_2('en/simpleBar', 'simpleBar3', "Importance of zero and -ve values", 'interact', 'en/simpleBar', 's_simpleBar3');
addPage_2('en/simpleBar', 'simpleBar4', "Chartjunk", 'static', 'en/simpleBar', 's_simpleBar4');
addPage_2('en/simpleBar', 'simpleBar5', "Misleading bar charts", 'static', 'en/simpleBar', 's_simpleBar5');
addPage_2('en/simplePie', 'simplePie3', "Chartjunk for pie charts", 'interact', 'en/univarCat', 's_univarCat6');
addPage_2('en/simplePie', 'simplePie4', "Misleading stacked bar charts", 'static', 'en/simplePie', 's_simplePie4');
addSection('bk/massey120', 'sec_groupGraph', "Bar charts to compare groups");
addPage_2('bk/massey120', 'groupGraph1', "Bar charts of frequencies and proportions", 'interact', 'bk/massey120', 's_groupGraph1');
addPage_2('en/groupGraph', 'groupGraph3', "Clustered bar charts", 'interact', 'en/bivarCat', 's_bivarCat3');
addPage_2('en/groupGraph', 'groupGraph4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4');
addPage_2('en/groupGraph', 'groupGraph5', "Two categories", 'interact', 'en/groupGraph', 's_groupGraph5');
addPage_2('en/groupGraph', 'groupGraph6', "Chartjunk", 'interact', 'en/bivarCat', 's_bivarCat2');
addSection('bk/massey120', 'sec_otherGraphs', "Other ways to present data");
addPage_2('en/scatterGraph', 'scatterGraph3', "Distinguishing groups#?# (opt)", 'interact', 'en/scatterGraph', 's_scatterGraph3');
addPage_2('en/scatterGraph', 'scatterGraph4', "Showing size#?# (opt)", 'interact', 'en/scatterGraph', 's_scatterGraph4');
addPage_2('en/timeGraph', 'timeGraph7', "Dynamic scatterplots#?# (opt)", 'interact', 'en/timeGraph', 's_timeGraph7');
addPage_2('en/maps', 'maps4', "Maps with pie and bar charts#?# (opt)", 'interact', 'en/maps', 's_maps4');
addPage_2('en/maps', 'maps5', "Distorted population maps#?# (opt)", 'interact', 'en/maps', 's_maps5');
addPage_2('en/maps', 'maps6', "Other distorted maps#?# (opt)", 'static', 'en/maps', 's_maps6');
addSection('bk/massey120', 'sec_graphs', "Data presentation principles");
addPage_2('en/graphs', 'graphs0', "Overview", 'static', 'en/graphs', 's_graphs0');
addPage_2('en/graphs', 'graphs1', "Types of publication", 'static', 'en/graphs', 's_graphs1');
addPage_2('en/graphs', 'graphs2', "From data to information", 'interact', 'en/graphs', 's_graphs2');
addPage_2('en/graphs', 'graphs3', "Tables, graphs and text", 'static', 'en/graphs', 's_graphs3');
addPage_2('en/graphs', 'graphs4', "Combining simple graphs#?# (opt)", 'static', 'en/graphs', 's_graphs4');
addPage_2('en/graphs', 'graphs5', "Advanced graphs#?# (opt)", 'interact', 'en/graphs', 's_graphs5');
addPage_2('en/graphs', 'graphs6', "Innovative graphics#?# (opt)", 'static', 'en/graphs', 's_graphs6');

addChapter('bk/massey120', 'ch_moreCollection', "More Data Collection", null, 'v_ch_moreCollection');
addSection('bk/massey120', 'sec_lurking', "Lurking variables");
addPage_2('en/lurking', 'lurking1', "Misleading marginal correlation", 'interact', 'en/lurking', 's_lurking1');
addPage_2('en/lurking', 'lurking2', "Misleading marginal difference in means", 'interact', 'en/lurking', 's_lurking2');
addPage_2('en/lurking', 'lurking3', "Simpsons paradox", 'interact', 'en/lurking', 's_lurking3');
addPage_2('en/lurking', 'lurking4', "Other examples with lurking variables", 'static', 'en/lurking', 's_lurking4');
addSection('bk/massey120', 'sec_samplingSchemes', "Different sampling schemes");
addPage_2('en/sampPractice', 'sampPractice1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3');
addSection('bk/massey120', 'sec_blocks', "Experiments with blocks");
addPage_2('en/blockIntro', 'blockIntro1', "Variability of experimental units", 'interact', 'en/blockIntro', 's_blockIntro1');
addPage_2('en/blockIntro', 'blockIntro2', "Blocks of similar experimental units", 'static', 'en/blockIntro', 's_blockIntro2');
addPage_2('bk/massey120', 'oneBlock1', "Randomised block design", 'interact', 'en/oneBlock', 's_oneBlock1');
addPage_2('en/oneBlock', 'oneBlock2', "Randomised block examples", 'static', 'en/oneBlock', 's_oneBlock2');
addPage_2('en/oneBlock', 'oneBlock3', "Comparison of designs", 'interact', 'en/oneBlock', 's_oneBlock3');

addChapter('bk/massey120', 'ch_estimation', "Estimating Parameters", null, 'v_ch_estimation');
addSection('bk/general', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro1');
addPage_2('en/estIntro', 'estIntro2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4');
addPage_2('en/estIntro', 'estIntro5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7');
addSection('bk/massey120', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3');
addPage_2('en/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5');
addPage_2('en/seMean', 'seMean6', "Usng SEs to compare estimators#?# (opt)", 'interact', 'en/seMean', 's_seMean6');
addPage_2('en/seMean', 'seMean7', "More about bias#?# (opt)", 'interact', 'en/seMean', 's_seMean7');
addSection('bk/general', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1');
addPage_2('en/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6');
addPage_2('en/ciMean', 'ciMean7', "Examples", 'static', 'en/ciMean', 's_ciMean7');
addSection('bk/general', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2');
addPage_2('en/estPropn', 'estPropn3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3');
addPage_2('en/estPropn', 'estPropn4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4');
addPage_2('en/estPropn', 'estPropn5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6');
addPage_2('en/estPropn', 'estPropn7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7');
addSection('bk/general', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'ciExtra1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1');
addPage_2('en/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2');
addPage_2('en/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3');
addPage_2('en/ciExtra', 'ciExtra4', "Other confidence levels", 'interact', 'en/ciExtra', 's_ciExtra4');

var language = "en";
var logoGif = "logo_massey.gif";
var homeDir = "bk/masseyBe";
var versionGif = "../general/images/castGeneral";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = false;
var summaryPdfUrl = "http://castAdmin2.massey.ac.nz/pdf/masseyBe";
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_b': 'Biometric', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '++': 'Custom', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_g', '_b', '_c');
versions['variation4'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('+g', '_g', '_a', '_b', '_c', '_m');
versions['valueDisplay7'] = new Array('+g', '_g', '_c', '_m');
versions['displayInterp1'] = new Array('_g', '_b', '_c');
versions['displayInterp2'] = new Array('_g', '_b', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['displayInterp6'] = new Array('_g', '_b', '_c');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density9'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat7'] = new Array('_g', '_b');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts4'] = new Array('+g', '_g', '_b', '_c');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['bivarCat1'] = new Array('+g', '_g', '_b', '_c');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['sampPractice4'] = new Array('+g', '_g');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['indep1'] = new Array('_g', '_b', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_g', '_b', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_g', '_b', '_c');
versions['randomMean6'] = new Array('_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['correlation2'] = new Array('+g', '_g');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');
versions['e_density1'] = new Array('+g', '_g');
versions['e_density2'] = new Array('+g', '_g');
versions['e_centerSpread3'] = new Array('+g', '_g');
versions['e_scatterplot2'] = new Array('+g', '_g');
versions['e_leastSqrs3'] = new Array('+g', '_g');
versions['e_curvature1'] = new Array('+g', '_g');
versions['e_normalDistn1'] = new Array('+g', '_g');
versions['e_normalDistn3'] = new Array('+g', '_g');
versions['e_normalDistn5'] = new Array('+g', '_g');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_g', '_b', '_c');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['density7'] = new Array('+g', '_g', '_b', '_c', '_m');
versions['density8'] = new Array('+g', '_g');
versions['transform1'] = new Array('_g', '_b');
versions['transform2'] = new Array('_g', '_b', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['correlation5'] = new Array('+g', '_g');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['smoothing6'] = new Array('+g', '_g');
versions['multivariate1'] = new Array('_g', '_b', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['simpleBar2'] = new Array('+g', '_g');
versions['simpleBar4'] = new Array('_g', '_b');
versions['groupGraph1'] = new Array('+g', '_g');
versions['lurking1'] = new Array('_g', '_b', '_c');
versions['lurking2'] = new Array('_g', '_b');
versions['lurking3'] = new Array('_g', '_c');
versions['sampPractice1'] = new Array('_g', '_b');
versions['oneBlock1'] = new Array('+g', '_g');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');

bookLoaded = true;
