
addBook('bk/french', 'book_splash', "A Propos de ce E-book CAST");

addChapter('bk/french', 'ch_preface', "Pr&eacute;face");
addSection('bk/french', 'sec_aboutCast', "A propos de CAST");
addPage_2('fr/aboutCast', 'aboutCast1', "Qu'est-ce que CAST?", 'static');
addPage_2('fr/aboutCast', 'aboutCast2', "Structure et navigation", 'static');
addPage_2('fr/aboutCast', 'aboutCast3', "Droit d'auteur et de licence", 'static');
addPage_2('fr/aboutCast', 'aboutCast4', "Remerciements", 'static');
addPage_2('fr/aboutCast', 'aboutCast5', "A propos de l'auteur", 'static');
addSection('bk/french', 'sec_otherInfo', " Autre information");
addPage_2('fr/otherInfo', 'otherInfo1', " Navigateurs et Java", 'static');
addPage_2('fr/otherInfo', 'otherInfo2', " Problèmes?", 'static');
addPage_2('fr/otherInfo', 'otherInfo3', " Impression", 'static');
addPage_2('fr/otherInfo', 'otherInfo4', "Modifications récentes aux CAST", 'static');
addPage_2('fr/otherInfo', 'otherInfo5', "Développements futurs possibles", 'static');

addChapter('bk/french', 'ch_intro', "Introduction: Des Donn&eacute;es");
addSection('bk/french', 'sec_context', "Contexte");
addPage_2('fr/context', 'context1', "L'importance du contexte", 'static');
addPage_2('fr/context', 'context2', "Statistiques", 'static');
addPage_2('fr/context', 'context3', "Le processus statistique", 'static');
addSection('bk/french', 'sec_structures', "Structures de données standard");
addPage_2('fr/structures', 'structures1', "Variables et individus", 'interact');
addPage_2('fr/structures', 'structures2', "Types de variables", 'interact');
addPage_2('fr/structures', 'structures3', "Les variables catégorielles et les groupes", 'interact');
addPage_2('fr/structures', 'structures4', "Définir de nouvelles variables", 'interact');
addPage_2('fr/structures', 'structures5', "Temps-ordre de données", 'static');
addPage_2('fr/structures', 'structures6', "Multi-niveaux des données", 'interact');
addPage_2('fr/structures', 'structures7', "Structure de données et la méthode statistique", 'static');
addSection('bk/french', 'sec_variation', "Variation");
addPage_2('fr/variation', 'variation1', "Signal et le bruit", 'interact');
addPage_2('fr/variation', 'variation2', "La variabilité naturelle", 'interact');
addPage_2('fr/variation', 'variation3', "Variabilité causée par des expériences", 'interact');
addPage_2('fr/variation', 'variation4', "La variabilité des données d'enquête", 'interact');
addPage_2('fr/variation', 'variation5', "Variation expliquée et inexpliquée", 'static');
addPage_2('fr/variation', 'variation6', "Prédire les valeurs futures", 'static');

addChapter('bk/french', 'ch_univar', "Une Variable Numérique");
addSection('bk/french', 'sec_valueDisplay', "Affichage graphique des valeurs");
addPage_2('fr/valueDisplay', 'valueDisplay1', "L'analyse des variations", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay2', "Base dot plot", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay3', "Dot plot jittered", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay4', "Stacked parcelles points", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay5', "Tiges et feuilles", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay6', "Division des tiges", 'interact');
addPage_2('fr/valueDisplay', 'valueDisplay7', "Tiges et feuilles de dessin", 'interact');
addSection('bk/french', 'sec_displayInterp', "Comprendre distributions");
addPage_2('fr/displayInterp', 'displayInterp1', "Les valeurs aberrantes", 'static');
addPage_2('fr/displayInterp', 'displayInterp2', "Clusters", 'interact');
addPage_2('fr/displayInterp', 'displayInterp3', "Distribution des valeurs", 'static');
addPage_2('fr/displayInterp', 'displayInterp4', "Informations supplémentaires sur les individus", 'interact');
addPage_2('fr/displayInterp', 'displayInterp5', "Distinguer les groupes connus", 'interact');
addPage_2('fr/displayInterp', 'displayInterp6', "Dangers de la surinterprétation", 'interact');
addSection('bk/french', 'sec_density', "Histogrammes et la densité");
addPage_2('fr/density', 'density1', "Densité des valeurs", 'static');
addPage_2('fr/density', 'density2', "Histogramme avec des largeurs de classe égale", 'interact');
addPage_2('fr/density', 'density3', "Choix des classes", 'interact');
addPage_2('fr/density', 'density4', "Histogrammes de données de petites séries", 'interact');
addPage_2('fr/density', 'density5', "Fréquence relative et de la zone", 'interact');
addPage_2('fr/density', 'density6', "En comparant des groupes", 'interact');
addPage_2('fr/density', 'density7', "Histogrammes avec des largeurs variant de classe", 'interact');
addPage_2('fr/density', 'density8', "Comprendre les histogrammes", 'interact');
addPage_2('fr/density', 'density9', "Polygones de fréquence", 'interact');
addPage_2('fr/density', 'density10', "Estimations de la densité du noyau", 'interact');
addPage_2('fr/density', 'density11', "Dessin à la main des histogrammes", 'interact');
addSection('bk/french', 'sec_boxPlot', "Médiane, quartiles et tracés en boîte");
addPage_2('fr/boxPlot', 'boxPlot1', "La nécessité de résumer", 'static');
addPage_2('fr/boxPlot', 'boxPlot2', "Médian, quartiles et boîte à moustaches", 'interact');
addPage_2('fr/boxPlot', 'boxPlot3', "Interpréter une forme de boîte parcelles", 'interact');
addPage_2('fr/boxPlot', 'boxPlot4', "Afficher les valeurs aberrantes", 'interact');
addPage_2('fr/boxPlot', 'boxPlot5', "Clusters", 'interact');
addPage_2('fr/boxPlot', 'boxPlot6', "Comparaison des groupes", 'interact');
addPage_2('fr/boxPlot', 'boxPlot7', "Dangers de sur-interprétation", 'interact');
addSection('bk/french', 'sec_centerSpread', "Décrivant le centre et la propagation");
addPage_2('fr/centerSpread', 'centerSpread1', "Centre et la propagation", 'static');
addPage_2('fr/centerSpread', 'centerSpread2', "Médian, la gamme et IQR", 'interact');
addPage_2('fr/centerSpread', 'centerSpread3', "Résumés du centre", 'interact');
addPage_2('fr/centerSpread', 'centerSpread4', "Propriétés de la médiane et la moyenne", 'interact');
addPage_2('fr/centerSpread', 'centerSpread5', "L'écart-type", 'interact');
addPage_2('fr/centerSpread', 'centerSpread6', "Règles d'or pour l'écart-type", 'static');
addPage_2('fr/centerSpread', 'centerSpread7', "Signifie comprendre et devns er", 'interact');
addPage_2('fr/centerSpread', 'centerSpread8', "Avertissements sur devn moyenne et standard", 'static');
addSection('bk/french', 'sec_moreVariation', "En savoir plus sur la variation (en option)");
addPage_2('fr/moreVariation', 'moreVariation1', "Effet des valeurs aberrantes", 'interact');
addPage_2('fr/moreVariation', 'moreVariation2', "L'écart type des données groupées", 'interact');
addPage_2('fr/moreVariation', 'moreVariation3', "Variation expliquée et les prédictions", 'interact');
addPage_2('fr/moreVariation', 'moreVariation4', "Variance et de degrés de liberté", 'static');
addPage_2('fr/moreVariation', 'moreVariation5', "Racine l'erreur quadratique moyenne", 'interact');
addPage_2('fr/moreVariation', 'moreVariation6', "Interprétation graphique de SD", 'interact');
addSection('bk/french', 'sec_percentile', "Les proportions et les centiles");
addPage_2('fr/percentile', 'percentile1', "Ensemble de données illustratives", 'interact');
addPage_2('fr/percentile', 'percentile2', "Proportions cumulatives", 'interact');
addPage_2('fr/percentile', 'percentile3', "Graphique des proportions cumulatives", 'interact');
addPage_2('fr/percentile', 'percentile4', "Centiles", 'interact');
addPage_2('fr/percentile', 'percentile5', "Afficher les percentiles", 'interact');
addPage_2('fr/percentile', 'percentile6', "En comparant des groupes", 'interact');
addPage_2('fr/percentile', 'percentile7', "En comparant des groupes d'autres percentiles", 'interact');
addPage_2('fr/percentile', 'percentile8', "Une meilleure définition des centiles", 'interact');
addSection('bk/french', 'sec_transform', "Transformations");
addPage_2('fr/transform', 'transform1', "Transformations linéaires", 'interact');
addPage_2('fr/transform', 'transform2', "Transformations logarithmique", 'interact');
addPage_2('fr/transform', 'transform3', "Quand utiliser une transformation logarithmique?", 'interact');
addPage_2('fr/transform', 'transform4', "Puissance transformations", 'interact');
addPage_2('fr/transform', 'transform5', "Effet de transformations sur les écrans", 'interact');
addSection('bk/french', 'sec_counts', "Les données discrètes (chiffres)");
addPage_2('fr/counts', 'counts1', "Des données discrètes et continues", 'interact');
addPage_2('fr/counts', 'counts2', "Histogrammes pour les comptages", 'interact');
addPage_2('fr/counts', 'counts3', "Les diagrammes à barres", 'interact');
addPage_2('fr/counts', 'counts4', "Moyenne et St devn", 'static');

addChapter('bk/french', 'ch_bivar', "Deux Variables Numériques");
addSection('bk/french', 'sec_scatterplot', "Nuage de points");
addPage_2('fr/scatterplot', 'scatterplot1', "Plus d'une variable", 'interact');
addPage_2('fr/scatterplot', 'scatterplot2', "Nuage de points", 'interact');
addPage_2('fr/scatterplot', 'scatterplot3', "Limitations des écrans univariée", 'interact');
addPage_2('fr/scatterplot', 'scatterplot4', "Distributions marginales", 'interact');
addPage_2('fr/scatterplot', 'scatterplot5', "Des séries chronologiques", 'interact');
addSection('bk/french', 'sec_relationship', "Comprendre les relations");
addPage_2('fr/relationship', 'relationship1', "Force d'une relation", 'interact');
addPage_2('fr/relationship', 'relationship2', "Les valeurs aberrantes", 'interact');
addPage_2('fr/relationship', 'relationship3', "Clusters", 'interact');
addPage_2('fr/relationship', 'relationship4', "Dangers de sur-interprétation", 'interact');
addPage_2('fr/relationship', 'relationship5', "Les variables explicatives et la réponse", 'static');
addSection('bk/french', 'sec_correlation', "Corrélation");
addPage_2('fr/correlation', 'correlation1', "Les unités de X et Y", 'interact');
addPage_2('fr/correlation', 'correlation2', "Variables sans unités (z-scores)", 'interact');
addPage_2('fr/correlation', 'correlation3', "Le coefficient de corrélation", 'interact');
addPage_2('fr/correlation', 'correlation4', "Les diagrammes de dispersion et de la valeur de r", 'interact');
addPage_2('fr/correlation', 'correlation5', "Relations non linéaires", 'interact');
addPage_2('fr/correlation', 'correlation6', "R n'a pas raconter toute l'histoire", 'interact');
addSection('bk/french', 'sec_leastSqrs', "Moindres carrés");
addPage_2('fr/leastSqrs', 'leastSqrs1', "Prédire Y de X", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs2', "Les modèles linéaires", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs3', "Valeurs ajustées et des résidus", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs4', "Moindres carrés", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs5', "La courbure et les valeurs aberrantes", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs6', "Parcelles résiduelles", 'interact');
addPage_2('fr/leastSqrs', 'leastSqrs7', "Prédire X Y et la prédiction", 'interact');
addSection('bk/french', 'sec_curvature', "Relations non linéaires");
addPage_2('fr/curvature', 'curvature1', "Transformations et la corrélation", 'interact');
addPage_2('fr/curvature', 'curvature2', "Transformations et modèles", 'interact');
addPage_2('fr/curvature', 'curvature3', "Modèles quadratiques", 'interact');
addPage_2('fr/curvature', 'curvature4', "Les dangers de l'extrapolation", 'interact');

addChapter('bk/french', 'ch_timeSeries', "S&eacute;ries Chronologiques");
addSection('bk/french', 'sec_timePlot', "Graphiques chronologiques parcelles");
addPage_2('fr/timePlot', 'timePlot1', "S&eacute;ries Chronologiques", 'interact');
addPage_2('fr/timePlot', 'timePlot2', "Patterns dans les séries chronologiques", 'interact');
addPage_2('fr/timePlot', 'timePlot3', "Plusieurs séries chronologiques", 'interact');
addSection('bk/french', 'sec_smoothing', "Lissage");
addPage_2('fr/smoothing', 'smoothing1', "Moyennes mobiles", 'interact');
addPage_2('fr/smoothing', 'smoothing2', "En savoir plus sur les moyennes mobiles", 'interact');
addPage_2('fr/smoothing', 'smoothing3', "Lissage robuste", 'interact');
addPage_2('fr/smoothing', 'smoothing4', "Lissage exponentiel", 'interact');
addPage_2('fr/smoothing', 'smoothing5', "Lissage Lowess des séries chronologiques", 'interact');
addPage_2('fr/smoothing', 'smoothing6', "Lissage Lowess de diagrammes de dispersion", 'interact');
addSection('bk/french', 'sec_trend', "Tendance à long terme");
addPage_2('fr/trend', 'trend1', "Tendance linéaire", 'interact');
addPage_2('fr/trend', 'trend2', "Tendance quadratique", 'interact');
addPage_2('fr/trend', 'trend3', "Prévision", 'interact');
addPage_2('fr/trend', 'trend4', "Tendance polynomiale", 'interact');
addPage_2('fr/trend', 'trend5', "Élimination de la tendance d'une série chronologique", 'interact');
addSection('bk/french', 'sec_cyclic', "Fluctuations à court terme");
addPage_2('fr/cyclic', 'cyclic1', "Autocorrélation", 'interact');
addPage_2('fr/cyclic', 'cyclic2', "AR (1) le modèle de l'autocorrélation", 'interact');
addPage_2('fr/cyclic', 'cyclic3', "AR (1) modèle et la tendance", 'interact');
addPage_2('fr/cyclic', 'cyclic4', "Tendance ou autocorrélation?", 'interact');
addPage_2('fr/cyclic', 'cyclic5', "Motifs cycliques", 'interact');
addSection('bk/french', 'sec_seasonal', "Données saisonnières");
addPage_2('fr/seasonal', 'seasonal1', "Les tendances saisonnières", 'interact');
addPage_2('fr/seasonal', 'seasonal2', "Lisser les variations saisonnières", 'interact');
addPage_2('fr/seasonal', 'seasonal3', "Estimation de l'effet saisonnier", 'interact');
addPage_2('fr/seasonal', 'seasonal4', "Données désaisonnalisée", 'interact');
addPage_2('fr/seasonal', 'seasonal5', "Mettre le tout ensemble", 'interact');
addPage_2('fr/seasonal', 'seasonal6', "Prévision avec des données saisonnière", 'interact');
addSection('bk/french', 'sec_multiplicative', "Modèles multiplicatifs");
addPage_2('fr/multiplicative', 'multiplicative1', "Modèles additif et multiplicatif", 'interact');
addPage_2('fr/multiplicative', 'multiplicative2', "Propriétés des modèles multiplicatifs", 'interact');
addPage_2('fr/multiplicative', 'multiplicative3', "Prévision des modèles multiplicatifs", 'interact');
addPage_2('fr/multiplicative', 'multiplicative4', "Analyser les données correctes", 'static');
addPage_2('fr/multiplicative', 'multiplicative5', "Types de données de séries chronologiques", 'static');
addSection('bk/french', 'sec_indexNos', "Indice de chiffres");
addPage_2('fr/indexNos', 'indexNos1', "Introduction", 'static');
addPage_2('fr/indexNos', 'indexNos2', "Simple indice des prix", 'static');
addPage_2('fr/indexNos', 'indexNos3', "Indice global des prix", 'static');
addPage_2('fr/indexNos', 'indexNos4', "Indices Laspeyres et Paasche", 'static');
addPage_2('fr/indexNos', 'indexNos5', "Dégonflage une série temporelle", 'static');

addChapter('bk/french', 'ch_cat', "Variables Catégorielles");
addSection('bk/french', 'sec_freqTable', "Tables de fréquences");
addPage_2('fr/freqTable', 'freqTable1', "Tables de fréquences", 'interact');
addPage_2('fr/freqTable', 'freqTable2', "Proportions et pourcentages", 'interact');
addPage_2('fr/freqTable', 'freqTable3', "Reconnaissant les tableaux de fréquence", 'static');
addPage_2('fr/freqTable', 'freqTable4', "Modifications aux catégories", 'interact');
addSection('bk/french', 'sec_univarCat', "Diagrammes à barres et camemberts");
addPage_2('fr/univarCat', 'univarCat1', "Diagrammes à barres", 'interact');
addPage_2('fr/univarCat', 'univarCat2', "Diagrammes de Pareto", 'interact');
addPage_2('fr/univarCat', 'univarCat3', "Chartjunk et graphiques à barres trompeuse", 'static');
addPage_2('fr/univarCat', 'univarCat4', "Graphiques à barres empilées et camemberts", 'interact');
addPage_2('fr/univarCat', 'univarCat5', "Comparaison des diagrammes à barres et camemberts", 'interact');
addPage_2('fr/univarCat', 'univarCat6', "Chartjunk pour les camemberts", 'static');
addPage_2('fr/univarCat', 'univarCat7', "Diagrammes à barres et camemberts pour des quantités", 'interact');
addSection('bk/french', 'sec_groupedCat', "En comparant des groupes");
addPage_2('fr/groupedCat', 'groupedCat1', "Tableaux de contingence", 'interact');
addPage_2('fr/groupedCat', 'groupedCat2', "Exemples de tableaux de contingence", 'static');
addPage_2('fr/groupedCat', 'groupedCat3', "Diagrammes à barres en utilisant proportions", 'interact');
addPage_2('fr/groupedCat', 'groupedCat4', "Graphiques à barres empilées", 'interact');
addPage_2('fr/groupedCat', 'groupedCat5', "Deux cas particuliers", 'interact');
addSection('bk/french', 'sec_bivarCat', "Bivariées distributions catégorielles");
addPage_2('fr/bivarCat', 'bivarCat1', "Les relations entre les variables", 'static');
addPage_2('fr/bivarCat', 'bivarCat2', "Histogrammes en 3 dimensions", 'interact');
addPage_2('fr/bivarCat', 'bivarCat3', "Graphiques à barres en cluster", 'interact');
addPage_2('fr/bivarCat', 'bivarCat4', "Distributions marginales", 'interact');
addPage_2('fr/bivarCat', 'bivarCat5', "Distributions conditionnelles", 'interact');
addPage_2('fr/bivarCat', 'bivarCat6', "En savoir plus sur les distributions conditionnelles", 'interact');
addPage_2('fr/bivarCat', 'bivarCat7', "Distns conditionnelle vs marginale", 'interact');
addSection('bk/french', 'sec_tableDisplay', "Présentation des données dans tableaux");
addPage_2('fr/tableDisplay', 'tableDisplay1', "Quadrillage et l'espace blanc", 'static');
addPage_2('fr/tableDisplay', 'tableDisplay2', "Mise en page et d'annotation", 'static');
addPage_2('fr/tableDisplay', 'tableDisplay3', "Chiffres significatifs et le bruit des données", 'interact');
addPage_2('fr/tableDisplay', 'tableDisplay4', "Variables significatives", 'interact');
addPage_2('fr/tableDisplay', 'tableDisplay5', "Permutation des lignes et des colonnes", 'static');
addPage_2('fr/tableDisplay', 'tableDisplay6', "Réorganisation des lignes", 'interact');
addPage_2('fr/tableDisplay', 'tableDisplay7', "Exemple", 'static');
addSection('bk/french', 'sec_logistic', "Régression logistique");
addPage_2('fr/logistic', 'logistic1', "Réponses catégoriques", 'interact');
addPage_2('fr/logistic', 'logistic2', "Valeurs ajustées et prédictions", 'interact');
addPage_2('fr/logistic', 'logistic3', "Courbe logistique", 'interact');
addPage_2('fr/logistic', 'logistic4', "Obtention d'un bon ajustement", 'interact');

addChapter('bk/french', 'ch_multivar', "Multivariée des données");
addSection('bk/french', 'sec_multivariate', "Affichage des données multivariées");
addPage_2('fr/multivariate', 'multivariate1', "Representing a third variable", 'interact');
addPage_2('fr/multivariate', 'multivariate2', "Rotating 3D scatterplots", 'interact');
addPage_2('fr/multivariate', 'multivariate3', "Scatterplot matrix and brushing", 'interact');
addPage_2('fr/multivariate', 'multivariate4', "Brushing example", 'interact');
addPage_2('fr/multivariate', 'multivariate5', "Slicing", 'interact');
addSection('bk/french', 'sec_regnGroups', "Groupes et régression");
addPage_2('fr/regnGroups', 'regnGroups1', "Additional variables in regression", 'interact');
addPage_2('fr/regnGroups', 'regnGroups2', "Displaying groups", 'interact');
addPage_2('fr/regnGroups', 'regnGroups3', "Regression with grouped data", 'interact');
addPage_2('fr/regnGroups', 'regnGroups4', "Parallel regression lines", 'interact');
addPage_2('fr/regnGroups', 'regnGroups5', "Transformed variables and groups", 'interact');
addPage_2('fr/regnGroups', 'regnGroups6', "Grouping with a numerical variable", 'interact');
addPage_2('fr/regnGroups', 'regnGroups7', "Scatterplot matrix with groups", 'interact');
addSection('bk/french', 'sec_multiRegn', "Régression multiple");
addPage_2('fr/multiRegn', 'multiRegn1', "More than one explanatory variable", 'interact');
addPage_2('fr/multiRegn', 'multiRegn2', "Multiple regression equation", 'interact');
addPage_2('fr/multiRegn', 'multiRegn3', "Interpreting coefficients", 'interact');
addPage_2('fr/multiRegn', 'multiRegn4', "Scatterplot of three variables", 'interact');
addPage_2('fr/multiRegn', 'multiRegn5', "Displayng the linear equation for Y vs X and Z", 'interact');
addPage_2('fr/multiRegn', 'multiRegn6', "Fitted values and residuals", 'interact');
addPage_2('fr/multiRegn', 'multiRegn7', "Least squares estimation", 'interact');
addSection('bk/french', 'sec_lurking', "Relations marginaux");
addPage_2('fr/lurking', 'lurking1', "Misleading marginal correlation", 'interact');
addPage_2('fr/lurking', 'lurking2', "Misleading marginal difference in means", 'interact');
addPage_2('fr/lurking', 'lurking3', "Simpsons paradox", 'interact');
addPage_2('fr/lurking', 'lurking4', "Other examples with lurking variables", 'static');

addChapter('bk/french', 'ch_sample', "Échantillonnage et de la variabilité");
addSection('bk/french', 'sec_popSamp', "Populations finies");
addPage_2('fr/popSamp', 'popSamp1', "Census or sample?", 'interact');
addPage_2('fr/popSamp', 'popSamp2', "Variability in a sample", 'interact');
addPage_2('fr/popSamp', 'popSamp3', "Sampling error", 'interact');
addPage_2('fr/popSamp', 'popSamp4', "Sampling error and sample size", 'interact');
addPage_2('fr/popSamp', 'popSamp5', "Sampling from finite populations", 'interact');
addPage_2('fr/popSamp', 'popSamp6', "Selecting a random sample", 'interact');
addSection('bk/french', 'sec_infPopn', "Échantillons des distributions");
addPage_2('fr/infPopn', 'infPopn1', "Data as representatives", 'static');
addPage_2('fr/infPopn', 'infPopn2', "Randomness of data", 'interact');
addPage_2('fr/infPopn', 'infPopn3', "Model to explain randomness", 'static');
addPage_2('fr/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact');
addPage_2('fr/infPopn', 'infPopn5', "Information from a single sample", 'interact');
addSection('bk/french', 'sec_probDensity', "Densité de probabilité et la probabilité");
addPage_2('fr/probDensity', 'probDensity1', "Finite populations", 'interact');
addPage_2('fr/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact');
addPage_2('fr/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact');
addPage_2('fr/probDensity', 'probDensity4', "Probability density functions", 'interact');
addPage_2('fr/probDensity', 'probDensity5', "Normal distributions", 'interact');
addPage_2('fr/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact');
addPage_2('fr/probDensity', 'probDensity7', "Properties of probability", 'static');
addSection('bk/french', 'sec_probSim', "Simulation (facultatif)");
addPage_2('fr/probSim', 'probSim1', "Probability models and simulation", 'interact');
addPage_2('fr/probSim', 'probSim2', "Simulation: Will the best team win?", 'interact');
addPage_2('fr/probSim', 'probSim3', "Is there evidence of skill in a league?", 'interact');
addPage_2('fr/probSim', 'probSim4', "Assessing unusual features in data", 'interact');
addPage_2('fr/probSim', 'probSim5', "Random numbers", 'interact');
addPage_2('fr/probSim', 'probSim6', "Generating categorical values", 'interact');
addPage_2('fr/probSim', 'probSim7', "Generating numerical values", 'interact');
addSection('bk/french', 'sec_randomMean', "Distribution des moyenne de l'échantillon");
addPage_2('fr/randomMean', 'randomMean1', "Parameters and statistics", 'interact');
addPage_2('fr/randomMean', 'randomMean2', "Variability of sample mean", 'interact');
addPage_2('fr/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact');
addPage_2('fr/randomMean', 'randomMean4', "Means from normal populations", 'interact');
addPage_2('fr/randomMean', 'randomMean5', "Large-sample normality of means", 'interact');
addPage_2('fr/randomMean', 'randomMean6', "Distribution of mean from a sample", 'static');
addPage_2('fr/randomMean', 'randomMean7', "Requirement of independence", 'interact');
addPage_2('fr/randomMean', 'randomMean8', "Sampling from finite populations", 'interact');
addSection('bk/french', 'sec_normalDistn', "Distributions normales");
addPage_2('fr/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact');
addPage_2('fr/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact');
addPage_2('fr/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact');
addPage_2('fr/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact');
addPage_2('fr/normalDistn', 'normalDistn5', "Z-scores", 'interact');
addPage_2('fr/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact');
addPage_2('fr/normalDistn', 'normalDistn7', "Other probabilities", 'interact');
addPage_2('fr/normalDistn', 'normalDistn8', "Normal tables", 'static');
addPage_2('fr/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact');
addPage_2('fr/normalDistn', 'normalDistn10', "Normal probability plots", 'interact');
addSection('bk/french', 'sec_randomPropn', "Distribution de l'échantillon proportion");
addPage_2('fr/randomPropn', 'randomPropn1', "Proportion and probability", 'interact');
addPage_2('fr/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact');
addPage_2('fr/randomPropn', 'randomPropn3', "Binomial distribution", 'interact');
addPage_2('fr/randomPropn', 'randomPropn4', "Binomial probability examples", 'static');
addPage_2('fr/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact');
addPage_2('fr/randomPropn', 'randomPropn6', "Normal approximation examples", 'static');
addSection('bk/french', 'sec_sampPractice', "Échantillonnage dans la pratique");
addPage_2('fr/sampPractice', 'sampPractice1', "Stratified sampling", 'interact');
addPage_2('fr/sampPractice', 'sampPractice2', "Cluster sampling", 'interact');
addPage_2('fr/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact');
addPage_2('fr/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static');
addPage_2('fr/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static');
addPage_2('fr/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact');
addPage_2('fr/sampPractice', 'sampPractice7', "Survey design issues", 'static');
addSection('bk/french', 'sec_controlChart', "Les cartes de contrôle");
addPage_2('fr/controlChart', 'controlChart1', "Présentation", 'static');
addPage_2('fr/controlChart', 'controlChart2', "Les graphiques de séquences", 'interact');
addPage_2('fr/controlChart', 'controlChart3', "Les limites de contrôle", 'interact');
addPage_2('fr/controlChart', 'controlChart4', "D'autres signaux d'être hors de contrôle", 'interact');
addPage_2('fr/controlChart', 'controlChart5', "Les fausses alarmes", 'interact');
addPage_2('fr/controlChart', 'controlChart6', "Exemples de cartes courir", 'interact');
addPage_2('fr/controlChart', 'controlChart7', "Les cartes de contrôle des moyens", 'interact');
addPage_2('fr/controlChart', 'controlChart8', "Les cartes de contrôle pour les gammes", 'interact');
addPage_2('fr/controlChart', 'controlChart9', "Trouver la cause des problèmes", 'interact');

addChapter('bk/french', 'ch_expDesign', "Expériences conçues");
addSection('bk/french', 'sec_causal', "Association &amp; relations causales");
addPage_2('fr/causal', 'causal1', "L'intérêt pour les relations", 'static');
addPage_2('fr/causal', 'causal2', "Relations causales et non causales", 'static');
addPage_2('fr/causal', 'causal3', "Detecting causal relationships", 'static');
addPage_2('fr/causal', 'causal4', "Les données d'observation et d'expérimentation", 'interact');
addPage_2('fr/causal', 'causal5', "La collecte des données et de la causalité", 'interact');
addSection('bk/french', 'sec_designIntro', "Principes de conception expérimentale");
addPage_2('fr/designIntro', 'designIntro1', "Experiments and treatments", 'static');
addPage_2('fr/designIntro', 'designIntro2', "Variable experimental units", 'interact');
addPage_2('fr/designIntro', 'designIntro3', "A badly designed experiment", 'interact');
addPage_2('fr/designIntro', 'designIntro4', "Confounding", 'static');
addPage_2('fr/designIntro', 'designIntro5', "Randomisation", 'interact');
addPage_2('fr/designIntro', 'designIntro6', "Replication", 'static');
addPage_2('fr/designIntro', 'designIntro7', "Blocking", 'interact');
addSection('bk/french', 'sec_pairBlock', "Jumelage et blocs");
addPage_2('fr/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact');
addPage_2('fr/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact');
addPage_2('fr/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact');
addPage_2('fr/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact');
addPage_2('fr/pairBlock', 'pairBlock5', "Randomised block experiments", 'static');
addSection('bk/french', 'sec_designTwo', "Deux ou plusieurs facteurs");
addPage_2('fr/designTwo', 'designTwo1', "Experiments with 2 factors", 'interact');
addPage_2('fr/designTwo', 'designTwo2', "Factorial design", 'static');
addPage_2('fr/designTwo', 'designTwo3', "Simple model for two factors", 'interact');
addPage_2('fr/designTwo', 'designTwo4', "Interaction between factors", 'interact');
addPage_2('fr/designTwo', 'designTwo5', "Example with interaction", 'interact');
addPage_2('fr/designTwo', 'designTwo6', "No-interaction model for three factors", 'interact');
addPage_2('fr/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact');
addSection('bk/french', 'sec_designPrelim', "Questions pratiques en matière de conception");
addPage_2('fr/designPrelim', 'designPrelim1', "Purpose", 'static');
addPage_2('fr/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static');
addPage_2('fr/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static');

addChapter('bk/french', 'ch_estimation', "L'estimation des paramètres");
addSection('bk/french', 'sec_estIntro', "Introduction à l'estimation");
addPage_2('fr/estIntro', 'estIntro1', "Interest in populations", 'static');
addPage_2('fr/estIntro', 'estIntro2', "Interest in parameters", 'static');
addPage_2('fr/estIntro', 'estIntro3', "Applications of estimation", 'static');
addPage_2('fr/estIntro', 'estIntro4', "Estimation error", 'static');
addPage_2('fr/estIntro', 'estIntro5', "Distribution of errors", 'interact');
addPage_2('fr/estIntro', 'estIntro6', "Standard error and bias", 'static');
addPage_2('fr/estIntro', 'estIntro7', "Interval estimates", 'static');
addSection('bk/french', 'sec_seMean', "L'écart de la moyenne");
addPage_2('fr/seMean', 'seMean1', "Error distribution for mean", 'interact');
addPage_2('fr/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact');
addPage_2('fr/seMean', 'seMean3', "Interpreting the standard error", 'static');
addPage_2('fr/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static');
addPage_2('fr/seMean', 'seMean5', "Standard error vs standard deviation", 'interact');
addPage_2('fr/seMean', 'seMean6', "Using SEs to compare estimators", 'interact');
addPage_2('fr/seMean', 'seMean7', "More about bias", 'interact');
addSection('bk/french', 'sec_ciMean', "Intervalle de confiance pour la moyenne");
addPage_2('fr/ciMean', 'ciMean1', "Intervalle de confiance à partir de l'erreur-type", 'static');
addPage_2('fr/ciMean', 'ciMean2', "Intervalle de confiance pour la moyenne, connu sigma", 'interact');
addPage_2('fr/ciMean', 'ciMean3', "Le niveau de confiance", 'interact');
addPage_2('fr/ciMean', 'ciMean4', "Le niveau de confiance, si sigma est remplacé par s", 'interact');
addPage_2('fr/ciMean', 'ciMean5', "Intervalle de confiance pour \u03bc, \u03c3 inconnu", 'interact');
addPage_2('fr/ciMean', 'ciMean6', "Propriétés de l'intervalle de confiance à 95%", 'interact');
addPage_2('fr/ciMean', 'ciMean7', "Exemples", 'static');
addSection('bk/french', 'sec_estPropn', "Estimation des proportions");
addPage_2('fr/estPropn', 'estPropn1', "General framework for estimation", 'static');
addPage_2('fr/estPropn', 'estPropn2', "Estimating a proportion", 'interact');
addPage_2('fr/estPropn', 'estPropn3', "Error distribution", 'interact');
addPage_2('fr/estPropn', 'estPropn4', "Normal approximation to error distribution", 'interact');
addPage_2('fr/estPropn', 'estPropn5', "Confidence interval for proportion", 'static');
addPage_2('fr/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact');
addPage_2('fr/estPropn', 'estPropn7', "Confidence interval examples", 'static');
addSection('bk/french', 'sec_ciExtra', "En savoir plus sur l'estimation");
addPage_2('fr/ciExtra', 'ciExtra1', "Marge d'erreur", 'interact');
addPage_2('fr/ciExtra', 'ciExtra2', "Taille de l'échantillon pour l'estimation signifie", 'interact');
addPage_2('fr/ciExtra', 'ciExtra3', "Taille de l'échantillon pour estimer la proportion", 'interact');
addPage_2('fr/ciExtra', 'ciExtra4', "Autres niveaux de confiance", 'interact');
addSection('bk/french', 'sec_estOther', "Simulation et bootstrap (avancé)");
addPage_2('fr/estOther', 'estOther1', "Need for simulation", 'static');
addPage_2('fr/estOther', 'estOther2', "Error distribution by simulation (advanced)", 'interact');
addPage_2('fr/estOther', 'estOther3', "Simulation from normal approximation (advanced)", 'interact');
addPage_2('fr/estOther', 'estOther4', "Bootstrap error distribution", 'interact');
addPage_2('fr/estOther', 'estOther5', "Standard error of correlation", 'interact');

addChapter('bk/french', 'ch_testing', "Tester des hypothèses");
addSection('bk/french', 'sec_testIntro', "Introduction aux tests d'hypothèses");
addPage_2('fr/testIntro', 'testIntro1', "Inference", 'static');
addPage_2('fr/testIntro', 'testIntro2', "Soccer league simulation", 'interact');
addPage_2('fr/testIntro', 'testIntro3', "Simulation to test a proportion", 'interact');
addPage_2('fr/testIntro', 'testIntro4', "Test for a mean", 'interact');
addPage_2('fr/testIntro', 'testIntro5', "Randomisation tests", 'interact');
addPage_2('fr/testIntro', 'testIntro6', "Soccer league randomisation", 'interact');
addPage_2('fr/testIntro', 'testIntro7', "Common patterns in hypothesis testing", 'static');
addSection('bk/french', 'sec_testPropn', "Test d'hypothèse pour les proportions");
addPage_2('fr/testPropn', 'testPropn1', "Inference about parameters", 'static');
addPage_2('fr/testPropn', 'testPropn2', "P-value for testing proportion", 'interact');
addPage_2('fr/testPropn', 'testPropn3', "Another example of testing a proportion", 'interact');
addPage_2('fr/testPropn', 'testPropn4', "One- and two-tailed tests", 'interact');
addPage_2('fr/testPropn', 'testPropn5', "Tests based on normal approximation", 'interact');
addPage_2('fr/testPropn', 'testPropn6', "Statistical distance", 'static');
addPage_2('fr/testPropn', 'testPropn7', "Tests based on statistical distance", 'interact');
addSection('bk/french', 'sec_testMean', "Tests d'hypothèses sur les moyens");
addPage_2('fr/testMean', 'testMean1', "Introduction", 'static');
addPage_2('fr/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static');
addPage_2('fr/testMean', 'testMean3', "P-value from statistical distance", 'interact');
addPage_2('fr/testMean', 'testMean4', "The t distribution", 'interact');
addPage_2('fr/testMean', 'testMean5', "The t test for a mean", 'interact');
addSection('bk/french', 'sec_decision', "Décisions et le niveau de signification");
addPage_2('fr/decision', 'decision1', "Hypothesis tests and decisions", 'static');
addPage_2('fr/decision', 'decision2', "Decision rules", 'interact');
addPage_2('fr/decision', 'decision3', "Significance level and p-values", 'interact');
addPage_2('fr/decision', 'decision4', "Sample size and power", 'interact');
addSection('bk/french', 'sec_testPValue', "Propriétés des valeurs p");
addPage_2('fr/testPValue', 'testPValue1', "Null and alternative hypotheses", 'interact');
addPage_2('fr/testPValue', 'testPValue2', "P-value and consistency with null hypothesis", 'interact');
addPage_2('fr/testPValue', 'testPValue3', "Distribution of p-values", 'interact');
addPage_2('fr/testPValue', 'testPValue4', "Interpretation of a p-value", 'interact');
addPage_2('fr/testPValue', 'testPValue5', "P-values for other tests", 'interact');

addChapter('bk/french', 'ch_twoGroups', "En comparant des groupes");
addSection('bk/french', 'sec_twoGroupModel', "Modèles pour deux groupes");
addPage_2('fr/twoGroupModel', 'twoGroupModel1', "Interest in underlying population", 'static');
addPage_2('fr/twoGroupModel', 'twoGroupModel2', "Model for two groups", 'interact');
addPage_2('fr/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact');
addPage_2('fr/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact');
addPage_2('fr/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact');
addSection('bk/french', 'sec_sumDiff', "Distribution des sommes et des différences");
addPage_2('fr/sumDiff', 'sumDiff1', "Means and sums of random samples", 'interact');
addPage_2('fr/sumDiff', 'sumDiff2', "Sum and differences", 'interact');
addPage_2('fr/sumDiff', 'sumDiff3', "Sums and differences (cont)", 'interact');
addPage_2('fr/sumDiff', 'sumDiff4', "Probabilities for sums and differences", 'static');
addSection('bk/french', 'sec_twoGroupInf', "En comparant les moyens en deux groupes");
addPage_2('fr/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact');
addPage_2('fr/twoGroupInf', 'twoGroupInf2', "Distribution of estimation error", 'static');
addPage_2('fr/twoGroupInf', 'twoGroupInf3', "CI for difference between means", 'interact');
addPage_2('fr/twoGroupInf', 'twoGroupInf4', "Testing a hypothesis", 'interact');
addPage_2('fr/twoGroupInf', 'twoGroupInf5', "One-tailed tests for differences", 'interact');
addSection('bk/french', 'sec_twoGroupPropn', "Comparaison de deux proportions");
addPage_2('fr/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact');
addPage_2('fr/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact');
addPage_2('fr/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static');
addPage_2('fr/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static');
addSection('bk/french', 'sec_testPaired', "Test t apparié");
addPage_2('fr/testPaired', 'testPaired1', "Paired data examples", 'static');
addPage_2('fr/testPaired', 'testPaired2', "Analysis of differences", 'interact');
addPage_2('fr/testPaired', 'testPaired3', "Paired t-test", 'interact');
addPage_2('fr/testPaired', 'testPaired4', "Pairing and experimental design", 'interact');
addSection('bk/french', 'sec_multiGroup', "En comparant plusieurs moyensmeans");
addPage_2('fr/multiGroup', 'multiGroup1', "Model with common standard deviation", 'interact');
addPage_2('fr/multiGroup', 'multiGroup2', "Estimate of common standard deviation", 'interact');
addPage_2('fr/multiGroup', 'multiGroup3', "Inference about two groups", 'static');
addPage_2('fr/multiGroup', 'multiGroup4', "Assessing differences between groups", 'interact');
addPage_2('fr/multiGroup', 'multiGroup5', "Sums of squares", 'interact');
addPage_2('fr/multiGroup', 'multiGroup6', "Coefficient of determination", 'static');
addPage_2('fr/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact');
addPage_2('fr/multiGroup', 'multiGroup8', "Examples", 'static');
addSection('bk/french', 'sec_randBlock', "Blocs randomisés");
addPage_2('fr/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static');
addPage_2('fr/randBlock', 'randBlock2', "Importance of using block information", 'interact');
addPage_2('fr/randBlock', 'randBlock3', "Data with no baseline treatment", 'interact');
addPage_2('fr/randBlock', 'randBlock4', "Randomised block designs", 'interact');
addPage_2('fr/randBlock', 'randBlock5', "Model for randomised blocks", 'interact');
addPage_2('fr/randBlock', 'randBlock6', "Removing block effects", 'interact');
addPage_2('fr/randBlock', 'randBlock7', "Sums of squares", 'interact');
addPage_2('fr/randBlock', 'randBlock8', "Anova table and examples", 'static');

addChapter('bk/french', 'ch_regnInference', "Régression inférence");
addSection('bk/french', 'sec_regnModel', "Modèles de régression linéaires");
addPage_2('fr/regnModel', 'regnModel1', "Interest in generalising from data", 'interact');
addPage_2('fr/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact');
addPage_2('fr/regnModel', 'regnModel3', "Normal linear model", 'interact');
addPage_2('fr/regnModel', 'regnModel4', "Errors and 95% band on scatterplot", 'interact');
addPage_2('fr/regnModel', 'regnModel5', "Model parameters", 'interact');
addSection('bk/french', 'sec_regnEst', "Estimation des paramètres");
addPage_2('fr/regnEst', 'regnEst1', "Point estimates of slope and intercept", 'interact');
addPage_2('fr/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact');
addPage_2('fr/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact');
addPage_2('fr/regnEst', 'regnEst4', "Standard error of least squares slope", 'static');
addPage_2('fr/regnEst', 'regnEst5', "95% confidence interval for slope", 'static');
addPage_2('fr/regnEst', 'regnEst6', "Properties of confidence interval", 'interact');
addPage_2('fr/regnEst', 'regnEst7', "Influences on accuracy", 'interact');
addSection('bk/french', 'sec_regnTest', "Paramètres tests de régression");
addPage_2('fr/regnTest', 'regnTest1', "Importance of zero slope", 'interact');
addPage_2('fr/regnTest', 'regnTest2', "Testing whether slope is zero", 'static');
addPage_2('fr/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static');
addPage_2('fr/regnTest', 'regnTest4', "Properties of p-values", 'interact');
addSection('bk/french', 'sec_regnPred', "Prédire la réponse");
addPage_2('fr/regnPred', 'regnPred1', "Estimated response distn at X", 'interact');
addPage_2('fr/regnPred', 'regnPred2', "Variability of estimate at X", 'interact');
addPage_2('fr/regnPred', 'regnPred3', "Estimating the mean vs prediction", 'interact');
addPage_2('fr/regnPred', 'regnPred4', "Confidence and prediction intervals", 'interact');
addSection('bk/french', 'sec_regnProblem', "Hypothèses de modèle linéaire");
addPage_2('fr/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact');
addPage_2('fr/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact');
addPage_2('fr/regnProblem', 'regnProblem3', "Curvature and non-constant variance &mdash; transforming Y", 'interact');
addPage_2('fr/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact');
addPage_2('fr/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact');
addPage_2('fr/regnProblem', 'regnProblem6', "Non-normal errors", 'interact');
addPage_2('fr/regnProblem', 'regnProblem7', "Correlated errors", 'interact');

addChapter('bk/french', 'ch_independence', "Indépendance");
addSection('bk/french', 'sec_prob', "Probabilités et applications");
addPage_2('fr/prob', 'prob1', "Joint probabilities", 'interact');
addPage_2('fr/prob', 'prob2', "Marginal probabilities", 'interact');
addPage_2('fr/prob', 'prob3', "Conditional probabilities", 'interact');
addPage_2('fr/prob', 'prob4', "Graphical display of probabilities", 'interact');
addPage_2('fr/prob', 'prob5', "Calculations with probabilities", 'interact');
addSection('bk/french', 'sec_indep', "Indépendence");
addPage_2('fr/indep', 'indep1', "Association between categorical variables", 'static');
addPage_2('fr/indep', 'indep2', "Independence of categorical variables", 'interact');
addPage_2('fr/indep', 'indep3', "Independence from samples", 'static');
addPage_2('fr/indep', 'indep4', "Testing for independence", 'interact');
addPage_2('fr/indep', 'indep5', "Chi-squared test statistic", 'interact');
addPage_2('fr/indep', 'indep6', "P-value for chi-squared test", 'interact');
addPage_2('fr/indep', 'indep7', "Examples", 'static');
addPage_2('fr/indep', 'indep8', "Comparing groups", 'static');

var language = "fr";
var logoGif = null;
var homeDir = "bk/french";
var versionGif = "images/castFrench";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = false;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "14";

var localVideos = true;

var fullTextString = 'Complet';
var summaryTextString = 'Résumé';
var videoTextString = 'Video';
var appletTextString = 'Complet';
fullTabTooltip = 'Full version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Interactive version of page';
var chapterString = 'Chapitre';

var versionName = {'_g': 'Général', '_b': 'Biométrique', '_c': 'Business', '_m': 'Climatiques', '_o': 'Stats officielles', '_a': 'Africaine', '_z': 'Autres'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['structures4'] = new Array('_g', '_a', '_c');
versions['structures5'] = new Array('_g', '_b', '_c');
versions['structures6'] = new Array('_g', '_b');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_g', '_b', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('_g', '_a', '_b', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['valueDisplay7'] = new Array('_g', '_c', '_m');
versions['displayInterp1'] = new Array('_g', '_b', '_c');
versions['displayInterp2'] = new Array('_g', '_b', '_c', '_m');
versions['displayInterp3'] = new Array('_g', '_c', '_m');
versions['displayInterp4'] = new Array('_g', '_b');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density7'] = new Array('_g', '_b', '_c', '_m');
versions['density9'] = new Array('_g', '_c');
versions['density10'] = new Array('_g', '_c', '_m');
versions['density11'] = new Array('_g', '_b', '_c', '_m');
versions['boxPlot6'] = new Array('_g', '_c');
versions['boxPlot7'] = new Array('_g', '_b');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['transform1'] = new Array('_g', '_b');
versions['transform2'] = new Array('_g', '_b', '_c');
versions['transform3'] = new Array('_g', '_c');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['counts4'] = new Array('_g', '_b', '_c');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship2'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['timePlot1'] = new Array('_g', '_b', '_c');
versions['timePlot2'] = new Array('_g', '_b', '_c');
versions['seasonal1'] = new Array('_g', '_m', '_z');
versions['seasonal2'] = new Array('_g', '_m', '_z');
versions['seasonal3'] = new Array('_g', '_m', '_z');
versions['seasonal4'] = new Array('_g', '_m', '_z');
versions['seasonal5'] = new Array('_g', '_m', '_z');
versions['seasonal6'] = new Array('_g', '_m', '_z');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat3'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['univarCat5'] = new Array('_g', '_b', '_c');
versions['univarCat6'] = new Array('_g', '_b', '_c');
versions['univarCat7'] = new Array('_g', '_b');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['groupedCat3'] = new Array('_g', '_b', '_c');
versions['groupedCat4'] = new Array('_g', '_b', '_c');
versions['groupedCat5'] = new Array('_g', '_b', '_c');
versions['bivarCat1'] = new Array('_g', '_b', '_c');
versions['tableDisplay1'] = new Array('_g', '_a');
versions['logistic1'] = new Array('_g', '_b', '_c');
versions['logistic2'] = new Array('_g', '_b', '_c');
versions['logistic4'] = new Array('_g', '_b', '_c');
versions['multivariate1'] = new Array('_g', '_b', '_c');
versions['multivariate2'] = new Array('_g', '_c');
versions['multivariate3'] = new Array('_g', '_c');
versions['multivariate5'] = new Array('_g', '_c');
versions['regnGroups7'] = new Array('_g', '_c');
versions['lurking1'] = new Array('_g', '_b', '_c');
versions['lurking2'] = new Array('_g', '_b');
versions['lurking3'] = new Array('_g', '_c');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b', '_c');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['probSim4'] = new Array('_g', '_b', '_c');
versions['probSim6'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_g', '_b', '_c');
versions['randomMean6'] = new Array('_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');
versions['sampPractice1'] = new Array('_g', '_b');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['pairBlock5'] = new Array('_g', '_b');
versions['designTwo1'] = new Array('_g', '_b');
versions['designTwo2'] = new Array('_g', '_b');
versions['designTwo6'] = new Array('_g', '_b');
versions['designPrelim2'] = new Array('_g', '_c');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');
versions['estOther3'] = new Array('_g', '_c', '_m');
versions['estOther5'] = new Array('_g', '_b');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro3'] = new Array('_g', '_b', '_c');
versions['testIntro5'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_g', '_b', '_c');
versions['testPropn1'] = new Array('_g', '_b', '_c');
versions['testPropn2'] = new Array('_g', '_b', '_c');
versions['testPropn3'] = new Array('_g', '_b', '_c');
versions['testPropn4'] = new Array('_g', '_b', '_c');
versions['testPropn5'] = new Array('_g', '_b');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_g', '_b', '_c');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['testPValue1'] = new Array('_g', '_c');
versions['testPValue2'] = new Array('_g', '_b', '_c');
versions['testPValue5'] = new Array('_g', '_b', '_c');
versions['twoGroupModel1'] = new Array('_g', '_b', '_c');
versions['twoGroupModel2'] = new Array('_g', '_b', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['twoGroupInf3'] = new Array('_g', '_b', '_c');
versions['twoGroupInf4'] = new Array('_g', '_b', '_c');
versions['twoGroupInf5'] = new Array('_g', '_b', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_g', '_b', '_c');
versions['testPaired2'] = new Array('_g', '_b', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_g', '_b', '_c');
versions['multiGroup3'] = new Array('_g', '_b', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_g', '_a', '_b', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_g', '_b', '_c');
versions['regnModel1'] = new Array('_g', '_b', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_g', '_b', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_g', '_b', '_c');
versions['regnPred3'] = new Array('_g', '_b', '_c');
versions['regnPred4'] = new Array('_g', '_b');
versions['regnProblem3'] = new Array('_g', '_b');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['prob5'] = new Array('_g', '_c');
versions['indep1'] = new Array('_g', '_b', '_c');
versions['indep2'] = new Array('_g', '_c');
versions['indep3'] = new Array('_g', '_c');
versions['indep4'] = new Array('_g', '_c');
versions['indep7'] = new Array('_g', '_c');
versions['indep8'] = new Array('_g', '_c');

bookLoaded = true;
