
addBook('bk/mathStats', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Recent changes to CAST", 'static');

addChapter('bk/mathStats', 'ch_probability', "Probability");
addSection('bk/mathStats', 'sec_probDefinitions', "Ways to define probability");
addPage_2('en/probDefinitions', 'probDefinitions1', "Uncertainty and Probability", 'static', 'en/probDefinitions', 's_probDefinitions1', 'en/probDefinitions', 'v_probDefinitions1');
addPage_2('en/probDefinitions', 'probDefinitions2', "Terminology", 'static', 'en/probDefinitions', 's_probDefinitions2', 'en/probDefinitions', 'v_probDefinitions2');
addPage_2('en/probDefinitions', 'probDefinitions3', "Classical definition of probability", 'interact', 'en/probDefinitions', 's_probDefinitions3', 'en/probDefinitions', 'v_probDefinitions3');
addPage_2('en/probDefinitions', 'probDefinitions4', "Applications of classical definition", 'static', 'en/probDefinitions', 's_probDefinitions4', 'en/probDefinitions', 'v_probDefinitions4');
addPage_2('en/probDefinitions', 'probDefinitions5', "Probability from relative frequency", 'interact', 'en/probDefinitions', 's_probDefinitions5', 'en/probDefinitions', 'v_probDefinitions5');
addPage_2('en/probDefinitions', 'probDefinitions6', "Estimating probabilities", 'static', 'en/probDefinitions', 's_probDefinitions6', 'en/probDefinitions', 'v_probDefinitions6');
addPage_2('en/probDefinitions', 'probDefinitions7', "Subjective probability", 'static', 'en/probDefinitions', 's_probDefinitions7', 'en/probDefinitions', 'v_probDefinitions7');
addSection('bk/mathStats', 'sec_probRules', "Probability calculations");
addPage_2('en/probRules', 'probRules1', "Core rules of probability", 'static', 'en/probRules', 's_probRules1', 'en/probRules', 'v_probRules1');
addPage_2('en/probRules', 'probRules2', "A few properties of probability", 'static', 'en/probRules', 's_probRules2', 'en/probRules', 'v_probRules2');
addPage_2('en/probRules', 'probRules3', "Examples", 'static', 'en/probRules', 's_probRules3', 'en/probRules', 'v_probRules3');
addSection('bk/mathStats', 'sec_probCondit', "Conditional probability");
addPage_2('en/probCondit', 'probCondit1', "Conditional probability", 'static', 'en/probCondit', 's_probCondit1', 'en/probCondit', 'v_probCondit1');
addPage_2('en/probCondit', 'probCondit2', "Graphical display of probabilities", 'interact', 'en/probCondit', 's_probCondit2', 'en/probCondit', 'v_probCondit2');
addPage_2('en/probCondit', 'probCondit3', "Partitions of the sample space", 'interact', 'en/probCondit', 's_probCondit3', 'en/probCondit', 'v_probCondit3');
addPage_2('en/probCondit', 'probCondit4', "Tree diagrams", 'static', 'en/probCondit', 's_probCondit4', 'en/probCondit', 'v_probCondit4');
addPage_2('en/probCondit', 'probCondit5', "More about tree diagrams", 'static', 'en/probCondit', 's_probCondit5', 'en/probCondit', 'v_probCondit5');
addPage_2('en/probCondit', 'probCondit6', "Independence", 'static', 'en/probCondit', 's_probCondit6', 'en/probCondit', 'v_probCondit6');
addPage_2('en/probCondit', 'probCondit7', "Law of total probability", 'static', 'en/probCondit', 's_probCondit7', 'en/probCondit', 'v_probCondit7');
addPage_2('en/probCondit', 'probCondit8', "Bayes theorem", 'interact', 'en/probCondit', 's_probCondit8', 'en/probCondit', 'v_probCondit8');

addChapter('bk/mathStats', 'ch_distributions', "Random Variables");
addSection('bk/mathStats', 'sec_discreteDistns', "Discrete random variables");
addPage_2('en/discreteDistns', 'discreteDistns1', "Discrete distributions", 'static', 'en/discreteDistns', 's_discreteDistns1', 'en/discreteDistns', 'v_discreteDistns1');
addPage_2('en/discreteDistns', 'discreteDistns2', "Cumulative distribution function", 'interact', 'en/discreteDistns', 's_discreteDistns2', 'en/discreteDistns', 'v_discreteDistns2');
addPage_2('en/discreteDistns', 'discreteDistns3', "Mean", 'static', 'en/discreteDistns', 's_discreteDistns3', 'en/discreteDistns', 'v_discreteDistns3');
addPage_2('en/discreteDistns', 'discreteDistns4', "Expected values", 'static', 'en/discreteDistns', 's_discreteDistns4', 'en/discreteDistns', 'v_discreteDistns4');
addPage_2('en/discreteDistns', 'discreteDistns5', "Variance", 'static', 'en/discreteDistns', 's_discreteDistns5', 'en/discreteDistns', 'v_discreteDistns5');
addSection('bk/mathStats', 'sec_continuousDistns', "Continuous random variables");
addPage_2('en/continuousDistns', 'continuousDistns1', "Probability density functions", 'interact', 'en/continuousDistns', 's_continuousDistns1', 'en/continuousDistns', 'v_continuousDistns1');
addPage_2('en/continuousDistns', 'continuousDistns2', "Probability and area", 'interact', 'en/continuousDistns', 's_continuousDistns2', 'en/continuousDistns', 'v_continuousDistns2');
addPage_2('en/continuousDistns', 'continuousDistns3', "Mean and variance", 'static', 'en/continuousDistns', 's_continuousDistns3', 'en/continuousDistns', 'v_continuousDistns3');
addPage_2('en/continuousDistns', 'continuousDistns4', "Normal distributions", 'interact', 'en/continuousDistns', 's_continuousDistns4', 'en/continuousDistns', 'v_continuousDistns4');
addPage_2('en/continuousDistns', 'continuousDistns5', "Important normal quantiles", 'interact', 'en/continuousDistns', 's_continuousDistns5', 'en/continuousDistns', 'v_continuousDistns5');
addSection('bk/mathStats', 'sec_randomSample', "Discrete random samples");
addPage_2('en/randomSample', 'randomSample1', "Independence", 'static', 'en/randomSample', 's_randomSample1', 'en/randomSample', 'v_randomSample1');
addPage_2('en/randomSample', 'randomSample2', "Random samples", 'static', 'en/randomSample', 's_randomSample2', 'en/randomSample', 'v_randomSample2');
addPage_2('en/randomSample', 'randomSample3', "Functions of two variables", 'static', 'en/randomSample', 's_randomSample3', 'en/randomSample', 'v_randomSample3');
addPage_2('en/randomSample', 'randomSample4', "Properties of sums and means", 'static', 'en/randomSample', 's_randomSample4', 'en/randomSample', 'v_randomSample4');
addPage_2('en/randomSample', 'randomSample5', "Central limit theorem", 'static', 'en/randomSample', 's_randomSample5', 'en/randomSample', 'v_randomSample5');
addSection('bk/mathStats', 'sec_uniform', "Uniform distribution");
addPage_2('en/uniform', 'uniform1', "Family of uniform distributions", 'static', 'en/uniform', 's_uniform1', 'en/uniform', 'v_uniform1');
addPage_2('en/uniform', 'uniform2', "Mean and variance", 'static', 'en/uniform', 's_uniform2', 'en/uniform', 'v_uniform2');
addPage_2('en/uniform', 'uniform3', "Sample mean", 'interact', 'en/uniform', 's_uniform3', 'en/uniform', 'v_uniform3');

addChapter('bk/mathStats', 'ch_bernoulliTrials', "Successes and Failures");
addSection('bk/mathStats', 'sec_bernoulli', "Bernoulli distribution");
addPage_2('en/bernoulli', 'bernoulli1', "Bernoulli trials", 'static', 'en/bernoulli', 's_bernoulli1', 'en/bernoulli', 'v_bernoulli1');
addPage_2('en/bernoulli', 'bernoulli2', "Mean and variance", 'static', 'en/bernoulli', 's_bernoulli2', 'en/bernoulli', 'v_bernoulli2');
addSection('bk/mathStats', 'sec_binomial', "Binomial distribution");
addPage_2('en/binomial', 'binomial1', "Binomial random variable", 'static', 'en/binomial', 's_binomial1', 'en/binomial', 'v_binomial1');
addPage_2('en/binomial', 'binomial2', "Binomial probability function", 'static', 'en/binomial', 's_binomial2', 'en/binomial', 'v_binomial2');
addPage_2('en/binomial', 'binomial3', "Mean and variance", 'static', 'en/binomial', 's_binomial3', 'en/binomial', 'v_binomial3');
addPage_2('en/binomial', 'binomial4', "Shape of the binomial distribution", 'interact', 'en/binomial', 's_binomial4', 'en/binomial', 'v_binomial4');
addPage_2('en/binomial', 'binomial5', "Binomial examples", 'static', 'en/binomial', 's_binomial5', 'en/binomial', 'v_binomial5');
addPage_2('en/binomial', 'binomial6', "Cumulative probabilities", 'interact', 'en/binomial', 's_binomial6', 'en/binomial', 'v_binomial6');
addSection('bk/mathStats', 'sec_geometric', "Geometric distribution");
addPage_2('en/geometric', 'geometric1', "Geometric random variable", 'interact', 'en/geometric', 's_geometric1', 'en/geometric', 'v_geometric1');
addPage_2('en/geometric', 'geometric2', "Cumulative distribution function", 'interact', 'en/geometric', 's_geometric2', 'en/geometric', 'v_geometric2');
addPage_2('en/geometric', 'geometric3', "Examples", 'static', 'en/geometric', 's_geometric3', 'en/geometric', 'v_geometric3');
addPage_2('en/geometric', 'geometric4', "Mean and variance", 'static', 'en/geometric', 's_geometric4', 'en/geometric', 'v_geometric4');
addSection('bk/mathStats', 'sec_negBinomial', "Negative binomial distribution");
addPage_2('en/negBinomial', 'negBinomial1', "Probability function", 'interact', 'en/negBinomial', 's_negBinomial1', 'en/negBinomial', 'v_negBinomial1');
addPage_2('en/negBinomial', 'negBinomial2', "Alternative form", 'static', 'en/negBinomial', 's_negBinomial2', 'en/negBinomial', 'v_negBinomial2');
addPage_2('en/negBinomial', 'negBinomial3', "Finding negative binomial probabilities", 'static', 'en/negBinomial', 's_negBinomial3', 'en/negBinomial', 'v_negBinomial3');
addPage_2('en/negBinomial', 'negBinomial4', "Cumulative distribution function", 'static', 'en/negBinomial', 's_negBinomial4', 'en/negBinomial', 'v_negBinomial4');
addPage_2('en/negBinomial', 'negBinomial5', "Mean and variance", 'static', 'en/negBinomial', 's_negBinomial5', 'en/negBinomial', 'v_negBinomial5');

addChapter('bk/mathStats', 'ch_esimation', "Estimating a Parameter");
addSection('bk/mathStats', 'sec_estimation', "Estimation");
addPage_2('en/estimation', 'estimation1', "Unknown parameters", 'static', 'en/estimation', 's_estimation1', 'en/estimation', 'v_estimation1');
addPage_2('en/estimation', 'estimation2', "Estimators of parameters", 'static', 'en/estimation', 's_estimation2', 'en/estimation', 'v_estimation2');
addPage_2('en/estimation', 'estimation3', "Bias", 'static', 'en/estimation', 's_estimation3', 'en/estimation', 'v_estimation3');
addPage_2('en/estimation', 'estimation4', "Standard error", 'interact', 'en/estimation', 's_estimation4', 'en/estimation', 'v_estimation4');
addPage_2('en/estimation', 'estimation5', "Mean squared error", 'static', 'en/estimation', 's_estimation5', 'en/estimation', 'v_estimation5');
addPage_2('en/estimation', 'estimation6', "Consistency", 'static', 'en/estimation', 's_estimation6', 'en/estimation', 'v_estimation6');
addPage_2('en/estimation', 'estimation7', "Sample mean or median?", 'interact', 'en/estimation', 's_estimation7', 'en/estimation', 'v_estimation7');
addSection('bk/mathStats', 'sec_methodOfMoments', "Method of moments");
addPage_2('en/methodOfMoments', 'methodOfMoments1', "The method of moments", 'interact', 'en/methodOfMoments', 's_methodOfMoments1', 'en/methodOfMoments', 'v_methodOfMoments1');
addPage_2('en/methodOfMoments', 'methodOfMoments2', "Examples", 'static', 'en/methodOfMoments', 's_methodOfMoments2', 'en/methodOfMoments', 'v_methodOfMoments2');
addSection('bk/mathStats', 'sec_maxLikelihood', "Maximum likelihood");
addPage_2('en/maxLikelihood', 'maxLikelihood1', "Likelihood function", 'interact', 'en/maxLikelihood', 's_maxLikelihood1', 'en/maxLikelihood', 'v_maxLikelihood1');
addPage_2('en/maxLikelihood', 'maxLikelihood2', "Maximising the likelihood", 'interact', 'en/maxLikelihood', 's_maxLikelihood2', 'en/maxLikelihood', 'v_maxLikelihood2');
addPage_2('en/maxLikelihood', 'maxLikelihood3', "Examples", 'interact', 'en/maxLikelihood', 's_maxLikelihood3', 'en/maxLikelihood', 'v_maxLikelihood3');
addSection('bk/mathStats', 'sec_asymptoticMle', "Asymptotic properties of MLEs");
addPage_2('en/asymptoticMle', 'asymptoticMle1', "Bias, variance and normality", 'static', 'en/asymptoticMle', 's_asymptoticMle1', 'en/asymptoticMle', 'v_asymptoticMle1');
addPage_2('en/asymptoticMle', 'asymptoticMle2', "Standard error", 'static', 'en/asymptoticMle', 's_asymptoticMle2', 'en/asymptoticMle', 'v_asymptoticMle2');
addPage_2('en/asymptoticMle', 'asymptoticMle3', "Examples", 'static', 'en/asymptoticMle', 's_asymptoticMle3', 'en/asymptoticMle', 'v_asymptoticMle3');
addSection('bk/mathStats', 'sec_newtonRaphson', "Numerical methods for MLEs");
addPage_2('en/newtonRaphson', 'newtonRaphson1', "Newton-Raphson algorithm", 'static', 'en/newtonRaphson', 's_newtonRaphson1', 'en/newtonRaphson', 'v_newtonRaphson1');
addPage_2('en/newtonRaphson', 'newtonRaphson2', "Log-series distribution", 'interact', 'en/newtonRaphson', 's_newtonRaphson2', 'en/newtonRaphson', 'v_newtonRaphson2');
addPage_2('en/newtonRaphson', 'newtonRaphson3', "Standard error", 'interact', 'en/newtonRaphson', 's_newtonRaphson3', 'en/newtonRaphson', 'v_newtonRaphson3');
addSection('bk/mathStats', 'sec_confidenceIntervals', "Confidence intervals");
addPage_2('en/confidenceIntervals', 'confidenceIntervals1', "Interval estimates", 'static', 'en/confidenceIntervals', 's_confidenceIntervals1', 'en/confidenceIntervals', 'v_confidenceIntervals1');
addPage_2('en/confidenceIntervals', 'confidenceIntervals2', "Distribution of estimation error", 'static', 'en/confidenceIntervals', 's_confidenceIntervals2', 'en/confidenceIntervals', 'v_confidenceIntervals2');
addPage_2('en/confidenceIntervals', 'confidenceIntervals3', "Confidence intervals", 'static', 'en/confidenceIntervals', 's_confidenceIntervals3', 'en/confidenceIntervals', 'v_confidenceIntervals3');
addPage_2('en/confidenceIntervals', 'confidenceIntervals4', "Other examples", 'static', 'en/confidenceIntervals', 's_confidenceIntervals4', 'en/confidenceIntervals', 'v_confidenceIntervals4');
addPage_2('en/confidenceIntervals', 'confidenceIntervals5', "Properties of confidence intervals", 'interact', 'en/confidenceIntervals', 's_confidenceIntervals5', 'en/confidenceIntervals', 'v_confidenceIntervals5');

addChapter('bk/mathStats', 'ch_continuous', "Continuous Distributions");
addSection('bk/mathStats', 'sec_continuousProbs', "Finding probabilities");
addPage_2('en/continuousProbs', 'continuousProbs1', "Probabilities by integration", 'interact', 'en/continuousProbs', 's_continuousProbs1', 'en/continuousProbs', 'v_continuousProbs1');
addPage_2('en/continuousProbs', 'continuousProbs2', "Rectangular distribution", 'static', 'en/continuousProbs', 's_continuousProbs2', 'en/continuousProbs', 'v_continuousProbs2');
addPage_2('en/continuousProbs', 'continuousProbs3', "Other examples", 'static', 'en/continuousProbs', 's_continuousProbs3', 'en/continuousProbs', 'v_continuousProbs3');
addPage_2('en/continuousProbs', 'continuousProbs4', "Cumulative distribution function", 'static', 'en/continuousProbs', 's_continuousProbs4', 'en/continuousProbs', 'v_continuousProbs4');
addPage_2('en/continuousProbs', 'continuousProbs5', "Quantiles", 'static', 'en/continuousProbs', 's_continuousProbs5', 'en/continuousProbs', 'v_continuousProbs5');
addSection('bk/mathStats', 'sec_continuousMeanVar', "Mean and variance");
addPage_2('en/continuousMeanVar', 'continuousMeanVar1', "Expected values", 'static', 'en/continuousMeanVar', 's_continuousMeanVar1', 'en/continuousMeanVar', 'v_continuousMeanVar1');
addPage_2('en/continuousMeanVar', 'continuousMeanVar2', "Mean and variance", 'static', 'en/continuousMeanVar', 's_continuousMeanVar2', 'en/continuousMeanVar', 'v_continuousMeanVar2');
addPage_2('en/continuousMeanVar', 'continuousMeanVar3', "Example", 'static', 'en/continuousMeanVar', 's_continuousMeanVar3', 'en/continuousMeanVar', 'v_continuousMeanVar3');
addSection('bk/mathStats', 'sec_continuousSamples', "Random samples");
addPage_2('en/continuousSamples', 'continuousSamples1', "Independence and random samples", 'static', 'en/continuousSamples', 's_continuousSamples1', 'en/continuousSamples', 'v_continuousSamples1');
addPage_2('en/continuousSamples', 'continuousSamples2', "Distribution of sample sum and mean", 'static', 'en/continuousSamples', 's_continuousSamples2', 'en/continuousSamples', 'v_continuousSamples2');
addSection('bk/mathStats', 'sec_continuousEst', "Estimating parameters");
addPage_2('en/continuousEst', 'continuousEst1', "Bias and standard error", 'static', 'en/continuousEst', 's_continuousEst1', 'en/continuousEst', 'v_continuousEst1');
addPage_2('en/continuousEst', 'continuousEst2', "Method of moments", 'static', 'en/continuousEst', 's_continuousEst2', 'en/continuousEst', 'v_continuousEst2');
addPage_2('en/continuousEst', 'continuousEst3', "Maximum likelihood", 'static', 'en/continuousEst', 's_continuousEst3', 'en/continuousEst', 'v_continuousEst3');
addPage_2('en/continuousEst', 'continuousEst4', "Properties of maximum likelihood estimators", 'static', 'en/continuousEst', 's_continuousEst4', 'en/continuousEst', 'v_continuousEst4');
addPage_2('en/continuousEst', 'continuousEst5', "Confidence intervals", 'static', 'en/continuousEst', 's_continuousEst5', 'en/continuousEst', 'v_continuousEst5');
addPage_2('en/continuousEst', 'continuousEst6', "Example: normal distribution mean", 'interact', 'en/continuousEst', 's_continuousEst6', 'en/continuousEst', 'v_continuousEst6');
addPage_2('en/continuousEst', 'continuousEst7', "Example: Rectangular maximum", 'interact', 'en/continuousEst', 's_continuousEst7', 'en/continuousEst', 'v_continuousEst7');

addChapter('bk/mathStats', 'ch_eventsInTime', "Events in Time");
addSection('bk/mathStats', 'sec_poisson', "Poisson distribution");
addPage_2('en/poisson', 'poisson1', "Poisson process", 'static', 'en/poisson', 's_poisson1', 'en/poisson', 'v_poisson1');
addPage_2('en/poisson', 'poisson2', "Events in fixed time", 'interact', 'en/poisson', 's_poisson2', 'en/poisson', 'v_poisson2');
addPage_2('en/poisson', 'poisson3', "Poisson probability function", 'interact', 'en/poisson', 's_poisson3', 'en/poisson', 'v_poisson3');
addPage_2('en/poisson', 'poisson4', "Mean and variance", 'static', 'en/poisson', 's_poisson4', 'en/poisson', 'v_poisson4');
addPage_2('en/poisson', 'poisson5', "Example", 'static', 'en/poisson', 's_poisson5', 'en/poisson', 'v_poisson5');
addPage_2('en/poisson', 'poisson6', "Maximum likelihood", 'static', 'en/poisson', 's_poisson6', 'en/poisson', 'v_poisson6');
addPage_2('en/poisson', 'poisson7', "Confidence interval for rate", 'static', 'en/poisson', 's_poisson7', 'en/poisson', 'v_poisson7');
addSection('bk/mathStats', 'sec_exponential', "Exponential distribution");
addPage_2('en/exponential', 'exponential1', "Time until first event", 'interact', 'en/exponential', 's_exponential1', 'en/exponential', 'v_exponential1');
addPage_2('en/exponential', 'exponential2', "Other exponential probabilities", 'static', 'en/exponential', 's_exponential2', 'en/exponential', 'v_exponential2');
addPage_2('en/exponential', 'exponential3', "Gamma functions", 'static', 'en/exponential', 's_exponential3', 'en/exponential', 'v_exponential3');
addPage_2('en/exponential', 'exponential4', "Mean and variance", 'static', 'en/exponential', 's_exponential4', 'en/exponential', 'v_exponential4');
addPage_2('en/exponential', 'exponential5', "Maximum likelihood", 'static', 'en/exponential', 's_exponential5', 'en/exponential', 'v_exponential5');
addPage_2('en/exponential', 'exponential6', "Confidence intervals", 'static', 'en/exponential', 's_exponential6', 'en/exponential', 'v_exponential6');
addSection('bk/mathStats', 'sec_lifetimes', "Lifetimes");
addPage_2('en/lifetimes', 'lifetimes1', "Survivor and hazard functions", 'static', 'en/lifetimes', 's_lifetimes1', 'en/lifetimes', 'v_lifetimes1');
addPage_2('en/lifetimes', 'lifetimes2', "Relationship to Poisson process", 'static', 'en/lifetimes', 's_lifetimes2', 'en/lifetimes', 'v_lifetimes2');
addSection('bk/mathStats', 'sec_erlang', "Time until k'th event");
addPage_2('en/erlang', 'erlang1', "Erlang distribution", 'static', 'en/erlang', 's_erlang1', 'en/erlang', 'v_erlang1');
addPage_2('en/erlang', 'erlang2', "Mean and variance", 'static', 'en/erlang', 's_erlang2', 'en/erlang', 'v_erlang2');
addPage_2('en/erlang', 'erlang3', "Probabilities", 'static', 'en/erlang', 's_erlang3', 'en/erlang', 'v_erlang3');

addChapter('bk/mathStats', 'ch_moreFlexibleModels', "Some Flexible Models");
addSection('bk/mathStats', 'sec_overdispersion', "Over-dispersion of counts");
addPage_2('en/overdispersion', 'overdispersion1', "Locations of items in space", 'static', 'en/overdispersion', 's_overdispersion1', 'en/overdispersion', 'v_overdispersion1');
addPage_2('en/overdispersion', 'overdispersion2', "Overdispersion in Poisson distribution", 'static', 'en/overdispersion', 's_overdispersion2', 'en/overdispersion', 'v_overdispersion2');
addPage_2('en/overdispersion', 'overdispersion3', "Generalised negative binomial distribution", 'interact', 'en/overdispersion', 's_overdispersion3', 'en/overdispersion', 'v_overdispersion3');
addPage_2('en/overdispersion', 'overdispersion4', "Overdispersion in binomial distribution", 'static', 'en/overdispersion', 's_overdispersion4', 'en/overdispersion', 'v_overdispersion4');
addPage_2('en/overdispersion', 'overdispersion5', "Beta-binomial distribution", 'interact', 'en/overdispersion', 's_overdispersion5', 'en/overdispersion', 'v_overdispersion5');
addSection('bk/mathStats', 'sec_weibull', "Varying hazard rate");
addPage_2('en/weibull', 'weibull1', "Weibull distribution", 'static', 'en/weibull', 's_weibull1', 'en/weibull', 'v_weibull1');
addPage_2('en/weibull', 'weibull2', "Mean, variance and shape", 'interact', 'en/weibull', 's_weibull2', 'en/weibull', 'v_weibull2');
addPage_2('en/weibull', 'weibull3', "Calculating Weibull probabilities", 'static', 'en/weibull', 's_weibull3', 'en/weibull', 'v_weibull3');
addSection('bk/mathStats', 'sec_gamma', "Gamma distribution");
addPage_2('en/gamma', 'gamma1', "Distribution for positive variables", 'interact', 'en/gamma', 's_gamma1', 'en/gamma', 'v_gamma1');
addPage_2('en/gamma', 'gamma2', "Gamma probabilities and quantiles", 'static', 'en/gamma', 's_gamma2', 'en/gamma', 'v_gamma2');
addPage_2('en/gamma', 'gamma3', "Some Gamma distribution properties", 'static', 'en/gamma', 's_gamma3', 'en/gamma', 'v_gamma3');
addSection('bk/mathStats', 'sec_beta', "Beta distribution");
addPage_2('en/beta', 'beta1', "Values between zero and one", 'interact', 'en/beta', 's_beta1', 'en/beta', 'v_beta1');
addPage_2('en/beta', 'beta2', "Mean and variance", 'static', 'en/beta', 's_beta2', 'en/beta', 'v_beta2');
addSection('bk/mathStats', 'sec_normal', "Normal distribution");
addPage_2('en/normal', 'normal1', "Standard normal distribution", 'interact', 'en/normal', 's_normal1', 'en/normal', 'v_normal1');
addPage_2('en/normal', 'normal2', "Mean and variance", 'static', 'en/normal', 's_normal2', 'en/normal', 'v_normal2');
addPage_2('en/normal', 'normal3', "Z-scores", 'interact', 'en/normal', 's_normal3', 'en/normal', 'v_normal3');
addPage_2('en/normal', 'normal4', "Probabilities for normal distributions", 'interact', 'en/normal', 's_normal4', 'en/normal', 'v_normal4');
addPage_2('en/normal', 'normal5', "Normal quantiles", 'static', 'en/normal', 's_normal5', 'en/normal', 'v_normal5');
addPage_2('en/normal', 'normal6', "Linear combinations, sums and means", 'static', 'en/normal', 's_normal6', 'en/normal', 'v_normal6');
addPage_2('en/normal', 'normal7', "Independence of sample mean and variance", 'interact', 'en/normal', 's_normal7', 'en/normal', 'v_normal7');

addChapter('bk/mathStats', 'ch_transforms', "Transformed Variables");
addSection('bk/mathStats', 'sec_transformWithCdf', "General methods");
addPage_2('en/transformWithCdf', 'transformWithCdf1', "Differentiating the CDF", 'static', 'en/transformWithCdf', 's_transformWithCdf1', 'en/transformWithCdf', 'v_transformWithCdf1');
addPage_2('en/transformWithCdf', 'transformWithCdf2', "Maximum of a rectangular distribution", 'interact', 'en/transformWithCdf', 's_transformWithCdf2', 'en/transformWithCdf', 'v_transformWithCdf2');
addPage_2('en/transformWithCdf', 'transformWithCdf3', "Monotonic transformations", 'static', 'en/transformWithCdf', 's_transformWithCdf3', 'en/transformWithCdf', 'v_transformWithCdf3');
addPage_2('en/transformWithCdf', 'transformWithCdf4', "Relationship with rectangular distribution", 'interact', 'en/transformWithCdf', 's_transformWithCdf4', 'en/transformWithCdf', 'v_transformWithCdf4');
addPage_2('en/transformWithCdf', 'transformWithCdf5', "Generating random numbers", 'interact', 'en/transformWithCdf', 's_transformWithCdf5', 'en/transformWithCdf', 'v_transformWithCdf5');
addSection('bk/mathStats', 'sec_linearTransform', "Linear transformations");
addPage_2('en/linearTransform', 'linearTransform1', "Mean and variance", 'static', 'en/linearTransform', 's_linearTransform1', 'en/linearTransform', 'v_linearTransform1');
addPage_2('en/linearTransform', 'linearTransform2', "Distribution of transformed variable", 'static', 'en/linearTransform', 's_linearTransform2', 'en/linearTransform', 'v_linearTransform2');
addPage_2('en/linearTransform', 'linearTransform3', "Scale and location parameters", 'static', 'en/linearTransform', 's_linearTransform3', 'en/linearTransform', 'v_linearTransform3');
addPage_2('en/linearTransform', 'linearTransform4', "Scale and location examples", 'static', 'en/linearTransform', 's_linearTransform4', 'en/linearTransform', 'v_linearTransform4');
addSection('bk/mathStats', 'sec_deltaMethod', "Delta method");
addPage_2('en/deltaMethod', 'deltaMethod1', "Variance of transformed variable", 'interact', 'en/deltaMethod', 's_deltaMethod1', 'en/deltaMethod', 'v_deltaMethod1');
addPage_2('en/deltaMethod', 'deltaMethod2', "Examples", 'static', 'en/deltaMethod', 's_deltaMethod2', 'en/deltaMethod', 'v_deltaMethod2');

addChapter('bk/mathStats', 'ch_moreEstimation', "More About Estimation");
addSection('bk/mathStats', 'sec_estimateTwoParam', "Estimating two parameters");
addPage_2('en/estimateTwoParam', 'estimateTwoParam1', "Method of moments", 'static', 'en/estimateTwoParam', 's_estimateTwoParam1', 'en/estimateTwoParam', 'v_estimateTwoParam1');
addPage_2('en/estimateTwoParam', 'estimateTwoParam2', "Maximum likelihood", 'static', 'en/estimateTwoParam', 's_estimateTwoParam2', 'en/estimateTwoParam', 'v_estimateTwoParam2');
addPage_2('en/estimateTwoParam', 'estimateTwoParam3', "Example", 'static', 'en/estimateTwoParam', 's_estimateTwoParam3', 'en/estimateTwoParam', 'v_estimateTwoParam3');
addPage_2('en/estimateTwoParam', 'estimateTwoParam4', "Grid search for MLEs", 'static', 'en/estimateTwoParam', 's_estimateTwoParam4', 'en/estimateTwoParam', 'v_estimateTwoParam4');
addSection('bk/mathStats', 'sec_pivotal', "Confidence intervals from pivots");
addPage_2('en/pivotal', 'pivotal1', "Wald-type confidence intervals", 'static', 'en/pivotal', 's_pivotal1', 'en/pivotal', 'v_pivotal1');
addPage_2('en/pivotal', 'pivotal2', "Pivots", 'static', 'en/pivotal', 's_pivotal2', 'en/pivotal', 'v_pivotal2');
addPage_2('en/pivotal', 'pivotal3', "Confidence interval for exponential rate", 'static', 'en/pivotal', 's_pivotal3', 'en/pivotal', 'v_pivotal3');
addPage_2('en/pivotal', 'pivotal4', "Confidence interval for binomial probability", 'static', 'en/pivotal', 's_pivotal4', 'en/pivotal', 'v_pivotal4');

addChapter('bk/mathStats', 'ch_normalRelated', "Normal-based distributions");
addSection('bk/mathStats', 'sec_chiSquared', "Chi-squared distribution");
addPage_2('en/chiSquared', 'chiSquared1', "Chi-squared with 1 degree of freedom", 'static', 'en/chiSquared', 's_chiSquared1', 'en/chiSquared', 'v_chiSquared1');
addPage_2('en/chiSquared', 'chiSquared2', "Properties of Chi-squared (1 df)", 'interact', 'en/chiSquared', 's_chiSquared2', 'en/chiSquared', 'v_chiSquared2');
addPage_2('en/chiSquared', 'chiSquared3', "General chi-squared distribution", 'static', 'en/chiSquared', 's_chiSquared3', 'en/chiSquared', 'v_chiSquared3');
addPage_2('en/chiSquared', 'chiSquared4', "General chi-squared properties", 'interact', 'en/chiSquared', 's_chiSquared4', 'en/chiSquared', 'v_chiSquared4');
addPage_2('en/chiSquared', 'chiSquared5', "Sample variance", 'static', 'en/chiSquared', 's_chiSquared5', 'en/chiSquared', 'v_chiSquared5');
addPage_2('en/chiSquared', 'chiSquared6', "Confidence interval for normal variance", 'static', 'en/chiSquared', 's_chiSquared6', 'en/chiSquared', 'v_chiSquared6');
addPage_2('en/chiSquared', 'chiSquared7', "Pooled variance from several samples", 'static', 'en/chiSquared', 's_chiSquared7', 'en/chiSquared', 'v_chiSquared7');
addSection('bk/mathStats', 'sec_tDistn', "T distribution");
addPage_2('en/tDistn', 'tDistn1', "Definition of t distribution", 'static', 'en/tDistn', 's_tDistn1', 'en/tDistn', 'v_tDistn1');
addPage_2('en/tDistn', 'tDistn2', "Mean, variance and shape", 'interact', 'en/tDistn', 's_tDistn2', 'en/tDistn', 'v_tDistn2');
addPage_2('en/tDistn', 'tDistn3', "Pivot for normal mean", 'static', 'en/tDistn', 's_tDistn3', 'en/tDistn', 'v_tDistn3');
addPage_2('en/tDistn', 'tDistn4', "Confidence interval for normal mean", 'static', 'en/tDistn', 's_tDistn4', 'en/tDistn', 'v_tDistn4');
addPage_2('en/tDistn', 'tDistn5', "Two samples from normal distributions", 'static', 'en/tDistn', 's_tDistn5', 'en/tDistn', 'v_tDistn5');
addPage_2('en/tDistn', 'tDistn6', "Estimating difference between means", 'static', 'en/tDistn', 's_tDistn6', 'en/tDistn', 'v_tDistn6');
addSection('bk/mathStats', 'sec_fDistn', "F distribution");
addPage_2('en/fDistn', 'fDistn1', "Ratio of chi-squared variables", 'static', 'en/fDistn', 's_fDistn1', 'en/fDistn', 'v_fDistn1');
addPage_2('en/fDistn', 'fDistn2', "Mean, variance and shape", 'interact', 'en/fDistn', 's_fDistn2', 'en/fDistn', 'v_fDistn2');
addPage_2('en/fDistn', 'fDistn3', "Comparing sample variances", 'static', 'en/fDistn', 's_fDistn3', 'en/fDistn', 'v_fDistn3');
addPage_2('en/fDistn', 'fDistn4', "Relationship between t and F distributions", 'static', 'en/fDistn', 's_fDistn4', 'en/fDistn', 'v_fDistn4');

addChapter('bk/mathStats', 'ch_hypothesisTests', "Hypothesis Tests");
addSection('bk/mathStats', 'sec_testConcepts', "Hypothesis test concepts");
addPage_2('en/testConcepts', 'testConcepts1', "Inference", 'static', 'en/testConcepts', 's_testConcepts1', 'en/testConcepts', 'v_testConcepts1');
addPage_2('en/testConcepts', 'testConcepts2', "Null and alternative hypotheses", 'static', 'en/testConcepts', 's_testConcepts2', 'en/testConcepts', 'v_testConcepts2');
addPage_2('en/testConcepts', 'testConcepts3', "Test statistic", 'static', 'en/testConcepts', 's_testConcepts3', 'en/testConcepts', 'v_testConcepts3');
addPage_2('en/testConcepts', 'testConcepts4', "P-value and its interpretation", 'interact', 'en/testConcepts', 's_testConcepts4', 'en/testConcepts', 'v_testConcepts4');
addPage_2('en/testConcepts', 'testConcepts5', "Two-tailed tests", 'interact', 'en/testConcepts', 's_testConcepts5', 'en/testConcepts', 'v_testConcepts5');
addPage_2('en/testConcepts', 'testConcepts6', "Distribution of p-values", 'interact', 'en/testConcepts', 's_testConcepts6', 'en/testConcepts', 'v_testConcepts6');
addSection('bk/mathStats', 'sec_goodnessOfFit', "Goodness of fit tests");
addPage_2('en/goodnessOfFit', 'goodnessOfFit1', "Counts and chi-squared distribution", 'static', 'en/goodnessOfFit', 's_goodnessOfFit1', 'en/goodnessOfFit', 'v_goodnessOfFit1');
addPage_2('en/goodnessOfFit', 'goodnessOfFit2', "Test for Poisson distribution", 'static', 'en/goodnessOfFit', 's_goodnessOfFit2', 'en/goodnessOfFit', 'v_goodnessOfFit2');
addPage_2('en/goodnessOfFit', 'goodnessOfFit3', "Poisson test with constraints", 'static', 'en/goodnessOfFit', 's_goodnessOfFit3', 'en/goodnessOfFit', 'v_goodnessOfFit3');
addPage_2('en/goodnessOfFit', 'goodnessOfFit4', "Test based on frequency table", 'static', 'en/goodnessOfFit', 's_goodnessOfFit4', 'en/goodnessOfFit', 'v_goodnessOfFit4');
addPage_2('en/goodnessOfFit', 'goodnessOfFit5', "Test for any discrete distribution", 'static', 'en/goodnessOfFit', 's_goodnessOfFit5', 'en/goodnessOfFit', 'v_goodnessOfFit5');
addPage_2('en/goodnessOfFit', 'goodnessOfFit6', "Test for continuous distribution", 'interact', 'en/goodnessOfFit', 's_goodnessOfFit6', 'en/goodnessOfFit', 'v_goodnessOfFit6');
addSection('bk/mathStats', 'sec_testNormal', "Tests about normal distns");
addPage_2('en/testNormal', 'testNormal1', "Test for mean, known \u03c3", 'static', 'en/testNormal', 's_testNormal1', 'en/testNormal', 'v_testNormal1');
addPage_2('en/testNormal', 'testNormal2', "Test about mean, unknown \u03c3", 'interact', 'en/testNormal', 's_testNormal2', 'en/testNormal', 'v_testNormal2');
addPage_2('en/testNormal', 'testNormal3', "Test about variance", 'static', 'en/testNormal', 's_testNormal3', 'en/testNormal', 'v_testNormal3');
addPage_2('en/testNormal', 'testNormal4', "Equal means in two distributions", 'static', 'en/testNormal', 's_testNormal4', 'en/testNormal', 'v_testNormal4');
addPage_2('en/testNormal', 'testNormal5', "Equal variances in two distributions", 'static', 'en/testNormal', 's_testNormal5', 'en/testNormal', 'v_testNormal5');
addSection('bk/mathStats', 'sec_fixedSigLevel', "Fixed significance level");
addPage_2('en/fixedSigLevel', 'fixedSigLevel1', "Significance level", 'static', 'en/fixedSigLevel', 's_fixedSigLevel1', 'en/fixedSigLevel', 'v_fixedSigLevel1');
addPage_2('en/fixedSigLevel', 'fixedSigLevel2', "Type I and II errors", 'interact', 'en/fixedSigLevel', 's_fixedSigLevel2');
addPage_2('en/fixedSigLevel', 'fixedSigLevel3', "P-values and decisions", 'interact', 'en/fixedSigLevel', 's_fixedSigLevel3');
addPage_2('en/fixedSigLevel', 'fixedSigLevel4', "Significance levels for discrete data", 'static', 'en/fixedSigLevel', 's_fixedSigLevel4');
addPage_2('en/fixedSigLevel', 'fixedSigLevel5', "Power function", 'interact', 'en/fixedSigLevel', 's_fixedSigLevel5');
addPage_2('en/fixedSigLevel', 'fixedSigLevel6', "Deciding on the sample size", 'interact', 'en/fixedSigLevel', 's_fixedSigLevel6');
addSection('bk/mathStats', 'sec_likelihoodRatio', "Likelihood ratio test");
addPage_2('en/likelihoodRatio', 'likelihoodRatio1', "Big model vs small model", 'static', 'en/likelihoodRatio', 's_likelihoodRatio1', 'en/likelihoodRatio', 'v_likelihoodRatio1');
addPage_2('en/likelihoodRatio', 'likelihoodRatio2', "Likelihood ratio", 'static', 'en/likelihoodRatio', 's_likelihoodRatio2', 'en/likelihoodRatio', 'v_likelihoodRatio2');
addPage_2('en/likelihoodRatio', 'likelihoodRatio3', "Likelihood ratio test", 'interact', 'en/likelihoodRatio', 's_likelihoodRatio3', 'en/likelihoodRatio', 'v_likelihoodRatio3');
addPage_2('en/likelihoodRatio', 'likelihoodRatio4', "Another example", 'static', 'en/likelihoodRatio', 's_likelihoodRatio4', 'en/likelihoodRatio', 'v_likelihoodRatio4');
addSection('bk/mathStats', 'sec_invertTest', "CI from inverting a test");
addPage_2('en/invertTest', 'invertTest1', "Test statistics and pivots", 'static', 'en/invertTest', 's_invertTest1', 'en/invertTest', 'v_invertTest1');
addPage_2('en/invertTest', 'invertTest2', "Test from a confidence interval", 'static', 'en/invertTest', 's_invertTest2', 'en/invertTest', 'v_invertTest2');
addPage_2('en/invertTest', 'invertTest3', "Confidence interval from a test", 'interact', 'en/invertTest', 's_invertTest3', 'en/invertTest', 'v_invertTest3');
addPage_2('en/invertTest', 'invertTest4', "Confidence interval for median#?#  (Difficult)", 'interact', 'en/invertTest', 's_invertTest4', 'en/invertTest', 'v_invertTest4');
addPage_2('en/invertTest', 'invertTest5', "CI from likelihood ratio test", 'interact', 'en/invertTest', 's_invertTest5', 'en/invertTest', 'v_invertTest5');

addChapter('bk/mathStats', 'ch_multivariateDistns', "Multivariate distributions");
addSection('bk/mathStats', 'sec_bivarDiscreteDistn', "Discrete bivariate distributions");
addPage_2('en/bivarDiscreteDistns', 'bivarDiscreteDistns1', "Joint probability function", 'static', 'en/bivarDiscreteDistns', 's_bivarDiscreteDistns1', 'en/bivarDiscreteDistns', 'v_bivarDiscreteDistns1');
addPage_2('en/bivarDiscreteDistns', 'bivarDiscreteDistns2', "Three-dimensional bar chart", 'interact', 'en/bivarDiscreteDistns', 's_bivarDiscreteDistns2', 'en/bivarDiscreteDistns', 'v_bivarDiscreteDistns2');
addPage_2('en/bivarDiscreteDistns', 'bivarDiscreteDistns3', "Marginal distributions", 'interact', 'en/bivarDiscreteDistns', 's_bivarDiscreteDistns3', 'en/bivarDiscreteDistns', 'v_bivarDiscreteDistns3');
addPage_2('en/bivarDiscreteDistns', 'bivarDiscreteDistns4', "Conditional distributions", 'interact', 'en/bivarDiscreteDistns', 's_bivarDiscreteDistns4', 'en/bivarDiscreteDistns', 'v_bivarDiscreteDistns4');
addPage_2('en/bivarDiscreteDistns', 'bivarDiscreteDistns5', "Independence", 'static', 'en/bivarDiscreteDistns', 's_bivarDiscreteDistns5', 'en/bivarDiscreteDistns', 'v_bivarDiscreteDistns5');
addPage_2('en/bivarDiscreteDistns', 'bivarDiscreteDistns6', "Random samples", 'static', 'en/bivarDiscreteDistns', 's_bivarDiscreteDistns6', 'en/bivarDiscreteDistns', 'v_bivarDiscreteDistns6');
addSection('bk/mathStats', 'sec_bivarContinDistns', "Continuous bivariate distributions");
addPage_2('en/bivarContinDistns', 'bivarContinDistns1', "Joint probability density function", 'static', 'en/bivarContinDistns', 's_bivarContinDistns1', 'en/bivarContinDistns', 'v_bivarContinDistns1');
addPage_2('en/bivarContinDistns', 'bivarContinDistns2', "Probabilities as integrals", 'static', 'en/bivarContinDistns', 's_bivarContinDistns2', 'en/bivarContinDistns', 'v_bivarContinDistns2');
addPage_2('en/bivarContinDistns', 'bivarContinDistns3', "Marginal distributions", 'static', 'en/bivarContinDistns', 's_bivarContinDistns3', 'en/bivarContinDistns', 'v_bivarContinDistns3');
addPage_2('en/bivarContinDistns', 'bivarContinDistns4', "Conditional distributions", 'static', 'en/bivarContinDistns', 's_bivarContinDistns4', 'en/bivarContinDistns', 'v_bivarContinDistns4');
addPage_2('en/bivarContinDistns', 'bivarContinDistns5', "Independence and random samples", 'static', 'en/bivarContinDistns', 's_bivarContinDistns5', 'en/bivarContinDistns', 'v_bivarContinDistns5');
addSection('bk/mathStats', 'sec_bivarExpected', "Expected values");
addPage_2('en/bivarExpected', 'bivarExpected1', "Discrete expected values", 'static', 'en/bivarExpected', 's_bivarExpected1', 'en/bivarExpected', 'v_bivarExpected1');
addPage_2('en/bivarExpected', 'bivarExpected2', "Continuous expected values", 'static', 'en/bivarExpected', 's_bivarExpected2', 'en/bivarExpected', 'v_bivarExpected2');
addPage_2('en/bivarExpected', 'bivarExpected3', "Properties of expected values", 'static', 'en/bivarExpected', 's_bivarExpected3', 'en/bivarExpected', 'v_bivarExpected3');
addPage_2('en/bivarExpected', 'bivarExpected4', "Means and variances", 'static', 'en/bivarExpected', 's_bivarExpected4', 'en/bivarExpected', 'v_bivarExpected4');
addSection('bk/mathStats', 'sec_covariance', "Covariance and correlation");
addPage_2('en/covariance', 'covariance1', "Covariance", 'static', 'en/covariance', 's_covariance1', 'en/covariance', 'v_covariance1');
addPage_2('en/covariance', 'covariance5', "Variance of a sum", 'static', 'en/covariance', 's_covariance5', 'en/covariance', 'v_covariance5');
addPage_2('en/covariance', 'covariance2', "Correlation coefficient", 'static', 'en/covariance', 's_covariance2', 'en/covariance', 'v_covariance2');
addPage_2('en/covariance', 'covariance3', "Linear relationships", 'static', 'en/covariance', 's_covariance3', 'en/covariance', 'v_covariance3');
addPage_2('en/covariance', 'covariance4', "Independence", 'static', 'en/covariance', 's_covariance4', 'en/covariance', 'v_covariance4');
addSection('bk/mathStats', 'sec_multinomial', "Multinomial distribution");
addPage_2('en/multinomial', 'multinomial1', "Joint probability function", 'interact', 'en/multinomial', 's_multinomial1', 'en/multinomial', 'v_multinomial1');
addPage_2('en/multinomial', 'multinomial2', "Marginal distributions", 'interact', 'en/multinomial', 's_multinomial2', 'en/multinomial', 'v_multinomial2');
addPage_2('en/multinomial', 'multinomial3', "Conditional distributions", 'interact', 'en/multinomial', 's_multinomial3', 'en/multinomial', 'v_multinomial3');
addPage_2('en/multinomial', 'multinomial4', "Means, variances and correlations", 'static', 'en/multinomial', 's_multinomial4', 'en/multinomial', 'v_multinomial4');
addPage_2('en/multinomial', 'multinomial5', "Parameter estimation", 'static', 'en/multinomial', 's_multinomial5', 'en/multinomial', 'v_multinomial5');
addSection('bk/mathStats', 'sec_bivarNormal', "Bivariate normal distribution");
addPage_2('en/bivarNormal', 'bivarNormal1', "Standard bivariate normal distribution", 'interact', 'en/bivarNormal', 's_bivarNormal1', 'en/bivarNormal', 'v_bivarNormal1');
addPage_2('en/bivarNormal', 'bivarNormal2', "General bivariate normal distribution", 'interact', 'en/bivarNormal', 's_bivarNormal2', 'en/bivarNormal', 'v_bivarNormal2');
addPage_2('en/bivarNormal', 'bivarNormal3', "Marginal distributions", 'interact', 'en/bivarNormal', 's_bivarNormal3', 'en/bivarNormal', 'v_bivarNormal3');
addPage_2('en/bivarNormal', 'bivarNormal4', "Conditional distributions", 'interact', 'en/bivarNormal', 's_bivarNormal4', 'en/bivarNormal', 'v_bivarNormal4');
addPage_2('en/bivarNormal', 'bivarNormal5', "Covariance and correlation", 'static', 'en/bivarNormal', 's_bivarNormal5', 'en/bivarNormal', 'v_bivarNormal5');

var language = "en";
var logoGif = null;
var homeDir = "bk/mathStats";
var versionGif = "images/castTheory";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = true;
var summaryPdfUrl = "http://castAdmin2.massey.ac.nz/pdf/mathStats";
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "13";

var localVideos = true;

var fullTextString = 'Full';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Full';
fullTabTooltip = 'Full text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Full text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {};
var versions = {};

bookLoaded = true;
