startExercise("exerciseCategProg.BuildContinTableApplet", 550, 650);

addVariation("studentGrades", "There were #sampleSize(10:14)# students in a Statistics class. The list on the left below shows the final grades for the students and their genders. Create a contingency table describing the grades and genders.\\n(For each successive row of the list, click on the appropriate cell of the contingency table to add one to its count.)", "xVarName(Gender)#xCategories(Male Female)#yVarName(Exam grade)#yCategories(A B C Fail)#jointProbs(0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125)", null, 0);
addVariation("skiingInjury", "Researchers in a French ski resort investigated whether the severity of injuries is related to whether the skiers have had previous skiing experience. The list on the left below shows the severity of injury and previous experience for #sampleSize(20)# skiers who had medical assistance for injuries. Create a contingency table describing the injuries and experience.\\n(For each successive row of the list, click on the appropriate cell of the contingency table to add one to its count.)", "xVarName(Background)#xCategories(Experienced Novice)#yVarName(Injury)#yCategories(Severe Minor)#jointProbs(.2 .3 .2 .3)", null, 0);
addVariation("alcoholNicotine", "#sampleSize(10:14)# pregnant women were asked about their use of alcohol (oz per day) and nicotine (gm per day) during their pregnancy. Each row of the list on the left below shows the results from one woman. Create a contingency table describing use of these substances.\\n(For each successive row of the list, click on the appropriate cell of the contingency table to add one to its count.)", "xVarName(Nicotine)#xCategories(No_nic 1_to_15 Over_15)#yVarName(Alcohol)#yCategories(No_alc Up_to_0.5 Over_0.5)#jointProbs(.23 .02 .02 .22 .05 .08 .22 .08 .08)", null, 0);

//----------------------------------------------

startExercise("exerciseCategProg.FindContinPropnApplet", 450, 600);

addVariation("grief", "The contingency table below describes the state of grief (I to IV) of 66 mothers who had suffered a neonatal death and the amount of support given to these mothers.\\n", "xVarName(Support)#xCategories(Good Adequate Poor)#yVarName(Grief state)#yCategories(Level_I Level_II Level_III Level_IV)#counts(17 6 3 1 9 5 5 2 8 1 4 5)", "#probType(0)#What proportion of these mothers had #criticalX(0:2)# support and were also in grief state #apos##criticalY(0:3)##apos#?|||#probType(1)#What proportion of these mothers had #criticalX(0:2)# support?|||#probType(2)#What proportion of the mothers with grief state #apos##criticalY(0:3)##apos# had #criticalX(0:2)# support?|||#probType(3)#What proportion of these mothers had grief level that was categorised as #apos##criticalY(0:3)##apos#?|||#probType(4)#What proportion of the mothers with #criticalX(0:2)# support were classified as having grief at #apos##criticalY(0:3)##apos#?", 0);
addVariation("marijuana", "Four hundred and forty five college students were classified according to both frequency of marijuana use and parental use of alcohol and psychoactive drugs. The contingency table below describes the data.\\n", "xVarName(Parent)#xCategories(Both One Neither)#yVarName(Student)#yCategories(Never Occasionally Regularly)#counts(17 11 19 68 44 51 141 54 40)", "#probType(0)#What proportion of the students had #criticalX(0:2)# of their parents who used alcohol or drugs and themselves #criticalY(0:2)# used marijuana?|||#probType(1)#What proportion of the students had #criticalX(0:2)# of their parents who used alcohol or drugs?|||#probType(2)#Of the students who #apos##criticalY(0:2)##apos# used marijuana, what proportion had #criticalX(0:2)# of their parents who used alcohol or drugs?|||#probType(3)#What proportion of the students #apos##criticalY(0:2)##apos# used marijuana?|||#probType(4)#Of the students with #criticalX(0:2)# of their parents who used drugs or alcohol, what proportion themselves #apos##criticalY(0:2)##apos# used marijuana?", 0);
addVariation("waferDefects", "The contingency table below describes the defects of four kinds that were detected in silicon wafers manufactured during three production shifts.\\n", "xVarName(Defect)#xCategories(A B C D)#yVarName(Shift)#yCategories(1 2 3)#counts(15 26 33 21 31 17 45 34 49 13 5 20)", "#probType(0)#What proportion of the wafers were made in shift #criticalY(0:2)# and had defect #criticalX(0:3)#?|||#probType(1)#What proportion of the wafers had defect #criticalX(0:3)#?|||#probType(2)#Of the wafers made on shift #criticalY(0:2)#, what proportion had defect #criticalX(0:3)#?|||#probType(3)#What proportion of the wafers were made on shift #criticalY(0:2)#?|||#probType(4)#What proportion of the wafers with defect #criticalX(0:3)# were made on shift #criticalY(0:2)#?", 0);
addVariation("fog", "Weather forecasts are often inaccurate. The following contingency table describes the occasions during a year in which fog was predicted for the following day and the actual occurrence of fog on that day.\\n", "xVarName(Actual)#xCategories(Fog No_fog)#yVarName(Forecast)#yCategories(Fog No_fog)#counts(28 17 5 315)", "#probType(0)#On what proportion of days was the forecast #criticalY(0:1)# and had the actual weather #criticalX(0:1)#?|||#probType(1)#On what proportion of days was there #criticalX(0:1)#?|||#probType(2)#On what proportion of the days with forecast #criticalY(0:1)# was the actual weather #criticalX(0:1)#?|||#probType(3)#For what proportion of days was the forecast #criticalY(0:1)#?|||#probType(4)#Of the days in which the actual weather was #criticalX(0:1)#, on what proportion was it forecast that there would be #criticalY(0:1)#?", 0);

//----------------------------------------------

startExercise("exerciseCategProg.FindContinPropnExternalApplet", 450, 650);

addVariation("grief", "The contingency table below describes the state of grief (I to IV) of 66 mothers who had suffered a neonatal death and the amount of support given to these mothers.\\nAnswer the following question to #requiredDecimals(4)# decimals. ", "xVarName(Support)#xCategories(Good Adequate Poor)#yVarName(Grief state)#yCategories(Level_I Level_II Level_III Level_IV)#counts(17 6 3 1 9 5 5 2 8 1 4 5)#dataName(MotherGrief)", "#probType(0)#What proportion of these mothers had #criticalX(0:2)# support and were also in grief state #apos##criticalY(0:3)##apos#?|||#probType(1)#What proportion of these mothers had #criticalX(0:2)# support?|||#probType(2)#What proportion of the mothers with grief state #apos##criticalY(0:3)##apos# had #criticalX(0:2)# support?|||#probType(3)#What proportion of these mothers had grief level that was categorised as #apos##criticalY(0:3)##apos#?|||#probType(4)#What proportion of the mothers with #criticalX(0:2)# support were classified as having grief at #apos##criticalY(0:3)##apos#?", 0);
addVariation("marijuana", "Four hundred and forty five college students were classified according to both frequency of marijuana use and parental use of alcohol and psychoactive drugs.\\nAnswer the following question to #requiredDecimals(4)# decimals. ", "xVarName(Parent)#xCategories(Both One Neither)#yVarName(Student)#yCategories(Never Occasionally Regularly)#counts(17 11 19 68 44 51 141 54 40)#dataName(StudentDrugs)", "#probType(0)#What proportion of the students had #criticalX(0:2)# of their parents who used alcohol or drugs and themselves #criticalY(0:2)# used marijuana?|||#probType(1)#What proportion of the students had #criticalX(0:2)# of their parents who used alcohol or drugs?|||#probType(2)#Of the students who #apos##criticalY(0:2)##apos# used marijuana, what proportion had #criticalX(0:2)# of their parents who used alcohol or drugs?|||#probType(3)#What proportion of the students #apos##criticalY(0:2)##apos# used marijuana?|||#probType(4)#Of the students with #criticalX(0:2)# of their parents who used drugs or alcohol, what proportion themselves #apos##criticalY(0:2)##apos# used marijuana?", 0);
addVariation("waferDefects", "This data set describes the defects of four kinds that were detected in silicon wafers manufactured during three production shifts.\\nAnswer the following question to #requiredDecimals(4)# decimals. ", "xVarName(Defect)#xCategories(A B C D)#yVarName(Shift)#yCategories(1 2 3)#counts(15 26 33 21 31 17 45 34 49 13 5 20)#dataName(DefectiveWafers)", "#probType(0)#What proportion of the wafers were made in shift #criticalY(0:2)# and had defect #criticalX(0:3)#?|||#probType(1)#What proportion of the wafers had defect #criticalX(0:3)#?|||#probType(2)#Of the wafers made on shift #criticalY(0:2)#, what proportion had defect #criticalX(0:3)#?|||#probType(3)#What proportion of the wafers were made on shift #criticalY(0:2)#?|||#probType(4)#What proportion of the wafers with defect #criticalX(0:3)# were made on shift #criticalY(0:2)#?", 0);
addVariation("fog", "Weather forecasts are often inaccurate. This data set describes the occasions during a year in which fog was predicted for the following day and the actual occurrence of fog on that day.\\nAnswer the following question to #requiredDecimals(4)# decimals. ", "xVarName(Actual)#xCategories(Fog No_fog)#yVarName(Forecast)#yCategories(Fog No_fog)#counts(28 17 5 315)#dataName(WeatherForecasts)", "#probType(0)#On what proportion of days was the forecast #criticalY(0:1)# and had the actual weather #criticalX(0:1)#?|||#probType(1)#On what proportion of days was there #criticalX(0:1)#?|||#probType(2)#On what proportion of the days with forecast #criticalY(0:1)# was the actual weather #criticalX(0:1)#?|||#probType(3)#For what proportion of days was the forecast #criticalY(0:1)#?|||#probType(4)#Of the days in which the actual weather was #criticalX(0:1)#, on what proportion was it forecast that there would be #criticalY(0:1)#?", 0);

//----------------------------------------------

startExercise("exerciseCategProg.ContinExpectedApplet", 600, 600);

addVariation("grief", "The contingency table below describes the state of grief (I to IV) of 66 mothers who had suffered a neonatal death and the amount of support given to these mothers.\\nIf a mother's grief state is independent of her level of support, what is the expected number with grief state '#criticalY(0:3)#' and '#criticalX(0:2)#' support?", "xVarName(Support)#xCategories(Good Adequate Poor)#yVarName(Grief state)#yCategories(Level_I Level_II Level_III Level_IV)#counts(17 6 3 1 9 5 5 2 8 1 4 5)#maxExpected(99.999)", null, 0);
addVariation("marijuana", "Four hundred and forty five college students were classified according to both frequency of marijuana use and parental use of alcohol and psychoactive drugs. The contingency table below describes the data.\\nIf parental history of using alcohol or drugs is independent of a student's own use of marijuana, what is the expected number of the students with #criticalX(0:2)# of their parents using alcohol or drugs and themselves #criticalY(0:2)# using marijuana?", "xVarName(Parent)#xCategories(Both One Neither)#yVarName(Student)#yCategories(Never Occasionally Regularly)#counts(17 11 19 68 44 51 141 54 40)#maxExpected(999.99)", null, 0);
addVariation("waferDefects", "The contingency table below describes the defects of four kinds that were detected in silicon wafers manufactured during three production shifts.\\nIf the probabilities of defects are the same for all shifts, what is the expected number of wafers made in shift #criticalY(0:2)# that had defect #criticalX(0:3)#?", "xVarName(Defect)#xCategories(A B C D)#yVarName(Shift)#yCategories(1 2 3)#counts(15 26 33 21 31 17 45 34 49 13 5 20)#maxExpected(99.99)", null, 0);
addVariation("fog", "Weather forecasts are often inaccurate. The following contingency table describes the occasions during a year in which fog was predicted for the following day and the actual occurrence of fog on that day.\\nIf the actual weather in a day is independent of the previous day's prediction, what is the expected number of days with forecast #criticalY(0:1)# and actual weather #criticalX(0:1)#?", "xVarName(Actual)#xCategories(Fog No_fog)#yVarName(Forecast)#yCategories(Fog No_fog)#counts(28 17 5 315)#maxExpected(999.99)", null, 0);

//----------------------------------------------

startExercise("exerciseCategProg.Chi2TestApplet", 550, 700);

addVariation("coldDuration", "A study was conducted to assess the effectiveness of a drug to reduce the duration of colds. #n[](50,100)# patients with cold symptoms were randomly given either the drug or a placebo (a tablet with no active ingredient). The contingency table below shows the reported cold durations of the patients.\\nWhat would you conclude from the chi-squared test under the table?", "xName(Treatment)#xLabels(Drug Placebo)#yName(Cold duration)#yLabels(1-2_days 3-4_days 5-8_days)#xMarginProbs(0.5 0.5)#yConditProbs[](0.4 0.3 0.3 0.3 0.4 0.3*0.4 0.4 0.2 0.2 0.3 0.5)#maxExpected(99.99)#maxChi2(999.99)#dependentText(Cold duration is affected by the drug)#independentText(Cold duration is not affected by the drug)", null, 0);
addVariation("plovers", "Wildlife ecologists monitored the breeding habitats of mountain plovers for three years and made note of where the plovers nested. The contingency table below summarises the results.\\nWhat would you conclude from the chi-squared test under the table?", "n(150:250)#xName(Year)#xLabels(2013 2014 2015)#yName(Nesting location)#yLabels(Agricultural_field Prairie_dog_habitat Grassland)#xMarginProbs(0.33 0.33 0.34)#yConditProbs[](0.5 0.4 0.1 0.45 0.4 0.15 0.4 0.4 0.2*0.5 0.4 0.1 0.4 0.5 0.1 0.5 0.3 0.2)#maxExpected(999.9)#maxChi2(999.99)#dependentText(nesting locations were different in different years)#independentText(nesting locations were the same in all years)", null, 0);
addVariation("tyreQuality", "The operations manager of a company that manufactures tyres wants to determine whether there are any differences in the quality of workmanship among the three daily shifts. She randomly selects #n(400:800)# tires and carefully inspects them. Each tyre is either classified as perfect, satisfactory, or defective, and the shift that produced it is also recorded. The contingency table below summarises the data collected.\\nWhat would you conclude from the chi-squared test under the table?", "xName(Shift)#xLabels(Shift_1 Shift_2 Shift_3)#yName(Tyre quality)#yLabels(Perfect Satisfactory Poor)#xMarginProbs(0.35 0.35 0.3)#yConditProbs(0.4 0.5 0.1 0.45 0.45 0.1 0.55 0.35 0.1)#maxExpected(999.9)#maxChi2(999.99)#dependentText(there are differences in tyre quality between shifts)#independentText(tyre quality is the same in all shifts)", null, 0);

//----------------------------------------------

