startExercise("exerciseTestProg.BinomialTestApplet", 500, 770);

addVariation("strawberryYoghurt", "It is thought that the proportion of customers buying yoghurt who choose strawberry flavour is#?:string[tail]( at least * equal to * no higher than * equal to * )##pSuccess[index](0.6,0.5,0.4)#.\\nOut of #nTrials(20:30)# customers buying yoghurt, #nSuccess(:)# were observed to pick strawberry. Perform a test for whether its probability is #?:string[tail](less than*less than*more than*more than*different from*not equal to)# #pSuccess#.", "index(0:2)#maxValue(99.9)#tail[](0,1,2,3,4,4)#maxSliderN(40)#trialsName(customers)#successesName(strawberry choices)#successName(choosing strawberry)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("raspberryYoghurt", "It is thought that the proportion of customers buying yoghurt who choose raspberry flavour is#?:string[tail]( at least * equal to * no higher than * equal to * )##pSuccess[index](0.6,0.5,0.4)#.\\nOut of #nTrials(20:30)# customers buying yoghurt, #nSuccess(:)# were observed to pick raspberry. Perform a test for whether its probability is #?:string[tail](less than*less than*more than*more than*different from*not equal to)# #pSuccess#.", "index(0:2)#maxValue(99.9)#tail[](0,1,2,3,4,4)#maxSliderN(40)#trialsName(customers)#successesName(raspberry choices)#successName(choosing raspberry)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("femaleLizards", "Researchers believe that the proportion of lizards of a particular species that are hatched female is#?:string[tail]( at least * equal to * no higher than * equal to * )##pSuccess[index](0.6,0.5,0.4)#.\\n#nTrials(20:30)# lizards were observed hatching and #nSuccess(:)# of these were female. Perform a test for whether the probability of being female is #?:string[tail](less than*less than*more than*more than*different from*not equal to)# #pSuccess#.", "index(0:2)#maxValue(99.9)#tail[](0,1,2,3,4,4)#maxSliderN(40)#trialsName(lizards)#successesName(females)#successName(being female)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("maleLizards", "Researchers believe that the proportion of lizards of a particular species that are hatched male is#?:string[tail]( at least * equal to * no higher than * equal to * )##pSuccess[index](0.6,0.5,0.4)#.\n#nTrials(20:30)# lizards were observed hatching and #nSuccess(:)# of these were male. Perform a test for whether the probability of being male is #?:string[tail](less than*less than*more than*more than*different from*not equal to)# #pSuccess#.", "index(0:2)#maxValue(99.9)#tail[](0,1,2,3,4,4)#maxSliderN(40)#trialsName(lizards)#successesName(males)#successName(being male)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("drugRecovery", "A drug company claims that when patients with sore throats take a throat lozenge, the probability of recovery after 12 hours is#?:string[tail]( at least *equal to *??? *??? * )##pSuccess[index](0.6,0.5,0.4)#.\\nIn an experiment with #nTrials(20:30)# patients, #nSuccess(:)# had recovered after 12 hours. Perform a test for whether the probability of recovery is #?:string[tail](less than*less than*???*???*different from*not equal to)# #pSuccess#.", "index(0:2)#maxValue(99.9)#tail[](0,1,4,4)#maxSliderN(40)#trialsName(patients)#successesName(recovered patients)#successName(recovery)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("drugFailure", "A drug company claims that when patients with sore throats take a throat lozenge, the probability of being still ill after 12 hours is#?:string[tail](??? *??? * no higher than * equal to * )##pSuccess[index](0.6,0.5,0.4)#.\\nIn an experiment with #nTrials(20:30)# patients, #nSuccess(:)# were still ill after 12 hours. Perform a test for whether the probability of being still ill is #?:string[tail](???*???*more than*more than*different from*not equal to)# #pSuccess#.", "index(0:2)#maxValue(99.9)#tail[](2,3,4,4)#maxSliderN(40)#trialsName(patients)#successesName(patients still ill)#successName(being still ill)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);

//----------------------------------------------

startExercise("exerciseTestProg.NormApproxTestApplet", 550, 770);

addVariation("voting", "A week before a city's election for mayor, the media claim that the proportion of voters who intend to vote for a candidate (Brown) is#?:string[tail]( at least * equal to * no higher than * equal to * )##pSuccess[index](0.3,0.4,0.5,0.6,0.7)#.\\n#nTrials[](300,400,500,600)# voters in the city are randomly selected and #nSuccess(:)# say they intend to vote for Brown. Perform a test for whether #?:string[tail](less than*less than*more than*more than*different from*not equal to)# #?:string[index](30%*40%*50%*60%*70%)# of the city intends to vote for Brown.", "index(0:4)#tail[](0,1,2,3,4,4)#trialsName(sampled voters)#successesName(Brown supporters)#successName(voting for Brown)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("cola", "A consumer group claims that#?:string[tail]( at least * * no higher than * * )##pSuccess[index](0.4,0.5,0.6)# of students prefer Coca Cola to Pepsi.\\nTo assess this claim, #nTrials[](200,300,400,500)# students on a campus are randomly selected and #nSuccess(:)# say they prefer Coca Cola. Perform a test for whether #?:string[tail](less than*less than*more than*more than*a percentage different from)# #?:string[index](40%*50%*60%)# of the students on that campus prefer Coke.", "index(0:2)#tail[](0,1,2,3,4,4)#trialsName(sampled students)#successesName(students preferring Coke)#successName(preferring Coke)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);
addVariation("chickenStress", "From previous research, a biologist believes that the proportion of chickens in battery farms suffering from stress is#?:string[tail]( at least * equal to * no higher than * equal to * * )##pSuccess[index](0.1,0.15,0.2,0.25)#.\\nTo assess this claim, #nTrials[](600,700,800,900,1000)# chickens in a farm are randomly selected and #nSuccess(:)# show signs of stress. Perform a test for whether the percentage of chickens on that farm that are stressed is #?:string[tail](less than*less than*more than*more than*different from)# #?:string[index](10*15*20*25)#%.", "index(0:3)#tail[](0,1,2,3,4,4)#trialsName(chickens)#successesName(chickens showing signs of stress)#successName(being stressed)#conclusions(There_is_no_evidence_that_H%sub1%_is_true There_is_only_weak_evidence_that_H%sub1%_is_true There_is_moderately_strong_evidence_that_H%sub1%_is_true There_is_very_strong_evidence_that_H%sub1%_is_true It_is_almost_certain_that_H%sub1%_is_true)", null, 0);

//----------------------------------------------

