startExercise("exerciseGroupsProg.SumDiffProbApplet", 600, 750);

addVariation("appleWeights", "The weights of one variety of apple have a normal distribution with mean #mu# = #mean1(100:200)# grams and standard deviation #sigma# = #sd1(8:12)# grams. Two of these apples are randomly selected.\\n", "maxMeanParam(9999)#maxSdParam(99.999)", "What is the probability that #group-cut-offs(2.5:0:the first apple weight:the second apple weight:grams:the total weight of the two apples)#?", 0);
addVariation("examMarks", "The mark of a student in a Maths exam has a normal distribution with mean #mu##sub1# = #mean1(60:80)# and standard deviation #sigma##sub1# = #sd1(5:10)#. The students mark in an English exam independently has a normal distribution with mean #mu##sub2# = #mean2(50:70)# and standard deviation #sigma##sub2# = #sd2(5:10)#.\\n", "maxMeanParam(9999)#maxSdParam(9.9999)", "For a randomly selected student, what is the probability that #group-cut-offs(:2:0:the students Maths mark:the students English mark:null:the students total mark)?", 0);
addVariation("batteryLife", "The life of a particular brand of watch battery is normally distributed with mean #mu##sub1# = #mean1(1000:1300)# days and standard deviation #sigma##sub1# = #sd1(40:60)# days. A second brand's battery life has a normal distribution with mean #mu##sub2# = #mean2(700:1000)# days and standard deviation #sigma##sub2# = #sd2(40:60)# days.\\n", "maxMeanParam(99999)#maxSdParam(99.999)", "If one battery of each type is simultaneously tested, what is the probability that #group-cut-offs(2:0:the life of the battery of the first brand:the life of the battery of the second brand:days:their total lifetime)#?", 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.DiffMeanProbApplet", 600, 750);

addVariation("appleWeights", "The weights of one variety of apple have a normal distribution with mean #mu# = #mean1(100:200)# grams and standard deviation #sigma# = #sd1(8:12)# grams.\\n", "maxMeanParam(9999)#maxSdParam(99.9999)", "singleOrMean(0)#If two apples are selected, what is the probability that #group-cut-offs(2.5:0:the weight of the first apple:the weight of the second apple:grams)#?|||singleOrMean(1)#If two samples of size n#sub1# = #n1(4:12)# and n#sub2# = #n2(4:12)# apples are selected, what is the probability that #group-cut-offs(2.5:0:the mean apple weight in the first sample:the mean apple weight in the second sample:grams)#?", 0);
addVariation("batteryLife", "The life of a particular brand of watch battery is normally distributed with mean #mu##sub1# = #mean1(1000:1200)# days and standard deviation #sigma##sub1# = #sd1(80:100)# days. A second brands battery life has a normal distribution with mean #mu##sub2# = #mean2(1100:1300)# days and standard deviation #sigma##sub2# = #sd2(80:100)# days.\\n", "maxMeanParam(99999)#maxSdParam(999.999)", "singleOrMean(0)#If one battery of each type is simultaneously tested, what is the probability that #group-cut-offs(2.5:0:the first brands lifetime:the second brands lifetime:days)#?|||singleOrMean(1)#If a sample of n#sub1# = #n1(4:12)# watches of the first brand and n#sub2# = #n2(4:12)# of the second brand are selected, what is the probability that #group-cut-offs(2.5:0:the mean lifetime for the first brand:the mean lifetime for the second brand:days)#?", 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.CiDiffMeanApplet", 600, 750);

addVariation("mammalWeights", "The weights of #group1Name(Male)# mammals of one species have normal distributions with mean #mu##sub1# and standard deviation #sigma##sub1#. The distribution of #group2Name(Female)# weights has parameters #mu##sub2# and #sigma##sub2#. Random samples of size n#sub1# = #n1(10:20)# and  n#sub2# = #n2(10:20)# are selected from these groups.\\n Find a #ciLevel(:)#% confidence interval for the difference between their mean weights.", "varName(Weight)#groupVarName(Sex)#units(kg)#mean1[](15,20)#mean2[](15,20)#sd1(2.0)#sd2(2.0)#axis(9 26 10 5)#maxSe(9.999)#maxPlusMinus(9.999)#maxSampleMean(15.999)#maxSampleSd(2.999)", null, 0);
addVariation("heartRates", "The resting heart rates of a random sample of n#sub1# = #n1(10:20)# adult patients with a viral infection and another n#sub2# = #n2(20:30)# healthy adults were recorded.\\n Assuming normal distributions for the heart rates, find a #ciLevel(:)#% confidence interval for the difference between the mean heart rates of infected and healthy adults.", "varName(Heart rate)#group1Name(Diseased)#group2Name(Healthy)#units(beats per minute)#mean1(72)#mean2[](72,90)#sd1(10)#sd2(10)#axis(45 120 50 10)#maxSe(99.999)#maxPlusMinus(99.999)#maxSampleMean(150.99)#maxSampleSd(20.99)", null, 0);
addVariation("packingTimes", "Two machines for packing cartons with jars are being compared. The times taken to pack n#sub1# = #n1(5:10)# cartons with the first machine and n#sub2# = #n2(20:30)# cartons using the second machine were recorded.\\n Assuming normal distributions for the packing times, find a #ciLevel(:)#% confidence interval for the difference between the mean packing times for the two machines.", "varName(Packing time)#group1Name(Machine 1)#group2Name(Machine 2)#units(sec)#mean1(42)#mean2[](40,42,44)#sd1(1)#sd2(1)#axis(37 47 38 2)#maxSe(99.999)#maxPlusMinus(9.999)#maxSampleMean(45.999)#maxSampleSd(9.999)", null, 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.TestDiffMeansApplet", 600, 800);

addVariation("mammalWeights", "A random sample of n#sub1# = #n1# male mammals of one species had weights with standard deviation s#sub1# = #sd1# kg and mean x#bar##sub1# = #mean1# kg. A similar sample of n#sub2# = #n2# females had standard deviation s#sub2# = #sd2# kg and mean x#bar##sub2# = #mean2# kg.\\nTest whether #?:string[tail](the mean weight of males is less than that of females*???*the mean weight of males is more than that of females*???*the underlying mean weights of males and females are different)#.", "tail[](0,2,4)#n1(10:20)#sd1(1.5:2.5)#mean1(15:25)#n2(10:20)#sd2(1.5:2.5)#mean2(:)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( male weights are lower*???* male weights are higher*???* male and female weights are different)", null, 0);
addVariation("heartRates", "The resting heart rates of a random sample of n#sub1# = #n1# adult patients with a viral infection had standard deviation s#sub1# = #sd1# and mean x#bar##sub1# = #mean1# beats per minute. Those of a similar sample of n#sub2# = #n2# healthy adults had standard deviation s#sub2# = #sd2# and mean x#bar##sub2# = #mean2#.\\nTest whether #?:string[tail](the mean heart rate of those with the infection is lower*???*the mean heart rate of those with the infection is higher*???*there is any difference between the mean heart rates of those with and without the infection)#.", "tail[](0,2,4)#n1(10:20)#sd1(7:13)#mean1(65:80)#n2(20:30)#sd2(7:13)#mean2(:)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( the heart rates of infected adults are lower*???* the heart rates of infected adults are higher*???* heart rates are different for the two groups)", null, 0);
addVariation("packingTimes", "Two machines for packing cartons with jars are being compared. The times taken to pack n#sub1# = #n1# cartons with the first machine had standard deviation s#sub1# = #sd1# sec and mean x#bar##sub1# = #mean1# sec. The packing times for n#sub2# = #n2# cartons packed by the second machine had standard deviation s#sub2# = #sd2# sec and mean x#bar##sub2# = #mean2# sec.\\nTest whether #?:string[tail](the first machine packs cartons more quickly*???*the first machine packs cartons more slowly*???*there is any difference between the mean packing times of the two machines)#.", "tail[](0,2,4)#n1(10:20)#sd1(7:13)#mean1(65:80)#n2(20:30)#sd2(7:13)#mean2(:)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( the first machine packs cartons more quickly*???* the first machine packs cartons more slowly*???* the packing times are different for the two machines)", null, 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.CiDiffPropnApplet", 600, 750);

addVariation("defectiveItems", "A new production method is being trialed to reduce the number of defective items produced. Out of n#sub1# = #n1[](200,250,300,400,500)# items produced by the #group1Name(Old method)#, there were x#sub1# = #x1(:)# defectives. With the #group2Name(New method)#, out of n#sub2# = #n2[](200,250,300,400,500)# items, there were x#sub2# = #x2(:)# defectives.\\nFind a #ciLevel(:)#% confidence interval for the difference between the probabilities of defectives.", "varName(prob of defective)#groupVarName(Production method)#pi1(0.10)#pi2(0.03)#seDecimals(4)#pDecimals(4)", null, 0);
addVariation("lizardSex", "A random sample of n#sub1# = #n1(50:100)# lizards of #group1Name(Species A)# contained x#sub1# = #x1(:)# males. In a different random sample of n#sub2# = #n2(50:100)# lizards of #group2Name(Species B)#, there were x#sub2# = #x2(:)# males.\\nFind a #ciLevel(:)#% confidence interval for the difference between the proportion of males in the two species.", "varName(prob of male)#groupVarName(Species)#pi1(0.3:0.6)#pi2(0.3:0.6)#seDecimals(4)#pDecimals(4)", null, 0);
addVariation("drugSideEffects", "In an assessment of the side effects of a drug, in a sample of n#sub1# = #n1(50:100)# patients who had been given the drug, there were x#sub1# = #x1(:)# who reported side effects. In a similar sample of n#sub2# = #n2(50:100)# patients who were given a placebo instead of the drug (the control group), x#sub2# = #x2(:)# reported side effects.\\nFind a #ciLevel(:)#% confidence interval for the difference between the probability of side effects in the two groups.", "group1Name(Drug group)#group2Name(Control group)#varName(prob of side effects)#groupVarName(Drug)#pi1(0.2:0.4)#pi2(0.2:0.4)#seDecimals(4)#pDecimals(4)", null, 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.TestDiffProbsApplet", 600, 950);

addVariation("lizardSex", "n#sub1# = #n1# lizards of #group1Name(Species A)# and n#sub2# = #n2# of #group2Name(Species B)# were collected in a jungle area. In the sample, there were x#sub1# = #x1(:)# males in Species A and x#sub2# = #x2(:)# males in Species B.\\nTest whether #?:string[tail](the proportion of males is less in Species A than in Species B*???*the proportion of males is higher in Species A than in Species B*???*the proportions of males in the two species are different from each other)#.", "tail[](0,2,4)#groupVarName(Species)#pi1[](0.5,0.8)##n1(40:70)##n2(40:70)#successes(:)#seDecimals(4)#pDecimals(4)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( there are fewer males in Species A*???* there are more males in Specied A*???* the proportions of males are different)", null, 0);
addVariation("drugSideEffects", "In an assessment of the side effects of a drug, in a sample of n#sub1# = #n1# patients who had been given the drug, there were x#sub1# = #x1(:)# who reported side effects. In a similar sample of n#sub2# = #n2# patients who were given a placebo instead of the drug (the control group), x#sub2# = #x2(:)# reported side effects.\\nTest whether #?:string[tail](the drug reduces the probability of side effects*???*the drug increases the probability of side effects*???*the drug affects the probability of side effects)#.", "tail[](0,2,4)#group1Name(Drug group)#group2Name(Control group)#groupVarName(Group)#pi1[](0.5,0.8)##n1(50:100)##n2(50:100)#successes(:)#seDecimals(4)#pDecimals(4)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( the drug lowers the prob of side effects*???* the drug increases the prob of side effects*???* the drug affects the prob of side effects)", null, 0);
addVariation("defectiveItems", "A factory has two production lines making plastic widgets. In #group1Name(Production line 1)#, quality control sampled n#sub1# = #n1# widgets and found that x#sub1# = #x1(:)# were defective. In a similar sample of n#sub2# = #n2# widgets from #group2Name(Production line 2)#, x#sub2# = #x2(:)# were defective.\\nTest whether #?:string[tail](production line 1 has a lower probability of defectives*???*production line 1 produces has a higher probability of defectives*???*the probability of a defective widget is different in the two production lines)#.", "tail[](0,2,4)#groupVarName(Production line)#pi1[](0.03,0.05)##n1(500:1000)##n2(500:1000)#successes(:)#seDecimals(5)#pDecimals(5)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( Production Line 1 has fewer defectives*???* Production Line 1 has more defectives*???* the lines have different probs of defectives)", null, 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.PickTestTypeApplet", 600, 700);
addCoreParam("popSampText", "A 2-sample t test#A paired t test");
addCoreParam("summaryMessage", "A 2-sample t test should be used to compare group means when you have independent samples. A paired test is needed when each sampled item in one group is associated with an item sampled from the other group.");
addCoreParam("nDescriptions", "5");
addCoreParam("title0", "Supermarket prices");
addCoreParam("scenario0", "A consumer decided to compare prices in supermarkets A and B.");
addCoreParam("popnDescription0", "20 canned items were randomly selected from supermarket A and their prices were recorded. In supermarket B, prices were found from 20 canned items were randomly selected in the same way. The prices should be compared with ...");
addCoreParam("sampleDescription0", "20 categories of canned food were picked as the focus of the comparison. The price of a randomly selected can of each type was found from supermarket A and similar prices were found from supermarket B. The prices should be compared with ...");
addCoreParam("popnMessages0", "A can selected from supermarket A is not associated with one from supermarket B since there might not be one of the same type. The data are not paired but are independent samples.");
addCoreParam("sampleMessages0", "Each of the cans selected from supermarket A is associated with one of the same type from supermarket B, making the data paired. (A paired t test takes advantage of this.)");
addCoreParam("title1", "Lamb weight");
addCoreParam("scenario1", "Researchers were interested in whether giving newborn lambs an injected vitamin supplement increases their weight gain.");
addCoreParam("popnDescription1", "30 lambs were randomly selected and given the vitamin whereas another randomly selected 30 lambs got no vitamin (the control group). The weights of all lambs were recorded after 10 weeks. The best way to assess whether the vitamin affects lamb weight is with ...");
addCoreParam("sampleDescription1", "30 sets of twin lambs were used in an experiment. In each set of twins one lamb was randomly selected to get the vitamin supplement; the other got no extra vitamin. The best way to assess whether the vitamin affects lamb weight is with  ...");
addCoreParam("popnMessages1", "Each lamb getting the vitamin is not specifically associated with one in the control group so the data are not paired. The data are independent samples.");
addCoreParam("sampleMessages1", "Each lamb getting the vitamin is associated with its twin that did not receive the supplement, making the data paired. (A paired t test takes advantage of this.)");
addCoreParam("title2", "Teaching methods");
addCoreParam("scenario2", "An educator was interested in whether a period of strenuous exercise affected performance in a mathematics test.");
addCoreParam("popnDescription2", "The 30 students in a class were randomly split into two groups. 15 of them were asked to run round a track for 10 minutes, followed by a 10 minute recovery period, then all students sat a maths test. The best way to assess whether exercise affects results is with ...");
addCoreParam("sampleDescription2", "The 30 students in one class were given a maths test. On the next day, they were asked to run round a track for 10 minutes, followed by a 10 minute recovery period, then sat a second maths test of similar level. The best way to assess whether exercise affects results is with ...");
addCoreParam("popnMessages2", "The 15 students getting the exercise are not each associated with one of the students getting no exercise so the data are not paired. The data are independent samples.");
addCoreParam("sampleMessages2", "The test results after exercise are from the same students who sat the test without exercising. This makes the data paired. (A paired t test takes advantage of this.)");
addCoreParam("title3", "Spider walking speed");
addCoreParam("scenario3", "A biologist was interested in whether praying mantis excrement affected the behaviour of wolf spiders.");
addCoreParam("popnDescription3", "Walking speeds of 24 spiders were measured over 1 hour when in a container containing filter paper; for a randomly selected 12 spiders, the filter paper was smeared with the excrement. The best way to assess whether the excrement affects walking speed is with ...");
addCoreParam("sampleDescription3", "Walking speeds of 12 spiders were measured over 1 hour when in a container containing clean filter paper. The filter paper was then smeared with the excrement and the spiders' walking speeds recorded again. The best way to assess whether the excrement affects walking speed is with ...");
addCoreParam("popnMessages3", "Different groups of spiders were in the two groups; a spider in the first group is not specifically paired with one in the second group. The data are independent samples.");
addCoreParam("sampleMessages3", "The walking speeds of the spiders exposed to the excrement are measured from the same spiders in the test without excrement. This makes the data paired. (A paired t test takes advantage of this.)");
addCoreParam("title4", "Zinc in drinking water");
addCoreParam("scenario4", "Drinking water containing high concentrations of trace metals can be a health hazard. An experiment was conducted to assess whether zinc concentration is different on the surface than in bottom water.");
addCoreParam("popnDescription4", "30 samples of water were obtained from different locations and these were randomly separated into groups of 15. In one group, zinc concentration was  measured at the surface, whereas it was measured at the bottom of the other sample. The best way to assess whether the mean concentrations are different is with ...");
addCoreParam("sampleDescription4", "Fifteen samples of water were obtained from different locations. Zinc concentration was measured at the surface and at the bottom of each sample. The best way to assess whether the mean concentrations are different is with ...");
addCoreParam("popnMessages4", "Different samples of water were in the two groups; there is no connection between any sample in the first group and one in the second group. The data are independent samples.");
addCoreParam("sampleMessages4", "The surface and bottom concentrations were measured from the same samples, making the data paired. (A paired t test takes advantage of this.)");

addVariation("generic", "Identify the appropriate test for the scenarios described below.", null, null, 0);

//----------------------------------------------

startExercise("exerciseGroupsProg.TestPairedDiffApplet", 600, 850);

addVariation("twinStudy", "A study involved #n(10:20)# items identical twins who had been raised apart. In each pair of twins, one was classified as being raised in a Better home than the other. A measurement was made from each child about an aspect of mental health.\\nTest whether the mean mental health of those in the Better homes, #mu##sub1#, is #?:string[tail](lower than*???*higher than*???*different from)# that of those from Poorer homes, #mu##sub2#.", "tail[](0,2,4)#mean1(100:150)#sd(20)#corr[](0.7)#dataDecimals(0)#seDecimals(2)#var1Name(Better)#var2Name(Poorer)#maxSampleMean(999.99)#maxSampleSd(99.99)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( the Better home mean is lower*???* the Better home mean is higher*???* Better and Poorer homes are different)#", null, 0);
addVariation("cornYields", "An agricultural researcher conducted an experiment to compare two corn varieties, A and B, using #n(10:20)# plots of land. Each plot was split into two with the two varieties randomly allocated to the two sub-plots. The yield of corn was recorded from each sub-plot in tonnes per hectare.\nTest whether the mean yield for variety A, #mu##sub1#, is #?:string[tail](lower than*???*higher than*???*different from)# that for variety B, #mu##sub2#.", "tail[](0,2,4)#mean1(5:15)#sd(1.5)#corr[](0.7)#dataDecimals(2)#seDecimals(3)#var1Name(Variety A)#var2Name(Variety B)#maxSampleMean(99.999)#maxSampleSd(99.999)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( Variety A is worse*???* Variety A is better*???* the varieties are different)#", null, 0);
addVariation("physiotherapyCharges", "A medical insurance company was concerned about charges made by two physiotherapists, A and B. A group of patients with running injuries was split into #n(30:50)# pairs with the injured runners in each pair assessed to have similar injuries. In each pair, one person was randomly sent to A and the other to B. The total treatment cost in $ from each runner was recorded.\\nTest whether the charge from physiotherapist A, #mu##sub1#, is #?:string[tail](lower than*???*higher than*???*different from)# that for physiotherapist B, #mu##sub2#.", "tail[](0,2,4)#mean1(800)#sd(200)#corr[](0.7)#dataDecimals(0)#seDecimals(1)#var1Name(Physio A)#var2Name(Physio B)#maxSampleMean(9999.99)#maxSampleSd(999.99)#conclusions(There_is_no_evidence_that There_is_only_weak_evidence_that There_is_moderately_strong_evidence_that There_is_very_strong_evidence_that It_is_almost_certain_that)#conclusionEnding[tail]( Physio B charges more*???* Physio B charges less*???* there is a difference between the physios)#", null, 0);

//----------------------------------------------

