
addBook('bk/massey100', 'book_splash', "About this CAST e-book");

addChapter('bk/general', 'ch_preface', "Preface", null, 'v_ch_preface');
addSection('bk/general', 'sec_aboutCast', "About CAST");
addPage_2('en/aboutCast', 'aboutCast1', "What is CAST?", 'static');
addPage_2('en/aboutCast', 'aboutCast2', "Structure and navigation", 'static');
addPage_2('en/aboutCast', 'aboutCast3', "Copyright and licence", 'static');
addPage_2('en/aboutCast', 'aboutCast4', "Acknowledgements", 'static');
addPage_2('en/aboutCast', 'aboutCast5', "About the author", 'static');
addSection('bk/general', 'sec_otherInfo', "Other Information");
addPage_2('en/otherInfo', 'otherInfo1', "Browsers and Java", 'static');
addPage_2('en/otherInfo', 'otherInfo2', "Problems?", 'static');
addPage_2('en/otherInfo', 'otherInfo3', "Printing", 'static');
addPage_2('en/otherInfo', 'otherInfo4', "Recent changes to CAST", 'static');
addPage_2('en/otherInfo', 'otherInfo5', "Possible future developments", 'static');

addChapter('bk/massey100', 'ch_dataDistns', "Data and Distributions");
addSection('bk/general', 'sec_context', "Context");
addPage_2('en/context', 'context1', "Importance of context", 'static', 'en/context', 's_context1');
addPage_2('en/context', 'context2', "Statistics", 'static', 'en/context', 's_context2');
addPage_2('en/context', 'context3', "The statistical process", 'static', 'en/context', 's_context3');
addSection('bk/massey100', 'sec_structures', "Standard data structures");
addPage_2('en/structures', 'structures1', "Variables and individuals", 'interact', 'en/structures', 's_structures1');
addPage_2('en/structures', 'structures2', "Types of variable", 'interact', 'en/structures', 's_structures2');
addPage_2('en/structures', 'structures3', "Categorical variables and groups", 'interact', 'en/structures', 's_structures3');
addSection('bk/general', 'sec_variation', "Variation");
addPage_2('en/variation', 'variation1', "Signal and noise", 'interact', 'en/variation', 's_variation1');
addPage_2('en/variation', 'variation2', "Natural variability", 'interact', 'en/variation', 's_variation2');
addPage_2('en/variation', 'variation3', "Variability caused by experiments", 'interact', 'en/variation', 's_variation3');
addPage_2('en/variation', 'variation4', "Variability in survey data", 'interact', 'en/variation', 's_variation4');
addPage_2('en/variation', 'variation5', "Explained and unexplained variation", 'static', 'en/variation', 's_variation5');
addPage_2('en/variation', 'variation6', "Predicting future variation", 'static', 'en/variation', 's_variation6');
addSection('bk/massey100', 'sec_valueDisplay', "Graphical display of values");
addPage_2('en/valueDisplay', 'valueDisplay1', "Analysing variation", 'interact', 'en/valueDisplay', 's_valueDisplay1');
addPage_2('en/valueDisplay', 'valueDisplay2', "Basic dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay2');
addPage_2('en/valueDisplay', 'valueDisplay3', "Jittered dot plot", 'interact', 'en/valueDisplay', 's_valueDisplay3');
addPage_2('en/valueDisplay', 'valueDisplay4', "Stacked dot plots", 'interact', 'en/valueDisplay', 's_valueDisplay4');
addPage_2('en/valueDisplay', 'valueDisplay5', "Stem and leaf plots", 'interact', 'en/valueDisplay', 's_valueDisplay5');
addPage_2('en/valueDisplay', 'valueDisplay6', "Splitting the stems", 'interact', 'en/valueDisplay', 's_valueDisplay6');
addSection('bk/massey100', 'sec_density', "Histograms and density");
addPage_2('en/density', 'density1', "Density of values", 'static', 'en/density', 's_density1');
addPage_2('en/density', 'density2', "Histogram with equal class widths", 'interact', 'en/density', 's_density2');
addPage_2('en/density', 'density3', "Choice of classes", 'interact', 'en/density', 's_density3');
addPage_2('en/density', 'density4', "Histograms of small data sets", 'interact', 'en/density', 's_density4');
addPage_2('en/density', 'density5', "Relative frequency and area", 'interact', 'en/density', 's_density5');
addPage_2('en/density', 'density6', "Comparing groups", 'interact', 'en/density', 's_density6');
addPage_2('en/density', 'density7', "Histograms with varying class widths", 'interact', 'en/density', 's_density7');
addPage_2('en/density', 'density8', "Understanding histograms", 'interact', 'en/density', 's_density8');
addSection('bk/massey100', 'sec_counts', "Discrete data (counts)");
addPage_2('en/counts', 'counts1', "Discrete and continuous data", 'interact', 'en/counts', 's_counts1');
addPage_2('en/counts', 'counts2', "Histograms for counts", 'interact', 'en/counts', 's_counts2');
addPage_2('en/counts', 'counts3', "Bar charts", 'interact', 'en/counts', 's_counts3');
addSection('bk/massey100', 'sec_univarCat', "Displaying categorical values");
addPage_2('en/freqTable', 'freqTable1', "Frequency tables", 'interact', 'en/freqTable', 's_freqTable1');
addPage_2('en/freqTable', 'freqTable2', "Proportions and percentages", 'interact', 'en/freqTable', 's_freqTable2');
addPage_2('en/univarCat', 'univarCat1', "Bar charts", 'interact', 'en/univarCat', 's_univarCat1');
addPage_2('en/univarCat', 'univarCat2', "Pareto diagrams", 'interact', 'en/univarCat', 's_univarCat2');
addPage_2('en/univarCat', 'univarCat4', "Stacked bar charts and pie charts", 'interact', 'en/univarCat', 's_univarCat4');
addSection('bk/massey100', 'sec_normalDistn', "Normal distributions");
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6');
addPage_2('en/normalDistn', 'normalDistn1', "Importance of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn1');
addPage_2('en/normalDistn', 'normalDistn2', "Shape of normal distributions", 'interact', 'en/normalDistn', 's_normalDistn2');
addPage_2('en/normalDistn', 'normalDistn3', "Sketching a normal distribution", 'interact', 'en/normalDistn', 's_normalDistn3');
addPage_2('en/normalDistn', 'normalDistn4', "Some normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn4');
addPage_2('en/normalDistn', 'normalDistn5', "Z-scores", 'interact', 'en/normalDistn', 's_normalDistn5');
addPage_2('en/normalDistn', 'normalDistn6', "Finding normal probabilities", 'interact', 'en/normalDistn', 's_normalDistn6');
addPage_2('en/normalDistn', 'normalDistn7', "Other probabilities", 'interact', 'en/normalDistn', 's_normalDistn7');
addPage_2('en/normalDistn', 'normalDistn8', "Normal tables", 'static', 'en/normalDistn', 's_normalDistn8');
addPage_2('en/normalDistn', 'normalDistn9', "Finding normal quantiles", 'interact', 'en/normalDistn', 's_normalDistn9');

addChapter('bk/massey100', 'ch_numSummaries', "Numerical Summary Measures");
addSection('bk/massey100', 'sec_boxPlot', "Box plots");
addPage_2('en/boxPlot', 'boxPlot1', "The need to summarise", 'static', 'en/boxPlot', 's_boxPlot1');
addPage_2('en/boxPlot', 'boxPlot2', "Median, quartiles and box plot", 'interact', 'en/boxPlot', 's_boxPlot2');
addPage_2('en/boxPlot', 'boxPlot3', "Interpreting a box plot's shape", 'interact', 'en/boxPlot', 's_boxPlot3');
addPage_2('en/boxPlot', 'boxPlot4', "Displaying outliers", 'interact', 'en/boxPlot', 's_boxPlot4');
addPage_2('en/boxPlot', 'boxPlot6', "Comparison of groups", 'interact', 'en/boxPlot', 's_boxPlot6');
addSection('bk/general', 'sec_centerSpread', "Describing centre and spread");
addPage_2('en/centerSpread', 'centerSpread1', "Centre and spread", 'static', 'en/centerSpread', 's_centerSpread1');
addPage_2('en/centerSpread', 'centerSpread2', "Median, range and IQR", 'interact', 'en/centerSpread', 's_centerSpread2');
addPage_2('en/centerSpread', 'centerSpread3', "Summaries of centre", 'interact', 'en/centerSpread', 's_centerSpread3');
addPage_2('en/centerSpread', 'centerSpread4', "Properties of median and mean", 'interact', 'en/centerSpread', 's_centerSpread4');
addPage_2('en/centerSpread', 'centerSpread5', "Standard deviation", 'interact', 'en/centerSpread', 's_centerSpread5');
addPage_2('en/centerSpread', 'centerSpread6', "Rules of thumb for st devn", 'static', 'en/centerSpread', 's_centerSpread6');
addPage_2('en/centerSpread', 'centerSpread7', "Understanding means and st devns", 'interact', 'en/centerSpread', 's_centerSpread7');
addPage_2('en/centerSpread', 'centerSpread8', "Warnings about mean &amp; st devn", 'static', 'en/centerSpread', 's_centerSpread8');
addSection('bk/massey100', 'sec_countSummary', "Discrete data (counts)");
addPage_2('en/counts', 'counts4', "Mean and st devn", 'static', 'en/counts', 's_counts4');

addChapter('bk/massey100', 'ch_bivar', "Bivariate Data &amp; Distributions");
addSection('bk/general', 'sec_scatterplot', "Scatterplots");
addPage_2('en/scatterplot', 'scatterplot1', "More than one variable", 'interact', 'en/scatterplot', 's_scatterplot1');
addPage_2('en/scatterplot', 'scatterplot2', "Scatterplots", 'interact', 'en/scatterplot', 's_scatterplot2');
addPage_2('en/scatterplot', 'scatterplot3', "Limitations of univariate displays", 'interact', 'en/scatterplot', 's_scatterplot3');
addPage_2('en/scatterplot', 'scatterplot4', "Marginal distributions", 'interact', 'en/scatterplot', 's_scatterplot4');
addPage_2('en/scatterplot', 'scatterplot5', "Time series", 'interact', 'en/scatterplot', 's_scatterplot5');
addSection('bk/general', 'sec_relationship', "Understanding relationships");
addPage_2('en/relationship', 'relationship1', "Strength of a relationship", 'interact', 'en/relationship', 's_relationship1');
addPage_2('en/relationship', 'relationship2', "Outliers", 'interact', 'en/relationship', 's_relationship2');
addPage_2('en/relationship', 'relationship3', "Clusters", 'interact', 'en/relationship', 's_relationship3');
addPage_2('en/relationship', 'relationship4', "Dangers of over-interpretation", 'interact', 'en/relationship', 's_relationship4');
addPage_2('en/relationship', 'relationship5', "Explanatory and response variables", 'static', 'en/relationship', 's_relationship5');
addSection('bk/general', 'sec_correlation', "Correlation");
addPage_2('en/correlation', 'correlation1', "Units for X and Y", 'interact', 'en/correlation', 's_correlation1');
addPage_2('en/correlation', 'correlation2', "Units-free variables (z-scores)", 'interact', 'en/correlation', 's_correlation2');
addPage_2('en/correlation', 'correlation3', "Correlation coefficient", 'interact', 'en/correlation', 's_correlation3');
addPage_2('en/correlation', 'correlation4', "Scatterplots and the value of r", 'interact', 'en/correlation', 's_correlation4');
addPage_2('en/correlation', 'correlation5', "Nonlinear relationships", 'interact', 'en/correlation', 's_correlation5');
addPage_2('en/correlation', 'correlation6', "R does not tell the whole story", 'interact', 'en/correlation', 's_correlation6');
addSection('bk/general', 'sec_leastSqrs', "Least squares");
addPage_2('en/leastSqrs', 'leastSqrs1', "Predicting Y from X", 'interact', 'en/leastSqrs', 's_leastSqrs1');
addPage_2('en/leastSqrs', 'leastSqrs2', "Linear models", 'interact', 'en/leastSqrs', 's_leastSqrs2');
addPage_2('en/leastSqrs', 'leastSqrs3', "Fitted values and residuals", 'interact', 'en/leastSqrs', 's_leastSqrs3');
addPage_2('en/leastSqrs', 'leastSqrs4', "Least squares", 'interact', 'en/leastSqrs', 's_leastSqrs4');
addPage_2('en/leastSqrs', 'leastSqrs5', "Curvature and outliers", 'interact', 'en/leastSqrs', 's_leastSqrs5');
addPage_2('en/leastSqrs', 'leastSqrs6', "Residual plots", 'interact', 'en/leastSqrs', 's_leastSqrs6');
addPage_2('en/leastSqrs', 'leastSqrs7', "Predicting Y and predicting X", 'interact', 'en/leastSqrs', 's_leastSqrs7');
addSection('bk/general', 'sec_curvature', "Nonlinear relationships");
addPage_2('en/curvature', 'curvature1', "Transformations and correlation", 'interact', 'en/curvature', 's_curvature1');
addPage_2('en/curvature', 'curvature2', "Transformations and models", 'interact', 'en/curvature', 's_curvature2');
addPage_2('en/curvature', 'curvature3', "Quadratic models", 'interact', 'en/curvature', 's_curvature3');
addPage_2('en/curvature', 'curvature4', "Dangers of extrapolation", 'interact', 'en/curvature', 's_curvature4');

addChapter('bk/massey100', 'ch_dataCollect', "Obtaining Data");
addSection('bk/general', 'sec_popSamp', "Finite populations");
addPage_2('en/popSamp', 'popSamp1', "Census or sample?", 'interact', 'en/popSamp', 's_popSamp1');
addPage_2('en/popSamp', 'popSamp2', "Variability in a sample", 'interact', 'en/popSamp', 's_popSamp2');
addPage_2('en/popSamp', 'popSamp3', "Sampling error", 'interact', 'en/popSamp', 's_popSamp3');
addPage_2('en/popSamp', 'popSamp4', "Sampling error and sample size", 'interact', 'en/popSamp', 's_popSamp4');
addPage_2('en/popSamp', 'popSamp5', "Sampling from finite populations", 'interact', 'en/popSamp', 's_popSamp5');
addPage_2('en/popSamp', 'popSamp6', "Selecting a random sample", 'interact', 'en/popSamp', 's_popSamp6');
addSection('bk/general', 'sec_infPopn', "Samples from distributions");
addPage_2('en/infPopn', 'infPopn1', "Data as representatives", 'static', 'en/infPopn', 's_infPopn1');
addPage_2('en/infPopn', 'infPopn2', "Randomness of data", 'interact', 'en/infPopn', 's_infPopn2');
addPage_2('en/infPopn', 'infPopn3', "Model to explain randomness", 'static', 'en/infPopn', 's_infPopn3');
addPage_2('en/infPopn', 'infPopn4', "Infinite populations (distributions)", 'interact', 'en/infPopn', 's_infPopn4');
addPage_2('en/infPopn', 'infPopn5', "Information from a sample", 'interact', 'en/infPopn', 's_infPopn5');
addSection('bk/general', 'sec_probDensity', "Probability &amp; probability density");
addPage_2('en/probDensity', 'probDensity1', "Finite populations", 'interact', 'en/probDensity', 's_probDensity1');
addPage_2('en/probDensity', 'probDensity2', "Probabilities with infinite populations", 'interact', 'en/probDensity', 's_probDensity2');
addPage_2('en/probDensity', 'probDensity3', "Bar charts of discrete probabilities", 'interact', 'en/probDensity', 's_probDensity3');
addPage_2('en/probDensity', 'probDensity4', "Probability density functions", 'interact', 'en/probDensity', 's_probDensity4');
addPage_2('en/probDensity', 'probDensity5', "Normal distributions", 'interact', 'en/probDensity', 's_probDensity5');
addPage_2('en/probDensity', 'probDensity6', "Probability and area under the pdf", 'interact', 'en/probDensity', 's_probDensity6');
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7');
addSection('bk/general', 'sec_sampPractice', "Sampling in practice");
addPage_2('en/sampPractice', 'sampPractice1', "Stratified sampling", 'interact', 'en/sampPractice', 's_sampPractice1');
addPage_2('en/sampPractice', 'sampPractice2', "Cluster sampling", 'interact', 'en/sampPractice', 's_sampPractice2');
addPage_2('en/sampPractice', 'sampPractice3', "Two-stage sampling", 'interact', 'en/sampPractice', 's_sampPractice3');
addPage_2('en/sampPractice', 'sampPractice4', "Sampling and non-sampling errors", 'static', 'en/sampPractice', 's_sampPractice4');
addPage_2('en/sampPractice', 'sampPractice5', "Coverage and non-response errors", 'static', 'en/sampPractice', 's_sampPractice5');
addPage_2('en/sampPractice', 'sampPractice6', "Interviewer and instrument errors", 'interact', 'en/sampPractice', 's_sampPractice6');
addPage_2('en/sampPractice', 'sampPractice7', "Survey design issues", 'static', 'en/sampPractice', 's_sampPractice7');
addSection('bk/general', 'sec_causal', "Association &amp; causal relationships");
addPage_2('en/causal', 'causal1', "Interest in relationships", 'static', 'en/causal', 's_causal1');
addPage_2('en/causal', 'causal2', "Causal and non-causal relationships", 'static', 'en/causal', 's_causal2');
addPage_2('en/causal', 'causal3', "Detecting causal relationships", 'static', 'en/causal', 's_causal3');
addPage_2('en/causal', 'causal4', "Observational and experimental data", 'interact', 'en/causal', 's_causal4');
addPage_2('en/causal', 'causal5', "Data collection and causality", 'interact', 'en/causal', 's_causal5');
addSection('bk/general', 'sec_designIntro', "Principles of experimental design");
addPage_2('en/designIntro', 'designIntro1', "Experiments and treatments", 'static', 'en/designIntro', 's_designIntro1');
addPage_2('en/designIntro', 'designIntro2', "Variable experimental units", 'interact', 'en/designIntro', 's_designIntro2');
addPage_2('en/designIntro', 'designIntro3', "A badly designed experiment", 'interact', 'en/designIntro', 's_designIntro3');
addPage_2('en/designIntro', 'designIntro4', "Confounding", 'static', 'en/designIntro', 's_designIntro4');
addPage_2('en/designIntro', 'designIntro5', "Randomisation", 'interact', 'en/designIntro', 's_designIntro5');
addPage_2('en/designIntro', 'designIntro6', "Replication", 'static', 'en/designIntro', 's_designIntro6');
addPage_2('en/designIntro', 'designIntro7', "Blocking", 'interact', 'en/designIntro', 's_designIntro7');
addSection('bk/general', 'sec_designPrelim', "Practical issues in design");
addPage_2('en/designPrelim', 'designPrelim1', "Purpose", 'static', 'en/designPrelim', 's_designPrelim1');
addPage_2('en/designPrelim', 'designPrelim2', "Experimental units and measurements", 'static', 'en/designPrelim', 's_designPrelim2');
addPage_2('en/designPrelim', 'designPrelim3', "Experiments with human subjects", 'static', 'en/designPrelim', 's_designPrelim3');

addChapter('bk/massey100', 'ch_probSamp', "Probability &amp; Sampling Distns");
addSection('bk/massey100', 'sec_probDensity', "Probability and probability density");
addPage_2('en/probDensity', 'probDensity7', "Properties of probability", 'static', 'en/probDensity', 's_probDensity7');
addSection('bk/general', 'sec_groupedCat', "Comparing groups");
addPage_2('en/groupedCat', 'groupedCat1', "Contingency tables", 'interact', 'en/groupedCat', 's_groupedCat1');
addPage_2('en/groupedCat', 'groupedCat2', "Contingency table examples", 'static', 'en/groupedCat', 's_groupedCat2');
addPage_2('en/groupedCat', 'groupedCat3', "Bar charts using proportions", 'interact', 'en/groupedCat', 's_groupedCat3');
addPage_2('en/groupedCat', 'groupedCat4', "Stacked bar charts", 'interact', 'en/groupedCat', 's_groupedCat4');
addPage_2('en/groupedCat', 'groupedCat5', "Two special cases", 'interact', 'en/groupedCat', 's_groupedCat5');
addSection('bk/general', 'sec_bivarCat', "Bivariate categorical distributions");
addPage_2('en/bivarCat', 'bivarCat1', "Relationships between variables", 'static', 'en/bivarCat', 's_bivarCat1');
addPage_2('en/bivarCat', 'bivarCat2', "3-dimensional bar charts", 'interact', 'en/bivarCat', 's_bivarCat2');
addPage_2('en/bivarCat', 'bivarCat3', "Clustered bar charts", 'interact', 'en/bivarCat', 's_bivarCat3');
addPage_2('en/bivarCat', 'bivarCat4', "Marginal distributions", 'interact', 'en/bivarCat', 's_bivarCat4');
addPage_2('en/bivarCat', 'bivarCat5', "Conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat5');
addPage_2('en/bivarCat', 'bivarCat6', "More about conditional distributions", 'interact', 'en/bivarCat', 's_bivarCat6');
addPage_2('en/bivarCat', 'bivarCat7', "Conditional vs marginal distns", 'interact', 'en/bivarCat', 's_bivarCat7');
addSection('bk/general', 'sec_prob', "Probability and applications");
addPage_2('en/prob', 'prob1', "Joint probabilities", 'interact', 'en/prob', 's_prob1');
addPage_2('en/prob', 'prob2', "Marginal probabilities", 'interact', 'en/prob', 's_prob2');
addPage_2('en/prob', 'prob3', "Conditional probabilities", 'interact', 'en/prob', 's_prob3');
addPage_2('en/prob', 'prob4', "Graphical display of probabilities", 'interact', 'en/prob', 's_prob4');
addPage_2('en/prob', 'prob5', "Calculations with probabilities", 'interact', 'en/prob', 's_prob5');
addSection('bk/general', 'sec_randomMean', "Distribution of sample mean");
addPage_2('en/randomMean', 'randomMean1', "Parameters and statistics", 'interact', 'en/randomMean', 's_randomMean1');
addPage_2('en/randomMean', 'randomMean2', "Variability of sample mean", 'interact', 'en/randomMean', 's_randomMean2');
addPage_2('en/randomMean', 'randomMean3', "Standard devn of sample mean", 'interact', 'en/randomMean', 's_randomMean3');
addPage_2('en/randomMean', 'randomMean4', "Means from normal populations", 'interact', 'en/randomMean', 's_randomMean4');
addPage_2('en/randomMean', 'randomMean5', "Large-sample normality of means", 'interact', 'en/randomMean', 's_randomMean5');
addPage_2('en/randomMean', 'randomMean6', "Distribution of mean from a sample", 'static', 'en/randomMean', 's_randomMean6');
addPage_2('en/randomMean', 'randomMean7', "Requirement of independence", 'interact', 'en/randomMean', 's_randomMean7');
addPage_2('en/randomMean', 'randomMean8', "Sampling from finite populations", 'interact', 'en/randomMean', 's_randomMean8');
addSection('bk/general', 'sec_randomPropn', "Distribution of sample proportion");
addPage_2('en/randomPropn', 'randomPropn1', "Proportion and probability", 'interact', 'en/randomPropn', 's_randomPropn1');
addPage_2('en/randomPropn', 'randomPropn2', "Properties of counts and proportions", 'interact', 'en/randomPropn', 's_randomPropn2');
addPage_2('en/randomPropn', 'randomPropn3', "Binomial distribution", 'interact', 'en/randomPropn', 's_randomPropn3');
addPage_2('en/randomPropn', 'randomPropn4', "Binomial probability examples", 'static', 'en/randomPropn', 's_randomPropn4');
addPage_2('en/randomPropn', 'randomPropn5', "Normal approximation to binomial", 'interact', 'en/randomPropn', 's_randomPropn5');
addPage_2('en/randomPropn', 'randomPropn6', "Normal approximation examples", 'static', 'en/randomPropn', 's_randomPropn6');

addChapter('bk/massey100', 'ch_quality', "Quality and Reliability");
addSection('bk/general', 'sec_controlChart', "Control charts");
addPage_2('en/controlChart', 'controlChart1', "Introduction", 'static', 'en/controlChart', 's_controlChart1');
addPage_2('en/controlChart', 'controlChart2', "Run charts", 'interact', 'en/controlChart', 's_controlChart2');
addPage_2('en/controlChart', 'controlChart3', "Control limits", 'interact', 'en/controlChart', 's_controlChart3');
addPage_2('en/controlChart', 'controlChart4', "Other signals of being out-of-control", 'interact', 'en/controlChart', 's_controlChart4');
addPage_2('en/controlChart', 'controlChart5', "False alarms", 'interact', 'en/controlChart', 's_controlChart5');
addPage_2('en/controlChart', 'controlChart6', "Examples of run charts", 'interact', 'en/controlChart', 's_controlChart6');
addPage_2('en/controlChart', 'controlChart7', "Control charts for means", 'interact', 'en/controlChart', 's_controlChart7');
addPage_2('en/controlChart', 'controlChart8', "Control charts for ranges", 'interact', 'en/controlChart', 's_controlChart8');
addPage_2('en/controlChart', 'controlChart9', "Finding the cause of problems", 'interact', 'en/controlChart', 's_controlChart9');

addChapter('bk/massey100', 'ch_est', "Estimation");
addSection('bk/general', 'sec_estIntro', "Introduction to estimation");
addPage_2('en/estIntro', 'estIntro1', "Interest in populations", 'static', 'en/estIntro', 's_estIntro1');
addPage_2('en/estIntro', 'estIntro2', "Interest in parameters", 'static', 'en/estIntro', 's_estIntro2');
addPage_2('en/estIntro', 'estIntro3', "Applications of estimation", 'static', 'en/estIntro', 's_estIntro3');
addPage_2('en/estIntro', 'estIntro4', "Estimation error", 'static', 'en/estIntro', 's_estIntro4');
addPage_2('en/estIntro', 'estIntro5', "Distribution of errors", 'interact', 'en/estIntro', 's_estIntro5');
addPage_2('en/estIntro', 'estIntro6', "Standard error and bias", 'static', 'en/estIntro', 's_estIntro6');
addPage_2('en/estIntro', 'estIntro7', "Interval estimates", 'static', 'en/estIntro', 's_estIntro7');
addSection('bk/general', 'sec_seMean', "Standard error of mean");
addPage_2('en/seMean', 'seMean1', "Error distribution for mean", 'interact', 'en/seMean', 's_seMean1');
addPage_2('en/seMean', 'seMean2', "Standard error when \u03c3 is known", 'interact', 'en/seMean', 's_seMean2');
addPage_2('en/seMean', 'seMean3', "Interpreting the standard error", 'static', 'en/seMean', 's_seMean3');
addPage_2('en/seMean', 'seMean4', "Standard error when \u03c3 is unknown", 'static', 'en/seMean', 's_seMean4');
addPage_2('en/seMean', 'seMean5', "Standard error vs standard deviation", 'interact', 'en/seMean', 's_seMean5');
addPage_2('en/seMean', 'seMean6', "Using SEs to compare estimators", 'interact', 'en/seMean', 's_seMean6');
addPage_2('en/seMean', 'seMean7', "More about bias", 'interact', 'en/seMean', 's_seMean7');
addSection('bk/general', 'sec_ciMean', "Confidence interval for mean");
addPage_2('en/ciMean', 'ciMean1', "Confidence interval from standard error", 'static', 'en/ciMean', 's_ciMean1');
addPage_2('en/ciMean', 'ciMean2', "Confidence interval for mean, known \u03c3", 'interact', 'en/ciMean', 's_ciMean2');
addPage_2('en/ciMean', 'ciMean3', "Confidence level", 'interact', 'en/ciMean', 's_ciMean3');
addPage_2('en/ciMean', 'ciMean4', "Confidence level if \u03c3 is replaced by s", 'interact', 'en/ciMean', 's_ciMean4');
addPage_2('en/ciMean', 'ciMean5', "Confidence interval for mean, unknown \u03c3", 'interact', 'en/ciMean', 's_ciMean5');
addPage_2('en/ciMean', 'ciMean6', "Properties of 95% confidence interval", 'interact', 'en/ciMean', 's_ciMean6');
addPage_2('en/ciMean', 'ciMean7', "Examples", 'static', 'en/ciMean', 's_ciMean7');
addSection('bk/general', 'sec_estPropn', "Estimating proportions");
addPage_2('en/estPropn', 'estPropn1', "General framework for estimation", 'static', 'en/estPropn', 's_estPropn1');
addPage_2('en/estPropn', 'estPropn2', "Estimating a proportion", 'interact', 'en/estPropn', 's_estPropn2');
addPage_2('en/estPropn', 'estPropn3', "Error distribution", 'interact', 'en/estPropn', 's_estPropn3');
addPage_2('en/estPropn', 'estPropn4', "Normal approximation to error distribution", 'interact', 'en/estPropn', 's_estPropn4');
addPage_2('en/estPropn', 'estPropn5', "Confidence interval for proportion", 'static', 'en/estPropn', 's_estPropn5');
addPage_2('en/estPropn', 'estPropn6', "Properties of 95% CI for proportion", 'interact', 'en/estPropn', 's_estPropn6');
addPage_2('en/estPropn', 'estPropn7', "Confidence interval examples", 'static', 'en/estPropn', 's_estPropn7');
addSection('bk/general', 'sec_ciExtra', "More about estimation");
addPage_2('en/ciExtra', 'ciExtra1', "Margin of error", 'interact', 'en/ciExtra', 's_ciExtra1');
addPage_2('en/ciExtra', 'ciExtra2', "Sample size for estimating mean", 'interact', 'en/ciExtra', 's_ciExtra2');
addPage_2('en/ciExtra', 'ciExtra3', "Sample size for estimating proportion", 'interact', 'en/ciExtra', 's_ciExtra3');
addPage_2('en/ciExtra', 'ciExtra4', "Other confidence levels", 'interact', 'en/ciExtra', 's_ciExtra4');
addSection('bk/general', 'sec_twoGroupModel', "Models for two groups");
addPage_2('en/twoGroupModel', 'twoGroupModel1', "Interest in underlying population", 'static', 'en/twoGroupModel', 's_twoGroupModel1');
addPage_2('en/twoGroupModel', 'twoGroupModel2', "Model for two groups", 'interact', 'en/twoGroupModel', 's_twoGroupModel2');
addPage_2('en/twoGroupModel', 'twoGroupModel3', "Parameters of the normal model", 'interact', 'en/twoGroupModel', 's_twoGroupModel3');
addPage_2('en/twoGroupModel', 'twoGroupModel4', "Parameter estimates", 'interact', 'en/twoGroupModel', 's_twoGroupModel4');
addPage_2('en/twoGroupModel', 'twoGroupModel5', "Difference between means", 'interact', 'en/twoGroupModel', 's_twoGroupModel5');
addSection('bk/massey100', 'sec_twoGroupCi', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'twoGroupInf1', "Distn of difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf1');
addPage_2('en/twoGroupInf', 'twoGroupInf2', "SE of difference between means", 'static', 'en/twoGroupInf', 's_twoGroupInf2');
addPage_2('en/twoGroupInf', 'twoGroupInf3', "CI for difference between means", 'interact', 'en/twoGroupInf', 's_twoGroupInf3');
addSection('bk/massey100', 'sec_twoGroupPropnCi', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'twoGroupPropn1', "Modelling two proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn1');
addPage_2('en/twoGroupPropn', 'twoGroupPropn2', "Distribution of difference in proportions", 'interact', 'en/twoGroupPropn', 's_twoGroupPropn2');
addPage_2('en/twoGroupPropn', 'twoGroupPropn3', "CI for difference in proportions", 'static', 'en/twoGroupPropn', 's_twoGroupPropn3');
addSection('bk/massey100', 'sec_pairedCi', "Paired data");
addPage_2('en/testPaired', 'testPaired1', "Paired data", 'static', 'en/testPaired', 's_testPaired1');
addPage_2('en/testPaired', 'testPaired2', "Analysis of differences", 'interact', 'en/testPaired', 's_testPaired2');

addChapter('bk/massey100', 'ch_test', "Testing Hypotheses");
addSection('bk/general', 'sec_testIntro', "Introduction to hypothesis tests");
addPage_2('en/testIntro', 'testIntro1', "Inference", 'static', 'en/testIntro', 's_testIntro1');
addPage_2('en/testIntro', 'testIntro2', "Soccer league simulation", 'interact', 'en/testIntro', 's_testIntro2');
addPage_2('en/testIntro', 'testIntro3', "Simulation to test a proportion", 'interact', 'en/testIntro', 's_testIntro3');
addPage_2('en/testIntro', 'testIntro4', "Test for a mean", 'interact', 'en/testIntro', 's_testIntro4');
addPage_2('en/testIntro', 'testIntro5', "Randomisation tests", 'interact', 'en/testIntro', 's_testIntro5');
addPage_2('en/testIntro', 'testIntro6', "Randomisation test for correlation", 'interact', 'en/testIntro', 's_testIntro6');
addPage_2('en/testIntro', 'testIntro7', "Common patterns in tests", 'static', 'en/testIntro', 's_testIntro7');
addSection('bk/general', 'sec_testPropn', "Tests about proportions");
addPage_2('en/testPropn', 'testPropn1', "Inference about parameters", 'static', 'en/testPropn', 's_testPropn1');
addPage_2('en/testPropn', 'testPropn2', "P-value for testing proportion", 'interact', 'en/testPropn', 's_testPropn2');
addPage_2('en/testPropn', 'testPropn3', "Another example", 'interact', 'en/testPropn', 's_testPropn3');
addPage_2('en/testPropn', 'testPropn4', "One- and two-tailed tests", 'interact', 'en/testPropn', 's_testPropn4');
addPage_2('en/testPropn', 'testPropn5', "Normal approximation", 'interact', 'en/testPropn', 's_testPropn5');
addPage_2('en/testPropn', 'testPropn6', "Statistical distance", 'static', 'en/testPropn', 's_testPropn6');
addPage_2('en/testPropn', 'testPropn7', "Tests based on statistical distance", 'interact', 'en/testPropn', 's_testPropn7');
addSection('bk/general', 'sec_testMean', "Tests about means");
addPage_2('en/testMean', 'testMean1', "Introduction", 'static', 'en/testMean', 's_testMean1');
addPage_2('en/testMean', 'testMean2', "Test for mean (known \u03c3)", 'static', 'en/testMean', 's_testMean2');
addPage_2('en/testMean', 'testMean3', "P-value from statistical distance", 'interact', 'en/testMean', 's_testMean3');
addPage_2('en/testMean', 'testMean4', "The t distribution", 'interact', 'en/testMean', 's_testMean4');
addPage_2('en/testMean', 'testMean5', "The t test for a mean", 'interact', 'en/testMean', 's_testMean5');
addSection('bk/massey100', 'sec_twoGroupTest', "Comparing means in two groups");
addPage_2('en/twoGroupInf', 'twoGroupInf4', "Testing a hypothesis", 'interact', 'en/twoGroupInf', 's_twoGroupInf4');
addPage_2('en/twoGroupInf', 'twoGroupInf5', "One-tailed tests for differences", 'interact', 'en/twoGroupInf', 's_twoGroupInf5');
addSection('bk/massey100', 'sec_twoGroupPropnTest', "Comparing two proportions");
addPage_2('en/twoGroupPropn', 'twoGroupPropn4', "Testing for difference in probabilities", 'static', 'en/twoGroupPropn', 's_twoGroupPropn4');
addSection('bk/massey100', 'sec_pairedTest', "Paired t test");
addPage_2('en/testPaired', 'testPaired3', "Paired t-test", 'interact', 'en/testPaired', 's_testPaired3');
addPage_2('en/testPaired', 'testPaired4', "Pairing and experimental design", 'interact', 'en/testPaired', 's_testPaired4');

addChapter('bk/massey100', 'ch_anova', "Analysis of Variance");
addSection('bk/massey100', 'sec_multiGroup', "Comparing several groups");
addPage_2('en/multiGroup', 'multiGroup1', "Model", 'interact', 'en/multiGroup', 's_multiGroup1');
addPage_2('en/multiGroup', 'multiGroup2', "Parameter estimates", 'interact', 'en/multiGroup', 's_multiGroup2');
addPage_2('en/multiGroup', 'multiGroup3', "Revisiting two groups", 'static', 'en/multiGroup', 's_multiGroup3');
addPage_2('en/multiGroup', 'multiGroup4', "Variation between and within groups", 'interact', 'en/multiGroup', 's_multiGroup4');
addPage_2('en/multiGroup', 'multiGroup5', "Sums of squares", 'interact', 'en/multiGroup', 's_multiGroup5');
addPage_2('en/multiGroup', 'multiGroup6', "Coefficient of determination", 'static', 'en/multiGroup', 's_multiGroup6');
addPage_2('en/multiGroup', 'multiGroup7', "Test for differences between groups", 'interact', 'en/multiGroup', 's_multiGroup7');
addPage_2('en/multiGroup', 'multiGroup8', "Examples", 'static', 'en/multiGroup', 's_multiGroup8');
addSection('bk/massey100', 'sec_randBlock', "Randomised blocks");
addPage_2('en/randBlock', 'randBlock1', "Generalising the idea of paired data", 'static', 'en/randBlock', 's_randBlock1');
addPage_2('en/randBlock', 'randBlock2', "Example with baseline treatment", 'interact', 'en/randBlock', 's_randBlock2');
addPage_2('en/randBlock', 'randBlock3', "Use of blocking information", 'interact', 'en/randBlock', 's_randBlock3');
addPage_2('en/randBlock', 'randBlock4', "Randomised block designs", 'interact', 'en/randBlock', 's_randBlock4');
addPage_2('en/randBlock', 'randBlock5', "Model for randomised blocks", 'interact', 'en/randBlock', 's_randBlock5');
addPage_2('en/randBlock', 'randBlock6', "Removing block effects", 'interact', 'en/randBlock', 's_randBlock6');
addPage_2('en/randBlock', 'randBlock7', "Sums of squares", 'interact', 'en/randBlock', 's_randBlock7');
addPage_2('en/randBlock', 'randBlock8', "Anova table and examples", 'static', 'en/randBlock', 's_randBlock8');

addChapter('bk/massey100', 'ch_expDesign', "Experimental Design");
addSection('bk/general', 'sec_pairBlock', "Pairing and blocks");
addPage_2('en/pairBlock', 'pairBlock1', "Aim of similar experimental units", 'interact', 'en/pairBlock', 's_pairBlock1');
addPage_2('en/pairBlock', 'pairBlock2', "Experiment with matched pairs", 'interact', 'en/pairBlock', 's_pairBlock2');
addPage_2('en/pairBlock', 'pairBlock3', "Randomisation in paired experiments", 'interact', 'en/pairBlock', 's_pairBlock3');
addPage_2('en/pairBlock', 'pairBlock4', "Matched groups of 3 or more units", 'interact', 'en/pairBlock', 's_pairBlock4');
addPage_2('en/pairBlock', 'pairBlock5', "Randomised block experiments", 'static', 'en/pairBlock', 's_pairBlock5');
addSection('bk/general', 'sec_designTwo', "Two or more factors");
addPage_2('en/designTwo', 'designTwo1', "Experiments with 2 factors", 'interact', 'en/designTwo', 's_designTwo1');
addPage_2('en/designTwo', 'designTwo2', "Factorial design", 'static', 'en/designTwo', 's_designTwo2');
addPage_2('en/designTwo', 'designTwo3', "Simple model for two factors", 'interact', 'en/designTwo', 's_designTwo3');
addPage_2('en/designTwo', 'designTwo4', "Interaction between factors", 'interact', 'en/designTwo', 's_designTwo4');
addPage_2('en/designTwo', 'designTwo5', "Example with interaction", 'interact', 'en/designTwo', 's_designTwo5');
addPage_2('en/designTwo', 'designTwo6', "No-interaction model for three factors", 'interact', 'en/designTwo', 's_designTwo6');
addPage_2('en/designTwo', 'designTwo7', "Interaction in 3-factor designs", 'interact', 'en/designTwo', 's_designTwo7');

addChapter('bk/massey100', 'ch_regn', "Regression and Correlation");
addSection('bk/general', 'sec_regnModel', "Linear regression models");
addPage_2('en/regnModel', 'regnModel1', "Interest in generalising from data", 'interact', 'en/regnModel', 's_regnModel1');
addPage_2('en/regnModel', 'regnModel2', "Distribution of Y for each X", 'interact', 'en/regnModel', 's_regnModel2');
addPage_2('en/regnModel', 'regnModel3', "Normal linear model", 'interact', 'en/regnModel', 's_regnModel3');
addPage_2('en/regnModel', 'regnModel4', "Another way to describe the model", 'interact', 'en/regnModel', 's_regnModel4');
addPage_2('en/regnModel', 'regnModel5', "Model parameters", 'interact', 'en/regnModel', 's_regnModel5');
addSection('bk/general', 'sec_regnEst', "Estimating parameters");
addPage_2('en/regnEst', 'regnEst1', "Estimating the slope and intercept", 'interact', 'en/regnEst', 's_regnEst1');
addPage_2('en/regnEst', 'regnEst2', "Estimating the error standard devn", 'interact', 'en/regnEst', 's_regnEst2');
addPage_2('en/regnEst', 'regnEst3', "Distn of least squares estimates", 'interact', 'en/regnEst', 's_regnEst3');
addPage_2('en/regnEst', 'regnEst4', "Standard error of least squares slope", 'static', 'en/regnEst', 's_regnEst4');
addPage_2('en/regnEst', 'regnEst5', "95% confidence interval for slope", 'static', 'en/regnEst', 's_regnEst5');
addPage_2('en/regnEst', 'regnEst6', "Properties of confidence interval", 'interact', 'en/regnEst', 's_regnEst6');
addPage_2('en/regnEst', 'regnEst7', "Influences on accuracy", 'interact', 'en/regnEst', 's_regnEst7');
addSection('bk/general', 'sec_regnTest', "Testing regression parameters");
addPage_2('en/regnTest', 'regnTest1', "Importance of zero slope", 'interact', 'en/regnTest', 's_regnTest1');
addPage_2('en/regnTest', 'regnTest2', "Testing whether slope is zero", 'static', 'en/regnTest', 's_regnTest2');
addPage_2('en/regnTest', 'regnTest3', "Strength of evidence and relationship", 'static', 'en/regnTest', 's_regnTest3');
addPage_2('en/regnTest', 'regnTest4', "Properties of p-values", 'interact', 'en/regnTest', 's_regnTest4');
addSection('bk/general', 'sec_regnPred', "Predicting the response");
addPage_2('en/regnPred', 'regnPred1', "Estimated response distn at X", 'interact', 'en/regnPred', 's_regnPred1');
addPage_2('en/regnPred', 'regnPred2', "Variability of estimate at X", 'interact', 'en/regnPred', 's_regnPred2');
addPage_2('en/regnPred', 'regnPred3', "Estimating the mean vs prediction", 'interact', 'en/regnPred', 's_regnPred3');
addPage_2('en/regnPred', 'regnPred4', "Confidence and prediction intervals", 'interact', 'en/regnPred', 's_regnPred4');
addSection('bk/general', 'sec_regnProblem', "Linear model assumptions");
addPage_2('en/regnProblem', 'regnProblem1', "Assumptions in a normal linear model", 'interact', 'en/regnProblem', 's_regnProblem1');
addPage_2('en/regnProblem', 'regnProblem2', "Curvature &mdash; transforming X", 'interact', 'en/regnProblem', 's_regnProblem2');
addPage_2('en/regnProblem', 'regnProblem3', "Curvature and non-constant variance", 'interact', 'en/regnProblem', 's_regnProblem3');
addPage_2('en/regnProblem', 'regnProblem4', "Transformations and prediction", 'interact', 'en/regnProblem', 's_regnProblem4');
addPage_2('en/regnProblem', 'regnProblem5', "Outliers and leverage", 'interact', 'en/regnProblem', 's_regnProblem5');
addPage_2('en/regnProblem', 'regnProblem6', "Non-normal errors", 'interact', 'en/regnProblem', 's_regnProblem6');
addPage_2('en/regnProblem', 'regnProblem7', "Correlated errors", 'interact', 'en/regnProblem', 's_regnProblem7');
addSection('bk/regn', 'sec_leastSqrsTwo', "Least squares for Y vs (X and Z)");
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo1', "More than one explanatory variable", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo2', "Three-dimensional scatterplots", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo3', "Linear equation and least squares plane", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo4', "Understanding the parameters", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo5', "Fitted values and residuals", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo6', "Estimating the parameters", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo7', "Least squares estimation", 'interact');
addPage_2('en/leastSqrsTwo', 'leastSqrsTwo8', "Interpreting the coefficients", 'interact');
addSection('bk/regn', 'sec_regnInfTwo', "Normal linear model and inference");
addPage_2('en/regnInfTwo', 'regnInfTwo1', "Normal linear model", 'interact');
addPage_2('en/regnInfTwo', 'regnInfTwo2', "Sampling variability of least squares plane", 'interact');
addPage_2('en/regnInfTwo', 'regnInfTwo3', "Distribution of estimated coefficients", 'interact');
addPage_2('en/regnInfTwo', 'regnInfTwo4', "Estimate of error standard deviation", 'interact');
addPage_2('en/regnInfTwo', 'regnInfTwo5', "95% confidence intervals for coefficients", 'interact');
addPage_2('en/regnInfTwo', 'regnInfTwo6', "Hypothesis tests for coefficients", 'interact');

var language = "en";
var logoGif = "logo_massey.gif";
var homeDir = "bk/massey100";
var versionGif = "../general/images/castGeneral";
var isLecturingVersion = false;
var isModule = false;
var hasSummaries = true;
var hasVideos = false;
var summaryPdfUrl = null;
var castWebServerUrl = "http://castBeta.massey.ac.nz";
var noOfChapters = "12";

var localVideos = true;

var fullTextString = 'Text';
var summaryTextString = 'In brief';
var videoTextString = 'Video';
var appletTextString = 'Text';
fullTabTooltip = 'Text version of page';
summaryTabTooltip = 'Summarised version of page';
videoTabTooltip = 'Version of page with videos';
appletTabTooltip = 'Text version of page with interaction';
var chapterString = 'Chapter';

var versionName = {'_g': 'General', '_b': 'Biometric', '_c': 'Business', '_m': 'Climatic', '_o': 'Official stats', '_a': 'African', '_z': 'Other'};
var versions = {};
versions['context1'] = new Array('_g', '_b', '_c', '_m', '_o');
versions['context2'] = new Array('_g', '_m', '_o');
versions['context3'] = new Array('_g', '_b');
versions['structures1'] = new Array('_g', '_a', '_b', '_c');
versions['structures2'] = new Array('_g', '_a', '_b', '_c');
versions['structures3'] = new Array('_g', '_c', '_o');
versions['variation4'] = new Array('_g', '_a');
versions['variation5'] = new Array('_g', '_c');
versions['variation6'] = new Array('_g', '_a');
versions['valueDisplay1'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay2'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay3'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay4'] = new Array('_g', '_b', '_c', '_m');
versions['valueDisplay5'] = new Array('_g', '_a', '_b', '_c', '_m');
versions['valueDisplay6'] = new Array('_g', '_c', '_m');
versions['density3'] = new Array('_g', '_c', '_m');
versions['density4'] = new Array('_g', '_b', '_c', '_m');
versions['density6'] = new Array('_g', '_b', '_c');
versions['density7'] = new Array('_g', '_b', '_c', '_m');
versions['counts1'] = new Array('_g', '_b', '_c');
versions['counts2'] = new Array('_g', '_b', '_c');
versions['counts3'] = new Array('_g', '_c');
versions['freqTable1'] = new Array('_g', '_c');
versions['freqTable2'] = new Array('_g', '_a', '_b');
versions['univarCat1'] = new Array('_g', '_a', '_b');
versions['univarCat4'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['normalDistn1'] = new Array('_g', '_c');
versions['normalDistn3'] = new Array('_g', '_b', '_c');
versions['normalDistn6'] = new Array('_g', '_b', '_c');
versions['normalDistn7'] = new Array('_g', '_b', '_c');
versions['boxPlot6'] = new Array('_g', '_c');
versions['centerSpread1'] = new Array('_g', '_b');
versions['centerSpread2'] = new Array('_g', '_b');
versions['centerSpread3'] = new Array('_g', '_b', '_c', '_m');
versions['centerSpread7'] = new Array('_g', '_c');
versions['counts4'] = new Array('_g', '_b', '_c');
versions['scatterplot1'] = new Array('_g', '_b', '_c');
versions['scatterplot2'] = new Array('_g', '_c');
versions['scatterplot4'] = new Array('_g', '_c');
versions['scatterplot5'] = new Array('_g', '_c');
versions['relationship1'] = new Array('_g', '_c');
versions['relationship3'] = new Array('_g', '_c');
versions['relationship4'] = new Array('_g', '_c');
versions['relationship5'] = new Array('_g', '_c');
versions['correlation1'] = new Array('_g', '_b', '_c');
versions['leastSqrs1'] = new Array('_g', '_b', '_c');
versions['leastSqrs3'] = new Array('_g', '_c');
versions['leastSqrs6'] = new Array('_g', '_c');
versions['leastSqrs7'] = new Array('_g', '_c');
versions['curvature1'] = new Array('_g', '_c');
versions['curvature2'] = new Array('_g', '_c');
versions['curvature3'] = new Array('_g', '_c');
versions['curvature4'] = new Array('_g', '_c');
versions['popSamp1'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp2'] = new Array('_g', '_c');
versions['popSamp3'] = new Array('_g', '_a', '_b', '_c');
versions['popSamp4'] = new Array('_g', '_b');
versions['popSamp5'] = new Array('_g', '_b', '_c');
versions['infPopn1'] = new Array('_g', '_b', '_c');
versions['infPopn2'] = new Array('_g', '_b', '_c', '_z');
versions['infPopn3'] = new Array('_g', '_b', '_c');
versions['infPopn5'] = new Array('_g', '_c');
versions['probDensity1'] = new Array('_g', '_b');
versions['probDensity2'] = new Array('_g', '_b', '_c');
versions['probDensity5'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['sampPractice1'] = new Array('_g', '_b');
versions['sampPractice5'] = new Array('_g', '_b', '_c');
versions['sampPractice6'] = new Array('_g', '_b');
versions['causal1'] = new Array('_g', '_b', '_c');
versions['causal2'] = new Array('_g', '_c');
versions['causal3'] = new Array('_g', '_b', '_c');
versions['causal4'] = new Array('_g', '_b', '_c');
versions['causal5'] = new Array('_g', '_c');
versions['designIntro1'] = new Array('_g', '_b', '_c');
versions['designIntro2'] = new Array('_g', '_c');
versions['designIntro3'] = new Array('_g', '_c');
versions['designIntro4'] = new Array('_g', '_c');
versions['designIntro5'] = new Array('_g', '_b', '_c');
versions['designIntro7'] = new Array('_g', '_c');
versions['designPrelim2'] = new Array('_g', '_c');
versions['probDensity7'] = new Array('_g', '_c');
versions['groupedCat1'] = new Array('_g', '_c');
versions['groupedCat2'] = new Array('_g', '_b', '_c');
versions['groupedCat3'] = new Array('_g', '_b', '_c');
versions['groupedCat4'] = new Array('_g', '_b', '_c');
versions['groupedCat5'] = new Array('_g', '_b', '_c');
versions['bivarCat1'] = new Array('_g', '_b', '_c');
versions['prob1'] = new Array('_g', '_b', '_c');
versions['prob2'] = new Array('_g', '_b', '_c');
versions['prob3'] = new Array('_g', '_b');
versions['prob5'] = new Array('_g', '_c');
versions['randomMean1'] = new Array('_g', '_b', '_c');
versions['randomMean6'] = new Array('_g', '_b', '_c');
versions['randomMean7'] = new Array('_g', '_b');
versions['randomPropn1'] = new Array('_g', '_c');
versions['randomPropn2'] = new Array('_g', '_c');
versions['randomPropn3'] = new Array('_g', '_b', '_c');
versions['randomPropn4'] = new Array('_g', '_b', '_c');
versions['randomPropn6'] = new Array('_g', '_b', '_c');
versions['estIntro1'] = new Array('_g', '_b', '_c');
versions['estIntro2'] = new Array('_g', '_b', '_c');
versions['estIntro3'] = new Array('_g', '_m');
versions['estIntro4'] = new Array('_g', '_c', '_m');
versions['estIntro5'] = new Array('_g', '_b', '_c');
versions['seMean1'] = new Array('_g', '_b', '_c');
versions['seMean2'] = new Array('_g', '_b');
versions['seMean3'] = new Array('_g', '_b');
versions['seMean4'] = new Array('_g', '_b', '_c');
versions['seMean6'] = new Array('_g', '_b', '_c');
versions['ciMean1'] = new Array('_g', '_c', '_m');
versions['ciMean2'] = new Array('_g', '_b');
versions['ciMean7'] = new Array('_g', '_b', '_c');
versions['estPropn1'] = new Array('_g', '_m');
versions['estPropn3'] = new Array('_g', '_b', '_c');
versions['estPropn4'] = new Array('_g', '_b', '_c');
versions['estPropn5'] = new Array('_g', '_b', '_c');
versions['estPropn7'] = new Array('_g', '_b', '_c');
versions['ciExtra1'] = new Array('_g', '_b', '_c');
versions['ciExtra2'] = new Array('_g', '_c');
versions['ciExtra3'] = new Array('_g', '_b');
versions['twoGroupModel1'] = new Array('_g', '_b', '_c');
versions['twoGroupModel2'] = new Array('_g', '_b', '_c');
versions['twoGroupModel4'] = new Array('_g', '_c');
versions['twoGroupModel5'] = new Array('_g', '_c');
versions['twoGroupInf1'] = new Array('_g', '_c');
versions['twoGroupInf2'] = new Array('_g', '_b', '_c');
versions['twoGroupInf3'] = new Array('_g', '_b', '_c');
versions['twoGroupPropn1'] = new Array('_g', '_c');
versions['twoGroupPropn3'] = new Array('_g', '_c');
versions['testPaired1'] = new Array('_g', '_b', '_c');
versions['testPaired2'] = new Array('_g', '_b', '_c');
versions['testIntro1'] = new Array('_g', '_b');
versions['testIntro3'] = new Array('_g', '_b', '_c');
versions['testIntro5'] = new Array('_g', '_b');
versions['testIntro7'] = new Array('_g', '_b', '_c');
versions['testPropn1'] = new Array('_g', '_b', '_c');
versions['testPropn2'] = new Array('_g', '_b', '_c');
versions['testPropn3'] = new Array('_g', '_b', '_c');
versions['testPropn4'] = new Array('_g', '_b', '_c');
versions['testPropn5'] = new Array('_g', '_b');
versions['testPropn7'] = new Array('_g', '_b');
versions['testMean1'] = new Array('_g', '_c');
versions['testMean2'] = new Array('_g', '_c');
versions['testMean3'] = new Array('_g', '_b');
versions['testMean4'] = new Array('_g', '_c');
versions['testMean5'] = new Array('_g', '_c');
versions['twoGroupInf4'] = new Array('_g', '_b', '_c');
versions['twoGroupInf5'] = new Array('_g', '_b', '_c');
versions['twoGroupPropn4'] = new Array('_g', '_c');
versions['testPaired3'] = new Array('_g', '_c');
versions['multiGroup1'] = new Array('_g', '_b', '_c');
versions['multiGroup3'] = new Array('_g', '_b', '_c');
versions['multiGroup4'] = new Array('_g', '_a');
versions['multiGroup6'] = new Array('_g', '_a', '_b', '_c');
versions['multiGroup7'] = new Array('_g', '_a');
versions['multiGroup8'] = new Array('_g', '_b', '_c');
versions['pairBlock5'] = new Array('_g', '_b');
versions['designTwo1'] = new Array('_g', '_b');
versions['designTwo2'] = new Array('_g', '_b');
versions['designTwo6'] = new Array('_g', '_b');
versions['regnModel1'] = new Array('_g', '_b', '_c');
versions['regnModel2'] = new Array('_g', '_c');
versions['regnModel5'] = new Array('_g', '_b', '_c');
versions['regnEst1'] = new Array('_g', '_c');
versions['regnEst2'] = new Array('_g', '_c');
versions['regnEst4'] = new Array('_g', '_c');
versions['regnEst5'] = new Array('_g', '_c');
versions['regnTest1'] = new Array('_g', '_c');
versions['regnTest2'] = new Array('_g', '_c');
versions['regnPred1'] = new Array('_g', '_b', '_c');
versions['regnPred3'] = new Array('_g', '_b', '_c');
versions['regnPred4'] = new Array('_g', '_b');
versions['regnProblem3'] = new Array('_g', '_b');
versions['regnProblem4'] = new Array('_g', '_c');
versions['regnProblem6'] = new Array('_g', '_c');

bookLoaded = true;
